### ISSUE TITLE
Enhancment

### ISSUE THREAD

**Issue by CDPotter** [MN-Script-Team/DHS-MAXIS-Scripts#1001]
It was suggested at a monthly meeting that maybe in an effort to have people checking their notices a message box that contained the recently approved notice could pop up is someone runs an approved/denied/closed script. 

This seemed a bit too much for me but maybe on that thought we could have scripts navigate to spec/wcom at the end of the scripts? We already have a message box reminding people to check their notices at the end of these scripts. 

Anyway I wanted to throw it out there and gauge interest/refine the idea.

**Comment by ruthmaloney** [comment]
It does seem excessive… Although, we have a lot of errors surrounding notices.

Ruth Maloney

**Comment by theVKC** [comment]
What does "could pop up" mean? A MsgBox? A "navigate to recent notice"? I would think that auto-navigating EVERY SINGLE TIME could be excessive, and a system strain that may not be helpful. But, it could be helpful as an _option_.

**Comment by CDPotter** [comment]
The idea was suggested that the notice's text be displayed in a message box. (naturally this would get complicated trying to find the right notice and for multiple programs and people)

I do like your idea of maybe adding a nav button on approved/denied/closed for spec/wcom?

**Comment by theVKC** [comment]
Closing due to lack of interest.
