### ISSUE TITLE
CSR script: time to split into two dialogs

### ISSUE THREAD

**Issue by theVKC** [MN-Script-Team/DHS-MAXIS-Scripts#1002]
I had a video-chat with MNPrairie today and confirmed that they are having issues viewing the CSR dialog. When I investigated it, they are using Windows 8.1 x64 Enterprise, instead of the Windows 7 x64 Enterprise that this has normally been tested on.

I tried it on my Windows 10 build, and that loaded just fine, but still... I think we need to concede defeat on the "spooky 65" issue, and just split this dialog in two. At least, to allow MNPrairie to test that.

I also confirmed they are not having problems viewing other large dialogs. With the CSR dialog in MNPrairie, it's only showing the left 100-or-so pixels of controls, and the user needs to "tab through" the rest to see them.

If anyone else has any ideas, I'd like to hear them. Otherwise, I will try and tackle this at hackathon Monday. I will have MNPrairie test it first, as well as testing a local version of the CSR script (let's just confirm it isn't something else). Assuming it works there, I will push it out statewide (just to help out any counties/agencies which may be considering a Win 8.1 upgrade).

@CDPotter and @RobertFewins-Kalb, are you familiar with any other scripts that are employing your "spooky 65" fix? Any other ideas you want me to try?

**Comment by CDPotter** [comment]
Just to add on to this two workers here are reporting the tabbing thing with the CAF script. 

Off the top of my head I'm blanking on other scripts that use it...

**Comment by RobertFewins-Kalb** [comment]
How do people feel about this...

![image](https://cloud.githubusercontent.com/assets/7842016/10046853/c2eb9c78-61d0-11e5-8616-d43c3ce32b49.png)

**Comment by RobertFewins-Kalb** [comment]
(this brings the CSR dialog under 65 objects)

**Comment by theVKC** [comment]
Not sure what you got rid of... a description of what was removed would be helpful.

**Comment by theVKC** [comment]
I can see: it looks like you got rid of the panels. For our friends using v6.x, we can't do that: MAXIS navigation can be blocked while a dialog is running, so those buttons are quite valuable. Plus accessibility.

**Comment by RobertFewins-Kalb** [comment]
dislike

**Comment by theVKC** [comment]
Your objection is noted. We need to think of accessibility concerns and the fact that several users require these buttons for longer dialogs.

**Comment by RobertFewins-Kalb** [comment]
I don't like splitting the dialog. We would be requiring users to navigate through an additional dialog just to accommodate the nav buttons. When I fix the syntax errors in the dialog code, it works just fine. I would rather keep the CSR in tact, but add comments within the code instructing script writers how to effectively

**Comment by theVKC** [comment]
What I'm saying is: it needs to be split. If you can't do it, I will. In this case, accessibility trumps other concerns.
