### ISSUE TITLE
BILS updater bug - not updating BILS

### ISSUE THREAD

**Issue by courtrightd** [MN-Script-Team/DHS-MAXIS-Scripts#1004]
Script appears to simply stop after entering new bills in the dialog and pressing ok.  Pretty sure I found the issue (panel not staying in edit mode), working on fix.

**Comment by theVKC** [comment]
Didn't we fix that? @IlseFerris?

**Comment by CDPotter** [comment]
Kirsten reported that issue this week as well. I hadn't had a chance to dig in quite yet.

**Comment by theVKC** [comment]
@IlseFerris, could this have anything at all to do with that issue you found yesterday with the order of the MAXIS_background_check being incorrect?

**Comment by IlseFerris** [comment]
This very well could be. I pulled in an updated version of the BILS Updater in with Op Doubtfire

**Comment by theVKC** [comment]
Hmmm. This is a critical bug. Can you pull the version out of Doubtfire and pull request separately?

**Comment by IlseFerris** [comment]
I'm on it!

**Comment by theVKC** [comment]
@courtrightd, can you hold off until Ilse pulls her work in?

**Comment by courtrightd** [comment]
Yep – I will wait.  The issue does seem to be from the second CHECK For MAXIS,  I have a temp fix working here by just adding a PF9 before it starts the loops to edit the panel.

**Comment by IlseFerris** [comment]
I pulled it into all 3 branches.  The issue I had yesterday in testing was the MAXIS_background_check prior to STAT/BUDG.  I moved it, and no issues since.
