### ISSUE TITLE
Cost Effective Script

### ISSUE THREAD

**Issue by MelissaFox-Stearns** [MN-Script-Team/DHS-MAXIS-Scripts#1017]
How about a script for all things CEHI? It could case note a determination (Approved, Denied or Pending verifications) and if a client is in Non-Coop. We had a macro for this in Stearns Co before scripts came out so I have some ideas of what type of fields it would cover. 
Is this something that would be used for others? Any thoughts?

**Comment by theVKC** [comment]
I like it. We have a case noter in BULK scripts, but I don't recall that it's comprehensive as you're describing. Any idea if your idea has more ideas than my idea had?

Also: do you want this one?

**Comment by MelissaFox-Stearns** [comment]
Maybe this is something specific to Stearns. We have a seperate department that determines CE and mails the reimbursement checks etc and they do not case note in Maxis. The financial workers here refer a case to that department to determine CE eligibility. The CE worker then lets the financial worker know the determination, if there are verifications needed (OHI cards, CEHI forms, etc), and if the client is in non-coop with instruction to close HC. 
Your bulk script would actually be a good script for our CEHI dept to use if they were allowed to case note. That is something I'm going to investigate.

My idea would be a script for the financial worker to case note depending on the reason. So if the a CEHI referral was done, the script could bring up a dialog to put information such as who has OHI available to them, who is on the OHI. The referral dialog could also include that a referral was sent to add a new hhld member to CEHI.  
If a CEHI determination is pending, it could bring up a dialog with what verifications are needed. It could also include who the CEHI worker is and how many times it has been requested. 
If CEHI was approved it would ask for hhld members, policy holder, Insurance type, CEHI worker, effective date, if the hhld was excluded from PMAP, and what the premium reimbursements will be. If Denied it would simply case note that it would be denied.
If  CEHI non-coop is imposed, the script would note if we closed HC for hhld member and what is needed to be in cooperation. 

Would this script make sense for other counties to use or is this a Special Stearns Situation (SSS)?  
Also, I would love to take it either way. I can write it for "in-house" use at Stearns if it doesn't make sense for others.

**Comment by theVKC** [comment]
Closing for the moment due to other priorities, per @MelissaFox-Stearns. Will reconsider opening it at a future date.
