### ISSUE TITLE
Bulk Rept-Revs error

### ISSUE THREAD

**Issue by Farleight** [MN-Script-Team/DHS-MAXIS-Scripts#1018]
The Cash coordinates are incorrect, causing Excel to error out on the Cash checks. Ln 206, Col 5 is coded as 35, but should be 34. I could probably handle this fix if somebody wants to talk me through this pull request/edit/post/etc nonsense that I've never had to deal with before.

**Comment by Farleight** [comment]
Actually, reviewing this, the issue may not be isolated to Rept - Revs.

**Comment by courtrightd** [comment]
It appears to me that the cash status is at col 35.  Is it always showing at 34 on yours?  If that is the case we will need a fix that reads  2 digits and then replace(cash_status, “ “, “”) or something.

**Comment by Farleight** [comment]
Oh, good... Yeah, it definitely shows 34 here.

**Comment by theVKC** [comment]
So... is this an issue or not? Shall I close it up?

**Comment by Farleight** [comment]
Well, it's an issue in Carlton, but if we're the only ones, I'll just update them for agency-use.

**Comment by theVKC** [comment]
We could do a "if county = you then do something different", and that could make it work in the long term... I'd prefer to go that route. Are you in, @Farleight?

**Comment by Farleight** [comment]
I am. We got swamped with pesky college kids here, and it may be a bit before I can jump on it, but I'm happy to try it out.

**Comment by theVKC** [comment]
I cannot assign this to you, but... I will assign to me and when you submit it, you become someone who I can assign future issues to, so yay. :P

**Comment by theVKC** [comment]
So in other words, you do the work but it stays in my number here to prevent others from starting it.

**Comment by theVKC** [comment]
@Farleight, can I bump this? How's it going?

**Comment by Farleight** [comment]
I was actually waiting on a reply from you to explain something to me. But to be fair, it was from while you were sick, so you may have missed it in your delirium.

I ultimately just went with Dave’s idea (above) of having it read both fields and removing the blank space because I discovered that it’s not county-specific. About half the people in Carlton have MAXIS screens where the cash field is at 34, and half are at 35. I can think of no logical reason for this, since everything else lines up and Cash is in the very middle of all of it, but MAXIS works in mysterious ways, and it is not mine to question why.

The problem is that I can’t test to see if my solution works because the Script won’t run correctly from outside the Script Files. It runs through all the screens and pulls up the Excel file but pulls over no information. Hence the question to you. Why is it doing this? What am I missing?

In theory, the solution I typed up is quite simple and should work without a hitch, but code has a way of being more complicated than anyone initially imagines, so I’d love to test it first.

**Comment by theVKC** [comment]
You probably need to manually insert your own `worker_county_code` variable for testing purposes. bulk scripts use that code pretty frequently for stuff like determining what worker to actually go to. This is normally pulled from the Global Variables file, but if you don't call that block (look at your REDIRECT files for an example), you won't hit it.

Just remember to remove said declaration before pull requesting.

**Comment by Farleight** [comment]
That worked remarkably well! Okay, I've tested this and it seems to be okay, causing no negative issues that I can see. Ready to move forward. I've never pull requested. How does one pull request?

**Comment by theVKC** [comment]
If you're ready, go ahead and issue a pull request into the master branch! You'll become lucky contributor number 20!

**Comment by Farleight** [comment]
I believe I've done that now. Let me know if something is glaringly incorrect.

**Comment by theVKC** [comment]
Looks great! Only thing I can think of is that this issue won't go live for non-scriptwriters until Monday when I release the beta scripts, and it won't go live statewide until a week after that. So, if your users need it in the meantime, might be smart to keep it on the agency custom for a week or so.

**Comment by Farleight** [comment]
Noted. Thanks much for your help! (Same kudos to David)
