### ISSUE TITLE
10/15 HEST changes

### ISSUE THREAD

**Issue by IlseFerris** [MN-Script-Team/DHS-MAXIS-Scripts#1019]
New amounts will be
$454 Heat/AC 
$141 electric
$38 phone (no change to phone)

scripts that will be affected by this change will be the NOTES - EXPEDITED SCREENING, ACTIONS - LTC SPOUSAL ALLOCATION.

Can anyone think of other scripts that need to be updated?

**Comment by theVKC** [comment]
@IlseFerris has this.
