### ISSUE TITLE
REPT search needs better instructions on script wiki

### ISSUE THREAD

**Issue by theVKC** [MN-Script-Team/DHS-MAXIS-Scripts#1020]
@CDPotter, looks like this was originally yours. Most of the instructions functionality is included in the image of the MsgBox: we need something more tangible in the actual instructions Wiki itself.

If @CDPotter isn't interested: anyone want to be the hero?

**Comment by CDPotter** [comment]
Can do!

**Comment by CDPotter** [comment]
And it has been beefed up!
