### ISSUE TITLE
Odd error when running scripts

### ISSUE THREAD

**Issue by CDPotter** [MN-Script-Team/DHS-MAXIS-Scripts#1022]
So I've had two different workers report the same error on different scripts at different times. When they try to run a script they get this error. Happened Monday on the client conact, and Tuesday on check EDRS, CAF, and Approved progs

![2015-08-19 07_51_16-inbox - charles potter co anoka mn us - outlook](https://cloud.githubusercontent.com/assets/7841989/9356554/22113dd4-4647-11e5-9740-6725d5ea9771.png)

**Comment by IlseFerris** [comment]
I had a worker report one of these yesterday too.  Only had one report, and thought it was a fluke or internal issue.  No other reports since.  They got it running the NOTES -SNAP CASE REVIEW script.

**Comment by courtrightd** [comment]
Is this possibly related to script_end_procedure trying to update the database and hitting a permission error or something weird?

**Comment by CDPotter** [comment]
Sounds like the error does happen after the script runs through so that would be script_end_procedure

**Comment by theVKC** [comment]
Consider backing up your database and refreshing it with a blank table. Closing.
