### ISSUE TITLE
enhancment suggestion docs rec'd

### ISSUE THREAD

**Issue by CDPotter** [MN-Script-Team/DHS-MAXIS-Scripts#1024]
A worker suggested that in the is this LTC or not message box could we make the No button the defaultly selected button instead of the yes? Save on keystrokes and mousing for a majority of workers who don't to LTC. 

I GTS'd it and found that "vbYesNoCancel Or vbDefaultButton2" (2 being the No) will change to focus of it. 

What are peoples thoughts on this?

**Comment by IlseFerris** [comment]
Sounds like a good idea to me.  Thanks for GTS'ing that so I didn't have to!

**Comment by theVKC** [comment]
Can you do it, @CDPotter?

**Comment by CDPotter** [comment]
Absolutely.
