### ISSUE TITLE
Burial asset script: overwriting over itself with the the removal of new_line function

### ISSUE THREAD

**Issue by IlseFerris** [MN-Script-Team/DHS-MAXIS-Scripts#1025]
@CDPotter are you still willing to look at this?

**Comment by CDPotter** [comment]
If it needs to happen quickly probably not. I will be away Thursday and Friday.

**Comment by IlseFerris** [comment]
Here's the other stuff that we're checking for---
One of the furious five that needs updating.  Here are the older functions that need to be removed from the scripts (these may or may not be in the script)

1. FuncLib block needs updating: 
IF default_directory = "C:\DHS-MAXIS-Scripts\Script Files\" OR default_directory = "" THEN 
instead of 
IF default_directory = "C:\DHS-MAXIS-Scripts\Script Files\" 
2. Functions to be replaced
a. write_TIKL (Call write_variable_in_TIKL to replace it)
b. write_new_line_in_SPEC_MEMO (Call write_variable_in_SPEC_MEMO to replace it)
c. write_new_Line_in_CASE_NOTE (Call write_variable_in_CASE_NOTE to replace it)
d. MAXIS check (Call check_for_MAXIS (True or False) to replace it)
e. ERRR_screen_check (replaced by call navigate_to_MAXIS_screen)
f. navigate to screen (replaced by call navigate_to_MAXIS_screen)
g. stat_navigation, navigation_buttons, memb_navigation_next, panel_navigation_next, memb_navigation_prev, and panel_navigation_prev (replaced by MAXIS_dialog_navigation)

**Comment by CDPotter** [comment]
Are there any situations in which it writes over itself for sure? I just ran it with everything I could fill in and it worked great on training 211707

**Comment by IlseFerris** [comment]
It appears it happens in situations which all fields are not complete, which is most cases.  I just ran this again on 217751,. Cash advance items was overwritten by cash advanced items.  Burial space/burial space items are not there either and 2 were entered.

**Comment by CDPotter** [comment]
Weird... I keep trying different things and I can't seem to replicate it... you're running the one from Master? I've tried both one saved to my desktop and one running through the powerpad off of BETA

**Comment by theVKC** [comment]
@IlseFerris, can you confirm this is still happening?

**Comment by IlseFerris** [comment]
This is still happening in MASTER and RELEASE branches.  The services portion seem to be overwritten, and the rest seems fine.

**Comment by IlseFerris** [comment]
Closing the issue. Since we are unable to recreate the issue, and no one else is reporting this we are closing.  Will open if this becomes an issue.

**Comment by CDPotter** [comment]
@IlseFerris and I have decided to close the issue for now as we cannot track down what is causing it. It seems fairly localized and only 2 uses of the burial asset script have occured at Hennepin in 08/15. Please close issue
