### ISSUE TITLE
Change report form rec'd enhancement: call for input

### ISSUE THREAD

**Issue by IlseFerris** [MN-Script-Team/DHS-MAXIS-Scripts#1036]
Just thinking about things and stuff this morning...

Should we have this case note template be updated to be used if a change is reported or if a CRF is rec'd.  Other option could be a check box added to the client contact script that if checked, the header would have "CHANGE REPORTED" in it. 

Thoughts?

**Comment by MelissaFox-Stearns** [comment]
I think thats a great idea. It could be used when client reports a change over the phone, in person,  in writing , or with the CRF. The script could ask if there's verification or if it was requested. 
I was also wondering if the type of change could be included in the header if the worker enteres something in its respective field. Example: if a worker enters information in the Jobs field, the header would include Changes Reported: Jobs.

**Comment by IlseFerris** [comment]
Heck yes it could! Do you want to take this one?

**Comment by MelissaFox-Stearns** [comment]
Sure! I'd love to :)

**Comment by IlseFerris** [comment]
@theVKC, you heard the gal :)

**Comment by theVKC** [comment]
Closing as this has become a separate project/milestone.
