### ISSUE TITLE
DWP Budget case note script- Script Error

### ISSUE THREAD

**Issue by MelissaFox-Stearns** [MN-Script-Team/DHS-MAXIS-Scripts#1039]
Got an error on this one this morning: Script Error at Line1, Column 1: Type mismatch: 'personal_needs'
I didn't put in a hhld number but it still tried to calculate the personal needs amount. The script should be updated with a safeguard for people like me (hehe). Could either make the personal needs hhld member a mandatory field - or - only do the calculation if a number is entered in this field. 

Would probably be an easy fix.

**Comment by theVKC** [comment]
Do you want it, @MelissaFox-Stearns?

**Comment by MelissaFox-Stearns** [comment]
I'll take it for sure!
