### ISSUE TITLE
Call for input: EXP SNAP question

### ISSUE THREAD

**Issue by IlseFerris** [MN-Script-Team/DHS-MAXIS-Scripts#1040]
A member of my team asked this question:
I know this may not be possible, but we need to know when approving Expedited SNAP if the client is in actual possession of an EBT card.
The reason is, the funds should not be REId if they have to order a card to replace a lost one.
REIing costs more money as I understand, but I’m not sure if we want to add another step to the scripts, or if we can.
Here's my question: do we think this could be helpful information to pull into the EXPEDITED SCREENING script?  Or maybe another script?

**Comment by CDPotter** [comment]
At least here at Anoka we have OSA's run the expedited screening script and I don't think we want them trying to determine the client's EBT card status. 

I hadn't heard that it costs more to REI. I knew that it could cause issues if say you REI'd for someone who could have had their card issued in office in that they have to wait for the new card to be shipped. (learned this lesson early on!)

I'd be hard pressed to think of anywhere to remind someone other than the already bloated CAF script.

**Comment by IlseFerris** [comment]
Yeah, I don't want to mess with the CAF unless we are doing a full CAF redux.  I put something together in the EXP screening script. Here’s how the script differs from the original:
If the client appears expedited, the script will go to the MONY/DISB screen and reads the MAXIS screen to see if the client has an EBT account open or not.

If the code is “N” then the following verbiage has been added to the case note “EBT Account is NOT open.  Recipient is able to get initial card in the agency.  Rapid Electronic Issuance (REI) can be used, but only to avoid an emergency issuance or to meet EXP criteria."

If the code is “Y” then the following verbiage has been added to the case note “EBT Account IS open.  Recipient will be able to get a replacement card in the agency.  Rapid Electronic Issuance (REI) with caution."

@ruthmaloney @theVKC can you weigh in?
