### ISSUE TITLE
ACTIONS - CS DISREGARD FIAT would be nice to have now for 10/15 benefits

### ISSUE THREAD

**Issue by courtrightd** [MN-Script-Team/DHS-MAXIS-Scripts#1056]

**Comment by CDPotter** [comment]
It looks like it should be usable. Shame Maxis couldn't get updated in the 3 month delay.

**Comment by theVKC** [comment]
Anyone feel up to adding it back to the dialog? @RobertFewins-Kalb

**Comment by CDPotter** [comment]
Adding it to the ACTIONS menu? I can do that tonight. Do we need new instructions as well?

**Comment by CDPotter** [comment]
Note we tested it once on one case here at Anoka. training case 226398
