### ISSUE TITLE
FUNCTIONS FILE: INSA showing coverage for all HH membs as MEMB 01?

### ISSUE THREAD

**Issue by theVKC** [MN-Script-Team/DHS-MAXIS-Scripts#106]
This was reported by X164414. I'm guessing we just need to build in a fix for showing who has what INSA. Looking for takers on this one.

**Comment by lpshanley** [comment]
Im looking into this now

**Comment by lpshanley** [comment]
Holy banannas
I see the problem
#isthisreallife

**Comment by lpshanley** [comment]
Should be done. Just Committed it!

**Comment by theVKC** [comment]
Closing, as this is also an issue reported on the FuncLib repo.
