### ISSUE TITLE
Project Mic Drop: add reviews cap

### ISSUE THREAD

**Issue by IlseFerris** [MN-Script-Team/DHS-MAXIS-Scripts#1083]
Add max reviews cap functionality that limits the amount of cases per caseload that can be run.  This will only be applied through the testing period.

**Comment by IlseFerris** [comment]
@vkc do you want to assign this to someone else? Not sure I'll have the time to research and update this one timely. @CDPotter @courtrightd, any takers?

**Comment by theVKC** [comment]
Why am I thinking @CDPotter and @RobertFewins-Kalb already have something like this...

**Comment by CDPotter** [comment]
We do not have such a tool built already. Wasn't really needed here in Anoka as we don't case bank.

**Comment by theVKC** [comment]
I thought I saw @RobertFewins-Kalb say he capped the max appointments scheduled when doing stats? That sort of function goes beyond banking, IMO.

**Comment by RobertFewins-Kalb** [comment]
I capped the number of cases that I am holding for a control, but I am running the REVS Scrubber one case load at a time.

**Comment by theVKC** [comment]
OK, I'll do it. :)
