### ISSUE TITLE
BULK SNAP case approval for HEST changes

### ISSUE THREAD

**Issue by IlseFerris** [MN-Script-Team/DHS-MAXIS-Scripts#1096]
Got a request from a Hennepin County worker to see if we can develop a BULK script for HEST changes for 10/15.  I want to say something like this was developed back in ANOKA WAAAAAYYYYY back in the day, but I'm not quite sure.  I would have been in Adult 2 still, so you know how long ago that was @theVKC 

EXAMPLE DAIL MESSAGE: INFO 10 15 SNAP MASS CHANGE NOT AUTO-APPROVED

**Comment by CDPotter** [comment]
What would the bulk script do?

**Comment by IlseFerris** [comment]
Ideally APP SNAP cases for 10/15 for the mass change, but I don't think this is kosher.

**Comment by CDPotter** [comment]
Definitely not, as far as I'm aware scripts cannot ever APP. The only bulking of changes that we've ever done was case noting/deleting if no action was needed. The COLA script works on this principle. 

https://github.com/MN-Script-Team/DHS-MAXIS-Scripts/blob/master/Script%20Files/BULK/BULK%20-%20COLA%20AUTO%20APPROVED%20DAIL%20NOTER.vbs

**Comment by theVKC** [comment]
Not kosher. Closing.

**Comment by IlseFerris** [comment]
Thanks for confirming.  My obligation was to ask.  Obligation complete. :)
