### ISSUE TITLE
NOTES - MAIN MENU is out of space.

### ISSUE THREAD

**Issue by courtrightd** [MN-Script-Team/DHS-MAXIS-Scripts#1099]
I went to add MFIP to SNAP transition note, and the M-Z menu is full at current size.  Do we want the whole main menu expanded?  Do we want to add a submenu to further break down the alphabet?  A button for MFIP scripts like the document noting button?  Other thoughts?

**Comment by CDPotter** [comment]
I would vote for cutting it into M-P and R-Z. They will be a little sparse but at least less cluttered?

**Comment by courtrightd** [comment]
Working on the M-P / R-Z split now, unless someone objects.

**Comment by theVKC** [comment]
I concur, @courtrightd. Good luck!
