### ISSUE TITLE
Thoroughly test Krabappel, then release it and move on with our lives

### ISSUE THREAD

**Issue by theVKC** [MN-Script-Team/DHS-MAXIS-Scripts#1110]
Any takers? Training case creator, anyone?

**Comment by theVKC** [comment]
Assigned it to myself just so it doesn't show up as unassigned. @CDPotter and @C-Love and others have indicated a willingness to test, but more testers are welcome. :)

**Comment by C-Love** [comment]
I have run into an issue. Write_panel_to_MAXIS_SHEL has the wrong coordinated for some of the fields:
  Subsidized should write to: 6, 46
  Shared should write to: 6, 60
  Paid to should write to: 7, 50

**Comment by RobertFewins-Kalb** [comment]
I have fixes all ready. There are also a couple of Krabappel fixes for the func lib that have been sitting out there for a while @theVKC

Sent from my iPhone

On Oct 20, 2015, at 4:28 PM, C-Love <notifications@github.com<mailto:notifications@github.com>> wrote:


I have run into an issue. Write_panel_to_MAXIS_SHEL has the wrong coordinated for some of the fields:
Subsidized should write to: 6, 46
Shared should write to: 6, 60
Paid to should write to: 7, 50

-
Reply to this email directly or view it on GitHub<https://github.com/MN-Script-Team/DHS-MAXIS-Scripts/issues/1110#issuecomment-149708629>.



Click here<https://www.mailcontrol.com/sr/F1TJ1Rr!7QTGX2PQPOmvUp5TF7aiJWLy9dL1hZeEcqovwo2FLEdN6Cc0w2zYdC!g8XdfyjS2ghX36NGKki70Ug==> to report this email as spam.


NOTICE: Unless restricted by law, email correspondence to and from Anoka County government offices may be public data subject to the Minnesota Data Practices Act and/or may be disclosed to third parties.

**Comment by RobertFewins-Kalb** [comment]
@C-Love we have been testing the crap out of this over the past 2 weeks and have hit quite a few snags. @CDPotter  or I should be able to submit pull requests with all the results.

**Comment by C-Love** [comment]
Ok - I was having some issues but I wasn't sure how much was user error. I will keep working at it a bit. I think I am figuring out what I was doing wrong. @RobertFewins-Kalb I will keep a list but wait to post until the pull requests go through.

**Comment by RobertFewins-Kalb** [comment]
Here are a few places where I've had to make fixes...

DCEX -- we need to do more thorough data validation for the child number. In the interim, I have had the function convert the number to a 2 digit number should the length be 1.

MEDI -- the function is not pulling MEDI_apply_prem_to_spdn OR MEDI_apply_prem_end_date through as parameters and it is not writing the values in Maxis (causing stat edits)

PARE -- the function needs to pull reference_number through as an argument so it creates a PARE panel for the appropriate household member

SHEL -- what you mentioned earlier

**Comment by theVKC** [comment]
FYI: FuncLib pull requests will start being accepted again Monday at DHS hackathon. Just haven't had time to do it in the last few weeks. Now, I'm going to return to my vacation. :sunglasses:

**Comment by C-Love** [comment]
I have not been able to redirect the path in the dialog box to a new filename. I fill in the new filename information and when I press 'reload details' I get a msgbox that says I must select a scenario. If I do that, the script moves forward instead of loading in new details from the alternate file I have saved. So basically I have to save the file as Krabappel template, in the same location for the script to read it.

**Comment by RobertFewins-Kalb** [comment]
We need to add a condition to the do/loop like in NOTES - VERIFS REQUESTED where it exists the do/loop when buttonpressed = -1 to make sure it is not error checking when you try to update the file path. On it.

**Comment by RobertFewins-Kalb** [comment]
...and make sure it opens the Excel file AFTER the dialog.

**Comment by RobertFewins-Kalb** [comment]
I am going to test logic that does this...
DO
DO
DO
 IF ButtonPressed = reload_excel_file THEN 
 * Close the Excel file that is already open (because Excel has to open in order to have an array with scenario names)
 * Reload the new file
LOOP UNTIL ButtonPressed <> reload_excel_path
LOOP UNTIL ButtonPressed = -1 AND scenario_dropdown <> "Select one..."
LOOP UNTIL final_check_before_running = vbYes

**Comment by RobertFewins-Kalb** [comment]
Alright...one custom function later and it's updated. Tested and working. I'll submit a fix.

**Comment by RobertFewins-Kalb** [comment]
@C-Love , thank you for testing!

**Comment by RobertFewins-Kalb** [comment]
Resolved in #1312

**Comment by theVKC** [comment]
Leaving issue open as we're still testing (thanks @C-Love you are amazing).

**Comment by theVKC** [comment]
Can I assume this has been tested and we believe it's working sufficiently for wide release?

* @C-Love 
* @RobertFewins-Kalb 
* @CDPotter 
* @courtrightd 

Assuming it's working, we really just need instructions (on SIR), scenarios (#1625) and time savings (#1626). If you-all believe it's been well tested for our purposes, I'm ready to close this issue.

**Comment by CDPotter** [comment]
It's been in use for 3+ training groups in our agency over the past half year.

**Comment by theVKC** [comment]
And (just to be clear for everyone): "in use" does mean "non scriptwriters could run it and it worked"?

**Comment by CDPotter** [comment]
Correct we provided our program coordinators with documentation a blank template and they have created and implemented their own training scenarios. Any issues were usually down to coding excel wrong. Any programming issues were worked out and submitted months ago. Correct @RobertFewins-Kalb?

**Comment by theVKC** [comment]
I'm going to say it's been "tested thoroughly" based on your report @CDPotter, and I'm going to close the issue.
