### ISSUE TITLE
Enhancement for the Sanction Case Note

### ISSUE THREAD

**Issue by StormageddonDLOA** [MN-Script-Team/DHS-MAXIS-Scripts#1113]
Could a line for the ES counselor and their phone number be added like is in the Employment Plan Received case note?

**Comment by courtrightd** [comment]
If this is for NOTES – MFIP SANCTION  / DWP DISQUALIFICATION,  this was resolved in #832, enhanced script should be in the next release.

**Comment by StormageddonDLOA** [comment]
Oh, perfect. Thanks for the heads up. I’ll close the issue.

Timothy DeLong, Financial Worker
Stearns County Human Services
705 Courthouse Square
St. Cloud, MN 56303
320-650-5842
