### ISSUE TITLE
Asset Assessment received

### ISSUE THREAD

**Issue by IlseFerris** [MN-Script-Team/DHS-MAXIS-Scripts#1115]
Request from LTC worker for an initial AA case note.  Here's what she has suggested:
"I think for the AA it would be nice to say it was rec’d, AA date, community and facility spouse info, faci info, verifs needed and and reported assets?  Also maybe something to select if it is for AC only."

This could be an enhancement to the current script, or a new script.

**Comment by theVKC** [comment]
Up to you.

**Comment by IlseFerris** [comment]
I'll take it, especially since I need to work on the AA anyways

**Comment by theVKC** [comment]
Is it going to be a new script or an update of the existing?

**Comment by IlseFerris** [comment]
I haven't decided yet. We can brainstorm at hackathon on Monday.

**Comment by theVKC** [comment]
Marking as help wanted, will remove if not completed by next week.

**Comment by theVKC** [comment]
Assuming nobody wants this, I'm closing it Monday.
