### ISSUE TITLE
BULK DAIL report option to use on multiple users (enhancement)

### ISSUE THREAD

**Issue by IlseFerris** [MN-Script-Team/DHS-MAXIS-Scripts#1116]
Request rec'd from Hennepin County supervisor who would like to be able to pull information from several user's DAIL messages.

**Comment by theVKC** [comment]
@IlseFerris, do you want this one?

**Comment by IlseFerris** [comment]
Sure thing!

**Comment by theVKC** [comment]
@IlseFerris, did we resolve this at hackathon Monday?

**Comment by IlseFerris** [comment]
Not resolved yet, still working on this

**Comment by theVKC** [comment]
Want help? I know we're both at our respective sites, but perhaps I can use this as an opportunity to test iLinc again.

**Comment by IlseFerris** [comment]
Of course I want help, but let me take another look at it first. Also I'm working on another issue.
.

**Comment by theVKC** [comment]
Woot! I can take a few minutes out tomorrow for it, too. Let me know.

**Comment by theVKC** [comment]
@IlseFerris: I'm taking this one unless you've gotten work done on it.
