### ISSUE TITLE
Burial assets enhancement: list in header which program assets were evaluated for

### ISSUE THREAD

**Issue by IlseFerris** [MN-Script-Team/DHS-MAXIS-Scripts#1121]
Received request for this as the current burial assets scripts gives a breakdown of what is not counted/ counted, but since there are different rules for CASH programs vs. HC, a clear distinction should be made.

**Comment by IlseFerris** [comment]
Also could maybe use a message at the end with the HCPM and CM references, and a reminder that assets excluded for HC may not be excluded for CASH programs.

**Comment by theVKC** [comment]
Do you want this one?

**Comment by IlseFerris** [comment]
Of course!
