### ISSUE TITLE
BULK PND2 ~ Issue with worker number fill

### ISSUE THREAD

**Issue by ALJ10** [MN-Script-Team/DHS-MAXIS-Scripts#1122]
Workers are reporting the PND2 script is not functioning properly. After we enter the last 3 of the worker ID and select the programs, it looks like it's going to run. But once it gets into Excel, it's howing formula errors. Maxis shows unknown worker. I attached a screen shot to show errors.

![script bulk pnd2 errors in excel_maxis](https://cloud.githubusercontent.com/assets/10159901/10079330/02cc22b6-62af-11e5-9196-c82460aa85ea.jpg)

**Comment by RobertFewins-Kalb** [comment]
I am working on a fix for writing the worker number. 

Regarding Excel, that's not a formula error. That's the output when you try to divide by zero, which is what is happening in that picture.
