### ISSUE TITLE
CSES New Hire returning to SELF without case number

### ISSUE THREAD

**Issue by RobertFewins-Kalb** [MN-Script-Team/DHS-MAXIS-Scripts#1124]
A financial worker has reported that the CSES NEW HIRE DAIL Scrubber is backing out to SELF but not bringing the case number with it. I shall bypass the Council of Elrond and take the foul bug to Mordor for destruction myself, casting it to the firey pit from whence it came!

**Comment by RobertFewins-Kalb** [comment]
Found it

**Comment by RobertFewins-Kalb** [comment]
Submitting a fix

**Comment by theVKC** [comment]
Is this doubtfire related?

**Comment by RobertFewins-Kalb** [comment]
Yep

**Comment by theVKC** [comment]
sounds vunderbar

**Comment by RobertFewins-Kalb** [comment]
It's also fixed

**Comment by RobertFewins-Kalb** [comment]
which is vunderbar
