### ISSUE TITLE
LTC Application received -- dialog bug reported

### ISSUE THREAD

**Issue by RobertFewins-Kalb** [MN-Script-Team/DHS-MAXIS-Scripts#1126]
Going to look into what is causing this...

![image](https://cloud.githubusercontent.com/assets/7842016/10086227/dafe172a-62d2-11e5-95a2-bc47e6595eed.png)

**Comment by RobertFewins-Kalb** [comment]
I believe I have found the problem and I am submitting a fix...

![image](https://cloud.githubusercontent.com/assets/7842016/10086353/8d160c60-62d3-11e5-8614-c8768bf7c66b.png)

**Comment by theVKC** [comment]
Resolved with #1127.
