### ISSUE TITLE
SHELTER FORM RECEIVED - Dialog out of range error.

### ISSUE THREAD

**Issue by courtrightd** [MN-Script-Team/DHS-MAXIS-Scripts#1131]
Happens whenever it is run from a menu (locally from agency custom or when running from github.)  Works when run directly (script->play).  That is as far as I got.

**Comment by theVKC** [comment]
Is this happening for anyone else using master or BETA branches? County folks who might have seen this bug:

@mldietz 
@IlseFerris 
@khiestand 
@C-Love 
@MelissaFox-Stearns

**Comment by theVKC** [comment]
More folks who might have seen it:

@ALJ10
@CDPotter 
@StormageddonDLOA

**Comment by ALJ10** [comment]
I haven’t rec’d any report of issues with that script. But I sent out an email to my workers asking for feedback on if they’ve used that script recently. I will share that with you if I receive a response.

Amanda Jensen
Technology Coordinator/Onbase OCSA_OCWA Certified
Crow Wing County Community Services
P.O. Box 686, 204 Laurel Street
Brainerd, MN 56401
Office:  (218) 824-1235
Fax:     (218) 824-1141
www.crowwing.us<http://www.crowwing.us/>
[http://mn-crowwingcounty.civicplus.com/DocumentCenter/View/5692]
Our Vision: Being Minnesota’s favorite place.
Our Mission: Serve well. Deliver value. Drive results.
Our Values: Be responsible. Treat people right. Build a better future.

Let me know how I am doing. Click here to take a moment and fill out this survey<https://www.surveymonkey.com/s/CommunityServiceLeadership>.

**Comment by CDPotter** [comment]
It looks like it's working for me through menu, strangely it took two clicks to get it to run. I opened menu, clicked r-z menu reloaded, clicked shelter form, menu reloaded, clicked shelter form, opened script.

**Comment by theVKC** [comment]
@courtrightd, is there a chance this is a local issue to the SLC?

**Comment by theVKC** [comment]
Perhaps @farleight has seen this one?

**Comment by courtrightd** [comment]
I feel like it shouldn’t be, since it is occurring for me when I use the same Beta branch that others are, but who knows.  I just finished an appt and will try to further diagnose.

**Comment by ALJ10** [comment]
I actually just tested on a case. Same process as CharlesP (two clicks to open), but it ran successfully with no errors.

Amanda Jensen
Technology Coordinator/Onbase OCSA_OCWA Certified
Crow Wing County Community Services
P.O. Box 686, 204 Laurel Street
Brainerd, MN 56401
Office:  (218) 824-1235
Fax:     (218) 824-1141
www.crowwing.us<http://www.crowwing.us/>
[http://mn-crowwingcounty.civicplus.com/DocumentCenter/View/5692]
Our Vision: Being Minnesota’s favorite place.
Our Mission: Serve well. Deliver value. Drive results.
Our Values: Be responsible. Treat people right. Build a better future.

Let me know how I am doing. Click here to take a moment and fill out this survey<https://www.surveymonkey.com/s/CommunityServiceLeadership>.

**Comment by theVKC** [comment]
Hmmmmmmmmmmmmmmmm. The two clicks thing does scare me a bit. @courtrightd, am I remembering correctly that you tweaked the NOTES MAIN MENU script this month? If so, perhaps there's something amiss all up in there?

**Comment by courtrightd** [comment]
Yeah – That was my worry too, but if I change my local copy of the menu script to call something else with that button it works fine, and if I call shelter form from a different button, it also works fine.  That doesn’t necessarily mean it isn’t something with the menu change, I’m just struggling to find it.

**Comment by IlseFerris** [comment]
When I click on it gives me a message box informing me a case number is required.  The dialog doesn't come up.  Tested about 12 times.

**Comment by courtrightd** [comment]
I think I found it.  Stand by.

**Comment by ALJ10** [comment]
I forgot to mention that. Sorry! I had that too. But if I actually went into a case (ex. case/curr) and then ran the script, it worked (beside the two click issue).

Amanda Jensen
Technology Coordinator/Onbase OCSA_OCWA Certified
Crow Wing County Community Services
P.O. Box 686, 204 Laurel Street
Brainerd, MN 56401
Office:  (218) 824-1235
Fax:     (218) 824-1141
www.crowwing.us<http://www.crowwing.us/>
[http://mn-crowwingcounty.civicplus.com/DocumentCenter/View/5692]
Our Vision: Being Minnesota’s favorite place.
Our Mission: Serve well. Deliver value. Drive results.
Our Values: Be responsible. Treat people right. Build a better future.

Let me know how I am doing. Click here to take a moment and fill out this survey<https://www.surveymonkey.com/s/CommunityServiceLeadership>.

**Comment by theVKC** [comment]
I like how to @courtrightd "struggling to find it" can be resolved in under 3 minutes. #scriptmaster

**Comment by courtrightd** [comment]
“struggling to find it” meant I suspected the exact type of issue it was, but looked at the code like 16 times and didn’t see it.  In my defense, I have done two phone appts while working on this.  Pull request coming.
