### ISSUE TITLE
HCAPP footer month new issue

### ISSUE THREAD

**Issue by CDPotter** [MN-Script-Team/DHS-MAXIS-Scripts#1139]
Footer month is being calculated as CM+1. changed to current month.

**Comment by theVKC** [comment]
Say @CDPotter, have you considered that the HC pop-up might show blank in current month vs CM + 1? Do you think it matters? Just curious.

**Comment by CDPotter** [comment]
I couldn't see why, before I took this out the script was still holding a variable in footer_month up until the point it had to display it in the dialog. If I remember I tried both 09 and 10 before submitting the Cstr and this fix.
