### ISSUE TITLE
Krabappel: inverse Krabappel

### ISSUE THREAD

**Issue by theVKC** [MN-Script-Team/DHS-MAXIS-Scripts#1142]
Basically, creates the Excel spreadsheet from an existing case. Casey from Ramsey has offered to take this one on. Welcome to the Krabappel universe.

**Comment by CDPotter** [comment]
Awesome news! Yay for Side Op: Turnabout!

**Comment by theVKC** [comment]
Agreed! @C-Love has this on lock.

**Comment by theVKC** [comment]
Marking this as help wanted for a week, as @C-Love does not presently have time.

**Comment by theVKC** [comment]
Assuming nobody wants this, I'm closing it Monday.

**Comment by RobertFewins-Kalb** [comment]
I'm poking away at this as time allows. 

Progress: I've set it up to allow you to copy from MAXIS to the scenarios spreadsheet. The script will copy the template and paste it into a new worksheet. If the script detects production or inquiry, it will ask for names to replace the real ones. Otherwise, if you are copying from training, it will give you the option of keeping the fake name or creating a new one.

So far, it's only reading from MEMB, MEMI and ADDR, but the nuts and bolts are there and it's just a matter of knocking out the programming for each of the remaining 650 fields.

Please assign this to me.

**Comment by theVKC** [comment]
I can certainly reopen this and assign it to you @RobertFewins-Kalb, but do you have an ETA on when it can be completed?

* July release enhancement deadline: 07/15
* August release enhancement deadline: 08/12

If you don't think it can be done by either of those, I'm going to leave it as closed and we can reopen the issue closer-to-the-estimated-time-of-completion.

**Comment by RobertFewins-Kalb** [comment]
It will be done by 8/12 for sure.

**Comment by theVKC** [comment]
Done! Good luck and thank you! This will be awesome.

**Comment by RobertFewins-Kalb** [comment]
I'm actually hoping to have it usable by the middle of next week (that whole "when I have time" has turned into "I'm getting this done") but I want to test it with trainers here for generating the next batch of training cases for the next round of future Hennepin County employees...

**Comment by CDPotter** [comment]
Kinda already know the answer but how is this one going?

**Comment by RobertFewins-Kalb** [comment]
Working on adding STATS_manualtime to each panel...about halfway through that. Otherwise done.

**Comment by IlseFerris** [comment]
Hey @RobertFewins-Kalb, if you're looking for some testers and/or people looking to gather some manual time for this, Casey and I are ready and willing.

**Comment by RobertFewins-Kalb** [comment]
I can submit a pull request if'n y'all want to add to it later. It should be working on the most recent Krabappel spreadsheet.

**Comment by CDPotter** [comment]
Any word on this @RobertFewins-Kalb ? Word is cases are gonna be disappearing on the 26th.

**Comment by C-Love** [comment]
@RobertFewins-Kalb - or *insert new name here* sent me the script to test. The script seems to run very well BUT there are some issues with data validation in the template file. I have noticed this in the past when creating scenarios. I plan to take a look at the template file at hackathon and then do some more testing. The script is testing very well so far. YAY!

**Comment by C-Love** [comment]
!!! How did I unassign someone?!? With markdown!? What is happening - UNDO!

**Comment by CDPotter** [comment]
Well that worked nicely anyway! Had to reassign to the @RoberT-1000.

**Comment by theVKC** [comment]
You didn't unassign it, @C-Love. I did.

@RobertFewins-Kalb lost his GitHub credentials, so I removed him from the organization and replaced him with his new GitHub persona, @RoberT-1000. Unfortunately, GitHub doesn't automatically update assignment details, but when the issue gets any-sort-of-update, it corrects the "missing people." Ergo, I did it but didn't know it until you talked about it.

**Comment by RoberT-1000** [comment]
Do you want me to upload what I have? Now that I'm back in, I can do.

**Comment by CDPotter** [comment]
Well we're in freeze so maybe after next release? (we're delaying the release until 9/30 this time to coincide with PRISM's first release.)

**Comment by RoberT-1000** [comment]
I've waited this long to upload. I can wait a bit more :)

**Comment by RoberT-1000** [comment]
Hey! I'm going to pull this in!!
