### ISSUE TITLE
Gas Cards Issued Enhancement

### ISSUE THREAD

**Issue by khiestand** [MN-Script-Team/DHS-MAXIS-Scripts#1144]
I will be adding the total amt given today and the total amt given this year to the subject line of this script.  I will now read as *$$* GAS CARDS ISSUED $40/$100 *$$*

**Comment by khiestand** [comment]
Enhancements are complete, will pull request on 9/30/15.

**Comment by theVKC** [comment]
Thanks @khiestand!
