### ISSUE TITLE
Notes - GRH - HRF

### ISSUE THREAD

**Issue by Y-Lor-Y** [MN-Script-Team/DHS-MAXIS-Scripts#1147]
The elig/grh button navigates to elig/mfip.

**Comment by theVKC** [comment]
Do you want this one, @Y-Lor-Y?

**Comment by Y-Lor-Y** [comment]
Sure, you can assign this to me.  I will work on this as much as possible.

**Comment by Y-Lor-Y** [comment]
the panel navigation to ELIG_GRH_button currently not within the function lib.  I've added that just now to the library, so will wait until that's fixed before I post my fix for this issue.
