### ISSUE TITLE
MSQ Notes Script

### ISSUE THREAD

**Issue by khiestand** [MN-Script-Team/DHS-MAXIS-Scripts#1148]
A new case note script that will note details of MSQ and update STAT/ACCI. You can assign this to me as it is already in the works.

**Comment by theVKC** [comment]
@khiestand, way back in the day, I had an MSQ script that went into MMIS and did stuff. Would you like me to dig it up and send it your way?

**Comment by khiestand** [comment]
@theVKC Oh sure why not!  I am sure the workers would LOVE for it to update in MMIS.  Do we have other scripts that update in MMIS that I could look at too for examples of how that is done?  If I can't get the MMIS part going, I can at least pull request what I have done, and enhance it later too.

**Comment by theVKC** [comment]
I don't think we have others. This one was done by me at the county, so I don't think it's live just yet. I'll dig around to see if I can find it.

**Comment by theVKC** [comment]
@khiestand, did I ever send that script to you? In any case, have you done any work on this? Just curious.

**Comment by khiestand** [comment]
@theVKC No I don't think you ever did send it.  No worries though, I haven't had any time recently to dedicate to scripts so no rush.

**Comment by theVKC** [comment]
OK, I'll see what I can do today! :)

**Comment by theVKC** [comment]
Any update on this, @khiestand? Just looking to clean up the issue list. If you haven't had much time to work on it, I might open it up to others.

**Comment by khiestand** [comment]
Yes, please open it up to others!  I have had no time, so would love it others wanted to jump on it.

**Comment by theVKC** [comment]
Will do! I'll leave it open until next hackathon at DHS. If nobody wants it, I'll close it then (and you can feel free to take it on at any time, and we can just reopen the issue).

**Comment by theVKC** [comment]
Would you estimate you could have this ready by mid-February? If so, I'll target it for the v2016.02 release.

**Comment by Y-Lor-Y** [comment]
I will try very hard to get it done.  It’s just that as much as I’m trying to create time at work to work on scripts…in the nature of my position as a trainer, I’m bombarded with new staffs, Q&A, and etc.

I might as well just buy an enclosed doorway and close it off with a top house/umbrella…to close off visitors.  LOL.

But I really want the GRH postpay done first.  I’m half way through with my coding.

Yang T. Lor | FCM Resource Trainer
Financial Assistance Services |  Ramsey County CHS
160 Kellogg Boulevard East, Saint Paul, MN  55101
P: 651-266-3621  |  Fax: 651-266-3705
E: yang.tou.lor@co.ramsey.mn.us
Schedule: M to Th, 7:45 AM to 6:00 PM
www.ramseycounty.us<http://www.ramseycounty.us>

The information included in this email message, including any attachments, is intended only for the person or organization to which it is addressed.  This email message may contain information that is privileged or confidential.  If you receive this email message and are not the intended recipient or responsible for delivering the message to the intended recipient, you may not use, disseminate, distribute, or copy the information included in this email and any attachments.  If you received this email by mistake, please reply by email and destroy all copies of this message and any attachments.  Thank you

**Comment by theVKC** [comment]
Sounds good. I'll leave this off for now and we can see where you end up with the other script. I can always add it later if you think you'll have time. No worries. :)

**Comment by theVKC** [comment]
@Y-Lor-Y: have you started this one yet? Just curious because @khiestand is coming to hackathon Monday, and if she's coming perhaps she wants her issue back! :)

**Comment by Y-Lor-Y** [comment]
I have not yet started on it.  If she wants it back, please do so.  At this point, I just got 4 new staff to train, so my time may be pushed out for the MSQ.

Yang T. Lor | FCM Resource Trainer
Financial Assistance Services |  Ramsey County CHS
160 Kellogg Boulevard East, Saint Paul, MN  55101
P: 651-266-3621  |  Fax: 651-266-3705
E: yang.tou.lor@co.ramsey.mn.us
Schedule: M to Th, 7:45 AM to 6:00 PM
www.ramseycounty.us<http://www.ramseycounty.us>

The information included in this email message, including any attachments, is intended only for the person or organization to which it is addressed.  This email message may contain information that is privileged or confidential.  If you receive this email message and are not the intended recipient or responsible for delivering the message to the intended recipient, you may not use, disseminate, distribute, or copy the information included in this email and any attachments.  If you received this email by mistake, please reply by email and destroy all copies of this message and any attachments.  Thank you

**Comment by theVKC** [comment]
OK, it's "help wanted" again. @khiestand, if you want it, it's yours!
