### ISSUE TITLE
Notes - MFIP Sanction 

### ISSUE THREAD

**Issue by Y-Lor-Y** [MN-Script-Team/DHS-MAXIS-Scripts#1149]
The dialog box verbiage indicate that the sanction needs to be cured by 10 days cut-off date, however, per policy it's actually 10 days from the effective month.  So, end of month minus 10.  For more detail, refer to PQ # 9892 (1/21/11) for further references.

**Comment by theVKC** [comment]
Are you volunteering to take this, @Y-Lor-Y?

**Comment by Y-Lor-Y** [comment]
Sure, I'll take a stab at it.  Note my time are limited, but if this is not a rush I would like to.
