### ISSUE TITLE
Priv case handling for Project Mic drop

### ISSUE THREAD

**Issue by IlseFerris** [MN-Script-Team/DHS-MAXIS-Scripts#1150]
@courtrightd A little bird told me that you were working on this?  Any truth to that/can you take a crack at it?

**Comment by courtrightd** [comment]
There is some truth to that – I did this for REPT/MONT, so it shouldn’t be hard to recreate it in other bulk scripts.  I’ll take it.

**Comment by courtrightd** [comment]
So, 30 days later I go to look at this, and maybe I'm losing it, but where is Project Mic Drop?

**Comment by theVKC** [comment]
My fork of the main repo, in a branch called `REVS_scrubber_building`. That way it's less obvious. https://github.com/theVKC/VKC-Script-Changes/tree/REVS_scrubber_building

**Comment by courtrightd** [comment]
Ok, this should be done, but my testing has revealed no PRIV cases on REPT/REVS this month.  I will test it next month and then pull it in.

**Comment by theVKC** [comment]
Woot! I'll leave it up until you do pull it in, @courtrightd. And thank you!

**Comment by theVKC** [comment]
Resolved by @courtrightd via side-pull. Thank you!
