### ISSUE TITLE
ACTIONS - PAYSTUBS RECEIVED possibly causing exception access violation

### ISSUE THREAD

**Issue by RobertFewins-Kalb** [MN-Script-Team/DHS-MAXIS-Scripts#1154]
I'm looking into this, but a worker reported that ACTIONS - PAYSTUBS RECEIVED caused an exception access violation. When I tested the script on a training case, I couldn't generate the error. I had the worker run the script with me there on the live case, and happened again. I am working on isolating the problem (it may be related to her machine).

I am also looking into any possible Doubtfire-related error.

**Comment by theVKC** [comment]
[renamed "possibly" so as not to scare people]

**Comment by RobertFewins-Kalb** [comment]
Yes. And for extra accuracy. Thanks!

**Comment by RobertFewins-Kalb** [comment]
Closing this issue. I cannot recreate the problem on my computer or any other users computer. I am chalking this up to gremlins
