### ISSUE TITLE
NOTES - Expedited Screening is case noting that clients known to EBT can get a new card

### ISSUE THREAD

**Issue by RobertFewins-Kalb** [MN-Script-Team/DHS-MAXIS-Scripts#1155]
A couple of workers have reported a possible issue with NOTES - Expedited Screening. To our knowledge, clients that are already known to EBT cannot receive a new card but the script is case noting that they can.

**Comment by IlseFerris** [comment]
Yikes, that's embarrassing.  I left NOT out.  I'm on this unless @RobertFewins-Kalb already found my error.

**Comment by RobertFewins-Kalb** [comment]
You can take it. I was just wondering if that was correct.

**Comment by RobertFewins-Kalb** [comment]
I'm taking a look at ACTIONS - PAYSTUBS RECEIVED right now

**Comment by RobertFewins-Kalb** [comment]
Thanks, @IlseFerris

**Comment by IlseFerris** [comment]
No problem.  And good luck with Paystubs rec'd.  That's an impressively complex script.
