### ISSUE TITLE
NOTES - Good Cause Claimed

### ISSUE THREAD

**Issue by StormageddonDLOA** [MN-Script-Team/DHS-MAXIS-Scripts#1157]
A request that we add DHS-3632 to the text box in with the DHS-3627 & DHS-3979.

**Comment by StormageddonDLOA** [comment]
I'll take this one.

**Comment by theVKC** [comment]
Good luck @StormageddonDLOA! :)

**Comment by theVKC** [comment]
Closed by #1237.
