### ISSUE TITLE
NOTES - Verifications Needed

### ISSUE THREAD

**Issue by StormageddonDLOA** [MN-Script-Team/DHS-MAXIS-Scripts#1158]
Msg on the Bluezone discussion forum dated 9/24/15.

Problem with Verifications Needed script
Anyone else having trouble with this script? It’s not including details for TIKL and worker signature.

**Comment by StormageddonDLOA** [comment]
I'll take this one.

**Comment by courtrightd** [comment]
I just had this reported to me today but haven’t tested yet.  I can look at it.

**Comment by StormageddonDLOA** [comment]
I think I've already found the issues.

**Comment by courtrightd** [comment]
Then I’ll let you have it ☺

**Comment by theVKC** [comment]
Good luck!
