### ISSUE TITLE
Script database error

### ISSUE THREAD

**Issue by CDPotter** [MN-Script-Team/DHS-MAXIS-Scripts#1164]
Anyone else getting this error message after running a script? Getting reports from BETA and Master users here. Just trying to determine if it's on our end or statewide. 

![2015-09-30 07_48_48-s1 - anoka desktop - anoka scripted desktop - bluezone mainframe display](https://cloud.githubusercontent.com/assets/7841989/10193292/b6e5b220-6747-11e5-895b-67ae50c95a12.png)

**Comment by CDPotter** [comment]
Our database got corrupted. repair fixed it. Fasted open/closure of issue ever?

**Comment by theVKC** [comment]
Thanks for closing, @CDPotter!
