### ISSUE TITLE
REIN_PROGS_button variable incorrect, critial bug

### ISSUE THREAD

**Issue by IlseFerris** [MN-Script-Team/DHS-MAXIS-Scripts#1168]
pull requests 1165-1167 resolve the issue

script will not run.  Reported on SIR.

**Comment by theVKC** [comment]
Pulled. @IlseFerris, care to be the hero and tell folks you fixed it?

**Comment by IlseFerris** [comment]
Posted on SIR.  Thanks for the fast pullin' @theVKC
