### ISSUE TITLE
CAF initial dialog enchancement, add Select one to CAF type

### ISSUE THREAD

**Issue by IlseFerris** [MN-Script-Team/DHS-MAXIS-Scripts#1174]
Hennepin County worker reports that users are not updating this field in MANY cases.  Select one option here would be amazing!  What do you all think?

**Comment by theVKC** [comment]
Let's do it. Do you want it?

**Comment by RobertFewins-Kalb** [comment]
Add err_msg handling?

**Comment by theVKC** [comment]
I'd think so, @RobertFewins-Kalb.

**Comment by IlseFerris** [comment]
yep, give it here!
