### ISSUE TITLE
New script Postponed WREG verifs WCOMer

### ISSUE THREAD

**Issue by CDPotter** [MN-Script-Team/DHS-MAXIS-Scripts#1180]
Thoughts on a script to add the prescribed WCOM for postponed ABAWD exemption verifs?

POLI TEMP 02.05.70.01

**Comment by courtrightd** [comment]
I think this would be excellent.  Perhaps as an enhancement to the Approved progs dialog?  (since the needed information should be noted when approving in this circumstance.)  I could see it as standalone too.

**Comment by theVKC** [comment]
I agree in making this an enhancement. Might be better to remind folks to use it there. Do you want it @CDPotter? 

(Also, small request @CDPotter, please provide a bit more detail in the title of these issues. When coming up with release notes, more description is always better.)

**Comment by CDPotter** [comment]
Whoops, too excited about the idea. Already working on it!

**Comment by theVKC** [comment]
Thanks! I did the release notes yesterday, so it's a bit of a sore subject for me at the moment. :P

**Comment by CDPotter** [comment]
Ok so I ignored my emails as I worked on it and built a separate script from the ma-epd wcom script. 

So currently the functionality is as such:
worker enters case number, approval month/year into dialog
script created HH member array and limits it to only one entry via loop (the grammar in the verbiage gets wonky trying to account for multiple HH members with different postponed WREG exemptions, I felt it was too rare to try to account for)
script grabs app date off prog and HH member's name off memb
calculates 10 day due date, and compares the app date to the 15th of the month to determine the proper closing date. 
shows dialog with edit boxes for verif due date and closure date (incase calc was wrong) and edit box for verifs postponed and worker sig. 
if the worker puts the verif due date after the case closure date the script will end as that will cause misleading notice
Then it tries to write WCOM using variables and poli/temp language
if it doesn't find waiting and FS it ends
if it does it case notes using variables 

My concern with making it an enhancement is the fail points confusing/upsetting people. Thoughts?

**Comment by theVKC** [comment]
Your script seems like it does more than approved programs, possibly too much to lump into the same script. I'm in favor, and I'll change the tags on the issue.

**Comment by CDPotter** [comment]
Sounds good to me, the poli/temp verbiage required 4 variables for input. I just got a last minute HC renewal I gotta do so I will share tomorrow!

**Comment by theVKC** [comment]
This looks great. @ruthmaloney might be interested in this one!

**Comment by ruthmaloney** [comment]
I like it and hope workers use it. Although, at this point, we do not review for verifications listed in WCOM on the postponed expedited auto-closure notice, I’m not sure if QC is reviewing that way. Now if we could just automate the 2919’s…  ;-)

Ruth Maloney

**Comment by theVKC** [comment]
AUTOMATE ALL THE 2919S!! :)
