### ISSUE TITLE
Ooops, need a file extension on NOTES - APPLICATION RECEIVED

### ISSUE THREAD

**Issue by theVKC** [MN-Script-Team/DHS-MAXIS-Scripts#1189]
It needs a ".vbs" in lower case on it. @C-Love, would you care to do the honors, so as to preserve your  code contributions?

**Comment by C-Love** [comment]
@theVKC  - Ooops - my bad - yeah I will fix it

**Comment by theVKC** [comment]
Resolved by #1190.
