### ISSUE TITLE
BULK - REPT/INAC LIST not connected to powerpad.

### ISSUE THREAD

**Issue by RobertFewins-Kalb** [MN-Script-Team/DHS-MAXIS-Scripts#1193]
When you try to run the script, you get the error that it cannot be found...

![image](https://cloud.githubusercontent.com/assets/7842016/10228780/3eedd75e-683a-11e5-9feb-9ee04beb6bdc.png)

**Comment by theVKC** [comment]
Is this on master, or everywhere? I'm going through GitHub notifications right now, so if you already pulled it I'm sure I'll see it soon.

**Comment by theVKC** [comment]
@RobertFewins-Kalb, bump. Was this resolved?

**Comment by RobertFewins-Kalb** [comment]
I haven't done anything about it. I shall fix now.

**Comment by theVKC** [comment]
Resolved by #1225.
