### ISSUE TITLE
Notes - CSR - BUSI income not pulling

### ISSUE THREAD

**Issue by Farleight** [MN-Script-Team/DHS-MAXIS-Scripts#1199]
BUSI income is not auto-filling (at least for HC purposes). Methinks BUSI has been updated so Add_BUSI_to_variable is not working properly... (Methinks this mostly because Robert told me to) In any case, I'm guessing that will affect much more than this one script, and I'm not sure where one would find Add_BUSI_to_variable  to update it.

**Comment by CDPotter** [comment]
It would be in the function library https://github.com/MN-Script-Team/BZS-FuncLib

**Comment by Farleight** [comment]
Thank you! Actually, reviewing that, everything seems to match up... unless I'm missing something, which is entirely plausible. Any thoughts, @RobertFewins-Kalb?

**Comment by CDPotter** [comment]
Agreed, all of the reads are on point. The only thing I saw that might be causing confusion is the function checks twice which HC amount should be included. It looks like when it is creating the variable it asks if footer_month = current_month_for_hc_est then is the only place that adds the HCA and HCB amounts into the variable. Looks like it either needs that if removed or an else added, but it needs some logic to write something isn't in the HC income estimator.

**Comment by CDPotter** [comment]
Submitted fix on funclib, this one can be closed one it is merged.

**Comment by theVKC** [comment]
This issue actually doesn't belong here, because it's related to FuncLib. As such, I'm closing this now, but will check it out on FuncLib shortly.

**Comment by theVKC** [comment]
Also, @Farleight, I don't think you could have known that Functions Library stuff goes on another repository. I should update my instructions to reflect that.
