### ISSUE TITLE
Update NOTES - SHELTER FORM RECEIVED to be an actions script with additional handling

### ISSUE THREAD

**Issue by RobertFewins-Kalb** [MN-Script-Team/DHS-MAXIS-Scripts#1207]
For the sake of ME reviewers, NOTES - SHELTER FORM RECEIVED should be case noting the date that the SF was received by the agency.

**Comment by IlseFerris** [comment]
Agreed.  We should also consider enhancing the ability to update ADDR, SHEL and HEST.

**Comment by ruthmaloney** [comment]
Nice

Ruth Maloney

**Comment by RobertFewins-Kalb** [comment]
Also doable @IlseFerris . I'm also going to add err_msg handling.

Operation Wind Tunnel

**Comment by IlseFerris** [comment]
Awesome!

**Comment by RobertFewins-Kalb** [comment]
I'm also going to add a field for actions taken.

**Comment by RobertFewins-Kalb** [comment]
And I'm going to change "cost per person" to "Client's share of rent"

**Comment by RobertFewins-Kalb** [comment]
This is turning into a major doing. @CDPotter  and I have discussed the fact that the SF has GRH information on it. There should be functionality to support the GRH side of things.

**Comment by theVKC** [comment]
I lean toward reinventing this as an actions script. Thoughts-es?

**Comment by theVKC** [comment]
Also: @RobertFewins-Kalb... please indicate more detail in your message header please. Thanks please.

**Comment by RobertFewins-Kalb** [comment]
RE: ACTIONS script. My thought is yes.

**Comment by IlseFerris** [comment]
I always hoped that this would turn into an actions script.  For the GRH side, are you thinking it's going to update FACI?  That's a slippery slope.

**Comment by RobertFewins-Kalb** [comment]
A very slippery slope, and one that is fraught with peril. I would like to get more information about what GRH does with a shelter form to determine if that's angle is viable.

**Comment by IlseFerris** [comment]
Indeed!  If you need help on your quest I would be willing to help you.  #SamandFrodo #OneActionToRuleThemAll

**Comment by RobertFewins-Kalb** [comment]
I think I have it all worked out... check it OUT!!!

![image](https://cloud.githubusercontent.com/assets/7842016/10298372/1f91f5a8-6ba4-11e5-9e0a-6bfb4ec6afab.png)

**Comment by RobertFewins-Kalb** [comment]
...and I know you see "Check here to have the script update ADDR, SHEL, and HEST...and, yes, it totally does that. I'm going to check to make sure all my procedures are kosher and then submit the code when the code freeze is lifted.

**Comment by RobertFewins-Kalb** [comment]
please check out case notes on training case 226398 for examples of the case note. I'm eager to get some input.

**Comment by RobertFewins-Kalb** [comment]
I'm going to submit a pull request for this to close the issue (the script is finished) and wait to see what, if any, interest there is from the GRH peeps.

**Comment by RobertFewins-Kalb** [comment]
Going to create a new pull request with ACTIONS - SHELTER EXPENSE VERIF RECEIVED, and an update to the ACTIONS main menu. Manual processing time has been included.
