### ISSUE TITLE
MFIP to SNAP enhancement

### ISSUE THREAD

**Issue by IlseFerris** [MN-Script-Team/DHS-MAXIS-Scripts#1211]
Error handling in case there is no MFIP active on the case?

**Comment by Farleight** [comment]
I have nothing productive to say, but I like the word "enchancement."

**Comment by IlseFerris** [comment]
Don't judge me @Farleight 
LOL!

**Comment by Farleight** [comment]
I'm not judging. It should legitimately be a word. An enhancement that makes a thing more enchanting. Like a Pygmalion enchancement.

**Comment by theVKC** [comment]
@IlseFerris, why would it be used if there's no MFIP active on the case? Would this be "in case MFIP already closed and we're case noting after the fact?" I might be missing a thing, and I don't want to be.

**Comment by courtrightd** [comment]
I don’t have time to look at it today, but is this an issue where we get a script error that I didn’t account for if someone tries to run the script in the wrong situation?   If so, I can take it.

**Comment by theVKC** [comment]
@courtrightd, I'll assign it to you. Feel free to add it whenever, but note that the beta release goes out today (script freeze starts tomorrow). No big deal on this issue, just thought I'd let you know.

**Comment by IlseFerris** [comment]
Well it shouldn't be used if there's no MFIP, but this, as you know, may not stop people from using it, and then reporting an error.  Just thinking ahead on some error handling is all.  Not a super priority.

**Comment by courtrightd** [comment]
Makes perfect sense, I’ll get it fixed for the next release.
