### ISSUE TITLE
Bulk Lists may not working with some multicounty agencies. 

### ISSUE THREAD

**Issue by RobertFewins-Kalb** [MN-Script-Team/DHS-MAXIS-Scripts#1213]
Worry not. I am on it.

**Comment by RobertFewins-Kalb** [comment]
#IGTS

**Comment by theVKC** [comment]
I added these three, @RobertFewins-Kalb. A couple of things:

1. Not a critical bug. Only affects a few people statewide.
2. Any more scripts affected? If so, please pull them to master and beta this week, as this is a bug fix.

**Comment by theVKC** [comment]
@RobertFewins-Kalb, this is done, right?

**Comment by RobertFewins-Kalb** [comment]
I believe so. Looks like I updated BULK - INAC LIST as well, and I'm pretty sure the other BULK list scripts that needed multi-county handling already had it.

**Comment by theVKC** [comment]
Thanks @RobertFewins-Kalb!
