### ISSUE TITLE
Notes - Approved Programs - CS disregard wcom may have an old date

### ISSUE THREAD

**Issue by Y-Lor-Y** [MN-Script-Team/DHS-MAXIS-Scripts#1217]
The CS disregard fiated wcom note to client has the earlier release date of 07/01/2015.  So that we're align to when to start this disregard, DHS puts this back on the table effective 10/01/2015.  Should this date be changed to 10/01/2015 for the WCOM to not confuse the client?

I can take this one on.

**Comment by theVKC** [comment]
Anyone have any thoughts on this?

**Comment by courtrightd** [comment]
Yeah – it definitely has an old date, and I’m worried we may have clients rather unhappy if they start receiving disregard in Oct.  but the notice says it was effective 7/1/15.

**Comment by theVKC** [comment]
@Y-Lor-Y, if you want to take this one on, be my guest. If you could pull it into both master and BETA, that'd be swell. I'm going to tag this as a bug, because the date is merky and probably considered incorrect.

**Comment by RobertFewins-Kalb** [comment]
Additional problem!!!

The script is set up to write to a notice on WCOM row 7. But we originally built the WCOM to include a DO/LOOP to find the appropriate notice. 

Whoever does this needs to make sure they are building a do...loop around this...
![image](https://cloud.githubusercontent.com/assets/7842016/10342398/823ee162-6cde-11e5-9c8e-02a067a7bf00.png)


...to make sure the script is finding the appropriate notice.

**Comment by RobertFewins-Kalb** [comment]
@Y-Lor-Y , can I tackle both issues? I know exactly what needs to get done.

**Comment by Y-Lor-Y** [comment]
@RobertFewins-Kalb @theVKC  I'm okay with that.  Take it on!  Also, I've just noticed, ontop of the date change:  row 470, that's where the case note to the spec/wcom - the date change from July to October.
Not that this is an error, but for the display of the case note, row 548, col 72, has an extra space.
There is also another minor typo:  Row 548, Col: 108,  "as" should be "has" right?

**Comment by RobertFewins-Kalb** [comment]
Also, APPROVED PROGRAMS is getting the Operation Wind Tunnel treatment for err_msg handling.

**Comment by theVKC** [comment]
Resolved by #1227.
