### ISSUE TITLE
Enhancement Request -- NOTES - APPROVED PROGS -- Add checkbox to indicate the approval of expedited SNAP with postponed verifs

### ISSUE THREAD

**Issue by RobertFewins-Kalb** [MN-Script-Team/DHS-MAXIS-Scripts#1219]
Thinking something like this...

![image](https://cloud.githubusercontent.com/assets/7842016/10342237/c59bc87c-6cdd-11e5-957e-5cfd2e40f105.png)

...the check box should modify the header to draw attention to the fact that the client's benefits are open FOR NOW but will not continue to remain unless the agency receives specific docs.

**Comment by theVKC** [comment]
Any thoughts @ruthmaloney?

**Comment by RobertFewins-Kalb** [comment]
We will submit a fix for everything but that checkbox. It's all written into the code but commented out so all we would need to do is remove 5 comment marker thingys.
