### ISSUE TITLE
CRITICAL BUG -- url for NOTES - INCARCERATION is not valid in the NOTES main menu

### ISSUE THREAD

**Issue by RobertFewins-Kalb** [MN-Script-Team/DHS-MAXIS-Scripts#1222]
I will submit a fix.

Thunderbirds are go!

**Comment by RobertFewins-Kalb** [comment]
I'm going to pass the dutchy to @IlseFerris  on the left hand side

**Comment by IlseFerris** [comment]
Got it!  Resolved with pull requests #1223 and #1224

**Comment by theVKC** [comment]
A friendly reminder: please test new scripts and changes to the menu before pulling them, folks.

**Comment by IlseFerris** [comment]
In my measly defense, the script hadn't been pulled yet, so I wasn't able to test it...wah wah...

**Comment by theVKC** [comment]
wah wah indeed.
