### ISSUE TITLE
New Script Idea -- FSET/ABAWD Double Checker Tool

### ISSUE THREAD

**Issue by RobertFewins-Kalb** [MN-Script-Team/DHS-MAXIS-Scripts#1231]
Here are the thoughts...
* The script would look for clients that are coded as needing to attend FSET and who are ABAWDs...
* The script would perform a maxis double check, looking at the EATS group, then checking the age and disability status of the people in the EATS group. Then it would check JOBS, UNEA, SCHL, PROG, PBEN and PREG to make sure that the client that is coded as an ABAWD and needs to attend FSET is actually coded correctly.
* The script could exist in 3 different iterations (once the logic is built, building the different iterations would be extremely easy)... BULK, ACTIONS, and DAIL Scrubber

**Comment by RobertFewins-Kalb** [comment]
The DAIL Scrubber could be run off the PEPR message informing the worker that the client had used their 3 months of ABAWD eligibility.

The ACTIONS script would be run one case at a time.

The BULK script would be run for an entire caseload or an entire agency. @CDPotter  and I are submitting a request for a report to identify all the clients that are coded 30/10 or 30/11 so we do not have to run the BULK script on 23,000 cases. Ideally, the BULK script would run from that existing report and highlight the cases where the client is coded elsewhere with a potential exemption from FSET and ABAWD.

**Comment by RobertFewins-Kalb** [comment]
@ruthmaloney , do you have any thoughts on the matter?

**Comment by theVKC** [comment]
I for one love this idea.

**Comment by ruthmaloney** [comment]
I love the idea also! We know there are a lot of cases that are not allowing the correct ABAWD exemptions. Commonly surrounding the most recent policy clarifications on WREG coding 21/04 (care of child <18) and 04/01 (care of an ill/incapacitated member). Our test samples also found issues with not allowing the exemptions for 22/01 (Applied/appealing SSI – related to PBEN) and 17/12 (RCA/GA recipients). And of course, some errors when there is a JOBS panel. Let me know if you want to discuss any of those areas further.

Ruth Maloney

**Comment by RobertFewins-Kalb** [comment]
This is live. I'm going to close the issue.

**Comment by theVKC** [comment]
@RobertFewins-Kalb, not sure if we should close this since it's only the ACTIONS part.
