### ISSUE TITLE
New Script Idea-- Bulk case list for MAXIS cases that have a related MNsure case.

### ISSUE THREAD

**Issue by jasont35** [MN-Script-Team/DHS-MAXIS-Scripts#1232]
Is there a way to have a script check all active MAXIS cases in your county and then check MMIS for an affiliated active MNsure case and list those cases and the affiliated case numbers in excel?

Example spreadsheet fields:

Case Name        MAXIS case #        MNsure case #       Active programs

**Comment by theVKC** [comment]
I wouldn't be able to devote time to this, but I think it sounds wonderful. Perhaps Anoka has something like this, either from when I was there or after? @CDPotter? @RobertFewins-Kalb? @mldietz?

**Comment by RobertFewins-Kalb** [comment]
In Anoka County, we use the fabulous Web-I tool to track that information.

**Comment by RobertFewins-Kalb** [comment]
There's a report in the area for MNSure (New Eligibility System) that will give you a list of all members in your county that are active in both systems. The output includes their PMI, SMI, Maxis Case Number, and MNSure Integrated Case number.

**Comment by RobertFewins-Kalb** [comment]
I have a script built to clean up that list. It takes about an hour to run, but it finds the maxis worker's x1 number and their supervisor. Then we filter the results and send them out to each supervisor.

**Comment by jasont35** [comment]
Thank you for the information Robert. Would I be able to use that script?

**Comment by RobertFewins-Kalb** [comment]
The code is right here...

https://raw.githubusercontent.com/RobertFewins-Kalb/Anoka-Specific-Scripts/master/UPDATE%20MAXIS%20MNSURE%20WEB%20I%20REPORT.vbs

A few things about it...

(1) You will need to update the file location and workbook names for it to work for you...
![image](https://cloud.githubusercontent.com/assets/7842016/10403974/34837a60-6e95-11e5-874e-c8d2bf85b6f8.png)

(2) The business about Internet Explorer is a message box that is continuously updated with the script's status information.

(3) You will need a user with access to the Web-I report.

**Comment by jasont35** [comment]
Thank You @RobertFewins-Kalb

**Comment by theVKC** [comment]
@RobertFewins-Kalb, would you be willing to submit this version of the script: a version that does NOT generate a list of each MAXIS case, but rather uses WebI info to do it? Any thoughts on that?

**Comment by RobertFewins-Kalb** [comment]
I will make some modifications, such as prompting the user to specify the location of the spreadsheet, but I will eventually get to it.

**Comment by theVKC** [comment]
Great! Thanks!

**Comment by RobertFewins-Kalb** [comment]
After consideration, I think this should be closed. The script we have requires regular user input on the back end to keep it current. If there is more interest, I am willing to revisit.

@theVKC, tear down this issue.

**Comment by theVKC** [comment]
Closing issue per @RobertFewins-Kalb's request. Can reconsider later.
