### ISSUE TITLE
CSR exempt IR enhancement--remove signature portion

### ISSUE THREAD

**Issue by IlseFerris** [MN-Script-Team/DHS-MAXIS-Scripts#1233]
Hennepin County worker requested enhancement. "When you run the CSR script for exempt review, it does not auto-pop your signature, it prompts you to sign your case note."

Worker signature could be moved to the initial dialog, and subsequent portion of the coding to add signature to exempt IR could be removed.

I can take this, unless someone at hackathon is looking for an easy win?

**Comment by theVKC** [comment]
@IlseFerris, couldn't the "sign your case note" just be set to worker_signature with a dialog? Wouldn't that solve the problem? Not everyone has the auto signature functionality...

**Comment by IlseFerris** [comment]
It could.  It's an extra step either way that I think can be streamlined by adding the worker signature field to the initial dialog.

**Comment by MelissaFox-Stearns** [comment]
I'll take this one! I could use an easy win :)
