### ISSUE TITLE
NOTES - Approved Programs - default the months of elig to case note to Current and Current + 1

### ISSUE THREAD

**Issue by C-Love** [MN-Script-Team/DHS-MAXIS-Scripts#1235]
Currently the script requires the user to manually update that they want 2 months of elig results case noted. This would be an enhancement to have the 2nd month default to current footer month + 1.

**Comment by theVKC** [comment]
@C-Love, has anything come of this?

**Comment by C-Love** [comment]
I am working on it. There are 2 issues on this script that I am tackling at the same time. I made some progress - 2 steps forward - 1 step back kind of thing.

**Comment by theVKC** [comment]
Good deal. Just thought I'd bump the issue, because I don't remember talking about it Monday. :)
