### ISSUE TITLE
Enhancement-MMIS message box reminder

### ISSUE THREAD

**Issue by devonne01** [MN-Script-Team/DHS-MAXIS-Scripts#1238]
Many times I've gotten HC renewals or CSR in late and MMIS has auto closed and I have updated my Maxis case and approved HC to continue only to forget to go into MMIS and re-open MMIS. Thinking about having a message box pop up that  if someone is processing HC that will remind them to update/check MMIS to make sure that it's active. Any input?

**Comment by theVKC** [comment]
I like it, but we'll leave it as a question/call for input.

**Comment by MelissaFox-Stearns** [comment]
That's a great idea! This happens often where people forget to update MMIS after approving or reinstating HC.

**Comment by StormageddonDLOA** [comment]
Good idea. I can take it if no one else wants it.

**Comment by devonne01** [comment]
If Veronica says go ahead. I'll take it since I was the one that put it out there. Shouldn't be to hard to add message box. But will let others know if I need help :)

**Comment by theVKC** [comment]
Go for it, @devonne01!

**Comment by theVKC** [comment]
Any update on this, @devonne01? If you haven't had time to do it, I might open it up to other scriptwriters. Trying to take down the issue list today.

**Comment by devonne01** [comment]
No, unfortunately I haven't had time. I was hoping to work on it at a hackathon but haven't been to one. I will be at the one in Stearns County in February but if you want to have someone else work on it; go ahead. I understand I'm sorry.

**Comment by theVKC** [comment]
If you're coming to the hackathon to work on it, I'll hold it for now. It's your only outstanding script issue, so no worries.

**Comment by devonne01** [comment]
Awesome.. Thank you. Yes Kelly and I are planning on attending on 02/08/2016!! I'll let you know if that changes..

**Comment by theVKC** [comment]
Great! Can you send an email with that, too? All this gets tracked with a calendar that's tied to my Outlook.
