### ISSUE TITLE
Check EDRS- Run for all household members automatically 

### ISSUE THREAD

**Issue by MelissaFox-Stearns** [MN-Script-Team/DHS-MAXIS-Scripts#1251]
I was thinking about enhancing the EDRS action script to automatically check for all household members instead of running it for each person. It could messagebox if there is a match to alert the worker before continuing onto the next member.

**Comment by MelissaFox-Stearns** [comment]
Done. This is super cool...
https://github.com/MN-Script-Team/DHS-MAXIS-Scripts/pull/1257

**Comment by theVKC** [comment]
(Reopening only because it's closed _by_ a pull request, I like order. :)
