### ISSUE TITLE
FMED: update the FMED panel, and case note the details of the medical expenses

### ISSUE THREAD

**Issue by IlseFerris** [MN-Script-Team/DHS-MAXIS-Scripts#1252]
Basically can update the FMED panel, and case note the details of the medical expenses (following CM 0018.12).  Since this is a sticky area for a lot of people, a kick a** tool would be amazing.

**Comment by CDPotter** [comment]
I'm not sure what you mean by following CM 08.12. What were you hoping the script do? My interpretation would be:

1: worker enters information into a dialog that mirrors the FMED panel 
2: variables are entered into FMED panel. 

My concern with my interpretation is it feels very 1:1 it would seem to be that everything entered into the dialog needs to be entered into MAXIS and the script wouldn't be doing much aside from a case note.

**Comment by theVKC** [comment]
update panel + case note = time saved over doing both separately.

If you don't want the script, I'll open it up to folks that do. I see value in this.

**Comment by CDPotter** [comment]
I can still do it, I just wanted a bit of clarification on what the vision was.

**Comment by theVKC** [comment]
@IlseFerris suggested it. Care to weigh in?

**Comment by IlseFerris** [comment]
Below is the part that I feel would be especially important information to be added to the functionality of the script and the case note. Very often a FMED panel exists, and there is NO documentation in case note re: budgeting of recurring and non-recurring medical expenses. 
My though is that the dialog can have an option/field  to case note how these expenses have been budgeted, as well as a place to note if a medical expense has not been used. Also reminders about using SIS-EW waiver obligations, Method B spenddowns and MA-EPD and MCRE premiums/obligations as FMED deductions as well.

For non-recurring medical expenses, the unit has these options:
* To allow the entire expense in 1 month.
* To average the expense over the remaining months of the current certification period.
* To allow the expense over the scheduled length of a payment plan. Clients may continue to use this expense as a deduction for the length of the payment schedule, even into another certification period.

If a unit has both recurring and non-recurring medical expenses in 1 month, list them separately and MAXIS will subtract the $35 medical deduction.

Units may choose to have fluctuating expenses averaged. They may also choose to have expenses which are billed less often than monthly averaged forward over the interval between scheduled billings or, if there is no scheduled interval, over the period the expense is intended to cover.

Do not use medical expenses from 1 certification period for a later period unless a payment schedule extends into that period. For applicant units, expenses must have been billed for the 1st time in the billing period before application.

**Comment by theVKC** [comment]
@IlseFerris, I like this. A lot.

**Comment by IlseFerris** [comment]
@CDPotter if you still want it, go for it, otherwise I'd be more than happy to take it :)

**Comment by CDPotter** [comment]
If you're got a good idea got for it. I had only gotten as far as designing the dialog. Seemed like the best idea to me was to read FMED fill in a dialog with up to 12(max fmed entries) rows with any info on there already and then have blank rows for each blank fmed row. Then have a other notes so people can explain their processes and then actions taken. (possibly adding in text for CM references). Here is my rough work so far (it crashed on me last night when I hit the dialog limit so it doesn't have everything). 
![2015-11-05 08_18_52-c__users_cdpotter_desktop_fmeddlg dlg - bluezone dialog editor](https://cloud.githubusercontent.com/assets/7841989/10970676/e8f4c426-8395-11e5-8b23-d2bc33bc6735.png)

**Comment by theVKC** [comment]
@CDPotter @IlseFerris because this is a SNAP area, and reeeeeeally error prone, I might be able to help with the development as well, especially if we do that sometime after next week... if you'd like assistance I might be able to swing this.

**Comment by theVKC** [comment]
Also, @CDPotter, I assigned you just to prevent anyone else from starting it. If @IlseFerris wants it, I can reassign it.

**Comment by theVKC** [comment]
@IlseFerris: think this will be done by Friday? Script freeze starts Tuesday.

**Comment by IlseFerris** [comment]
This one's going to have to be March I'm afraid

**Comment by IlseFerris** [comment]
I'm going to close this for now. My March is looking really fierce, and this has been getting the backseat for months now. Shut it down, Ferris. Shut it down.
