### ISSUE TITLE
New Script Idea -- Integrate the Web-I tool with scripts, enabling workers to double check their MAXIS cases against MNSure to determine if their client is active in both systems

### ISSUE THREAD

**Issue by RobertFewins-Kalb** [MN-Script-Team/DHS-MAXIS-Scripts#1253]
Anoka County is going to run something like this locally. The tool is quite crude -- it's just going to create a copy of the most recent master list (maintained manually) and the script will filter the entire spreadsheet according to the worker's search result, displaying the query criteria in the closing msgbox.

**Comment by theVKC** [comment]
Because you made it an issue... do you want to take this to add it statewide?

**Comment by theVKC** [comment]
@RobertFewins-Kalb, can I bump this? How's it going?

**Comment by RobertFewins-Kalb** [comment]
bump away. There doesn't appear to be any interest.

**Comment by RobertFewins-Kalb** [comment]
I haven't had any chance to make this more general (since the script relies on my input on the spreadsheet).

**Comment by theVKC** [comment]
Want I should close the issue?

**Comment by RobertFewins-Kalb** [comment]
Yes
