### ISSUE TITLE
Krabappel Enhancement -- Create Macro to Copy Template, Add New Workbook to Front of List, and Prompt User for New Scenario Name

### ISSUE THREAD

**Issue by RobertFewins-Kalb** [MN-Script-Team/DHS-MAXIS-Scripts#1259]
We are finding that for more technologically challenged users, the process of copying the template, adding it to the front of the list, and renaming it would be simpler if there was a button to simplify the process.

**Comment by RobertFewins-Kalb** [comment]
Then we could hide the template workbook along with the controls workbook to preserve the integrity of the software (it's not a script at this point...this thing is a massive beast and its developers are hereby granted the title Beast Master)

**Comment by theVKC** [comment]
:)

Only thing I worry about is that macro-enabled documents can sometimes be impossible to email to each other. Plus, Office 2013 has a tendency to open macro-enabled documents in a restricted mode (a setting needs to modify to make it a "trusted document"). If you feel the risks of confusion from that outweigh the risks of confusion from copy/pasting, be my guest.

**Comment by theVKC** [comment]
@RobertFewins-Kalb, was this done? Also, did you want to take this?

**Comment by theVKC** [comment]
@RobertFewins-Kalb, bumping again. Please respond.

**Comment by RobertFewins-Kalb** [comment]
I'll take a stab at it.

**Comment by RobertFewins-Kalb** [comment]
After consideration, I'm going to close this. The script we have requires a lot of user input on the back end. If there is considerable interest in this being more widely available, I am willing to revisit, but for now, it is dead.
