### ISSUE TITLE
Interview No Show.. New script or Enhancement? 

### ISSUE THREAD

**Issue by MelissaFox-Stearns** [MN-Script-Team/DHS-MAXIS-Scripts#1260]
I have heard from a lot of my co-workers here at Stearns that they would like a case note script for Interview No Show/ No answer when the client does not show or does not answer the phone for a scheduled interview. 

I realize there is a NOMI Script, however this only applies to SNAP cases. 
We also have the Lobby No Show script, however that indicates the worker paged the client. We don't page our clients here at Stearns. Here the client checks in at the front desk and then the interviewer is notified. 

I'm trying to figure out if maybe we should be looking at an enhancement to Lobby No Show or do a separate script. These are some of the changes I we would want to look at if we did an enhancement: 

- The Lobby No show could be changed to include scheduled appts (not just sameday interviews). Have the "Client was paged in the lobby" and 1st and 2nd page times be seperate and non-mandatory fields so other counties who don't use this system can still use the script. Instead we would just need a field for "Interview time" 

- Maybe the header could say something more generic like " No show for interview" or "Attempted phone interview- No answer" depending on what the worker checks instead of "Attempted to page client in Lobby" ?

- This script already has a checkbox to send the Nomi which is fantastic for new applications. It would also be cool if it did the Nomi script for FS recerts too. This could eliminate the need for the separate NOMI sent action script. 

- The script could also include CAF information like CAF Date, what programs applying for, or if it was a recert. This could be helpful if client calls back to reschedule. 

@C-Love  @theVKC  Any thoughts on this?

**Comment by C-Love** [comment]
We could certainly rework this to be more accommodating to other interview processes. We have a similar process where clients are scheduled to a worker and the worker is notified - but then occasionally they still leave. So - then the wording would just be adjusted. 

I was thinking to keep this one pretty simple as the interview no show is typically separate from programs being pended or processed and so didn't include any wording on the CAF information. My thought was that this would already be on the notes from when the CAF was pended or in MAXIS. 

We could certainly adjust it to apply to phone interviews. I would hope to keep the paging/calling times mandatory - it is our process to attempt to page/call the client twice to allow for missing the first one. Even if it was a scheduled in person interview - we still page them twice in case they miss the first one. Not sure about this but it would lose a lot of it's structure if we eliminated that aspect.

I had initially hoped to run the actual NOMI script from this script but we haven't really been chaining them in that way. I know we discussed those options yesterday - BUT I would want to make sure that workers don't have to enter information twice (that kind of defeats the purpose). We could certainly have a second check box for the Recert NOMI procedure but not run the actual script until we work that chaining thing out. 

I feel like I am rambling here. I think it's great to make some updates to the scope of situations this could be used for, like phone or scheduled. I would not want to lose the structure of the script as I think that is really helpful to encourage good client service. I also don't think this would be super helpful if it was too bulky, as a worker I don't want to spend too much time on a No Show.

**Comment by MelissaFox-Stearns** [comment]
It's aight, we can keep your's the way it is. Just something I was noodling over. 

I think then (at least here in Stearns) we need a script for when a client doesn't check in at the front desk for their In person interview or client doesn't answer their phone for their phone interview. And something that can be used for all program interviews. 
So I'm going to write this script. I don't hear any objections so here I go!

**Comment by C-Love** [comment]
What if we had 2 paths for this script - so an initial dialog that the worker can select scheduled or sameday.? Then the scheduled one would lead to what you are thinking, and sameday would lead to the one that exists. That way there is more flexibility without loosing the speed.

**Comment by MelissaFox-Stearns** [comment]
Heck yeah,  I can get on board that train!
How about this... I'll work on the dialog and script for my end and then I'll connect with you about possibly putting them together? 
In the meantime, I'm open for more feedback. Thanks Casey!

**Comment by theVKC** [comment]
I like the idea of modifying the one script to do both things. @MelissaFox-Stearns, @C-Love, either of you feel like taking it?

**Comment by MelissaFox-Stearns** [comment]
I can take it. I'll connect with @C-Love to help as needed :)

**Comment by C-Love** [comment]
@MelissaFox-Stearns - Rock on! Let me know what I can do. I will be at the next Stearns hackathon so we could connect then as needed.
