### ISSUE TITLE
Approved Programs error when 2 cash programs have different outcomes

### ISSUE THREAD

**Issue by C-Love** [MN-Script-Team/DHS-MAXIS-Scripts#1262]
Basically if a worker denies a cash program the same day they approve a different cash program, the NOTES - Approved Programs Script has difficulty. This might happen if Cash was pended on a family case that also has an SSI adult. Then MSA is denied and MFIP approved.

**Comment by theVKC** [comment]
Any ideas for a fix, @C-Love?

**Comment by theVKC** [comment]
@C-Love has volunteered. Thank you!

**Comment by C-Love** [comment]
@theVKC  Can we reopen this? The fix doesn't seem to address situations other than DWP/MFIP transition.

**Comment by theVKC** [comment]
Does your new script fix this, @C-Love?
