### ISSUE TITLE
MEMOS - Appointment Letter

### ISSUE THREAD

**Issue by Y-Lor-Y** [MN-Script-Team/DHS-MAXIS-Scripts#1266]
This is specifically for Ramsey County's location.  We have a 2nd location out in the hub, Community Action Building.  If we could have the addition with the Ramsey options in the dropdown box, please.
Address: 450 N. Syndicate, St. Paul, MN 55104.

Thanks.

**Comment by theVKC** [comment]
Is there a room number for that?

**Comment by theVKC** [comment]
Also, see #1271. If someone works on this issue, please add #1271 to the list too.

**Comment by Y-Lor-Y** [comment]
No, there's no room number.
I can try this.

**Comment by Y-Lor-Y** [comment]
Sorry...I found out that that location do have a suite #.  
Full address:  450 N Syndicate St. Suite 250 St. Paul, MN 55104.

**Comment by theVKC** [comment]
Good luck @Y-Lor-Y!

**Comment by Y-Lor-Y** [comment]
I take it you'll also assign me #1271 too?  I'm fine with that, too.

**Comment by theVKC** [comment]
No, that's closed. @Farleight took care of it. :)

**Comment by Y-Lor-Y** [comment]
okay, thanks! @theVKC

**Comment by Y-Lor-Y** [comment]
I was ask to put this on hold, until the supervisors talked about how our internal scheduling system "CAFE" is going to play out before submitting the changes.  I've already completed the changes, just need to wait for final direction before submitting the changes. @theVKC

**Comment by theVKC** [comment]
No problem, just tag the issue when you make the pull request!
