### ISSUE TITLE
HRF- Add case note grant info from Elig/FS for UHFS cases

### ISSUE THREAD

**Issue by MelissaFox-Stearns** [MN-Script-Team/DHS-MAXIS-Scripts#1268]
Coworker brought up today that the HRF has the option to check the box to case note grant info from Elig/Mfip, however if the HRF is for UHFS, it has no option to case note the elig results from SNAP. 

I think it would be cool if we also made a check box for the SNAP (UHFS) to case note the amounts.

**Comment by theVKC** [comment]
Do you feel like taking this on @MelissaFox-Stearns?

**Comment by MelissaFox-Stearns** [comment]
Yes! Assign away :)
