### ISSUE TITLE
Appt letter: Hubbard County intake address needs updating

### ISSUE THREAD

**Issue by theVKC** [MN-Script-Team/DHS-MAXIS-Scripts#1271]
They are at 205 Court Ave, Park Rapids, MN 56470. Any takers? Easy win.

**Comment by Farleight** [comment]
Never looked at that script before, but I'm assuming it only requires this?:

elseif worker_county_code = "x129" then 
	agency_office_array = array("Hubbard")


ELSEIF worker_county_code = "x129" THEN
    agency_address.street = "205 Court Ave" 
    agency_address.city = "Park Rapids" 
    agency_address.zip = "56470" 
 

If so, I can probably handle that.

**Comment by theVKC** [comment]
@Farleight, any chance you can pound it out in an hour or so?

**Comment by Farleight** [comment]
That depends if that was accurate or not. If so, yes, it's pretty much pounded. Do you assign now, or should I pull request?

**Comment by theVKC** [comment]
Go ahead and pull request, please and thank you!

**Comment by Farleight** [comment]
I did a thing... possibly even the correct thing, but we'll let that be a surprise.

**Comment by theVKC** [comment]
You're amazing, @Farleight! Thank you!

**Comment by Farleight** [comment]
I've always suspected so.
