### ISSUE TITLE
NOTES - Expedited Screening is no longer providing a msgbox of results when it can't case note

### ISSUE THREAD

**Issue by RobertFewins-Kalb** [MN-Script-Team/DHS-MAXIS-Scripts#1273]
@CDPotter had fixed this, but I believe doubtfire reduced the script's functionality.

**Comment by CDPotter** [comment]
I'm looking into a fix.

**Comment by theVKC** [comment]
"Fixed" = enhancement. #ImNotStillBitterAtAll

Also, I think a better, more permanent solution to our woes would be to modify the function itself to provide some sort of doublecheck like this. That way, this sort of thing would be detected.

I think it also speaks to a need for scriptwriters to consider testing multiple scenarios when working on enhancements. Had we tested an out-of-county case, we would have discovered this.
