### ISSUE TITLE
critical bug: BULK REPT INAC needs worker_county_code removed

### ISSUE THREAD

**Issue by IlseFerris** [MN-Script-Team/DHS-MAXIS-Scripts#1278]
Not working in all branches except for the county of origin

**Comment by IlseFerris** [comment]
Pull requests #1279-#1281 resolves this

**Comment by theVKC** [comment]
So, we reverted @IlseFerris' commits and had @RobertFewins-Kalb add back county-determination pieces. :) That was #1287.
