### ISSUE TITLE
Move Client Contact button

### ISSUE THREAD

**Issue by IlseFerris** [MN-Script-Team/DHS-MAXIS-Scripts#1284]
Reported on SIR discussion board: 
Is it possible to put the Client Contact button on the main power pad, instead of having to click Notes, then client contact?  This is probably the most used button, especially on intake days, and it would be nice to save a click.  Not sure if this can be customized without changing for everyone?  If so, please provide instructions.
Thanks!

**Comment by theVKC** [comment]
No. This would require all counties to upgrade their scripts, just to move a button. Plus, you do that for one script, and what comes next? Can't open those floodgates.

**Comment by IlseFerris** [comment]
Works for me.  Thanks!
