### ISSUE TITLE
CRITICAL BUG -- ACTIONS - CS DISREGARD FIAT is applying an incorrect amount b/c of scientific notation

### ISSUE THREAD

**Issue by RobertFewins-Kalb** [MN-Script-Team/DHS-MAXIS-Scripts#1297]
I have submitted a fix to master, beta, and release.

**Comment by theVKC** [comment]
How was this not caught? @RobertFewins-Kalb, I'll pull this in, but can you investigate why nobody flipping noticed this?!?

**Comment by RobertFewins-Kalb** [comment]
I have the same questions myself. We tested the hell out of this and it didn't dabble in the dark arts of scientific notation then. Thank the maker for those msgboxes.

**Comment by RobertFewins-Kalb** [comment]
If the script finds that the amount of disregard being applied is less than 0.01, it converts it to 0.

**Comment by theVKC** [comment]
@RobertFewins-Kalb, please insert that into a comment in the actual script, per issue #1298. :)
