### ISSUE TITLE
Add comments explaining your workaround, Robert

### ISSUE THREAD

**Issue by theVKC** [MN-Script-Team/DHS-MAXIS-Scripts#1298]
@RobertFewins-Kalb, on the CS FIATer, please add comments explaining why you did a scientific notation workaround, and how it works. Not critical, but please do it for me. Thanks!

**Comment by theVKC** [comment]
@RobertFewins-Kalb, can I bump this? Just need some comments from you explaining your clever workaround. Future generations depend on this.

**Comment by RobertFewins-Kalb** [comment]
I can do it right quick if'n you wants.

**Comment by theVKC** [comment]
I'n do

**Comment by RobertFewins-Kalb** [comment]
It's'n done... pull request #1360

**Comment by theVKC** [comment]
Thank'n you

**Comment by RobertFewins-Kalb** [comment]
Yes'm
