### ISSUE TITLE
Call for input Changing HCAPP verbiage

### ISSUE THREAD

**Issue by CDPotter** [MN-Script-Team/DHS-MAXIS-Scripts#1299]
The question has been tossed around here that the HCAPP verbiage in scripts like Closed Progs and Denied is misleading to support staff. The fear is they will advise the client of the incorrect method to reapply for HC benefits. 

Do people think we should update mentions of HCAPP to be something like "New HC application"? or would it just make sense to explain to people that HCAPP just stands for Health Care Application and doesn't refer to a specific form anymore.

**Comment by theVKC** [comment]
I like it!

**Comment by theVKC** [comment]
@CDPotter, we're discussing this at hackathon and I've made the decision that this is wise, however, we should probably create separate issues for each affected script. As such, closing this question. Good luck!
