### ISSUE TITLE
BUG Verifs needed checkboxes don't do anything

### ISSUE THREAD

**Issue by CDPotter** [MN-Script-Team/DHS-MAXIS-Scripts#1302]
Reported on SIR:

When box is checked for "DHS2919A -Verification A is sent" it is not carrying over into the case note.

Another issue with this script is it's not carrying over the Sent to AREP option to the case/note. Thought I'd mention that on this thread rather than creating a new thread since it's for the same script.

Submitting fix

**Comment by theVKC** [comment]
Resolved by #1303. Not sure why it didn't close.
