### ISSUE TITLE
New Script - Bulk - EMPS List Generator

### ISSUE THREAD

**Issue by Farleight** [MN-Script-Team/DHS-MAXIS-Scripts#1316]
Not my idea, but I saw it on the discussion board, and I don't see that anyone's working on it yet. Are they? If not, I have uncharacteristic full confidence in my ability to take this on... stemming mainly from the fact that I've already done it. 

Basically just a copy of the SWKR generator script, but for EMPS. I could even throw extra EMPS related info in there if we so choose. (Currently just worker name and agency)

**Comment by courtrightd** [comment]
Should be very similar to current stuff, but keep in mind the multiple caregiver problems you may have (the EMPS you are looking for might not be the first one.)   You may need to have it check elig to get the member numbers or something.  That’s the major issue I’ve had with pulling this info to my access database.  (And EMPS is seldom current, but this new script could fix that)

**Comment by Farleight** [comment]
Valid point. I'll have to play around with that. I could just have it check every member in theory, but that would make the whole process take significantly longer... Geez Dave, I'm trying to do easy things here... Why do you gotta be all "logical" about it?

**Comment by theVKC** [comment]
@Farleight, any update on this?

**Comment by Farleight** [comment]
Yes... I've spent some serious time thinking about it while doing other things. I soon hope to find time to do it while thinking about other things.

**Comment by theVKC** [comment]
Good deal. Let me know if you need anything!

**Comment by Farleight** [comment]
I've been relegated to MNSure duty at the county here, so I won't lie; it's going to be a long time before I get a chance to look at this again. If anyone else wants to take a stab at it, go ahead. If not, it's still on my future roster, but you can feel free to close the issue for now if you'd like. I can always bring it back later (whenever new scripts are being accepted).

**Comment by theVKC** [comment]
I'll leave it open for a week or so. If nobody comments on it, I'll close it. :)
