### ISSUE TITLE
MFIP housing grant work around

### ISSUE THREAD

**Issue by IlseFerris** [MN-Script-Team/DHS-MAXIS-Scripts#1318]
ACTION script to FIAT the $50 of counted HUD funds out of the MFIP budget (in FMBI?) to ensure that the housing grant is being added to the cases that are exempt from counting the subsidy income.  This would be similar to the Child support FIATer in nature, and maybe we should consider merging these since many MFIP cases need both FIATs.
I have a PDF from mentor meeting today that details out the steps. MAXIS Mentors were informed at this meeting that this will be fixed in MAXIS at some point in 2016, but no date has been given at this point.  I can send this document to anyone who wants it, but could not load it to the issue.

Thoughts on this?

**Comment by theVKC** [comment]
Do you want it?

**Comment by IlseFerris** [comment]
If it's still help wanted on Monday, then yes. I'm going to try to knock out some of my other issues prior to committing.

**Comment by theVKC** [comment]
@StormageddonDLOA has volunteered to take this on. Thank you!

**Comment by IlseFerris** [comment]
New POLI/TEMP reference for this: TE02.10.100 HOUSING GRANT WITH SUBSIDIZED HOUSING

**Comment by theVKC** [comment]
[WORKAROUND FOR SPECIFIC MFIP UNITS RECEIVING SUBSIDIZED HOUSING.pdf](https://github.com/MN-Script-Team/DHS-MAXIS-Scripts/files/25430/WORKAROUND.FOR.SPECIFIC.MFIP.UNITS.RECEIVING.SUBSIDIZED.HOUSING.pdf)

**Comment by IlseFerris** [comment]
@StormageddonDLOA any progress on this one?

**Comment by StormageddonDLOA** [comment]
Yeah I’ve got it done and a couple of my co-workers are testing it. Checked with Veronica on a couple changes I made to bring it more in line with the CS exclusion and got her approval.

**Comment by IlseFerris** [comment]
Awesome!
