### ISSUE TITLE
Action - CS Disregard Fiater

### ISSUE THREAD

**Issue by Y-Lor-Y** [MN-Script-Team/DHS-MAXIS-Scripts#1321]
I was running this script today and it did not seem to be working or something is off.
What happen is that the script would run just fine until it get to the parts where it checks for the UNEA panels - if found, it gives the message box that it found one of the three incomes type, to press ok to continue.  After it went through the UNEA panels checking and pressed OK to continue.  It then skips all the way down to the script end procedure message - showing the message that it is success and to run the approved program.  In actuality, no FIAT'ing was done.

So, the whole part of telling it to go and process the fiat'ing was skipped.

I'm looking at the coding...I noticed two area, not sure if they may be out of place or not.  Or, it could totally be something else.

Row 197, The Loop is not define, I thought Loops has to be define or conditioned.  Maybe not in this case?

Row 242's There is a transmit put on this row, just seems out of place to me.

Thanks,
Yang

**Comment by theVKC** [comment]
Was it just for one case, @Y-Lor-Y? We aren't seeing widespread reports of this issue, are we? Seems like if it were either of those things, we'd have widespread reports of problems, when in actuality I'm not seeing any such reports.

**Comment by Y-Lor-Y** [comment]
I tried it on one case only at this time.  I will test this out for cases that I can apply this script to test it out today and report back.

**Comment by CDPotter** [comment]
I've been emailing with Yang and it seems to be something to do with the MFIP_cash_status variable. The case is app close and the script will ignore cases where there's no MFIP and where the status is App close. According to the script the cash_status (from curr) must be <> "" AND <> "APP CLO" 

This looks like an addition from #1294 by @RobertFewins-Kalb maybe he can shed some light? I wasn't involved in this fix I'm afraid.

**Comment by Y-Lor-Y** [comment]
Thanks!  That explains it then.

**Comment by courtrightd** [comment]
I have seen this happen once as well, but haven’t had opportunity to narrow it down.

**Comment by theVKC** [comment]
Well, I know that @RobertFewins-Kalb is out until Monday. Anyone else want to take it on?

**Comment by courtrightd** [comment]
I’ll look at it this afternoon.

**Comment by theVKC** [comment]
Wonderful. Thanks @courtrightd! Next time I'm in SLC I'm buying you lunch. Thanks for all your help!
