### ISSUE TITLE
Check EDRS

### ISSUE THREAD

**Issue by MelissaFox-Stearns** [MN-Script-Team/DHS-MAXIS-Scripts#1324]
The variable name SSN_Number was incorrectly spelled SS_Number so it wasn't going through the SSN part of the check. This shouldn't have caused any problems because if there were any matches it would have caught the name. Anyway, the fix has been done and it seems to be working the way it's supposed to now. 
I pulled the fix to Beta and Release branches also 

Mel

**Comment by theVKC** [comment]
#1317 resolved this. Thanks @MelissaFox-Stearns!
