### ISSUE TITLE
Question on XFS Screening

### ISSUE THREAD

**Issue by C-Love** [MN-Script-Team/DHS-MAXIS-Scripts#1325]
The question has come up regarding XFS Screening, when the client leaves one of the CAF1 questions blank we have insufficient information to determine XFS, is it then acceptable to screen the application as NOT Expedited? Maybe @ruthmaloney can clarify. I apologize if this has been addressed already. Our screeners are asking. 

If we can screen them as not XFS, is there a way we can add an option for the script to note that answers were left blank and so we cannot determine them as XFS?

**Comment by CDPotter** [comment]
I've personally always operated on if it's blank it's a zero until stated otherwise. Seems better to err on the side of them being possibly expedited.

**Comment by theVKC** [comment]
We programmed it as "if it's blank, it's zero" to err on the side of caution. I'd love to hear if @ruthmaloney has any insight on this.

**Comment by ruthmaloney** [comment]
It's best to treat as expedited until you find it's not. Feds don't care why we go over the expedited processing timeframes. We need to do everything possible to meet those timelines. Our leeway is for the apps that we've done everything we can to process timely but the client fails to comply (ex. Mailed in app for homeless person with no phone - there's only so much an agency can do). Counties that do well with expedited numbers, treat incomplete apps as expedited.

Sent from my iPhone

On Oct 29, 2015, at 2:07 PM, Veronica Kahl Cary <notifications@github.com<mailto:notifications@github.com>> wrote:


We programmed it as "if it's blank, it's zero" to err on the side of caution. I'd love to hear if @ruthmaloney<https://github.com/ruthmaloney> has any insight on this.

—
Reply to this email directly or view it on GitHub<https://github.com/MN-Script-Team/DHS-MAXIS-Scripts/issues/1325#issuecomment-152289624>.


Caution: This e-mail and attached documents, if any, may contain information that is protected by state or federal law. E-mail containing private or protected information should not be sent over a public (nonsecure) Internet unless it is encrypted pursuant to DHS standards. This e-mail should be forwarded only on a strictly need-to-know basis. If you are not the intended recipient, please: (1) notify the sender immediately, (2) do not forward the message, (3) do not print the message and (4) erase the message from your system.

**Comment by theVKC** [comment]
@C-Love, does that answer your question? Would you mind if we close the issue?

**Comment by C-Love** [comment]
Thank you, this is very helpful. I will advise our screeners.
