### ISSUE TITLE
BULK MA-EPD/Medi Part B CEI script needs instructions on SIR

### ISSUE THREAD

**Issue by IlseFerris** [MN-Script-Team/DHS-MAXIS-Scripts#1332]
Pretty self-explanatory. Instructions are not there.

**Comment by CDPotter** [comment]
I could probably look at it tomorrow and write something up if you wanna assign it to me.

**Comment by theVKC** [comment]
Will do, and thank you!

**Comment by IlseFerris** [comment]
Thank you @CDPotter!

**Comment by CDPotter** [comment]
It has been submitted.
