### ISSUE TITLE
Enhancement PND2 interview status

### ISSUE THREAD

**Issue by CDPotter** [MN-Script-Team/DHS-MAXIS-Scripts#1333]
It was requested that the PND2 script be modified to document if a SNAP application has had an interview and what their expedited status is. I have made a modification and am testing it today. It will be slow testing due to the scope of the BULK script.

**Comment by theVKC** [comment]
Thank you! @ruthmaloney might like this one. :)

**Comment by ruthmaloney** [comment]
Yes, very much so! Anything to improve our expedited timeliness is appreciated!

Ruth Maloney

**Comment by CDPotter** [comment]
@ruthmaloney and @theVKC in testing various methods to grab this information it seems like finding expedited cases is quite the task. I ran a version of the script on the Anoka agency and found 225 pending SNAP cases, of those there was 1 priviledge I couldn't look at, 45 cases where FSCR states the case isn't expedited, and 177 cases without ELIG results. 

It seems like adding a useful/reliable column for expedited status might not be possible. We can easily add a column for interview completed or not (since that's pretty straight forward on PROG) and then end users can sort the days pending and see how many cases under 5 days haven't completed an interview. Thoughts?

**Comment by theVKC** [comment]
This was my concern too, @CDPotter. I think that a script as you suggest might be a good jumping off point, from which additional data points from supervisors and reviewers might uncover themselves.

**Comment by courtrightd** [comment]
Could the script check for the expedited screening script case note, and ignore the cases that don’t screen as expedited.  It would still list cases that didn’t have the expedited screen script run on them to be checked manually.  In our county, we try to make sure that script is run on every application received.

**Comment by theVKC** [comment]
There could be a column for "expedited screening case note status", where it could say "says expedited", "says not expedited", and "case note not found"...

**Comment by CDPotter** [comment]
Hm I could see it being a bit unreliable due to out of county screenings or clients putting wrong info into CAF1,  but I can add it easily enough.

**Comment by theVKC** [comment]
Remove commented out functionality in order to pull script into master, save commented out functionality for later. It's in a new branch here. @CDPotter, you can probably close your branch now (but leave the issue because I want to add it to master without the unnecessary functionality).

**Comment by theVKC** [comment]
Closing for now, will re-evaluate later.
