### ISSUE TITLE
BULK - DAIL REPORT needs comments

### ISSUE THREAD

**Issue by IlseFerris** [MN-Script-Team/DHS-MAXIS-Scripts#1335]
Comments, where are you? Trying to learn more about BULK scripts, and could use some comments on this script. @RobertFewins-Kalb can the gauntlet be passed to you?

**Comment by RobertFewins-Kalb** [comment]
I can and shall. Sorry aboot that.

**Comment by IlseFerris** [comment]
Thank you! I'm just trying to reverse engineer and could use the comments.
