### ISSUE TITLE
Bug LTC 1503 not using footer month variable

### ISSUE THREAD

**Issue by CDPotter** [MN-Script-Team/DHS-MAXIS-Scripts#1337]
Report from workers:

Just reporting that I noticed the 1503 script is not updating panels in the footer month I select initially for a 1503.  It updates in the month I have Maxis in but not the footer month it initially asks about.  So for instance- I select the footer month of September but Maxis is in October- it only updates panels in October. Maybe not such a big deal but a couple of us noticed it and I figured I would bring that up. 

Seems like MAXIS footer month is collected but the script never actually enters it or changes the month. Any takers?

**Comment by theVKC** [comment]
@IlseFerris has volunteered. Thank you!
