### ISSUE TITLE
Enhancement Request -- MEMOS - APPOINTMENT LETTER -- add field for additional information 

### ISSUE THREAD

**Issue by RobertFewins-Kalb** [MN-Script-Team/DHS-MAXIS-Scripts#1340]
An LEP worker today requested that there be an additional field in MEMOS - APPOINTMENT LETTER for additional information for the client. She sets up a lot of interviews through interpreters and the appointment letter causes some confusion for her clients who are unaware of the interpreter service. 

The idea would be to add these additional notes at the end of the appointment letter in those (roughly) 8 lines that could provide additional notes to the client without the worker having to touch the letter a second time.

**Comment by theVKC** [comment]
@ruthmaloney, do you see/foresee a problem with adding text to the appointment letter? I know it's quite prescribed from a policy perspective, and we've gotten in trouble in the past for writing notes-to-the-client on there.

**Comment by ruthmaloney** [comment]
I think it’s fine to add information about interpreter services on the letter. If I understand this correctly, the worker wants to inform the client that they will be using an interpreter for the interview – seems to make sense to give them this information ahead of time.

Ruth Maloney

**Comment by Y-Lor-Y** [comment]
Or could a check box be put into this so that way it's an option.  If it's checked then it'll put the additional verbiage that the interview will have an interpreter, both on the CASE NOTE and SPEC/MEMO.

**Comment by theVKC** [comment]
My concern is that a blank "other notes for client" section could be misused. Only thinking of that based on the ME review I was part of at Anoka. Thoughts on that @ruthmaloney? Basically, it's an "add a checkbox for some canned text" vs. "add an other notes section and let folks do with it as they want" situation. I could go either way.

**Comment by ruthmaloney** [comment]
I agree with you Veronica, a blank “other notes” section could (and most likely would) be misused. I thought the intent was specific to using an interpreter for the interview. If this is still the case, I like the check box idea with text relating to the interpreter service.

Ruth Maloney

**Comment by theVKC** [comment]
Well then, @RobertFewins-Kalb, I'm going to close this issue. Feel free to create a new one for the specific checkbox for interpreter info if you'd like. Link back to this issue if you do that, please. Thanks!
