### ISSUE TITLE
Statistical Data - Manual timing

### ISSUE THREAD

**Issue by GayS** [MN-Script-Team/DHS-MAXIS-Scripts#1341]
It would be really helpful if scripts included manual time to complete script as part of the "gathering stats" language as standard practice.  This would assist all data reports to be consistent when analyzing amount of time saved by using scripts.

**Comment by theVKC** [comment]
This will be an ongoing project. As such, I'm self-assigning it to track.

**Comment by theVKC** [comment]
I'm removing the self-assignment. I decided that's messy to track.

**Comment by theVKC** [comment]
@MelissaFox-Stearns, @C-Love , @IlseFerris, and @StormageddonDLOA just updated each script, and I updated FuncLib. @GayS is monitoring the results in Stearns and will let me know when things look stable, in the next few days.

**Comment by GayS** [comment]
Stat collection continues to look like they are working properly.  However, we have only used two BULK scripts and a few MEMOS.

**Comment by theVKC** [comment]
I'm going to close this issue, and we can just create new individual issues if any trouble should occur. Thanks for monitoring it, @GayS!
