### ISSUE TITLE
Call for input on CAF/edrs update

### ISSUE THREAD

**Issue by IlseFerris** [MN-Script-Team/DHS-MAXIS-Scripts#1348]
Hennepin County worker asked if there way to promote/reiterate checking eDRS when using the CAF. My thought is that we could add a check box to the case number dialog of the CAF "edrs was checked for all adult HH members". If SNAP is checked, and the CAF TYPE is an intake, reapplication, add program or addendum then the CAF script will stop, and a message box will come up informing the worker that edrs needs to be checked for all HH adult HH members, and referring them to use the ACTION script. 

Can I get some feedback on this? Thanks!

![image](https://cloud.githubusercontent.com/assets/10836829/10916813/f7964e60-8222-11e5-87ab-531e5cc4c566.png)

**Comment by CDPotter** [comment]
With talk of killing the CAF in it's current incarnation I'd say we hold off on enhancements. Plus there's already a checkbox for EDRS at the end.

**Comment by IlseFerris** [comment]
Normally I would say we should wait too, but this is an area we are seeing missed more and more at our county. The checkbox on the last dialog is only case noting, this would stop the worker from going forward until they confirmed that it was checked (and then it would case note that the check was completed.)

**Comment by theVKC** [comment]
I also vote for waiting. I reallllly don't want to add more on to this already confusing situation. Plus, this doesn't apply to all programs, and I don't want to get jumbled up in logic there. I'd prefer we close this issue and evaluate it on SNAP intake path instead.

**Comment by theVKC** [comment]
@IlseFerris, can we close this?

**Comment by IlseFerris** [comment]
Sure thing!
