### ISSUE TITLE
Bug when hitting cancel on a DAIL Scrubber Hire Match

### ISSUE THREAD

**Issue by StormageddonDLOA** [MN-Script-Team/DHS-MAXIS-Scripts#1354]
When ever I hit cancel on a Hire Match when running the DAIL Scrubber the script does some interesting things, that I'm not sure even how to explain, and I have to stop script to get it to stop bugging out.

**Comment by CDPotter** [comment]
I can confirm I ran into this today too when I hit the x button on the new hire message.

**Comment by theVKC** [comment]
Any chance MAXIS is to blame, @CDPotter or @StormageddonDLOA?

**Comment by CDPotter** [comment]
Hard to say, just ran it on another person's dail (cleared mine already) and was able to reproduce it first try. I'd wager it's something with cancel confirmation?

**Comment by StormageddonDLOA** [comment]
Don’t know.

**Comment by CDPotter** [comment]
Most likely doubtfire related. Those new functions require case_number and a lot of the dail scrubbers just hit S on the fail.

**Comment by theVKC** [comment]
But that was over two months ago. We would have seen it last month.

**Comment by StormageddonDLOA** [comment]
Only if someone hit cancel.

**Comment by RobertFewins-Kalb** [comment]
The problem is MAXIS_navigation function. There's no do/loop around the dialog. It looks like the script is trying to navigate_to_MAXIS_screen but it is not working with a case number...

![image](https://cloud.githubusercontent.com/assets/7842016/10943659/e57bb8a6-82da-11e5-883f-f7b1eae45150.png)

**Comment by theVKC** [comment]
But we should have seen this last month. Can someone create a local version and test? I'm still running the QC sample so I'm out of commission.

**Comment by CDPotter** [comment]
Only if someone hit cancel and thought to report it. I added a do loop and reordered cancel_confirmation and maxis_nav and it works perfectly locally. Submitting fix.

**Comment by RobertFewins-Kalb** [comment]
My guess is that user so infrequently cancel the new hire DAIL scrubber script that we haven't had a chance to hit that error.
