### ISSUE TITLE
Update NOTES - LTC COLA Summary 2015 for 2016

### ISSUE THREAD

**Issue by C-Love** [MN-Script-Team/DHS-MAXIS-Scripts#1363]
User requested this update for LTC caseload. COLA processing is next month.

**Comment by theVKC** [comment]
Would you like to do this one, @C-Love?

**Comment by IlseFerris** [comment]
I can take this one if @C-Love doesn't have it started already

**Comment by theVKC** [comment]
Haven't heard from @C-Love on it. @IlseFerris, go for it if you want it!

**Comment by CDPotter** [comment]
There was a suggestion to add the UNEA amount in the title of the COLA script so the worker could easily view the new RSDI or SSI amount when looking at the title. Promised we'd pass it on. Thoughts?

**Comment by theVKC** [comment]
No. People can add it manually.

**Comment by theVKC** [comment]
(It gets realllllly tricky with multiple grant recipients)

**Comment by CDPotter** [comment]
Fair enough, thanks for the input!

**Comment by IlseFerris** [comment]
Agreed. A lot of these cases also have other UNEA besides just RSDI and SSI as well as multiple claim numbers.
