### ISSUE TITLE
Enhancement New Jobs/dail scrubber

### ISSUE THREAD

**Issue by CDPotter** [MN-Script-Team/DHS-MAXIS-Scripts#1364]
It was suggested that maybe we include the name of the job in the tikl to make it more clear which job the tikl is about. Thoughts?  (for ACTIONS - New jobs and Dail scrubber for new hire)

**Comment by theVKC** [comment]
I like it in theory. Do you think we have enough room on the TIKL for this info? If there's enough room, I think it's a good'n.

**Comment by CDPotter** [comment]
We've got 105 characters or about 2 empty lines on the TIKL to use. I think it should be able to work in conjunction with the TIKL function.

**Comment by theVKC** [comment]
Make it so!
