### ISSUE TITLE
ENHANCEMENT REQUEST -- ACTIONS - TRANSFER CASE -- new worker MEMO?

### ISSUE THREAD

**Issue by RobertFewins-Kalb** [MN-Script-Team/DHS-MAXIS-Scripts#1365]
A user in SIR has asked about adding the option to add a new worker MEMO to the in-county case transfer script. This was deliberately left off when the script was originally developed as it would be an annoyance to the worker to have to field calls about why the case was transferred.

Thoughts?

My vote is that if it is added, it should not be defaulted to checked.

**Comment by IlseFerris** [comment]
I don't love this as an option, but if this is something that counties could use, then ok with me. It should most definitely not be defaulted to checked.

**Comment by theVKC** [comment]
I think we _could_ do this, but I would want really, really clear explanations as to what it does within the script (I'm thinking a Yes/No MsgBox with the text on it).

Even so, I'd call for input on this. I could see it being annoying for the receiving agency.
