### ISSUE TITLE
NOTES - HRF -- cancel does not cancel the script

### ISSUE THREAD

**Issue by RobertFewins-Kalb** [MN-Script-Team/DHS-MAXIS-Scripts#1366]
The maxis_navigation and cancel_confirmation function calls are out of order.

**Comment by IlseFerris** [comment]
@RobertFewins-Kalb I can take that if you haven't started already

**Comment by RobertFewins-Kalb** [comment]
I'm already working on it. I'm making a few other updates including err_msg handling.

I would like to make sure we correct this for all the scripts where the problem exists, however. Here are the lines of code in question...
![image](https://cloud.githubusercontent.com/assets/7842016/11041357/f45789e0-86d6-11e5-90d1-ffd645535068.png)

**Comment by theVKC** [comment]
@RobertFewins-Kalb, a release is about to go out. Can I get an update on this?
