### ISSUE TITLE
BUG - Button doesn't work for new ES referral script

### ISSUE THREAD

**Issue by courtrightd** [MN-Script-Team/DHS-MAXIS-Scripts#1370]
Fix on it's way!

**Comment by IlseFerris** [comment]
@courtrightd did you fully test this?

**Comment by courtrightd** [comment]
Yes, tested the fix locally to the best of my abilities.

**Comment by IlseFerris** [comment]
Thank you, thank you! I'm excited to see this one in action :)

**Comment by theVKC** [comment]
Because this means the script wasn't tested, I need someone to quick test it. @IlseFerris? @courtrightd?

**Comment by IlseFerris** [comment]
Looks like it's working from my end of the world

**Comment by theVKC** [comment]
Can you ask one of the workers to test it @llseFerris?

**Comment by courtrightd** [comment]
The fix is working now for all users in SLC.

**Comment by theVKC** [comment]
Thank you @courtrightd!

**Comment by courtrightd** [comment]
I just set us back to a non-database agency, and retested, everything is working fine now with the button and the script.
