### ISSUE TITLE
CSES dail enhancement, case note to include HC income is excluded.

### ISSUE THREAD

**Issue by IlseFerris** [MN-Script-Team/DHS-MAXIS-Scripts#1373]
Requested from a worker on SIR; CSES - scrubber case note In a case where there it is a HC ONLY case (and the script disregards the income anyway), can the case note add "HC only - income excluded" or something? ------------------------------------------ ::: 10/15 CSES messages ::: * No HC review due at this time. Case is HC only - income excluded. --- ABC, using automated script. 

I don't know anything about processing child so I'm going to throw this out to the family workers.

**Comment by theVKC** [comment]
I am nixing this, I want all HC handling removed for MAGI. I don't want it to do anything for MAGI-only HC at all.
