### ISSUE TITLE
Remove stray "New!!!" notices from MAIN MENU scripts

### ISSUE THREAD

**Issue by theVKC** [MN-Script-Team/DHS-MAXIS-Scripts#1375]
Easy win. We should leave the ones from October forward. Just need to look through each. Anyone want it?

**Comment by theVKC** [comment]
I'm removing all the ones from October and back. By the time the release goes out, November will almost be a distant memory.

**Comment by theVKC** [comment]
Can we remove them from November forward? So only scripts that are new as of November or December would be included in this thing.

**Comment by StormageddonDLOA** [comment]
I believe they should all be updated now. Please let me know if I missed any.
