### ISSUE TITLE
Enhancements GRH HRF

### ISSUE THREAD

**Issue by CDPotter** [MN-Script-Team/DHS-MAXIS-Scripts#1376]
We had a few requests for updates to the GRH HRF.

It was requested to add the GRH DOC amount to the case note (in the calculation part). This one seems like a easy needed fix. 

It was also requested that we alter the title to read the previous month rather than the retro month and previous month. Currently if run for an 10/15 HRF it will read August/October HRF. The worker stated that this isn't needed as income isn't budgeted retrospectively for GRH. They use the actual income from 10/15 to budget the post pay for the 10/15 HRF. 

We could use some input on the 2nd one. Our thought is if we want to keep it the way it is we could maybe add an editbox so workers can edit the months written into the title if they so desire.

**Comment by theVKC** [comment]
I do not recall precisely who came up with that wording, it may have been @ramonalisa1. Any thoughts?

**Comment by CDPotter** [comment]
So it looks like there's a function in the script to autofill from FACI however the variable it autofills to isn't used anywhere.

Would it make more sense to write in code to just check DOC or edit the function in the funclib to check for DOC and add back a possibly missing editbox for FACI information.

Also any word on the header anyone who deals with GRH HRFS?

**Comment by theVKC** [comment]
What is "DOC"?

**Comment by ramonalisa1** [comment]
DOC stands for “Difficulty of Care” which is added on to the basic GRH rate.

Lisa M.
Financial Assistance Supervisor

P
Please consider the environment before printing this email.

CAUTION:  This e-mail and attached documents, if any, may contain information that is protected by state or federal law.  E-Mail containing private or protected information should not be sent over a public (non-secure) Internet unless it is encrypted pursuant to DHS standards.  This e-mail should be forwarded only on a strictly need-to-know basis. If you are not the intended recipient, please:  (1) notify the sender immediately; (2) do not forward the message; (3) do not print this message; and (4) erase the message from your system.

USDA is an equal opportunity providers and employer.

**Comment by CDPotter** [comment]
Had a few more suggestions for the overhaul.

-The opening dialog asks for GRH and HC checkboxes. The variables don't do anything. I want to incorporate the checkboxes into the header "November GRH/HC HRF Rec'd 11/1/15: Complete"
-The case note from GRH elig just grabs whatever is currently in ELIG for that month. I'm adding a check to not grab info that wasn't approved. (similar to approved progs)

**Comment by theVKC** [comment]
I wish I had more opportunity to work with GRH folks.

So, shall I assume you're taking this issue then?

**Comment by CDPotter** [comment]
Yes I am already working on it.

**Comment by theVKC** [comment]
Beautiful!

**Comment by CDPotter** [comment]
Issue was resolved with pull #1455 Closing.
