### ISSUE TITLE
Add DFLN to script

### ISSUE THREAD

**Issue by theVKC** [MN-Script-Team/DHS-MAXIS-Scripts#138]

**Comment by theVKC** [comment]
I'm bumping this. Anyone want it? @CDPotter, @RobertFewins-Kalb, @courtrightd, or @lpshanley?

**Comment by RobertFewins-Kalb** [comment]
Oh, hey...I'm working on this

**Comment by RobertFewins-Kalb** [comment]
Also, I'm going to close my earlier pull request and resubmit with my updates

**Comment by RobertFewins-Kalb** [comment]
Done. This issue can be closed.
