### ISSUE TITLE
Enhancements Bils Updater

### ISSUE THREAD

**Issue by CDPotter** [MN-Script-Team/DHS-MAXIS-Scripts#1384]
There was a suggestion to have the BILS updater end back at the top of the list so adding a Transmit and possibly looping shift pf7 back to the start of bils. Small quality of life suggestion. Thoughts?

**Comment by IlseFerris** [comment]
Was a reason given? I ask because the BILS panel can sort by Date, Ref Nbr, Service, Gross by hitting PF6.

**Comment by CDPotter** [comment]
Ok I have gotten clarification. The script currently navigates to BILS and opens edit mode(pf9). The dialog displays asking the worker to enter the BILS information. Here is where the workers would like it to show the most recent BILS so they can enter them into the updater dialog. Right now if you PF9 it will bring you to the end of the list which can be bills from many years ago meaning the worker would have to click off the script and nav through the bils to get back to the top. (seem to affect both updating and adding new bils functions of script)

**Comment by IlseFerris** [comment]
OK then that makes sense and is a good enhancement. I like it.

**Comment by CDPotter** [comment]
K, I'll get on it then!
