### ISSUE TITLE
Citizenship/Identity verified enhancement/DAIL scrubber

### ISSUE THREAD

**Issue by IlseFerris** [MN-Script-Team/DHS-MAXIS-Scripts#1387]
Request from worker wondering if one of the options under citizenship proof can be something like "client attested, not required for SNAP(or program)" or something like that (I suppose n/a might also work). Really just wondering if there's a policy reason NOT to do this. We think this could be a good way to reiterate that this script should be run for all cases, specifically SNAP cases for identity. @ruthmaloney @theVKC

**Comment by ruthmaloney** [comment]
Self-attestation is not an option for non-citizens for SNAP. Is there a way to ensure this isn’t missed for non-citizen applicants?

Ruth Maloney

**Comment by theVKC** [comment]
I don't think there's a way it can be missed... that's really hard to foolproof. I'd like to close this issue if that's OK with you @IlseFerris.
