### ISSUE TITLE
Enhancements MA-EPD EI FIATer (make memb # do something)

### ISSUE THREAD

**Issue by CDPotter** [MN-Script-Team/DHS-MAXIS-Scripts#1392]
The script collects member number but it doesn't actually navigate to the proper jobs panel based off of it. Provides problems for non-memb 01 MA-EPD cases. I can tackle next week unless someone else wants it today.

**Comment by theVKC** [comment]
Just to be clear: we're talking about the MA-EPD EI FIATer, right?

**Comment by theVKC** [comment]
It's yours!

**Comment by CDPotter** [comment]
Correct, and thanks!
