### ISSUE TITLE
Enhancements Postponed WREG WCOMer (add tikl)

### ISSUE THREAD

**Issue by CDPotter** [MN-Script-Team/DHS-MAXIS-Scripts#1393]
I want to add a tikl to remind the worker to close the case in 10 days if verif isnt returned. Since the approval is a work around the case won't automatically close for postponed verifs. I think after the WCOM is added a tikl could help the worker remember to close the case on time. I can do this next week.

**Comment by theVKC** [comment]
What script is this for?

**Comment by CDPotter** [comment]
The script is a MEMO script that adds the WCOM for when we have to postpone WREG verifs like drug treatment and disability. The worker has to use a work around in MAXIS to approve SNAP but then remember to close the case properly since according to MAXIS nothing was actually postponed.

**Comment by theVKC** [comment]
So, this is a new script? We're under a script freeze. Unless I'm missing something...

**Comment by RobertFewins-Kalb** [comment]
Enhancement to this'n

![image](https://cloud.githubusercontent.com/assets/7842016/11159295/f03f4078-8a23-11e5-8891-aef0c89b141e.png)

**Comment by theVKC** [comment]
Aaah, I see. It's a new one, that's why I didn't remember it off the top of my head. Do you want it, @CDPotter?

**Comment by CDPotter** [comment]
Yes I do.
