### ISSUE TITLE
Closed Progs intake date bug (adding checkbox to sanction case)

### ISSUE THREAD

**Issue by CDPotter** [MN-Script-Team/DHS-MAXIS-Scripts#1394]
Currently we are running into problems with workers using the closed progs script when sanctioning someone. The script adds a reinstate/intake date which is incorrect as my understanding is that if the client closes for non-coop and start their sanction they will have to serve out their sanction. I was thinking a checkbox and editbot (to enter how many months) to edit the verbiage would be good. Thoughts @theVKC and @ruthmaloney 

Per CM:

Apply the sanction policy until the client does 1 of the following:

Serves the minimum sanction period and verbally agrees to comply with SNAP E&T during the SNAP application process.

Leaves the unit's home.
 
  -If a unit member who failed to comply joins another unit as that unit's PWE, the entire new unit is       ineligible for the rest of the disqualification period.
 
  -If a unit member who failed to comply joins another unit where that person is NOT the PWE, ONLY that person is ineligible.

  -If a unit is disqualified because the PWE failed to comply and a new person who has not committed any violations joins the unit as the PWE, end the disqualification for the other unit members. Require a new application and prorate benefits from that date

Becomes exempt from work registration or SNAP E&T participation.

**Comment by ruthmaloney** [comment]
I like the idea.

Ruth Maloney

**Comment by theVKC** [comment]
Do you want it, @CDPotter?

**Comment by CDPotter** [comment]
Yes I do.

**Comment by theVKC** [comment]
Also, I called this a bug because it's a policy issue. It can go through despite a beta freeze (it would go in master and beta at this time)

**Comment by CDPotter** [comment]
Thoughts on verbiage? @theVKC @ruthmaloney 

"SNAP is entering sanction for ## months. If client does not comply by closure date ##/##/## client will enter sanction for SNAP. Refer to worker for details on compliance."

**Comment by theVKC** [comment]
This is, of course, for the case note? (Just being clear.)

I'd rather see a date range _and_ an amount of months, but that's just me.

**Comment by CDPotter** [comment]
Yes this is just for a case note. I can totally manipulate the variable, figured I'd keep it simple at first then expand based on need. So maybe:

"SNAP is entering sanction for ## months MM/YY-MM/YY. If client does not comply by closure date ##/##/## client will enter sanction for SNAP. Refer to worker for details on compliance."

**Comment by CDPotter** [comment]
So I've had it sitting on my desktop for a while now in working form. I'm going to submit what I have.

**Comment by CDPotter** [comment]
Merged 12/14/15
