### ISSUE TITLE
Baby Born/HHLD comp change script crossover

### ISSUE THREAD

**Issue by StormageddonDLOA** [MN-Script-Team/DHS-MAXIS-Scripts#1399]
The HHLD comp change script includes a dialog box if the client is reporting a baby being born. They are both incredibly similar making the baby born script redundant. 

Screen shots of both dialog boxes are attached.

**The case number shown is a fake case number.**

![baby born script dialog box](https://cloud.githubusercontent.com/assets/13385361/11158483/1245a474-8a1e-11e5-8a78-6a95d5509797.PNG)
![hhld comp change - baby born dialog box](https://cloud.githubusercontent.com/assets/13385361/11158489/18087de6-8a1e-11e5-9486-21c03d76dd71.PNG)

**Comment by theVKC** [comment]
I'm in favor of a new optional first dialog that contains case number and "change reported" as a dropdown. If you select "baby born", it goes down the baby born path. Then, we get rid of the duplicate script. Thoughts?

**Comment by StormageddonDLOA** [comment]
Sounds good to me.

**Comment by theVKC** [comment]
I still want other feedback. @MN-Script-Team/county-agency-scriptwriters?

**Comment by courtrightd** [comment]
I really like the initial dialog/dropdown, that leaves the door open to future enhancements without having to redo the whole script or add more new scripts.

**Comment by theVKC** [comment]
Completely agreed. This actually ties into an issue from @MelissaFox-Stearns's work:  #1036. I could totally see merging "change reported" and "household comp change" together as well. Thoughts?

**Comment by devonne01** [comment]
I agree with David, it leaves the door open for future..

**Comment by theVKC** [comment]
Project Bowie? Ch-ch-ch-ch-changes! We could:

1. Create an initial dialog with all the "change reported" type scripts we can muster up.
2. User checks which changes they are dealing with.
3. The checkboxes chain load each new script in the chain. You could even include a selector for "number of times to run the script".

This would require a pretty sizable dialog upgrade to dynamic dialogs, but it's do-able and I think it could really streamline how users find, discover, and use scripts.

**Comment by IlseFerris** [comment]
Just for one day

**Comment by CDPotter** [comment]
GIST of our ideas from Hackathon today

https://gist.github.com/CDPotter/8fab998bbe4b048db135

**Comment by theVKC** [comment]
@StormageddonDLOA has volunteered for this one. Thank you!
