### ISSUE TITLE
Enhancement to REPT REVS for error reduction

### ISSUE THREAD

**Issue by courtrightd** [MN-Script-Team/DHS-MAXIS-Scripts#1406]
Adds two optional (with checkboxes) features to REPT/REVS pull data to excel to assist with auditing SNAP reviews for accuracy:
- Checks if an autoclose notice was sent, and enters info about the type of notice. (To assist supervisors with choosing cases to audit for timeliness and accuracy.)
- Checks for errors in updating STAT/REVW by going to case/note on cases that are coded with "N" and looks for the words "CAF received" or "CSR received" in 45 days prior to REVW date.  On cases coded "I" looks for the word "approved" in prior 30 days to check for cases where worker forgot to approve the results.   This check would ideally be performed just before autoclose notices go out (on the 16th)   This will not be 100% accurate due to differences in entering case/notes, but testing in our county revealed very few false positives, and corrected plenty of case errors.

Run time on a bank with ~ 400 reviews was less than 5 minutes.
This will be ready to pull in for the next beta release, but I am very open to discussion / further enhancement suggestions.
@ruthmaloney

**Comment by theVKC** [comment]
I LOVE THIS

**Comment by ruthmaloney** [comment]
Love it and thank you for thinking it out so well! Am I able to test it or not till it’s released? What types of errors/trends did you find?

Ruth Maloney

**Comment by theVKC** [comment]
I can help you test it, Ruth!

**Comment by courtrightd** [comment]
Current version is located on PATCH-1 in my repository, here:
https://github.com/courtrightd/MAXIS-BZ-Scripts-County-Beta/blob/patch-1/Script%20Files/BULK/BULK%20-%20REPT-REVS%20LIST.vbs
