### ISSUE TITLE
Returned Mail Script enhancement.

### ISSUE THREAD

**Issue by StormageddonDLOA** [MN-Script-Team/DHS-MAXIS-Scripts#1411]
I received a request to make some additions to the case note on this script. The changes are in quotes below.

•	For mail with no forwarding address:

Returned mail received "from post office on"
"From address:"
*No forwarding address was indicated.
*Sending verification request to last known address. TIKLed for 10 day return.     
(NOTE generated via BULK script) 
Worker signature

•	For mail with a forwarding address:

Returned mail received 'from post office on"
"From address:"
"Forwarding address provided:"
Updated Addr to match forwarding address. Forwarded returned mail to current address. Sent appropriate returned mail paperwork for current programs.
(NOTE generated via BULK script)
Worker signature

These additions make it easier for the worker to add the ADDR mailed to and the forwarding ADDR (if known) to the case note.

**Comment by StormageddonDLOA** [comment]
I can take this one.

**Comment by CDPotter** [comment]
How detailed are we allowed to get with people's addresses in case notes? @theVKC

**Comment by theVKC** [comment]
I don't know that it's a problem, it's not FTI. What I'm wondering is how you'd get it to fill in the previous address? Right now, the beauty is that it's bulkified. If you need to add a lot more information in the dialog, is it making it more complex than it needs to be?

**Comment by RobertFewins-Kalb** [comment]
Two thoughts...
(1) Why would we need to case note the address?
(2) I think that makes it more complex than it needs to be. We have STAT/ADDR for checking the address and CASE/ADHI for checking the address history.

**Comment by theVKC** [comment]
My worry is that STAT/ADDR can itself be wrong, and CASE/ADHI itself can be tricky to accurately read. The best source of this information is from the mail itself, which isn't really script-able as of 2015.

**Comment by StormageddonDLOA** [comment]
Yeah I thought of that too so the enhancement wouldn’t actually check the ADDR or try to pull anything into the case note. All this would be doing is adding those lines to the case note so the worker can manually add the address.

It was asked if we could add those lines because that is information that our process specialists are entering in here now per our guidelines on returned mail.

If this needs to be left as a county specific script that’s fine, I just thought other counties might like the addition too. It seems unlikely that Stearns County is the only county that case notes the ADDR rec’d back from and what the forwarding ADDR is (if there is one).

**Comment by theVKC** [comment]
@StormageddonDLOA I'm inclined to close the issue, and I'd encourage your staff to reconsider the policy. There is a gray area here with data privacy, and also (in my humble opinion) the benefits of the BULK functionality for returned mail far outweigh the need to case note specifics (you could just as easily store the info in an Excel spreadsheet, bypassing both issues).
