### ISSUE TITLE
Verifs needed bug.

### ISSUE THREAD

**Issue by StormageddonDLOA** [MN-Script-Team/DHS-MAXIS-Scripts#1415]
From the SIR discussion form:

"When running the script, it notes that forms were sent to the AREP, even when the box was not selected."

Just checked it and the bug still exists.

**Comment by StormageddonDLOA** [comment]
I'll work on it.

**Comment by CDPotter** [comment]
100% my fault. It's triggering IF verif_A_check = checked THEN write_variable_in_CASE_NOTE("* Forms sent to AREP.")

**Comment by StormageddonDLOA** [comment]
Yep. Nice easy fix. ☺
