### ISSUE TITLE
Krabappel bug with SNAP CSRs

### ISSUE THREAD

**Issue by RobertFewins-Kalb** [MN-Script-Team/DHS-MAXIS-Scripts#1417]
Can anything think of any reasons why cases appl'd 10/13/15 (app date of 6/6/15) wouldn't show up on REPT/REVS for 12/15? However cases appl'd 10/16/15 (app date 6/5/15) do show up.

-STAT/REVW was coded same for each case.
-Script was run after 5pm in most cases.
-Script was run by two different workers.
Below is my chart of things We've looked at:

CASE 1: Has job, appl'd 10/13/15 19:32, app date 6/6/15, by me (Doesn't show up on REVS for 12)
CASE 2: no job, appl'd 10/16/15 16:58, app date 6/4/15, by x102601 (shows up in REVS for 12)
CASE 3: has job, appl'd 10/13/15 17:28, app date 6/4/15, by me (Doesn't show up on REVS for 12)
CASE 4, has job, appl'd 10/16/15 17:25, app date 6/5/15, by me (shows up in REVS for 12)
CASE 5, has job, appl'd 10/13/15 17:01, app date 6/2/15, by x102601 (Doesn't show up on REVS for 12)

We're at a bit of a loss for ideas on why this happened.

**Comment by theVKC** [comment]
I don't know... the training region is weird.

**Comment by ruthmaloney** [comment]
6/6/15 is a Saturday?

Ruth Maloney

**Comment by RobertFewins-Kalb** [comment]
Not sure, but thinking that something happened to the training region on 10/13/15.

**Comment by theVKC** [comment]
Feel free to close this if you're done.

**Comment by theVKC** [comment]
Thanks @RobertFewins-Kalb!
