### ISSUE TITLE
Replace old FuncLib call with BETA-less call in NOTES scripts and test each script

### ISSUE THREAD

**Issue by theVKC** [MN-Script-Team/DHS-MAXIS-Scripts#1425]
LOTS AND LOTS of lines here...

**Comment by IlseFerris** [comment]
I can take these issues, and work on them on Monday (since I've already done something very similar with the 1st update).

**Comment by theVKC** [comment]
I am breaking this up into sections, unlike doubtfire which was wayyyyy too many scripts to update. I'll give you the NOTES section, but I want to see others try the others if possible.

**Comment by IlseFerris** [comment]
Works for me. We can work on this at hackathon on Monday if some attendees want to take a crack at the others.

**Comment by IlseFerris** [comment]
no trouble :)

**Comment by theVKC** [comment]
Resolved by @IlseFerris!
