### ISSUE TITLE
enhancement BULK menu swap

### ISSUE THREAD

**Issue by CDPotter** [MN-Script-Team/DHS-MAXIS-Scripts#1462]
I've been thinking for an end user it might make more sense for the OTHER BULK scripts to be the default menu rather than the LIST Gen scripts. Seems like people are more likely to use the OTHER BULK scripts rather than the LIST ones.

**Comment by theVKC** [comment]
I disagree. From what I hear the list ones are more popular. But, I'm open to other scriptwriters from other agencies weighing in. @MN-Script-Team/county-agency-scriptwriters?

**Comment by CDPotter** [comment]
Anyone else have any thoughts? If not I'm gonna close the list and we can make local adjustments.
