### ISSUE TITLE
BUG LTC Asset assessement writing assets multiple times

### ISSUE THREAD

**Issue by CDPotter** [MN-Script-Team/DHS-MAXIS-Scripts#1467]
A worker reported that the script is writing the same assets over and over again. Looking at the code it seems at line 239 it is looking for “NO MORE ASSETS TO DISPLAY” however when I go to the affected case and pf8 it displays “THERE ARE NO MORE ASSETS” at 19, 7. 

If anyone wants to tackle and test this one feel free. I don't think I will be able to tackle it this afternoon as I'm leaving shortly. 

![2015-11-25 13_47_02-s1 - anoka desktop - anoka scripted desktop - bluezone mainframe display](https://cloud.githubusercontent.com/assets/7841989/11407942/789f5d76-937b-11e5-92a9-fa664c66b9e0.png)

**Comment by theVKC** [comment]
Any ideas @IlseFerris?

**Comment by CDPotter** [comment]
I was able to get a few cases to verify that the verbiage in MAXIS has changed. I'll work on it today and do some testing.

**Comment by IlseFerris** [comment]
I started on this, so I can keep going. Unless you're deep into the rabbit hole already.

**Comment by CDPotter** [comment]
Ah nope I am not. Do you want me to email a few case numbers with multiple pages of asset assessments for testing?

**Comment by IlseFerris** [comment]
That would be amazing! Thanks @CDPotter

**Comment by IlseFerris** [comment]
MAXIS ASET function in training and production are different from each other, but only slightly. Just so everyone knows who dares goes in there. #MAXISFAIL

**Comment by theVKC** [comment]
Hmmm. Weird. When you're all wrapped up with this one, can you write up a description of exactly what's different, and send it my way? I might forward it to some folks here. We try to keep those areas in sync, so this sounds weird to me.

**Comment by IlseFerris** [comment]
Will do
