### ISSUE TITLE
New Script idea (for post freeze) Adding adult kids WCOM(input needed)

### ISSUE THREAD

**Issue by CDPotter** [MN-Script-Team/DHS-MAXIS-Scripts#1468]
While doing a training a few weeks back it was suggested that maybe we could have a WCOM for when you have to add an adult child to a SNAP family HH if they meet a caretaker exemption. Apparently there is a FAIT procedure and prescribed WCOM that goes along with this. 

Is anyone more familiar with this procedure?

**Comment by ruthmaloney** [comment]
It’s listed in POLI TEMP ABAWD STAT/WREG Coding – child under 18   TE02.05.70.03, starts on page 8

Ruth Maloney

**Comment by theVKC** [comment]
Thanks for the idea! FYI: I'd prefer to keep new script ideas off of GitHub for the time being. I would prefer to see current issues reduced before we add new ones that can't be worked on.

I tagged this as "POST FREEZE ONLY" and we can reevaluate it after the new scripts freeze ends. I'll now close the issue, we can reopen it after the freeze.

**Comment by theVKC** [comment]
The freeze is lifted! The freeze is lifted!

@CDPotter: do you still want this one?

**Comment by CDPotter** [comment]
I'm going to check with PCs at Anoka to see if it is still wanted and how it should be handled, but you can assign to me for the time being.
