### ISSUE TITLE
MFIP Sanction case note.

### ISSUE THREAD

**Issue by StormageddonDLOA** [MN-Script-Team/DHS-MAXIS-Scripts#1477]
It was reported that the MFIP sanction case note is giving an edit that 01/01/2016 is not a valid date of sanction.

**Comment by courtrightd** [comment]
I just had the same issue reported.  I can take it, I have time this afternoon.

**Comment by IlseFerris** [comment]
My email was down all day until about 2 minutes ago. We've had 2 reports with the same issue here.

**Comment by theVKC** [comment]
Please pull the fix into master, beta, and release branches. Note the FuncLib block is different for master than beta and release. Thanks @courtrightd!
