### ISSUE TITLE
Add data validation features to spreadsheet

### ISSUE THREAD

**Issue by theVKC** [MN-Script-Team/DHS-MAXIS-Scripts#148]
Unfortunately, we didn't have time for this yesterday. I'm adding bits and pieces of data validation here and there, but it won't be comprehensive. Anyone interested in taking it on?

**Comment by RobertFewins-Kalb** [comment]
I'm adding it as I go along.

**Comment by RobertFewins-Kalb** [comment]
On my data validation, here are examples of what I'm doing...
For WREG, ABAWD Status:
10 - ABAWD Counted Month
Then, when the script is reading the Excel file, I'm making it read only the left 2 characters. My rationale is that while I'm already in here, why not make it a little more user friendly...

**Comment by theVKC** [comment]
Love it!

**Comment by theVKC** [comment]
I'll take the rest.
