### ISSUE TITLE
STAT/PROG navigation button for the Power Pad? Thoughts?

### ISSUE THREAD

**Issue by theVKC** [MN-Script-Team/DHS-MAXIS-Scripts#1489]
Looking for feedback. It's easy enough and I'm finishing the new Power Pad today (I was out yesterday).

@MN-Script-Team/county-agency-scriptwriters?

**Comment by devonne01** [comment]
I don’t know that answer. I usually move all mine to pnd2 right away and then send out the appointment via the script.

**Comment by CDPotter** [comment]
Seems unnecessary to me.

**Comment by Y-Lor-Y** [comment]
In situation such as MFIP closed and SNAP needs to be open, client requesting EA, and etc.  I would support it being added.  Compare to ACCT button that is currently up, I'd say this one is often use less or equally then a PROG navigate.  I'd say if there are room, I'd support it.  If you're cutting for more room...not having it is fine, too.

**Comment by devonne01** [comment]
The worker said that she thinks it has to do with footer month? She got the application on 11/30/2015 and tried to do appointment letter in December and it didn’t work, went back to footer month 11 and it worked?

**Comment by theVKC** [comment]
@devonne01, this is the wrong thread for this reply. I think you meant to send that to the other thread. This is about adding a STAT/PROG button.

**Comment by theVKC** [comment]
@IlseFerris, your idea is hanging by a thread. Care to defend it?

**Comment by C-Love** [comment]
I would say that this navigation is used heavily by screeners. For counties that have people dedicated to screening/appling this makes a lot of sense.

**Comment by IlseFerris** [comment]
Super helpful to see application dates of multiple programs and status while staying in STAT

**Comment by theVKC** [comment]
If Ramsey and Hennepin want it, that's good enough for me.

**Comment by theVKC** [comment]
Oh, and I can break freeze on this because it's a nav script and updating the Power Pad over and over again isn't fun or desirable.

**Comment by courtrightd** [comment]
Lets just bend the rules for Hennepin once again.  ☺

**Comment by theVKC** [comment]
x127 + x162 = lots of persuasion

**Comment by theVKC** [comment]
(besides, because it takes a Power Pad update, most workers won't see it until at least January)

**Comment by IlseFerris** [comment]
Hey now @courtrightd, I resemble that remark...:)
