### ISSUE TITLE
EditBoxes on ACTIONS - TRANSFER are sized differently (master only)

### ISSUE THREAD

**Issue by courtrightd** [MN-Script-Team/DHS-MAXIS-Scripts#1494]

**Comment by theVKC** [comment]
Can you expound on this a bit, @courtrightd? Is this a question, a bug, an enhancement?

**Comment by courtrightd** [comment]
Just a consistency issue – looks like when HC got added to the dropdown, the editbox sizes changed from 15 to 20, so the in-county dialog looks different from the out-of county dialog.

**Comment by RobertFewins-Kalb** [comment]
There's also an orientation issue. The bottom of the text needs to align with the bottom of the edit box...

![image](https://cloud.githubusercontent.com/assets/7842016/11565296/ed2e3018-99a2-11e5-8847-b6c54aafc24f.png)

**Comment by courtrightd** [comment]
It's all cleaned up now - I just copied the existing version of the dialog from BETA and added HC to the dropdown.
