### ISSUE TITLE
BUG (funclib) Write to note functions

### ISSUE THREAD

**Issue by CDPotter** [MN-Script-Team/DHS-MAXIS-Scripts#1496]
Anyone else running into overwriting problems on the CAF? Looks like SHEL, COEX/DCEX, ACCT, and other assets wrote over the header and notes on income and budget. 

![2015-12-03 11_16_46-s1 - anoka desktop - anoka scripted desktop - bluezone mainframe display](https://cloud.githubusercontent.com/assets/7841989/11568119/f915c280-99af-11e5-92a1-0b6b2a6f10cf.png)

**Comment by theVKC** [comment]
The pattern here is weird. Typically with an overwrite you would see things in a sequence. The overwriting itself goes in order.

**Comment by theVKC** [comment]
This, though, has shel/hest at the top and coex toward the bottom.

**Comment by CDPotter** [comment]
Yeah that's why I'm leaning towards fluke but just wanted to throw it out there in case.

**Comment by IlseFerris** [comment]
It's running fine in Hennepin

**Comment by theVKC** [comment]
One thing that happens sometimes is people enter or home or something while it's running. I'm blaming that (or just some random fluke) and closing the issue.
