### ISSUE TITLE
URGENT: needs to approve Health Care

### ISSUE THREAD

**Issue by theVKC** [MN-Script-Team/DHS-MAXIS-Scripts#150]
I have some old (ancient) code which may help, but I've totally run out of time to do it:

https://github.com/theVKC/Anoka-Historical-Scripts/tree/master/Training%20case%20creators

If someone wants to steal my code (this worked on family HC as well as adult), or start fresh, we don't have a training case creator without this.

My advice: use Krabappel to make the fake case, then use a separate script for the approval, then pull request that separate script and I'll merge.

(Making cash a separate issue so that it doesn't need to be the same folks tackling both.)

**Comment by RobertFewins-Kalb** [comment]
I think this is done. I think the file PROJ KRABAPPEL HC APPROVAL.vbs (https://github.com/MN-Script-Team/DHS-MAXIS-Scripts/blob/master/Project%20Krabappel/PROJ%20KRABAPPEL%20HC%20Approval.vbs) does just that.

**Comment by theVKC** [comment]
Has it been merged into the main code though? Can we do that assembly?


Caution: This e-mail and attached documents, if any, may contain information that is protected by state or federal law. E-mail containing private or protected information should not be sent over a public (nonsecure) Internet unless it is encrypted pursuant to DHS standards. This e-mail should be forwarded only on a strictly need-to-know basis. If you are not the intended recipient, please: (1) notify the sender immediately, (2) do not forward the message, (3) do not print the message and (4) erase the message from your system.

**Comment by RobertFewins-Kalb** [comment]
I think it should be made a custom function and then added to the Krabappel FunkyLib. IF OK = True, THEN make it so I shall.

**Comment by RobertFewins-Kalb** [comment]
Done
