### ISSUE TITLE
SNAP E & T enhancement for banked ABAWD months

### ISSUE THREAD

**Issue by IlseFerris** [MN-Script-Team/DHS-MAXIS-Scripts#1500]
If a HH member is using counted ABAWD months, a manual referral will be needed. I will take this.

**Comment by IlseFerris** [comment]
I'm #1500 !!!!!!!!

**Comment by theVKC** [comment]
Woo Goo!

**Comment by IlseFerris** [comment]
Hey now...

**Comment by theVKC** [comment]
It'll never go away, @IlseFerris.

**Comment by IlseFerris** [comment]
Dang auto-correct
