### ISSUE TITLE
NOTES >> APPLICATION RECEIVED is not working in RELEASE

### ISSUE THREAD

**Issue by RobertFewins-Kalb** [MN-Script-Team/DHS-MAXIS-Scripts#1503]
The issue was reported in SIR and it looks like it's still brokes. It is working in MASTER but not RELEASE.

**Comment by RobertFewins-Kalb** [comment]
Sorry... the footer month is being erased when you run the script on a case that is not yet in REPT/PND2.

That's the issue.

**Comment by theVKC** [comment]
Basically, #1491 needs to be copied over into RELEASE. @RobertFewins-Kalb, are you on it?

**Comment by RobertFewins-Kalb** [comment]
yarp

**Comment by RobertFewins-Kalb** [comment]
Pull request merged...

**Comment by theVKC** [comment]
This was a duplicate of #1491, that due to the extra-long time between releases wasn't released from master as quick as we'd like. Generally, any critical bugs (that prevent the script from working entirely) should go to both master and release branches.

**Comment by RobertFewins-Kalb** [comment]
I'm not going to bother pulling to BETA since that is going extinct.

**Comment by theVKC** [comment]
Agreed
