### ISSUE TITLE
New ABAWD Banked months process FIATER

### ISSUE THREAD

**Issue by theVKC** [MN-Script-Team/DHS-MAXIS-Scripts#1513]
This overrides script freeze because MAXIS isn't doing what it needs to do in any capacity for the ABAWD banked months. Also, it isn't coming out until January, so there's that.

@courtrightd, @IlseFerris, @C-Love, and I are working on it.

**Comment by theVKC** [comment]
What do we think, folks! Based on all of the work we've done, do we think it's ready to pull in to master?

@IlseFerris @courtrightd @C-Love: if it's good, someone also needs to update the main menu script... I'd do it but I'm working on a report.

**Comment by IlseFerris** [comment]
I think it's good to go. I have instructions on the ready as well. I will update the main menu button as well.

**Comment by courtrightd** [comment]
So I was testing the version that just got pulled in, and realized there are some issues that I fixed last week that I never got pulled in, so I’ve been discussing this based on the version we’re running locally not the version everyone else has. Namely, the dialog info doesn’t carry into the budget when it is changed.  Additionally, some issues with multiple jobs panels on multiple members not being counted in budget, BUSI not counting after initial month has also been reported.  I’m working on some testing and fixes.

**Comment by theVKC** [comment]
Good catch, @courtrightd. If you can create new issues as you pull them in, that'd be wonderful.

**Comment by IlseFerris** [comment]
Good deal, thanks @courtrightd

**Comment by theVKC** [comment]
Did #1690 fix it, @courtrightd?

**Comment by courtrightd** [comment]
I think it is ready to pull into master at this point.  I'm tracking down an unconfirmed issue with BUSI, but I will make a new issue for that if I confirm it.

**Comment by theVKC** [comment]
Good deal.

**Comment by IlseFerris** [comment]
YAY! Go team go!

**Comment by theVKC** [comment]
Yup. This wraps for Boardwalk (although I'll leave the milestone up until it goes live in case of bugs). Seriously, you all are amazing @IlseFerris, @courtrightd, @C-Love.
