### ISSUE TITLE
JOBS panel gets updated Jan for Feb potentially

### ISSUE THREAD

**Issue by theVKC** [MN-Script-Team/DHS-MAXIS-Scripts#1514]
We need to insert logic into Boardwalk to facilitate this.

**Comment by IlseFerris** [comment]
I was snooping around the jobs panel today in the footer month of 02/16. I cannot detect any changes to the JOBS panel at this point.

**Comment by theVKC** [comment]
Thanks for snooping, Ilse!

**Comment by IlseFerris** [comment]
My pleasure!
