### ISSUE TITLE
NOTES burial assets

### ISSUE THREAD

**Issue by CDPotter** [MN-Script-Team/DHS-MAXIS-Scripts#1519]
Had a question on why the policy number is required on this script. Per the PC's investigation into policy a policy number isn't required. Should we remove this requirement?

**Comment by IlseFerris** [comment]
If new information shows it's not mandatory, then yes, we should remove it.

**Comment by CDPotter** [comment]
It's not a field on the OTHR panel so I'd say it's safe to go. I'm going to submit a pull with it commented out (yay err message handling making this super easy!). Due to the way the case note works I'm going to add a bit to if "" then = "not provided"

**Comment by theVKC** [comment]
Is it conditionally required? Like, if there's a policy we should include the number?

**Comment by CDPotter** [comment]
Yes it's part of the ERR_MSG handling. 

Looking through the code and going to the source of the suggestion we learned a few things. 1: the script already defaults policy_number to "none" 2: the worker must have deleted this default thus causing her problems with mandatory verification.

Since the script already defaults and answer of "none" in there I think this can be closed.

**Comment by theVKC** [comment]
Good deal, thanks @CDPotter!
