### ISSUE TITLE
DAIL scrubber enhancement - CSES

### ISSUE THREAD

**Issue by kaleykobber** [MN-Script-Team/DHS-MAXIS-Scripts#1532]
Is it possible to have a case note script available for when the script cannot be used to process the child support DAIL message(s)? So, the worker runs the DAIL scrubber script, the script can't process the DAILs, and the worker receives an error message to process them manually. Then, the worker processes the child support DAILs manually, and then could run a case note script following manual processing? 

Is this already in the works? @RobertFewins-Kalb

**Comment by theVKC** [comment]
@RobertFewins-Kalb, I was thinking you had something like this being worked on in your present work on CS.

**Comment by RobertFewins-Kalb** [comment]
That was the plan. However, during development, we hit an exception access violation -- making me think the array (storing CSES and UNEA classes is too large for the script host to handle).

We will revise our approach to the CSES DAIL Scrubber, but we will make sure we are case noting thoroughly.

**Comment by theVKC** [comment]
I have some ideas for that, BTW. I think we can (and should) still do it as an array. I may have mentioned that many agencies are moving to cloud-based Microsoft Office solutions, and these don't necessarily include the OLE automation for Excel. So, eventually, we must either stop supporting the script or move it into array handling.

In any case, should I remove this as a "question", and add it as an enhancement request?

**Comment by RobertFewins-Kalb** [comment]
I think close it. The plan from day 1 included a more thorough case note.

**Comment by theVKC** [comment]
Right, but if you're including the issue as @kaleykobber described, it still makes it a trackable issue on GitHub for people other than you. :)

Also, technically @kaleykobber is asking for a separate case note, and I don't know that we've addressed that. A "you updated this manually" case note template. @kaleykobber, would you see value in a separate case note IF the DAIL scrubber started noting each case?

**Comment by RobertFewins-Kalb** [comment]
Whichever. You can leave it at enhancement request. I just don't know how quickly this will get done (it's a beast) and I don't want to have a bunch of open projects hanging out there.

**Comment by kaleykobber** [comment]
I like the idea of the DAIL scrubber case noting each case, but this would be for cases where the script stops and is not able to process the child support. So, would it still case note in that scenario? The DAILs may be within the realm or may be outside of the realm, but for whatever reason, couldn't be updated by the script. Maybe it needs to be a separate NOTES script that just follows the same format as the DAIL scrubber case note? The case note would be different, depending on whether or not the DAILs are within the realm (is my thought)...

**Comment by theVKC** [comment]
@kaleykobber: is it OK if we change this to "adding an other notes section to the case note"? I ask because feedback at hackathon indicates that workers usually update the SNAP info manually, and then simply re-run the script (and changing that process might be more difficult than amending the existing script)?

The new title would read "CSES: add 'other notes' section to script".

**Comment by kaleykobber** [comment]
Yes, I think that would be fine.
Maybe the issue of what to do when child support falls outside the realm needs to be a county process, then? It does not appear that this can be addressed through the script (even as a case note scenario)?

**Comment by theVKC** [comment]
I think we can give people a space to talk about it, but right now it's kind of weird.

**Comment by theVKC** [comment]
* weird to address with a script, because things can be so county-specific.
