### ISSUE TITLE
Critital bug: NAV button & INFO ABOUT BLUEZONE SCRIPTS button issue

### ISSUE THREAD

**Issue by IlseFerris** [MN-Script-Team/DHS-MAXIS-Scripts#1536]
Not sure if anyone else is getting this issue, and it also doesn't seem to be effecting the other new scripts. Getting the "something has gone wrong" message, followed by this message when you hit OK

"script error at line 32, column 5/Type mismatch: 'script_end_procedure"

**Comment by RobertFewins-Kalb** [comment]
If the script is not successfully loading the FuncLib, the script host will not know what "script_end_procedure" means and will give you a type mismatch error.

**Comment by courtrightd** [comment]
This is not an issue here.

**Comment by theVKC** [comment]
@IlseFerris, did you download and set-up the redirect files?
