### ISSUE TITLE
Incarceration script won't load

### ISSUE THREAD

**Issue by theVKC** [MN-Script-Team/DHS-MAXIS-Scripts#1553]
Looks like there may be an issue with the URL. On it.

**Comment by theVKC** [comment]
On comparison, the dash character doesn't appear to be the proper ASCII dash character. Screenshots pending my investigation.

**Comment by theVKC** [comment]
This appears to have been broken since before October 8, but on October 8, @IlseFerris updated the file to correct the issue. It appears that the dash character between NOTES and INCARCERATION doesn't match the normal standard, which is weird for multiple reasons.

1. This should have been caught when testing the fix (it sure looks like it's never been working, which means it was never once tested, and yes I'm irritated by that).
2. This doesn't seem possible as ASCII keyboards have been standardized since like the mid 80s.

@IlseFerris: I fear that your 10-key's dash key might be at fault. Perhaps it acts differently than we'd expect (and BTW, this could certainly have led to other weird bugs which resolve themselves when I look at them, because I don't use the 10-key dash).

Here's what I have when I copy the string from the MAIN MENU:
![image](https://cloud.githubusercontent.com/assets/5701751/11821822/0a75d4a4-a331-11e5-9916-ba4b05221b5a.png)
 
Note that the editor treats the regular dash as a modifier (brown color), and the weird dash as a string (black color). Ilse, can you open up BZSH, zoom in really far, and see what color the dash key on your 10-key is?

In any case, I'm going to update the string and close the issue.

**Comment by theVKC** [comment]
Original commit which started this: https://github.com/MN-Script-Team/DHS-MAXIS-Scripts/commit/615ae38e7dbfa8f6546626a693507861cc5309b9

**Comment by IlseFerris** [comment]
tested this on separate 10 key, 10 key on keyboard and on general keyboard. Could not replicate the error (glad it wasn't me...whew!)
