### ISSUE TITLE
Enhancement -- Paystubs received should default to update PIC, HC Inc, and case note

### ISSUE THREAD

**Issue by RobertFewins-Kalb** [MN-Script-Team/DHS-MAXIS-Scripts#1559]
Why are we still giving people the option?

**Comment by RobertFewins-Kalb** [comment]
This is an easy enhancement and I can take it if the opinion is that there's no reason to not case note, and update all months...

**Comment by theVKC** [comment]
*Why we don't want to always update the PIC*: not everyone is on SNAP.
*Why we don't want to always update the HC popup*: not everyone is on HC.
*Why we don't want to always case note*: the PIC updater case notes. Didn't want to force two case notes on people.

Thoughts? I'd rather leave it as is and just yell at you if you don't pick at least one option (an "are you sure? this is weird" would suffice).

**Comment by RobertFewins-Kalb** [comment]
It doesn't hurt to have the information on the PIC or the HC Inc. UNLESS we want to have the script determine if SNAP and HC are active or pending to determine which areas should be updated automatically...

**Comment by theVKC** [comment]
Actually, it can hurt. Especially in the SNAP world, we see folks not updating PICs with new information on a new application because the old info is still there. We also see oververification because the old info is there. Generally, we try to avoid unnecessarily updating it where possible.
