### ISSUE TITLE
Boardwalk - add handling for expedited / delayed verif

### ISSUE THREAD

**Issue by courtrightd** [MN-Script-Team/DHS-MAXIS-Scripts#1560]
I have been working on handling for verifications marked ?.   They should be budgeted on expedited cases, but should give the current not handled message on all others.  
Proposed solution: 
a function run after each read of a "?_" verif that brings up a vbYesNo msgbox asking the worker whether they want to count this income or deduction.  Click yes, and it reassigns the verif variable from "?_" to "OT".  Click no, it leaves it alone, and handles with the current warning message.
The function is made, just tell me this makes sense before I go adding it all over the script.

**Comment by theVKC** [comment]
Make it so.
