### ISSUE TITLE
DAIL Scrubber - other counties experiencing errors 

### ISSUE THREAD

**Issue by Y-Lor-Y** [MN-Script-Team/DHS-MAXIS-Scripts#1561]
Reporting item on SIR: Are any other counties beside Goodhue, Aitkin, and Winona, plus another (not sure which County Jennifer is from) county are experiencing errors with their DAIL Scrubber?  According to SIR th

One of the error noted: (from SIR)
*All of our staff is getting the following error on PRISM:
* 
* Script Error at Line 1, Column 1:
* Type mismatch: 'case_amount_check'

***
According to the other counties this appears to be affecting only the CSES Dails.
****
I thought it may be the  change required now that beta branch is gone.
Please see the SIR posting.

I've tested these two scripts - which as redirect to release and master (each separated folders).
It came back working just fine.

Thanks,
Yang

**Comment by Y-Lor-Y** [comment]
sorry forgot to #theVCK

**Comment by RobertFewins-Kalb** [comment]
It would be nice to know what DAIL message they're running on. case_amount_check is not a function.

**Comment by RobertFewins-Kalb** [comment]
nevermind...CSES Processing

**Comment by courtrightd** [comment]
This variable is on line 804 of the cses processing script.   I did a quick look at PRISM, and it is at least reading from the right spot.   I can’t find any dails to test further currently.

**Comment by RobertFewins-Kalb** [comment]
I'm in communication with the worker that reported it.

**Comment by Y-Lor-Y** [comment]
Not sure why I closed it.  Had me going crazy not able to find it.  Sorry, it's re-opened.

**Comment by RobertFewins-Kalb** [comment]
I wonder if the problem is this seemingly sporadic issue that the BZSH has with assigning both a numeric and string characteristic to a number that it reads from Blue Zone. 

The variable in question reads the number of CS cases the individual is a part of. That value (at 7, 17) is a number, but if the script thinks it's a string, the numeric comparison would not work.

**Comment by theVKC** [comment]
Sorry, I've been working on reports all day.

Could we convert the value to a numeric every time, somehow? Perhaps add some error handling around it?

@LaLarson: are you seeing this?

**Comment by RobertFewins-Kalb** [comment]
I think that's what we do. We had to do that with the footer_month issues (only in reverse). I'm not sure why, but sometimes BZSH gets wonky when we read numbers off the screen.

**Comment by RobertFewins-Kalb** [comment]
@LaLarson have talked about it, beeteedubs

**Comment by theVKC** [comment]
Good to know. Do you want it @RobertFewins-Kalb?
