### ISSUE TITLE
SNAP E & T letter needs inhibiting logic to stop exempt counties from using the script

### ISSUE THREAD

**Issue by IlseFerris** [MN-Script-Team/DHS-MAXIS-Scripts#1567]
per TE02.05.69 several counties have rec'd a wavier from participation for E & T from FNS.

**Comment by Farleight** [comment]
Maybe this is a dumb question, but... why are exempt counties trying to use the script?

**Comment by IlseFerris** [comment]
Well they shouldn't be, so we're just going to make sure that the exempt counties cannot use it :)
