### ISSUE TITLE
Enhancement BULK consolidation. 

### ISSUE THREAD

**Issue by CDPotter** [MN-Script-Team/DHS-MAXIS-Scripts#1569]
We have created 3 scripts here at Anoka that incorporate the function of 3 other scripts. Each script does a different action, TIKLs(replaces bulk TIKler), Memos, Case notes(replaces case note from excel list).

So it allows the user to select from entering case number manually, gathering case numbers from an excel list(with functionality to allow users to browse their system rather than typing a file path), or grabbing them off of REPT/ACTV.

2/3 are enhancements while 1 would technically be a new script. Is this something to wait on until script thaw?

**Comment by theVKC** [comment]
I'm a bit confused by your first sentence. What three scripts of DHS' would you be consolidating, exactly? Keep in mind Anoka's not on the standard Power Pad, so your names might be different than ours.

**Comment by CDPotter** [comment]
BULK - BULK TIKLer
BULK - CASE NOTE FROM EXCEL LIST
and it looks like there isn't a BULK MEMOer stateside yet. 

So 2/3 are enhancements while 1 is technically a new script.

**Comment by theVKC** [comment]
@CDPotter: did you work on this?

**Comment by CDPotter** [comment]
I do have these ready.

**Comment by theVKC** [comment]
Go ahead and pull it in! :)
