### ISSUE TITLE
Enhancement HRF Add GA or generic Cash checkbox.

### ISSUE THREAD

**Issue by CDPotter** [MN-Script-Team/DHS-MAXIS-Scripts#1574]
From SIR:
"One of our singles workers asked that the HRF script also have a check box for GA cash.  (It currently lists MFIP, SNAP & HC.)  She has monthly reporters who are getting cash."

I don't see why not, I could knock it out quickly unless someone else wanted to tackle it.

**Comment by CDPotter** [comment]
Actually, the check boxes don't do anything... So we have options

1: Remove the checkboxes
2; Add GA and make the checkboxes do something.

Thoughts?

**Comment by theVKC** [comment]
I agree. Solution 2! Do you want it?

**Comment by CDPotter** [comment]
What luck! I did exactly that already! I will submit after this drop in.

**Comment by theVKC** [comment]
#FASlife
