### ISSUE TITLE
BUG (critical?) -- CSES Processing DAIL Scrubber 

### ISSUE THREAD

**Issue by RobertFewins-Kalb** [MN-Script-Team/DHS-MAXIS-Scripts#1582]
Several users are reporting a problem with the CSES DAIL Scrubber. It appears to be happening around line 800 in the script... Type Mismatch Error: case_amount_check

I'm looking into it.

**Comment by RobertFewins-Kalb** [comment]
Direct quote from a member of staff: "It appears to be running correctly when there is CMS/CMI in Prism, but giving me the error when there is not. I’m manually checking all those that I get the error on, and I have not had any with the medical support."

**Comment by theVKC** [comment]
Folks here at hackathon aren't seeing this. Why am I thinking either you or @CDPotter just pulled something in that addresses it? Maybe?

**Comment by RobertFewins-Kalb** [comment]
We were finding the problem on case 287247 (I doubt the DAILs are still there). I haven't pulled something because it seemed like an isolated incident. I did add some code to a version I haven't pulled.

After turning Excel visible, I could see where the problem was coming from. When the script would go back through and check the SSNs in PRISM, it would get to a point where the SSN field in Excel was blank, it would dump a blank SSN into PRISM and then try to read the number of cases, but that information was not being brought on screen in PRISM.

To alleviate it, I just added an EXIT DO after it finds no SSN...

![image](https://cloud.githubusercontent.com/assets/7842016/12175424/c0a99cc6-b527-11e5-9772-8892f82da9b7.png)


I can submit a pull request today.

**Comment by RobertFewins-Kalb** [comment]
Whoops. I can submit a pull request after I get rid of the MsgBox

**Comment by theVKC** [comment]
Why am I thinking @CDPotter just did something about this, though?

"CSES Processing - Script was incorrectly writing SSN by 1 digit. This has been resolved. Built by Charles Potter (Anoka County)."

**Comment by RobertFewins-Kalb** [comment]
That was just about the coordinates of where the SSN was being written.

**Comment by RobertFewins-Kalb** [comment]
No. That changed the EMSendKey to an EMWriteScreen to make it go faster.

**Comment by CDPotter** [comment]
Update: two reports of this on SIR.

**Comment by theVKC** [comment]
Hmmm. @RobertFewins-Kalb, did you ever submit a pull request on this (your comment 8 days ago makes me think you worked on it).

**Comment by RobertFewins-Kalb** [comment]
I did not pull anything. I built something but it did not seem like that common a problem until we just now did some SIR sleuthing. Working on a pull request right now
