### ISSUE TITLE
Agency Custom button

### ISSUE THREAD

**Issue by GayS** [MN-Script-Team/DHS-MAXIS-Scripts#1583]
the agency custom button isn't "finding" and auto building the agency custom scripts.

**Comment by theVKC** [comment]
Can you give me a bit more detail as to why? Perhaps we can work on that Monday if we don't have time today.

**Comment by GayS** [comment]
I am closing this issue.  Agency Custom scripts need to be in the DHS-MAXIS_Scripts\Script Files\AGENCY CUSTOMIZED folder for the button to work properly (ours were located in a different folder).
