### ISSUE TITLE
NOTES - MOF- Comment out the diagnosis field

### ISSUE THREAD

**Issue by RobertFewins-Kalb** [MN-Script-Team/DHS-MAXIS-Scripts#1589]
The case note script for a medical opinion form received includes a field for "Diagnosis." While we aren't requiring that it is completed and workers are completely free to omit that field, I am concerned that workers may feel prompted to provide information related to a client's medical history into case notes since the dialog includes a field for that information.

My thought is we remove that edit box to reduce the likelihood that sensitive medical information does not get into case notes.

What are peeps' thoughts on this matter?

**Comment by Farleight** [comment]
Completely agree. I like HIPAA Violations as much as the next guy, but let's at least try to be subtle about it.

**Comment by theVKC** [comment]
I agree in theory. I feel like we addressed this once before and it was considered OK. But, if folks agree it should be removed as a CYA thing, I support it.

**Comment by lpshanley** [comment]
The only people that could look at those notes legally are people that are bound by HIPAA. Including somewhere to enter the information is in no way shape or form a violation. We could place “optional” or “If provided” near the field so the worker knows that It can be omitted however this wouldn’t a violation if its left alone. Legally, while I’m not a lawyer, I see no issues. I agree with Veronica I believe we have chatted about this in the past and it was decided that it was OK. I would also leave it to the consensus of the group if it’s a desired field or not however I don’t think there are any legal issues at hand unless something has changed that I am unaware of! ☺

-Lucas
“Valar dohaeris”
#DecimateTheErrorRate
P Please consider the environment before printing this email. P

**Comment by Farleight** [comment]
The client can request them at any point, and they are not bound by HIPAA. Granted, it seems ridiculous to say that the client wouldn't be allowed to view their own paperwork, but in the case of multiple person HHs, or next of kin sorts of things, it's actually a legitimate argument. HIPAA wasn't designed for logical thought. The prime directive of the whole thing is "If you don't need to, don't." We simply don't need to. A diagnosis is not necessary case information. So why take the chance?

**Comment by RobertFewins-Kalb** [comment]
My concern is also about whether or not we have a legitimate business reason for case noting that information. We are really only concerned about the "how long will the client be unable to work" bit on the MOF. Methinks we should remove the field.

**Comment by theVKC** [comment]
We just talked about this at hackathon. We made the following decision:

* We'll comment out the diagnosis field and replace it with a text field that says "The diagnosis field has been removed from this script pending review"
* Stearns County will send a PQ requesting additional clarification.

Thinking that should address the issue. :)

**Comment by theVKC** [comment]
@MelissaFox-Stearns has agreed to take this on, so yay!
