### ISSUE TITLE
Merge BULK scripts MISC NON MAGI and PDED list together

### ISSUE THREAD

**Issue by IlseFerris** [MN-Script-Team/DHS-MAXIS-Scripts#1601]
much of the 2 scripts are duplicated. They should be merged to create a SUPER BULK list (one bulk script to rule them all).

**Comment by theVKC** [comment]
Not Bowie, since this isn't a change reported script.

**Comment by theVKC** [comment]
Would you estimate you could have this ready by mid-February? If so, I'll target it for the v2016.02 release.

**Comment by IlseFerris** [comment]
I plan on having this one done this week.

**Comment by theVKC** [comment]
@IlseFerris: think this will be done by Friday? Script freeze starts Tuesday.

**Comment by IlseFerris** [comment]
This will be ready prior to the freeze
