### ISSUE TITLE
Merge phone number look up and REPT SEARCH scripts together

### ISSUE THREAD

**Issue by IlseFerris** [MN-Script-Team/DHS-MAXIS-Scripts#1603]
Make them one script to rule them all :)

**Comment by theVKC** [comment]
What type of script should this be? What should it be named?

**Comment by RobertFewins-Kalb** [comment]
What if we took a page from the Child Support peeps and expanded REPT Search to include phone number and client address?

**Comment by theVKC** [comment]
That was kind of what I was thinking.

Also, as this doesn't have to do with changes, it isn't a Bowie script. Anyone want it?

**Comment by theVKC** [comment]
@StormageddonDLOA has this!

**Comment by theVKC** [comment]
Would you estimate you could have this ready by mid-February, @StormageddonDLOA? If so, I'll target it for the v2016.02 release.

**Comment by StormageddonDLOA** [comment]
I believe so, yes.
