### ISSUE TITLE
Merge the gas cards and mileage reimbursement scripts into "NOTES - CLIENT TRANSPORTATION COSTS.vbs"

### ISSUE THREAD

**Issue by IlseFerris** [MN-Script-Team/DHS-MAXIS-Scripts#1609]
Do it!

**Comment by theVKC** [comment]
@IlseFerris:  what would you propose we call the new script?

**Comment by IlseFerris** [comment]
NOTES - client transportation costs?

**Comment by theVKC** [comment]
Mel has volunteered to take this on. Thank you!

**Comment by theVKC** [comment]
Also, not really Bowie as it has nothing to do with changes.

**Comment by theVKC** [comment]
Would you estimate you could have this ready by mid-February, @MelissaFox-Stearns? If so, I'll target it for the v2016.02 release.
