### ISSUE TITLE
ACTIONS - UPDATE WORKER SIGNATURE should be a "UTILITIES" script

### ISSUE THREAD

**Issue by theVKC** [MN-Script-Team/DHS-MAXIS-Scripts#1612]
Because, if you think about it, it's really more of a utility than an action.

@RobertFewins-Kalb: since this was primarily your baby, are you interested in taking it? That way it saves you as the author (for history purposes).

**Comment by RobertFewins-Kalb** [comment]
I can get it done

**Comment by theVKC** [comment]
Any update on this one? I feel like we talked about adding it to the script info button. Not sure where we landed.

**Comment by RobertFewins-Kalb** [comment]
I can update that script if'n that's the decision.

**Comment by theVKC** [comment]
I think it should be both. Link to it from the info button, and a separate UTILITIES button (which we can expand in the future to include other utilities scripts, such as a script reset link like a zmd reset...)

**Comment by theVKC** [comment]
@RobertFewins-Kalb: any update on this? I'm willing to take it as part of the new Power Pad plans.

**Comment by theVKC** [comment]
(Also, as folks won't be updating to the new Power Pad with a UTILITIES button right away, we'll cross list it in ACTIONS for a while)

**Comment by RobertFewins-Kalb** [comment]
I have what I emailed you ready to roll. If that will work, I'll pull it in as an update to the scripts info button. Otherwise, I haven't worked on anything else. You can has if'n you wants.

**Comment by theVKC** [comment]
Please pull it into the info button. I'll take the rest from there.

**Comment by theVKC** [comment]
Issue not quite "resolved" as the script file itself still lives in the ACTIONS folder. It should be renamed "UTILITIES - UPDATE WORKER SIGNATURE" and should live in the utilities folder with it crosslinked on ACTIONS until the new Power Pad comes out.

**Comment by theVKC** [comment]
And I'll take that on...
