### ISSUE TITLE
Needs STATS_enhanced_db variable in global variables

### ISSUE THREAD

**Issue by theVKC** [MN-Script-Team/DHS-MAXIS-Scripts#1615]
It should be set to `false` if you're not running the new database, and `true` if you are. Folks running stats for their caseloads will want to take note.

* @RobertFewins-Kalb or @CDPotter - Anoka
* @IlseFerris - Hennepin
* @GayS - Stearns
* @courtrightd - St. Louis

Anyone else?

**Comment by CDPotter** [comment]
So we should add STATS_enhanced_db = True to globvar locally?

**Comment by theVKC** [comment]
Only after modifying your scripts database to match the enhanced database (the new usage statistics file I pulled in yesterday). Formal instructions are pending, but I just want folks to be aware that it's coming.
