### ISSUE TITLE
Boardwalk dialog issue - need help.

### ISSUE THREAD

**Issue by courtrightd** [MN-Script-Team/DHS-MAXIS-Scripts#1617]
For some reason, when the dialog comes up with the budget information, any edits made do not stick with the variables.  It doesn't matter what you enter in the dialog, the original variable value is entered in the budget.  Additionally, if you click one of the navigation buttons, all the values in the dialog become 100.  Any insight would be helpful.

**Comment by theVKC** [comment]
Could this be where it's dimming? Would some strategically placed dims prior to the dialog itself help?

**Comment by courtrightd** [comment]
After messing with dims and anything else I could think of, it seems that dialogs and classes in an array is not a workable combination under BZSH.  I made it work by using the standard variables from the panels in the dialog, then assigning to the class properties after the dialog is run.  I'll be cleaning this solution up on Monday.

**Comment by theVKC** [comment]
This seems weird to me, since I'd done it the other way. But I'm interested in your workable solution.

**Comment by theVKC** [comment]
@courtrightd: I assume your pull request #1573 resolved this, and I'm closing the issue.
