### ISSUE TITLE
Build formally supported scenarios for Krabappel

### ISSUE THREAD

**Issue by theVKC** [MN-Script-Team/DHS-MAXIS-Scripts#1625]
2-3 from each major county involved ought to cover it. I believe Anoka is good, so that would leave:

* St. Louis (@courtrightd)
* Hennepin (@IlseFerris)
* Ramsey (@C-Love @Y-Lor-Y)
* Stearns (@GayS @MelissaFox-Stearns @StormageddonDLOA)

Can we get some fake documents from each agency?

**Comment by RobertFewins-Kalb** [comment]
Anoka Program Coordinators build 16. Pro Tip: If you're going to build a scenario with a CARS panel, it MUST have HC Benefit Y/N even if the case is not a health care case.

**Comment by theVKC** [comment]
I think your 16 means Anoka's earned a pass on contributing to this. :)
