### ISSUE TITLE
Update Krabappel for time savings

### ISSUE THREAD

**Issue by theVKC** [MN-Script-Team/DHS-MAXIS-Scripts#1626]
Need per-item savings based on time it takes to update a panel. Average it out to 40 sec per panel.

**Comment by theVKC** [comment]
@GayS: are you working on this? If not, I might take it.

**Comment by GayS** [comment]
I have it on my “to-do list” but if you want to get it done sooner – ok w/me.

**Comment by theVKC** [comment]
I'll be in the script soon to move it into the UTILITIES folder, so I might as well. #OneLessHandoff

**Comment by GayS** [comment]
Ok – I will take it off my list – thank you. #simplify

**Comment by theVKC** [comment]
@CDPotter is working on this, but I'm removing the issue as it's cross listed with #53 now.
