### ISSUE TITLE
CRITICAL BUG -- Invalid Character in BILS Updater

### ISSUE THREAD

**Issue by RobertFewins-Kalb** [MN-Script-Team/DHS-MAXIS-Scripts#1629]
Looks like there are a bunch of these guys: ` where there should be these guys '

We have users reporting the problem. Going to submit a fix to both MASTER and RELEASE.

**Comment by theVKC** [comment]
Can you close and pull these again? Just finished the script release.

**Comment by theVKC** [comment]
See #1623
