### ISSUE TITLE
D-F Notes Button Out of Range

### ISSUE THREAD

**Issue by khiestand** [MN-Script-Team/DHS-MAXIS-Scripts#1661]
Everyone in Wright County is getting a "Dialog ID 252 is Out Of Range" error message and a "Dialog ID 44 is Out of Range" message when trying to click on the Notes D-F button.  Pressing the stop script button is the only want to cancel out of it.  Help please.

**Comment by CDPotter** [comment]
It was an error from a merge earlier today. I emailed @theVKC but haven't heard back yet.

**Comment by theVKC** [comment]
I'm off site away from my machine. @IlseFerris just pulled something a bit ago.

**Comment by MelissaFox-Stearns** [comment]
We are getting the same message here at Stearns except Stopscript doesn't work. We need to restart our computers to get the error message to go away.

**Comment by asunderman** [comment]
It seems to be working as it should here in Le Sueur County.

**Comment by CDPotter** [comment]
The stop script button may not work but you can try this for the time being

![stop script](https://cloud.githubusercontent.com/assets/7841989/12337459/dd30c560-bacf-11e5-83ca-9579bef40dbb.png)

**Comment by MelissaFox-Stearns** [comment]
Silly me. I assumed Stopscript would close the error by itself. It looks like we can close with stopscript just have to hit the button then go to the dialog and press OK.  Sorry for the derp. ;)

**Comment by CDPotter** [comment]
Can people take a look and see if that worked on their end? Looks like it's good for me.

**Comment by MelissaFox-Stearns** [comment]
All clear on my end! :)

**Comment by khiestand** [comment]
Good to go in Wright Co!

**Comment by theVKC** [comment]
@asunderman: this should only be affecting the master branch (scriptwriter branch). Just making sure here: did you experience the issue as described in @CDPotter's original post? That would imply we have a crossed wire somewhere.
