### ISSUE TITLE
Adding Banked Month Data to NOTES - APPROVED PROGRAMS

### ISSUE THREAD

**Issue by C-Love** [MN-Script-Team/DHS-MAXIS-Scripts#1663]
Adding a separate dialog, case note, tikl to Approved Programs.
Allows to be expanded to tracking.

**Comment by theVKC** [comment]
Is this resolved by your pull request #1664, @C-Love?

**Comment by theVKC** [comment]
Technically... this isn't part of Boardwalk. It's related, but not really dependent on the new script. Removing milestone indicator.
