### ISSUE TITLE
Remove commented out "diagnosis" code from MOF, and adjust size of dialog

### ISSUE THREAD

**Issue by theVKC** [MN-Script-Team/DHS-MAXIS-Scripts#1667]
Easy win. See PQ #16506. Any takers?

**Comment by theVKC** [comment]
(Also, I think we should maybe amend the dialog to reflect: "do not case note the diagnosis per PQ #16506)

**Comment by Farleight** [comment]
I have time for an easy one today. You're thinking just a general text box on the dialogue itself that says something like, "Don't violate HIPAA, you heathen!"? Or some other such verbiage that is less confrontational...

**Comment by Farleight** [comment]
I haven't done enough of these to know for sure if I can pull prior to being assigned, but I tried and the Propose File Change thing isn't popping up. It just says "waiting for fork." I can relate. I've gone to restaurants with inaccesible silverware before.

**Comment by CDPotter** [comment]
You should be able to. I just go to the MASTER and RELEASE branches and find the file directly and click edit then after deleting the old file and replaces it with the revised one I commit then pull. 

![edit file](https://cloud.githubusercontent.com/assets/7841989/12358748/695066d2-bb74-11e5-88ed-4c97eab2c4a5.png)

**Comment by Farleight** [comment]
Chrome worked. Took a stab at the wording. If you had something else in mind, let me know. Gratzi for the tech assistance CDP.

**Comment by CDPotter** [comment]
No problem, glad we got it working!

**Comment by theVKC** [comment]
Only need it in master, we disabled the function in release manually on Monday.

**Comment by theVKC** [comment]
And thanks @Farleight!
