### ISSUE TITLE
Boardwalk: SHEL panel costs error

### ISSUE THREAD

**Issue by IlseFerris** [MN-Script-Team/DHS-MAXIS-Scripts#1679]
All SHEL panel deductions are not pulling into the dialog, and the OTHER shelter costs are not being written into the SNAP budget.

**Comment by courtrightd** [comment]
THIS IS MY FAULT.  Sorry, I was really sloppy last week.  I will pull the fix in a moment.

**Comment by theVKC** [comment]
@courtrightd: Ilse's out for the moment. Any chance you can fill me in on what's going on?

**Comment by IlseFerris** [comment]
I just submitted the fix. I was just waiting for my pull request from earlier to get accepted. No worries @courtrightd I had a rough week last week myself :)

**Comment by theVKC** [comment]
Resolved by #1683.
