### ISSUE TITLE
usage statistics.accdb: it needs a front-end

### ISSUE THREAD

**Issue by theVKC** [MN-Script-Team/DHS-MAXIS-Scripts#1687]
I'm taking it. Someday this will be done. Someday soon, I hope.

**Comment by theVKC** [comment]
OK, I'm just not going to have time to get this done. Anyone out there with Access experience want to build some tool to display the time savings? @courtrightd?

**Comment by courtrightd** [comment]
Time is likely an issue for me in the near term, but I would be willing to look at it in the future.  Definitely would not happen for May release.

**Comment by theVKC** [comment]
Wonderful. As you can see I've delayed it a few times myself.

**Comment by theVKC** [comment]
@courtrightd, in light of recent events, I am going to mark this issue as a sleeper and close it for now. We can always reopen.

**Comment by theVKC** [comment]
(basically, we can reopen it when we're ready to actually work on it, but neither of us appear to have time at the moment and I don't want it cluttering GitHub because most of us don't have requisite Access experience)
