### ISSUE TITLE
Resolved: that Krabappel should be a UTILITIES script

### ISSUE THREAD

**Issue by theVKC** [MN-Script-Team/DHS-MAXIS-Scripts#1688]
Anyone want to debate this? :) (No, I wasn't just listening to NPR, why do you ask?)

I think it belongs as a utility script owing to its nature as a training case builder. It doesn't work with real-world data at all. So, let's hide it.

Thoughts? 

@CDPotter 
@RobertFewins-Kalb 
@courtrightd 
@lpshanley 
@IlseFerris 
@C-Love 
@GayS 
@StormageddonDLOA 
@MelissaFox-Stearns

**Comment by IlseFerris** [comment]
Works for me

**Comment by courtrightd** [comment]
Did we all log our responses before the debate starts, and the winner will be the team that changes the most opinions?
That being said, my response is yes, before and after the debate.

**Comment by RobertFewins-Kalb** [comment]
It doesn't really work with the current actions-bulk-notes split.

**Comment by theVKC** [comment]
^^^Exactly. It isn't bulk because it's only doing one case (although across multiple case numbers). It isn't actions because it isn't doing an action on an existing case, really, and it doesn't really note anything.

**Comment by GayS** [comment]
makes sense to me - helps keep power pad organized and clutter free

**Comment by theVKC** [comment]
Anyone want to be responsible for moving it? Perhaps we should each take turns to reflect our contributions? :P

**Comment by StormageddonDLOA** [comment]
Works for me!

**Comment by theVKC** [comment]
Since I'm not getting volunteers, I'll just plan on moving it over. :)
