### ISSUE TITLE
New script idea AREP Case note

### ISSUE THREAD

**Issue by CDPotter** [MN-Script-Team/DHS-MAXIS-Scripts#1708]
An idea was brought up to have an AREP case note template. This would be something that would bring attention to changes in AREPs and possibly serve as a reminder for what can be shared (possible functionality to TIKL to get new AREP forms if needed.)

Thoughts?

**Comment by theVKC** [comment]
Personally, I like it.

**Comment by theVKC** [comment]
Do we have any scriptwriters interested in working on this? Could be a good opportunity for a newer scriptwriter...
