### ISSUE TITLE
NOTES - PostPay GRH Non-HRF

### ISSUE THREAD

**Issue by Y-Lor-Y** [MN-Script-Team/DHS-MAXIS-Scripts#1730]
Our GRH unit asking if we can build a script that would run for the non-HRF cases.  I have met a few time to go over what was needed and started building one.  I will share with the rest once done, and will be asking for help.

Thanks,

**Comment by theVKC** [comment]
Would you estimate you could have this ready by mid-February? If so, I'll target it for the v2016.02 release.

**Comment by Y-Lor-Y** [comment]
That’s the plan.

Yang T. Lor | FCM Resource Trainer
Financial Assistance Services |  Ramsey County CHS
160 Kellogg Boulevard East, Saint Paul, MN  55101
P: 651-266-3621  |  Fax: 651-266-3705
E: yang.tou.lor@co.ramsey.mn.us
Schedule: M to Th, 7:45 AM to 6:00 PM
www.ramseycounty.us<http://www.ramseycounty.us>

The information included in this email message, including any attachments, is intended only for the person or organization to which it is addressed.  This email message may contain information that is privileged or confidential.  If you receive this email message and are not the intended recipient or responsible for delivering the message to the intended recipient, you may not use, disseminate, distribute, or copy the information included in this email and any attachments.  If you received this email by mistake, please reply by email and destroy all copies of this message and any attachments.  Thank you

**Comment by theVKC** [comment]
Great! Thanks!

**Comment by theVKC** [comment]
@Y-Lor-Y: think this will be done by Friday? Script freeze starts Tuesday.

**Comment by Y-Lor-Y** [comment]
I cannot promise by Friday.  I need to test some cases out internally with it, so see if there are any bugs.  I’m at the last part, where I am writing the case notes codes.

I’m thinking of spending sometime today on it after 4:30, to have that done then check in with a few GRH workers to test it.

*finger crosses* to see if it works well, then I’ll let you know.  But for sure you’ll have an answer if it’ll be ready before script freeze or not.

Yang T. Lor | FCM Resource Trainer
Financial Assistance Services |  Ramsey County CHS
160 Kellogg Boulevard East, Saint Paul, MN  55101
P: 651-266-3621  |  Fax: 651-266-3705
E: yang.tou.lor@co.ramsey.mn.us
Schedule: M to Th, 7:45 AM to 6:00 PM
www.ramseycounty.us<http://www.ramseycounty.us>

The information included in this email message, including any attachments, is intended only for the person or organization to which it is addressed.  This email message may contain information that is privileged or confidential.  If you receive this email message and are not the intended recipient or responsible for delivering the message to the intended recipient, you may not use, disseminate, distribute, or copy the information included in this email and any attachments.  If you received this email by mistake, please reply by email and destroy all copies of this message and any attachments.  Thank you

**Comment by theVKC** [comment]
Sounds good, thank you!

**Comment by theVKC** [comment]
@Y-Lor-Y: I'm moving this to March. No pressure. Thanks for doing it!

**Comment by Y-Lor-Y** [comment]
Alrighty.  I won’t get it done, tested out live cases and it’s giving me some errors so I need to relook at my scripting.

Yang T. Lor | FCM Resource Trainer
Financial Assistance Services |  Ramsey County CHS
160 Kellogg Boulevard East, Saint Paul, MN  55101
P: 651-266-3621  |  Fax: 651-266-3705
E: yang.tou.lor@co.ramsey.mn.us
Schedule: M to Th, 7:45 AM to 6:00 PM
www.ramseycounty.us<http://www.ramseycounty.us>

The information included in this email message, including any attachments, is intended only for the person or organization to which it is addressed.  This email message may contain information that is privileged or confidential.  If you receive this email message and are not the intended recipient or responsible for delivering the message to the intended recipient, you may not use, disseminate, distribute, or copy the information included in this email and any attachments.  If you received this email by mistake, please reply by email and destroy all copies of this message and any attachments.  Thank you

**Comment by Y-Lor-Y** [comment]
FYI - Update:

I'm basically done with the script.  I need to finish the instruction, which is almost done, too...then will need to submit the script and instruction one go.  Shooting to have it complete this coming Friday 3/18/16.  Thanks.

**Comment by theVKC** [comment]
@Y-Lor-Y: because I haven't received/reviewed this one yet, and script freeze starts today, I'm going to have to move it to the April release.

**Comment by Y-Lor-Y** [comment]
Sorry about that.  I planned on last Friday, but last Thursday I went over the script with our GRH unit, and found few items needs to move around a bit.  So I had to swap coding in my script.

I was not in the office Friday so didn’t have time to update this in GitHub or work on the script, so couldn’t inform you.

I understand.  After do a few last minute testing, then I should be able to submit this.  I thought I was all set.

Yang T. Lor | FCM Resource Trainer
Financial Assistance Services |  Ramsey County CHS
160 Kellogg Boulevard East, Saint Paul, MN  55101
P: 651-266-3621  |  Fax: 651-266-3705
E: yang.tou.lor@co.ramsey.mn.us
Schedule: M to Th, 7:45 AM to 6:00 PM
www.ramseycounty.us<http://www.ramseycounty.us>

The information included in this email message, including any attachments, is intended only for the person or organization to which it is addressed.  This email message may contain information that is privileged or confidential.  If you receive this email message and are not the intended recipient or responsible for delivering the message to the intended recipient, you may not use, disseminate, distribute, or copy the information included in this email and any attachments.  If you received this email by mistake, please reply by email and destroy all copies of this message and any attachments.  Thank you

**Comment by Y-Lor-Y** [comment]
I've put this out for Agency Custom for our GRH staff to use to see if any last minute items may have been missed or tweak.  I'm shooting to have this submitted for April release.

**Comment by theVKC** [comment]
Thanks for the update!!

**Comment by theVKC** [comment]
Moving this to the May release.

**Comment by theVKC** [comment]
Can I get an update on this @Y-Lor-Y? Do you think it'll be done by Friday (the due-date for the May release enhancements)? Thanks!

**Comment by theVKC** [comment]
@Y-Lor-Y, my apologies, you ended up falling off of this script assignment because you left the MN-Script-Team group. You are still assigned this issue. I just can't do that in GitHub because of GitHub settings.

**Comment by Y-Lor-Y** [comment]
Sorry Veronica,

Yes.  I’m tuning the scripts to per your comments last time.  I look to have it enter back up on GitHub asap…hopefully before this Friday.

Yang T. Lor | FCM Resource Trainer
Financial Assistance Services |  Ramsey County CHS
160 Kellogg Boulevard East, Saint Paul, MN  55101
P: 651-266-3621  |  Fax: 651-266-3705
E: yang.tou.lor@co.ramsey.mn.us
Schedule: M to Th, 7:45 AM to 6:00 PM
www.ramseycounty.us<http://www.ramseycounty.us>

The information included in this email message, including any attachments, is intended only for the person or organization to which it is addressed.  This email message may contain information that is privileged or confidential.  If you receive this email message and are not the intended recipient or responsible for delivering the message to the intended recipient, you may not use, disseminate, distribute, or copy the information included in this email and any attachments.  If you received this email by mistake, please reply by email and destroy all copies of this message and any attachments.  Thank you

**Comment by theVKC** [comment]
Closing this issue and marking it as a sleeper. The script as written doesn't match our formatting or structural guidelines (it doesn't behave like our other scripts). It was buggy on my runs and will need to be rewritten. With GRH HRF-related-procedures being updated in the coming months, I would like to hold on this issue for a while and let policy catch-up.

**Comment by CDPotter** [comment]
(sorry for double post, I reopened the pull rather than the issue)

@kennyasalee Will you be able to get this done by Friday? It's gonna be a short window this month and freeze starts again end of day 8/12/16

**Comment by kennyasalee** [comment]
you bet! will do
