### ISSUE TITLE
Create SNAP WCOM menu

### ISSUE THREAD

**Issue by CDPotter** [MN-Script-Team/DHS-MAXIS-Scripts#1734]
We had an idea to create submenu in MEMOs for SNAP related WCOM scripts. Assign to me.

**Comment by theVKC** [comment]
Hey @CDPotter: think this will be done this week? Otherwise I don't want to include it in the v2016.02 release.

**Comment by CDPotter** [comment]
It's interview day today so I may have time to knock it out tomorrow?

**Comment by theVKC** [comment]
Great. I'm going to get the MEMOS changed over to NOTICES today, then. That needs to happen before the installer goes out. Oy.

**Comment by CDPotter** [comment]
Question does CS disregard (MFIP which kinda has snap?) count as a SNAP related WCOM?

**Comment by CDPotter** [comment]
Also, are we thinking make it in BULK/OTHER BULK's image?
