### ISSUE TITLE
Changing name of MEMOS to NOTICES

### ISSUE THREAD

**Issue by CDPotter** [MN-Script-Team/DHS-MAXIS-Scripts#1735]
There was discussion at the most recent hackathon about considering changing the name of the MEMOs button as there are LETRs and WCOMs in there. Here are some ideas that were floated around but please feel free to offer up alternatives as we wanna find a good word that will make sense for everyone. 

1: Notices
2: MEMO/WCOM
3: (your idea here!)

---

VKC edit: we're going with NOTICES. Each MEMOS script needs to be moved to a NOTICES folder and have its name changed both within the script and in the filename itself.

Here's a list...

- [x] Update redirect list to create a new redirect file in the installer
- [x] Create redirect file for GitHub/script users
- [x] Create new folder for NOTICES
- [x] Create new MAIN MENU for NOTICES
- [x] Convert old MAIN MENU to a simple redirect ala NOTES alpha split menus (old folder must remain for folks not yet using the newest Power Pad)
- [x] Update 12 Month Contact
- [x] Update ABAWD With Child In HH WCOM
- [x] Update Appointment Letter
- [x] Update CS Disregard WCOM
- [x] Update Duplicate Assistance WCOM
- [x] Update GRH OP CL Left Faci
- [x] Update LTC - Asset Transfer
- [x] Update MA-EPD No Initial Premium
- [x] Update Method B WCOM
- [x] Update MFIP Orientation
- [x] Update MNSure Memo
- [x] Update NOMI
- [x] Update Overdue Baby
- [x] Update Postponed WREG Verifs
- [x] Update SNAP E&T Letter
- [ ] Update Power Pad with NOTICES button
- [ ] Test each script button

**Comment by theVKC** [comment]
My vote is for "notices". I think "NOTICES - SCRIPT NAME GOES HERE.vbs" jives well with "ACTIONS - SCRIPT NAME GOES HERE.vbs".

**Comment by C-Love** [comment]
I like NOTICES

**Comment by IlseFerris** [comment]
Notices is my vote. There I said it.

**Comment by Y-Lor-Y** [comment]
I'm for the "Notices" button.  It does flow well with the other categories.
