### ISSUE TITLE
Baby Born and Change Reported scripts not opening? --Critical Bug--

### ISSUE THREAD

**Issue by MelissaFox-Stearns** [MN-Script-Team/DHS-MAXIS-Scripts#1748]
These two scripts won't open for me and kick me back out to the main menu. Is anyone else having issues?

**Comment by RobertFewins-Kalb** [comment]
Yep... when I click either script, I get this message...

![image](https://cloud.githubusercontent.com/assets/7842016/12595459/04842506-c441-11e5-892b-d70319dd922a.png)


But when I click it again, it case notes in MAXIS showing only...
"---"
worker_signature

**Comment by RobertFewins-Kalb** [comment]
(not going to paste pictures of MAXIS on GH)

**Comment by MelissaFox-Stearns** [comment]
Yep me too!

**Comment by RobertFewins-Kalb** [comment]
It looks like there are issues with the dialog names and the dialog calls. The values in the first dialog are never being established so the script skips them.

I don't really see why it's looping and making you push the button twice, however...

...digging

**Comment by RobertFewins-Kalb** [comment]
(To elaborate, the first dialog in NOTES - CHANGE REPORTED is not being called so the value "List1" is never being assigned a value.)

**Comment by RobertFewins-Kalb** [comment]
I'm working on it

**Comment by RobertFewins-Kalb** [comment]
Soon to submit a fix

**Comment by RobertFewins-Kalb** [comment]
@MelissaFox-Stearns, can you rename this issue to highlight that this is a critical bug?

**Comment by RobertFewins-Kalb** [comment]
@theVKC, I'm concerned that the Baby Born script is dumping Social Security Numbers in case notes. The New Hire DAIL Scrubber specifically edits out the client's SSN. Should we update this one? (Separate issue)

**Comment by theVKC** [comment]
@RobertFewins-Kalb: any issues with SSNs should be addressed on a separate issue from the critical fix.

Also, this needs to be fixed in release too, I believe. @RobertFewins-Kalb: can you pull it in there (if you haven't already)?

**Comment by RobertFewins-Kalb** [comment]
I shall (create a new issue and a new pull request for release)
