### ISSUE TITLE
NOTES- Employment Plan/Status Update script- Receiving a message when choosing school as primary activity.

### ISSUE THREAD

**Issue by MelissaFox-Stearns** [MN-Script-Team/DHS-MAXIS-Scripts#1752]
When I choose the Employment Plan- High School/ GED as the Primary Activity and then fill in the edit box with the school information, I am given a message box that says I did not complete the school information field even though I have. 
I haven't come across this message for any of the other primary activities so it appears to just be this one area. 
Does this happen with anyone else?

**Comment by theVKC** [comment]
Sounds weird, like we should fix it. Is it happening elsewhere in Stearns? Also: do you want it? :)

**Comment by courtrightd** [comment]
I'm seeing the same error.  This can be assigned to me if you want.

**Comment by theVKC** [comment]
You got it!
