### ISSUE TITLE
NOTES Main Menu- EDRS DISQ match found- explanation of script is cut off on the dialog box 

### ISSUE THREAD

**Issue by MelissaFox-Stearns** [MN-Script-Team/DHS-MAXIS-Scripts#1753]
ON the D-F Notes Sub Menu. The new script for EDRS DISQ Match found looks like it the explanation didn't fit all onto 1 line so it cuts off after "per"

**Comment by CDPotter** [comment]
I fixed it in my pull today along with another one on the interview script.

**Comment by MelissaFox-Stearns** [comment]
Oops! Thanks I'll close this

**Comment by theVKC** [comment]
Not sure this should have closed, because it's still an open issue that hasn't yet been resolved with a pull request. Unless it's a duplicate or a question, please don't close your own issues if the issue hasn't been resolved. :)

**Comment by CDPotter** [comment]
I added this small fix along with another one that was cut off in this update.
