### ISSUE TITLE
Shelter form rec'd needs to be removed from NOTES main menu

### ISSUE THREAD

**Issue by IlseFerris** [MN-Script-Team/DHS-MAXIS-Scripts#1757]
Can anyone take care of this? Otherwise I can do it in the morning.

**Comment by RobertFewins-Kalb** [comment]
I removed it when I submitted my pull request to create it as an actions script. Has it been added back to the menu?

**Comment by IlseFerris** [comment]
It's live on master and release, so I it looks like that may be the case

**Comment by RobertFewins-Kalb** [comment]
Crap stick. I'm looking over my pull request and I did in fact NOT remove it from the NOTES main menu even though I made other updates to the NOTES main menu. Mea culpa. Looks like I updated the NOTES main menu to include the explanation of income.

**Comment by IlseFerris** [comment]
Crap stick indeed...LOL! If you could fix that stick that would be great. BAHAHAHAHAHA!
Also thank you :)
