### ISSUE TITLE
Critital BUG REVW/MONT closures unable to get to case note

### ISSUE THREAD

**Issue by CDPotter** [MN-Script-Team/DHS-MAXIS-Scripts#1759]
The script is having issues for some workers trying to get into a new case note. Script is getting hung up on  PROG PF9ing and dumping case note onto PROG. 

Looks like a Start_a_blank_case_note fixes it. uploading fix.

**Comment by theVKC** [comment]
Is this happening in RELEASE too?

**Comment by CDPotter** [comment]
Unsure, I can pull just to be sure?

**Comment by theVKC** [comment]
I would. Thanks @CDPotter!

**Comment by CDPotter** [comment]
#1769
