### ISSUE TITLE
BUG - Bulk Case Transfer is not stopping at the specified number of cases

### ISSUE THREAD

**Issue by C-Love** [MN-Script-Team/DHS-MAXIS-Scripts#1764]
Basically the script will just keep on transferring until it gets through all of the cases, completely ignoring the number put entered in the second dialog. It doesn't happen every time. 

I have the fix (convert a string to a number so math will happen).

**Comment by theVKC** [comment]
Do you think this is critical enough to warrant sending to RELEASE as well, @C-Love?

**Comment by C-Love** [comment]
It is fairly critical so that would probably be good.

**Comment by theVKC** [comment]
Sounds good. If you could do that @C-Love, that'd be much appreciated.
