### ISSUE TITLE
Remove SSN field from baby born in Change Reported

### ISSUE THREAD

**Issue by RobertFewins-Kalb** [MN-Script-Team/DHS-MAXIS-Scripts#1768]
In DAIL - NEW HIRE, we are x'ing out the client's SSN. In reviewing the baby born section in NOTES >> CHANGE REPORTED, I found that the dialog includes a field for the child's SSN and that it's a mandatory field. I move that the field be removed entirely.

Thoughts...?

**Comment by Farleight** [comment]
I would concur; if it's not editing the Memb panel, it doesn't need it. This falls under my "don't ask; don't tell" policy.

**Comment by theVKC** [comment]
If it has no action (i.e. updating a non-CASE/NOTE panel in MAXIS), I agree completely. If it updates a panel in MAXIS, it should remain (but obviously not case note).

Any takers to investigate? Could be an easy win, @MN-Script-Team/county-agency-scriptwriters!

**Comment by StormageddonDLOA** [comment]
I can take this.

**Comment by theVKC** [comment]
Thanks @StormageddonDLOA!
