### ISSUE TITLE
New script - banked month database maintenance

### ISSUE THREAD

**Issue by courtrightd** [MN-Script-Team/DHS-MAXIS-Scripts#1787]
This would be a utility that checks all cases in the access database.  It steps through all cases/members coded as using a banked month in the month selected, goes to ELIG/FS, finds the most recent approved version, and checks that the member remains active, if not, it reassigns the database value so that an accurate list can be submitted to DHS.
I propose calling it a UTILITY because it updates a database, not MAXIS, but would be open to BULK as well.  
Once I know where it belongs I will pull in my latest version, as well as a copy of the database table to insert into usage statistics.accdb.

**Comment by theVKC** [comment]
First of all: yes to it being a utility.
Second: I think it sounds wonderful.
Third: I don't think it should be inserted into usage statistics.accdb: I propose a separate folder and database (as I don't want to force current usage statistics.accdb users to have to update any schema or other Access pieces if they don't want to).

Thoughts on that?

**Comment by courtrightd** [comment]
I’m fine with that, just needs a new global variable for banked_month_database_path and edit a couple lines of code.   Counties can assign the path however they wish.

**Comment by theVKC** [comment]
Sounds great, and thanks!
