### ISSUE TITLE
SNAP E & T student info updates needed

### ISSUE THREAD

**Issue by IlseFerris** [MN-Script-Team/DHS-MAXIS-Scripts#1789]
Needs following information to be updated: 
* Eligible student needs to be student
* Directions to include sending a verification request form for E & T contact
* Informative message that a 30 day TIKL is automatically made when a manual referral is made.

**Comment by theVKC** [comment]
@IlseFerris: there isn't a lot of info on your issue. In the future, please try to add more detail about what's missing. For example, "what verbiage actually needs to change?" or "what instructions are missing?" I'm trying to make sure we all provide more detail about the work we do as we're doing the work.

**Comment by IlseFerris** [comment]
I'm in meetings all day, I'll be able to expand on this in a couple hours. Sorry for the quick issue/pull.
