### ISSUE TITLE
New Script Dail Scrubber for TYMA TIKL handling

### ISSUE THREAD

**Issue by CDPotter** [MN-Script-Team/DHS-MAXIS-Scripts#1792]
Adding a TYMA TIKler script for those that will use the dail scrubber to TIKL as you go for TYMA.

**Comment by theVKC** [comment]
Related to #1754. That script should be complete before this one is started.

@CDPotter: do you expect completion before February 16 for the script freeze?

**Comment by theVKC** [comment]
Also, updated title. "New script dail scrubber" isn't very clear, as it requires the end user to click it to see details about the script. Please try to add more detail in the future, @CDPotter. :)

**Comment by CDPotter** [comment]
RE: previous comment, they are all completed, tested, and pulled.

**Comment by theVKC** [comment]
Yup, you were fast! :) Thanks!
