### ISSUE TITLE
CRITICAL Enhancement Dail scrubber new hire (new dail message)

### ISSUE THREAD

**Issue by CDPotter** [MN-Script-Team/DHS-MAXIS-Scripts#1795]
Apparently the new hire messages have been revamped. Here is what I've found so far. 

![mn jobs](https://cloud.githubusercontent.com/assets/7841989/12847592/0b251da2-cbda-11e5-9c93-00d9fc0a2ec5.png)

They even include out of state jobs. 

![out of stat jobs](https://cloud.githubusercontent.com/assets/7841989/12847595/0e544746-cbda-11e5-8aa6-089c3ebb412d.png)

**Comment by CDPotter** [comment]
My gut is start reading at job details instead of the beginning of the message since the states can vary. If we wanna go with this method I can pull whenever. 

![fix](https://cloud.githubusercontent.com/assets/7841989/12847744/f7433688-cbda-11e5-8456-4b728aacb100.png)

I'm reviewing the new hire script as there are some changes to what to read as well. Yay friday!

**Comment by IlseFerris** [comment]
Good catch @CDPotter! It looks like JOB DETAILS is static, so it looks like it would work to me.

**Comment by CDPotter** [comment]
Uh oh.. maybe not...?
![uh oh](https://cloud.githubusercontent.com/assets/7841989/12848066/20a404e2-cbdd-11e5-9a50-9d1585d07088.png)

**Comment by CDPotter** [comment]
And I just got word that someone had two HIRE messages for the same job. 

HIRE 01 16    NEW MI JOB DETAILS FOR SSN
HIRE 02 16    NEW JOB DETAILS FOR SSN #4

She deleted the MI one before I could look at it but I think we need clarification of how these new messages work and if they will replace the old ones. @theVKC Is there any digging you can do into this? There's nothing on SIR about a change.

**Comment by CDPotter** [comment]
Turn of events. SIR posted at 7:51 (moments after I checked). This is gonna be a weird one. I'm assuming we are getting these out of state/duplicate ones because of out of state HQs for companies.

**Comment by MelissaFox-Stearns** [comment]
Yeah I've noticed it appears to go by corporate headquarters. Like a Walmart job will show up as AR.

**Comment by MelissaFox-Stearns** [comment]
Have we come across  any of the normal New Hire messages that are NOT duplicates? Sir says to delete the duplicate ones that are not from the National Directory of New Hires (NDNH) so maybe we can have something that checks for duplicates and proceeds with the NDNH one?

**Comment by C-Love** [comment]
I have a user with some that are the older, normal version that do NOT have a duplicate with the new version.

I vote for 2 different scripts.

**Comment by MelissaFox-Stearns** [comment]
Yep me too.

**Comment by theVKC** [comment]
Wow, this is funny. Just emailed you all about it. This group is amazing.

My vote is for two scripts. @CDPotter: I assume you want this!

**Comment by theVKC** [comment]
Also, I don't think it's critical if it's only affecting a new DAIL message. If the old ones still work, it's an enhancement and not a critical bug fix.

**Comment by theVKC** [comment]
(But of that last comment, I'm open to suggestions otherwise, as I'm not processing them)

**Comment by MelissaFox-Stearns** [comment]
It's not a bug, but from the chaos surrounding me this morning... I would say it's critical.
It's funny how we forgot how we had to do all of this manually not that long ago.

**Comment by theVKC** [comment]
If this is causing a mild panic with counties, I'll mark it as a (somewhat rare) "critical enhancement".

**Comment by CDPotter** [comment]
Doing my Friday Intake but once I'm done I can upload.

**Comment by theVKC** [comment]
Excellent. Thank you @CDPotter!!

**Comment by MelissaFox-Stearns** [comment]
He da real VP!

**Comment by theVKC** [comment]
@CDPotter: earning MAJOR kudos right now. :100:  

When completed and tested, can you pull this into both master and release, @CDPotter?

**Comment by CDPotter** [comment]
Question on pulling to release. TYMA TIKLer isn't there. Will that cause problems?

**Comment by CDPotter** [comment]
(my gut says pull the dail scrubber script along with the NDNH script then leave the TYMA one behind but keep the code in the dail scrubber script to avoid merge conflicts?)

**Comment by theVKC** [comment]
I'd just copy the NDNH related code and pull that. Yes there might be a merge conflict, but I have a way around that using a force push.

**Comment by theVKC** [comment]
Instructions are updated. Thanks all! Go team, and especially go @CDPotter!
