### ISSUE TITLE
Denied programs has colons that duplicate

### ISSUE THREAD

**Issue by IlseFerris** [MN-Script-Team/DHS-MAXIS-Scripts#1801]
In some of the case note lines in this script there are colons after the initial case note line text, and the "write_bullet_and_variable_to_case_note" function are being used. 

Hennepin Charles (Senhorc) is submitting a fix momentarily.

**Comment by theVKC** [comment]
Go @senhorc!

**Comment by theVKC** [comment]
Self assigning so I process it when I switch PCs shortly. @senhorc has this on lock! Woot!

**Comment by IlseFerris** [comment]
Woot indeed! @senhorc is here!

**Comment by CDPotter** [comment]
I feel like we almost need a introduction section for new people.

**Comment by theVKC** [comment]
I suppose I can always shoot out an email with info each time a new contributor joins in...

**Comment by IlseFerris** [comment]
An intro would be awesome! We should all do a little into piece too. It would be fun.
