### ISSUE TITLE
Enhancement-Combined AR script-interview date box

### ISSUE THREAD

**Issue by devonne01** [MN-Script-Team/DHS-MAXIS-Scripts#1804]
HC and MSA do no require interviews. Can we make the interview box not a mandatory field?

**Comment by CDPotter** [comment]
It isn't mandatory. The only loop untils are "Loop until worker_signature <> "" and review_status <> "Select one..." and actions_taken <> "" and recert_datestamp <> """

Has the error been happening to you?

**Comment by devonne01** [comment]
You are correct. I was wrong..

**Comment by CDPotter** [comment]
No worries! Just wanted to make sure we didn't have any version/location issues.
