### ISSUE TITLE
BUG CS disregard FIATER: unmarried parents with one shared kid and one non shared kid

### ISSUE THREAD

**Issue by CDPotter** [MN-Script-Team/DHS-MAXIS-Scripts#1810]
So we ran into a case that didn't work properly with the CS disregard FIATER because of the odd HH composition:

Memb 01: mom
Memb 03: mom and unrelated’s child
Memb 20: unrelated
Memb 21: unrelated’s child

(the script doesn't FIAT for memb 21 because it only looks at applicant's PARE)

I tend to lean towards this might just be one of those rare cases that needs to be processed manually but I wanted to get the opinion of other's who handle MFIP/DWP to see if it's more common than I'm thinking. Thoughts?

**Comment by theVKC** [comment]
We're at hackathon today. Here's a tag for all MAXIS attendees:

@MelissaFox-Stearns 
@GayS 
@StormageddonDLOA 
@devonne01 
@khiestand 
@Y-Lor-Y 
@C-Love 
@IlseFerris

**Comment by Y-Lor-Y** [comment]
I can reasonably say that there are quite enough amount of cases out there that this will be a common thing.  Some county may have it specialized where all of these cases are localized to one worker.

This might be more additional work, but could we have it where it does the following:

If PMI (from CS DAIL) = memb (the child rec’ving CS Incomes) = counts elig membs if elig membs under 18 (is this the cut-off?  Or if you’re still 18, in school, still on MFIP, and still rec’ving CS = does this still applies to you?)  I don’t remember seeing age limit beside verbiage ‘minor’ – in that stance, I’m to assume it’s referring to under 18.

OR remove the part where it looks at PARE, and have it look at ELIG MFIP instead & Age of those on ELIG/MFIP

By the time we run this script, there should’ve been an ELIG MFIP result out there.

For now until something’s done to handle/include these situations, I’d say a message to process it manually would be a good idea.


Yang T. Lor | FCM Resource Trainer
Financial Assistance Services |  Ramsey County CHS
160 Kellogg Boulevard East, Saint Paul, MN  55101
P: 651-266-3621  |  Fax: 651-266-3705
E: yang.tou.lor@co.ramsey.mn.us
Schedule: M to Th, 7:45 AM to 6:00 PM
www.ramseycounty.us<http://www.ramseycounty.us>

The information included in this email message, including any attachments, is intended only for the person or organization to which it is addressed.  This email message may contain information that is privileged or confidential.  If you receive this email message and are not the intended recipient or responsible for delivering the message to the intended recipient, you may not use, disseminate, distribute, or copy the information included in this email and any attachments.  If you received this email by mistake, please reply by email and destroy all copies of this message and any attachments.  Thank you

**Comment by Farleight** [comment]
I won't be at the Thon, but Yang is correct, that sort of HH comp is not even remotely "rare." So if you're questioning the merit of fixing for it... there's merit. 267% sure on this one.

**Comment by RobertFewins-Kalb** [comment]
I like the approach of going to ELIG/MFIP, grabbing the reference numbers of all people that are eligible, then going to MEMB for each person to grab their age, then grabbing the cs amounts, then going back to ELIG to FIAT the results.

**Comment by theVKC** [comment]
+1 to all of you. @CDPotter: would you like to take this one?

**Comment by CDPotter** [comment]
Sure I can poke at it tomorrow after SNAP WCOM.

**Comment by theVKC** [comment]
Wonderful! I'll mark it for Feb release, but know you can always kick it back to March if you'd like.

**Comment by CDPotter** [comment]
Since I don't know much about MFIP/DWP I may be asking a lot of questions. 

If we go with pulling ref numbers of eligible people off of MFIP/DWP ELIG is it safe to then use anyone 18 and under (or is it up to 18th bday?) to count kids? 

Is it possible to have someone unrelated who is under 18 who is eligible for MFIP/DWP? (say someone else's child staying with the applicant family)

Also any other odd combinations of HHs that we find in MFIP/DWP?

**Comment by Farleight** [comment]
They can remain on MFIP up to 19, assuming they're still in school.

I can't think of anyone unrelated who would be on the Cash portion of the grant without some kind of special custodial arrangement... potentially Uncle Harry... but it's been awhile since I've had an MFIP caseload, so wait for additional response on that one.

Relative Care MFIP happens often, but that's not really "odd" in the way I assume you mean.

**Comment by Y-Lor-Y** [comment]
Let me put some scenarios up, hope it’ll help you.  I’ve put my response under your questions below…I welcome any inputs to my answers below and/or corrections.

****

If we go with pulling ref numbers of eligible people off of MFIP/DWP ELIG is it safe to then use anyone 18 and under (or is it up to 18th bday?) to count kids?

My response:
I also went back and review the CM 17.15.03 – it references to child being on the MFIP/DWP grants.  I looked in the glossary for child, it reference me to minor child, and under minor child is the following verbiage:  So it can be up to age 19 and still full time student or equivalent  training.
MINOR CHILD
A child under age 18.

MFIP, DWP : A child who lives with PARENTS or other CAREGIVER, is not the parent of a child in the home, and who is 1 of the following:
●

Less than 18 years old.


OR

●

Under the age of 19 and a FULL-TIME STUDENT in a SECONDARY SCHOOL or equivalent level of vocational or technical training, designed to fit students for gainful employment.




Is it possible to have someone unrelated who is under 18 who is eligible for MFIP/DWP? (say someone else's child staying with the applicant family) – Yes it is possible.

My response:  (the scenarios below already taken into consideration that verification of relationship has been established already and etc, thus, MFIP is active for ongoing)

Scenario 1)

You can have the following situation happening: 1 caregiver, and she has one biological child, and one related child, and they’re all receiving MFIP on one case.  The related child is a nephew to the caregiver.  And in this situation, assuming the related child is receiving CS incomes.  The disregard would apply to this case MFIP grants.

Scenario 2)

You could have grandma applied for MFIP for only two of her grandchildren.  1 Adult, 2 children.  Caregiver does not want any assistance.  Both children receives child supports.  Disregard would apply to the MFIP grants.

Scenario 3)

You have Uncle, Aunt, and their biological child on UNCLE HARRY.  However, you have nephew and niece with this household, and both are open on MFIP.  Both are receiving CS incomes.  The CS disregard, would need to be applied to the MFIP grants on this case.

Also any other odd combinations of HHs that we find in MFIP/DWP?

My response:
I don’t see this situation happening on a regular base, so, I’m calling this as a rare based on my experience when I was and current involvement of the MFIP program in Ramsey County, hence the “ONLY” stipulation part is what I’m referring to…if the CS incomes is forwarded to the minor caregiver – when that does occur, we do need to apply disregard to minor caregiver’s MFIP case.  I’m going to also ask for more inputs from the others on this specific situation… (CM: 17.15.03)

When a minor caregiver does not live with an adult custodial parent, count the minor caregiver’s portion of the child support as the minor caregiver’s income ONLY if the income is forwarded to the minor caregiver or to the adult with whom the minor caregiver lives. If the child support is not forwarded, do not count it against the minor caregiver’s case nor count it against the MFIP grant of the parent who received the child support payment.

**Comment by RobertFewins-Kalb** [comment]
@theVKC, do we know if the promised MAXIS enhancement is on the horizon? I worry about dedicating a bunch of time to correct a problem that is supposed to be resolved through MAXIS. We're looking over a game plan to enhance the script and it's not a simple one. Popcorn, @CDPotter!!

**Comment by CDPotter** [comment]
So we've had a few thoughts about how to restructure things:

1; use an excel file (not preferred method) to organize things and determine what kids should be eligible.

2: Use a HH member dialog to have workers select kids. This would create an array and we would bypass the PARE panel (resolving the unrelated parents with shared kid and non shared kid issue), then check UNEA and ELIG as it currently does. (easy method but does require worker to know who the children on the case are, though the script still evaluates if they have SSI, CS and eligibility for CASH)

3: Rebuild array off of ELIG(to get elig people), then memb(to get everyone in case the pare is inelig),  then check PARE for everyone to find KIDS listed in ELIG (using instrings) then taking those kids and checking their UNEA and ELIG as it currently does. 

Thoughts?

**Comment by Y-Lor-Y** [comment]
I like option #2, and it  put a little incentive on the worker, too!  However, option #3 may be more effective in error reduction and time saving.

I think whichever of the two you choose, I’m fine with it.  Both process are a lot better than having the script stop, and telling the worker to review and process it manually.

Yang T. Lor | FCM Resource Trainer
Financial Assistance Services |  Ramsey County CHS
160 Kellogg Boulevard East, Saint Paul, MN  55101
P: 651-266-3621  |  Fax: 651-266-3705
E: yang.tou.lor@co.ramsey.mn.us
Schedule: M to Th, 7:45 AM to 6:00 PM
www.ramseycounty.us<http://www.ramseycounty.us>

The information included in this email message, including any attachments, is intended only for the person or organization to which it is addressed.  This email message may contain information that is privileged or confidential.  If you receive this email message and are not the intended recipient or responsible for delivering the message to the intended recipient, you may not use, disseminate, distribute, or copy the information included in this email and any attachments.  If you received this email by mistake, please reply by email and destroy all copies of this message and any attachments.  Thank you

**Comment by theVKC** [comment]
I support option 2, @CDPotter and @RobertFewins-Kalb. I am inquiring as to the status of this issue with MN.IT, though. I vote to hold off until I know more (for obvious reasons @RobertFewins-Kalb touched on).

**Comment by theVKC** [comment]
Also, @CDPotter or @RobertFewins-Kalb: thoughts on dropping this from February release and targeting March instead? We have a day to complete it for February.

**Comment by RobertFewins-Kalb** [comment]
Yeah...March at the absolute earliest.

**Comment by theVKC** [comment]
Closing this. Can re-evaluate in the future.
