### ISSUE TITLE
Dail - New Hire- Have script check jobs panel carries through to next footer month

### ISSUE THREAD

**Issue by MelissaFox-Stearns** [MN-Script-Team/DHS-MAXIS-Scripts#1821]
When New Hire script adds a jobs panel in, often times it does not carry through to the next month. 
It seems it would not be possible to have the script go into the next footer month to add or check for the jobs panel because it could cause a duplicate jobs panel to be entered. 
What I am proposing is to have the New Hire script check for the "This data will expire on ...." when Jobs panel is entered and then alert the worker that it may not have carried over. 

Any thoughts?

**Comment by theVKC** [comment]
Love it. Good luck!

**Comment by theVKC** [comment]
@MelissaFox-Stearns: have you started on this? Just curious about an ETA... I've heard info about possible New Hire procedure changes and I'm wondering if it would make more sense to close this.

**Comment by MelissaFox-Stearns** [comment]
Oh really? I'm done with it I just haven't pulled it yet. Should I hold off?
What kind of changes are they making?

**Comment by theVKC** [comment]
Nothing affecting the main running of the script, as far as I know, but you never really know. If you've already done it, I think we're OK to pull it.
