### ISSUE TITLE
NAV - PHONE NUMBER OR NAME LOOKUP: Stats concern in last name lookup

### ISSUE THREAD

**Issue by theVKC** [MN-Script-Team/DHS-MAXIS-Scripts#1825]
It looks like it's saying just 10 seconds, period, regardless of how many screens it searches through. I'd think that 10 seconds is per REPT/* screen.

Thoughts? If other @MN-Script-Team/county-agency-scriptwriters agree that the name lookup should be more than 10 total seconds, we'll need someone to volunteer to take this one this week. :)

**Comment by theVKC** [comment]
OK, I'm making the call and will add a counter to register each page it searches.

**Comment by mldietz** [comment]
I know it definitely takes more than 10 seconds to run. 10 seconds per page sounds about right.

**Comment by GayS** [comment]
agreed - thanks for fixing it @theVKC .
