### ISSUE TITLE
Very minor typo on NOTES - CAF

### ISSUE THREAD

**Issue by theVKC** [MN-Script-Team/DHS-MAXIS-Scripts#1853]
NOTES – CAF  has the following format error on line 530:

IF E_and_T_checkbox = checked THEN CALL write_variable_in_CASE_NOTE("*Client is willing to participate with E&T")

There should be a space between * and Client to be consistent with the rest of the note.

I am not taking this, but I have a scriptwriter in the wings who might want this one.

**Comment by theVKC** [comment]
@KateiMartini fixed this one for us. Thank you! #WashingtonCountyOnTheBoard

**Comment by IlseFerris** [comment]
Nice, and welcome Washington county!
