### ISSUE TITLE
BUG CAF no longer writing MM/YY in header for recerts

### ISSUE THREAD

**Issue by CDPotter** [MN-Script-Team/DHS-MAXIS-Scripts#1860]
CAF is writing ***/ recert: incomplete" looks like variable was changed to MAXIS_footer_month above but not below. On it.

**Comment by CDPotter** [comment]
NOTE: not an issue in release as release still has footer_month and footer_year.

**Comment by theVKC** [comment]
Curious @CDPotter: why shouldn't we change all instances of `footer_month` to `MAXIS_footer_month`? I believe I might have initially suggested that to @IlseFerris when she was working on this. Seems more descriptive and jives well with other systems which use that terminology. Thoughts?

**Comment by CDPotter** [comment]
I know @RobertFewins-Kalb was on board with this since they use this convention in PRISM-land. I think it would be a good change.

**Comment by theVKC** [comment]
One issue I could see with that approach (to contradict myself) is that we use footer_month in FuncLib for some logic:

![image](https://cloud.githubusercontent.com/assets/5701751/13018101/660931c8-d18d-11e5-84d5-31e97048c722.png)

So, if we go that route (which I support wholeheartedly), we need to apply it across the board.

I also support doing this with case_number. I think MAXIS_case_number is far better and allows a greater amount of clarity. We'd have to do one big find/replace.

**Comment by CDPotter** [comment]
Indeed, it would be quite the overhaul!

**Comment by theVKC** [comment]
I think we should talk about that with others at DHS hackathon next Monday (not this Monday).

**Comment by CDPotter** [comment]
Sounds like a plan, I can add a new issue to prompt discussion? (so we can resolve and close this one for now)

**Comment by theVKC** [comment]
Add it to FuncLib, actually. Seems that's the first place we'd need to evaluate, right?

**Comment by CDPotter** [comment]
On it.

**Comment by IlseFerris** [comment]
I updated many footer_month/footer_year in to MAXIS_footer_month and MAXIS_footer_year during Operation Doubtfire. This probably would be too bad in the script files, but it will be time consuming in the FuncLib.
