### ISSUE TITLE
SCRIPTING RELATED ONLY: Type mismatch MAXIS_footer_month_confirmation

### ISSUE THREAD

**Issue by CDPotter** [MN-Script-Team/DHS-MAXIS-Scripts#1862]
Has anyone else had any issues with testing the CAF offline? I keep getting a type mismatch for MAXIS_footer_month_confirmation. When I was testing a recent fix I couldn't test it with this function not commented out. Looking at the function it doesn't change any variables nor does the find_variable function it uses. 

Anyone else hitting this?

**Comment by theVKC** [comment]
If your "use_master_branch" isn't set to "true", I could see this happening. @IlseFerris' new function is only in the master branch, because it's under testing...

@CDPotter, can you confirm this so we can close the issue?

**Comment by theVKC** [comment]
I don't know about you, but I know that @IlseFerris and I test with `run_locally` and GitHub Desktop, and this closely emulates the GitHub experience (of which branch goes where), but offline. This has allowed much greater flexibility in development.

**Comment by CDPotter** [comment]
That's the ticket! Closing!
