### ISSUE TITLE
BULK MEMO FROM LIST, stats counter only counting as one

### ISSUE THREAD

**Issue by IlseFerris** [MN-Script-Team/DHS-MAXIS-Scripts#1867]
@CDPotter, I was looking over your script to update the script list w/ time savings, and it looks like the stats counter is only counting the usage of the script as one instance, instead of it counting each instance within the script. Can you take a look at this one?

**Comment by CDPotter** [comment]
On it, I'll double check the other two.

**Comment by IlseFerris** [comment]
Awesomeness, and thank you! Take a look at BULK NON MAGI HC INFO if you need an example :)
