### ISSUE TITLE
New script Withdrawn Progs

### ISSUE THREAD

**Issue by CDPotter** [MN-Script-Team/DHS-MAXIS-Scripts#1879]
Would anyone be interested in a withdrawn programs script that works similar to denied progs? If so assign to me and I can update for statewide use and pull in.

**Comment by theVKC** [comment]
I don't know if I like this idea... I think an action script to properly update panels (i.e. not just "whatever people want to put on PACT") might be better. I worry this would contribute to button overload, as it fairly neatly fits inside closing or denying a program.

My vote would instead to be special editboxes on both denied and closed progs. But, I'm open to suggestions from other @MN-Script-Team/county-agency-scriptwriters or from @ruthmaloney!

**Comment by CDPotter** [comment]
Makes sense, that was my original though but the people who suggested it thought it would be helpful to have some of the specifics (plus it calculates the rein days better than denied, but that could be fixed with withdraw specific boxes)

Here is the screens for the script I built and have running for our county. 

![dlg](https://cloud.githubusercontent.com/assets/7841989/13111911/1773b88e-d54e-11e5-8d9b-a41715e0c4b2.png)
![cn](https://cloud.githubusercontent.com/assets/7841989/13111912/1b701bf8-d54e-11e5-980e-1625e5263da5.png)

**Comment by ruthmaloney** [comment]
I don't see anything wrong with it. We don't want people using PACT when they can complete the action using other panels (in this case the REPT/PND2), which this appears to do/promote. Is there anything out there that incorporates all of the PND2 actions that can be taken into one script? We see many cases where the applicant failed to interview, yet the worker fails STAT panels instead of changing the code on REPT/PND2 to deny for no interview and are still seeing many Agency/Client delay errors. Not sure if this is possible, but it would be nice to see some type of script that could run anytime an action (other than approval) is taken on a pending case, reminding the worker to think about the REPT/PND2 codes. The downside to becoming more aware of the PND2 codes, is that we are also seeing workers now using the PND2 denial reasons for missing verifications instead of using PACT (the prior "cheat") or the correct STAT panels.

**Comment by courtrightd** [comment]
Perhaps the pnd2 issues could be helped with an enhancement to denied progs along the lines of:
Check here to have the script deny from REPT/PND2 if the applicant did not complete the interview and NOMI was sent.
Check here to have the script deny from REPT/PND2 if the applicant withdrew their application.

**Comment by theVKC** [comment]
How about a prompt that asks the worker details, and then it does the right thing PND2-wise, turning this "withdrawal note" into a more comprehensive actions script around "properly deny this case"?

**Comment by ruthmaloney** [comment]
I like it

Ruth Maloney

**Comment by theVKC** [comment]
Thoughts @CDPotter? @courtrightd? Anyone else paying attention to this thread? :)

**Comment by devonne01** [comment]
I like it too ☺

**Comment by CDPotter** [comment]
Sorry case work was calling. 

So the thoughts are:

1: to add to denied progs to adjust the rein dates and case note when things are denied off of PND2 and with what code
 
or

2: Rework the withdrawn progs draft into an actions script that updates PND2 based on what code you entered into an edit box?(or what checkbox you pick)

My only fear with option 2 is having the script take a denial action for the worker(granted it's a very reversible denial action). Typically I know we've strayed away from APPing. I would err towards the side of leaving the worker on PND2 with a message box.

**Comment by Y-Lor-Y** [comment]
Just piggy back on the option 2 Charles mentioned…Could we do it where, it’ll give them an option (dialog or msgbox) to choose (check box) or an edit box to put the info in, when it gets to that part (so the incentive is still on the worker’s taking action).  So the script will still be running from start to end, up to prior to APP’ing.  Though, this might take a bit more work.

Yang T. Lor | FCM Resource Trainer
Financial Assistance Services |  Ramsey County CHS
160 Kellogg Boulevard East, Saint Paul, MN  55101
P: 651-266-3621  |  Fax: 651-266-3705
E: yang.tou.lor@co.ramsey.mn.us
Schedule: M to Th, 7:45 AM to 6:00 PM
www.ramseycounty.us<http://www.ramseycounty.us>

The information included in this email message, including any attachments, is intended only for the person or organization to which it is addressed.  This email message may contain information that is privileged or confidential.  If you receive this email message and are not the intended recipient or responsible for delivering the message to the intended recipient, you may not use, disseminate, distribute, or copy the information included in this email and any attachments.  If you received this email by mistake, please reply by email and destroy all copies of this message and any attachments.  Thank you

**Comment by theVKC** [comment]
Personally I like both options 1 and 2. But I'm a jerk sometimes. :P

I don't think updating the PND2 code via script is on the same realm as APPing with a script, as APPing immediately triggers many, many additional actions and I don't think updating PND2 does that right away (could be wrong). @ruthmaloney: any thoughts on that?

**Comment by courtrightd** [comment]
I support enhancing denied progs purely for the sake of having less total scripts.  Another possibility to avoid the script taking the action would be to have denied progs check REPT/PND2 before the dialog pulls up, and autofill the denial reason editbox with the reason if it found a PND2 denial.  That way a worker incorrectly using PND2 would have to erase the “interview not completed, NOMI was sent” case note and replace it with “verifications not received”.  That might effectively point out the error?

**Comment by theVKC** [comment]
Ooooh, I like that @courtrightd. A MsgBox could explain why it's filling in what it did, and that would be a good alert-without-telling-the-worker-exactly-how-to-do-their-job...

**Comment by CDPotter** [comment]
@courtrightd I like that idea a lot.

**Comment by ruthmaloney** [comment]
When the code on PND2 is updated to an “I” (incomplete) or “R” (withdrawal), it will auto-deny during the overnight batch. When it’s changed from the “P” to an “A” (Agency delay) or “C” (Client delay), it will continue pending and only change what is stated as the delay cause on the pending notice that is sent on the 30th day.

Ruth Maloney

**Comment by RobertFewins-Kalb** [comment]
@courtrightd, that has my vote as well, especially if it is identifying which programs are being withdrawn from the coordinates of the R.

**Comment by ruthmaloney** [comment]
I’m torn… We need workers to be aware of the PND2 codes and understand how to get correct notices to go out to the client and when to use STAT panels.

Is there a way to have check boxes for why the case is being denied, ex: missing verifications, no interview, app withdrawn, etc… then some type of prompt to ask/say how/what panels/method they should use to deny. So if they check “no interview”, it would ask/search for an initial interview date, a NOMI date, and if both of those are complete, then do something (take the worker to, or autofill) with the PND2? If they select “missing verifications”, it would prompt them to complete the appropriate STAT panels, etc.

Ruth Maloney

**Comment by CDPotter** [comment]
So to sum, this will be an enhancement to DENIED PROGS that will now

1: Head to rept/pnd2 and read the program and code
2: If the program code is I or R write that program and reason in the "Denial reason" edibox (EX: SNAP: withdrawn on PND2)
3: Inform the worker if this information is found via a message box (EX: SNAP was coded with an R on PND2. This information was automatically entered on your denial reasons. If the case is not being withdrawn please review PND2)
4: Change the reinstate dates for the programs coded R or I based
5: Consider removing the first checkbox referring to changing the reinstate date based on if case was pending for verifs or not.

**Comment by devonne01** [comment]
I like that idea

**Comment by theVKC** [comment]
As this is purely informative, I'm guessing @CDPotter's proposal supports @ruthmaloney's concern?  

From my end, I like it.

**Comment by CDPotter** [comment]
(Sorry @ruthmaloney missed your comment while I was typing that)

My proposal might miss some of the points Ruth was getting at with regards to reminding workers when to code what. 

Personally what we did here at Anoka was to create a small cheat card that we asked people to put at their desk. It specific when you're allowed to use PACT/PND2/STAT to deny for SNAP

**Comment by courtrightd** [comment]
Okay, so to address those concerns, what if there are 3 checkboxes added, 1 for verifs, 2 for the pnd2 reasons, and the denial reason editbox becomes “other reason:”   (Then there is a visible reminder to use PND2 correctly)There is existing code in the script that I put there to check notices to see if verifs needed was the reason (and edit them if requested).  What if we modify it so that it checks the notices if “verifs needed” is checked, and checks PND2 if that is checked,  (before or after), and gives the worker a msgbox if the denial reasons don’t match maxis?  This will also catch mistakes such as putting unverified income in so the notice reads over income when it should have been verifs not provided.

**Comment by ruthmaloney** [comment]
Charles – will you email me that please? I’d love to be able to share it with agencies this year.

Ruth Maloney

**Comment by ruthmaloney** [comment]
I think I love it!

Ruth Maloney

**Comment by C-Love** [comment]
You guys are amazing! (I've been following along but busy with interviews and such) I think this will help us SO much! This is a huge area of errors for us. I think putting the wording for the notice in the way @courtrightd is saying will help workers be way more aware of the issues around these denials. 

Go team!

**Comment by CDPotter** [comment]
Ok! So after some wrestling with the denied progs dialog (that intake dates bit makes it a pain!) Here is what I have for a revamp so far:

If intake dates = TRUE
![2016-03-07 13_52_09-denied progs dialog](https://cloud.githubusercontent.com/assets/7841989/13581538/f537266a-e46c-11e5-9113-cbccb34453fa.png)

If intake dates = FALSE
![2016-03-07 13_59_01-denied progs dialog alt](https://cloud.githubusercontent.com/assets/7841989/13581541/f87ab918-e46c-11e5-9f78-fc57776257d7.png)

The plan I'm operating on is: The worker will check the necessary boxes then the script will go to Pnd2 (if a pnd2 box is checked) and check if what they entered on the script is what is on Pnd2. Then if missing verifs was checked it will check the most recent elig results for that program to make sure the case was denied for missing verifs per the notice. If there are any discrepancies between what the worker picks on the script and what they've coded the script will give them a message box. 

What are people's thoughts?

**Comment by IlseFerris** [comment]
That is awesome! Great looking dialogs too

**Comment by CDPotter** [comment]
Hitch in the plan, HC doesn't allow for PND2 denials/withdraw. Maybe change "Other Reasons" to "Other/Health Care" reasons?

**Comment by theVKC** [comment]
Agreed, @CDPotter.

**Comment by theVKC** [comment]
Any update on this, @CDPotter? Think we should delay it until the April release?

**Comment by CDPotter** [comment]
May as well. I've got the dialog working, but gotta rethink the way HC works. What do people there think of the format?

**Comment by C-Love** [comment]
I like the layout. I think it adds an additional level of detail about denials. I think the additional logic around connecting to the notices will be wonderful.

**Comment by theVKC** [comment]
@CDPotter: any chance this will be done this week? It's tied to the April release. No worries otherwise.

**Comment by CDPotter** [comment]
I believe the Pnd2 part is working as expected. The checking notices/elig screen part I haven't worked on yet. I could upload and we could add that as an enhancement down the line if people still want it? It got a little complicated.

**Comment by theVKC** [comment]
Your call.

**Comment by CDPotter** [comment]
I think I'll upload what I have, integrating reading notices/elig is quite the undertaking at the moment. Plus this will give us a bit of feedback on how people work with the changes in requirements of running the script.

**Comment by courtrightd** [comment]
I would be happy to work on the notices end of this in the future some time.

**Comment by CDPotter** [comment]
Feel free! I feel like you had a better vision for it anyway!
