### ISSUE TITLE
Allow birth dates other than 01/01

### ISSUE THREAD

**Issue by theVKC** [MN-Script-Team/DHS-MAXIS-Scripts#188]
This came from Stearns County. It's not considered core functionality, but it would allow training scenarios to more closely match production conditions, and I see that as useful. My thought is adding a "MM/DD" cell to each HH memb, right above the "age" cell (so that it's dynamically updated each year).

**Comment by RobertFewins-Kalb** [comment]
I have a working solution. #HoorayForMe
