### ISSUE TITLE
Bug case note/tikl from list

### ISSUE THREAD

**Issue by CDPotter** [MN-Script-Team/DHS-MAXIS-Scripts#1882]
Found another issue while creating instructions. Looks like in my copy and pasting I left in the wrong dialog call for the excel portion of these two scripts meaning the script defaults to the last dialog build and displays that. (interesting bug though!) Fix incoming.

**Comment by theVKC** [comment]
This is interesting. I also discovered some interesting stuff about dialogs and buttonpressed functionality. Remind me to play with it on Monday.
