### ISSUE TITLE
Housing grant FIAT: FIAT multiple months

### ISSUE THREAD

**Issue by IlseFerris** [MN-Script-Team/DHS-MAXIS-Scripts#1887]
I've had several requests for this enhancement. DHS sends out a list (I believe monthly) on cases that need to the Housing grant FIATed into the case. This would be a huge win for all counties. The ABAWD Banked MONTHS FIATer has this functionality so it should be pretty easy to replicate.

**Comment by theVKC** [comment]
How would you propose to do this programmatically? Just curious what your steps would be.

**Comment by theVKC** [comment]
Also, do you want it?

**Comment by IlseFerris** [comment]
It doesn't look like I have a choice now...LOL!
I'm thinking that we give a start date option, then FIAT through current month + 1. Basically go in and create a FOR..NEXT loop starting with the initial month selected, making and saving the FIAT, and repeating until CM + 1.

**Comment by theVKC** [comment]
That could work. Perhaps...

```
For each footer_month_to_process in process_month_array
    EMWriteScreen footer_month_to_process.footer_month, x, y
    EMWriteScreen footer_month_to_process.footer_year,  x, y
    '<<<Do a bunch of processing>>>
Next
```

Whatcha think? Objects maybe?

**Comment by theVKC** [comment]
I should clarify, this would be objects plus arrays.

**Comment by IlseFerris** [comment]
Looks doable to me

**Comment by Y-Lor-Y** [comment]
Am I thinking the same processing...These notes from DHS is referring to retro months.
If that's the case, that might work along then line with what @C-Love and I were talking about from Ramsey County about going back to retro months and approved via Mony/Check for the housing grants.

OR is this something totally different?
