### ISSUE TITLE
Exempt county handling for SNAP E & T letter & ABAWD banked months FIATer

### ISSUE THREAD

**Issue by IlseFerris** [MN-Script-Team/DHS-MAXIS-Scripts#1888]
x144 - Mahnomen is now exempt from E & T per SIR announcement. The other counties that are exempt have been blocked from using this script, so this county will need to be updated. 

@theVKC, Assign this one to me.

**Comment by ruthmaloney** [comment]
Aitkin and Mahnomen were both approved to be exempt

Ruth Maloney

**Comment by IlseFerris** [comment]
Good to know, adding x101 to the issue. Thanks @ruthmaloney!

**Comment by theVKC** [comment]
I've assigned this for March as it isn't a bug. The workers should simply refrain from using the script, right? Unless someone can give me a compelling reason to elevate it to a bug-to-be-fixed.
