### ISSUE TITLE
Update NOTICES and BULK menus to follow new NOTES conventions

### ISSUE THREAD

**Issue by CDPotter** [MN-Script-Team/DHS-MAXIS-Scripts#1889]
The new NOTES MAIN MENU conventions are less error prone than the current dynamic dialogs in NOTICES and BULK. They should be updated to all be the same convention.

**Comment by theVKC** [comment]
Good call. See FuncLib 163: https://github.com/MN-Script-Team/BZS-FuncLib/issues/163.

Want this one? Once the NOTES function is proved to be working I'll move a version to FuncLib that will also allow automatic alpha-splitting.

**Comment by IlseFerris** [comment]
Just as an FYI: the current NOTICES menu still says "MEMOS" in the dialog header and within the text of the dialog box. I'm sure this will be totally redone, but in case this doesn't get released into the RELEASE branch right away, this may be it's own issue.

**Comment by CDPotter** [comment]
Do we want to alpha split BULK/NOTICES or keep the them same as they currently are?

**Comment by IlseFerris** [comment]
I was thinking that I would create category buttons (similar to the NOTES main menu), except that the scripts would be separated by category. Are you taking the NOTICES menu @CDPotter? Either way, we should probably make them each their own issue. I was planning on taking BULK

**Comment by CDPotter** [comment]
Oh I was just going to tackle both of them since it's basically just converting NOTES MAIN MENU into BULK and NOTICES. Can you elaborate more on your ideas on how to split them?

**Comment by CDPotter** [comment]
Per sidebar with Ilse we decided to keep the current split for BULK and NOTICES

**Comment by theVKC** [comment]
I was thinking we could add to the function an ability to have other splits. Perhaps as an additional item on the class (`.alpha_split_override`). That way we could maintain separate splits for LTC, List Gens, et al.
