### ISSUE TITLE
Pay stubs rec'd- case noting the PIC all wonky

### ISSUE THREAD

**Issue by IlseFerris** [MN-Script-Team/DHS-MAXIS-Scripts#1891]
Has anyone gotten reports of the SNAP PIC is not case noting correctly?
![image](https://cloud.githubusercontent.com/assets/10836829/13154241/b4441b50-d63d-11e5-8617-414a6e553303.png)

This seems to be happening in both branches. 
This is from release branch: 
![image](https://cloud.githubusercontent.com/assets/10836829/13154296/ed5e15b2-d63d-11e5-9400-decb33a2a146.png)

**Comment by theVKC** [comment]
You'd think this would be fairly widely reported. I'd be curious to know if it's happening elsewhere.

**Comment by CDPotter** [comment]
Hmmm... worked properly for me.. I see you were able to repeat it. Anything odd about the data entered?
(I ran it on a case with a job, with 3 checks paid weekly, and only asked it to case note the PIC)

![test](https://cloud.githubusercontent.com/assets/7841989/13154874/b951caae-d640-11e5-8009-0a460525048d.png)

**Comment by asunderman** [comment]
From one of my co-workers….
I’ve noticed that sometimes it will use old information.  As in, I am processing a 3/16 renewal but the check amounts case noted for the PIC are from previous months.  I can’t say for sure that I wasn’t in a different footer month but I don’t feel like that should matter when you tell the script what month the review is for.  Does this make any sense to you? ☺

**Comment by theVKC** [comment]
@IlseFerris: is it possible the footer_month confirmation deal from the CAF script could also affect this?

**Comment by CDPotter** [comment]
@asunderman that's happening when you run paystubs rec'd or a renewal script?

**Comment by CDPotter** [comment]
Initial assessment: looks like it's reading the base jobs panel rather than the PIC. So the script is having some kind of issue getting into PIC to read it. Could be PIC isn't open long enough to read, could be PIC isn't getting opened, could be connection issues?

@IlseFerris Maybe putting a waitready in front of the part where it reads the PIC might help? Since I can't seem to replicate it I can't do too much to troubleshoot it at this point.

**Comment by IlseFerris** [comment]
I used 5 pay stubs each time. this might be throwing the error. 
I am going to test with 3, 4, 5 pay stubs after my very late lunch :(

**Comment by CDPotter** [comment]
Ok, go eat first! Gotta fuel the brain before tackling weird things like this!

**Comment by theVKC** [comment]
Go eat @IlseFerris.

**Comment by IlseFerris** [comment]
current_status = "eating"

**Comment by asunderman** [comment]
renewal

**Comment by CDPotter** [comment]
Ah well that would be a separate issue than this one with the paystubs rec'd. Could you create a new issue and detail what has been happening with what scripts?

**Comment by IlseFerris** [comment]
Thanks @CDPotter for troubleshooting with me :)

Looks like the issue is isolated to case noting the PIC for 5 pay stubs (or more pay stubs). The functionality of updating the PIC and JOBS is still in tact. I'll work on a fix this morning.

**Comment by MelissaFox-Stearns** [comment]
I have had this issue happen to me before but when I tried to replicate it a second time, it worked fine.
