### ISSUE TITLE
HH Comp/Baby Born script doesn't case note from Other Notes field. 

### ISSUE THREAD

**Issue by MelissaFox-Stearns** [MN-Script-Team/DHS-MAXIS-Scripts#1893]
A co-worker just brought this to my attention. When you click Notes- HH Comp Change- Baby Born. The Other Notes field in the dialog box doesn't case note. 

I think it would be an easy fix but I can't find the script on the master branch...

**Comment by IlseFerris** [comment]
It's been replaced by NOTES - CHANGE REPORTED.

**Comment by theVKC** [comment]
We should probably remove the script from the NOTES MAIN MENU if it's still showing up.

**Comment by theVKC** [comment]
Anyone want it? I'm in a meeting but have GitHub up. I can quick complete a pull request if needed.

**Comment by IlseFerris** [comment]
Baby born looks like it's already been removed, just HH comp is still there in the Master branch.

**Comment by MelissaFox-Stearns** [comment]
Yeah it's the hhld comp script that's running the same script as change reported. 
I can fix the Change Reported script so it case notes the "Other Notes" field. I can probably get to it some time today.
