### ISSUE TITLE
Possible bug appt letter writing last day to complete interview 12/31/1899

### ISSUE THREAD

**Issue by CDPotter** [MN-Script-Team/DHS-MAXIS-Scripts#1896]
Anyone else hitting this bug? I had it reported by one user on one case and I haven't been able to repeat it. 

![appt letter](https://cloud.githubusercontent.com/assets/7841989/13182162/07ae686e-d6f6-11e5-97c0-059842206c82.png)

**Comment by theVKC** [comment]
Seems like a looping error or something.

**Comment by IlseFerris** [comment]
Hennepin has this script disabled, so nothing on this end (obviously) :)

**Comment by theVKC** [comment]
Is there a chance the date functionality reading a date incorrectly? As in it's dividing 02 by 11 then by 2016?

**Comment by CDPotter** [comment]
Not sure... Here is where it's generated. 
![code](https://cloud.githubusercontent.com/assets/7841989/13182413/30760742-d6f7-11e5-874f-8678fc2dc156.png)

I couldn't be a leap year thing right? Since I've been having a hard time replicating it I'm thinking maybe it's just a fluke but I wanted to check with others.

**Comment by theVKC** [comment]
Ooooooh, that might be it.

**Comment by theVKC** [comment]
@CDPotter: let me know if you confirm the solution works. If that's the fix I'll call it critical and we'll push it through to release as well.

**Comment by CDPotter** [comment]
After a day I was unable to replicate this error in any fashion. Closing for now.
