### ISSUE TITLE
Question: Approved Progs, not grabbing results if version is from yesterday but approval today

### ISSUE THREAD

**Issue by CDPotter** [MN-Script-Team/DHS-MAXIS-Scripts#1898]
The script seems to go to ELIG SUMM and bases if it will continue on is date of the last version matches current date. Had a worker who ran things through background last night before closing and then approved those results from 2/18/16 on 2/19/16. 

Should we leave it this way to encourage people to not use old results?

**Comment by C-Love** [comment]
This would be an easy enough fix but personally I am hesitant. I don't know how often this would come up and am inclined to say we encourage people not to use old ELIG results. A BGTX takes less than a minute.

**Comment by theVKC** [comment]
I agree with @C-Love: better to encourage a BGTX. You never know what can change in a day... what if the income standards or HEST standards changed in that day? Better safe than sorry.
