### ISSUE TITLE
SIR instructions buttons error

### ISSUE THREAD

**Issue by IlseFerris** [MN-Script-Team/DHS-MAXIS-Scripts#1899]
When NOTICES is pressed, it goes to the BULK instructions
Link to notices: https://www.dhssir.cty.dhs.state.mn.us/MAXIS/blzn/Script%20Instructions%20Wiki/Notices%20scripts.aspx
When NOTES is pressed, nothing happens
Link to notes: https://www.dhssir.cty.dhs.state.mn.us/MAXIS/blzn/Script%20Instructions%20Wiki/Notes%20scripts.aspx

**Comment by CDPotter** [comment]
We should be able to fix this Monday if we revamp the menus (otherwise if we don't get to it a quick update should be able to resolve them in Master and Release)

**Comment by IlseFerris** [comment]
Agreed, we should try to do all the updates to the main menus on Monday
