### ISSUE TITLE
Bulk Case Transfer - worker number entry is only 3 digits

### ISSUE THREAD

**Issue by C-Love** [MN-Script-Team/DHS-MAXIS-Scripts#1904]
For the sake of consistency! Bulk case transfer currently asks for only the last 3 of the x-number. All scripts should request the worker numbers in the same format

**Comment by theVKC** [comment]
Agreed!

**Comment by theVKC** [comment]
Normally I wouldn't do this (technically we're breaking freeze here), but since @C-Love added this minor housekeeping enhancement with a bug fix, I will pull it through on v2016.02.
