### ISSUE TITLE
Over-payment case note script not going to the next page.

### ISSUE THREAD

**Issue by StormageddonDLOA** [MN-Script-Team/DHS-MAXIS-Scripts#1915]
Co-worker reported that the over-payment case note script she entered didn't advance to the next page and ended up overwriting on page 1.

**Comment by theVKC** [comment]
Is this duplicate-able? This happens on occasion because MAXIS hangs up and it isn't a "script issue" as much as a MAXIS issue...

**Comment by StormageddonDLOA** [comment]
I'll start testing and see what I can come up with.

**Comment by theVKC** [comment]
Generally speaking, we don't consider it a bug if we can't duplicate it... it might just be a MAXIS hiccup.

**Comment by StormageddonDLOA** [comment]
looks like it was just a hiccup as I can't duplicate it. I'll see if the worker can duplicate it.

**Comment by StormageddonDLOA** [comment]
just a hiccup - closing issue
