### ISSUE TITLE
Explanation of Income Budgeted: Add info about Self employment income

### ISSUE THREAD

**Issue by IlseFerris** [MN-Script-Team/DHS-MAXIS-Scripts#1917]
At mentor meeting this morning, self employment income was reviewed and clarified. Since it's an error prone area, maybe self employment should be added to the 'explanation of budgeted income' script. Or maybe it's better as it's own script. Thoughts?

**Comment by courtrightd** [comment]
My vote is for add it to the current income budgeted script, as It is more likely to become habit to note income using 1 script.  What about a dynamic dialog system, where the dialog that comes up is split in 3 sections: Busi, Jobs, Unea;  and which sections appear is dependent on which panels are found?  That way if there is a BUSI panel, it gets it’s own description box as well as checkboxes for method used, BUSI specific documentation, etc.

**Comment by theVKC** [comment]
I agree, add to the existing script.

**Comment by theVKC** [comment]
I'm thinking we should try and get this out this month. Does anyone want it? Or do we still want a debate?

**Comment by IlseFerris** [comment]
My vote is one script as well. @C-Love was working on adding overtime information to Explanation of Income Budgeted too, just as an FYI. Whoever takes this should coordinate with her.

**Comment by theVKC** [comment]
Well I think she's out today, but perhaps @C-Love wants to take this one?

**Comment by C-Love** [comment]
I was out (Wednesdays are my day off for anyone who is tracking my schedule). I will take it. I do like Self Employment

I will take a look at the Mentor Meeting notes on SIR.
