### ISSUE TITLE
HC renewal doesn't allow user to change footer month

### ISSUE THREAD

**Issue by IlseFerris** [MN-Script-Team/DHS-MAXIS-Scripts#1923]
Date is set to CM + 1, when the user should able to select the applicable month. I got this.

**Comment by theVKC** [comment]
But... doesn't the autofill only work in CM+1?

**Comment by CDPotter** [comment]
They can already change the footer month and it should affect which month the script autofills from. It just defaults to CM+1 since most renewals are for CM+1.

**Comment by IlseFerris** [comment]
Users can already change the footer month, but the issue is if the client is in the footer month of 0/16, and the script defaults to footer month 03/16, the information from 01/16 is still inputted into the dialog boxes/case note, and that is no good. 
In theory, if a user has updated a current renewal for CM + 1, the CM + 1 footer month/year will be read off of MAXIS. I stand by my update.

**Comment by CDPotter** [comment]
I see I wasn't understanding what the issue was. So if someone is in stat in 03/16 and the run the script and enter 02/16 it won't back out to self and switch to 02/16?

**Comment by IlseFerris** [comment]
Yes, that's correct. The CAF had the same issue, but I already updated the CAF. We might have to research this in a few other scripts as well.
