### ISSUE TITLE
HC Renewal: add "cost effective insurance availability" editbox

### ISSUE THREAD

**Issue by theVKC** [MN-Script-Team/DHS-MAXIS-Scripts#1925]
This came from a user in Ottertail County. @IlseFerris, any chance you can add this to your existing pull request?

**Comment by IlseFerris** [comment]
Since it was assigned to me, yes...LOL!

**Comment by theVKC** [comment]
I predicted you'd jump at the chance.

**Comment by IlseFerris** [comment]
You know me well :)

**Comment by IlseFerris** [comment]
Done and done
