### ISSUE TITLE
Bug, approved progs DWP pends SNAP approved, type mismatch

### ISSUE THREAD

**Issue by CDPotter** [MN-Script-Team/DHS-MAXIS-Scripts#1935]
Getting another type mismatch error on a case where SNAP was approved but DWP pends for 02/16.

I tried running it from self with 03/16 as the month, only SNAP selected, and the requested start month of 02/16. Not sure why it's trying to go to 00/11...  Looking into it but has anyone else hit this?

![2016-02-26 08_38_17-inbox - charles potter co anoka mn us - outlook](https://cloud.githubusercontent.com/assets/7841989/13355156/8e47e2ba-dc64-11e5-8965-6d19bdfdc8d2.png)

**Comment by theVKC** [comment]
Is there a chance footer_month is getting an extra zero? I.e. it's "001" instead of "01"?

**Comment by CDPotter** [comment]
ELIG coordinates might have moved....

**Comment by theVKC** [comment]
If this is the case it should be happening very frequently and should be easy to replicate.

**Comment by CDPotter** [comment]
scratch that. it couldn't get to elig DWP and got stuck on just elig where its 55 and 57. Still investigating...

**Comment by courtrightd** [comment]
I had that error reported, but didn’t get a case number so couldn’t track it.  Pretty sure it was a pending DWP case as well.

**Comment by C-Love** [comment]
@CDPotter  - I have a thought. I think it tries to navigate to elig DWP first and THEN change footer months - so if elig/dwp doesn't exist in the first month of the package it gets all wonky - so it could change to elig/sum first and then change the footer month and THEN go to the right elig program - I think that would fix it

**Comment by CDPotter** [comment]
I just added a new condition to each ELIG section read that the appropriate program must be selected to even try to look for results. It seemed to be working when I tested it on the offending case and an mfip case and a snap only case.

**Comment by theVKC** [comment]
I can't imagine a situation in which @CDPotter's solution doesn't work. @C-Love, are you OK with this solution? Does that sound like it'd do the job?

**Comment by CDPotter** [comment]
Only situation I can think of is if someone checked the program box but there weren't results causing a deailing (in which case that's user error)

**Comment by C-Love** [comment]
Sounds good @CDPotter - best of all worlds I think.

**Comment by theVKC** [comment]
Wonderful. Thanks team!
