### ISSUE TITLE
New Script- Interview Scheduled 

### ISSUE THREAD

**Issue by MelissaFox-Stearns** [MN-Script-Team/DHS-MAXIS-Scripts#1937]
this is something I've wanted to work on for a long time but I've been holding off for some reason. I would like to create a comprehensive Interview Scheduled script that includes CAF information, eDRS check, expedited screening, and the Appointment Letter memo.  Maybe even an action script to update Type and Prog? 

I started an idea list of things that I would like to see in the script. 

- [ ] Phone/office interview
- [ ] Phone #
- [x] CAF Date or ApplyMN date
- [x] New/Recert
- [x] ProgramsRequested/Recertifying
- [ ] Type/progupdate- Possible action script to do this for you?
- [ ] Hhld comp- This could be autofilled but I would like to see the worker compare it to the CAF
- [ ] Interview date
- [ ] Interview time
- [ ] Interviewer
- [ ] Interpreter scheduled- Y/N 
- [ ] Client notified (spec/memo, front desk, over the phone..Etc) 
- [ ] Expedited Screening- Implement part of or chainlink the Expedited Screening script 
- [ ] Residency/addr-This could be autofilled to have the worker compare to CAF
- [ ] Cafsigned- Check if it's signed and if the right people signed it. N/A if it is ApplyMN
- [ ] Arep- Also can be autofilled to compare with CAF
- [ ] All pages recvd?
- [ ] Edrs checked- Chainlink the eDRS Check script 
- [ ] Appointment letter- Implement part of the Appointment Letter Memo script 

Any thoughts?

**Comment by theVKC** [comment]
1. I love it.
2. Sounds like it fits into Project Bowie pretty well. Chainlinking FTW.
3. I'd like to hear from @ruthmaloney on any SNAP-specific pieces that we might be interested in incorporating.

**Comment by theVKC** [comment]
(Tagged as both ACTIONS and NOTES, but the actual scope may vary)

**Comment by theVKC** [comment]
@MelissaFox-Stearns, any chance you think this could be done by the June or even July release? I am trying to organize the issues and target dates for them.

**Comment by CDPotter** [comment]
Let's close this one for now, it looks like it's similar to the workflow process we are building currently. We can always reopen later if needed.
