### ISSUE TITLE
NOTES - Foster Care HCAPP (Add instructions and script info to dialog.)

### ISSUE THREAD

**Issue by LaLarson** [MN-Script-Team/DHS-MAXIS-Scripts#1939]
Similarly to the MTAF script I would like to enhance the dialog for this script to include a little more information/instruction as well as tighten up a few areas so that it displays better on small screens. If you could assign this to me, that would be great! I would like to work on this when I get to my new job at Olmsted!

**Comment by theVKC** [comment]
I like it! Go forth!

**Comment by LaLarson** [comment]
Working on this! Dialog box is updated/done, but I can't test the script because I don't have access to the training region yet! (Horns... Wahhh, wahhhhhhhhh.) I will test as soon possible! :)

**Comment by LaLarson** [comment]
Okay... Just kidding! I just got training region access, I tested it, and it looks good! Now, I'm having github lack of knowhow issues. :S Making progress though!
