### ISSUE TITLE
ELIG FS: "banging head against wall" not always working

### ISSUE THREAD

**Issue by theVKC** [MN-Script-Team/DHS-MAXIS-Scripts#194]
It isn't always getting to the approval. I think that if it catches at "just the right time", it'll bounce back to SELF and this tricks the script into thinking it approved. My solution would be to replace the attempt to get to ELIG/FS with an attempt to get to STAT/SUMM (using `MAXIS_background_check`). @CDPotter  or @RobertFewins-Kalb, I think this function belonged to one of you. Care to take it?

**Comment by theVKC** [comment]
Is this resolved @RobertFewins-Kalb?

**Comment by RobertFewins-Kalb** [comment]
I don't think I changed anything but it seems to be working just fine. Yes...?
