### ISSUE TITLE
BUG CAF not reading WREG months

### ISSUE THREAD

**Issue by CDPotter** [MN-Script-Team/DHS-MAXIS-Scripts#1941]
We changed the variable footer_month to MAXIS_footer_month in the CAF but the autofill functions all still use footer_month. Should we just change CAF back to footer_month? PRISM doesn't use footer_months so we don't need to differentiate.

**Comment by theVKC** [comment]
Yes for now. We can transition them later. Pick a standard and do a massive find-replace across all scripts.

**Comment by theVKC** [comment]
Do you want it?

**Comment by CDPotter** [comment]
On it. Release as well?

**Comment by theVKC** [comment]
Do you think it matches the critical criteria? It doesn't sound critical to me... can't workers manually fill them in?

**Comment by CDPotter** [comment]
They can, depends on if they notice. I'll pull to Master.

**Comment by RobertFewins-Kalb** [comment]
I have to ask why we're bothing with "MAXIS_footer_month." You can't tell PRISM what month to work in.

**Comment by theVKC** [comment]
I'm wanting to move toward MAXIS-specific variables having MAXIS_* at the front, for starters. Something that can be used in multiple scripts/functions should be globally defined and standardized, and this sets a good precedent for instances where there is a difference (i.e. MAXIS_case_number vs PRISM_case_number). If all MAXIS-specific cross-functional variables are predefined somewhere, it's clearer for debugging purposes and encourages clarity.

Also, other systems do use the "footer month" concept, beyond MAXIS. Just a bit of futureproofing in case the functions find reuse elsewhere.
