### ISSUE TITLE
HCAPP and HC Renewal script: new editbox for "Collateral Contact for Verification info".

### ISSUE THREAD

**Issue by Kolbwalt** [MN-Script-Team/DHS-MAXIS-Scripts#1945]
We recently had a Health Care Audit and in the audit we received an error due to not case noting our collateral contact information for verification.  It is in policy that we are to case note the collateral contact information for Health Care and it’s stated in the combined manual to enter a description in the case file regarding the collateral contact.  During our Whole Unit Meeting, it was asked if that could be added to the case note script somehow so that it triggers them to enter the collateral information.  What are your thoughts on this?

**Comment by CDPotter** [comment]
What do you mean by collateral contact information?

**Comment by Kolbwalt** [comment]
If there could be a “collateral Contact for verification” section added to case notes.  Example would be, I called the employer and spoke to Terri and verified that they make $12 per and will be working 20 hours per week.  We wouldn’t have any paperwork in the file to support this, just the phone call that was made.  If it isn’t case noted how to do we know where we got this information.  (This holds true for later down the road or if someone else is looking or working on the case.)

Staff are forgetting to case note their “collateral contact” that they made to verify the information.  I believe in the panel it’s a code “3” for some of the panels.  Hope this helps clarify things and if you have additional questions, please let me know.

Thanks!
Karrie

**Comment by CDPotter** [comment]
Ah ok, that makes sense. I've always just used/instructed people to use NOTES - Client Contact anytime contacting someone outside of the agency.

**Comment by theVKC** [comment]
I like it in the case note because it reminds people to do it. I'm pretty strongly in favor. Anyone want it?

**Comment by CDPotter** [comment]
@theVKC are you seeing this as a brand new script? or an enhancement to NOTES - client contact?

**Comment by theVKC** [comment]
Neither. Not on NOTES - CLIENT CONTACT at all. I think we want it on the HCAPP and HC Renewal script as a new editbox called "Collateral Contact for Verification".

Any takers?

**Comment by theVKC** [comment]
@Kolbwalt: @MelissaFox-Stearns is going to be contacting you for more info on this. Yay!

**Comment by Kolbwalt** [comment]
Awesome!  ☺

**Comment by theVKC** [comment]
@MelissaFox-Stearns, can I get an update on this issue? It's been delayed a few times. I'm hoping to either push it out this month or close it (trying to reduce issues on the list).

**Comment by theVKC** [comment]
Closing due to lack of time to get this one done. Will revisit if interest from any scriptwriters (and time) permits.
