### ISSUE TITLE
Utilities script idea: POLI/TEMP list 

### ISSUE THREAD

**Issue by IlseFerris** [MN-Script-Team/DHS-MAXIS-Scripts#1952]
Hennepin county keeps a list of POLI/TEMP topics on an excel spreadsheet, and has made this available to users in the HSR manual. This has been very valuable since it can be searched easily. I have this one in the hopper already, and have been using it locally. 
Thoughts on it's usefulness to other counties?

**Comment by theVKC** [comment]
How would it be worked into a script?

**Comment by theVKC** [comment]
Also, I'm only assigning management of the question to you. :P

**Comment by IlseFerris** [comment]
Thanks for the clarification of the issue assignment ;P

It just creates a list of the POLI TEMP topics, reference # and date updated. Users can search the document for keywords, topic title, or most updated. 
Run time is 13 seconds, so it can save users time fooling around looking for what they need in POLI/TEMP.

![poli temp](https://cloud.githubusercontent.com/assets/10836829/13470533/396e2486-e072-11e5-82c2-e3f34733feaf.PNG)

**Comment by theVKC** [comment]
Oh, so it's a script that generates this Excel sheet? Or just links to it? Does it look in POLI/TEMP or does it just bring up a link?

**Comment by IlseFerris** [comment]
Yes, it generates the list in Excel from POLI/TEMP. No link, just grabbing what is currently in POLI/TEMP.

**Comment by theVKC** [comment]
Love it. I'll remove "question". Can't wait to see it.

**Comment by Y-Lor-Y** [comment]
Also this is something that is very helpful especially for SNAP.

Known Problems Affecting SNAP Elig.  TE02.06.02
