### ISSUE TITLE
Interim Assistance Agreement script idea

### ISSUE THREAD

**Issue by IlseFerris** [MN-Script-Team/DHS-MAXIS-Scripts#1954]
Request from Hennepin County: We are wondering if there is a GA/GRH IAA Blue Zone case note.  One that can take the worker to the following steps
1.	Update the PBEN panel
2.	Entering a case note
3.	Dail writ the case if the IAA is not returned in 30 days

This should also include an option to case note if it's for a new application or renewal. Thoughts?

**Comment by theVKC** [comment]
Sounds like an ACTIONS script if it's updating PBEN each time. Any thoughts on that?

**Comment by IlseFerris** [comment]
Agreed, I think ACTION is appropriate

**Comment by theVKC** [comment]
Anyone want it?

**Comment by IlseFerris** [comment]
I can take it unless someone else is interested

**Comment by IlseFerris** [comment]
Can you change this to May? With the IAA clarifications at mentor meeting we still need to talk this one out. Thanks!

**Comment by theVKC** [comment]
@IlseFerris, where are we at with this? I expected to see it by now.

**Comment by IlseFerris** [comment]
Let's move it to June. I've started on it, but it keeps getting bumped for other priorities.

**Comment by theVKC** [comment]
Let me know if you want me to close it entirely and we can start it up again if it becomes important.

**Comment by IlseFerris** [comment]
Let's close this for now. The priority just keeps getting pushed back. I will still work on it, and test it locally as time permits.
