### ISSUE TITLE
Change reported enhancement: reminder to add baby born to mom MHC plan

### ISSUE THREAD

**Issue by IlseFerris** [MN-Script-Team/DHS-MAXIS-Scripts#1955]
Request from worker to have a checkbox/line in case note that the newborn's managed health care plan was updated to the same as mom's carrier. 

 Could be a good reminder/nudge in the right direction for workers.

**Comment by theVKC** [comment]
Seems easy. Any takers?

**Comment by StormageddonDLOA** [comment]
I'll take it.
