### ISSUE TITLE
Proof of relationship enhancement: handling for multiple HH members

### ISSUE THREAD

**Issue by IlseFerris** [MN-Script-Team/DHS-MAXIS-Scripts#1958]
Request from Hennepin County user:
Is there a was the relationship proof script can look like this when there are multiple household members instead of it only being able to log one child at a time … 

I think it's a good idea.

**Comment by theVKC** [comment]
Not sure at all what this is doing. You don't have much info in this comment and a misspelling in the title, @IlseFerris. :P

**Comment by IlseFerris** [comment]
The current script only allows one HH member to be case noted at a time. Worker has requested that the script be able to case note proof of relationship on multiple household members in a single case note.

And apologies for the sloppy issue verbiage #TooManyBallsInTheAir

**Comment by theVKC** [comment]
Much better. Any takers?

**Comment by C-Love** [comment]
I will take this - for April release
