### ISSUE TITLE
Call for input: new script to enter spenddown info into MMIS

### ISSUE THREAD

**Issue by IlseFerris** [MN-Script-Team/DHS-MAXIS-Scripts#1959]
Request from Hennepin county user:
Is there a way we could create a spenddown script, where it would take the excess income portion off of BSUM in Maxis and then update RSPD in MMIS? 

I'm hesitant about this one since:
1. MMIS is a real challenge to input into manually, let alone trying to code in.
2. SD vs. recipient amounts can be vastly different from each other. 
3. MMIS has about a thousand inhibiting errors.
4. LTC and waiver recipients have very complex cases, and many additional steps beyond updating RELG, RSPD and RPPH.

**Comment by theVKC** [comment]
I think it might be beyond scope without a formal MMIS scriptwriter. That's my take on it. If a county wants to champion it I could see it, but I would worry it'd be super error prone.

Any other thoughts, team?

**Comment by theVKC** [comment]
Also, these "call for input" things might be better suited for Slack. :P

**Comment by CDPotter** [comment]
I'd err on the side of it's too error prone to program.

**Comment by IlseFerris** [comment]
I agree, too much to support at this time. I'll close the issue. Thanks team!
