### ISSUE TITLE
Add "sent 5181 to case manager" checkbox on LTC scripts

### ISSUE THREAD

**Issue by IlseFerris** [MN-Script-Team/DHS-MAXIS-Scripts#1962]
This enhancement came from Stearns Count.
Request to have a check box/ case note line for "sent 5181 to case manager"

Scripts included in this would be:
NOTES - LTC - 1503
NOTES - LTC - ASSET ASSESSMENT
NOTES - LTC - MA APPROVAL
NOTES - LTC - RENEWAL

**Comment by theVKC** [comment]
Anyone want it?

**Comment by GayS** [comment]
I can take issue #1962  to work on at the 3/14 hack a thon.

**Comment by theVKC** [comment]
Woohoo! Thanks @GayS!

**Comment by IlseFerris** [comment]
Looking at my notes it looks like Christine wanted this added to the NOTES - CLOSED PROGRAMS script and NOTES - INTAKE APPROVAL (although it may already be on that script)

**Comment by theVKC** [comment]
For closed programs, it would make sense to have it in a groupbox labeled "For LTC cases", right?

**Comment by GayS** [comment]
got it -
