### ISSUE TITLE
Enhancement: REVW/MONT Closure reapply verbiage. 

### ISSUE THREAD

**Issue by CDPotter** [MN-Script-Team/DHS-MAXIS-Scripts#1968]
We were wondering if we could change the verbiage from 

"* Client needs to reapply for HC after (intake date)" 

to

"Client needs to turn in new application for HC after (intake date)"

We've been getting some concerns about the verbiage. For example on a HC renewal that closed the client can turn in a HC renewal form after closure and the case would be reapplied in the renewal month rather than reinstated. Workers are getting confused on if they should be reapplying or reinstated based on the word reapply. 

Thoughts?

**Comment by CDPotter** [comment]
NOTES: Closed progs has this "(intake date) after which a new HCAPP is required."

**Comment by theVKC** [comment]
Works for me. Do you want it, @CDPotter?

**Comment by CDPotter** [comment]
Sure assign it to me. I probably can't get to it today (interview day) but I will knock it out when I've got a chance.
