### ISSUE TITLE
BUG: DAIL - SEND NOMI not entering dates right

### ISSUE THREAD

**Issue by CDPotter** [MN-Script-Team/DHS-MAXIS-Scripts#1970]
I was running the dail scrubber on my revs scrubber messages (granted I don't remember if we used a local version of revs scrubber) and the client didn't turn in CAF so I selected don't sent nomi option. It entered this as the case note.

![2016-03-09 10_03_20-s1 - anoka desktop - anoka scripted desktop - bluezone mainframe display](https://cloud.githubusercontent.com/assets/7841989/13641484/2fff9d0a-e5de-11e5-8975-274dc08a8ba2.png)

Here is the dail:

![dail](https://cloud.githubusercontent.com/assets/7841989/13641514/4cbfd5e0-e5de-11e5-8493-94816d93cd14.png)

**Comment by theVKC** [comment]
Because this script isn't live yet, I am closing this issue. Please report it on issue #710.

**Comment by theVKC** [comment]
Wait! I take it back, this is for the DAIL portion!

**Comment by theVKC** [comment]
@CDPotter or @IlseFerris: either of you want to fix it?

**Comment by CDPotter** [comment]
Taking the moment of the missed interview to look at code it looks like the dail message is still the same in the REVS scrubber as what I got. So It looks like the DAIL scrubber portion is just truncating things oddly.

I could probably look at it tomorrow, today is a wash for scripting. @IlseFerris if you can knock it out today go for it.

**Comment by theVKC** [comment]
I'm guessing the TIKL from REVS Scrubber should have a standard MM/DD/YYYY format. This one didn't, so it broke the SEND NOMI function? That's my hunch. If we standardize the date length at MM/DD/YYYY and not M/D/YYYY I bet it'll work.

**Comment by IlseFerris** [comment]
I'm tied up for the next 2 days straight. If you can tackle this one @CDPotter  that would be amazing!

**Comment by CDPotter** [comment]
I'll look at it tomorrow then.

**Comment by theVKC** [comment]
In any case, I think the REVS TIKL should always follow a standard MM/DD/YYYY format. I'll add that to the Mic Drop to-do.
