### ISSUE TITLE
Enhancement: notes acronym expansion

### ISSUE THREAD

**Issue by CDPotter** [MN-Script-Team/DHS-MAXIS-Scripts#1972]
I noticed that on NOTES there were a few acronyms people may not know. I was thinking I could update the descriptions to include the full name since in many case it says things like Template for the CSR and has plenty of room.  

Examples I found were CSR MTAF OHP and ICAMA

Thoughts or suggestions for others?

**Comment by theVKC** [comment]
I like the idea just fine. Less acronyms reduces confusion, generally. :)

Only concern about the NOTES menu structure (at this point) is that the function I created enters everything in one line. Obviously we have troubles with word-wrapping those text fields in the function as-written.

Perhaps this should also dynamically reconfigure the text fields to a new size if x-many characters are present in the description?

**Comment by CDPotter** [comment]
Well the ones I listed have plenty of room to expand but that is definitely something we could look at. Though it might make things unnecessarily complicated?

**Comment by theVKC** [comment]
Maybe for this issue we skip it, but I want to try and add this feature to the function.

**Comment by CDPotter** [comment]
Sounds good. Definitely something to keep in the back of our minds!
