### ISSUE TITLE
Update Check_for_password function in scripts

### ISSUE THREAD

**Issue by MelissaFox-Stearns** [MN-Script-Team/DHS-MAXIS-Scripts#1977]
Update all or most scripts to add the check_for_password function since more counties are moving to Bluezone version 6. 
The following is the prioritized list: 

- [ ] ACTIONS - ABAWD Screening Tool
- [ ] ACTIONS - New Job Reported
- [ ] ACTIONS - Paystubs Received
- [ ] NOTES - Approved Programs
- [ ] NOTES - Change Report Form Received
- [ ] NOTES - Change Reported
- [ ] NOTES - Client Contact
- [ ] NOTES - Closed Programs
- [ ] NOTES - Combined AR
- [ ] NOTES - CSR
- [ ] NOTES - Denied Programs
- [ ] NOTES - Documents Received
- [ ] NOTES - Emergency
- [ ] NOTES - Expedited Determination
- [ ] NOTES - Explanation of Income Budgeted
- [ ] NOTES - HC Renewal
- [ ] NOTES - HCAPP
- [ ] NOTES - HRF
- [ ] NOTES - Interview Completed
- [ ] NOTES - MFIP to SNAP Transition
- [ ] NOTES - MTAF
- [ ] NOTES - Overpayment
- [ ] NOTES - Verifications needed
- [ ] NOTICES - Appointment letter

**Comment by theVKC** [comment]
We need to identify scripts that are affected, and seek out a BlueZone customization solution if possible. @C-Love: I hear you have a script list?
