### ISSUE TITLE
Remove CS disregard fiater from existence

### ISSUE THREAD

**Issue by IlseFerris** [MN-Script-Team/DHS-MAXIS-Scripts#1978]
MAXIS has now been updated to handle this. It needs to be removed since running it over the cases since 10/15 will cause the disregard to be duplicated.

**Comment by theVKC** [comment]
This is critical as it's a major policy issue if the script is duplicating a benefit.

**Comment by CDPotter** [comment]
We also gotta remove the WCOM(s) for it. I know approved progs has it in there.

**Comment by theVKC** [comment]
I think the WCOMs would not be considered critical (avoiding merge conflicts). Separate issue might be helpful just to distinguish.

**Comment by CDPotter** [comment]
Sounds good, I can tackle that one as I have a chance at the moment.

**Comment by C-Love** [comment]
@theVKC  this script is still available in release.
