### ISSUE TITLE
Update ACTIONS main menu to have the new look/feel

### ISSUE THREAD

**Issue by theVKC** [MN-Script-Team/DHS-MAXIS-Scripts#1998]
This will give me a chance to test my function, so I'll take it.

**Comment by theVKC** [comment]
Opening this up. Any takers?

**Comment by CDPotter** [comment]
Sure I can do this one.

**Comment by CDPotter** [comment]
Question do we want to lump utilities as it's own sub-menu or keep it separate?

**Comment by theVKC** [comment]
Utilities is just a redirect. Agencies using the current supported Power Pad have a utilities button.

**Comment by CDPotter** [comment]
Got it, last question should I alpha split in anticipation of getting more scripts or leave it mailable to alpha split later?

**Comment by theVKC** [comment]
Don't alpha split. My advanced final function should do that for us.
