### ISSUE TITLE
Project Gorbachev: break up the CAF script into smaller chunks

### ISSUE THREAD

**Issue by theVKC** [MN-Script-Team/DHS-MAXIS-Scripts#1999]
The smaller chunks should be able to run other scripts as needed. For example, pulling up the NOTICES menu for sending some notices. This will require updates to script_end_procedure and run_from_github functions.

**Comment by theVKC** [comment]
Targeting this major piece for the May release.

**Comment by C-Love** [comment]
To better address case noting information about income, we should enhance Explanation of Income Budgeted. Basically, the dialog for Explanation of Income Budgeted should loop for every income panel that exists on a case. We need to mandate workers to add comments about income (including date range and verifs used). Currently the CAF script does not require the 'Notes on Income' field to be completed. Additionally, we could better document notes on income if Explanation of Income Budgeted if the dialog ran once for each income panel.

**Comment by ruthmaloney** [comment]
I love this one!!! ☺

Ruth Maloney

**Comment by theVKC** [comment]
We're going to tear down this wall April 11-12. :)

**Comment by CDPotter** [comment]
Will reopen once workflows are cracked.
