### ISSUE TITLE
Project Bowie: turn "changes reported" into a dashboard that can run other change-reported scripts

### ISSUE THREAD

**Issue by theVKC** [MN-Script-Team/DHS-MAXIS-Scripts#2000]
It's time.
- [x] Create dialog which displays "change reporting" scripts (@theVKC)
- [x] Make dialog have the ability to select multiple scripts to run (i.e. a workflow) (@theVKC)
- [x] Dialog should allow a script to run multiple times, and that functionality should actually factually work (@theVKC)
- [x] Dialog should link back to SIR instructions for each script (@theVKC)
- [x] All change reported scripts should be updated to reflect current understanding of dialog declaration and definitions (@C-Love)
- [ ] Dialog should be dynamic based on scripts associated with this workflow subcategory (@theVKC)
- [ ] Script should incorporate a "favorites view" which adds the ability to create custom workflows (@RobertFewins-Kalb)
- [ ] Script should incorporate a "discovery mode" in which end users can select criteria that may apply, which autoselects the appropriate scripts in workflow (@theVKC)

**Comment by theVKC** [comment]
Targeting this for the May release.

**Comment by RobertFewins-Kalb** [comment]
Enhancement: Add capability for users/agencies to build custom (_favorite_) workflows.

@CDPotter and I have built the ability for users to select specific scripts to run based on selection of scripts from all scripts list and then saving that selection to txt file on specified network location. I'm thinking we could handle that along with the dynamicization of the workflow dialog to handle the custom lists.

**Comment by RobertFewins-Kalb** [comment]
Then the user could access their custom workflows like this...

![image](https://cloud.githubusercontent.com/assets/7842016/14921666/ee3c5d52-0df8-11e6-948d-8118b02e0268.png)

**Comment by theVKC** [comment]
Boom. Let's get it done.

**Comment by theVKC** [comment]
Well folks, I wanted to target this for the May release but now I fear we won't have enough time to test this in the master branch. Considering my script-wide updates needed (see all yesterday's pull requests), I'm making the executive decision to switch this to the June release. This way we can focus on cleaning up any errors caused by yesterday's and today's work.

**Comment by RobertFewins-Kalb** [comment]
Update: The workflow view has been expanded to accommodate a new button group. At the top is a link to the Create/Update Workflows script (thinking that would be a Utilities script) that borrows heavily from Anoka County's Favorites Menu.

![image](https://cloud.githubusercontent.com/assets/7842016/15937056/0c683af8-2e33-11e6-8831-e9d68aa66a18.png)

When you click to Update/Create WF, you are redirected to this...

![image](https://cloud.githubusercontent.com/assets/7842016/15937079/21edab88-2e33-11e6-8ba8-49f83a3748d4.png)

...where existing workflows can be loaded and modified. I'm wondering if it's worth adding a "Workflow Description" field to provide more information. That can be added to the workflow builder gobbins. If you press "Build New WF", you get a rudimentary dialog with a list of all scripts represented by checkboxes. You can build a custom workflow from here, selecting the scripts involved. The buildy script then creates a new txt file...

![image](https://cloud.githubusercontent.com/assets/7842016/15937190/7bd82a92-2e33-11e6-826d-23fc7a242845.png)

...which the workflow main menu would read when loading the workflow.


Back to the main menu, when you select different workflows, the script loops, loads the txt file, and builds the dialog.
![image](https://cloud.githubusercontent.com/assets/7842016/15937250/aa39b2e8-2e33-11e6-85af-5a64c0c65352.png)

![image](https://cloud.githubusercontent.com/assets/7842016/15937271/bd4cd572-2e33-11e6-93a0-a00db07944f7.png)



We need a way to save and load the text files. I'm thinking the most basic thing to do is use the `default_directory` location in GlobVar until something is added to the installer...?

![image](https://cloud.githubusercontent.com/assets/7842016/15937343/1a991a06-2e34-11e6-8405-b37bcd8d1803.png)

"Borrowing" from @lpshanley 's Agency Custom solution, all we need to do is tell the scripts the value for `dir` and the rest falls into place.

**Comment by theVKC** [comment]
I think `default_directory` should be OK for now. This looks really really really good @RobertFewins-Kalb!

**Comment by RobertFewins-Kalb** [comment]
What branch should I pull into?

**Comment by theVKC** [comment]
The VKC-Gorbachev branch (we had started doing Gorbachev then pivoted to Bowie).

**Comment by RobertFewins-Kalb** [comment]
I'm thinking that before I can work the agency custom workflows option to the dialog, it has to be a dynamic dialog. The Changes Reported workflow script has the scripts in the workflow hard-coded, which isn't going to work with what I have been working with...

![image](https://cloud.githubusercontent.com/assets/7842016/16088419/9e273ac6-32ec-11e6-947a-8659afd3ff30.png)

I can pull in the "Create Custom Workflows" script to that branch... as a utility script? ...but I am thinking that the agency custom workflows option will need to wait until after it is made dynamic (including making the URL for the help button a property in the script class).

Thoughts?

**Comment by theVKC** [comment]
I am hoping to make it dynamic today or tomorrow, @RobertFewins-Kalb. Admittedly that doesn't give us much time though. It's dependent on some other issues with FuncLib getting fixed first.

If I get it dynamicized ASAP (this morning or early afternoon perhaps), think you can work your logic in? Otherwise we could certainly make it a utilities script for now.

**Comment by RobertFewins-Kalb** [comment]
That doesn't give us much time, indeed. What's the deadline for my pull request -- EOD Friday?

Related: If individual workflows are saved as individual files that the script then calls up, I could get the logic put in rather quickly. I built the dashboard (see above) to call up and jump between individual workflow files. If that's the case, then I could (easily) give users the ability to jump between DHS provided workflows (blow it out a bit wider) and agency custom workflows...I'll even throw in the rust-proofing at 50% off.

**Comment by theVKC** [comment]
EOD Friday, or alternatively we delay by another month. I'm open to that to allow more time for development and testing. I've been working on dynamicism in existing main menus and reducing non-instruction errors by locking in instructions processes with script files.

If end of day Friday is too soon, I think I'll delay it another month. No harm there, I'd rather deliver a dynamite project with lots of instructions.

**Comment by RobertFewins-Kalb** [comment]
Sounds grrrrrrrrrrrreat.

**Comment by RobertFewins-Kalb** [comment]
I will also wait on UTILITIES - CUSTOM WORKFLOW BUILDER until after I see how your dynamicalizationing (C) goes down. I'm sure I will need to add a field for `help_url` at the very least.

**Comment by theVKC** [comment]
You'll see it, it's pretty slick. It assumes the file name for the wiki page is identical to the script name and then dumps a URL based on that.

**Comment by C-Love** [comment]
@theVKC seems like this will be resolved with the framework for the new python scripts and will be resolved by nature of Hydra - would you say that is correct?

**Comment by theVKC** [comment]
Agreed.

**Comment by C-Love** [comment]
Closing since this will be handled with Hydra
