### ISSUE TITLE
Bug with BrowseForFile

### ISSUE THREAD

**Issue by theVKC** [MN-Script-Team/DHS-MAXIS-Scripts#2008]
So I discovered an issue with BrowseForFile as indicated in the EOMC script and elsewhere.

If your computer defines the default folder in a space that isn't "Computer" (i.e. "My Computer", "HS#######", etc.)

I discovered (via Googling) a new method which seems to call up HTML (and by extension, Javascript) which loads the a proper save/load dialog and exports it as a variable. Confirmed to be working at DHS.

Will be updating Krabappel with this function, after which we can evaluate the EOMC script. <del>@CDPotter  and @RobertFewins-Kalb: since you built BrowseForFile, any chance you can give me a list of scripts that use that function? </del>

#### Update 04/06/2016
These are the identified scripts:

- [x] CASE NOTE FROM LIST
- [x] MEMO FROM LIST
- [x] TIKL FROM LIST
- [x] UPDATE EOMC LIST

**Comment by CDPotter** [comment]
If my memory is correct BULK MEMO/TIKL/CASE NOTE FROM LIST are the only 3 that use it currently that I added. So those 3 and the EOMC one.

**Comment by RobertFewins-Kalb** [comment]
That sounds about right, unless any other script writer snuck the function into another script that we don't know about.

**Comment by theVKC** [comment]
This new one is slick-as-all-get-out, folks.

**Comment by theVKC** [comment]
Here it is with some comments:

```vba
Function File_Selection_System_Dialog(file_selected)
	'Creates a Windows Script Host object
	Set wShell=CreateObject("WScript.Shell")

	'Creates an object which executes the "select a file" dialog, using a Microsoft HTML application (MSHTA.exe), and some handy-dandy HTML.
	Set oExec=wShell.Exec("mshta.exe ""about:<input type=file id=FILE><script>FILE.click();new ActiveXObject('Scripting.FileSystemObject').GetStandardStream(1).WriteLine(FILE.value);close();resizeTo(0,0);</script>""")

	'Creates the file_selected variable from the exit
	file_selected = oExec.StdOut.ReadLine
End function
```

**Comment by RobertFewins-Kalb** [comment]
Hell yeah! That is slick.

**Comment by theVKC** [comment]
Only thing I want to add to this before making it official is a method to pass a file-type parameter. But, I want it to be optional. Need to do some research into how to do that both with VBScript and with the HTML app functionality.

**Comment by theVKC** [comment]
Can we get folks to test Krabappel now that it's in master, and see how this holds up? If it works well I'll throw it into FuncLib and we can update the other scripts.

**Comment by theVKC** [comment]
("this" being the new function that I added in Krabappel)

**Comment by CDPotter** [comment]
I was able to make 3 Beasleys and drop em into Robert's X#. Browse for the file on my desktop.

**Comment by theVKC** [comment]
Fantastic. It'd be great to hear from folks outside of BlueZone 5.1c2. So Stearns, St. Louis, Hennepin, and Ramsey folks...

**Comment by theVKC** [comment]
Moved this to April, since I haven't heard back from any other agencies using non 5.1c2 BlueZone. We'll test into next month and then tackle this for the next release.

**Comment by C-Love** [comment]
I have been using this new functionality in Training Case Creator and also in the Banked Months reporting script that we are working on. Seems fine with V6.

**Comment by theVKC** [comment]
Gorgeous. I'll try and get this updated next week.

**Comment by theVKC** [comment]
These are the identified scripts:

- [ ] CASE NOTE FROM LIST
- [ ] MEMO FROM LIST
- [ ] TIKL FROM LIST
- [ ] UPDATE EOMC LIST
