### ISSUE TITLE
Enhancement -- Add an additional check_for_MAXIS in Paystubs Received

### ISSUE THREAD

**Issue by RobertFewins-Kalb** [MN-Script-Team/DHS-MAXIS-Scripts#2009]
A worker reported they took too long to enter pay information in the Paystubs received script and when they hit OK, MAXIS had timed out. In the resulting chaos, they were suspended from MAXIS. 

Looking through the code, I can see where the check_for_MAXIS should go. 

I got this.

**Comment by RobertFewins-Kalb** [comment]
I'll put this only in MASTER unless you want me to put it in release as well, @theVKC.

**Comment by theVKC** [comment]
I'm closing this as a wontfix, @RobertFewins-Kalb. See #1977. There are v6 issues with check_for_MAXIS and as agencies are upgrading their BlueZone more are seeing this. The way we should resolve this issue should be with that new function.

**Comment by CDPotter** [comment]
What new function?

**Comment by theVKC** [comment]
check_for_password
