### ISSUE TITLE
NOTES- Changes Reported/ HH Comp- Doesn't case note Actions Taken

### ISSUE THREAD

**Issue by MelissaFox-Stearns** [MN-Script-Team/DHS-MAXIS-Scripts#2011]
Just found out that the Changes Reported script under HH Comp Change does not case note the Actions Taken part of the dialog.

**Comment by theVKC** [comment]
Want to fix it, @MelissaFox-Stearns?

**Comment by StormageddonDLOA** [comment]
I can take it.
