### ISSUE TITLE
NOTICES - MFIP Orientation not entering user entered addresses into memo

### ISSUE THREAD

**Issue by courtrightd** [MN-Script-Team/DHS-MAXIS-Scripts#2012]
If the user uses the dropdown, the address updates, but if they then change it, the original address is printed on the memo.  If they enter an address without using the dropdown, nothing prints on the memo.

**Comment by theVKC** [comment]
Hmmm. Issue with the variables, perhaps? Want to take it?

**Comment by courtrightd** [comment]
Yep, I’ll take it.

**Comment by theVKC** [comment]
Excellent. Think it can be done by next Friday? Ideally sooner for testing?

**Comment by courtrightd** [comment]
I’ll have it done this morning.

**Comment by theVKC** [comment]
Booyah!
