### ISSUE TITLE
BULK - REPT REVS not moving past SELF menu

### ISSUE THREAD

**Issue by IlseFerris** [MN-Script-Team/DHS-MAXIS-Scripts#2014]
![image](https://cloud.githubusercontent.com/assets/10836829/13814746/77d694ea-eb55-11e5-8a31-3f912ed5c07f.png)

REPT REVS not moving past SELF screen for current month +2 is marked yes and no. This is occurring in the release branch. Anyone else having issues?

**Comment by theVKC** [comment]
What script is REPT REVS? That's a MAXIS screen.

**Comment by IlseFerris** [comment]
It's the BULK REPT REVS script. It won't navigate into REPT/REVS, it's just getting stuck on the the SELF meun. I can look at this later, but wanted to know if others are having the same issue.

**Comment by theVKC** [comment]
Is this happening with multiple users, x1 numbers, etc? Also, if it hasn't been confirmed with multiple x1s and users, it shouldn't be on GitHub just yet.

**Comment by CDPotter** [comment]
I can poke at it, what settings were you using? (progs, users, month, etc)

**Comment by theVKC** [comment]
Did someone insert the footer month the wrong way? Perhaps an extra slash? This seems really weird.

**Comment by IlseFerris** [comment]
It is happening to multiple workers here in release. Master appears to have same code so I'd imagine it's an issue there too. Thanks @CDPotter for taking a look. I'm out in the community today presenting SNAP.

**Comment by CDPotter** [comment]
Do you happen to know if they were checking "Check here to read info from case notes to help locate cases with STAT/REVW errors" and/or "check here to have the script read info from SNAP autoclose notices"?

I was able to break things by going into CM+2 and checking these boxes. (MASTER BRANCH) I've gotta look what that first checkbox even does but the 2nd one shouldn't be an option if you're in CM+2

**Comment by theVKC** [comment]
If it's based on a checkbox, I don't know if it's critical. I'm open to discussing that, though.

**Comment by CDPotter** [comment]
What it appears to me is:

1: users are picking they want to check CM+2 05/16
2: they are asking the script to check for rec'd/approved renewals. Impossible for CM+2, I can't think of any reason why a renewal would be received/approved for 05/16 in 03/16.
3: they are asking the script to check for SNAP autoclose notices. Also impossible for CM+2. 

So we can either chalk it up to people using the script incorrectly, or I can add logic for if CM+2=True & checkboxes are checked error message appears.

**Comment by IlseFerris** [comment]
The users I had test selected current month + 2 yes, and selected HC, CASH and SNAP programs to add to Excel list. No other options.

**Comment by CDPotter** [comment]
So running it here with those parameters I don't have any issues. 

The script goes back to self in between each user, then clears footer_month and footer_year variables, then writes left two of date and right two of date. So it must be grabbing 3/ instead of 03

@IlseFerris is going to get back to me on how her date constant displays but if other agencies wouldn't mind making a quick test script and msgboxing date to see if it displays as 3/16/2016 or 03/16/2016 we could see if this is something we need to be concerned about for other scripts.

**Comment by courtrightd** [comment]
I’m getting the same issue with the script when just checking SNAP and saying NO for cm+2.  Date display is 3/16/2016 NOT 03.

**Comment by CDPotter** [comment]
Perfect,from the aspect of I know how to correct it! Fix incoming.

**Comment by theVKC** [comment]
I've decided not to consider this critical, in an effort to prevent merge conflicts. As this is a list script, which doesn't directly impact cases, I think we can stretch it until the formal release.
