### ISSUE TITLE
NOTES- Significant Change- Denial reason update

### ISSUE THREAD

**Issue by MelissaFox-Stearns** [MN-Script-Team/DHS-MAXIS-Scripts#2035]
One of the denial reasons for Significant change was "income didn't decrease by 50%". Well, in October they changed the policy to decrease $65 and 50%. 
I want to change to update the denial reason to be something like.... "Income didn't decrease enough"
so we don't have to update it every time they make a change to policy. :)

**Comment by theVKC** [comment]
@MelissaFox-Stearns: what do you think? Is this a "bug" in the sense that the policy could be considered _wrong_? Or is it more of an enhancement? I ask because this is script freeze.
