### ISSUE TITLE
Function Autofill_editbox_from_MAXIS.... ACCT Panel limit

### ISSUE THREAD

**Issue by MelissaFox-Stearns** [MN-Script-Team/DHS-MAXIS-Scripts#2037]
Gay and I discovered that there is a error when the script is gathering data from the panels to enter in the edit boxes if there are over 9 ACCT Panels. 
It appears that the Function is reading the number of panels and looping once it hits 10 panels because it is only reading 1 digit (which happens to be 0) and creates an endless loop. :)

 Elseif panel_read_from = "ACCT" then 
	For each HH_member in HH_member_array
      EMWriteScreen HH_member, 20, 76
      EMWriteScreen "01", 20, 79
      transmit
      EMReadScreen ACCT_total, 2, 2, 78
	  ACCT_total = trim(ACCT_total)   'deleting space if one digit. 
      If ACCT_total <> 0 then
        variable_written_to = variable_written_to & "Member " & HH_member & "- "
        Do
          call add_ACCT_to_variable(variable_written_to)
          EMReadScreen ACCT_panel_current, 1, 2, **73**
          **If cint(ACCT_panel_current) < cint(ACCT_total) then transmit
        Loop until cint(ACCT_panel_current) = cint(ACCT_total)**
      End if
    Next

**Comment by theVKC** [comment]
@MelissaFox-Stearns: First, if this is related to a function, it belongs in the FuncLib repo. :)
Second, @CDPotter just fixed this, I think. Or am I wrong? Charles, can you elaborate?

**Comment by CDPotter** [comment]
This sounds like the issue I fixed. Testing it on my 96 account case it does seem to have gotten stuck for some reason...Looks like I missed adjusting a few numbers. This should only affect cases with more than 9. I'll submit a fix.

**Comment by theVKC** [comment]
@CDPotter: I'm closing this issue. Just set this up with the original issue on FuncLib, which I'll reopen.

**Comment by CDPotter** [comment]
Side note, I tested it with the CAF just now after the fix and it worked.fake case 226545 if anyone wants to see a 96 account(max) CAF case note. It really shows that the overflow function for case notes works!
