### ISSUE TITLE
Memos - Appointment Letter Script - Add Interview Location.

### ISSUE THREAD

**Issue by jasont35** [MN-Script-Team/DHS-MAXIS-Scripts#2038]
Worker requested to have "In-Home" added as an Interview location as there are situations to where a worker may go to the clients home for the interview.

**Comment by theVKC** [comment]
I like the idea. We're on an enhancement freeze until March 28, so it can't be pulled in until after that time. @jasont35, any interest in doing this one? You could likely just add the code into the dialog directly.

**Comment by jasont35** [comment]
Wish I could Veronica, but I currently do not have any time to devote to scripts.

**Comment by CDPotter** [comment]
Side note, the notice will probably need to be tweaked a bit, maybe even reading the ADDR panel? I don't think we do a lot of in home interviews so I'm not entirely sure how it works.

Would it be safe to write the address in ADDR in the notice as the location?

**Comment by jasont35** [comment]
I talked to the worker who suggested this and he thinks this would work for most cases. The only thing he did mention is if there was the possibility of being able to select whether it was the residential address or the mailing address that was used. It would be a rare occasion that a worker would be visiting the client at their mailing address but it could happen. Maybe we add 2 new interview locations - one for In-home interview residential address and one for In-home interview mailing address.

**Comment by theVKC** [comment]
Well, I'm wondering if any scriptwriters who do this process could take this one? Since most agencies don't address in-home's, I probably can't prioritize this over my existing issue list.

We'll keep it on the list until the first April hackathon. If nobody has taken the issue I'll close it. Perhaps one of the scriptwriter agencies does this process?

**Comment by theVKC** [comment]
FYI: if this script were to be done, I'd want it done with a global variable, which should default to "off" (don't want to freak out financial workers in agencies that won't offer this option to most financial workers).

**Comment by theVKC** [comment]
Closing issue due to lack of interest from scriptwriter agencies. Anyone can re-review the issue if they'd like, if they have time to devote to it.
