### ISSUE TITLE
New Scripts Banked Month WCOMS

### ISSUE THREAD

**Issue by CDPotter** [MN-Script-Team/DHS-MAXIS-Scripts#2039]
(FOR POST FREEZE)

Anyone interested in some WCOM scripts for:

All banked months used = "You have been receiving SNAP banked months. Your SNAP is closing for using all available banked months. If you meet one of the exemptions listed above AND all other eligibility factors you may still be eligible for SNAP. Please contact your financial worker if you have questions."

Banked months notifier = "You have used all of your available ABAWD months. You may be eligible for SNAP banked months if you are cooperating with Employment services. Please contact your financial worker if you have questions."

Closing for E/T non-coop = "You have been receiving SNAP banked months. Your SNAP case is closing because CLIENT NAME did not meet requirements of working with Employment and Training. If you feel you have Good Cause for not cooperating with this requirement please contact your financial worker before your SNAP closes. If your SNAP closes for not cooperating with Employment and Training you will not be eligible for future banked months. If you meet an exemption listed about AND all other eligibility factors you may still be eligible for SNAP. Please contact your financial worker if you have questions."

Thoughts?

**Comment by IlseFerris** [comment]
Very interested, and thank you!

**Comment by theVKC** [comment]
Do you want this one, @CDPotter?

**Comment by CDPotter** [comment]
We have them build in a master script, just gotta pull them out and make them their own things.
