### ISSUE TITLE
Merge the stats block that loads after FuncLib with the stats info from prior-to FuncLib block

### ISSUE THREAD

**Issue by theVKC** [MN-Script-Team/DHS-MAXIS-Scripts#2042]
Basically, making it one block. I got this.

**Comment by GayS** [comment]
I have moved all the stat collection blocks to follow start timer in the ACTIONS scripts.  Do you want me to send a pull request?

**Comment by theVKC** [comment]
If they're all done, go for it. And thank you @GayS!

**Comment by theVKC** [comment]
This is now a duplicate of #1938. Removing.
