### ISSUE TITLE
bug fix: Training case gen MSA/SNAP approval needs to slow down

### ISSUE THREAD

**Issue by CDPotter** [MN-Script-Team/DHS-MAXIS-Scripts#2044]
MSA and SNAP get approved too quickly back to back causing the first month of SNAP to not have the very recently approved MSA budgeted into it. 

I'll take a crack at this.

**Comment by CDPotter** [comment]
After trying to work on this for the day I'm hitting a solid wall. I was able to get it most of the way there, however it just seems like this is too much for MAXIS to handle. 

After much experimentation (see all the Francis Underwoods in training region.) I was operating on; If MSA had been approved then the script would force it's way into background so SNAP could have MSA budgeted into it for the initial SNAP month. However in doing so you have to account for the case being locked in elig background after the MSA approval, then the case trying to get to SNAP elig but unable to because there are results being generated in the BGTX you just did, then you have to get past the popups on ELIG SNAP asking if you're sure you want to approve SNAP without current MSA results being approved. 

I ran this current version 6 times
- 4 times I hit NAT errors around trying to force my way past the message that the SNAP results out there are from an older version please wait while BGTX processes.
- 1 time I was able to get to the point where SNAP ELIG asks are you sure you want to approve SNAP results with unapproved MSA results (since we ran it through BGTX). There may have been more to account for in terms of programming for these popups. 
- 1 time the entire thing crashed stating script error line 1 1 with no message beneath it explaining why. Then the script continued to act weird when reopened. I might chalk this one up to having too many excel files open at the same time.

Here are the fruits of my labor if there is anyone intrepid enough to work on it. 
https://github.com/CDPotter/DHS-MAXIS-Scripts/commit/21e754b97ecc152b05fe85fd380dff76324e2fa4

**Comment by theVKC** [comment]
I agree, this doesn't seem like a big enough problem to worry more about.

Can I request that Krabappel be updated to indicate this, perhaps on the main dialog? Something like: "note: MSA/SNAP cases might not have the MSA budgeted onto SNAP for first month due to system limitations"? This (in my opinion, at least) would "resolve the issue" in that folks would know not-to-do-that.

@CDPotter, can you make that addition to close this issue?
