### ISSUE TITLE
Dail Scrubber - Postponed Verifs Script

### ISSUE THREAD

**Issue by khiestand** [MN-Script-Team/DHS-MAXIS-Scripts#2046]
New Script Idea from a Sherburne Co Worker:

Dail scrubber.  If we have an expedited case and we approve it and request verifications. If the client does not return the verifications the case will auto-close and a dail message will pop up and saying  something about case auto closed due to not turning in postponed verifs.  If the script could put that into a case note and state the policy for when a client could be deemed expedited again.

I don't probably have time, please mark as help wanted.  Thanks!

**Comment by CDPotter** [comment]
I really like that one! Much better than the generic Closed Progs (if the worker even uses it). Pulling the guts out of Closed Progs would be a good start for determining dates.

**Comment by C-Love** [comment]
I love this! I want it

**Comment by kennyasalee** [comment]
cool

**Comment by theVKC** [comment]
Boom @C-Love! Ha ha @kennyasalee.

**Comment by C-Love** [comment]
@theVKC - I have to push this back to the May release.

**Comment by theVKC** [comment]
@C-Love I'm going to push this back to June because you've been out. If you get it done, great. Otherwise, we'll push it back. If you won't have time for it we can close it.

**Comment by theVKC** [comment]
Moving to July per @C-Love at meeting.
