### ISSUE TITLE
Shelter Expense Verif Recv'd Issue - Room and Board

### ISSUE THREAD

**Issue by jasont35** [MN-Script-Team/DHS-MAXIS-Scripts#2047]
A worker used this script and selected the "Check here if this is for Room and Board" and finished the rest of the fields. When she selected "OK" a pop up window opened informing her that she would need to enter in the information into the SHEL panel manually. The script then created 2 separate case notes. One case note had the correct title, how much the rent was ($0 in this case), and the worker's signature. The second case note had a weird title (the number 3 and some symbols), and then listed the new address that was reported.

**Comment by theVKC** [comment]
Has this been able to be duplicated, @jasont35? I don't mean to sound dismissive, but sometimes MAXIS just messes up sometimes. I don't think we've been seeing this in our testing. Any chance you can duplicate the error?

**Comment by jasont35** [comment]
I had the worker show me while I was watching and seen the 2 case notes that it created. I don't have a live case example but I used a training case I had to run the script and it created both of the case notes. I ran it 3 times. I will send you the training case number in SIR if you would like to check it out. 

First time it had an error and wasn't able to go to the SHEL screen. One case note was created but I did not put in a dollar sign in the rent area and got a Script Error -- "Script Error at Line 1, Column1: Type mismatch: 'FormatCurrency'". 

2nd time I ran it and filled in the dollar sign in the rent area. Script worked great but created 2 case notes. One case note title Shelter Expense Verif Received on 03/30/2016 looks correct but does not have the address information. 2nd case note has what appears to be the date in the title but missing a character and has the address in the body of the case note. 

3rd time I ran it I left the dollar sign out again in the rent area. Script was able to go to SHEL and worked correctly, but again created the same 2 case notes as well as giving me the same Script error as above.

**Comment by theVKC** [comment]
If you can email me with screenshots and case numbers, I'd be happy to take a look sometime next week.

**Comment by theVKC** [comment]
Fake case 232968 shows this one. But, sadly, I won't have time to look at it until a couple of weeks from now at least. It's definitely a bug and definitely there. Any takers?

**Comment by CDPotter** [comment]
I'll start digging.

**Comment by CDPotter** [comment]
I think I've spotted the goofiness, submitting pull to Master.
