### ISSUE TITLE
DISQ Generator

### ISSUE THREAD

**Issue by LaLarson** [MN-Script-Team/DHS-MAXIS-Scripts#2051]
Initially I would like to create a script that creates IEVS DISQ panels (for all programs and all assistance unit members), and then case notes them.

**Comment by theVKC** [comment]
@LaLarson: do you think you'll have time to complete this before Friday April 15? If not, I'll move it to the May release.

**Comment by LaLarson** [comment]
Could you move this one to May? :)

**Comment by theVKC** [comment]
Sure thing. Thank you!

**Comment by theVKC** [comment]
Think this will be done by Friday @LaLarson? Still interested in it? Want me to close it?

**Comment by LaLarson** [comment]
Yeah, that one will definitely not be done by Friday… ☹

I would say you can close it for now, and I’ll make a new issue later if we need to. ☺

Laura Larson
Eligibility Specialist, FSA

PH: 507-328-6182
FX: 507-328-7956
