### ISSUE TITLE
New script idea update address 

### ISSUE THREAD

**Issue by CJOHNS356** [MN-Script-Team/DHS-MAXIS-Scripts#2052]
A script that would update all the information on the ADDR panel and write a case note 

I would like to work on this

**Comment by theVKC** [comment]
Hi @CJOHNS356! Any chance you'll be completing this before Friday? No worries if not, but I need to know whether-or-not it needs to be moved to the May release target instead of the April release target. It's no big deal if not, but I'd like to know in order to keep the issue list up-to-date.

Thank you!

**Comment by CJOHNS356** [comment]
Veronica,
No I don't think I would be able to complete this by Friday
please move to May

Thank you

**Comment by theVKC** [comment]
Can I get an update on this @CJOHNS356? Do you think it'll be done by Friday (the due-date for the next release enhancements)? Thanks!

**Comment by CJOHNS356** [comment]
Veronica,

The script is about 80 % done it has a few bugs I need to work out and the case noting part of the script still needs to be written.  I am currently way behind in my regular work and I am not sure I would be able to complete this by Friday. I think it would be better to wait until the next release.

Christopher Johnson
Family Support and Assistance
Eligibilty Specialist
Olmsted County Family Support and Assistance
Phone: (507) 328-6311
Fax: (507) 328-7956

NOTICE: This e-mail communication is for the sole use of the intended recipients and may contain unclassified confidential information. Any unauthorized disclosure, copying or dissemination of this communication is prohibited. If you are not the intended recipient, please notify the sender by e-mail and delete all copies received. Thank you.
P Go Green!  Please do not print this e-mail unless it is completely necessary.

**Comment by RobertFewins-Kalb** [comment]
For the sake of simplicity, is it worth considering opening up ACTIONS >> SHELTER EXPENSE VERIF RECV'D? That script will update ADDR and case note. I think there's a requirement that some shelter expense be entered but we could modify err_msg handling to allow this script to be more generally a shelter info updater

**Comment by CJOHNS356** [comment]
Thank you I will check that out

Christopher Johnson
Family Support and Assistance
Eligibilty Specialist
Olmsted County Family Support and Assistance
Phone: (507) 328-6311
Fax: (507) 328-7956

NOTICE: This e-mail communication is for the sole use of the intended recipients and may contain unclassified confidential information. Any unauthorized disclosure, copying or dissemination of this communication is prohibited. If you are not the intended recipient, please notify the sender by e-mail and delete all copies received. Thank you.
P Go Green!  Please do not print this e-mail unless it is completely necessary.

**Comment by theVKC** [comment]
Hi @CJOHNS356! Any chance this will be done Friday for testing for the June release? We've moved this quite a few times and if it isn't going to be ready I will close the issue until you're ready to release it. If it's ready and you just need GitHub help, let me know and I can help there this week. I'm about to issue new instructions for adding a script to GitHub.

**Comment by LaLarson** [comment]
Hi V! Chris is actually out of the office for the week.

**Comment by theVKC** [comment]
Thanks @LaLarson! I'll move it to July then. @CJOHNS356, when you get back, an update would be greatly appreciated.

**Comment by theVKC** [comment]
@CJOHNS356: can I get an update on where this script is at? If I'm not hearing from you in the next week or so, I'll assume the project isn't being worked on anymore and will close the issue here (we can always reopen it when you get time).
