### ISSUE TITLE
Script Idea to have a script that generates OUT OF STATE VERIFICATION form

### ISSUE THREAD

**Issue by kennyasalee** [MN-Script-Team/DHS-MAXIS-Scripts#2053]
we have a OUT OF STATE Contact information from http://www.dhs.state.mn.us/main/groups/economic_support/documents/pub/dhs16_143156.pdf

Idea: A OUT OF STATE inquiry script. Worker can select a STATE, have the (HH_memb) Select the client you want to inquirer about, and have the script generate a out of state inquiry Word Doc request form. The Script will pull info such as: the X16XXX contact info and county address info, etc from MAXIS, clients address information, out of state contact information, and includes the info onto the generated Word Doc Form request. Does a case note. Then the worker can print out the form and fax it to the Out State Agency

**Comment by theVKC** [comment]
@kennyasalee: do you think you can get this done by the 15th? If not, I'm going to set it out for the May release instead of the April release.

**Comment by theVKC** [comment]
Assigning to Casey because @kennyasalee is not a formal contributor just yet. Once he submits a script somewhere he can be directly assigned tasks. It's a sometimes clumsy system.

**Comment by theVKC** [comment]
Can I get an update on this @kennyasalee?  Do you think it'll be done by Friday (the due-date for the next release enhancements)? Thanks!

**Comment by theVKC** [comment]
I've moved this to the June release. @kennyasalee, please reply to comments on GitHub when we ask for updates. This is how I manage the project.

**Comment by kennyasalee** [comment]
Wow I am so out of date on this one. I started on this and have a version I am testing on right now. 06/16 release is possible

**Comment by kennyasalee** [comment]
so I do commit to this? @CDPotter ??

**Comment by kennyasalee** [comment]
Possibly by this Friday 06/17/16 or by 06/24/16...

**Comment by theVKC** [comment]
Wonderful, I'll keep it here in June and if it doesn't happen by Friday let me know and I'll bump it to July. Thanks for the update!

**Comment by theVKC** [comment]
Welcome to the (formal) team, @kennyasalee!

I've added you as the assignee to this issue. I'm moving it to the July release target, but if you can get it done today please feel free to pull request it.

**Comment by CDPotter** [comment]
Hey @kennyasalee hows things with the script going?

**Comment by kennyasalee** [comment]
darn I just mess it up again on the file name format!! argh. forgot the "s" after "NOTICE". let me know if this can be corrected or closed again. sorry

**Comment by CDPotter** [comment]
You'll have to create a new pull request for me to be able to review it. You can always add a new commit to a branch you're working on while the pull is active to make changes.

**Comment by kennyasalee** [comment]
perfect sounds good. sorry for the fuss
