### ISSUE TITLE
New Script Idea- Actions- Date of Death 

### ISSUE THREAD

**Issue by asunderman** [MN-Script-Team/DHS-MAXIS-Scripts#2054]
Actions script with a dialog box for case #, DOD, place of death, lien "yes" or "no", surviving spouse check box, note to check CFR & confirm either x-fer to CFR or  refer file for possible estate collection.  Create case note for all these things.

would update STAT MEMB with a DOD & transmit

reminder to check HC elig and approve as needed

I'll attempt this.  :)

**Comment by theVKC** [comment]
Go @asunderman!
