### ISSUE TITLE
New script idea- Actions- PACT Panel/Returned mail

### ISSUE THREAD

**Issue by KateiMartini** [MN-Script-Team/DHS-MAXIS-Scripts#2055]
I would like to create an action script for returned mail and/or other reasons (refused to file, request case closure)  using the Pact panel to close.

Returned mail**following poli/temp guidelines.

I would like to work on this project.

**Comment by theVKC** [comment]
@ruthmaloney, you might like this one. :) Go @KateiMartini!

**Comment by ruthmaloney** [comment]
Yesssssss! Reviewing cases today with PACT errors. Too common!

Ruth Maloney

**Comment by theVKC** [comment]
Can I get an update on this @KateiMartini? Do you think it'll be done by Friday (the due-date for the next release enhancements)? Thanks!

**Comment by theVKC** [comment]
I haven't heard yet, so I'm moving this to June.

**Comment by KateiMartini** [comment]
Sorry, for the delay in responding.  Yes if you could move it to June that would be great.  I have been working on it this week but I don't think I will get it done in time.

**Comment by theVKC** [comment]
Done. No problem! Thanks for doing it! It'll be a hit!

**Comment by theVKC** [comment]
@KateiMartini, can I get an update on this? Do you think it'll be done by Friday?

If not, I may close the issue if you don't think you'll have time in the next month-or-so to work on it. I need to try and keep the issue list up-to-date and if it isn't being worked we can mark it as a "sleeper" issue (something to be worked on when time allows) and close it from the active list. That's no big deal.

If you think you can get it done this week, I'll keep it in June. If you think it'll be next month, I'll move it to July. If you don't have time (or if I don't hear by Friday), I'll close the issue.

**Comment by theVKC** [comment]
Closed due to lack of response from scriptwriter assigned. @KateiMartini, please feel free to reopen this issue before pulling it in.
