### ISSUE TITLE
New Script: Unea panel 

### ISSUE THREAD

**Issue by MulvaneyDani** [MN-Script-Team/DHS-MAXIS-Scripts#2056]
I would like to write a script for a unea panel for direct spousal support. This could eventually be enhanced for other sources of unea/ HH members.

**Comment by theVKC** [comment]
Yay! Good luck!

**Comment by theVKC** [comment]
@MulvaneyDani: do you think you'll have this completed by Friday the 15th? No worries if not, but I'll move it off of the April release track and into the May release track.

**Comment by theVKC** [comment]
@MulvaneyDani, since I haven't heard from you, I'm moving this to May.

**Comment by theVKC** [comment]
Can I get an update on this @MulvaneyDani? Do you think it'll be done by Friday (the due-date for the next release enhancements)? Thanks!

**Comment by theVKC** [comment]
I haven't heard from @MulvaneyDani, so I am moving this to the June release and opening it up for other scriptwriters. Anyone want it? @MN-Script-Team/county-agency-scriptwriters?

**Comment by theVKC** [comment]
Marking as a sleeper and closing it. We will reopen if anyone is interested.
