### ISSUE TITLE
New Script idea - HC Fiater for Earned Income for LTC- ICF-DD clients

### ISSUE THREAD

**Issue by mxiong1** [MN-Script-Team/DHS-MAXIS-Scripts#2057]
Some  Long-term care clients that are in ICF-DD facilities active on health care works & receives earned income, however, they are allowed the following deductions of $80 special personal allowance from earned income & FICA taxes withheld, if a FIATER can be created it'll be helpful. 

Policy exist: HCPM 23.15.10

**Comment by theVKC** [comment]
Hi @mxiong1! Think this can be done by the April 15 deadline for new scripts for April? If not, no worries, I'll just kick it back to the May release.

**Comment by mxiong1** [comment]
Hi Veronica,

The script was already completed, but I believe Ilse was going to help me enhance the script.

Thanks,

May C. Xiong | AFAW Unit 1- Financial Worker
Financial Assistance | Community Human Services
160 East Kellogg Boulevard, Saint Paul, MN  55101
Fax: 651-266-3933
may.xiong@co.ramsey.mn.us<mailto:may.xiong@co.ramsey.mn.us>

[cid:image001.jpg@01D0F463.0A6BF010]

**Comment by IlseFerris** [comment]
@mxiong1, Let's coordinate next week to get your script done!

**Comment by mxiong1** [comment]
@IlseFerris sounds good.

**Comment by theVKC** [comment]
Fantastic! @IlseFerris, since I can't directly assign ownership of issues to @mxiong1 (since she doesn't have an accepted pull request yet), I'm going to assign this issue to you, since you're providing leadership on next steps with the script. @mxiong1, when the script goes live, you'll get all the credit. :)

**Comment by IlseFerris** [comment]
Works for me!

**Comment by mxiong1** [comment]
Awesome:)
