### ISSUE TITLE
NOTES - Vendoring Information

### ISSUE THREAD

**Issue by senhorc** [MN-Script-Team/DHS-MAXIS-Scripts#2058]
Script will read vendor type(s), vendor name, vendor number, phone number, account number, dollar amouint owed by the client and the budgeted amount, input from dialog by user, will write to casenote

I would like to use for DHS classroom scripting practice

**Comment by theVKC** [comment]
Accidentally assigned the wrong person. Removed assigned person.

**Comment by theVKC** [comment]
@senhorc, a couple of things.

1. I don't think you've accepted the invitation to formally join the script team for assignments. I sent this a month ago or so, you can accept at https://github.com/MN-Script-Team. Please do this so I can properly assign you this issue (it appears unassigned from my admin area).
2. Do you think you can have this done by April 15? That's the deadline for new scripts to be added to the April release. If it's not able to be done by then, that's fine. Just let me know and I'll move it to the May release.

**Comment by theVKC** [comment]
Assigning to @IlseFerris just for tracking: @senhorc is doing the work. @senhorc, if you can accept the invitation to formally join MN-Script-Team, that'd be swell. https://github.com/MN-Script-Team

**Comment by theVKC** [comment]
@senhorc and @IlseFerris, this issue has been inactive for some time without anyone working on it. I'm going to mark this as a sleeper issue, and close it. If you get it built locally and you're comfortable, please please please tag me in this issue and ask me to reopen it.

**Comment by IlseFerris** [comment]
Works for me. @senhorc should be back to work soon so we'll be able to take care of it then.
