### ISSUE TITLE
Enhancement Request -- Add supervisor name to BULK report scripts that can be run agency wide

### ISSUE THREAD

**Issue by RobertFewins-Kalb** [MN-Script-Team/DHS-MAXIS-Scripts#2061]
A request has been made to add the supervisor name to BULK - CHECK SNAP FOR GA/RCA. For scripts like this, though, that can be used for quality assurance, I'm thinking we could expand that to other BULK report scripts to make distribution of lists easier.

I have a couple of ideas for this and would happy to take it on.

**Comment by theVKC** [comment]
I like it. Thanks @RobertFewins-Kalb!

**Comment by RobertFewins-Kalb** [comment]
RE: CHECK SNAP FOR GA/RCA, I am going to add a manual time for looking up the worker's supervisor for those folks doing Stats Plus Plus. The process is going to REPT/USER, entering the worker ID, finding the supervisor ID, and then entering that to find the supervisor name. I have that process timed at 25 seconds.

Testing now, but initial results are looking good. I will have a pull request for Check SNAP for GA/RCA ready today.

**Comment by theVKC** [comment]
Can we create a checklist for these so we know when the issue is complete, @RobertFewins-Kalb? 

I'll start:

- [ ] CHECK SNAP FOR GA RCA
- [ ] FIND PANEL UPDATE DATE

**Comment by theVKC** [comment]
@RobertFewins-Kalb: I suppose you should add the checklist to the top, since this is your issue and not mine that I created.
