### ISSUE TITLE
Bug -- Paystubs received is jumping ahead one employer.

### ISSUE THREAD

**Issue by RobertFewins-Kalb** [MN-Script-Team/DHS-MAXIS-Scripts#2065]
I suspect the checking for password out modification is what is causing this.

Staff are reporting that the script is putting the information on the wrong panel. I think the transmit in check_for_password is doing it.

I'm looking into it

**Comment by theVKC** [comment]
Weird, I'd have hoped we'd catch that in testing.

**Comment by theVKC** [comment]
Reopening because this is still up in master. Can someone running master test this for me? @RobertFewins-Kalb? @CDPotter?

**Comment by theVKC** [comment]
*up in release, not master

**Comment by CDPotter** [comment]
I ran it on a fake case with 2 jobs panels, it appears to be working the correct job (job 01) was updated.

**Comment by theVKC** [comment]
Great. @RobertFewins-Kalb: I'll close it in release.
