### ISSUE TITLE
Appointment letter: update intake address for Carver County

### ISSUE THREAD

**Issue by theVKC** [MN-Script-Team/DHS-MAXIS-Scripts#2070]
Here it is: 602 E 4th St, Chaska, MN 55318

Anyone want it? It needs to be done by April 15 so it can go out for testing. Should be as easy as adding a couple of lines to the script, and if you're newer I'd be happy to walk you through it.

**Comment by asunderman** [comment]
I'll bite.  Sounds like it might not be a bad place for a newbie to start.

**Comment by theVKC** [comment]
Great! @asunderman: if you want me to walk you through the process, perhaps we can set up a phone meeting for later this week. It's an easy fix, you might be able to tell how to do it just by looking at the code.

**Comment by asunderman** [comment]
I think I'll try it first and see if I can figure it out.  If I need help, I'll send up the white flag.

**Comment by asunderman** [comment]
A question @theVKC - in looking at the script file I see there are a couple other counties with no address listed.  I was thinking about contacting them, getting the appropriate addresses for them and updating them ALL at once.  Can I do that?

**Comment by theVKC** [comment]
If you want to, be my guest! My last attempt was likely a year ago.
