### ISSUE TITLE
Enhancement- NOTES - LTC - RENEWAL

### ISSUE THREAD

**Issue by JonesPat** [MN-Script-Team/DHS-MAXIS-Scripts#2071]
Looking for the custom household array to be added to the NOTES- LTC- Renewal script. Some workers have clients with 2 members in the house hold but also have CADI cases with 4 or 5 members. Supervisors are looking for specific client.

**Comment by CDPotter** [comment]
So there's two sections to this script, I don't use it in gen work so I'm not too familiar with it.

1: Pulling data from stat panels, I'm assuming this one needs to be narrowed to specific HH members.

2: Pulling elig data for memb 01 and 02. Would it be good to make this section specific to HH members as well?

**Comment by RobertFewins-Kalb** [comment]
Follow up question (b/c I'm here in Dakota with @JonesPat) is whether this is appropriate script for CADI renewals.

It sounds like the enhancement request is to make the LTC renewal more similar to the HC renewal. Is there CADI-specific information that NOTES - HC RENEWAL is missing that is included in NOTES - LTC - RENEWAL?

**Comment by JonesPat** [comment]
Attached is the breakdown request for what was requested. The request combines different parts between the NOTES - HC RENEWAL and NOTES - LTC - RENEWAL and adds the HH members box for LTC renewals with 2 members or CADI renewals

[ScriptRequest.pdf](https://github.com/MN-Script-Team/DHS-MAXIS-Scripts/files/202917/ScriptRequest.pdf)

**Comment by RobertFewins-Kalb** [comment]
Speaking with Dakota Co folks. Going to request some state guidance on the issue. Wondering if this is waiver-specific? @IlseFerris? Any thoughts? Should we be case noting more for LTC/waiver renewals?

**Comment by theVKC** [comment]
I'm bowing out of this for now. My HC contact has recently left the agency and I don't currently have a replacement. I'll support whatever decision is made by the group on this one, but I don't have resources here to provide/determine direction (not for a bit while I await a new contact).

**Comment by theVKC** [comment]
Can we get a decision on this one made by hackathon Monday (04/11)? At least, progress made? If I hear nothing else, I'll close it then.

**Comment by RobertFewins-Kalb** [comment]
I'll poke around with the script if no one else wants. It's still slightly vague about what is wanted other than -- please make mind meld NOTES - LTC RENEWAL and NOTES - HC RENEWAL 

Possibly something to consider with scripts consolidation (I'm forgetting the op name...Brooklyn?) rather than now.

**Comment by theVKC** [comment]
Project Bowie is for ch ch ch ch changes.
Project Gorbachev breaks up the biggest script in town, the CAF script.

Both use chain-loading functionality to reduce the number of buttons folks need to click to find/use a new script.

Project Brooklyn is a play on the Manhattan Project. It's the CSES scrubber modifications.

#TheMadnessHasBeenExplained

**Comment by theVKC** [comment]
Do you want me to target this for April, or May?

**Comment by RobertFewins-Kalb** [comment]
May at the earliest

**Comment by theVKC** [comment]
I'll add it for May, we can always revisit. Let me know if it becomes unattainable and I'll close it.

**Comment by StephanieW7** [comment]
Is this script working?  We have tried it lately and we are receiving this error...."A 05/2016 span could not be found.  Try this again.  You may need to run the case through background."  
There is an approved HC version for 05/2016 and now an unapproved version for 05/2016.

**Comment by RobertFewins-Kalb** [comment]
@StephanieW7 can you create a new issue for that?

![image](https://cloud.githubusercontent.com/assets/7842016/14864461/96cbcf50-0c7f-11e6-92ae-f733cf5e7a76.png)

**Comment by StephanieW7** [comment]
Can do – Thanks, Stephanie

**Comment by theVKC** [comment]
Can I get an update on this @RobertFewins-Kalb? Do you think it'll be done by Friday (the due-date for the next release enhancements)? Thanks!

**Comment by theVKC** [comment]
This might be addressed through Bowie or other upcoming projects. Closing and marking as a sleeper issue. We can pursue at a different time if there's interest.
