### ISSUE TITLE
NOTES - CLOSED Program - Dialog Modifications

### ISSUE THREAD

**Issue by Y-Lor-Y** [MN-Script-Team/DHS-MAXIS-Scripts#2076]
A staff brought to my attention about the notes - closed program script.  It asked her to input the last date of elig (which is the last day of the month before closure month).  However, when you input that date in there.  The case note generated by the script still shows that the last day to REIN would be that same date of closure as entered in the dialog.  An example below, so that you can see what I'm referring to.
>>>
Closed HC/cash 3/31/2016                                     
* Reason for closure: IEVS non-cooperation 4th quarter 2015- M01.     
* Verifs needed: Signed IEVS difference notice returned or all EI from
                 10/2015-12/2015 for M01 job at Torgeson.             
* Updated MMIS.                                                       
* Added WCOM to notice.                                                                                                      
* Last HC REIN date: 3/31/2016, after which a new HCAPP is required.  
* Last cash REIN date: 3/31/2016, after which a new CAF is required.  
* All programs closed. Case becomes intake again on 5/1/2016.         
>>>>
The date of closure the dialog ask for is 03/31/2016 (this is the last date of case being active - prior to the month of closure).  But the Date the programs "last" REIN should not be the same as the date of closure.

The rein date should at least be +1 "m" from the date of closure.
And for HC purpose if due to no renewal/review, rein date should be at least +4 "m" from date of closure.

Thanks,

**Comment by theVKC** [comment]
Do you have a policy citation for the month + 1? I believe we had policy confirm some time ago that they don't get an extra month, and it's considered a new application without a REIN period.

Can you get that citation, @Y-Lor-Y?

**Comment by Y-Lor-Y** [comment]
Maybe the example I gave above is a poor example.  However, for MFIP if client is auto-closed for situation such as no HRF/ER completed for review month of 04/2016, the last active date is 3/31/2016.  Client still have that window within 04/2016 until last date of 04/30/2016 for the case to be REIN back to 04/01/2016.  I think this is what the staff was getting at.  This is where the +1 comes into play.

Also, maybe the REIN verbiage in the case note is what threw me off, too.  Because if a case is set to close for 05/2016, and today 4/04/2016...it doesn't make sense to say that the last date to REIN it would be 04/30/2016, when the case itself in 04/2016 is still active and does not need a REIN.

I'll look at the CM for reinstatement for MFIP.

**Comment by theVKC** [comment]
I think (if I'm not mistaken) we phrased it that way for clerical/coverage staff who might not know that the client can't be reinstated. By putting a firm date in, we were able to accurately convey to the non-worker staff that the client needed a new application.

I am open to tweaking the wording, but I don't want to add +1 month unless we have a policy citation. :)

**Comment by Y-Lor-Y** [comment]
SIR message issued on 12/30/14 - expired 01/30/15 - 
* Effective Feburary 1, 2015 a 30-day reinstatement period will be allowed for these cash programs.

CM: 0007.03.06 - Processing a Late HRF - states that you can reinstate the MFIP back once the HRF process is consider complete.  References to TE02.08.188.

Bulletin# 14-69-05 :  30-day reinstatements.
Effective February 1, 2015. A 30-day reinstatement period will be allowed. If a case is
closed due to not completing the recertification process, the case may be reinstated if
recertification requirements are met within 30 days of the termination of benefits. Benefits
are retroactive for the full benefit month.

So - I guess it's safe to say for CASH, if closed for incomplete/no review (HRF or ER) - the last day to REIN would be +1 "m" for the date.

**Comment by theVKC** [comment]
I don't know. I'm not sure if you actually "REIN" in these situations. "Reinstate" (the policy term) versus "REIN" the system term are two different things.

Perhaps we can weigh in with MFIP/HC policy folks? Alternatively, I'm just going to remove the functionality entirely. I spend too much time thinking about it.

**Comment by theVKC** [comment]
Perhaps any other @MN-Script-Team/county-agency-scriptwriters have any opinions on it?

**Comment by Farleight** [comment]
I've been eying this one. I'm curious what you mean by Reinstate versus REIN being two different things. Is this a thing that people know about that I don't know about? Because I've always considered them pretty synonymous. I can't think of a reinstate situation in which you wouldn't REIN.

In terms of policy, he's absolutely right. There should be an extra month in the situations he has presented. The script instructions seem to allow for the possibility in certain cases too: 

"Case is at CSR recert (gets entire next month after closure for REIN), and 
Case is at HC annual renewal (can turn in HC ER instead of new HCAPP, but still counts as a new application)."

I'm not sure how the functionality translates to that though.

**Comment by C-Love** [comment]
I am a bit confused about the issue here. I think part of the problem is a general understanding of when to Reinstate policy and Reapplication policy. I have seen many workers REIN when they should be APPLing. I think maybe it would be helpful if we had the policy references and had it all mapped out we could build the explanations into the script so that we can help workers advance their understanding of this often incorrectly applied policy. 

However, @Y-Lor-Y the autoclose issues are a bit different. I can't imagine people are running this script on autoclosed cases - and I don't think they would need to. 

@theVKC  I can understand wanting to do away with this but I think we should not back down from advancing our working understanding of this particularly incorrectly applied policy.

**Comment by Farleight** [comment]
I wanted to make that point about auto-closures too, which is what led me to the script instructions... but I didn't see anything in there that would have set people away from that course, so while I agree that they probably shouldn't run this script for auto-closures, I don't know that I'd feel comfortable saying they're not.

**Comment by theVKC** [comment]
@Y-Lor-Y: could these issues be stemming from not using the checkboxes @Farleight outlined correctly?

**Comment by LaLarson** [comment]
Boom... Totally agree with @C-Love! I think that the misunderstanding of policy that she is referencing is all the more reason that getting this locked down, and perhaps getting more info on the dialog box, is a great thing! Let me know if I can help in any way. 

Also, I can confirm that when a case closes for no HRF they do have until the last day of the month it closed to turn it in/complete it. For CSR's I'm pretty sure they have until the last day of the month to complete it, but benefits should be prorated from the date of receipt of the final verifications. For recertification it depends on if they turned in the CAF or not. If they did, then they have until the end of the month to have the interview and get all their proofs in, and it can be REIN'd (although sometimes it would be in their favor to just reapply, especially if expedited). If not, they need to reapply.

HC I would have to do some double checking on, but there are definitely people (MAGI?? Could be everybody though?) who have the extra three/four months (it follows the retro application policy). 

This is just my working knowledge?  I would have to double check policy to be sure, but it looks like it's probably all up there in @Y-Lor-Y 's response. I love the idea of making this clearer for people! It's so convoluted!

**Comment by theVKC** [comment]
@LaLarson: I know of no-one more qualified to properly convey complex info on a dialog than you. Would you want to take the lead on this one?

**Comment by LaLarson** [comment]
@theVKC Potentially?! When does this need to be done by? I don't have immediate time I don't think, but if it's by May release I might be able to?

**Comment by theVKC** [comment]
It's not super critical. I'm comfortable with May release, @LaLarson. Thank you! Boom!

@Y-Lor-Y: if you can confirm whether-or-not existing checkboxes were utilized, that'd be wonderful.

**Comment by Farleight** [comment]
This is one of those things that would actually make a nice little side-script... no functionality inside of, or connection to, MAXIS... just a thing that you run that asks you a series of questions. "6 Month or Annual?" "Was Paperwork Received prior to closure?"  "What programs are we looking at?" "Why does the caged bird sing?" And then it compiles that and just tells you if it's REIN or not... and maybe cites the portion of policy that explains why.

That seems unlikely to happen... but that's my own take on a very beneficial, yet functionally useless script.

**Comment by theVKC** [comment]
Hmmm. I actually kind of like it, @Farleight. Could be a good add-on for Closed Progs.

**Comment by Y-Lor-Y** [comment]
@theVKC @LaLarson   I asked the staff and she said, yes, they used the checkboxes.

More detail info on how or when to use this script would be great, if it's not intended for auto-close cases.

Initially that's what I thought - that it was not for auto-close cases.  But the more I look at it the script, and how the case note is lay out...I thought maybe it's for all situations.  That a case note why the case was closed, may it be auto-close - which the client can reinstate their cases.  If it was closed for a other reasons beside auto-close, then a different verbiage could be sub into rather then rein, which may also have led this particular staff of mine to use it.  Enhancement could be a good build-in.  If the intend of this script is for coverage or clericals - then informing the client from a clerical or worker - that they need to reapply or having their case reinstate would be even better if the verbiage is more specific.  Over All, I like the script and support it.  To do away with it would be wise, imo.

REIN to me, is the functionality for MAXIS while reinstate or reinstatement is the verbiage used in policy/context/contents.  They're the same.

I do agree with you @C-Love that quite a number of workers are using REIN where they should be APPL'ing.  And, understanding when to take action between the two are crucial.

**Comment by theVKC** [comment]
For the record: "REIN" and "reinstatement" aren't the same. One's a MAXIS procedure while another is a policy guideline. There are instances where you do one without the other.

If the checkboxes had been used, they should get the spare month. I've tested this recently and that works. If that functionality was broken recently, we should fix it.

REVW/MONT Closures is for autoclose cases. @LaLarson, if you update this dialog, can you add a note making that clear to folks?

**Comment by C-Love** [comment]
agreed @theVKC - REVW/MONT Closure should be used for autoclose. Took the words out of my mouth.

**Comment by theVKC** [comment]
Also, I'm making this issue specifically about dialog modifications to clear up misconceptions and language. @LaLarson, thank you for agreeing to take this on.

Since this appears to also be a bit of a policy discussion, I'm going to ask that any new discussion about the policy take place in Slack. This thread has become really long.

If any bugs are found in the actual script itself (i.e. checkboxes aren't working as expected), please make a new issue.
