### ISSUE TITLE
BULK / Update EOMC list ~ Script error at Line 1, Column 1

### ISSUE THREAD

**Issue by ALJ10** [MN-Script-Team/DHS-MAXIS-Scripts#2077]
First, I have to say THANK YOU for creating this script. It will be very helpful to us!
NOTE FROM SUPERVISOR: I did save the report without changing anything on the spreadsheet on 3/30. Then tried to run the update on 4/2 using the report that was not changed. I saved it multiple ways. Did one with all three programs - HC, SNAP, CASH. Then saved each individually unchanged. I got the error on every report I tried. Snapshot of error is attached. *** Are we missing a step in running this script?
![update eomc list script error](https://cloud.githubusercontent.com/assets/10159901/14325064/2d1c2dd6-fbed-11e5-95b3-0c5e7f5c0ebd.jpg)

**Comment by courtrightd** [comment]
What version of Bluezone are you running?  There may be a compatibility problem that we are working on a fix for.

**Comment by theVKC** [comment]
@courtrightd - any insight for Amanda? Runtime error seems like maybe BrowseForFile bug?

**Comment by courtrightd** [comment]
That's what I'm thinking - is your new version tested on v.6 yet

**Comment by theVKC** [comment]
I think @C-Love might have tested my new function on 6. Casey, is this true?

**Comment by ALJ10** [comment]
Thank you for the quick responses! We're running v5.1C2 Build 1325

**Comment by IlseFerris** [comment]
Casey's offline today, can someone from Stearns county confirm?

**Comment by theVKC** [comment]
Well, if you're running v5x, I'm a bit confused by this.

We noticed a bug in the BrowseForFile function (bug is #2008) which I've fixed in the new training case creator script, and I'm awaiting confirmation that it's working before fixing this bug in other scripts, including this one.

@ALJ10: are you able to select the Excel file in your script? Or does it error-out on startup?

**Comment by ALJ10** [comment]
Per the supervisor, she was able to select the spreadsheet. It opens and adds the column (case active?). Looks like it's going to run, but then it stops and gives her the error.

**Comment by courtrightd** [comment]
Any chance you could send me the excel file, or at least a screenshot of the first 20 lines or so?

**Comment by theVKC** [comment]
Via email, please. #DataPrivacy

**Comment by ALJ10** [comment]
Yes, I can send it via email. To whom should I email it to?

**Comment by courtrightd** [comment]
courtrightd@stlouiscountymn.gov I'll work on it this afternoon.

**Comment by ALJ10** [comment]
Just sent it. Thank you!

**Comment by GayS** [comment]
we also encountered the error at Stearns.

**Comment by courtrightd** [comment]
I'm seeing it now, it has to do with not finding a value in HC / GRH cols, I'll work on a fix this afternoon.

**Comment by theVKC** [comment]
@courtrightd: would this count as critical? Can this be bypassed in any way? Or will this happen each time it's run?

**Comment by courtrightd** [comment]
It can’t be bypassed, so I would say critical.  It will happen most times it is run. (it currently only works on spreadsheets with a GRH column)

**Comment by theVKC** [comment]
OK, it's now critical. Can you pull to release as well?

**Comment by ALJ10** [comment]
I just ran the script and it worked. Thank you for resolving the issue so quickly! Much appreciated!
