### ISSUE TITLE
New ACTION script: MFIP housing grant MONY/CHCK issuance 

### ISSUE THREAD

**Issue by IlseFerris** [MN-Script-Team/DHS-MAXIS-Scripts#2081]
THE SCRIPT WILL DO THE FOLLOWING:
1.	Navigates to MONY/INQX and creates a list of MFIP issuances within the current year. 
2.	Searches the MFIP issuances for Housing grant issuances that match the footer month/year selected by the user. If an issuance is not found, the script will continue to step 3. 
3.	Navigates to ELIG/MFIP and reads the EMPS status, member code, cash portion and state portion codes for the MONY/CHCK, and checks if the case is in sanction, and that $110 is the housing grant amount listed on ELIG/MFSM. If case in not a sanction, and the housing grant amount is $110, the script will continue to step 4.
4.	Navigates to MONY/CHCK for the selected footer month/year, and creates an issuance for the housing grant of $110 (using coding from ELIG/MFIP). 
5.	Enters the applicable verbiage on the ‘restoration of benefits’ screen in the MONY/CHCK function per the Housing grant bulletin (#15-68-06C issued on 06/01/15). 
6.	Creates a CASE/NOTE to record the case action.

On the eve of the April MFIP Housing grant list being issued on SIR, I've got this!

**Comment by theVKC** [comment]
By chance have you been testing this in the State of Hennepin, @IlseFerris?

**Comment by IlseFerris** [comment]
Oh I have, and not to toot my own horn, but it's pretty awesome. Average time savings per issuance is over 4 minutes.
