### ISSUE TITLE
Housing grant fiater needs to be removed

### ISSUE THREAD

**Issue by IlseFerris** [MN-Script-Team/DHS-MAXIS-Scripts#2083]
Assign to me to be complete for the April release.

**Comment by CDPotter** [comment]
I'm working on modernizing actions main menu so I can knock this out as part of it.

**Comment by theVKC** [comment]
@IlseFerris, I'm reassigning to @CDPotter,

**Comment by IlseFerris** [comment]
Good deal, thanks @CDPotter!
