### ISSUE TITLE
NOTES - RETURNED MAIL RECEIVED: needs dialog item variables renamed

### ISSUE THREAD

**Issue by theVKC** [MN-Script-Team/DHS-MAXIS-Scripts#2091]
@StormageddonDLOA: the dialog items are "Check1", "Check2", etc.. Those should be renamed to follow standards (something like `something_something_checkbox`), as well as any other dialog variables.

Can you work on this for Monday's hackathon really quick? That'd be greatly appreciated.

**Comment by StormageddonDLOA** [comment]
Sure.
