### ISSUE TITLE
Add REVW dates to the LTC-GRH list gen

### ISSUE THREAD

**Issue by IlseFerris** [MN-Script-Team/DHS-MAXIS-Scripts#2097]
Hennepin County supervisor has asked for a REVW date column be added to the LTC-GRH List gen. I think it would be helpful to those users, so I can take this unless someone else wants it.

**Comment by theVKC** [comment]
Tagging this with the May release since April is a shorter release month. If someone can get it done by Friday we can add it to the April release instead. Marked as help wanted. Thanks @IlseFerris!

**Comment by IlseFerris** [comment]
So my bad, made this an issue before looking into the issue myself. Users of the LTC GRH list have the option to select to create the list from REPT/REVW which would eliminate the need to have this option. #CalmDown
