### ISSUE TITLE
New script: UPDATE SCRIPTS

### ISSUE THREAD

**Issue by theVKC** [MN-Script-Team/DHS-MAXIS-Scripts#2101]
Here's what it should do:
- Check if you have read/write access to Global Variables
- If you have read/write, show a dialog with all of the Global Variables settings
- Based on user selection, update Global Variables file
- Encourage user to test scripts
- Allow users to add new variables (variable name) and the default value(s) for that variable.
- Grabs newest Power Pad if a new one is available (use last_updated_date for that)
- Grabs new redirect files if new ones are available (use last_updated_date for that)

---

At one point this was going to be a standalone script, but now it's going to be a function used in PRISM as well. https://github.com/MN-Script-Team/BZS-FuncLib/issues/279. As such, this "script" is pretty much going to be a FuncLib call and a reference to an update_scripts function.

@CDPotter, I'll let you know when it's been deployed in PRISM. If you'd like, I can pull an identical script here as well (identical since we're all going to the same function).

**Comment by RobertFewins-Kalb** [comment]
Ooooooooo...I like this. A lot. This would come in very handy for Child Support as we develop our GlobVar. Request:

- [ ] Allow users to add new variables (variable name) and the default value(s) for that variable.

**Comment by theVKC** [comment]
I like it.

**Comment by theVKC** [comment]
I've improved the scope to include updating Power Pads and redirect files. This means the script will now simply be called "UPDATE SCRIPTS". This enhanced scope is likely beyond the June release, but I will try.

**Comment by theVKC** [comment]
I am working on this as we speak, folks.

https://github.com/MN-CS-Script-Team/PRISM-Scripts/issues/450

Hoping for this week on it.

**Comment by CDPotter** [comment]
Progress! 
![global variable updater](https://cloud.githubusercontent.com/assets/7841989/18388728/60c165fc-7668-11e6-8244-161ae210d3c6.PNG)

Any comments or suggestions? I'm pondering if I should remove the ability to edit the default filepath/run locally. In my mind anyone who would want to change to settings should be able to manually edit the global variables file.

**Comment by theVKC** [comment]
I agree: run locally and default file path should not be included. That stuff is for scriptwriters getting experimental and should be reasonably hidden from average users.

**Comment by theVKC** [comment]
Per our discussion this morning, I'll add this to my to-do to work with the downloading of the Power Pad. Thanks for swapping some work with me @CDPotter!

**Comment by C-Love** [comment]
This appears to be completely irrelevant with the conversion as all of this will be handled differently. Global Variables, PowerPads, etc will not exist in the new process. Closing.
