### ISSUE TITLE
Enhancement -- Modify display in GA/RCA into SNAP report

### ISSUE THREAD

**Issue by RobertFewins-Kalb** [MN-Script-Team/DHS-MAXIS-Scripts#2104]
Check SNAP for GA/RCA currently reads the GA amount from the "Grant Amount" field. A request has been made the to split the output into 4 columns (currently 1). I think the original idea to pull from Grant Amount had to do with catching adjudicated fraud (the only time we would not budget net). I have been informed that adjudicated fraud with GA is not frequent. 

The four columns for the output would be Review Case? (if issuance amount = budgeted amount THEN no, ELSEIF issuance amount <> budgeted amount THEN yes ELSEIF review month = TRUE then "REVW MONTH" and no budget information),  "Grant Amount" (for GA...not sure what to do about RCA), "Amount Issued" and "Amount Budgeted". 

I can take it.

**Comment by theVKC** [comment]
Is this getting done by Friday, @RobertFewins-Kalb?

**Comment by RobertFewins-Kalb** [comment]
yes

**Comment by theVKC** [comment]
Wonderful! Thank you!
