### ISSUE TITLE
NOTICES - NOMI: Hennepin County office hour for NW region needs to be udpated

### ISSUE THREAD

**Issue by IlseFerris** [MN-Script-Team/DHS-MAXIS-Scripts#2108]
assign to me for the April release please

**Comment by theVKC** [comment]
@IlseFerris: I thought that pull request I brought in fixed this. Can you confirm this is fixed in master?

**Comment by IlseFerris** [comment]
It was confirmed that it changed again. I will submit this update this morning.

**Comment by theVKC** [comment]
Are they changing it a bunch? Or just giving incorrect info?

**Comment by IlseFerris** [comment]
The office hours on the website were wrong. They don't change often at all.
