### ISSUE TITLE
New script: ACTIONS - ASSET PANEL UPDATER

### ISSUE THREAD

**Issue by theVKC** [MN-Script-Team/DHS-MAXIS-Scripts#2109]
This new script should update asset panels, based on changes reported or new information at intake. This is part of the ongoing Project Bowie.

Any takers? Could be a simple way to add some ACTIONS scripts to your repertoire!

**Comment by theVKC** [comment]
Moving this to the June release @StormageddonDLOA to go along with the update to Project Bowie (which was also moved to June).

**Comment by IlseFerris** [comment]
Hey @StormageddonDLOA, let me know if you need me to take a look at your script again. I'd be happy to :)

**Comment by StormageddonDLOA** [comment]
Just need to make a few tweaks then I think it’s going to be good to go.
Unfortunately due to being on phones and understaffed I haven’t had time to make those changes yet. ☺

**Comment by IlseFerris** [comment]
Good deal, just let me know if you need anything.
