### ISSUE TITLE
Dialog Name Change for Project Bowie

### ISSUE THREAD

**Issue by C-Love** [MN-Script-Team/DHS-MAXIS-Scripts#2110]
Review all of the following scripts:

- [x] Actions - New Job Reported
- [x] Actions - Send SVES
- [x] Notes - AREP Form Receivied
- [x] Notes - Baby Born
- [ ] Notes - Change Report Form Received
- [x] Notes - Deceased Client Summary
- [x] Notes - HH Comp Change
- [x] Notes - Incarceration
- [x] Notes - LTC - 1503
- [x] Notes - LTC - 5181
- [x] Notes - Pregnancy Reported
- [x] Action - ABAWD FSET Exemption Checker
- [x] Notes - Verifications Needed

Need to determine if there is more than one dialog defined within the script. If there is then the dialog needs to be changed and it also needs to be moved to be defined in line with the code - right before the dialog.

I am doing this.

**Comment by theVKC** [comment]
@C-Love, can I get an update on this one? I'm holding up on my remaining Bowie work waiting for this to be wrapped up.

**Comment by C-Love** [comment]
I am getting this up today. I am determined.

**Comment by theVKC** [comment]
I believe in you!! :)
