### ISSUE TITLE
New Bulk Script - MAXIS HC Non-MAGI Persons/Cases

### ISSUE THREAD

**Issue by ramonalisa1** [MN-Script-Team/DHS-MAXIS-Scripts#2112]
With the migration of MAXIS cases into METS starting with July 2017 HC ERs, we are looking at moving some cases around.  I would love a script that could be run on X1 numbers that would go through a caseload, check if the person is active on MA, coded as AA, AX, CB, CK or CX and check that the person has no spenddown.  If so, it would push that info to a bulk Excel spreadsheet so that we can determine how many persons/cases will be migrating and move cases accordingly. It would be nice if the script would also include their next HC ER date from the STAT/REVW panel.

**Comment by LaLarson** [comment]
@RobertFewins-Kalb Could you send Lisa the information you sent Meridee?

**Comment by RobertFewins-Kalb** [comment]
It sounds like there's a lot of demand for the script. How's about I just submit a new script to the BULK list menu?

**Comment by ramonalisa1** [comment]
Whatever you can do would be great!!  We can find no way or not report that exists currently that will pull this specific information from MAXIS.

Lisa M.
Financial Assistance Supervisor

P
Please consider the environment before printing this email.

CAUTION:  This e-mail and attached documents, if any, may contain information that is protected by state or federal law.  E-Mail containing private or protected information should not be sent over a public (non-secure) Internet unless it is encrypted pursuant to DHS standards.  This e-mail should be forwarded only on a strictly need-to-know basis. If you are not the intended recipient, please:  (1) notify the sender immediately; (2) do not forward the message; (3) do not print this message; and (4) erase the message from your system.

USDA is an equal opportunity providers and employer.

**Comment by theVKC** [comment]
@RobertFewins-Kalb: want to try and release it in April? Or should we wait until May?

**Comment by RobertFewins-Kalb** [comment]
I'll get it done this week

**Comment by ramonalisa1** [comment]
You rock!!  Thanks, Robert! ☺

Lisa M.
Financial Assistance Supervisor

P
Please consider the environment before printing this email.

CAUTION:  This e-mail and attached documents, if any, may contain information that is protected by state or federal law.  E-Mail containing private or protected information should not be sent over a public (non-secure) Internet unless it is encrypted pursuant to DHS standards.  This e-mail should be forwarded only on a strictly need-to-know basis. If you are not the intended recipient, please:  (1) notify the sender immediately; (2) do not forward the message; (3) do not print this message; and (4) erase the message from your system.

USDA is an equal opportunity providers and employer.

**Comment by RobertFewins-Kalb** [comment]
@theVKC, this is going to be a single pull request with multiple commits. I'll let you know when I have it all ready.

**Comment by ramonalisa1** [comment]
Thanks again!

Lisa M.
Financial Assistance Supervisor

P
Please consider the environment before printing this email.

CAUTION:  This e-mail and attached documents, if any, may contain information that is protected by state or federal law.  E-Mail containing private or protected information should not be sent over a public (non-secure) Internet unless it is encrypted pursuant to DHS standards.  This e-mail should be forwarded only on a strictly need-to-know basis. If you are not the intended recipient, please:  (1) notify the sender immediately; (2) do not forward the message; (3) do not print this message; and (4) erase the message from your system.

USDA is an equal opportunity providers and employer.

**Comment by ramonalisa1** [comment]
Robert, in thinking about this script, there are two MAGI elig types that DHS is still unsure when/how will migrate into METS.  Those are PX and 11.  We will need to run this report at some point, but I am wondering if in the dialog box we should give an option of checking which elig types for which we would like to run the report, i.e. check boxes for PX, 11, AA, AX, CB, CK, CX so we can customize the report a bit.

Lisa M.
Financial Assistance Supervisor

P
Please consider the environment before printing this email.

CAUTION:  This e-mail and attached documents, if any, may contain information that is protected by state or federal law.  E-Mail containing private or protected information should not be sent over a public (non-secure) Internet unless it is encrypted pursuant to DHS standards.  This e-mail should be forwarded only on a strictly need-to-know basis. If you are not the intended recipient, please:  (1) notify the sender immediately; (2) do not forward the message; (3) do not print this message; and (4) erase the message from your system.

USDA is an equal opportunity providers and employer.

**Comment by theVKC** [comment]
Can I get an update on this @RobertFewins-Kalb? Do you think it'll be done by Friday (the due-date for the next release enhancements)? Thanks!

**Comment by RobertFewins-Kalb** [comment]
Yes but probably not with consideration for the issues raised by @ramonalisa1. I could simply include the eligibility bases to the output and let users filter the Excel spreadsheet based on that.

https://www.google.com/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=filtering%20excel%20spreadsheet 

This is where the comment section is going to turn into a Country Time Lemonade commercial... The script was conceived at a simpler time (when who was and was not going into MNsure...now METS) wasn't so complicated.

**Comment by theVKC** [comment]
Well want I should close it, Robert? We can call it a sleeper or move it to the June release. I'm trying to reduce the issue list here. Poking all the bears.

**Comment by RobertFewins-Kalb** [comment]
I've been working on it. I'm thinking about releasing what we have and then working on an update for June. This has proved to be quite useful with conversion looming...

**Comment by theVKC** [comment]
I agree. Go forth, please and thank you!

**Comment by theVKC** [comment]
Per @RobertFewins-Kalb this isn't going to be live this month. Moving to the June release.

**Comment by theVKC** [comment]
Can I get an update on where this is at @RobertFewins-Kalb? Looking to close a few issues in the next week. If you don't think this will be doable we can mark it as a sleeper issue and we can revisit it at a later date.
