### ISSUE TITLE
Enhancement: Denied Progs 30 day reinstate check box verbiage

### ISSUE THREAD

**Issue by CDPotter** [MN-Script-Team/DHS-MAXIS-Scripts#2114]
We are again getting users checking this box for cases where interviews weren't conducted. It currently reads:

Check here if proofs were not provided and this case pended the full 30 day period (or 45/60 days for HC). Applies a 30 day reinstate period. 

Maybe we could adjust it to:

Check here if requested progs were not provided, interview was completed and the case pended for the full 30 day period (or 45/60 days for HC). Applies a 30 day reinstate period. 

Nitpicking I know but thoughts?

**Comment by theVKC** [comment]
Sounds fine to me. Want it?

**Comment by CDPotter** [comment]
Sure, I can knock it out quickly.
