### ISSUE TITLE
LTC 5181

### ISSUE THREAD

**Issue by StephanieW7** [MN-Script-Team/DHS-MAXIS-Scripts#2118]
Hi,
We are noticing an error on the LTC 5181 Script under the NOTES Script section.  On the third dialog box - where you check the box for Sent 5181 back to Case Manager.  When this box is checked it does not add into the case note the 5181 was sent back to the Case Manager.  
Thanks,
Stephanie W
X171601

**Comment by theVKC** [comment]
Hi @StephanieW7! Is this happening for more than one user?

Any LTC scriptwriters want to take a look at this?

**Comment by IlseFerris** [comment]
Confirmed as an issue. I can submit the fix.

**Comment by theVKC** [comment]
Think you can get it for the April release, @IlseFerris?

**Comment by IlseFerris** [comment]
Yes pull I will pull it in momentarily
