### ISSUE TITLE
Enhancement: Modernize NOTES - LEP SAVE 

### ISSUE THREAD

**Issue by CDPotter** [MN-Script-Team/DHS-MAXIS-Scripts#2127]
Had a user today report he got a message instructing him to navigate to case note and PF9 before this script could case note. Looking at code this script needs a face lift. If anyone wants to get their feet wet in modernizing a script let me know by tomorrow otherwise I'll tackle this one and submit.

**Comment by CDPotter** [comment]
Pre-funclib!!! It's like an archeological dig!

![subs](https://cloud.githubusercontent.com/assets/7841989/14543985/52eed4f8-025c-11e6-96ee-f6482b42e009.png)

**Comment by theVKC** [comment]
Oh, 2011 Veronica. The things I wish I could tell you.

**Comment by CDPotter** [comment]
Added safety measures, error message handling, and still cut 30 lines of code! Want me to pull or wait for next release?

**Comment by theVKC** [comment]
Kicked this back to April since @CDPotter pulled it in and I haven't finalized the release just yet. Doing that now.
