### ISSUE TITLE
FIND UPDATE PANELS enhancement

### ISSUE THREAD

**Issue by IlseFerris** [MN-Script-Team/DHS-MAXIS-Scripts#2130]
Hennepin County supervisors have requested that PARE and PBEN panels be updated to the list of case criteria to search. This enhancement will help improve inconsistencies in CASH programs, and target cases for review that have recently been updated.

**Comment by RobertFewins-Kalb** [comment]
Add AREP and SWKR as well?

**Comment by theVKC** [comment]
@IlseFerris: do you want this one?

**Comment by IlseFerris** [comment]
We could add AREP and SWKR if there is a need. Has this been requested?
Also I can take it unless someone else has a burning desire.

**Comment by CDPotter** [comment]
Yes It's been on Robert and I's plate for sometime but kept getting pushed aside. WREG was also included on that request if it's not already an option.

**Comment by IlseFerris** [comment]
WREG is not an option yet. I'll add it.
