### ISSUE TITLE
Note - PND MSA

### ISSUE THREAD

**Issue by rhondahines** [MN-Script-Team/DHS-MAXIS-Scripts#2132]
It is our understanding when someone is approved for GA and applying for SSA benefits we are supposed to ‘PEND MSA’ by entering a case note.  So, if/when SSA benefits approved, if other elig criteria is met, MSA can be issued back to that date.
*
Could a script be done to make this easier for financial workers to remember to do this?

**Comment by theVKC** [comment]
Anyone interested? @MN-Script-Team/county-agency-scriptwriters?

**Comment by CDPotter** [comment]
It's for sure not a practice we do here at Anoka. Wouldn't that mean issuing MSA and GA overlapping?

**Comment by theVKC** [comment]
@rhondahines, can you confirm a policy citation for this, perhaps POLI/TEMP or a PQ? I only represent SNAP policy, my info on MSA is admittedly outdated.

**Comment by Farleight** [comment]
I have no policy citation, but there are definitely instructions out there for how to do a GA/MSA conversion, which include going back 10 months to issue MAXIS benefits and manually calculating anything beyond that time. Seems to me if we're supposed to be pending MSA, those instructions wouldn't really exist, or would at least make reference to "this is what you do in the case of complete failure to follow the real rules." This pending MSA thing sounds like a lone county trying to get creative... but my instincts have been wrong before... 7 times.

**Comment by KateiMartini** [comment]
I actually have a manual on this topic.  Wash Co. is huge on Interim Assistance.  I am not in the office today but I can share a copy of the manual tomorrow once I am back in office.

**Comment by theVKC** [comment]
I'm leaving the issue up for now, I'd love if someone could get a definite citation for this process one way or another.

**Comment by theVKC** [comment]
If there's no definite citation in one week (April 25), I'll close the issue.

**Comment by rhondahines** [comment]
According to the MSA workbook posted in the Training Toolkit (MSA Library) on SIR

Page 77 it says:



GA with MSA Pending

The last system piece that needs to be covered is the process of opening a pending MSA case.

When GA is opened under the category of permanent disability MSA is pended. This is not initially done on CASH II on the PROG panel. To pend MSA in this situation a case note is entered. It is from this case note that we can determine the begin date of eligibility for MSA once SSI has been approved.

Note: For instructions on how to pend MSA while opening a GA case, see POLI/TEMP TE02.10.46.

There are separate instructions for processing MSA, when a GA client gains SSI eligibility, depending upon how many months ago the application was taken. Due to current system limitations the initial cash approval package cannot contain more than 12 months.

For applications taken within the past 10 months, close GA and determine MSA eligibility by completing the following procedures in MAXIS:

·        It then lists 13 steps that need to be taken to close GA and determine MSA elig in MAXIS.

TE 02.10.56 has procedures for when the client gains SSI elig when initial appl is more than 10 months old.



Let me know if there is further information you’d like.  Thanks!



Rhonda Hines
Human Services of Faribault & Martin Counties
Financial Assistance Supervisor

**Comment by KateiMartini** [comment]
[IAA Conversion Processing 4.15.docx](https://github.com/MN-Script-Team/DHS-MAXIS-Scripts/files/224536/IAA.Conversion.Processing.4.15.docx)

**Comment by theVKC** [comment]
"To pend MSA in this situation a case note is entered. It is from this case note that we can determine the begin date of eligibility for MSA once SSI has been approved."

Seems pretty clear to me. 

@KateiMartini: I glanced through your document and saw your document says to use the GA date? Or was I missing something. It's pretty long and I just used a Ctrl-F on it. :)

**Comment by Farleight** [comment]
Oh, interesting. I must have read the initial post incompletely. So all we're doing is a case note.That's logical, I guess. Not sure why it's necessary, but if the state says it, it must be true!

**Comment by theVKC** [comment]
If I'm remembering back to my adult-cash days... we did this because cash i/ii doesn't always stay consistent enough for tracking, MSA/GA gets putsy, and MAXIS doesn't track it well otherwise (there isn't an "MSA pending" field that I know of). The case note was the best bet. I remember doing it years ago. I didn't know it was still the process! Good to see it's consistent. :P

**Comment by theVKC** [comment]
@LaLarson is going to seek clarification formally. If this comes back as the current policy, she has volunteered to create the case note. Thanks @LaLarson!

**Comment by theVKC** [comment]
@LaLarson, since this is an ongoing policy question, and hasn't been resolved yet, I'm going to mark the issue as a sleeper issue and close it. If you get clarification back in about the policy, let's reopen it and do something about it.
