### ISSUE TITLE
Approved Progs needs error handling on banked months dialog

### ISSUE THREAD

**Issue by courtrightd** [MN-Script-Team/DHS-MAXIS-Scripts#2133]
Leaving number of months blank results in type mismatch error, stopping script.  I've got this after freeze is lifted.

**Comment by theVKC** [comment]
Could this be considered critical? It seems like it's a major inconvenience.

**Comment by courtrightd** [comment]
I suppose so, it does cause the script to break.  I didn't really consider it so simply because no one noticed it until now.  I'll work on it asap.

**Comment by CDPotter** [comment]
The script autofills in the month/year so the unless if something went goofy with that the users have to remove/alter the dates to hit this bug.

**Comment by courtrightd** [comment]
The problem is with the little box to the right of the initial month/year for number of months approved.  It defaults blank.  It looks like there is error handling there for month/year.

**Comment by CDPotter** [comment]
Aaaahhh! Got it! I missed that this was the banked month portion! Thanks for clarification!

**Comment by theVKC** [comment]
@courtrightd, any movement on this?

**Comment by courtrightd** [comment]
ETA tomorrow AM.

**Comment by theVKC** [comment]
Thank you!!

**Comment by courtrightd** [comment]
Should this be pulled to release as well?

**Comment by theVKC** [comment]
No, the new release is coming in a few days.
