### ISSUE TITLE
Enhancement - Approved Programs script ending at SPEC/WCOM

### ISSUE THREAD

**Issue by tdahl21** [MN-Script-Team/DHS-MAXIS-Scripts#2134]
Hey Everyone,

Since a lot of errors have been linked to incorrect notices, could we have the Approved Programs script leave a worker at SPEC/WCOM after the casenote has been ran?  Almost like when the Case Transfer script is ran and it leaves you at SPEC/XFER.  This would hopefully help people to double check notices more often.

Thanks for checking this idea out!

**Comment by theVKC** [comment]
I like the idea. Does anyone out there have any thoughts on it?

**Comment by asunderman** [comment]
I'll take a stab at this.

**Comment by theVKC** [comment]
Yay! Thanks @asunderman!

We're on a script freeze through Monday, so no new pull requests until Monday, unless they fix critical bugs in the new/updated scripts.

**Comment by tdahl21** [comment]
Thank you!

**Comment by theVKC** [comment]
Can I get an update on this @asunderman? Do you think it'll be done by Friday (the due-date for the next release enhancements)? Thanks!

**Comment by asunderman** [comment]
No, we’re in the process of scanning all our paper files and moving back to the courthouse from the barn.  No time for script writing right now.  Sorry…

**Comment by theVKC** [comment]
No worries @asunderman. I think I'll take this issue and pound it out, just to decrease the list by one more. :)

**Comment by theVKC** [comment]
@tdahl21: this is now live in the test branch. Expect to see it for real the Monday after next!
