### ISSUE TITLE
BULK - DAIL report enhancement: add option to select DAIL types

### ISSUE THREAD

**Issue by IlseFerris** [MN-Script-Team/DHS-MAXIS-Scripts#2136]
Hennepin County supervisor requested to have users be able to select the DAIL type for the report. Turns out that Ramsey was looking for the DAIL report to filter out the IEVS notices. 
Assign to me for the May release.

**Comment by RobertFewins-Kalb** [comment]
Are we assuming that filtering an Excel file is beyond the capacity of most users?


NOTICE: Unless restricted by law, email correspondence to and from Anoka County government offices may be public data subject to the Minnesota Data Practices Act and/or may be disclosed to third parties.

**Comment by IlseFerris** [comment]
Yes, users can filter the list, but I think having options for the users encourages the use of the BULK scripts.

**Comment by theVKC** [comment]
@RobertFewins-Kalb, I said the same thing initially, but I came around. It's like a nav script... Not everyone will need it, but those who do will love it.

**Comment by RobertFewins-Kalb** [comment]
Just being snarky :)


NOTICE: Unless restricted by law, email correspondence to and from Anoka County government offices may be public data subject to the Minnesota Data Practices Act and/or may be disclosed to third parties.
