### ISSUE TITLE
MFIP orientation memo: Goodhue County had an address change

### ISSUE THREAD

**Issue by theVKC** [MN-Script-Team/DHS-MAXIS-Scripts#2138]
They have moved from 469 12th Street to their old (now permanent) address of 426 West Ave, Red Wing, MN.

Any takers??

**Comment by LaLarson** [comment]
I shall try! It seems only fitting! Can I do it on Monday at Hackathon? :)

**Comment by theVKC** [comment]
Fantastic!

**Comment by LaLarson** [comment]
This is resolved... I emailed Goodhue and they are going to need to manually update their global variables. :)
