### ISSUE TITLE
NOTICES - MFIP ORIENTATION needs address list added

### ISSUE THREAD

**Issue by courtrightd** [MN-Script-Team/DHS-MAXIS-Scripts#2140]
Currently pulls address info from Global Variables, which is no longer supported.  An address list will be added to the script itself similar to current Appointment letter script.  I have this.

**Comment by theVKC** [comment]
It actually pulls from Global Variables, not FuncLib. Good luck!

**Comment by theVKC** [comment]
Can I get an update on this @courtrightd? Do you think it'll be done by Friday (the due-date for the next release enhancements)? Thanks!

**Comment by courtrightd** [comment]
Yes, I'll be finishing it up tomorrow.
