### ISSUE TITLE
BULK - Determine INAC Date & Reason

### ISSUE THREAD

**Issue by LaLarson** [MN-Script-Team/DHS-MAXIS-Scripts#2144]
Please assign to the LaLa!

**Comment by theVKC** [comment]
@LaLarson, we have this marked for June. I need to keep the issue list up-to-date.

If you don't think you can get it done by Friday (the deadline for new June scripts) but you think it can be done by next month, I'll keep the issue open. If it can be done by Friday, I'll keep it tied to the June release. If you can't give an ETA (or if I don't hear by Friday), I'll mark the issue as a sleeper issue and close it.

I'd appreciate an update on it! Thank you!!

**Comment by LaLarson** [comment]
Hi!

Okay, this is that one that turned very cash/Olmstedy-ish... I would say lets move it to July, and give me one more chance to make it more universal again. I would try to work on it before Friday, but I was sick last week, and now I'm buried in my other work.

**Comment by theVKC** [comment]
No worries @LaLarson, thanks for the update!

**Comment by theVKC** [comment]
I know you missed last hackathon, @LaLarson... think this will get done this month? Otherwise I'm going to have to close it. We can always reopen it if you have an opportunity again.

**Comment by theVKC** [comment]
Per @LaLarson, this is not going to be done this month. Marking as a sleeper issue and closing.
