### ISSUE TITLE
New Script - Banked Months Report to DHS 

### ISSUE THREAD

**Issue by C-Love** [MN-Script-Team/DHS-MAXIS-Scripts#2146]
New Utilities script that will take an initial list of clients and create the DHS report as requested. This script will do some checking of possible exemptions and check elig. It will then create the list for DHS based on the spreadsheet that were provided by DHS. It will also create a separate list of clients that were not added to the DHS report and why. These reports and month checking will all be report month specific. 

@IlseFerris  and I have been working on this and have it mostly done. We plan to pull it in this week.

**Comment by theVKC** [comment]
I think this sounds like a bulk script and not a utilities script. Utilities scripts don't work with real data.
