### ISSUE TITLE
New Script MA Inmate Application WCOM

### ISSUE THREAD

**Issue by CDPotter** [MN-Script-Team/DHS-MAXIS-Scripts#2148]
Per ONESource http://hcopub.dhs.state.mn.us/onesourcestd/Process_DHS_6696_Incarceration_No_Sup.htm #7 first bullet first sub bullet. 

We should be adding "MA Begins (release date), the date you are released from the correctional facility."

The issue came about because a worker wanted the HCAPP to note the correctional facility FACI panels with end dates (currently if it finds end dates it ignored the panel). I thought it would be good to tackle this in a separate script rather than altering the function shared by so many other scripts.

This script would start with a custom one person HH member dialog(seen in other scripts), read FACI, compare dates, find the most recent end date of FACI panels with 68 (county correctional) codes and take that to be the release date and display it with a message box to confirm it is correct, finally navigating to SPEC/WCOM finding the HC notice, writing the WCOM and Case noting the information. 

**WCOM**
MA begins mm/dd/yyyy, the date you are released from the correctional facility

**CASE NOTE**
MA Inmate Application Approval WCOM
MA Start Date: mm/dd/yyyy
Incarceration End Date: mm/dd/yyyy
Facility Name: facility
WCOM added

Worker_signature

I would like to be assigned to this one.

**Comment by theVKC** [comment]
Thanks @CDPotter!
