### ISSUE TITLE
New script idea Other program eligibility MEMO (call for input)

### ISSUE THREAD

**Issue by CDPotter** [MN-Script-Team/DHS-MAXIS-Scripts#2153]
MEMO script where worker  can notify client of potential eligibility for SNAP, CASH, MSA, MA. So for example you're doing a MA renewal and you spot a client with $733 living alone and you want to send a letter letting them know they may be eligible for SNAP/MSA. 

Only downfalls I see are, why wouldn't we just send it on letter head alongside an application? and we'd probably have to put a generic address/phrase as to where to apply/get application as we don't want to restrict where people can apply so "You can get a paper application mailed to you or at your local County/Tribal Agency."

Thoughts? I wanted to get a gauge for interest in this idea. 

(Assign to me)

**Comment by C-Love** [comment]
I really appreciate this idea. It happens a lot to me where I am trying to alert clients to other programs. I do really wish there was a 'Send CAF' option in SPEC/LETR to support this but it would be a good start.

**Comment by CDPotter** [comment]
Agreed on the CAF things! Sadly we can just look longingly over the fence into PRISM land and their document generation abilities.

**Comment by RobertFewins-Kalb** [comment]
It's turbo great

**Comment by Y-Lor-Y** [comment]
I like the idea.  Some clients may not want to apply for the  other benefits and etc, that not sending a CAF might overall be a better option.  But having resources within the memo would be great.  Such as online option, phone request info if they're interest, in-person request info, other sites info, or generic info sites of these programs for them.

**Comment by courtrightd** [comment]
Should it have language reminding of the importance of CAF1 to set application date?

**Comment by CDPotter** [comment]
I like that! So maybe something like "When applying for SNAP and/or CASH you can submit the first page of the paper application to set your date of application. Your first month's benefit will be determined based on your application date."
