### ISSUE TITLE
Notes - Expedited Determination error encounter

### ISSUE THREAD

**Issue by Y-Lor-Y** [MN-Script-Team/DHS-MAXIS-Scripts#2154]
Hi, One of my staff on the floor encounter this error when using the expedited determination error:

Script Error at line 1, column 1:
Type mismatch: '[string: ""]'

Looking at where/when this error prompt, during when it runs the PNLP (if I remember correctly, either the incomes or abps).

If this is already a known error (somehow I have a feeling this is a known issue with string value " ").

Thanks,

**Comment by CDPotter** [comment]
Do you know what they were doing when they hit the error? Where in the script did it occur, what variables did they enter/not enter?

**Comment by C-Love** [comment]
I just got an error report on this on Tuesday and I have it on my list to look at. I am pretty sure the issue is in looking at PNLR after the case number dialog happens. I will look now.

**Comment by C-Love** [comment]
Found it! That was totally my bad - no clue how I missed it. Basically I hardcoded in a number for a row to read on a loop. Yikes. I am testing the fix right now, then I will pull it in.
