### ISSUE TITLE
Enhancement: BULK REVW/MONT closures Add GRMR?

### ISSUE THREAD

**Issue by CDPotter** [MN-Script-Team/DHS-MAXIS-Scripts#2158]
So apparently there's a REPT/GRMR screen that contains GRH HRF renewals (basically MONT for GRH) the script currently misses all these renewals if they are incompleted (apparently very rare as most facilities like to be paid).

I was thinking it would be a simple enhancement to add this screen. The case note would probably be the same as the MONT one? Anyone with more GRH experience want to help check verbiage with me?

(assign to me)

**Comment by IlseFerris** [comment]
I can help out with this one. It's been a while since I've been in GRH, and haven't necessarily used REPT/GRMR, but I'll help however I can :)

**Comment by CDPotter** [comment]
@theVKC Also do you have any info on when GRH HRFs will be going away?

**Comment by theVKC** [comment]
None.

**Comment by CDPotter** [comment]
Closing as GRH is reported to move to 6 month reporting very shortly. Per worker who suggested it was a very small subset who appeared on this last at the end of the month anyway.

**Comment by theVKC** [comment]
Thanks @CDPotter!
