### ISSUE TITLE
Enhancement: NOTES - LEP SAVE allow multiple runs

### ISSUE THREAD

**Issue by CDPotter** [MN-Script-Team/DHS-MAXIS-Scripts#2165]
A worker commented it was a bit annoying to be unable to run the scripts for multiple users. Since we could see this getting resolved by the workflow we thought maybe a temporary solution would work.

The solution being adding a custom HH dialog so workers can select what users to note/TIKL and then wrap the noting/tikling in a for/next. 

Thoughts?

**Comment by theVKC** [comment]
I think we should avoid this because workflow potentially makes it obsolete. I'd really rather not spend time or resources changing it just to potentially change it back.

**Comment by CDPotter** [comment]
Fair enough, closing it!
