### ISSUE TITLE
SNAP E & T enhancement: add 'other manual referral' option

### ISSUE THREAD

**Issue by IlseFerris** [MN-Script-Team/DHS-MAXIS-Scripts#2174]
Hennepin County QI team has requested that an 'other manual referral' option be added to the script. I think it's a good enhancement, especially for this team, since they are heavily reviewing SNAP. 

Assign to me for May release.

**Comment by theVKC** [comment]
Are you thinking county-specific? Seems like it could be logical to include for everyone.

**Comment by IlseFerris** [comment]
Agreed, I created the option for all users (Hennepin, automated and manual). It's in the pull request :)
