### ISSUE TITLE
New Hire message (new hire name <> MAXIS name)

### ISSUE THREAD

**Issue by CDPotter** [MN-Script-Team/DHS-MAXIS-Scripts#2179]
So a coworker and myself both had issues this month where we failed to notice that the newhire message was for someone with a different name than the MAXIS name of the person with that SSN. My case was a switch of the SSN number (likely the new employee's mistake) while someone else had completely different SSN numbers. 

I was thinking it might be good to compare the two strings and prompt the user if they don't match, allowing them to stop or continue (to account for missing middle initials and spacing differences)

If this is good to go I will get started on it.

**Comment by theVKC** [comment]
I like the idea of a prompt. Go for it! Do you think it'll be done and tested by Friday? I suppose we're out of new hires.

**Comment by CDPotter** [comment]
I've actually cracked it already just poking at it a bit. 

Indeed we are, but I was able to test it on all of my case notes (luckily the new hire message portion I needed is copied over into the case note).

**Comment by theVKC** [comment]
You may have been able to test it, but I'm worried statewide we won't have enough testers. Please pull it in after release this month, so we can test it in early June. Thank you!
