### ISSUE TITLE
BULK / Update EOMC List ~ Discrepencies in accuracy of ACTIVE column

### ISSUE THREAD

**Issue by ALJ10** [MN-Script-Team/DHS-MAXIS-Scripts#2181]
A supervisor ran this script after the first of the month. She said she checked accuracy of the report and said it's about 50% compared to the actual program status in MAXIS. I ran it to see if I had the same results. I did not check all of them. But out of the first six cases that were listed as active, two of them were closed in MAXIS. If you would like some case #s to research, let me know who I should email them to.

**Comment by theVKC** [comment]
@courtrightd, I believe this was your script. Can you take a look?

**Comment by courtrightd** [comment]
I will take a look.  If you emailed me some case numbers to courtrightd@stlouiscountymn.gov that would be great.

**Comment by ALJ10** [comment]
David, I just emailed you a variety of case #s (SNAP, GA, MSA). Thank you!

**Comment by theVKC** [comment]
FYI @courtrightd, I just updated the BULK scripts with the new FuncLib block. If you've been working on this you might want to fetch upstream.
