### ISSUE TITLE
FosterCare HCAPP Issue

### ISSUE THREAD

**Issue by AimeePaxton** [MN-Script-Team/DHS-MAXIS-Scripts#2182]
We are having some issues with the foster care scripts. When our workers go into Foster Care HCAPP, everything comes across that they type in, but the Actions Taken Line. We have tried taking scripts off of bluezone and then re-establishing scripts and  completed the file save, but it is still not working. Any suggestions? We were told, a potential bug?

**Comment by RobertFewins-Kalb** [comment]
It looks like the actions taken variable was never written into the case note

**Comment by RobertFewins-Kalb** [comment]
Scratch that...it was renamed actions_taken in the dialog but not updated in the case note

**Comment by AimeePaxton** [comment]
What do we need to do here? I am new to all of this. Sorry & Thank you.

**Comment by RobertFewins-Kalb** [comment]
If you can gather the following ingredients, we can perform a sacred pull request ritual and pray the computer spirits will look favorably upon our request...

- [ ] bat's wing
- [ ] chicken's foot
- [ ] strand of curly, red hair
- [ ] garlic salt

**Comment by AimeePaxton** [comment]
Thanks! That made my Monday! I will see what I can do, but I am a little limited on the garlic salt…everything else maybe.

Aimee Paxton
Eligibility Worker
Mille Lacs County CVS
525 2nd Street S.E.
Milaca, MN 56353
P. 320-983-8208
F. 320-983-8306

**Comment by theVKC** [comment]
In all seriousness @AimeePaxton: Robert pulled in a fix, but it goes through our release cycle process, so you won't see it live for two weeks. That avoids a sticky situation called a "merge conflict" where too many changes in one area break the ability to send newly-tested-scripts live to everyone statewide.

Now, I need to see an alchemist about a bat wing.

**Comment by RobertFewins-Kalb** [comment]
Sounds like @AimeePaxton has everything but the garlic salt. I can provide that.

**Comment by AimeePaxton** [comment]
Thank you! That is greatly appreciated! You guys & gals are the best!
