### ISSUE TITLE
Actions- Case Transfer

### ISSUE THREAD

**Issue by lisaholker** [MN-Script-Team/DHS-MAXIS-Scripts#2192]
Several workers have questioned if this script sends the Spec/memo to the AREP or Social Worker on the case.
When a manual spec/memo is done you can select who you want to send it to but the script doesn't give that option.  
When we go back in after it's been done on cases that have AREP's it doesn't appear the spec/memo is being sent to the AREP.
Can this feature be added?  To select multiple recipients for spec/memo?

Thanks!  Lisa

**Comment by theVKC** [comment]
I believe this script originally came courtesy of @CDPotter and @RobertFewins-Kalb. Do either of you have a sense of this idea, and whether-or-not it is implemented? Why am I thinking it was asking?

**Comment by courtrightd** [comment]
It looks like this functionality isn't here in this script, but I put it into NOTES - APPOINTMENT LETTER, so could be added here.  Or maybe we should create a open_MAXIS_spec_memo(swrk, arep) function that would allow the desired outcome in all scripts.  Though that would be more work than copy / pasting into this script.

**Comment by RobertFewins-Kalb** [comment]
We could add that functionality to the out-of-county transfer MEMO. @courtrightd built that functionality for other scripts.

**Comment by RobertFewins-Kalb** [comment]
Hey, speaking of @courtrightd!

**Comment by theVKC** [comment]
I presume you mean NOTICES - APPOINTMENT LETTER. #SticklerForTheDetails :)

I don't think a function is really all that necessary at this junction. I'm open to suggestions on that. In any case, @courtrightd, am I assuming you're volunteering for this righteous task?

**Comment by courtrightd** [comment]
Yes, I will take this righteous task!  And skip the function for now.  I plan to just copy in just like the (insert category here) - APPOINTMENT LETTER script does it with automatically sending to arep / swkr if found (and marked to receive notices in stat), no user input.

**Comment by theVKC** [comment]
When might you have it done @courtrightd? Before Friday?

**Comment by courtrightd** [comment]
I'll shoot for that.

**Comment by theVKC** [comment]
Boom! @lisaholker, we're targeting our releases for the fourth Monday of each month. This means if Dave gets it built by Friday, it will be tested next week and will go out Monday, May 23.

**Comment by lisaholker** [comment]
Awesome- thanks so much for the quick response everyone! ☺

Lisa Holker
Financial Assistance Supervisor
Sherburne County Health & Human Services
13880 Business Center Dr.
Elk River, Mn. 55330
Phone: 763-765-4021 Fax: 763-765-4096
Sherburne County Health and Human Services values customer service and would like to hear from those who receive services from us about your most recent experience.  Please visit this link https://www.surveymonkey.com/r/SCHHS2015 to complete a quick survey.  Your assistance in completing this will help us improve internal efficiencies and the quality of services to Sherburne County residents.
Please disregard if you have already completed a survey in the last 90 days.  Thank you.

The information contained in this email is confidential information intended only the use of the individual or entity named above.  If the reader of this message is not the intended recipient, or the employee or agent responsible to deliver to the intended recipient, you are hereby notified that any dissemination or copying of this communication is strictly prohibited.  If you have received this communication in error, please notify us by responding directly to this email and destroy all information received immediately.

**Comment by theVKC** [comment]
I've also updated all of the ACTIONS scripts with the new FuncLib block, @courtrightd. :)
