### ISSUE TITLE
Add note to old MAIN MENU scripts instructing users to update their scripts

### ISSUE THREAD

**Issue by theVKC** [MN-Script-Team/DHS-MAXIS-Scripts#2193]
Three old MAIN MENU files are depreciated and should be deleted soon:

- [ ] NOTES 0-G
- [ ] NOTES H-Z
- [ ] MEMOS

We need to put in a `MsgBox` with a warning to users that these files will be obsoleted after the June release, so users should update their scripts.

Hennepin updates their Power Pad this week (hopefully Thursday). I'd like to time this update right after that point.

Scriptwriting counties: make sure your Power Pad is the updated one with a `UTILITIES` button in the top-right corner. @MN-Script-Team/county-agency-scriptwriters

**Comment by GayS** [comment]
If we don't have a power pad with "utilities" button on the top-right, do we need to rerun the installer?

**Comment by Farleight** [comment]
Rerun the most current installer. I had an old version on my desktop, but just updated today with the one on Github here and it worked fine... except that I had to reset some Global Variables that I had previously changed. (You may want to back up anything you think you may have manually updated like that)

**Comment by theVKC** [comment]
Precisely @Farleight! Yes @GayS, you should update. I saw your Power Pad yesterday and it needs to be updated again. This should be the last update until workflow scripts come in a few months.

**Comment by GayS** [comment]
is v1.4 the current installer?

**Comment by theVKC** [comment]
Use whatever's on the link in SIR at the bottom of the page.

**Comment by GayS** [comment]
@theVKC thanks

**Comment by theVKC** [comment]
@GayS, have you completed the update? If so, I'll get this one done right away. I have to do it tomorrow but would like to do it today.

**Comment by GayS** [comment]
@theVKC  - Yes I updated the installer last night so we are good to go! Thanks

**Comment by theVKC** [comment]
Wonderful! Yay!
