### ISSUE TITLE
Find panel update date update in master: remove person-based handling for PACT

### ISSUE THREAD

**Issue by IlseFerris** [MN-Script-Team/DHS-MAXIS-Scripts#2222]
PACT is the only case-based panel. Doesn't need all the HH member handling, it just slows it down.
Assign to me.

**Comment by IlseFerris** [comment]
I got #2222!

**Comment by theVKC** [comment]
Go you!

**Comment by theVKC** [comment]
Also, can you do this by end-of-day tomorrow?

**Comment by IlseFerris** [comment]
Done and done :)
