### ISSUE TITLE
Notices-Method B WCOM

### ISSUE THREAD

**Issue by KateiMartini** [MN-Script-Team/DHS-MAXIS-Scripts#2230]
There is a wording issue and a typo in this script.  
"Although your spenddown is $xxx your recipient amount the amount, or the amount"
"This is how the recipient amount is determined"  Recipient is spelled wrong.

**Comment by theVKC** [comment]
Want it @KateiMartini?

**Comment by KateiMartini** [comment]
Yes, I can try it.  It should be easy enough for me.

**Comment by theVKC** [comment]
Wonderful. Think you can get it done by tomorrow's release? If not, we'll make it a June issue.

**Comment by theVKC** [comment]
Can I get an update on this one @KateiMartini? It looks like you added your commit to your branch but didn't do the pull request step.

**Comment by theVKC** [comment]
@KateiMartini, I need an update on this one as well. :)
