### ISSUE TITLE
ACTIONS - Transfer Case

### ISSUE THREAD

**Issue by GayS** [MN-Script-Team/DHS-MAXIS-Scripts#2241]
We are getting an error indication that we are not in production exact wording: "You are not able to go into update mode. Did you enter in inquiry by mistake?  Please try again in production".  This was first reported last Thursday and others are reporting same issue today.

**Comment by courtrightd** [comment]
Are these users on master or release?  And what is the scenario (in county / out of county / memo to client, etc.)

**Comment by GayS** [comment]
They are on the master and transferring out of county.

**Comment by courtrightd** [comment]
I've been digging, but I can't replicate here, and the issue isn't obvious.  I made a bunch of updates on Thursday, but working here.  Any chance you can see what maxis looks like when the error happens? It has to be on SPEC/MEMO, but there may be an error msg on bottom missing case number, etc.

**Comment by GayS** [comment]
Hey Dave @courtrightd  I will try to sit with the staff that reported the issue on Thursday (5/19) and let you know what I see happening on this end.  Thanks for your help.

**Comment by GayS** [comment]
Dave @courtrightd , the script seems to run through and update panels, but I didn't see it go into SPEC/MEMO - although they move so fast it's hard to be sure!!

**Comment by theVKC** [comment]
See #2059. This does not appear to be a script bug _per se_, but a BlueZone configuration issue. Please check to make sure Options>API settings match those recommended by the installation instructions in SIR.

**Comment by GayS** [comment]
Hi - @theVKC .  We have confirmed correct session TLSv1 and API settings (DDE enabled).  We are using version 61c7.  The script worked after the security upgrade but stopped functioning after 5/12.  Further suggestions?

**Comment by theVKC** [comment]
Is Production in Screen 1 (S1)? If the button is selected in the wrong screen, or production is not on screen one (per the FAQ on SIR), these issues may occur.

It is recommended that users always ensure production is S1 and inquiry/MMIS (if not used within S1 and toggled with MDHS) is S2. When shutting down production, users should also shut down inquiry.

**Comment by GayS** [comment]
Yes – they are in S1 when running scripts – with no other scripts open in the background.  It runs through the panels and errors out at the end.

**Comment by theVKC** [comment]
But is another screen open? That seems to be the issue, the other screen. If they only have a single session up, with no other sessions running (which can be confirmed by task manager or restarting the pc), then there's a misbehavior in the script (or more likely the Functions Library). But that hasn't been able to be confirmed by anyone who can duplicate the issue. Hence why I'm hesitant to call it a script issue.

If on a fresh restart, only one session is operated, and it's an mdhs session, and the error recurs, then it's a FuncLib issue. Otherwise it's a configuration issue. Either way, it's not a script issue. Hence why I'm keeping the issue closed.

**Comment by GayS** [comment]
I have confirmed - on more than one sample – no other screens are open and we continue to get the error.

**Comment by theVKC** [comment]
Is this after a fresh restart though? That's the thing that tells me where the issue might be.

**Comment by theVKC** [comment]
Also, can you confirm if MDHS access is used (i.e. user runs MDHS) or if CICS... access is used?

Also also, as I said previously, this is a FuncLib issue and not a script issue. Please create a new issue on FuncLib. I'm going to lock this conversation, feel free to Slack or email me for more details.
