### ISSUE TITLE
BUG actions transfer case

### ISSUE THREAD

**Issue by CDPotter** [MN-Script-Team/DHS-MAXIS-Scripts#2242]
The script currently is designed to be run by a  worker who is sending the case to someone else. The SPEC/MEMO was updated to say:

"... You case has been transferred. 
I will be your new case worker.  ..."

Now if this MEMO is being generated by the old worker who is doing the transferring the old worker's information will appear on that MEMO. 

I would suggest we find the X# entered to transfer to and include that person's information in the body of the MEMO.

I can take this issue.

**Comment by courtrightd** [comment]
If it waits to send memo until after transfer, it causes an error on PRIV cases.  We will probably need to at least add a check for this to avoid this.

**Comment by CDPotter** [comment]
Ah I never thought about that! I will amend my pull!
