### ISSUE TITLE
Bulk Script- Case Tranfer

### ISSUE THREAD

**Issue by lisaholker** [MN-Script-Team/DHS-MAXIS-Scripts#2246]
I can get it to run until I try to put the new workers to transfer to in.
It errors out and says "Servicing Worker is Missing or Invalid" on the spec/xfer screen.
The worker number is showing correctly on the screen though.  
I've tried with x171xxx as Script states several times with several different worker numbers, also tried with just the 6 digits and last 3 digits to see if that made a difference and it won't work any of the ways I've tried.

Thanks,
Lisa

**Comment by theVKC** [comment]
@lisaholker, @C-Love of Ramsey County is going to contact you about this script.

**Comment by C-Love** [comment]
I was able to take a look at this. This is a MAXIS issue, where sometimes (randomly) the transfer operation in MAXIS does not work if all of the letter characters in the worker number are not upper case. Craziness. 

I have a fix for the script that I will push through to help accommodate this MAXIS issue. 

@lisaholker - if you could please do a PF11 on this as well, so we can report this issue to MNIT.

**Comment by lisaholker** [comment]
I’ll submit the PF11 on the xfer screen today.

Thanks,

Lisa Holker
Financial Assistance Supervisor
Sherburne County Health & Human Services
13880 Business Center Dr.
Elk River, Mn. 55330
Phone: 763-765-4021 Fax: 763-765-4096
Sherburne County Health and Human Services values customer service and would like to hear from those who receive services from us about your most recent experience.  Please visit this link https://www.surveymonkey.com/r/SCHHS2015 to complete a quick survey.  Your assistance in completing this will help us improve internal efficiencies and the quality of services to Sherburne County residents.
Please disregard if you have already completed a survey in the last 90 days.  Thank you.

The information contained in this email is confidential information intended only the use of the individual or entity named above.  If the reader of this message is not the intended recipient, or the employee or agent responsible to deliver to the intended recipient, you are hereby notified that any dissemination or copying of this communication is strictly prohibited.  If you have received this communication in error, please notify us by responding directly to this email and destroy all information received immediately.
