### ISSUE TITLE
BUG NOTE - HC Renewal Year error

### ISSUE THREAD

**Issue by GayS** [MN-Script-Team/DHS-MAXIS-Scripts#2249]
When the NOTE-HC Renewal script is run from SPEC/MEMO, the script enters a "/" in place of the year in the Case Number and Footer Month dialog box.

**Comment by CDPotter** [comment]
Looks like it's a problem with the function MAXIS_footer_finder it's finding Month: but on MEMO there's a second spot where Month: exists causing it to read "/ ". 

Would it make sense to program and IF for if the function is run on MEMO to read differently?

**Comment by GayS** [comment]
@CDPotter sounds logical to have an IF function for running on MEMO.

**Comment by theVKC** [comment]
After talking with Charles this sounds like a FuncLib issue. He's going to move this over to FuncLib and I'm closing it here. It will get resolved soon though, @GayS!
