### ISSUE TITLE
FuncLib - Actions-Transfer Case

### ISSUE THREAD

**Issue by GayS** [MN-Script-Team/DHS-MAXIS-Scripts#2253]
Actions-Transfer Case is giving an error message indicating user is in inquiry vs. production.  Users are in production, only one session running, happens after restarting computer, API setting is set to DDE enabled, BlueZone session manager is configured to 61c7, TLSv1.

**Comment by theVKC** [comment]
@GayS, please put this on the FuncLib repository, not here. https://github.com/MN-Script-Team/BZS-FuncLib
