### ISSUE TITLE
Denied Programs Script - Incorrect case note wording possibly?

### ISSUE THREAD

**Issue by jasont35** [MN-Script-Team/DHS-MAXIS-Scripts#2254]
This was brought to my attention by my supervisor and a co-worker. I am not trained in the Cash program so am not sure on this but here is what was stated.

> When an APPLICATION is denied - intake begins the following day. They don't get a month for REIN. 
> 
> Example: Application rec'd on 5/18/16. Application withdrawn 5/18/16. Intake begins 5/19/16 in which it would be considered a new application. 
> The script is showing after 6/17/16 it becomes intake.

**Case note created -**

----Denied cash----                                                 
* cash denial date: 5/18/2016                                       
* Application date: 5/18/2016                                       
* Reason for denial: Client withdrew application.                   
---                                                                 
* Last cash REIN date: 6/17/2016, after which a new CAF is required.
* All programs denied. Case becomes intake again on 6/18/2016.  

I think the main issue with this is the case note states "Last cash REIN date:" and i think they are saying that this wouldn't be considered a REIN, but would be a new application. The original CAF could be used for 30 days but it would be entered as a new application.

**Comment by theVKC** [comment]
@jasont35, I'm not sure that policy you're citing is correct. Any chance you can find a citation which supports this?

Also, there are checkboxes which alter these dates. Can you confirm the checkboxes were used correctly? I.e. I want you to try multiple checkboxes and see if that alters the date.

I will leave this issue open for one week, then I will close it if no further action is taken from your end. We get these questions a lot and usually we find checkboxes weren't used correctly.

@MN-Script-Team/county-agency-scriptwriters: I'm all in favor of simply removing this functionality entirely. I spend way too much time looking into this, and I am concerned it adds little.

**Comment by courtrightd** [comment]
I think the REIN wording is used in this script whenever a new CAF would not be needed, regardless of whether correct procedure is to REIN or enter as a new app.  I feel the script should be left as is, workers still need to determine proration / application dates on a case by case basis, but noting the dates in the way the script does helps give workers a reminder on the timelines for each program, and can be helpful when telling a client whether they need a new app.  Different counties refer to "intake"  with different wording as well, but it is generally accepted to mean a new CAF is needed and start the application process over.

**Comment by theVKC** [comment]
One thing I'm looking for is comment about the value of the REIN dates. I know one very, very large county opted to simply remove them from the case notes. @courtrightd, I assume your comment is in favor of keeping them. I'd be interested to hear what others think.

**Comment by jasont35** [comment]
The CM talks about when a complete application is needed (CM 0005.09.03) and when a complete application is not needed (CM 0005.09.06. It also addresses the issue one of our county EWs had: What happens when a client withdraws their application and the application is denied? The actions that can be taken are address in CM 0005.12.21.

I think the confusion comes into play when using the term “REIN”. This is not only a function performed in MAXIS, there are some case situations in which a program can be reinstated with a prorated allotment or no impact on allotment.

Again, back to the specific situation from our county EW. The client withdrew their application. They have not made contact to request a reinstatement, and so any new program request would require a new application (assuming they are not requesting reinstatement of the denied program within 10 days).

It can be confusing, at times, to EWs when the term “REIN” appears at the bottom of the script. Rather than working to change the script, one suggestion, is to have county EWs review the Case Notes , as is the existing business practice. They could then make any needed changes/corrections, based upon the specific case action and program(s) applied for or not renewed.
Kathleen Herring, FAS, Penn Cty

**Comment by theVKC** [comment]
That makes sense. We do have checkboxes for withdrawal which modify the date. I assume those checkboxes were not used?

Essentially, what my question boils down to is:

* Is the date being challenged? Or
* Is the wording of "REIN" being challenged?

Wording varies from agency to agency. Updating wording on a script can be very very challenging, because while one agency questions the existing wording, other agencies use it confidently. Updates for wording-sake I usually don't approve, unless it provides more clarity (usually "adding wording" is OK but "changing wording" I worry about).

Now, if it's the date, we need to look at those checkboxes and make sure they were used correctly.

Let me know @jasont35, if you want to keep the issue open or close it based on the above.

**Comment by jasont35** [comment]
The worker did use the check boxes but the only check box for a date is the one to put the denial date not the REIN date or Intake date. She did enter the denial date under the Cash check box. 

It is mostly the wording of "REIN", but the date would also be incorrect for a withdrawn application at least as per the previous mentioned Combined Manual references. 

I would say we can close this issue for now and if needed look at it again later if it is questioned again. The worker can change the wording in the case note, if needed, for these rare instances.

**Comment by CDPotter** [comment]
To the discussion above Anoka would like to keep the dates. They are extremely helpful for OSAs and a lot of our workers would be disappointed/upset if they disappeared.

**Comment by theVKC** [comment]
OK @jasont35, I'll close the issue. For the record, I am open to considering modifying the text "REIN" to be something else, so long as we have good support for it from scriptwriters, and solid reasoning to explain it to staff statewide.
