### ISSUE TITLE
Bulk Rept Lists (PND1, REVS, REVW) content error

### ISSUE THREAD

**Issue by Farleight** [MN-Script-Team/DHS-MAXIS-Scripts#2258]
The Rept Lists each check to see if a user "has_content" prior to carrying info to Excel. There seems to be little consistency in which content is checked for between these, but all seem okay except the above three. These three use the 2nd coordinate of the case number field and assume no case exists if it is blank. It misses cases of 5 or fewer numbers, and in doing so, misses entire caseloads if the first case alphabetically happens to have 5 or fewer numbers.

Proposing to switch this language to look for all 8 digits. I cannot publicly admit to doing this while my county has me on a script freeze... but if it were to accidentally be assigned to me, who knows what might happen?

**Comment by theVKC** [comment]
Ooops, my finger slipped. :)
