### ISSUE TITLE
Claims Script

### ISSUE THREAD

**Issue by Kolbwalt** [MN-Script-Team/DHS-MAXIS-Scripts#2263]
A question was asked regarding claim notes.  Often times Eligibility Workers will just copy and paste the case notes for the claim into the claims note section.  Staff are wondering if they could get a script to put the same note into two different areas, CASE notes and CLAIM Notes.  Is that an option or does it already exist?

**Comment by theVKC** [comment]
I don't believe it's an option yet. I have built some functionality for writing in various claims-based screens, though.

@Kolbwalt: are you thinking something like a "copy this case note to claim note" option? Or a specific claims-based case note?

Also, any @MN-Script-Team/county-agency-scriptwriters interested in it?

**Comment by Kolbwalt** [comment]
I was thinking of having a box where if they check it, it will automatically be entered into the claims notes.  It saves them time.  ☺  I highlighted the section.
Thanks!!

**Comment by theVKC** [comment]
@Kolbwalt, since this went into GitHub, I can't see the option you highlighted. Can you log into GitHub and upload the file into a comment? Or feel free to email it to me directly. :)

**Comment by theVKC** [comment]
OK, we talked through email. Here's what we're thinking:

1.       The user uses a regular case note, like they currently do. No extra checkboxes or other features.
2.       After the user uses a regular case note, the user starts a new utilities script: “copy this case note to a claims note”.
3.       That script does the work on whatever case note the user wants.

So, who wants it? Anyone?

**Comment by CDPotter** [comment]
I'll take this one. I want to make it more function like so we can put case notes in other places like memos or wcoms in addition to claim notes.

**Comment by Kolbwalt** [comment]
Thank you!

**Comment by theVKC** [comment]
Thanks @CDPotter! Think it can be done by June release?

**Comment by CDPotter** [comment]
That's due by 6/17? I think I should be able to.

**Comment by theVKC** [comment]
@CDPotter, can I get an update on this one? Think it'll be done by Friday for the release deadline?

**Comment by CDPotter** [comment]
I don't think I'll be able to get it done by then. We've been a bit short handed and I'm out on Friday. If I do get it done I will submit it.

**Comment by CDPotter** [comment]
WCOM is proving to be difficult...Also for STATS should I time it based on manually re-writing a case note or copy and pasting a case note?

**Comment by theVKC** [comment]
Copy and pasting.
