### ISSUE TITLE
Enhancement: Notes closed progs sanction date clarifier

### ISSUE THREAD

**Issue by CDPotter** [MN-Script-Team/DHS-MAXIS-Scripts#2264]
Currently the sanction case note writes something like this:

![sanc date](https://cloud.githubusercontent.com/assets/7841989/15588364/292faabc-2353-11e6-9153-3302cbb3cdca.png)

I think it would be more helpful it it wrote 3/1/16-5/31/16 instead as some people may interpret 3/16-6/16 as a 4 month period. 

If others think this clarification would be good I can get started on it (or if someone wants to be entrepreneuring they're more than welcome to take it too!)

**Comment by theVKC** [comment]
This is always a funny debate. I have always been in favor of the actual days with it ending on the final day of the last ineligible month. But, I'm open to debate. Any @MN-Script-Team/county-agency-scriptwriters have an opinion?

**Comment by Farleight** [comment]
Yes... the change.

**Comment by theVKC** [comment]
@CDPotter, do you want this one?

**Comment by CDPotter** [comment]
If everyone likes it yes I can work on it.

**Comment by theVKC** [comment]
Approved! Do you think it can be done by Friday's release deadline?

**Comment by CDPotter** [comment]
Since this should be a small fix I could probably get this done by Friday.
