### ISSUE TITLE
Enhancement ACTIONS FSET CHECKER rewording

### ISSUE THREAD

**Issue by CDPotter** [MN-Script-Team/DHS-MAXIS-Scripts#2270]
For the 30 hours or equivolent message it says:

appears to be earning equivalent of 30 hours/wk at federal minimum wage. Please review for ABAWD and SNAP E&T exemptions.

I want to change to:

appears to be working 30 hours or earning equivalent of 30 hours/wk at federal minimum wage. Please review for ABAWD and SNAP E&T exemptions.

As well as add "and SNAP E&T exemptions." to the line about working 80 hours(since working 80 is a snap e&t exemption rather than ABAWD exemption.)

If this is all good I can submit pull.

**Comment by theVKC** [comment]
Is this in CM @CDPotter? The part about "working 30 hours or..."? I believe you're correct on it but a citation might help clarify things with users who might question it.

**Comment by CDPotter** [comment]
CM 0028.06.12

● Employed or self-employed and meets 1 of the provisions below:
   -Working at least 30 hours per week (regardless of wage level).

   - Receiving earnings at least equal to 30 hours a week at the federal minimum wage.

**Comment by theVKC** [comment]
Thank you!!! Do you see a place in the script to put that citation so workers can see it? Also, make sure your blip includes it.
