### ISSUE TITLE
BULK/ DAIL ~ Possibility of adding an alpha split search within the worker ID

### ISSUE THREAD

**Issue by ALJ10** [MN-Script-Team/DHS-MAXIS-Scripts#2273]
Here's a suggestion from a financial worker. Thoughts?
***
I’m wondering what your thoughts would be on looking at a script enhancement for the DAIL script under BULK. Currently, it will pull DAIL messages for a specific worker (in our work it would be the case bank ex: X118ADL) I’m wondering if this script could be enhanced to have an option to pull alpha split DAILs from a case bank.

Example: It asks for the worker which would be X118ADL, then enter their alpha split A-EZ

If the worker could enter their own alpha split into this search it would be super handy for workers to use to manage their own alpha split DAILs. I’m pretty certain many counties use alpha split for DAIL management, we cannot be the only ones.

**Comment by theVKC** [comment]
Hi! I would think an end user could simply sort the list alphabetically (it is Excel after all) and then disburse/delete the unneeded fields, right? Is that a viable option?

I'm open to considering this for a bit, and if any scriptwriters are interested in it, please feel free to take it and run with it. But, I don't currently have time to pursue this enhancement.

I'll leave it up until next hackathon (June 13). If nobody wants to take the issue by then I'll close it.

**Comment by theVKC** [comment]
Closing due to lack of interest from scriptwriters. Can pursue if a scriptwriter comes forward and wants to work on it.
