### ISSUE TITLE
BULK / REVW/MONT Closures ~ 4 month extension for MAGI pops...

### ISSUE THREAD

**Issue by ALJ10** [MN-Script-Team/DHS-MAXIS-Scripts#2274]
A supervisor utilized the REVW/MONT Closures script toward the end of May. She indicated to me that she did not see the "4 month extension for MAGI pops" included on the script. She was thinking maybe that policy was no longer in effect. But she determined it's still in effect. So she's wondering why she wouldn't have seen that on the script itself. Unfortunately, I don't have a screen shot of what she was seeing/entering. Thoughts?

**Comment by CDPotter** [comment]
The code was in there but someone adjusted something causing it to read incorrectly. I fixed this on the MASTER branch last week. https://github.com/MN-Script-Team/DHS-MAXIS-Scripts/pull/2266

**Comment by theVKC** [comment]
Looks like this will go live later this month for the June release. Closing this issue.
