### ISSUE TITLE
Bug >> INAC Scrubber includes reference to X102CLS

### ISSUE THREAD

**Issue by RobertFewins-Kalb** [MN-Script-Team/DHS-MAXIS-Scripts#2279]
![image](https://cloud.githubusercontent.com/assets/7842016/15838266/b176d848-2c02-11e6-9e80-2c9674e4383c.png)

So this is a thing. I am concerned that there are agencies that are transferring cases to X102CLS. This is in both master and release.

**Comment by theVKC** [comment]
Is this just on the four extra months path?

**Comment by RobertFewins-Kalb** [comment]
It is indeed.

**Comment by theVKC** [comment]
This explains why it hasn't been discovered. I believe Anoka is the only county using that path. It hasn't been worked into the installer yet.

We should certainly fix the issue, regardless! I'd prefer to replace the two long paths with a single unified process which keeps them for the four months anyway. Pretty sure that's now a pretty firmly established procedure.

**Comment by theVKC** [comment]
@RobertFewins-Kalb, do you want this one? We can dispose of the multi-paths at the same time and make short work of the entire issue.

**Comment by RobertFewins-Kalb** [comment]
I can take it

**Comment by RobertFewins-Kalb** [comment]
I have an issue that I think should be considered on this script. Going to create a new issue.

**Comment by theVKC** [comment]
@RobertFewins-Kalb, think this will be done by Friday's release? If not I can mark it for July.

**Comment by RobertFewins-Kalb** [comment]
I'll get it done this week

**Comment by theVKC** [comment]
Thank you!!
