### ISSUE TITLE
NOTES - ASSET ASSESSMENT has a typo

### ISSUE THREAD

**Issue by theVKC** [MN-Script-Team/DHS-MAXIS-Scripts#2285]
`EMReadScreen` is spelled `EMReadScreacen` on line 271. This is causing an impassable type mismatch error.

@IlseFerris of Hennepin has volunteered to get this done. Originally reported by Aitkin County.

@IlseFerris, please pull into both master and RELEASE, as this is critical and impassable.

**Comment by IlseFerris** [comment]
Ready to go in release and master!
