### ISSUE TITLE
ACTIONS - COPY PANELS TO WORD: this should be a utilities script

### ISSUE THREAD

**Issue by theVKC** [MN-Script-Team/DHS-MAXIS-Scripts#2290]
Since it isn't taking an action on a case _per se_, but merely copying case information for easier review by case reviewers (and supervisors and others), I believe this is a utilities script and not an actions script.

Any thoughts @MN-Script-Team/county-agency-scriptwriters?

**Comment by IlseFerris** [comment]
Makes sense to move this to utilities. POLI - TEMP is similar to this script, and that is also a utilities script.

**Comment by theVKC** [comment]
If none are opposed by Monday's hackathon, I will proceed.

**Comment by IlseFerris** [comment]
I'll take it.

**Comment by theVKC** [comment]
@IlseFerris pulled this (by my own request) into my branch for #2301. Closing this issue.
