### ISSUE TITLE
ACTIONS - HOUSING GRANT MONY CHCK ISSUANCE: needs shorter title

### ISSUE THREAD

**Issue by theVKC** [MN-Script-Team/DHS-MAXIS-Scripts#2291]
It's too long for the new unified button settings for workflow and main-menu autocreation:

![image](https://cloud.githubusercontent.com/assets/5701751/15908485/95b245e4-2d87-11e6-866b-e673b41e52bc.png)

We could save space by calling it "HG", but perhaps @IlseFerris has other ideas.

Also, I'll ask you to take this one to preserve your history as the primary scriptwriter.

**Comment by theVKC** [comment]
Note that when we update the name of this file we will also need to update the instruction file on SIR.

**Comment by IlseFerris** [comment]
Will do, and thanks for being a purist ;D
