### ISSUE TITLE
Enhancement/Input Needed >> INAC Scrubber mode for users without MMIS access

### ISSUE THREAD

**Issue by RobertFewins-Kalb** [MN-Script-Team/DHS-MAXIS-Scripts#2292]
Anoka Co has users that will not be given MMIS access but will have a MAXIS caseload. As cases convert to METS, more caseloads are going to be MAXIS CASH & SNAP only. We would like a way to bypass MMIS for those users.

I am hoping there is a way to determine user permissions in REPT/USER (if you sort by Supervisor, it looks like it displays user permissions, but it doesn't make a whole lot of sense to me). I'm thinking MMIS Bypass Mode would also check for the programs that closed that months and ignore cases that closed on health care. That way, we could prevent users from running a version that has fewer checks in hopes of clearing more of their INAC cases.

We currently have an MMIS Bypass INAC Scrubber running locally, but I would rather not invite confusion with users.

What are peeps, thoughts?

**Comment by theVKC** [comment]
I like the idea, especially if it can be determined dynamically. An alternative would be to simply see if MMIS is running and if not, ask the user if they want to bypass (instead of now, in which it just shuts down). That might be simpler and accomplish the same goals, n'est-ce pas?

**Comment by theVKC** [comment]
Same as the other issue @RobertFewins-Kalb, think this should be a June or July release?

**Comment by RobertFewins-Kalb** [comment]
I'll get it done this week

**Comment by theVKC** [comment]
Thank you!

**Comment by RobertFewins-Kalb** [comment]
Update >> Unless anyone else is aware, there is no way to to easily check for a user's permissions in MAXIS. Going to REPT/USER and sorting based on supervisor gives you a list of permissions, but it's not really straight forward. @theVKC I like the option to bypass if the user cannot get in. I'll go ahead and make that the way it does.
