### ISSUE TITLE
Bug mic drop sent paperwork to wrong case

### ISSUE THREAD

**Issue by CDPotter** [MN-Script-Team/DHS-MAXIS-Scripts#2293]
Had a case with MSA/MA renewal due 07/16 and SNAP closed for no CSR 12/31/16. However the renewal date for SNAP was still 07/16 and as such it sent a interview letter. It needs to look for ACTV on prog for SNAP as well.

I can take this one.

**Comment by theVKC** [comment]
Can we close Mic Drop issues and just tag the original issue with a comment and in the pull request please? Since this isn't live the separate issue here isn't necessary.

**Comment by IlseFerris** [comment]
Awesome @CDPotter thank you!
