### ISSUE TITLE
BULK list scripts: let's merge/bulk them all together

### ISSUE THREAD

**Issue by theVKC** [MN-Script-Team/DHS-MAXIS-Scripts#2299]
I think we could do this differently. Perhaps a checklist where you select the areas you want to search.

I worked on something like this at Anoka. @CDPotter and @RobertFewins-Kalb, I believe the two of you have enhanced this since I came to DHS... is there a chance you could share it? I view this as a great button-reduction process.

**Comment by theVKC** [comment]
Here are the scripts indicated:

- REPT/ACTV 
- REPT/EOMC 
- REPT/INAC 
- REPT/MFCM 
- REPT/PND1 
- REPT/PND2 (also breaks down PND2 data by worker) 
- REPT/REVS 
- REPT/REVW

Also, @IlseFerris, does this mean we already have an MFCM script?

**Comment by theVKC** [comment]
Also, probably the new IEVS report.

**Comment by RobertFewins-Kalb** [comment]
The most recent version of what we have is here...

https://raw.githubusercontent.com/RobertFewins-Kalb/Anoka-Specific-Scripts/master/ANOKA%20REPORT%20GEN.vbs

**Comment by theVKC** [comment]
@RobertFewins-Kalb, would you be willing to state-ify this one for me? Looks like we'd primarily need to restore access to FuncLib (I did warn you-all about that in January of 2015) and add statistical tracking.

**Comment by C-Love** [comment]
@theVKC we have an MFCM report which lists the MF participating cases but does not indicate Monthly reporting status or the status of the current months HRF. REPT MRSR and REPT MONT do those. 

Also, I have a supervisor here who was just talking with me this morning about having these together. So, great timing!

**Comment by IlseFerris** [comment]
I will be working on my BULK lists between now and Tuesday, just as an FYI to whomever takes this issue.

**Comment by theVKC** [comment]
@MN-Script-Team/county-agency-scriptwriters: I'm going to get separate hackathon space for this sometime in July. I should also have WebEx access by then, so we can do a remote session. Does anyone want to join the coalition of the willing?

**Comment by CDPotter** [comment]
I could probably help with that.

**Comment by theVKC** [comment]
Woot @CDPotter!

**Comment by theVKC** [comment]
@RobertFewins-Kalb: do you want in on this party? You did reference it in #2332 and I know Anoka's discussed this a bit. We'd love to have you.

@CDPotter and @RobertFewins-Kalb: have you been adding any updates from the existing lists (PND1/PND2/etc) to the Anoka-specific version? We've made minor changes which I don't want to lose if we borrow heavily from your work.

**Comment by RobertFewins-Kalb** [comment]
1. sign me up

2. We have not been adding updates from the existing lists

**Comment by CDPotter** [comment]
This isn't a huge priority, we're gonna mark it as sleeper for now and come back around to it.
