### ISSUE TITLE
Splitting "OTHER NAV" between "NAV" and "UTILITIES"

### ISSUE THREAD

**Issue by theVKC** [MN-Script-Team/DHS-MAXIS-Scripts#2301]
So, I'm completing #2159. Creating a large list of scripts, and functionality to automatically determine URLs, subcategories, and SIR instruction URLs for both Main Menu and Workflow scripts.

OTHER NAV is located inside the NAV folder. This presents challenges in my functionality as I have to handle these few scripts completely differently:

- Look up MAXIS case in MMIS
- Look up MMIS PMI in MAXIS
- Move Production Screen to Inquiry
- Phone Number or Name Lookup
- PRISM Screen Finder
- View INFC

So, we have two choices:
1. I keep "other nav" where it is, and add functionality into my script class to see "OTHER NAV" and treat it differently.
2. Since these particular scripts could arguably be more-or-less "Utilities", we could move all of these scripts over to the Utilities button, and then discontinue the Other Nav button.

Thoughts @MN-Script-Team/county-agency-scriptwriters?

**Comment by C-Love** [comment]
I agree that the top 4 could be easily classified as Utilities. View INFC seems very much a Nav script - though with it buried in a menu - not sure how much it is being used. 

Is there any possibility this type of issue would be presented in another area of scripts as well, where you would have to work out the functionality anyway? (personally I can think of any place) Hate to make a bunch of changes - including a potential power pad change and then still need to work out the functionality anyway.

**Comment by CDPotter** [comment]
I can't remember the last time I used view INFC because of the new way to get that info. (though I know of some workers who probably don't remember how to do it manually anymore.)

At Anoka we have most of these script buttons still on our personal powerpad rather than behind Other NAV. I really enjoy having easy access to MAXIS to MMIS personally. Since we have our own powerpad Anoka doesn't have an official stance on this one.

**Comment by IlseFerris** [comment]
These scripts could move to utilities and I'd be ok with that. That said, having access to MAXIS to MMIS by not going into a sub menu would be ideal.

**Comment by theVKC** [comment]
Here's what I think we should do.

1. Update the Power Pad to move **Look up MAXIS case in MMIS**, **Look up MMIS PMI in MAXIS**, and **View INFC** to the Power Pad. This also requires creating new REDIRECT files and updating the installer. The files would be moved to the NAV folder, sans "OTHER NAV".
2. Update **Move Production Screen to Inquiry**, **Phone Number or Name Lookup**, and **PRISM Screen Finder** to the UTILITIES menu. The files would be moved to the UTILITIES folder.
3. The NAV and UTILITIES menus in the list of scripts can be updated properly.
4. **OTHER NAV MAIN MENU** would be updated to purely link to the old files for agencies using the old Power Pad, only until enough time has passed where we can justify removing it and requiring another reinstallation (we just wrapped one so I'd prefer to wait a bit on that step).

I'll get this done this before Monday's release. Agencies who want the new Power Pad can simply update it at their leisure once this is complete.

**Comment by theVKC** [comment]
@IlseFerris is going to be helping me with moving the scripts to the utilities menu since she's already updating it for #2290.
