### ISSUE TITLE
Find Updated panels

### ISSUE THREAD

**Issue by bblomer** [MN-Script-Team/DHS-MAXIS-Scripts#2332]
On the Bulk Lists - Find Updated panels - can we add the DFLN panel to this current script so we can quickly run a report to see who needs to go to random drug testing.

**Comment by RobertFewins-Kalb** [comment]
That sounds like you need a different script. Find Updated Dates would be used when you want to see which DFLN panels have been updated within a certain date criteria. That wouldn't really be a good match for what you are looking for. This sounds like something that would fall within the scope of #2299 ...definitely something to keep in mind.

**Comment by IlseFerris** [comment]
Agreed, I this would be it's own script. @bblomer can you update the title of the issue to reflect that you are requesting a new BULK script for DFLN/drug testing recipients. Can you also elaborate on any other information you'd want the script to include?

Any takers on this one?

**Comment by courtrightd** [comment]
I have a bulk script to find every actv case with a DFLN panel in the county and build a spreadsheet.  I can get it cleaned up and shared (but not until next month).

**Comment by IlseFerris** [comment]
@courtrightd for the win!

**Comment by theVKC** [comment]
I concur with my fellow scriptwriters. We should make this a separate script since it's a bit outside of scope. I also think it might fit well into #2299's process.

@courtrightd, if I made a unified "Pull Data to Excel" style script, think you could add this function? If so, I might close this issue and defer into #2299.

**Comment by courtrightd** [comment]
I would be willing to add this to a pull data to excel list, I was going to enhance it before uploading anyway, so I will wait and add it to the new script from #2299

**Comment by theVKC** [comment]
I'm going to close this issue and we can make sure it's added to #2299.
