### ISSUE TITLE
Closed Programs enhancement - HC program manuals button update

### ISSUE THREAD

**Issue by IlseFerris** [MN-Script-Team/DHS-MAXIS-Scripts#2334]
HCPM and IAPM manuals are not outdated. Users need to use the MHCP-EPM manual. 
Closed Programs has buttons for each of these program manuals, and will need to be updated to remove the old buttons and add a MHCP-EPM button that links to: http://hcopub.dhs.state.mn.us/epm/#t=index_1.htm

**Comment by theVKC** [comment]
"not outdated" or "now outdated"? My understanding is they are "now outdated". @IlseFerris, can you confirm?

**Comment by CDPotter** [comment]
My understanding is they're still usable for cases processed before 06/16 but everything forward is EPM

**Comment by IlseFerris** [comment]
The previous manuals ARE outdated. My bad.
Also I believe @CDPotter resolved this with #2341. Can you reassign to him?
