### ISSUE TITLE
Enhancement: Burial assets, adding preview, dynamic calculator, better control

### ISSUE THREAD

**Issue by CDPotter** [MN-Script-Team/DHS-MAXIS-Scripts#2343]
After the last update to burial assets we got another request to make it a bit more powerful. This time we've been taking it slow and testing things to make sure this latest update is nice and thorough. Our additions this time include:

 A dynamic calculator that displays current totals for counted assets and things applied to the BFE. When the user hits a button the calculator will refresh, it will also make sure the user doesn't enter more than $1500 into the BFE and appropriate relabel the last item to push the BFE over $1500 to BFE/counted (it will also let the user know of this change and inform them to review it). This is more in line with examples found in LTC training case notes. 

A preview messagebox after the user enters all of the information. This box will display the totals, what items were selected, what their items values are, and what the status of the item is (counted excluded etc). User can then go back, quit, or go to case note. 

We also cleaned up some old outdated functions and case noting procedures.

The script is currently being tested at Anoka so I want to delay this until next release cycle to make sure we get it right.

**Comment by theVKC** [comment]
Sounds great @CDPotter! I'll tag it for July.

**Comment by theVKC** [comment]
Freeze is over! Can I get an update on this one?

**Comment by CDPotter** [comment]
Just pulled, wanted to get some testing done this morning after filling it with comments.
