### ISSUE TITLE
New utilities script: "what scripts are new?"

### ISSUE THREAD

**Issue by theVKC** [MN-Script-Team/DHS-MAXIS-Scripts#2346]
This came from a message @C-Love sent me. I love this idea. It goes through the script_array and returns all of the new scripts in a list. On it. Unless of course @C-Love has already started it.

**Comment by theVKC** [comment]
This should also have a link to release notes.

**Comment by C-Love** [comment]
I did not start it!

**Comment by theVKC** [comment]
Good deal. Do you want to help me with it at all?

**Comment by RobertFewins-Kalb** [comment]
Do you want what we have for our favorites menu? It pulls that information dynamically

**Comment by theVKC** [comment]
I do, I do!

My method uses the `release_date` property in the new list of scripts. Methinks both your iteration and mine ought to use that property to deliver these details. How does your iteration do it?

**Comment by C-Love** [comment]
Let me know what you need from me - happy to help. I have limited time this week, but we will be together on Monday.

**Comment by RobertFewins-Kalb** [comment]
What we have relies on "NEW" being the first three characters in the description property to build a `new_scripts_array`

**Comment by theVKC** [comment]
I see. Our new functionality (see #2159) integrates a `.release_date` property. Then, my function reads that date, and automatically delivers "NEW MM/DD/YYYY" if that date is within the last two months. This way I don't need to edit descriptions to remove that bit (that was getting old across 200 scripts). So, going forth once #2159 is resolved, the descriptions will not contain any "NEW" at the beginning.

**Comment by RobertFewins-Kalb** [comment]
Good to know. We just needed a rudimentary way of letting staff know what scripts were new and that seemed to be the most accessible solution.

**Comment by theVKC** [comment]
I bet you can utilize the same process we have, if you'd like. I think it's in the ACTIONS - MAIN MENU file for this month's real-life test.

**Comment by CDPotter** [comment]
Tied to workflow project will reopen once cracked
