### ISSUE TITLE
DAIL - SEND NOMI policy clarification

### ISSUE THREAD

**Issue by IlseFerris** [MN-Script-Team/DHS-MAXIS-Scripts#2347]
If a CAF was not rec'd in agency, and an appt letter was not sent, then you would not send the NOMI, otherwise the NOMI should be sent. 
Since contact is made with the client via appt letter sent when using the REVS scrubber, and this DAIL scrubber only works with TIKL messages created by the REVS scrubber, additional logic and verbiage regarding weather or not a CAF rec'd in agency needs to be removed. This was my bad. Here is the POLI/TEMP info:

TE02.05.15 regarding NOMI's for recerts: 
NOTE:  This SPEC/MEMO text should only be used for situations
where a FS Recertification is due, the county contacts  
the client OR the client contacts the agency, schedules 
an interview in person or by phone, the client misses   
the scheduled interview and either a CAF has been       
submitted to the agency or no CAF is submitted to the   
agency.                                                 
                                                        
This SPEC/MEMO text is NOT to be used when the FS       
recipient never contacts the agency and no CAF is       
received.  When there is no request for further         
assistance the client will receive the proper closing   
notices from the MAXIS system.     

Assign to me. I have the fix, and tested it locally with success.

**Comment by theVKC** [comment]
Luckily this is so tied to #710, which isn't live, that it shouldn't be affecting many agencies.

**Comment by IlseFerris** [comment]
True story. Will be resolving #710 by the end of the day so this needed to get done too.
