### ISSUE TITLE
script question-appt letter

### ISSUE THREAD

**Issue by x158215** [MN-Script-Team/DHS-MAXIS-Scripts#2370]
Our case aide would like an explanation as to why on the bottom of the appt letter it says:
"if expedited interview date is not within six days of the application, explain:"
should this be changed to 5 days since expedited has to be issued within 5 days?

**Comment by theVKC** [comment]
"Within six days" is a more explanative catch-all. It gets all of the five-day folks, including possible holidays. "Within 5 days" could leave doubt on what to do about day 5. This doesn't. Good question!
