### ISSUE TITLE
Call for input: Removal of Excel spreadsheet created by APPROVED PROGRAMS

### ISSUE THREAD

**Issue by IlseFerris** [MN-Script-Team/DHS-MAXIS-Scripts#2373]
Currently the NOTES - APPROVED PROGRAMS script creates an Excel spreadsheet if the case is a banked months case. This functionality was added very early into the development of tools to assist workers to manually track banked months. Other tools have been created that I believe supersede the need for a spreadsheet for a single case to be created. That said, I would like to remove it. If you are a county who uses these spreadsheets, and wants to see the functionality remain, I would like to hear from you. Otherwise I will remove this functionality at the end of the week. Thank you @MN-Script-Team/county-agency-scriptwriters

**Comment by CDPotter** [comment]
Anoka does not use this feature.

**Comment by asunderman** [comment]
I put an email out to my co-workers to see if any of them use it.  I’ll report back when I have an answer.

Ann

**Comment by asunderman** [comment]
And now if our IT department will make it so I can see “normal” github stuff on our network…  grrr….  I think they’re firewall/block all the sites happy.

Ann

**Comment by theVKC** [comment]
@asunderman: let me know if you need me to contact any IT folks over there to explain the business need for access.

**Comment by asunderman** [comment]
YAY!  GitHub access is back and "normal"  and yes, my co-workers DO use this report.

**Comment by theVKC** [comment]
If even one county is using this report, in Excel format, we should keep it, as there will be more. @asunderman, can you confirm your folks are using the Excel report?

**Comment by IlseFerris** [comment]
I think we should allow users to opt of this option (possibly via global variables). That way counties that need it have it, and those who don't need it can suppress it.

**Comment by theVKC** [comment]
Is it so obtrusive @IlseFerris, that adding/removing should be hidden from most users? I try to only use Global Variables for options that are set by local county policy, so things like x1 numbers for a CLS division, or EGA requirements, etc.. Remember: most counties can't update their Global Variables easily at all. If we allowed Global Variables for every possible script option, hoo boy.

If the concern is that it's obtrusive, then we should make it less intrusive.

**Comment by IlseFerris** [comment]
How about adding the Excel option as a checkbox then? Many users at my county have not been using approved programs for banked months cases (I review most of them so I know first-hand), and I fear it's due the Excel list being generated.

**Comment by theVKC** [comment]
How is it showing up now? Does it just show up? I thought it was buried in a button?

**Comment by theVKC** [comment]
@courtrightd, did you add this feature? Do you want to jump in here?

**Comment by IlseFerris** [comment]
@C-Love added this one I believe. Again this was added very early on before we had any other tools available. 
If you identify a case as being banked months, then the Excel list will appear (as well as a TIKL for end of the banked months period).

**Comment by courtrightd** [comment]
All counties not using the access database solution (everyone but SLC) get the spreadsheet.  We don't have it here, so I don't have much input.

**Comment by theVKC** [comment]
Well, I don't want to get rid of it. Perhaps a button or something? I like a button over a checkbox for this, it has instant gratification.

**Comment by CDPotter** [comment]
global variable?

**Comment by theVKC** [comment]
See above. I don't love that option. Most folks can't update theirs and recent experience tells me I will be hated if I hide it there. Plus I don't want to get into a habit of adding every possible option to GlobVar.

**Comment by CDPotter** [comment]
Ah, missed that! Sorry!

**Comment by C-Love** [comment]
The trouble we are having is the tracking. The initial instructions from DHS were to track on a Spreadsheet (they had a tracking form that is a DHS Form version of a tracking sheet). A button would be difficult because it only works once the correct start month and number of months is entered in the Banked Months specific dialog. If you click the button  before there are months and such you get a blank excel - or if you click OK and forget to click the button first, you don't get a spreadsheet. 

I have 2 thoughts - one would just be a checkbox at the top of the banked months dialog 'I TRACK BY EXCEL' then we can easily code certain counties to have that autochecked by county code. 

OR we institute a warning box just before the spreadsheet giving a depreciation date for the excel sheet an if your county uses it, contact to keep it in, then we aren't guessing at who is or is not using it.

OR DHS (excluding @theVKC ) could come up with an actual tracking system and we could track things that way #BCodePlease

**Comment by theVKC** [comment]
I don't like the coding for certain counties. I do like the warning box. That way, any folks who are using it come out of the woodwork. If we do want to get rid of it, we can discuss it with them at that point.

**Comment by IlseFerris** [comment]
Update: Hennepin and Ramsey users will have the Excel option suppressed. For all other users a message box will appear informing them the spread sheet will be retired as of the August script release unless there is feedback from users that they have no other process for tracking. 

s feedback from users that they are using the spread sheet as part of their agency's banked

**Comment by Jmallen9** [comment]
MNPrairie is using this feature on the script as well.  Our staff take the information off the Excel spreadsheet and move it onto the DHS report that is sent off to report months used.  Until Maxis is updated to collect this data and county are no longer responsible I would like to keep this option available in scripts.  Jeremy Allen MNPrairie.

**Comment by CDPotter** [comment]
Is anyone opposed to having it in/removing the warning this will be removed" message box?

**Comment by IlseFerris** [comment]
If someone needs it, then let's keep the excel functionality for them.

**Comment by CDPotter** [comment]
Sounds good since it's a minor house keeping thing that requires 0 testing I'm going to break the rules and remove the warning during the freeze.
