### ISSUE TITLE
New Script - MAXIS to METS healthcare migration

### ISSUE THREAD

**Issue by StormageddonDLOA** [MN-Script-Team/DHS-MAXIS-Scripts#2376]
This was rec'd as an email from one of my co-workers. Thoughts?

Problem:  MAXIS to METS healthcare migration
•	In order to reduce the # of problem cases during the migration, it would be helpful to move over as many cases as we can before the migration process begins.  
•	We need to contact the families and obtain their permission to do so if we do not wait for the migration.

Request:   
•	Is there currently a script in BZ that could help us identify Apparently MAGI cases that could be manually moved to METS?  
•	If not, how difficult would it be to create such a script?  
•	Is there an existing script that identifies enough of the items we need that perhaps we could use that report and manually filter out the ones that do not meet the criteria?

Specs:      At a guess, I expect the script would need to look at the following:
•	REPT/ACTV (perhaps filter by unit or worker)
•	ELIG/HC – identify the MAGI codes such as PX, ANB, AA, AX, CX, CB, CK
•	Spenddown – filter out spenddown cases.  Not sure if a script could do that, or if we would just need to look at each case individually
•	MSUR – not all cases with Mnsure participants will have MSUR panels, but this could be a useful field anyway (maybe)

Thanks for reviewing!

**Comment by CDPotter** [comment]
Well we already have one to create a list of magi/non magi https://github.com/MN-Script-Team/DHS-MAXIS-Scripts/blob/master/Script%20Files/BULK/BULK%20-%20MAGI%20NON%20MAGI%20REPORT.vbs

Do note that if run for an entire agency it will take a long time (here at Anoka I think it took at least 8 hours?)

**Comment by theVKC** [comment]
@StormageddonDLOA, I'm going to close this one for now as it looks like the script (which has been in master for a few weeks) does what you're describing. If that doesn't work we can reopen the issue.
