### ISSUE TITLE
Enhancement to NOTES - Client Contact Script

### ISSUE THREAD

**Issue by kennyasalee** [MN-Script-Team/DHS-MAXIS-Scripts#2379]
Ramsey county had a request enhancement for NOTES - Client Contact script pertaining to contacts regarding joint curam/METS issues. Situations may occur that preferably, case noting in maxis will be needed. Since not all workers are familiarized with curam, METS or MMIS systems. Per @C-Love 's information with @LaLarson: It will be helpful to have a field in Client Contact. I think simply a "MNSURE/IC case number: " field so that workers can be alerted to provide point of reference to the METS case. Seems like a easy commit. I am down to.

**Comment by theVKC** [comment]
It's yours, @kennyasalee! Good luck!
