### ISSUE TITLE
Denied Programs - Self Declaration of Over Income Policy

### ISSUE THREAD

**Issue by C-Love** [MN-Script-Team/DHS-MAXIS-Scripts#2388]
There is a very specific policy that was recently updated about denying SNAP applications for Self-Declared over income. ( TE 02.05.106 )

It does not appear that this information is in the script to note if this selection is checked. Seems like if workers are checking this, we should have some more to the script to detail the required information. It is as follows (warning TEMP Manual spoilers ahead)

-Date of interview
-Client statement of income
-GIT for the SNAP HH size
-Reason for denial

It does appear the REIN dates follow this updated policy.

I don't have a ton of time but this seems pretty important and I will take it instead of letting it close.

**Comment by theVKC** [comment]
I'll mark as help wanted for now. If nobody else wants it one of us will take it for certain.

**Comment by theVKC** [comment]
@StormageddonDLOA has volunteered to take this on! Thank you!
