### ISSUE TITLE
Enhancement bulk inac scrubber pause on xfer

### ISSUE THREAD

**Issue by CDPotter** [MN-Script-Team/DHS-MAXIS-Scripts#2392]
It would be a good idea to pause on the XFER screen during dev mode to insure that the right information is being entered into XFER. I can tackle this.

**Comment by theVKC** [comment]
*Wright is usually capitalized because it's a county. :P

**Comment by CDPotter** [comment]
I must have Phoenix Wright on the brain again. Whoops!
