### ISSUE TITLE
Bug on Notices - Postponed WREG Verification - Date format

### ISSUE THREAD

**Issue by C-Love** [MN-Script-Team/DHS-MAXIS-Scripts#2393]
There is an error with a function used (I think it might be the ten day function) where a warning box pops up saying that 7//16 is not a valid date. I have done very little research into why this is happening other than to find that it does repeat. Some date format issue. 

Not critical as the script does continue and complete but worker needs to input the ten day date manually. This is why I think it is an error in that function. I am guessing either the month is somehow defined as 7/ instead of 07 OR the day portion is not defined somewhere. 

Sorry, I am unhelpful, it's been a long day.

**Comment by CDPotter** [comment]
Ah I bet that's the leading 0 issue... where some versions of bluezone save the leading 0 if read and others don't. I bet adding some leading 0 handling for datepart"(m" should work. If I updated the code could you test it?

**Comment by theVKC** [comment]
I think our issue is here (104-106):

```vb.net
EMReadScreen app_date, 8, 10, 33
app_date = replace(app_date, " ", "/")
CALL navigate_to_MAXIS_screen("STAT", "MEMB")  'grabbing client's name
```

The replace function doing two "/" marks makes me think something on PROG isn't reading correctly. Perhaps it sees a 0 and thinks it's blank. A simple way to test this would be to test it on a case that was approved after the 10th of a month. At the very least, MsgBoxing through it should illuminate the issue.

@C-Love is taking this on. Thank you!!!

**Comment by RobertFewins-Kalb** [comment]
@CDPotter and I had a little think on this...mayhaps an update to the function to work with the function `MonthName` would allow the script to handle both "07" and "7" for the footer month. Within the function...

`FUNCTION ten_day_cutoff_check(MAXIS_footer_month, MAXIS_footer_year, ten_day_cutoff)
     'getting rid of slashes that are hanging out and formatting to numeric
     MAXIS_footer_month = replace(MAXIS_footer_month, "/", "")
     MAXIS_footer_month = MAXIS_footer_month * 1
     IF MonthName(MAXIS_footer_month) = "January" AND MAXIS_footer_year = "16" THEN ... `
