### ISSUE TITLE
bug with Krabappel age calculation

### ISSUE THREAD

**Issue by RobertFewins-Kalb** [MN-Script-Team/DHS-MAXIS-Scripts#2396]
I take the blame for this -- the way the training case generator is creating client's date of birth is incorrect. It is making clients a year too old. I have a fix ready.

**Comment by theVKC** [comment]
You got it, and thank you!

@C-Love, can you make sure your scenarios account for this?

**Comment by C-Love** [comment]
I think we should be good. Not seeing any huge impact.

**Comment by theVKC** [comment]
@RobertFewins-Kalb, can you take a look at what @C-Love reported? She has 20+ scenarios built for Ramsey and is in-the-middle of deploying this process to their trainers. If it's not making a difference, perhaps the bug is elsewhere?

**Comment by RobertFewins-Kalb** [comment]
Not sure I understand @C-Love's error report. What the script was doing was subtracting 1 from the year of birth, making the client one year older than requested.

**Comment by theVKC** [comment]
@RobertFewins-Kalb and @C-Love: I am not seeing the bug in practice myself. Looking through my cases it seems everything was created as I expected.

@RobertFewins-Kalb and @C-Love, can you connect offline and discuss the bug? I'll leave the issue open until Friday, and if not resolved by then I'm closing it. I'm also closing pull request #2397. @RobertFewins-Kalb, if we determine your pull request resolves this bug per @C-Love and my testing, after you both discuss it, we can reopen it.

**Comment by RobertFewins-Kalb** [comment]
If you make a scenario with a 5 y/o and make their birthday 01/01, they will come across as being 6 in MAXIS. This is what started the pull request.
