### ISSUE TITLE
Closed Progs HC rein verbiage

### ISSUE THREAD

**Issue by CDPotter** [MN-Script-Team/DHS-MAXIS-Scripts#2400]
Time for this topic again!

The verbiage in the dialog is causing confusion. 

"This script does not case note REIN dates for HC, due to the ever changing nature of these programs at this time. MAGI clients have up to **three months** (follows retro application policy) after case closure to turn in their renewals and have eligibility determined. They can also reapply online using METS. "

Clients have 4 months to be reinstated. 

Since these rules keep changing faster than we can keep the scripts accurate I propose we change it to:

"This script does not case note REIN dates for HC, due to the ever changing nature of these programs at this time. Please refer to current policy."

**Comment by theVKC** [comment]
I agree, let's get rid of it.
