### ISSUE TITLE
Default footer month date needs to be removed from new BULK scripts

### ISSUE THREAD

**Issue by IlseFerris** [MN-Script-Team/DHS-MAXIS-Scripts#2405]
In my less than infinite wisdom, I added a default date of CM - 1 (since this is when most of these cases need to be reviewed). Unfortunately this means that users cannot select their own month. 
Needs to be removed from BULK list: 
* GRMR
* MONT
* MAMS
*  MRSR

Assign to me, pulling in a fix momentarily. I will also pull this into the release branch if necessary as well.

**Comment by theVKC** [comment]
Nope, not critical. Just master is fine.
