### ISSUE TITLE
Call for input: removing description from MAIN MENUs

### ISSUE THREAD

**Issue by theVKC** [MN-Script-Team/DHS-MAXIS-Scripts#2411]
So, here's an idea that I just had: remove the description from MAIN MENU scripts. The reasons:

1. There is a limit to the number of controls we can have in a script. My update to add SIR links (#2159) has broken some larger scripts. I appear to be able to fix it by changing the name of every single dialog, but that's... challenging.
2. There are now a lot of scripts. A lot more when the main menu process was invented. I'm thinking that if we use a grid-based format, and remove descriptions, it would be very easy to display many more script files (less clicks).

Here's what I think it'll look like when you click the instructions button under this process:
![image](https://cloud.githubusercontent.com/assets/5701751/16699282/df6914bc-4518-11e6-9fa4-8998e782cc0b.png)

I like this because it'll remove the "description" controls, and condense the script buttons into fewer menus. I would like some feedback from you-all @MN-Script-Team/county-agency-scriptwriters.

**Comment by CDPotter** [comment]
I'm assuming this also helps with the dynamicizing things? It would definitely pull the rug out from some people who need the descriptions to help them pick the script. Had a worker who didn't know what the Combined AR script was until he read that AR stood for annual renewal. 

I guess my biggest concern would be people who wouldn't bother to try a script if it didn't have a blip next to it.

**Comment by theVKC** [comment]
It does help make things more dynamic. We could also change the name of some scripts to make them more descriptive (that might be warranted anyway, see Projects Bowie and Gorbachev).

**Comment by CDPotter** [comment]
Overall I think it's a good idea I'm just anticipating some push back from certain Anoka end users who don't like change. Ultimately we can't halt progress for the sake of keeping an UI that isn't working for us anymore. So I like it!

**Comment by RobertFewins-Kalb** [comment]
I like that a lot. I don't know how many users are digging too deep into the description and this could be a quick and easy way to give them some good info.

**Comment by theVKC** [comment]
We can also use longer descriptions with this. The description in a main menu at present is only about a sentence. With a MsgBox we can make it much longer if needed.

**Comment by theVKC** [comment]
We discussed this at hackathon today, and it's a go.

This is part of #2159 and https://github.com/MN-Script-Team/BZS-FuncLib/issues/163.

Closing this issue, will add to test branch for the above.
