### ISSUE TITLE
End Approved Programs Script - have it end in the Case Note

### ISSUE THREAD

**Issue by C-Love** [MN-Script-Team/DHS-MAXIS-Scripts#2415]
I am finding that having the Approved Programs script end at WCOM is not a benefit. I would like this to go back to ending on the case note. 
- I prefer to be able to read through my case note once it is written and ending the script there allows me to do that. 
- The process is to add a WCOM before running Approved/Closed/Denied and I often use a script to do that anyway so being navigated there does not benefit my work process that much. 
- SPEC/WCOM also tends to be picky about footer month and I find that for intake cases the navigation ends me in a footer month that does not actually hold a notice to which I can add a WCOM. 

Can we go back to what it was before?

@tdahl21

**Comment by theVKC** [comment]
I would like to see a reminder pop-up at the end.

**Comment by theVKC** [comment]
Tagging this with the July release. @C-Love, if there are no objections, would you like to do this pull request to reverse it?

I will hold this for a week (folks here at hackathon were strongly in favor of returning to the old process), and would like to reverse it by Friday (enhancement deadline).

**Comment by IlseFerris** [comment]
I am submitting a pull request for approved programs this morning, so I can take care of removing this.

**Comment by theVKC** [comment]
Go forth @IlseFerris!
