### ISSUE TITLE
Notices - Appointment Letter enhancement

### ISSUE THREAD

**Issue by StormageddonDLOA** [MN-Script-Team/DHS-MAXIS-Scripts#2426]
My supervisor is wondering if we can have the notice that goes to the client to include "you must have a photo ID"?

Or if "must" is going to cause an issue then word it as "Please bring a photo ID to your interview."

**Comment by IlseFerris** [comment]
You cannot require a photo ID, only identification.

**Comment by theVKC** [comment]
We are absolutely not allowed to specify the type of identification allowed for this function. Sorry @StormageddonDLOA.

**Comment by StormageddonDLOA** [comment]
That’s why I added the last part to the issue idea. “Please” doesn’t say “must”.

Timothy DeLong, Financial Worker
Stearns County Human Services
705 Courthouse Square
St. Cloud, MN 56303
320-650-5842

**Comment by StormageddonDLOA** [comment]
The last part of my issue addressed that.

Why can’t we request they bring in a photo ID without saying it’s mandatory?

Timothy DeLong, Financial Worker
Stearns County Human Services
705 Courthouse Square
St. Cloud, MN 56303
320-650-5842

**Comment by StormageddonDLOA** [comment]
We could even word it as “please bring a photo ID if you have one.”

Timothy DeLong, Financial Worker
Stearns County Human Services
705 Courthouse Square
St. Cloud, MN 56303
320-650-5842

**Comment by theVKC** [comment]
It's a SNAP stickler point. By suggesting the one document, it could be considered oververification or could imply that a photo ID is mandatory. I've tried to get stuff like this included before and it gets shot down pretty easily as an error.

Essentially, here's the bottom line: Appointment Letter text absolutely cannot be changed without first consulting with SNAP policy.

**Comment by StormageddonDLOA** [comment]
OK, I’ll let her know. ☺

Timothy DeLong, Financial Worker
Stearns County Human Services
705 Courthouse Square
St. Cloud, MN 56303
320-650-5842

**Comment by theVKC** [comment]
Thanks @ruthmaloney!
