### ISSUE TITLE
Bug NOTICES Method B WCOM

### ISSUE THREAD

**Issue by CDPotter** [MN-Script-Team/DHS-MAXIS-Scripts#2433]
other health insurance is written twice in WCOM, it should also only grab the medicare premium if it is coded as Y for apply premiums to SPDN/BUDGETS on MEDI. Fix incoming.

**Comment by theVKC** [comment]
We're under a script freeze, @CDPotter...

**Comment by theVKC** [comment]
I suppose this is a bug and not an enhancement. My bad.

**Comment by CDPotter** [comment]
I'd say it's non-critical so we can sit on it till later? The worst part is its writing health insurance twice on a notice as a deduction leading to faulty math being written and client confusion.  (nothing that can't be solve by a once over from a worker while we wait)

**Comment by theVKC** [comment]
No worries, I'll pull it. It's a bug, enough of a bug to where I'll let it through this time. :)
