### ISSUE TITLE
CAF notes indicates wrong/incorrect ABAWD months information

### ISSUE THREAD

**Issue by kennyasalee** [MN-Script-Team/DHS-MAXIS-Scripts#2436]
This was submitted from a Ramsey County resource trainer, pertaining to a scenario when NOTES-CAF script was initiated. 

From worker:
"I think there is something wrong with the CAF script when it comes to ABAWD.  This client has not used any ABAWD months, yet the script wrote: “Second set of ABAWD months used:”……I assume it writes it like this (with a semi-colon) to indicate *if* any other ABAWD months have been used the number would be listed *after* the semi-colon, but having this language appear in the case note when there are NOT any additional months is confusing.  Just a suggestion or FYI in case is is an issue. "

In the case,  FSET Work Reg status is: 30. and ABAWD status: 10. and of course no months had been used in the ABAWD tracking record.

I believe the error is in the FUNCTION FILE:
FUNCTION autofill_editbox_from_MAXIS(HH_member_array, "WREG", notes_on_abawd)

and not in the NOTES-CAF file.

**Comment by IlseFerris** [comment]
I updated this function a week ago in the MASTER branch. It will be updated in the RELEASE branch next Monday. Here's the issue in the FuncLib if you want to take a look. https://github.com/MN-Script-Team/BZS-FuncLib/issues/262

**Comment by kennyasalee** [comment]
Oh Ok thanks @IlseFerris !
