### ISSUE TITLE
Update Case Note information in NOTES - EVF Received 

### ISSUE THREAD

**Issue by kaleykobber** [MN-Script-Team/DHS-MAXIS-Scripts#2437]
We had a worker report that the title of the case note is confusing. If the worker answers "no" to any of these three questions: Signed by client? Completed by employer? Additional Info requested? - the EVF should be "incomplete". 

But, the script only puts "incomplete" in the case note header if you answer "no" to: Completed by employer? In all other circumstances, it puts "complete" in the title of the case note, which might not be true if the release is needed from the client or if additional information was requested.

**Comment by theVKC** [comment]
Marked as help wanted. Any takers?

**Comment by asunderman** [comment]
Since I feel like a script slacker lately....  I'll take this.

**Comment by theVKC** [comment]
Good deal! We're in a script freeze, because I'm leaving SNAP to join Child Support, and @CDPotter is taking over my MAXIS GitHub duties. I presume @CDPotter will let you know when the freeze is over! :)

**Comment by CDPotter** [comment]
@asunderman How is things going with this?

**Comment by CDPotter** [comment]
We discussed this in length this morning and decided that complete/incomplete may not be the best way to label an EV. As such we think the header should be that we rec'd the EV the date, and then if someone says YES to additional information we add that to the header. This way the header is clear for anyone reviewing the case note. @asunderman Have you had a chance to work on this? If not I will relist as help wanted.

**Comment by CDPotter** [comment]
Reassigning to @MelissaFox-Stearns
