### ISSUE TITLE
Transfer Case script

### ISSUE THREAD

**Issue by jasont35** [MN-Script-Team/DHS-MAXIS-Scripts#2439]
There is a section on Spec/XFER County to County to enter in a date that the case file was sent. Could this be added to the script to fill in that section as well as adding the information to the case note?

**Comment by CDPotter** [comment]
Here at Anoka County (probably last time I'll be saying that) the workers aren't actually the ones to send out the case file (we submit a form and our office support staff actually send the file.).

What do other counties do?

**Comment by IlseFerris** [comment]
Hennepin county workers also submit a request to the OS staff to send the documents from the case file.

**Comment by jasont35** [comment]
I had that discussion with the worker that suggested this as well, and she stated that she waits to transfer the case until she knows that the case file is being sent out that day. I am sure this is being done differently in all counties as well as the fact that their are days when it was "planned" to be sent but doesn't get sent due to an emergency or other situations. This request might not be useful due to these reasons.

**Comment by CDPotter** [comment]
Yeah, I think it might make sense to leave it off. (the dialog is fairly jam packed already.) We can revisit it later if there's more interest in it. @jasont35 would you mind closing the issue? I am unable to at this point.
