### ISSUE TITLE
Script Que

### ISSUE THREAD

**Issue by StephanieW7** [MN-Script-Team/DHS-MAXIS-Scripts#2445]
Hello,

We are wondering if we you could select multiple scripts to run in a que sequence?  
For example: A worker could select the CAF, Approved OR Denied, and the explanation of income script to run one right after the other?

Thanks,
Stephanie

**Comment by CDPotter** [comment]
The idea is a bit more complicated but we are discussing and looking at options for it. If you'd like to track progress on it check out this issue. 

The main issue with chain loading scripts is it tends to overwhelm the system. We keep running into functional limitations while working on it, so it will take some time to get something solid working.
