### ISSUE TITLE
Remove BULK MAGI/NON MAGI report

### ISSUE THREAD

**Issue by CDPotter** [MN-Script-Team/DHS-MAXIS-Scripts#2447]
We just got word from DHS that we are to no longer used the BULK script as they are identifying Migration candidates on their own and publishing that report.

We have been asked by MNIT to remove the script to avoid confusion in people using the report the script generates to identify migration candidates. 

I'll be removing the buttons from MASTER and RELEASE now.

**Comment by CDPotter** [comment]
And apparently I need to learn how to use branches as Admin! So there's gonna be no pull on these ones as I accidentally committed directly to release and master. 

Issue resolved.

**Comment by theVKC** [comment]
Yup! Please use branches and labels, and assign yourself issues you're resolving. That way I can get stats if needed (and so can you). :)

**Comment by CDPotter** [comment]
I have much to learn about being on this side. =)

**Comment by IlseFerris** [comment]
#Adminlife

**Comment by theVKC** [comment]
[Pssst... you still didn't label it]
