### ISSUE TITLE
Enhancement -- NOTES - OVERPAYMENT for new cash policy

### ISSUE THREAD

**Issue by RobertFewins-Kalb** [MN-Script-Team/DHS-MAXIS-Scripts#2452]
Hey, so, we've got new cash claims policy. Agency error may not be collectible. Methinks we should have a new editbox on the dialog for NOTES - OVERPAYMENT to prompt workers to case note that information.

**Comment by CDPotter** [comment]
For more information: https://www.dhssir.cty.dhs.state.mn.us/MAXIS/Lists/MAXIS%20Announcements/DispForm.aspx?ID=1457&RootFolder=%2FMAXIS%2FLists%2FMAXIS%20Announcements

I would say people will want to see the calculation used to determine if we can collect, and whether or not we can. So maybe a dropdown box and an editbox? 

Anyone want it?
