### ISSUE TITLE
Enhancement: NOTES - CSR add GRH to programs selectable

### ISSUE THREAD

**Issue by LaLarson** [MN-Script-Team/DHS-MAXIS-Scripts#2453]
Hi!

I'm not sure if this is an enhancement or a bug, but here it is... We've had a request to have GRH added to the CSR script now that those recipients now use this form?? :)

If anyone has the time/knowhow to tackle this one, feel free... @CJOHNS356 and I can't at the moment as we are in the fires of the METS/migration netherworld.

**Comment by IlseFerris** [comment]
I can take this. @CDPotter, do you want me to pull this in for the August release?

**Comment by CDPotter** [comment]
If you can knock it out today please do!

**Comment by IlseFerris** [comment]
I can do that.
