### ISSUE TITLE
Enhancement - ACCT Updater - MsgBox about panel creation error

### ISSUE THREAD

**Issue by C-Love** [MN-Script-Team/DHS-MAXIS-Scripts#2465]
This is most certainly a user error proofing measure.

Basically if the script is run and the case can not be updated for some reason (inactive case or wrong member number entered) the new panel is not created or the existing panel is not updated and the script does not actually update STAT. The script continues as normal. 

It would be helpful if a message box were to come up to indicate that there was a problem updating STAT. The New Job Reported script appears to have this functionality and can probably be code hunted. 

If someone else could take this that would be fantastic.

**Comment by CDPotter** [comment]
Side issue, this script can't handle 10+ ACCT panels. I'll look at both of these.
