### ISSUE TITLE
Idea: if we can't create more than x dialogs, just keep recreating the same dialog

### ISSUE THREAD

**Issue by theVKC** [MN-Script-Team/DHS-MAXIS-Scripts#247]
So, there's a dialog max, right? Something like 6 or 7, and less in cases of scripts loading other scripts, right?

What if the elements of the dialog are pumped into a function, where we can change them dynamically? I.e. `If x = y then Dialog_function_omega(CAF_dialog)`? Then, our dialogs could contain the elements of the dialog itself, but always be referred to programmatically by the same dialog name. Wouldn't this hypothetically work the same way as dynamically changing the content of an editbox?

This has me all excited.

**Comment by RobertFewins-Kalb** [comment]
Here's the raw git. I have put it in my personal repo 

https://raw.githubusercontent.com/RobertFewins-Kalb/GitSome-at-Home/master/NOTE%20-%20CAF.vbs
