### ISSUE TITLE
Enhancement - Citizenship Scrubber  Category: DAIL Scrubber

### ISSUE THREAD

**Issue by x143626** [MN-Script-Team/DHS-MAXIS-Scripts#2470]
If possible, have the citizenship scrubber route the user back to the dail screen similar to how the other scrubbers work.

**Comment by CDPotter** [comment]
This seems simple enough, anyone interested in tackling this one?

**Comment by IlseFerris** [comment]
Assign this one to me and @senhorc, and we'll work on it together for the September release.
