### ISSUE TITLE
Enhancement - CAF Notes - check boxes for pkgs approved

### ISSUE THREAD

**Issue by x143626** [MN-Script-Team/DHS-MAXIS-Scripts#2471]
In the CAF notes, it would be nice to have check boxes for package(s) approved similar to the CSR verbiage regarding program(s) that are being recertified.

**Comment by CDPotter** [comment]
Are you talking about listing the programs acted in the case note? I believe it currently does that already.

**Comment by x143626** [comment]
Yes and No – the CAF script does ask which programs are being acted on, but the worker wanted something at the end of the script which would autopopulate with status and amounts for any program that had been completed. The attachment is of a CSR script autopopulating with completed benefit info. She would like to see something similar for the CAF script as well. Make sense?

**Comment by CDPotter** [comment]
Ah I see, I would hesitate to add this to the CAF at this time. Currently it's very bloated with features (to a functional limit actually). Our long term plan is to rework the CAF and create a workflow in which we can chain load scripts meaning you could select CAF and Approved programs (which has the autofill from ELIG feature) in one go. As such I'm going to close this issue for now. (Veronica is taking the lead on developing the workflow and going to share the code with us once she cracks it.)

**Comment by x143626** [comment]
Thank you, I think I do remember something along those lines about a year ago when someone else wanted to enhance the CAF script. I will pass this info along and try to retain it for future reference!
