### ISSUE TITLE
Main menu scripts: outdated "NEW" identifiers need to be removed

### ISSUE THREAD

**Issue by IlseFerris** [MN-Script-Team/DHS-MAXIS-Scripts#2474]
NOTES Main menu has several scripts back to 01/2016 that need to be updated,
NOTICES Main menu has one script to update.

I can take this one for the September release.

**Comment by CDPotter** [comment]
if it's the 04/16 one in Notices I asked Kenny to knock that out in pull #2469

**Comment by IlseFerris** [comment]
Sounds good. I'll take care of NOTES MM then. Thanks @kennyasalee and @CDPotter!

**Comment by theVKC** [comment]
Note that my new function for main menus does automatically add and remove the NEW!!! date. So, don't spend much time on this one if you can avoid it. :)
