### ISSUE TITLE
Call for input: CAF notes on income becoming mandatory

### ISSUE THREAD

**Issue by CDPotter** [MN-Script-Team/DHS-MAXIS-Scripts#2482]
With the increased need to make sure we are explaining our budgeting reasoning I think we should revisit making this field mandatory. We originally put the issue to bed after building Explanation of income and paystubs rec'd. However some end users are resistant to using multiple scripts. 

I'd suggest that if the earned income or unearned income fields are not blank then the worker must complete notes on income. They can then do something like "see paystubs rec'd", "see explanation of income case note", show their math, explain that the job/unea ended therefore n/a, etc. 

(side note it is already mandatory on paystubs rec'd)

Thoughts?

**Comment by Farleight** [comment]
I think there's a large population of workers out there who are against robots telling them what to do. My fear would be that as requirements for a script increase, the number of willing users of said script will decrease. That said, I am already not a willing user of this script, so my vote counts less than yours.

**Comment by courtrightd** [comment]
In order to try and meet ME reviewer guidelines, we have mandated using the other scripts to explain anything that can't quickly be explained in this field.  I already tell everyone to use this, we would embrace the mandate.

**Comment by theVKC** [comment]
*embrace the mandate* #NewBandNameICallIt

**Comment by C-Love** [comment]
This is a mandatory script in Ramsey and I would love to have some QC numbers to support that the errors are high here. I don't doubt you but the information that is coming to our workers is that the errors are in other places than explanation of income in case notes and it would be great to have something to support why having this field be mandatory could contribute to decreasing the error rate. 

Just my thought from my very loud workers that would not like things to slow them down

**Comment by CDPotter** [comment]
I hear ya, but if they don't have income to explain it won't slow them down any. If they do have income its' really for the best to take a moment to explain where those numbers on your panel came from. I usually just wrote something quick like "Using 3 paystubs provided I got average (100+10+20)/3=50 biweekly"

**Comment by Farleight** [comment]
I don't care how good your case note is. If it says 100+10+20 divided by 3 = 50, you're still gonna' get dinged. I understand the merit of it, but I will argue on behalf of the "very loud workers." Things like that are the very reason I don't use many of the scripts. I do a lot of processing and I don't care to be slowed down by a thing that is supposed to save me time. And in the majority of counties where scripts are not mandated, people will pick and choose the ones that they use, and I hate the idea of turning people away from something that could otherwise boost accuracy.

I'm really done now though. I promise. Carry on the conversation.

**Comment by CDPotter** [comment]
Whoops, that's what I get for early morning mathing. 

In playing devil's advocate the only reason it would slow someone down would be if they didn't write any notes on their income. I could see people only using the earned/unearned income fields and writing their notes in there but that would simply be a matter of changing where you wrote you not. 

I guess I'd say if people aren't already using the notes on income field then it's likely they're not writing sufficient case notes (unless they write their notes in the other fields), if they are already using it then they won't notice any interruption at all.

**Comment by CDPotter** [comment]
In talking with other county reps and viewing/doing some CAPERS and PARS reviews I think we definitely need to mandate it. I will take this one.
