### ISSUE TITLE
CRITICAL Changes to jobs/unea/schl

### ISSUE THREAD

**Issue by CDPotter** [MN-Script-Team/DHS-MAXIS-Scripts#2485]
MAXIS is getting some changes to these panels (installed 9/1/16 for benefit month 10/16)

JOBS: 
- New type codes include T - Training P - Service program and R - Rehab Program These will need to be accounted for. 
- There is also a new field around 6 60 "Hourly Wage" which needs to be read from when those 3 income types are used. 
-This new field seems to move the verif code to the left at 6, 34 and the income type code to 5, 34 (checking to see when this will be installed into MAXIS.)

UNEA
- New type codes include 18 - military training 47 - counted tribal income 48 - trust income 49 non-recurring income. These will need to be accounted for. 
- No other changes to panel presented.

SCHL
- New type codes include 10 - Post-sec tech schl student 12 adult basic ed 14 English as a 2nd language
- No other changes to panel presented.

So far we know we have to change paystubs rec'd as it writes to verif codes on jobs (location moved now), and banked month fiater. 

Can anyone think of any other MAXIS scripts that read type and verif codes (without the use of the autofill functions)

**Comment by CDPotter** [comment]
As an aside this is the fix I've found to be helpful for this issue with multiple versions of the panels available depending on the footer month

![fix for changes](https://cloud.githubusercontent.com/assets/7841989/17980155/a13e3656-6ac3-11e6-983a-e362cbe3f0f2.PNG)

**Comment by IlseFerris** [comment]
Here are the scripts that will need changes:  
ACTIONS     ABAWD Banked months fiater    job_type at 5, 38- verif code at 6, 38
ACTIONS     LTC Spousal allocation fiater    job_type at 5, 38
ACTIONS     New job reported(income type will need to be added to the droplist)     job_type at 5, 38, verif code at 6,38
ACTIONS     Paystubs rec'd(jobs verif code droplist will need to be updated)    verif code at 6, 38

**Comment by CDPotter** [comment]
Thanks for searching the scripts for me! I also remembered both new hire dails will need this as well. Here's hoping for a smooth Thursday next week!

**Comment by IlseFerris** [comment]
The new hire DAIL scripts just put a "W" in as a placeholder coding until the job verification is received. Based on that, I don't think we will need to update the DAIL scripts.

**Comment by CDPotter** [comment]
They both EMWrite to the old coordinates for the verif code and type codes. In any case I've got them all ready to go now. 

I'm going to hold off on updating the type droplists until we get a look at it and since that isn't really a critical issue.

**Comment by IlseFerris** [comment]
Gotcha :)
