### ISSUE TITLE
Adding EMPS panel field and info to NOTES - CAF

### ISSUE THREAD

**Issue by IlseFerris** [MN-Script-Team/DHS-MAXIS-Scripts#2487]
Two CASH programs (MFIP and DWP) rely on this information. Having this information in the CAF will help workers identify changes to EMPS info , and will create a record about what is happening on EMPS in the case note. 

I've been testing this and CAF dialog 1 can support this field. Does anyone have any objections to this addition?

**Comment by CDPotter** [comment]
Do you have a screen of the new dialog? 

What do others think?

**Comment by IlseFerris** [comment]
![image](https://cloud.githubusercontent.com/assets/10836829/18052351/82e3244c-6dbf-11e6-91f7-e446feb255ca.png)

**Comment by courtrightd** [comment]
This would be stellar.  You have my full support.

**Comment by IlseFerris** [comment]
Thanks for the feedback @courtrightd!

**Comment by C-Love** [comment]
DO IT!

**Comment by CDPotter** [comment]
I like it!
