### ISSUE TITLE
Banked Months FIATer needs enhancement for XFS Handling

### ISSUE THREAD

**Issue by C-Love** [MN-Script-Team/DHS-MAXIS-Scripts#2491]
Banked Months FIATer does not account for assets to correctly determine if a case is Expedited or not. 

I have not started on this yet, but I can work on it if no one else can.

**Comment by theVKC** [comment]
Filling in for @CDPotter today.

Since expedited is so important, would this possibly be a critical bug? If it is, would you mind pulling it in ASAP?

**Comment by C-Love** [comment]
I can see your point. I will not have it until Thursday at the very earliest. If anyone has time before that they can feel free. Otherwise I will look at it then.

**Comment by CDPotter** [comment]
Casey if while you're in there you could add some handling for the 10/16 changes? I think it would help reduce merge conflicts. 

I would think we just want to add the new types to the line on 485, and the hourly wage field SHOULD only budget for cash programs, and is only mandatory for J G T and R types.

**Comment by CDPotter** [comment]
@C-Love I just went ahead and added the new types. Please use the new version for your fix.
