### ISSUE TITLE
Enhancement: Change ABAWD exempt county list in banked month fiater

### ISSUE THREAD

**Issue by CDPotter** [MN-Script-Team/DHS-MAXIS-Scripts#2497]
I have seen the list but I am unable to make any forward facing changes until POLI/TEMP is updated. Once that happens I can make a change.

**Comment by IlseFerris** [comment]
This list is also in NOTICES - SNAP E & T Letter

**Comment by CDPotter** [comment]
Good to know! Thank you!

**Comment by CDPotter** [comment]
Ok the list has been published in 10/16 POLI TEMP (02.05.69)

The 13 counties are:

Aitkin
Cass
Clearwater
Hubbard
Itasca
Kanabec
Koochiching
Lake of the Woods
Mahnomen
Marshall
Mille Lacs
Norman
Wadena

This waiver is in effect until 9/30/17

I will update the ACTIONS - Banked month fiater and NOTICES - SNAP E&T letter, before 09/16 release.
