### ISSUE TITLE
DAIL - CSES Scrubber (the new one) not case noting.

### ISSUE THREAD

**Issue by courtrightd** [MN-Script-Team/DHS-MAXIS-Scripts#2500]
In testing this morning, multiple instances have been found where the script can't open a case note, because it hasn't made it back to the dail.  It happens when it is left on the UNEA panel for worker review, or a worker does something in MAXIS while a dialog is up.   Probably needs some sort of check to make sure it is on the dail before opening the note.

**Comment by IlseFerris** [comment]
I had a tester run into this issue this morning as well.

**Comment by CDPotter** [comment]
Would anyone be able to take a look at this issue?

**Comment by courtrightd** [comment]
I can work on it, I have some thoughts on a solution I will try this afternoon.

**Comment by CDPotter** [comment]
Awesome! I know @RobertFewins-Kalb 's users are testing it as well but he's having issue with github so I may have him forward you anything he finds.

**Comment by CDPotter** [comment]
@courtrightd how is this going?

**Comment by courtrightd** [comment]
Doing a bit of testing this morning, pull coming soon.
