### ISSUE TITLE
NOTES/Foster Care HCAPP ~ Addl boxes/fields for HH comp and assets

### ISSUE THREAD

**Issue by ALJ10** [MN-Script-Team/DHS-MAXIS-Scripts#2509]
Per the request of a financial worker and supervisor...
I am requesting that text boxes be added for HH comp and assets to the Foster Care HCAPP NOTES script.
****
Please let me know if that is a possibility. Thank you!

**Comment by CDPotter** [comment]
Anyone interested? or does anyone have any input?
