### ISSUE TITLE
NOTES / Combined AR ~ Case/note not including program that's being recertified....

### ISSUE THREAD

**Issue by ALJ10** [MN-Script-Team/DHS-MAXIS-Scripts#2512]
A few financial workers are reporting that the Combined AR script is not including the program being renewed in the case/note.  So they've been manually typing in the program on the 1st line. I'm not sure if there's a glitch with the script or if there's a reason it's not included. So I thought I'd report it just in case. Please keep me posted! Thank you!

**Comment by CDPotter** [comment]
This is indeed a problem! The checkboxes aren't attached to anything, @MelissaFox-Stearns has volunteered to look at it!
