### ISSUE TITLE
NOTES - GRH - HRF and NOTES - GRH -non HRF post pay: do we still need these

### ISSUE THREAD

**Issue by IlseFerris** [MN-Script-Team/DHS-MAXIS-Scripts#2514]
Looking for some direction about these scripts. Since the NOTES - CSR has been updated to accommodate  6 month reporting for GRH case, can deleted NOTES - GRH HRF? 

Then is the NOTES - GRH non HRF post pay script still necessary for GRH workers?

**Comment by CDPotter** [comment]
Per GRH person here: 

1.	Notes GRH NON HRF post-pay script will still be needed for people that do not have earned income and short term stay clients (30 days or less).
2.	I do not see any reason someone would use the Notes – GRH HRF script anymore since HRF’s are not needed for GRH anymore.
