### ISSUE TITLE
REVS Scrubber is not scheduling some MFIP cases

### ISSUE THREAD

**Issue by C-Love** [MN-Script-Team/DHS-MAXIS-Scripts#2534]
We have had reports of some cases not being included in the scheduling using REVS Scrubber. 
It appears to only be MFIP cases at this point. 

The main issue appears to be if the SNAP recert date is the same as the MFIP recert date on REVW - the script sees that a SNAP revw is due but when it checks PROG it finds that SNAP is not active and kicks it off the list in error. 

I just discovered the issue and don't have a solution but I am working on it. I propose this could go through the freeze? I would hate for another month for the script to miss cases. 

I do have a question - is there a reason for the ordering of the script - I mean - is there a reason it does not determine which programs are active BEFORE going to REVW? It seems like we could customize what the script would look for on REVW better if it knows what programs it needs to REVW. I know this was a big project that I was only a part of at testing, so you may have run into other issues with that order that I am not foreseeing.  @CDPotter  @RobertFewins-Kalb @IlseFerris @theVKC

**Comment by CDPotter** [comment]
Bug fixes are always welcome during script freeze.

As for a reasoning for that I'm afraid I don't recall. I know I ran into some issues with identifying MFIP vs MSA months back.

**Comment by C-Love** [comment]
Well - I will just start in on a fix and see if I can get it working SOON.

**Comment by CDPotter** [comment]
Thank you! Good luck, it's a beast of a script!

**Comment by C-Love** [comment]
Ok - I have this done. I want to test is a little more - I will pull in on Thursday.
