### ISSUE TITLE
Call for Input: REVS Scrubber double booked appointments

### ISSUE THREAD

**Issue by C-Love** [MN-Script-Team/DHS-MAXIS-Scripts#2537]
We have had a few workers that accidentally have their appointment times in the morning and afternoon overlapping and the script basically double books their appointment. We could try to figure out how to error proof this a little...

Thoughts?

**Comment by CDPotter** [comment]
Is it because people are clicking the double book checkbox or is it a bug?

**Comment by C-Love** [comment]
No, they aren't clicking the double book option. It is user error from what I can tell - I don't think it is a bug. What happens is the worker selects their appointments to run from 10:00 AM - 1:00PM every hour and 12:00PM - 3:00PM every hour - so then there are 2 appointments booked for 12:00 and 1:00. 

Our only task could be to add some handling to warn workers of this overlap.

**Comment by CDPotter** [comment]
Ah I see, it's been a few months since I ran it but didn't we add a excel spreadsheet to review the times beforehand? 

That said it might be something to look into.

**Comment by C-Love** [comment]
Yes, there is most certainly an Excel spreadsheet that lists all of the cases and their appointment times, a message box even comes up alerting workers to review it BEFORE having the script continue and actually send out notices and such. 

This would be a worker error proofing measure. We can do some REVS scrubber discussion at hackathon.

**Comment by CDPotter** [comment]
I think with the current safeguard showing the worker exactly what appointments are going to be scheduled we don't need to add a fix to the already complicated appointment determining code.
