### ISSUE TITLE
Call for input: Adding verbiage to worker_sig to indicate a script was run

### ISSUE THREAD

**Issue by CDPotter** [MN-Script-Team/DHS-MAXIS-Scripts#2546]
I'm getting a lot of questions from reviewers wondering "Was this case note I'm looking at generated by a script?"

I was thinking we could add something to the end of script such as "This note was generated by name_of_script". That way people who are unfamiliar with spotting script generated case notes would be able to know how the information was compiled. 

Few concerns I have:
1: I worry people might assume the case note has 0 worker input, but maybe verbiage could clear that up.
2: Implementing might be tricky. My first thought was slap it on the back of worker_sig in funclib but that means all the "if worker_sig = ""s" would have to be changed... We couldn't add it to Script_end_procedure since that isn't always in a case note at the end. This would likely involve editing every script that case notes. 

Anyway what are the thoughts of others?

**Comment by RoberT-1000** [comment]
Would it be easier for the reviewers to know which headers and case note structures are going to be from scripts and which are going to be manually created?

**Comment by RoberT-1000** [comment]
(or more effective, rather than easier)

**Comment by theVKC** [comment]
I was thinking what @RoberT-1000 said, that it may be easier to provide a list of headers. I would say that the presence of the asterisk-style-bullet-points and the "---" above the signature was designed to be a simple giveaway that a script was in-fact used (because most workers don't write like that). Admittedly, that assumption might be flawed now that so many workers use scripts everywhere.

**Comment by CDPotter** [comment]
I agree but my initial thought was to say that when you see the *** you know it's a script but in showing my examples (Paystubs rec'd, new job reported, and CAF) I got four different headers:

New jobs : >>>
Paystubs: ~~~(for PIC note) and nothing for regular note
CAF: ***

I also suggested that people look for the --- near worker sig, or the "* " format for data being entered into the body.

**Comment by RoberT-1000** [comment]
I would be down for a single custom function that writes the header consistently...

`write_header_to_case_note(header text)`

Then we just agree to a single three character combo to rule them all.

**Comment by theVKC** [comment]
I'm very open to such a custom function. I also think a worker signature function might be helpful. We could use them both in PRISM and MAXIS if we do it right (I'm dreaming of a new unified function for writing to CAAD or CASE/NOTE or MEMO or DORD or anything else, but that might be a while).

**Comment by CDPotter** [comment]
In discussion here at hackathon we are going to go with building a document to help reviewers identify script assisted case notes.
