### ISSUE TITLE
Bug -- ACTIONS - BANKED MONTHS FIATer

### ISSUE THREAD

**Issue by RoberT-1000** [MN-Script-Team/DHS-MAXIS-Scripts#2548]
We are getting "Script Error at Line 1, Column 1: Expected 'Then'" when running the Banked Months FIATer

**Comment by CDPotter** [comment]
Looks like an or got attached to a _ I can fix.

**Comment by RoberT-1000** [comment]
You are quick! I was just about to say, "Line 130...I will submit a fix."

Thank you, sir!
