### ISSUE TITLE
Make notes on income mandatory on CSR 

### ISSUE THREAD

**Issue by CDPotter** [MN-Script-Team/DHS-MAXIS-Scripts#2551]
Since it's mandatory on CAF it makes sense to have the CSR follow suit. (post freeze) Anyone want it?

**Comment by RoberT-1000** [comment]
Sure!

**Comment by RoberT-1000** [comment]
OK...after the last pull request...should I do this now or wait?

**Comment by CDPotter** [comment]
You're fine to do it now, we are out of script freeze. I just was just clarifying why I wasn't going to ask you to pull the revw/mont fix into release.

**Comment by RoberT-1000** [comment]
Gotcha!
