### ISSUE TITLE
SNAP E & T Critical bug: typo throwing Line 1 error

### ISSUE THREAD

**Issue by IlseFerris** [MN-Script-Team/DHS-MAXIS-Scripts#2561]
Line 262 is throwing an error that disables the script. A space will fix it. 
Also the date of the exemption ending needs to be updated from 09/30/16 to 09/30/17, and manual address entry needs to be disabled for counties that are now exempt. 

Assign to me. I will pull a fix in master and release momentarily.

**Comment by CDPotter** [comment]
Coulda sworn I fixed that recently.
