### ISSUE TITLE
New script: ACTIONS - ABAWD MINOR CHILD EXEMPTION FIATER

### ISSUE THREAD

**Issue by IlseFerris** [MN-Script-Team/DHS-MAXIS-Scripts#2569]
POLI TEMP: TE02.05.70.03 - ABAWD STAT/WREG CODING- CHILD UNDER 18--has a documented process to follow when FIATing non-parents in the SNAP HH when the SNAP HH contains a minor child. 

This is a very error prone errors especially in cases where the eligibility workers are adding changes to income and/or expenses since those are not being carried over into the new budget.

Assign to me for the October release.

**Comment by IlseFerris** [comment]
Let's push this to the November release. I want another month to test locally.

**Comment by CDPotter** [comment]
@MN-Script-Team/maxis-scriptwriters can we get some testing on this?

@IlseFerris Could you post instructions to SIR?

**Comment by IlseFerris** [comment]
I'll work on them today

**Comment by courtrightd** [comment]
We have run this twice in the real world today, working great so far.

**Comment by IlseFerris** [comment]
Thanks for the confirmation @courtrightd! I have local testers running it today with success.
