### ISSUE TITLE
Enhancement to County Burial AND Call for Input

### ISSUE THREAD

**Issue by C-Love** [MN-Script-Team/DHS-MAXIS-Scripts#2577]
Missing fields to do with where the money is going and does no autofiling currently. Needs a little enhancement to make it more useable. As this process takes place majorly outside of MAXIS and is fairly county specific, the script will be fairly open (not have many mandatory fields). 

I am working on this. 

I do have one question - would it be beneficial to have the option for the script to generate a word document with some information on the case? Seeing as workers don't really have a case file for these - just wondering if and output of some kind in the event that the determination cannot be made, the worker could have a single page summary of action already taken/information on the case.

**Comment by CDPotter** [comment]
I think that could be helpful, maybe as a checkbox option?

**Comment by C-Love** [comment]
Yeah - that's what I was thinking.
