### ISSUE TITLE
Enhancement NOTES Explanation of income budgeted: self employment budget method noting

### ISSUE THREAD

**Issue by CDPotter** [MN-Script-Team/DHS-MAXIS-Scripts#2578]
One of the issues ME reviewers are seeing is workers not documenting that the client agreed to the self employment budget method used. Since the CAF and other similar scripts are rather bloated I'd hate to add a checkbox for something like this. My thought was to add a checkbox to the explanation of income budgeted script. 

Maybe something like this:

![capture](https://cloud.githubusercontent.com/assets/7841989/19078544/1cd5aaee-8a16-11e6-8e6c-97e02c89e223.PNG)

That case notes: "\* Client agreed to self employment budgeting method" if checked. 

Thoughts?/Anyone want it?

**Comment by C-Love** [comment]
Think that is a good idea BUT I don't think that will be sufficient to improve the outcome - this script does not get a ton of use. It would be really helpful on the CAF, CSR and HRF. 

What if we had a vbYesNo in the autofill function for BUSI? Then the worker is just asked that question in the middle of the script looking at an existing BUSI panel.

**Comment by CDPotter** [comment]
Ooohh I like that!

**Comment by C-Love** [comment]
RE-Open ME!

We are going to create a button by the notes on income field that will start a dialog with checkboxes that will have preselected options for filling in the income notes field.

**Comment by C-Love** [comment]
OK - I need input. What are common and encouraged inputs for Notes on Income or Explanation of Income Budgeted?

Here is what I have:
![notes on income dialog](https://cloud.githubusercontent.com/assets/13418322/19489411/ccbbe02a-9530-11e6-81ad-0beade9a165d.JPG)

What else should be in that big empty space?

**Comment by CDPotter** [comment]
Maybe:

Client has confirmed that BUSI income is reasonably certain to continue as budgeted.
Client has confirmed that RBIC income is reasonably certain to continue as budgeted.
Client has confirmed that UNEA income is reasonably certain to continue as budgeted.

**Comment by C-Love** [comment]
So logical @CDPotter  - for sure.

**Comment by Farleight** [comment]
I like the language... admittedly, I'm not a fan of the concept as a whole, but I've come to realize that most script-writers are less concerned about plausible deniability than I am. You all seem to want "technical accuracy." Shame really... well-documented case notes can only lead to overpayments.
