### ISSUE TITLE
CAF Intake Bug

### ISSUE THREAD

**Issue by atroke** [MN-Script-Team/DHS-MAXIS-Scripts#2579]
I was doing a script on a new application – chose caf, intake and also tried it doing caf recert and both times – when I got to the page 2 regarding income, unearned income, etc.    it wouldn’t let me continue, prompt came up saying that stat panels show income and need to put in info for income.   There was no stat/unea or jobs panels in maxis.   Tired to put none in, tried to put other things and it just kept saying need to put in income.   I couldn’t get past that part.   It gave me a yes no  at the bottom so I said no and then it went in to scrolling the stat panels again and then jumped to next page where you put in fmed/fiat info.   Then it saved to maxis.

**Comment by CDPotter** [comment]
Are you sure the earned income and unearned income fields didn't have something written in them? If there is a jobs or rbic or busi or unea panel for the worker select household member it would be populated on the Earned income or unearned income fields. 

![capture](https://cloud.githubusercontent.com/assets/7841989/19085108/b6e285d6-8a2e-11e6-87bd-12e69801f8e5.PNG)

If this doesn't answer the question please email me a case number so I can take a look at the case.

**Comment by atroke** [comment]
Per the worker who worked on the case she states:

No, there is no STAT panels for those areas, there is a STWK panel.  The field “earned income” populated blank.   But it wanted something in there.   Case number is 1504760.

**Comment by CDPotter** [comment]
Please do not post case number on Github. It is a public forum. 

Looking at the case note the worker wrote NONE in the earned income and UNEA fields. By writing non the script read the fields as "NOT BLANK" and therefore assumed they were filled with earned/unearned income information and demanded a "notes on income" field to be completed.

**Comment by CDPotter** [comment]
Running the script myself on the case I was able to get through just fine by leaving the earned and unearned income fields blank. I'm chalking this one up to the worker writing NONE in the blank fields.
