### ISSUE TITLE
CSES Scrubber - Possible Enhancement

### ISSUE THREAD

**Issue by LaLarson** [MN-Script-Team/DHS-MAXIS-Scripts#2580]
Hello!

I just ran the new scrubber on CSES DAILS for a case.  Members 03 & 04 both have CSES budgets/panels but there were no DAILS for them this month, thus probably no CS received. In this case $0.00 is potentially a "normal income fluctuation" for them, but lets say it wasn't.... Would the script know that in some way?? Would that be pointed out to the worker?? Should it be checking all people, not just the PMI's found on the DAIL?

**Comment by courtrightd** [comment]
This seems to start getting at the SNAP end of this for accuracy.  Have the script check all existing UNEA - CS panels, and compare amount budgeted to dail amount, ask worker if they want to update.  I like it.

**Comment by CDPotter** [comment]
@MN-Script-Team/maxis-scriptwriters Is this something we would still like to see?

**Comment by C-Love** [comment]
To be handled once conversion is over.
