### ISSUE TITLE
New Script -- Wage Match (wink wink) DAIL scrubber

### ISSUE THREAD

**Issue by RoberT-1000** [MN-Script-Team/DHS-MAXIS-Scripts#2583]
Anoka has been running a script that brings "wage match" and JOBS information for the quarter in question and the budget going forward to the financial worker similar to the BNDX scrubber. It's a good'un and I have been meaning to share for a while. The output looks like this...

![image](https://cloud.githubusercontent.com/assets/22157633/19092401/10ec98e2-8a4c-11e6-861a-90fb25eaf00a.png)

And then the user gets to make their own decision.

**Comment by C-Love** [comment]
nudge nudge
