### ISSUE TITLE
Enhancement - Drug Felon

### ISSUE THREAD

**Issue by C-Love** [MN-Script-Team/DHS-MAXIS-Scripts#2591]
Enhancement request to have the NOTES-Drug Felon script more comprehensive to address all aspects of the process and follow-up for both when initially reported from the list and when selected for drug testing and then the follow up for these processes. 

I will be working on this soon - should be ready by Nov release.

**Comment by CDPotter** [comment]
@C-Love Could you update instructions/add new ones on SIR? 

@MN-Script-Team/maxis-scriptwriters could I get some testing on Master branch?

**Comment by C-Love** [comment]
Absolutely. Working on them now.
