### ISSUE TITLE
Enhancement for BULK ADDR

### ISSUE THREAD

**Issue by C-Love** [MN-Script-Team/DHS-MAXIS-Scripts#2592]
Request to add an indicator in the report for 'homeless'.

Either Kenny or I will be working on this at some point - no ETA.

**Comment by CDPotter** [comment]
@MN-Script-Team/maxis-scriptwriters This is in MASTER now, could I get confirmation that it is working?

**Comment by IlseFerris** [comment]
Confirmed, working in master. Although if it's not complete it shows the underscore instead of being blank.

**Comment by C-Love** [comment]
Confirmed it is working. I did not come across any blanks.

**Comment by CDPotter** [comment]
Thanks! I think I'm going to pull it through with the underscores, it highlights the error on the case just as well as a blank.
