### ISSUE TITLE
New ACTIONS script to help clean up stat

### ISSUE THREAD

**Issue by C-Love** [MN-Script-Team/DHS-MAXIS-Scripts#2602]
A script that will guide a worker through updating and removing STAT panels so that cases are cleaner and easier to work with and update. This can find blanks in required fields of STAT panels and use panel dates and the application dates and panel types to identify panels that need review and possible deletion. 

Worker will still make decision, the script would identify potential problematic panels.

Kenny or I will work on this at some point. No ETA at this time.

**Comment by Farleight** [comment]
I like this very much. Even digital clutter bothers me.

**Comment by IlseFerris** [comment]
This is a fantastic idea!

**Comment by C-Love** [comment]
I am working on this now. I have a spreadsheet that I am going to use to track all the panels and what should be done with them/ what retention exists, etc. Who is willing to look at/contribute to my spreadsheet? @IlseFerris @Farleight  @courtrightd @RoberT-1000 ???

**Comment by C-Love** [comment]
Also @ruthmaloney  - could you offer any input from DHS - or could you refer me to someone I could reach out to on this. I foresee some conflicting ideas here.

**Comment by Farleight** [comment]
I can check it out. Not sure how much help I'll be on the retention side. I only know the little bit that's mentioned in various policy bulletins, and those don't always reflect real life.

**Comment by ruthmaloney** [comment]
Sorry for the delayed response. I’m checking into it. I agree that some could get complicated.

Ruth Maloney

**Comment by ruthmaloney** [comment]
Hello,

Please forward the request to Barb.Martin@state.mn.us<mailto:Barb.Martin@state.mn.us> and copy Kevin.Lee@state.mn.us<mailto:Kevin.Lee@state.mn.us> .

Thanks,

Ruth Maloney


Caution: This e-mail and attached documents, if any, may contain information that is protected by state or federal law. E-mail containing private or protected information should not be sent over a public (nonsecure) Internet unless it is encrypted pursuant to DHS standards. This e-mail should be forwarded only on a strictly need-to-know basis. If you are not the intended recipient, please: (1) notify the sender immediately, (2) do not forward the message, (3) do not print the message and (4) erase the message from your system.

**Comment by C-Love** [comment]
I still love this but we probably don't need to prioritize this prior to conversion. Add this as an issue to the Python Repo once it is ready for issues.

**Comment by C-Love** [comment]
To be handled once conversion is over.
