### ISSUE TITLE
New Script - Budget Estimator

### ISSUE THREAD

**Issue by C-Love** [MN-Script-Team/DHS-MAXIS-Scripts#2604]
Create a script that allows for input of budget parameters that will give an estimated elig/inelig and benefit amount. This will NOT case note, just give worker some overview information about how different information/changes will impact the budget.

Kenny or I will take this at some point. No ETA at this time.

**Comment by StormageddonDLOA** [comment]
If no one minds I'll take a stab at this.

**Comment by C-Love** [comment]
This is very dialog heavy and will need a complete rewrite into Python basically from scratch. Will reviwe after conversion is complete. 

On a good note this should be significantly easier with wx.

**Comment by C-Love** [comment]
To be handled once conversion is over.
