### ISSUE TITLE
ACTIONS - Copy screens to Word: add INFC screens?

### ISSUE THREAD

**Issue by theVKC** [MN-Script-Team/DHS-MAXIS-Scripts#261]
Seems logical. Any takers?

**Comment by RobertFewins-Kalb** [comment]
Procedural question -- are we even allowed to send INFC panels? As I understand it, those are not our verifications to send out.

I recommend closing this issue.

**Comment by theVKC** [comment]
I believe you can give it to the client. But, if nobody responds to your bump today I'll close it.
