### ISSUE TITLE
Enhancements to REVS Scrubber

### ISSUE THREAD

**Issue by C-Love** [MN-Script-Team/DHS-MAXIS-Scripts#2610]
We have been using REVS Scrubber quite a bit and have some enhancements for it. 

We need to add an array to reduce potential errors and missed notes etc. This needs to be a big old beautiful array. 

Now we can add outlook back as an option! 

Randomize the list order so that all the same names are not on the same day.

Add a few fields to the Excel list - client name, language, interpreter Y/N.

Kenny or I will be doing this soonish. No ETA at this time.

**Comment by kaleykobber** [comment]
Also, add a field to the Excel list that lists the day of the week of the appointment (in addition to the date). This would hopefully flag a worker if they accidentally scheduled an appointment on a Saturday or Sunday, or a regularly scheduled day off.

**Comment by kaleykobber** [comment]
Another request! This is for the NOMI DAIL scrubber script. Is it possible to add an additional pop-up window listing the possible reasons the NOMI is being sent? Ex. CAF not received, unable to reach client (no phone number, phone number didn't work, client did not answer), etc.? This would be helpful information to see in the case note, as well as displayed on the notice the client receives (if it is possible to modify the notice).

**Comment by C-Love** [comment]
This code is all done. However I know Ramsey is running locally and using this code - Hennepin has a different process. SO - does any other county have a need for this - anyone else running the REVS scrubber? I can pull this code in if needed by anyone BUT I won't worry about it if no one is using it.
@MN-Script-Team/maxis-scriptwriters

**Comment by C-Love** [comment]
I will pull these in to the collaborative branch so people can see the changes. Will not update in the main branch.

**Comment by C-Love** [comment]
To be handled once conversion is over.
