### ISSUE TITLE
Call for input: REPT/PND2 enhancement to add last case note information

### ISSUE THREAD

**Issue by IlseFerris** [MN-Script-Team/DHS-MAXIS-Scripts#2611]
Hennepin County supervisor has requested that the date, x number and header of the most recent case note be added as columns to the "Case information worksheet" in REPT/PND2. Users can select these options in the main dialog via check boxes.

Thoughts?

**Comment by C-Love** [comment]
I can see this information as being helpful for supervisors getting an overview of their worker's pending cases.

**Comment by CDPotter** [comment]
@MN-Script-Team/maxis-scriptwriters can I get a check on this in Master branch to confirm it's working

**Comment by IlseFerris** [comment]
Confirmed, working in master branch
