### ISSUE TITLE
NEW SCRIPT IDEA ~ Appeal Decision

### ISSUE THREAD

**Issue by ALJ10** [MN-Script-Team/DHS-MAXIS-Scripts#2619]
A financial worker (and a supervisor) are wondering if there could be discussions in the possibility of having an Appeal Decision script. Worker thought it could include if the judge upheld or overturned the county's decision and actions needed/taken on the case. Please let me know if there's interest in having discussions on this idea. Thank you!

**Comment by CDPotter** [comment]
Is this different from your suggestion on #694 ?

**Comment by ALJ10** [comment]
The worker thought this would be a separate script. But she figured if it could be combined into one, one script would be sufficient.

**Comment by IlseFerris** [comment]
In association with issue #694, this script will give the worker the following options to resolve: 
* appeal summary completed
* appeal hearing info
* appeal decision received
* appeal resolution 

This way there doesn't need to be several new scripts, just several options within the one script.

**Comment by CDPotter** [comment]
Going to be tackled as part of #694
