### ISSUE TITLE
NEW SCRIPT IDEA ~ Appeal Hearing Scheduled....

### ISSUE THREAD

**Issue by ALJ10** [MN-Script-Team/DHS-MAXIS-Scripts#2620]
A financial worker (and a supervisor) are wondering if there could be discussions in the possibility of having a script for when an appeal hearing is scheduled. Worker thought it could include the date of the appeal hearing, if it's via phone or in person, the time, the docket number, the Judge’s name, the appeals phone number, and a notes box to add any other info that might be needed. Please let me know if there's interest in having discussions on this idea. Thank you!

**Comment by IlseFerris** [comment]
In association with issue #694, this script will give the worker the following options to resolve: 
* appeal summary completed
* appeal hearing info
* appeal decision received
* appeal resolution 

This way there doesn't need to be several new scripts, just several options within the one script.

**Comment by CDPotter** [comment]
Going to be tackled as part of #694
