### ISSUE TITLE
NOTES - EMER enhancement: add emergency screening for selected users

### ISSUE THREAD

**Issue by IlseFerris** [MN-Script-Team/DHS-MAXIS-Scripts#2627]
I've been working with my workers and Ramsey County EMER staff to create a basic EMER programs screening based on general criteria such as meeting residency and crisis reason. Will restrict this to Hennepin County and Ramsey County workers for the time being. 

Assign to me for the October release.

**Comment by CDPotter** [comment]
Resolved with this pull https://github.com/MN-Script-Team/DHS-MAXIS-Scripts/pull/2659
