### ISSUE TITLE
Asset assessment enhancement: add option for AA received 

### ISSUE THREAD

**Issue by IlseFerris** [MN-Script-Team/DHS-MAXIS-Scripts#2629]
AA are now required for disability waiver clients. This means that more and more AA will be coming into counties. Having an option to case note what was rec'd, what was needed, and some other basic information will be very helpful. 

I can take this for the November release unless someone has time before that to dedicate to it.

**Comment by CDPotter** [comment]
Are you planning on re-naming it since it won't be exclusive to LTC?
