### ISSUE TITLE
Asset assessment enhancement: add handling for more than 4 asset panels in ASET

### ISSUE THREAD

**Issue by IlseFerris** [MN-Script-Team/DHS-MAXIS-Scripts#2630]
Currently the script can handle up to 4 pages in the ASET function. There are 8 panels, so the logic needs to be reworked to account for reading and case noting all these panels.

**Comment by CDPotter** [comment]
A few last minute fixes were added, can I get confirmation that this is working in MASTER @MN-Script-Team/maxis-scriptwriters (hopefully last test!)
