### ISSUE TITLE
New script: Asset reduction case note 

### ISSUE THREAD

**Issue by IlseFerris** [MN-Script-Team/DHS-MAXIS-Scripts#2631]
With Asset assessment's staring to come into counties in quantity, documentation of asset reduction is needed. Case noting when assets need to be reduced, and when they have been resolved is something that has been lacking, and will continue to be needed in HC. 

I have mocked up some work, so I'd be happy to share that if someone wants this issue. Otherwise if not assigned by the DHS hackathon on 10/24/16, I can take it.

**Comment by CDPotter** [comment]
@MN-Script-Team/maxis-scriptwriters can I get confirmation that this is working in Master?

**Comment by IlseFerris** [comment]
Confirmed, working in master
