### ISSUE TITLE
Working minor exemption script

### ISSUE THREAD

**Issue by IlseFerris** [MN-Script-Team/DHS-MAXIS-Scripts#2632]
Request from worker: 
For working minors, a script that detects that there is a minor who is verified in school and working and therefore allows the income to be coded as excluded
i'm figuring it is something similar to looking for abawd exemptions, but this one would be to potentially resolve dails regarding working minors.

**Comment by CDPotter** [comment]
@ruthmaloney Does MAXIS not handle this properly?

**Comment by CDPotter** [comment]
As an aside, I updated case 246333 (training region) with a 11 year old who has a job(verified) and in school (N). The income is not being budgeted.

**Comment by IlseFerris** [comment]
Good deal, we can close it then if MAXIS does what it's supposed to do.
