### ISSUE TITLE
Aged benefits DAIL scrubber

### ISSUE THREAD

**Issue by IlseFerris** [MN-Script-Team/DHS-MAXIS-Scripts#2633]
This is laid out very welll in POLI/TEMP TE16.03. 
This would be very helpful for CASH cases in particular to have a DAIL scrubber with an option to send a SPEC/MEMO re: aged benefits.

**Comment by C-Love** [comment]
This is not done but will be worked on and added after conversion.

**Comment by C-Love** [comment]
To be handled once conversion is over.
