### ISSUE TITLE
ACTIONS - RETURNED MAIL

### ISSUE THREAD

**Issue by IlseFerris** [MN-Script-Team/DHS-MAXIS-Scripts#2636]
The returned mail process is well documented in POLI/TEMP TE02.08.012> 
This process is prime for an actions script.

**Comment by CDPotter** [comment]
Could this possibly be a BULK ACTION?

**Comment by C-Love** [comment]
We still love this - I'm looking at you @MiKaylaH22 - will work on it after conversion.

**Comment by C-Love** [comment]
To be handled once conversion is over.
