### ISSUE TITLE
Idea: a text file where a county can add custom pop-ups before or after a script runs

### ISSUE THREAD

**Issue by theVKC** [MN-Script-Team/DHS-MAXIS-Scripts#2640]
Just looking for feedback on this idea. Crosslisted on PRISM: https://github.com/MN-Script-Team/DHS-PRISM-Scripts/issues/568.

As an example, if you want a pop-up box to run before and after the intake script, you can add:

```
before intake: "Please note: our county does not process gas card reimbursements."
after intake: "Remember to update the case status in SharePoint!"
```

Thoughts @MN-Script-Team/maxis-scriptwriters?

**Comment by C-Love** [comment]
I think this is neat-o! That's right - this idea earns 50s slang cool points.
