### ISSUE TITLE
Call for input: expand functionality of Banked Months FIATer

### ISSUE THREAD

**Issue by courtrightd** [MN-Script-Team/DHS-MAXIS-Scripts#2641]
The script currently checks for proper coding of initial banked month before allowing the worker to proceed.  With the 36 month period now being reached, there are potential cases that need the SNAP budget FIATed in the same way that are NOT banked month cases.  Considering turning this into a ABAWD FIATer by removing the banked month safety features.

**Comment by Farleight** [comment]
I see no downside to that. It solves one of seventeen ABAWD problems. Make it so.

**Comment by courtrightd** [comment]
Closing this, it is covered under #2690
