### ISSUE TITLE
New script: MFIP allocation (DAIL or ACTIONS)

### ISSUE THREAD

**Issue by IlseFerris** [MN-Script-Team/DHS-MAXIS-Scripts#2643]
Worker requested script to identify/process MFIP allocation cases.

The entire text from CM 18.30 is as follows:
MFIP, DWP:
Deduct part of a caregiver's income to cover the unmet needs of an ineligible spouse and/or an ineligible child under the age of 21 who lives with the caregiver. Allow this deduction only if the caregiver lives with and is financially responsible for the person.

Income of a minor child cannot be allocated.

Do not allow allocation for the support of people who:
● Choose not to be members of the unit. See 0014 (Assistance Units).

● Are disqualified.

The maximum allocation is the difference between the unit's Transitional Standard, and the Transitional Standard the unit would have if the spouse and/or child were in the unit. See 0020.09 (MFIP/DWP Assistance Standards).

The actual allocation is the maximum allocation minus the ineligible spouse's and/or child's net income. See 0016.18 (Income of Inel. Parent/Guard. of Minor Crgvr).

**Comment by courtrightd** [comment]
So I talked with my MFIP folks, and allocation cases are very rare for us.  That being said, is does require an off-line calculation that is entered into FIAT and is therefore very error-prone.  MAXIS generates a DAIL every time a potential allocation case runs through background, so they seem to be well identified.   Would the desired script be a FIATer to do the actual calculation and FIAT the results?

**Comment by C-Love** [comment]
@MelissaFox-Stearns is there any news on this? I am guessing this should be tagged for post freeze.

**Comment by C-Love** [comment]
To be handled once conversion is over.
