### ISSUE TITLE
BULK LISTS - REPT/ACTV Enhancement - add Child Care

### ISSUE THREAD

**Issue by kaleykobber** [MN-Script-Team/DHS-MAXIS-Scripts#2651]
Is it possible to add child care as a program to select to scan from REPT/ACTV?

**Comment by theVKC** [comment]
Any thoughts from @MN-Script-Team/maxis-scriptwriters?

(I'm filling in a bit for Charles while he's out of the office today)

**Comment by IlseFerris** [comment]
I like it! If we're adding child care, IVE should be added as well. 
Also there's a column for "AT" but I have NO idea what that is. Anyone know what it is?

**Comment by Farleight** [comment]
That's FIAT

**Comment by C-Love** [comment]
AH! There is a FIAT column! How have I never seen this before - I know this is useful!!! My mind is blown. I need to sit down. We could write a BULK report just around FIATed (ahem Error Prone as all ____) cases...

**Comment by IlseFerris** [comment]
I can't believe the FIAT column was hiding in plain sight this whole time. I'll add this as well.

**Comment by CDPotter** [comment]
@MN-Script-Team/maxis-scriptwriters can I get a check on this in Master branch to confirm it's working

**Comment by IlseFerris** [comment]
Confirmed, working in master branch
