### ISSUE TITLE
Bug-ish: GRH HRF script is still listed on Complete List of Scripts file

### ISSUE THREAD

**Issue by RoberT-1000** [MN-Script-Team/DHS-MAXIS-Scripts#2652]
Should I remove it or are there counties that are still wanting it on the list?

**Comment by theVKC** [comment]
I'm going to defer to @CDPotter on this. He'll be back someday soon. :)

**Comment by CDPotter** [comment]
I always forget about this list so yes we should probably just remove it. @RoberT-1000 Wanna knock it out?

**Comment by RoberT-1000** [comment]
On it!
