### ISSUE TITLE
Expedited screening enhancement: add option to note if enough info to determine exp criteria

### ISSUE THREAD

**Issue by IlseFerris** [MN-Script-Team/DHS-MAXIS-Scripts#2656]
Request from Hennepin County supervisor: Add check box to expedited screening case note to indicate that there was not enough information to determine expedited criteria. 

Thoughts?

**Comment by CDPotter** [comment]
So you're talking if someone drop & runs an application and doesn't complete the expedited section? My gut would be to treat any blank as a 0.

What are other agencies doing?

**Comment by IlseFerris** [comment]
Yes, blank or incomplete.

**Comment by Farleight** [comment]
Yeah, I'm pretty sure DHS policy says you have to treat blanks as 0. I know for sure that's what we do, and it's not because we want to. Somewhere along the line we were told we had to.

**Comment by theVKC** [comment]
I recall hearing the same thing at a meeting. Blank = 0. I also think it's a good protection against a bad review to treat blanks as 0.

**Comment by theVKC** [comment]
In fact, pretty sure it was a policy meeting with DHS policy folks.

**Comment by IlseFerris** [comment]
Sounds good, thanks for the feedback team!
