### ISSUE TITLE
BULK Case Transfer - TANF months used

### ISSUE THREAD

**Issue by kaleykobber** [MN-Script-Team/DHS-MAXIS-Scripts#2676]
The script has you enter "MFIP cases with at least __ TANF months used." It will give results for all cases where Memb 01 has used at least that many months, even if that person is not currently active on the MFIP case. Is it possible to add an indicator for the person (active/inactive on MFIP)? Or, most recent (last) month used? 

Does the script also list months used if there is another adult in the household open on MFIP (besides Memb 01)?

**Comment by C-Love** [comment]
To be handled once conversion is over.
