### ISSUE TITLE
Notes - GRH Post pay

### ISSUE THREAD

**Issue by StormageddonDLOA** [MN-Script-Team/DHS-MAXIS-Scripts#2677]
Co-workers (2 separate FWs) are reporting getting a script error (invalid character) on this script. This is all the information I have at this time.

**Comment by CDPotter** [comment]
Looks like some invisible character is at the end of the script. I'm looking at it.

**Comment by CDPotter** [comment]
@StormageddonDLOA Could you have them try again in 5-10 mins after cached version of github catches up.

**Comment by StormageddonDLOA** [comment]
It’s working! Thanks!
Sorry I wasn’t able to get back to you yesterday.

**Comment by StormageddonDLOA** [comment]
Will do!
