### ISSUE TITLE
Add HC sanction to MFIP sanction/DWP disq script

### ISSUE THREAD

**Issue by IlseFerris** [MN-Script-Team/DHS-MAXIS-Scripts#2680]
Request from worker: 
For Child Support Sanctions, we can sanction just Healthcare without client being on MFIP or DWP program. For imposing a HC Sanction, we don’t impose a percentage it’s just closed for the next available month.
Example text for case note: 
 HC SANCTION CURED    
                                               
- Month Sanction Cured: October  
- HH memb(s) #: 01  
- Client Came Into Compliance On: 10/18/2016  
- Sanction Cured Reason: Client complied with Child Support  
- Client was notified Via: Client Not Notified  
- Actions Taken: .....

**Comment by CDPotter** [comment]
We may want to rework these scripts into a overall sanction menu and possibly considering actionizing these scripts.

**Comment by C-Love** [comment]
Thinking this should actually be handled with the Eligibility Summary - #3012 
@MelissaFox-Stearns any update on this? If not we can just bunch it in with an eligibility summary since it is connected to those actions.

**Comment by C-Love** [comment]
Will be handled with creation of the full eligibility summary - case #3012
