### ISSUE TITLE
New Script Idea BULK STAT/DLFN

### ISSUE THREAD

**Issue by AimeePaxton** [MN-Script-Team/DHS-MAXIS-Scripts#2683]
I have a request to see if there would be a way to have REPT DFLN? To show cases that have the DFLN panel in it?

**Comment by CDPotter** [comment]
What are you looking to do with the data?

**Comment by AimeePaxton** [comment]
We are hoping to be able to pull a report to show all active cases with a DFLN panel. This would be used for case maintenance on UA results. We will be outsourcing UA's and we would need to know who is all active with a Drug Felon. I hope that helps.

**Comment by CDPotter** [comment]
Hmm, due to the sensitive nature of the information being collected, and that counties (not dhs) is responsible for determining their own process for random UA testing (CM 0011.27.03.01) I think this might be better left to a county specific script.
