### ISSUE TITLE
Adding reminder to send EBT brochure

### ISSUE THREAD

**Issue by CDPotter** [MN-Script-Team/DHS-MAXIS-Scripts#2689]
At the mentor meeting today delegates from Hennepin asked if we could consider adding reminders to any script to be run in a situation where the EBT brochure should be sent out. I told them I would bring it up. 

I'm not really sure it's a good reminder. Personally I think there are better ways to meet this requirement to get this brochure into people's hands. Anoka could build packets with them included in it for anyone who grabbed a CAF at Anoka. One would think DHS could sent one along with recert paperwork (Though I'm unsure who to ask about that)

**Comment by theVKC** [comment]
My opinion: it'd depend on what "reminder" means, but I like the idea of the script user being able to indicate that one was sent. I wouldn't anticipate we'd be able to get one added to recert paperwork anytime soon, and it is a helpful piece (and I'd also heard feedback to this effect when I traveled the state for SNAP scripts).

**Comment by C-Love** [comment]
My opinion is that any state required document or brochure should be available in SPEC/LETR

**Comment by ruthmaloney** [comment]
Do we have a list of situations Hennepin is talking about?

Does anyone know if the brochure is sent with the EBT card (when the card is mailed)? I would think it would be, but I’m not positive. I’m unaware of a requirement to provide the EBT brochure with a recertification (CM 0009.06 doesn’t list it).

When an EBT card is issued in the agency, the brochure should be given with the card. I don’t know that a script/case note mention of this is the most effective way to handle it. I would recommend making it an agency practice – if a card is issued in agency, an EBT brochure should be handed to the client with the card.

Ruth Maloney

**Comment by CDPotter** [comment]
@ruthmaloney it was reviewed at mentor meeting 10/26/16 (30 mins in).

For November updates CM will reflect this.

5.12.12.01 added for MFIP and SNAP sections. At initial applications, at reapplications, it is mandatory to provide them with it. 

9.06.06 for recertifications it is advised to ask if they want more info on using EBT card and send depending on answer.

**Comment by ruthmaloney** [comment]
I was just watching that now. I apologize for speaking too soon.

Ruth Maloney

**Comment by CDPotter** [comment]
it sounds like scripting isn't the solution for this issue. We're going to try to pursue other more advantageous avenues. Thanks all for the suggestions/discussion.
