### ISSUE TITLE
Banked Months TIKLer enhancement for Approved Progs

### ISSUE THREAD

**Issue by courtrightd** [MN-Script-Team/DHS-MAXIS-Scripts#2691]
Idea: with the maxis improvements for banked months eliminating monthly PEPR dails, setting a reminder to workers to review status and update WREG each banked month is needed.  I propose enhancing approved progs to create a TIKL for each banked month noted as approved.

**Comment by C-Love** [comment]
And a DAIL scrubber to go with it?

**Comment by courtrightd** [comment]
So said dail scrubber would perhaps check elig versions or whatever to see if still open as ABAWD, ask worker to confirm that case is still eligible on banked months, then update WREG and CASE/NOTE?

**Comment by C-Love** [comment]
yes - exactly

**Comment by courtrightd** [comment]
My life is going to be terrible if this doesn't happen, so it can be assigned to me and I will find time unless someone else wants it.

**Comment by courtrightd** [comment]
Is there any reason Approved Progs still needs to generate a spreadsheet, or can I completely remove that function when I pull in the TIKL enhancement?

**Comment by CDPotter** [comment]
My gut would says it could be removed but I could also see agencies wanting to keep it for their own tracking purposes. What do others think?

**Comment by C-Love** [comment]
I think we have had this discussion before. I think it can go away. We could pull in a message box for a few weeks to ask workers to report if they are still using it, otherwise it is just useless code. It was a bother to our workers and if others are not using it I am sure it is a bother to them as well. 

I would like to see it go away.

**Comment by courtrightd** [comment]
I'll wait till tomorrow, and pull in the enhancements if there is no further comment.

**Comment by CDPotter** [comment]
@MN-Script-Team/maxis-scriptwriters could I get confirmation this is good and working in Master?

**Comment by C-Love** [comment]
Working here, sets all kinds of TIKLs.
