### ISSUE TITLE
DAIL - NEW HIRE/NEW HIRE NDNH enhancement: add DAIL scrubbers to process TIKL 

### ISSUE THREAD

**Issue by IlseFerris** [MN-Script-Team/DHS-MAXIS-Scripts#2697]
Request from Hennepin County supervisor to create DAIL scrubber to handle processing NEW HIRE/NEW HIRE NDNH scripts. Options could include giving the user the option to use ACTIONS - PAYSTUBS RECEIVED (which also promotes this very under utilized script), update the JOBS panels to reflect that verification was not returned, etc. 

Thoughts, or other enhancement ideas?

**Comment by theVKC** [comment]
I love the idea of bringing in Paystubs Received. Was always a dream of mine to try and accomplish.

**Comment by IlseFerris** [comment]
#IDreamedADream #Issue24601

**Comment by CDPotter** [comment]
Don't we not have verifications when we get new hire/ndnh messages? How would one run paystubs received without verification? I'm a bit confused what this enhancement will do/fix.

**Comment by IlseFerris** [comment]
You can give the user options on what they'd like to do. If verification has been received, then give the option to run paystubs rec'd, if not the JOBS panel can be checked to ensure that the JOBS panel is present and coded as a N, and remind users to ensure that their elig results reflect verifications for income was not provided.

**Comment by CDPotter** [comment]
But why would you still have this HIRE DAIL if you had verifications? If I'm remember right you can delete HIRE messages after they've been processed (sending verif request/tikl/add new jobs panel). 

When I was processing if I had verifications that DAIL was long gone and I just opened up ACTIONS and clicked paystubs rec'd. Seems to be something that isn't needed. 

That's just my thoughts though. What are other's opinions?

**Comment by Farleight** [comment]
I'm thinking along the same lines as Charles here. If I already have paystubs ready to be processed when that DAIL rolls around, I just delete it. If I don't have them, I request them, and then delete it (usually via the existing script). There is never a time where I would run the script, request the info, and leave the DAIL out there.

**Comment by theVKC** [comment]
I was thinking you run the scrubber off the TIKL the DAIL scrubber originally creates. Not the original message. So it asks: "have you received the paystubs?" and then if you say "yes" it jumps in to Paystubs Received, but only from the TIKL.

**Comment by Farleight** [comment]
I'm thinking along the same lines as Veronica here... What are you even thinking Charles? Get with it!

**Comment by Farleight** [comment]
Seriously though,

I would still process those paystubs independently from the TIKL. Maybe that's just me.

**Comment by CDPotter** [comment]
I agree with Travis. The DAIL wouldn't be my hint to process the paystubs. If they were in my inbox I would process them rather than waiting for a DAIL to tell me to close the case for no verification. Alternatively if I did get the DAIL telling me to close the case for no verif I would close and just run NOTES - Closed Progs.

**Comment by theVKC** [comment]
Not everyone has an opportunity to process prior to the TIKL date, though. Especially in larger counties. At least, that's been my observation in my travels. That might be where Hennepin is coming from with it: by incorporating an *option* to run from the TIKL and ask the worker, you make it a "batch-able" process. But I'd check with @IlseFerris on that before taking my word for it.

**Comment by Farleight** [comment]
options are always good. My point was actually not dependent on the date of processing though... even if I haven't processed by the time the TIKL comes, I still do it separately. I would in fact look at the TIKL, see that I have the stuff, delete the TIKL, and then process the verifs whenever they come up in the regular rotation. I would not take them out of date order simply because a TIKL showed up... and I would not save a TIKL for a thing that's already turned in.

**Comment by C-Love** [comment]
To be handled once conversion is over.
