### ISSUE TITLE
bug with Expedited Screening Case Note script at Fillmore County

### ISSUE THREAD

**Issue by StormageddonDLOA** [MN-Script-Team/DHS-MAXIS-Scripts#2703]
I received an email from Fillmore County (X123) that when they use the Expedited Screening script it's not using the new (10/2016) HEST info in it's calculations and case note.

I used the script a couple times yesterday to test it and had no problems. Today they sent me a screenshot showing $450 in the utilities line so they are still having an issue.

This may be localized to just their county.

**Comment by CDPotter** [comment]
The code is in the release version. Anyone else seeing this?

**Comment by theVKC** [comment]
Is it possible they're using an old non-GitHub installation? This script has been around a while...

**Comment by CDPotter** [comment]
Since $450 was the '14 number I'd assume that's the case.

**Comment by StormageddonDLOA** [comment]
I'll email them back and see if that's the problem.

**Comment by theVKC** [comment]
I'd suggest the reinstall all scripts.

**Comment by StormageddonDLOA** [comment]
Email away! Reinstall suggested.

**Comment by StormageddonDLOA** [comment]
closing the issue

**Comment by StormageddonDLOA** [comment]
thanks for the help!
