### ISSUE TITLE
Enhancement ACTIONS: HG Supplement incorporate new process

### ISSUE THREAD

**Issue by CDPotter** [MN-Script-Team/DHS-MAXIS-Scripts#2709]
With the new announcement of the new process for MFIP Housing grant supplements @IlseFerris is going to be tackling enhancing this script so it is good to be used for these new situations.

**Comment by CDPotter** [comment]
@MN-Script-Team/maxis-scriptwriters Could I get some master branch confirmation that the new script ACTIONS - HG Expansion MONY-CHCK runs (don't process a case) and the instruction button works?

**Comment by CDPotter** [comment]
Accidentally closed, still need confirmation buttons are working in Master.

**Comment by C-Love** [comment]
Script opens and instructions work.

**Comment by IlseFerris** [comment]
Yay!

**Comment by IlseFerris** [comment]
Three master branch users at Hennepin confirmed script is working as anticipated.

**Comment by CDPotter** [comment]
Yay! I shall pull into RELEASE. However Rita has asked that people hold off going full force into processing the list as they want to revise the 10/16 one, to be released Monday. She has given me the go ahead to put this into RELEASE.

**Comment by IlseFerris** [comment]
Awesome news!!!
