### ISSUE TITLE
eDRS script

### ISSUE THREAD

**Issue by theVKC** [MN-Script-Team/DHS-MAXIS-Scripts#271]
Basically, follows the new rules of the eDRS process. I need to do a bit more research (need to get comfortable with the process) before I can take it on, but if anyone else wants to tackle it, let's do it.

**Comment by CDPotter** [comment]
Hello all, 

If anyone finds a case that actually has a result for the EDRS screen please let me know via email Charles.potter@co.anoka.mn.us We have no idea what it looks like if the search does turn up someone. It would be nice to expand what we are building but at this time it looks like we will just be able to determine if the message is "Nothing found" or not.

**Comment by CDPotter** [comment]
Thanks for the responses! I've got what I need for now and submitted a working version!
