### ISSUE TITLE
Bug - Bulk - Enhanced - Check SNAP for GA/RCA

### ISSUE THREAD

**Issue by Farleight** [MN-Script-Team/DHS-MAXIS-Scripts#2710]
This Script does not have a time-out fail-safe, as discovered the fun way, when I tried to run it, got suspended from MAXIS, and had it lock up my computer in a continuous loop while trying to find information while logged out. It must be stopped. If anyone feels like a hero, please kill the loop.

**Comment by CDPotter** [comment]
This is now live in Master, could I get confirmation that it is working from script writers using master branch?

**Comment by theVKC** [comment]
(Psssht, @CDPotter, if you want people to respond you need to tag them in the post. Something like @MN-Script-Team/maxis-scriptwriters should do it. Also, @Farleight is on vacation I believe.)

**Comment by CDPotter** [comment]
Whoops, I figured replying would cause notification emails.

**Comment by theVKC** [comment]
Depends on the user settings. I play it safe and bug everyone all at once. :)

**Comment by CDPotter** [comment]
@MN-Script-Team/maxis-scriptwriters second request for confirmation this is working.

**Comment by Farleight** [comment]
I'll try to check this out next time I'm timed out... but it better work or I'm blaming you when I send the unsuspend ticket.

**Comment by RoberT-1000** [comment]
Going to submit a pull request. Everything appears to be working.

**Comment by RoberT-1000** [comment]
I'm not going to add anything to the changelog to say that I fixed an error in the changelog that was preventing the script from running. That seems awfully circular.

**Comment by CDPotter** [comment]
Thanks! It's been merged into Master.

**Comment by RoberT-1000** [comment]
I didn't even think about whether i should pull into release. I'll take a look.

**Comment by RoberT-1000** [comment]
By the way, release does not have `check_for_MAXIS`...I'll add if'n ye like

**Comment by CDPotter** [comment]
I was waiting for at least one confirmation it's working to pull into release.

**Comment by CDPotter** [comment]
Thought I just tested it and it seemed fine, so I'm going to commit your most recent version through to release.

**Comment by IlseFerris** [comment]
This one looks good to me. Confirmed, working in master branch
