### ISSUE TITLE
End of Month Closure Case Note script (Bulk REVW/MONT Closures I believe)

### ISSUE THREAD

**Issue by StormageddonDLOA** [MN-Script-Team/DHS-MAXIS-Scripts#2713]
Got forwarded an email from Red Lake County:

"We’re not sure if it happens all the time or not, but we’ve noticed that when running the script to do the end of the month closure case/notes, the 4 month reinstate timeline was case noted on some NON-MAGI cases.  Workers may want to check to see if the case/notes are correct when running this script."

I haven't tested or ran into the issue personally as I've never used this script.

**Comment by CDPotter** [comment]
I believe for renewals that is correct. 

EPM2.3.4.2:
A late renewal is a renewal for which either of the following is true:

•the renewal form is received before the last day of the fourth month following closure; or

•any additional information or verifications that were required are received before the last day of the fourth month following closure.

Eligibility for enrollees who do not return the renewal form, or who return the form but do not provide all the information and verifications needed to renew eligibility, is closed. However, eligibility for enrollees who are closed for failing to renew may be redetermined without requiring a new application if the form is returned within four months of the date of closure. The original certification period and renewal date apply.

**Comment by StormageddonDLOA** [comment]
I will forward this answer on.

Thanks!
