### ISSUE TITLE
CSES DAIL scrubber enhancement: Add option to update for HC only cases

### ISSUE THREAD

**Issue by IlseFerris** [MN-Script-Team/DHS-MAXIS-Scripts#2714]
At hackathon Stearns, Ramsey, Hennepin and DHS discussed adding an option to users to update Child Support income for HC only cases. The justification for this: for MFIP cases that are temporarily closed due to incomplete HRF, users would need to process the income updates manually, unless the DAIL message was held until a later date. This effects case banking agencies like Stearns and Hennepin more than other agencies, but this is a solid option for all users. A vbYesNo can be added to give the user the option to update this income information or not.

**Comment by courtrightd** [comment]
I will take this one too.

**Comment by CDPotter** [comment]
@courtrightd please take a chance to test the updates Casey made to the scrubber last week while working on this. #2802

**Comment by CDPotter** [comment]
@MN-Script-Team/maxis-scriptwriters Can I get confirmation this is working? Just need one agency for this smaller fix.
