### ISSUE TITLE
NEW SCRIPT IDEA ~ DAIL SCRUBBER or a simple NOTE for MAXIS cases that migrated over to METS...

### ISSUE THREAD

**Issue by ALJ10** [MN-Script-Team/DHS-MAXIS-Scripts#2718]
I rec'd the following script idea from a worker. It was discussed by the supervisors and they requested I submit the idea to see if there have been any discussions or if it would even be a possibility. Let me know if you need further details. Thank you!

Here's the request from the worker/supervisors:
A script of some sort for the METS migration DAIL messages that we get. Currently, I copy & paste that DAIL into a case note. Since this is going to be an ongoing project and will take some time, I thought a DAIL scrubber script would be nice just to case note that the HC is closing for METS migration. Otherwise, at least a regular NOTE script where we can choose who is closing and when. I think if the worker has a case note that stands out to them there will be less errors in processing renewals in the Maxis system which will result in more cases migrating and less remaining in Maxis.

**Comment by LaLarson** [comment]
@CJOHNS356 Wrote two scripts that we use here in Olmsted... My understanding is that one will put all the DAILs on a spreadsheet, and a second script that will take all of the DAILs on said spreadsheet and case note them. We can share them if they would be useful.

**Comment by IlseFerris** [comment]
Ooooh can we get that pulled in? Those sound fantastic!

**Comment by CDPotter** [comment]
I did build a version of this for MNIT this last month and I stored it here: https://gist.github.com/CDPotter/cfcb335ddb6d597571bbd33615780244 

Counties could modify this and use in county customized.

**Comment by C-Love** [comment]
Migration as a large process is over. Thinking we don't need this anymore.
