### ISSUE TITLE
MFIP sanction/DWP disqualification (EASY new script idea)

### ISSUE THREAD

**Issue by theVKC** [MN-Script-Team/DHS-MAXIS-Scripts#272]
This one will be a simple one if anyone wants to create it. Submitted by X171683:

The following items could be included in the script:

* Type of sanction (Employment Services or Child Support)
* Effective date of sanction/disqualification
* Number of occurrences
* Vendor information - if we are vendoring due to the sanction, vendor number, etc.
* Status Update information (documenting that we sent a status update to ES and CCA)
* FIAT

Any takers for this easy one?

**Comment by GayS** [comment]
ok - so I have this "finished" and saved in my github.  Not sure how to push it to you from there?

**Comment by theVKC** [comment]
@GayS pushed this one out a few days ago, and I've received it and will add to NOTES main menu. Nice work!

**Comment by GayS** [comment]
Thanks - I'm on the board now!!
