### ISSUE TITLE
NOTES - LTC COLA summary needs update for 2017

### ISSUE THREAD

**Issue by IlseFerris** [MN-Script-Team/DHS-MAXIS-Scripts#2735]
Dates for COLA case note are hard coded for 2016. Needs updates for 2017. 

Assign issue to me.

**Comment by CDPotter** [comment]
@MN-Script-Team/maxis-scriptwriters can I get confirmation that this is working on master branch as expected?

**Comment by C-Love** [comment]
My tester is unable to process these cases and test as they are waiting for instructions on these. Does anyone have them so I can forward them on? Maybe @IlseFerris ?

**Comment by CDPotter** [comment]
I think we might be in a holding pattern until the yearly SIR posting on it.

**Comment by IlseFerris** [comment]
There are instructions for this one on SIR: https://www.dhssir.cty.dhs.state.mn.us/MAXIS/blzn/Script%20Instructions%20Wiki/LTC%20-%20COLA%20summary%202016.aspx
It's just labeled as COLA summary 2016

**Comment by IlseFerris** [comment]
https://www.dhssir.cty.dhs.state.mn.us/MAXIS/Lists/MAXIS%20Announcements/DispForm.aspx?ID=1541&RootFolder=%2FMAXIS%2FLists%2FMAXIS%20Announcements

POLI TEMP has been updated with the 2017 COLA info

**Comment by C-Love** [comment]
Thank you! I will forward to my testers

**Comment by IlseFerris** [comment]
I have testers confirming this is working. Can we get this into release today?

**Comment by CDPotter** [comment]
Sure thing!

**Comment by IlseFerris** [comment]
Excellent!
