### ISSUE TITLE
New Hire Dail 10 day notice 

### ISSUE THREAD

**Issue by x143626** [MN-Script-Team/DHS-MAXIS-Scripts#2736]
CM verification due dates update for Nov 2016 - Is anyone working on updating the new hire dail 10 day notice to begin the 10 day count the day after the date the verification is requested? Our workers notice the dail is still plugging in 10 days from the day the request goes out instead of 11. Wish list - They would also like an option to have a worker entered date over-ride (for holidays, weekends, etc where additional days are needed).

**Comment by CDPotter** [comment]
Currently the script uses a date add function for 10 days. Meaning if someone requested verifs on 3/11/16 it would look like this:

3/11/16 day 0
3/12/16 day 1
3/13/16 day 2
3/14/16 day 3
3/15/16 day 4
3/16/16 day 5
3/17/16 day 6
3/18/16 day 7
3/19/16 day 8
3/20/16 day 9
3/21/16 day 10 (day it would TIKL for/case note)

Are you saying this is now incorrect?

**Comment by x143626** [comment]
OK, I talked with a couple of folks here (they are now officially off the ledge – whew!) – what you are doing is correct.
I think where they are getting hung up regarding the dail is that at our agency, mail is picked up from the building at 10 AM. This means that if a case is processed in the afternoon, mail won’t leave until 10AM of the following day. Because of this, we often give an extra day on the paperwork being sent out so clients will have a truer 10 day period. This also means that when we see a dail for the technically correct date, it may or may not be what we put on the return paperwork for the clients.
What we have decided to do as a group is to simply complete those types of dails one day later to make sure during audits we are within the correct date range for any negative action that needs to be taken.  For our wish list – we would still like to explore the possibility of giving workers the option to over-ride the pre-populated date to allow for holidays, weekends, or whatever time the mail is picked up.
Thanks!

**Comment by C-Love** [comment]
I find one of the benefits of this script is that it does reduce the possibility of worker error in determining the return date (for the TIKL). This is a standard 10 days in policy and procedure. However each county gets to determine non-working days (weekends and holidays) and we should not deploy a statewide script that makes assumptions about non-working days. Delaying the return date is not addressed anywhere in policy, so it does not seem be have backing for this. Additionally this change would slow down the script run. 

I would rather leave it as is.
