### ISSUE TITLE
Enhancement - GRH - NON-HRF Postpay

### ISSUE THREAD

**Issue by StormageddonDLOA** [MN-Script-Team/DHS-MAXIS-Scripts#2740]
A few of my co-workers that do GRH have asked if the part on the first line of the case note that says "billings" can be changed to read "GRH Payment"? 

The reason being that it's much clearer to them when for instance they are on phones and trying to find the case note dealing with the GRH payment.

**Comment by CDPotter** [comment]
Personally I don't see why not, anyone else with GRH background have any objections?

Currently it reads:  "facility_location  BILLINGS FOR  GRH_process_date"

**Comment by IlseFerris** [comment]
That works for me. Makes sense.

**Comment by CDPotter** [comment]
@MN-Script-Team/maxis-scriptwriters can I get confirmation from master branch users this is working?

**Comment by C-Love** [comment]
Looks good here,
