### ISSUE TITLE
BULK - MEMO from List (Semi colons aren't making new line??)

### ISSUE THREAD

**Issue by LaLarson** [MN-Script-Team/DHS-MAXIS-Scripts#2748]
Hi! 

We're trying to use this script to send out MEMOs to several hundred cases letting them know that child care will now be administered through our county (and not a contracted agency), and when I'm testing it in the training region (used the training case creator - AHHHMAZING!) the semi colons don't seem to be making new lines?? 

If someone could help me figure this out, we would be most grateful!! This one is seemingly over my head! 

I'm x155797, and there's only one case in my number in the training region if anyone cares to see it first hand??

**Comment by CDPotter** [comment]
Looks like write_variable_in_SPEC_MEMO doesn't have the (EMWriteScreen replace(word, ";", "") & " ", noting_row, noting_col) that case note does. 

I would wager this is because of the 2 page limit for Spec Memos. It's something we could look at bit I'd fear it might be error prone for people who aren't aware of it/as proactive in testing.

**Comment by theVKC** [comment]
You beat me to it, @CDPotter! I was about to say the same thing.

https://github.com/MN-Script-Team/BZS-FuncLib/issues/310 would resolve this particular issue. I also have an idea to (with this unified function) enter capability to yell back if it's programmed to enter too much info. What would we think of that?

**Comment by theVKC** [comment]
(I'm also thinking we could ditch the semicolons for something formal when coded from this script, but that's a bit from now I'm guessing)

**Comment by LaLarson** [comment]
You folks are so great! LOL... I knew it was over my head! I can understand what you are saying, but what never have figured that out.  

Okay... So in this scenario, it's definitely too long even when we (Glory to YOU!!!) fix this probably. I will figure out something else. 

I appreciate you looking at it! You are the best!!

**Comment by CDPotter** [comment]
Sounds good! Sadly SPEC/MEMO itself doesn't allow much space for formatting. I'll go ahead and close this since it would be more of a function update.
