### ISSUE TITLE
NOMI - Bug on master branch with new pull

### ISSUE THREAD

**Issue by courtrightd** [MN-Script-Team/DHS-MAXIS-Scripts#2758]
My test users just reported NOMI was broken - Expected Statement error.  No other info at this time, I got them working again by taking them off master.

**Comment by theVKC** [comment]
Guessing #2757 resolves this, but is pending.

**Comment by courtrightd** [comment]
Duh - I didn't see that pending pull there.  Thanks V.

**Comment by CDPotter** [comment]
Indeed, it should be fixed now. I let some merge conflict language stick around. Could you give it check in master?
