### ISSUE TITLE
Enhancement - NOTES- IEVS Notice recived verbiage and name change

### ISSUE THREAD

**Issue by C-Love** [MN-Script-Team/DHS-MAXIS-Scripts#2760]
It has been requested to change the file name, button, and case note header from 'IEVS Notice' to 'IEVS Match'.

This is clearer as the script is meant to address the IEVS DAIL - which is the match. The notice wording refers more directly to the Difference Notice.

I got this

**Comment by CDPotter** [comment]
This is now live in Master, could I get confirmation that it is working from non-script writers using master branch?

**Comment by CDPotter** [comment]
@MN-Script-Team/maxis-scriptwriters (for previous post)

**Comment by IlseFerris** [comment]
Confirmed, working in master branch

**Comment by kaleykobber** [comment]
Our users are reporting an error when accessing this script... "Something has gone wrong. The code stored on GitHub was not able to be reached. The script has stopped. Please check your Internet connection. Consult a scripts administrator with any questions." It appears to only be this script. It is working in Master Branch, but not in Release Branch.

**Comment by CDPotter** [comment]
Thanks for reporting, looks like the name change on the file didn't make it's way to release. I've updated it. Could you confirm it is working?

**Comment by kaleykobber** [comment]
Yes, it is working now. Thank you!
