### ISSUE TITLE
Enhancement to ACTIONS - PA Verif Request to exclude other income detail

### ISSUE THREAD

**Issue by C-Love** [MN-Script-Team/DHS-MAXIS-Scripts#2762]
In creating the word document for use by outside agencies - have an option to exclude the other income from the spreadsheet. 

I have this.

**Comment by CDPotter** [comment]
@MN-Script-Team/maxis-scriptwriters could I get confirmation from master branch peeps this is working?

**Comment by CDPotter** [comment]
@MN-Script-Team/maxis-scriptwriters second request for confirmation this is working.

**Comment by IlseFerris** [comment]
Confirmed, working in Master branch
