### ISSUE TITLE
Bug - Notes Verifications Needed

### ISSUE THREAD

**Issue by RoberT-1000** [MN-Script-Team/DHS-MAXIS-Scripts#2765]
The name of the file in the new directory does not match the name of the file in the Complete List of Scripts. Are other agencies experiencing an issue? This is throwing off the Anoka Favorites Script and it's also bothering me that it's inconsistent.

The file name...
![image](https://cloud.githubusercontent.com/assets/22157633/20729878/7730e418-b649-11e6-87f5-b0c46612da7a.png)

In Complete List of Scripts...
![image](https://cloud.githubusercontent.com/assets/22157633/20729897/93c2f0f8-b649-11e6-86d4-d80c613c014e.png)

In the Notes main menu...
![image](https://cloud.githubusercontent.com/assets/22157633/20731314/7d2bee8e-b64f-11e6-8574-e223c78393dc.png)

**Comment by CDPotter** [comment]
@MN-Script-Team/maxis-scriptwriters could I get some testers on Master to make sure this is good to go to release?

**Comment by RoberT-1000** [comment]
Good in Anoka
