### ISSUE TITLE
Enhancement to NOTES - HRF - Add LTC functionality

### ISSUE THREAD

**Issue by C-Love** [MN-Script-Team/DHS-MAXIS-Scripts#2769]
Our LTC cases are Manual Monthly for HC and have HRFs.

I will be pulling this in shortly.

**Comment by CDPotter** [comment]
@MN-Script-Team/maxis-scriptwriters Let's keep an eye on this one since it's a bit bigger, keep me posted on this one!

**Comment by CDPotter** [comment]
@MN-Script-Team/maxis-scriptwriters second request for confirmation this is working.

**Comment by LaLarson** [comment]
We are getting reports in Olmsted that it's not working.

**Comment by CDPotter** [comment]
When does it appear? (What options did they pick)

**Comment by IlseFerris** [comment]
Confirmed, working in Master. 
We've gotten this error too from time to time, but it's not specific to this script.

**Comment by CDPotter** [comment]
@LaLarson any more info on this one?

**Comment by CDPotter** [comment]
@LaLarson and @MN-Script-Team/maxis-scriptwriters If there are no more issues are we good to put this into release?

**Comment by LaLarson** [comment]
So sorry I didn't respond, somehow I missed it! Good to go!
