### ISSUE TITLE
CSES DAIL scrubber - Benefit Period - Possible Bug

### ISSUE THREAD

**Issue by kaleykobber** [MN-Script-Team/DHS-MAXIS-Scripts#2774]
When the DAIL scrubber is being run, after the initial dialog box and after the worker reviews the Excel spreadsheet and the script goes back into MAXIS, the script is getting stuck on the benefit month on the main MAXIS screen... The script enters "1/" instead of "01" as the benefit month, and the script is unable to continue. The worker receives an error message that they may be in Inquiry (even though they are in Production). 
Here is a screenshot: 

![image 1](https://cloud.githubusercontent.com/assets/13418535/20887214/660a56a4-babf-11e6-9554-2b0e810c4196.PNG)

**Comment by CDPotter** [comment]
Found the issue. Around line 1072 we are checking if UNEA_month is length 1. However UNEA_month is defined as issue_date (plus 2 months) so it will never be length 1. 

Fix incoming.

**Comment by CDPotter** [comment]
@MN-Script-Team/maxis-scriptwriters Ok this is in both RELEASE and MASTER. Please keep me informed if this is working on here through other channels. Keep an eye on this one!

**Comment by kaleykobber** [comment]
Appears to be working now. Thanks for the speedy fix!

**Comment by IlseFerris** [comment]
I'm waiting for cases to test, but if @kaleykobber says it's working, that's good enough for me.

**Comment by CDPotter** [comment]
Cool, I did get verification via email from Dakota county (release) that it's working again for them, and I ran it locally pretending to be Anoka on an Anoka case in inquiry and it worked. I think we might be good, but everyone keep and ear/eye open.
