### ISSUE TITLE
DAIL SCRUBBER - child support received

### ISSUE THREAD

**Issue by StormageddonDLOA** [MN-Script-Team/DHS-MAXIS-Scripts#2776]
I've had a couple so-workers run into issues with the scrubber going into 01/2016 on MFIP cases to try and update the retro income, not 01/2017.

**Comment by CDPotter** [comment]
Can you email me a case number so I can work on this?

**Comment by IlseFerris** [comment]
I just had a report of this as well

**Comment by CDPotter** [comment]
I'm guessing it's because MAXIS_footer_year is never defined. Strangely on the case I was testing on it didn't do this yesterday and when I tried to code proactively for this it cause the case to go into 16 instead of 17. I can work on this but I need a case number emailed to me.

**Comment by StormageddonDLOA** [comment]
Asked for a case number if it happens again.

**Comment by IlseFerris** [comment]
Also waiting for case numbers from staff

**Comment by CDPotter** [comment]
Check out this fix if anyone is having issues. I want to make sure this fix holds before pulling into Master https://github.com/MN-Script-Team/DHS-MAXIS-Scripts/blob/cses-year-fix/dail/cses-scrubber.vbs

**Comment by StormageddonDLOA** [comment]
I have a case number you can take a look at. It's not the MFIP issue but a different one that pops up from time to time. I'll email you the number.

**Comment by StormageddonDLOA** [comment]
I wonder if it's because SNAP is pending.

**Comment by CDPotter** [comment]
Yes that is indeed the case for that case number you sent me. There's no approved version of ELIG for SNAP. I'm wondering if that might be for the best as we may not want the script processing the DAIL when there's SNAP pending?

Otherwise as far as the main issue goes is it working and getting int 01/17 now? Should I put it in release?

**Comment by CDPotter** [comment]
I'm trusting that this was a small fix, I tested it on a few cases from 02 and 73 DAILS, and I operating on no news is good news and committing this to release.

**Comment by StormageddonDLOA** [comment]
I didn’t have any issues on the ones I ran and everyone I asked also reported no problems. ☺
