### ISSUE TITLE
Point of Inquiry -- Appointment Letter

### ISSUE THREAD

**Issue by RoberT-1000** [MN-Script-Team/DHS-MAXIS-Scripts#2778]
Question: Why is the appointment letter script only case noting the appointment time when it is a phone interview? I'm thinking it should always be case noting the appointment time.

**Comment by CDPotter** [comment]
Looks like it got removed accidentally when Hennepin joined the appointment letter train. I can knock out quickly.

**Comment by RoberT-1000** [comment]
It's all shiny, cap'n
