### ISSUE TITLE
BUG on DAIL - CSES New Job Reported

### ISSUE THREAD

**Issue by C-Love** [MN-Script-Team/DHS-MAXIS-Scripts#2783]
We hanged the coordinates for the New Hire scripts a while back (See Issue # 2485) but this got missed. 

JOBS won't update.

Idea. Could we find a way to merge this back into one script? This is a bit ridiculous.

**Comment by theVKC** [comment]
(FYI, merging them all back together was always something I wanted to do)

**Comment by CDPotter** [comment]
I could also see merging them back together. Wanna throw up a separate issue for it?
