### ISSUE TITLE
REPT/PND2: add IV-E and Child Care

### ISSUE THREAD

**Issue by IlseFerris** [MN-Script-Team/DHS-MAXIS-Scripts#2786]
This is being added to REPT/ACTV. Should also be added to REPT/PND2

Assign to me.

**Comment by CDPotter** [comment]
@MN-Script-Team/maxis-scriptwriters can I get a check on this in Master branch to confirm it's working

**Comment by IlseFerris** [comment]
Confirmed, working in master branch
