### ISSUE TITLE
DAIL Scrubber - CS Scrubber

### ISSUE THREAD

**Issue by StormageddonDLOA** [MN-Script-Team/DHS-MAXIS-Scripts#2788]
We are having an issues on SNAP cases when the CS scrubber is run. The error we're getting is "Script Error at Line 1, Column 1: Type mismatch "BUDG, RSDI".

This is on cases that have no RSDI.

**Comment by CDPotter** [comment]
@MN-Script-Team/maxis-scriptwriters Anyone else hitting this issue?

**Comment by IlseFerris** [comment]
I just got a report of this issue as well

**Comment by CDPotter** [comment]
It looks like it's not getting into ELIG/FS. I'm guessing this has something to do with writing the "E" on the dail and the assumption that the script made it back to the DAIL.

**Comment by CDPotter** [comment]
@StormageddonDLOA Could you test the fix that is in master right now?
