### ISSUE TITLE
HG supplement: adding handling enhancement

### ISSUE THREAD

**Issue by IlseFerris** [MN-Script-Team/DHS-MAXIS-Scripts#2791]
Ran through most of the 11/16 HG supplement list, and a couple of enhancements would be helpful. 
1. Handling for significant change cases. The navigation in ELIG is a little different. 
2. Handling for cases where the issuance that eligibility worker can approve has been exceeded (when this occurs, supervisors need to approve the issuance).

Assign to me, I've been testing this locally with great success.

**Comment by CDPotter** [comment]
@IlseFerris Can I get confirmation this is good to go in Master?

**Comment by IlseFerris** [comment]
We are good to go into release. Testing locally and in Master branch.
