### ISSUE TITLE
Enhancement: NOTES - CAF add checkbox for giving client EBT brochure 

### ISSUE THREAD

**Issue by bblomer** [MN-Script-Team/DHS-MAXIS-Scripts#2793]
At the  October mentor meeting with DHS we were informed that we need to give the brochure "How to Use your MN EBT card" to each applicant and make sure the client understands how to use it at each recertification.  There is currently a box that says we made an EBT referral on the script.  With the recent revision of the CAF, workers are asking if we need to case/note that we have given or sent this required form and the other required forms that are listed on P. 9 of the CAF.  
Should this be added to the CAF script?  
Thanks!

**Comment by CDPotter** [comment]
I've been out of the front desk loop for a bit now but aren't those brochures generally included along with the intake packet? (Which has a checkbox to case note on intake)

Now the only issues would be recerts as those generally do not get intake packets but we are required to at least OFFER the EBT brochure at recerts. 

and non-office applications who wouldn't get a intake packet. 

I'm going to ask ME and QC here to see how they would grade this.

Also I was looking for page 9 on this CAF to see what other docs are needed and I couldn't find it listed here, either on PDF page 9 or CAF page 9.
https://edocs.dhs.state.mn.us/lfserver/Public/DHS-5223-ENG

My hesitation is again the CAF is bloated with checkboxes and fields. Adding a checkbox for one document will lead to more checkboxes for other documents.

**Comment by bblomer** [comment]
It is going to make things interesting with the new expandable CAF.

Thank you and I’ll relay this information to my team.  I’m good with just making sure it’s checked on the Caf.

Thanks,

Bridget Blomer
Financial Assistance Supervisor
Scott County Health & Human Services
792 Canterbury Rd So
Shakopee, MN  55379
Phone: 952-496-8258
Fax: 952-496-8825


Privileged/Confidential information may be contained in this message.  If you are not the addressee indicated in this message (or responsible for delivery of the message to such person), please do not copy or deliver this message to anyone.  Rather, we ask that you: (1) please notify the sender by replying to this transmission and (2) please delete this message and any copy of it (in any form) without disclosing it.
