### ISSUE TITLE
New script idea: SMRT process case note

### ISSUE THREAD

**Issue by IlseFerris** [MN-Script-Team/DHS-MAXIS-Scripts#2794]
More than one worker/supervisor has requested a case note template to record the SMRT process). Here is what they suggested. One script, three paths: 

ECF Workflow Completed SMRT referral request
SMRT requested for:
Date SMRT referral completed:
SMRT start date: 
Reason for referral:
Is referral expedited?
If yes, why is expedited being requested?

ISDS referral completed for SMRT
SMRT requested for:
Completion date:
Program requested:
Requested SMRT start date:
Comments:

SMRT determination received
SMRT requested for:
SMRT Approved or Denied (check box)
SMRT start date: 
Approved Programs: 
MMIS updated ( maybe the check box)

**Comment by IlseFerris** [comment]
I'll take this one

**Comment by CDPotter** [comment]
Can I get confirmation this is working in Master from two agencies? @MN-Script-Team/maxis-scriptwriters

**Comment by CJOHNS356** [comment]
Works in Olmsted County

Christopher Johnson
Family Support and Assistance
Eligibilty Specialist
Olmsted County Family Support and Assistance
Phone: (507) 328-6311
Fax: (507) 328-7956

NOTICE: This e-mail communication is for the sole use of the intended recipients and may contain unclassified confidential information. Any unauthorized disclosure, copying or dissemination of this communication is prohibited. If you are not the intended recipient, please notify the sender by e-mail and delete all copies received. Thank you.
P Go Green!  Please do not print this e-mail unless it is completely necessary.

**Comment by courtrightd** [comment]
Confirmed working up north.

**Comment by IlseFerris** [comment]
Confirmed, working in master
