### ISSUE TITLE
NOTES - ES referral enhancement: add program name into header of case note

### ISSUE THREAD

**Issue by IlseFerris** [MN-Script-Team/DHS-MAXIS-Scripts#2797]
Hennepin County family programs HSR requested that the program name be added to the header. This makes for ease of reviewing appointment dates for recipients per program.

**Comment by CDPotter** [comment]
I personally like it but I didn't use it much, any other thoughts?

**Comment by courtrightd** [comment]
We don't schedule them at our agency for fam cash, but I have no objections to this if leaving the schedule date blank results in nothing added to header.

**Comment by IlseFerris** [comment]
I'll take this one

**Comment by CDPotter** [comment]
This is live in MASTER could I get confirmation that it is working? @MN-Script-Team/maxis-scriptwriters

**Comment by IlseFerris** [comment]
Confirmed, working in master
