### ISSUE TITLE
Change verbiage from Curum to METS in MNsure retro HC application

### ISSUE THREAD

**Issue by IlseFerris** [MN-Script-Team/DHS-MAXIS-Scripts#2798]
Request from Hennepin County HSR working in METS: would like references to Curum changed to METS.

**Comment by CDPotter** [comment]
METS still can't do retro hm? I like this change but I have little stake in the HC world. Anyone else on board?

**Comment by IlseFerris** [comment]
I'll take this

**Comment by CDPotter** [comment]
@MN-Script-Team/maxis-scriptwriters Can I get confirmation this is working in MASTER?

**Comment by IlseFerris** [comment]
Confirmed, working in master
