### ISSUE TITLE
Inverse Krabapple is having an Identity Crisis

### ISSUE THREAD

**Issue by C-Love** [MN-Script-Team/DHS-MAXIS-Scripts#2803]
We have a name problem and the script won't run.
There are 2 scripts listed for this on the Utilities Main Menu - Copy Case Data for Training & Copy Case Data. Neither of them work. Copy Case Data for Training has a file not found error. Copy case data has a weird description - looks like the description for Copy Case Note Elsewhere - which is not actually listed on the menu. So it looks like our list of scripts is all screwy. 

Then in Git Hub the script is named copy-case-data as the file name BUT in the script file the script name is defined as UTILITIES - COPY MAXIS CASE DATA TO EXCEL.vbs

So we need to name this baby. Then fix all the calls/code etc

**Comment by CDPotter** [comment]
I'm thinking we go with:

Rename copy case data (inverse krabapple) file to match button Copy Case Data for Training
Rename copy case note data button to match file copy case note elsewhere

This will keep the buttons the same but make them work.

**Comment by CDPotter** [comment]
@MN-Script-Team/maxis-scriptwriters Can I get confirmation these two are now loading?
Utilities - Copy Case Data for Training
Utilities - copy case note elsewhere

**Comment by C-Love** [comment]
Looks good here.

**Comment by kaleykobber** [comment]
Are there instructions available for this script? I didn't find them when I looked on SIR...

**Comment by CDPotter** [comment]
It does not appear that there are instructions on SIR. @RoberT-1000 do you have any instructions for this one?

**Comment by RoberT-1000** [comment]
You know what? I don't think I do. I can try to get this done.

@kaleykobber you'll need a Krabappel template to run that script.

**Comment by kaleykobber** [comment]
Thank you. Can we use the same template we use for the Training Case Creator script?

**Comment by CDPotter** [comment]
They are one in the same, Krabappel was just a project code name.

**Comment by RoberT-1000** [comment]
Yep. You have to use that. The script looks in specific places for data validation to make sure it is writing the appropriate values to each field.

**Comment by kaleykobber** [comment]
Gotcha.

**Comment by RoberT-1000** [comment]
What @CDPotter said :)

**Comment by kaleykobber** [comment]
Did you get a chance to upload the instructions to SIR? I'm still not seeing them...
