### ISSUE TITLE
LTC - GRH list generator enhancement: add field for FACI type coding

### ISSUE THREAD

**Issue by IlseFerris** [MN-Script-Team/DHS-MAXIS-Scripts#2816]
FACI name is a column in this script. Would be super helpful to also include the faci coding type. 

Assign to me.

**Comment by CDPotter** [comment]
@MN-Script-Team/maxis-scriptwriters This is live in master, could I get confirmation that it is working?

**Comment by IlseFerris** [comment]
Confirmed, working in MASTER
