### ISSUE TITLE
Documents rec'd HSR scanner project for x127 users

### ISSUE THREAD

**Issue by IlseFerris** [MN-Script-Team/DHS-MAXIS-Scripts#2818]
Request from Hennepin County supervisors to add functionality to this script for HSR's (eligibility workers) to indicate if the document was scanned by the worker. This is a huge customer service initiative at Hennepin County. 

Assign to me.

**Comment by CDPotter** [comment]
Just to help me get the request, when would having a case note documenting the worker scanned it be helpful? 

I've only had experience with Onbase and that system was pretty good about tracking who made the scan.

**Comment by IlseFerris** [comment]
Supervisors want case notes to document that the forms were rec'd/scanned by the HSR. Although ECF (our EDMS system), they want this information to be reflected in MAXIS.

**Comment by CDPotter** [comment]
@IlseFerris Can you confirm this is working in Hennepin Master? @MN-Script-Team/maxis-scriptwriters can someone not from Hennepin confirm that they do not see the new checkbox in master?

**Comment by IlseFerris** [comment]
Working in Hennepin Master
