### ISSUE TITLE
Change in Self-Employment Policy

### ISSUE THREAD

**Issue by ramonalisa1** [MN-Script-Team/DHS-MAXIS-Scripts#282]
Scripts puloing data from STAT/BUSI may need to be updated for 2/1/15 as there is a change in which self-employment will be calculated.  New fields are being added to STAT/BUSI.  See policy:

Self-Employment Handout for 2/1/15
The purpose of this handout is to give further guidance in implementing the new simplified self-employment policy effective 2/1/15.    

The new simplified self-employment policy means:
•	Self-Employment expenses will no longer be used to calculate self-employment income
•	Clients may choose between two methods based on either 50% current gross self-employment income or their annual self-employment taxable income filed with the IRS within the last twelve months
•	This policy change applies to MFIP, GA, MSA (Non-SSI), GRH (Non-SSI), and SNAP with some exceptions

Guidelines:   
Self-Employment Definition:   What is considered Self-Employed or Self-Employment has not changed. 
Continue to refer to: CM 2.61 Glossary “Self-Employed” and “Self-Employment.” 

Effective 2/1/15 Implementation:   
For applications with self-employment income processed on or after 2/1/15, use the new self-employment policy. 

For participants with self-employment income, use the new self-employment policy at recertification starting 2/1/15 or recertifications after 2/1/15.    However, continue to use the self-employment policy prior to 2/1/2015 until recertification, even if a change is reported prior to recertification. 

Effective 2/1/15 New Self-Employment Budgeting:
Applicants and participants at recertification must choose one of the methods described below for determining self-employment income, unless there are other program provisions (see SNAP).   

Effective 2/1/15 New Self-Employment Income Calculation:
An agency must determine self-employment income based on client choice, which is either:
(1)  50% of gross earnings from self-employment 
- As determined by business records or self-employment form
- Gross earnings are defined as earned income before taxes and deductions
- This method is based on using current income to calculate self-employment income
or
(2)  Taxable Income 
-  As determined from an Internal Revenue Service (IRS) tax forms that has been filed with the IRS within the last year
-  Taxable Income means “Net profit” from the applicable annual tax forms
-  Divide the “Net profit” by the twelve to find the monthly average income for the year 
- This method is based on using an annual average to calculate self-employment income

Clients may choose either method, unless there are other programs provisions (see SNAP).

Document in case notes which method the applicant or participant has chosen. 

Self-Employment Hours 
MFIP:  Only the hours the participant earns the federal minimum wage count toward the participation requirements. The number of self-employment hours is determined by dividing the net self-employment income by the federal minimum wage.

Changing Method at Recertification:  
Participants must be given the option to change their method of self-employment income calculation at recertification

Changing Method between Recertification:
50% to Taxable Income:  Participants, who use the 50% of current self-employment income method, may choose the Taxable Income method at the next benefit month, unless there are other program provisions (see SNAP).

Taxable Income to 50%:  Participants, who use the Taxable Income method, must continue to use this method until recertification, unless there is an unforeseen significant change.    An unforeseen significant change means a decrease in income, where their income decrease was equal to or greater than the earned income disregard from the income used to determine the benefit for the current month, and this decrease was unpredictable. 

For example, if a participant’s current eligibility was based on income of $1000.00, and their earned income disregard for that program is 50% (e.g. MFIP), and the client verifies their income has been reduced to $500.00, and it was due to an unforeseen/unpredictable change, they would be eligible to change their method from using Taxable Income to the 50% method (50% of current gross income).   Note:  The earned income disregard is program specific. 

Requests to change options must be in writing by the client.

**Comment by ramonalisa1** [comment]
System Change:  
Effective for benefit month 2/1/15, two new fields, “Self Employment Method” and “Date”,  have been added to STAT/BUSI to record the counted self-employment method and option date for tracking and reporting purposes.  These fields should only be completed if the applicant or recipients meets the conditions as stated above. 
 
Workarounds for self-employment rental and roomer/boarder income for affected cash programs will be announced in a later posting.  Please note that this policy change does not impact how MAXIS determines eligibility and benefit amount.  The counted self-employment gross income calculation will continue to be completed manually by the workers.

**Comment by theVKC** [comment]
This may require a change to the shared functions, as the parts that read BUSI would be stored there. I’m thinking we get a small team to work the functions library and get this working…


Caution: This e-mail and attached documents, if any, may contain information that is protected by state or federal law. E-mail containing private or protected information should not be sent over a public (nonsecure) Internet unless it is encrypted pursuant to DHS standards. This e-mail should be forwarded only on a strictly need-to-know basis. If you are not the intended recipient, please: (1) notify the sender immediately, (2) do not forward the message, (3) do not print the message and (4) erase the message from your system.
