### ISSUE TITLE
CSES Scrubber bug reading wrong MFIP month for change

### ISSUE THREAD

**Issue by StormageddonDLOA** [MN-Script-Team/DHS-MAXIS-Scripts#2824]
The portion of the CN that states if there is a change in MFIP isn't working correctly all of the time. A co-worker found at least 2 instances where the CN says "no change" but there is a change in the new MFIP results. 

I have a couple case numbers if you need them to investigate the issue.

**Comment by CDPotter** [comment]
Could you email me case numbers? Charles.Potter@state.mn.us

**Comment by StormageddonDLOA** [comment]
I’d love to but I keep getting the email back as undeliverable at the address you put in behind the request. Charles.Potter@state.mn.us<mailto:Charles.Potter@state.mn.us>

**Comment by CDPotter** [comment]
Forgot the middle intial, that's what I get for not emaling myself very often.  Charles.D.Potter@state.mn.us

**Comment by StormageddonDLOA** [comment]
LOL…no problem!

**Comment by CDPotter** [comment]
The fantastic @C-Love is going to take this one. The script is set up to grab it's change status from ELIG/MFIP so that is where it's getting "NO CHANGE".

**Comment by C-Love** [comment]
It appears to be going to the wrong footer month to get this information.

This is read from ELIG/MFIP so it is going off of the last approved version listed for the month that has been changed. This should be valid information - if we look at the correct month :)

**Comment by CDPotter** [comment]
@MN-Script-Team/maxis-scriptwriters Here's hoping there's still some CSES messages to test this on!

**Comment by Farleight** [comment]
We should really build language into these allowing us to artificially recreate MAXIS messages through TIKL for testing purposes... not so much for cases like these where the things pop up again every month, but for the more obscure messages. That'd be an easy func-lib addition. Convert "TIKL" to "Whatevs".

Pipe dreams...

**Comment by CDPotter** [comment]
As I understand it PRISM has a magic training region with tons scenarios built in already that refreshes once a week so you can test to your heart's content. Not jealous at all =)

**Comment by courtrightd** [comment]
I don't have specific case numbers, but our master branch users have run the script a dozen times since this install with no issues reported.

**Comment by CDPotter** [comment]
Thanks @courtrightd ! I think I'm going to call this fix good and commit to release.

Special thanks to @C-Love for the repairs to this monster of a script!
