### ISSUE TITLE
Enhancement Request - CAF/Combined AR - 2 yr review TIKL

### ISSUE THREAD

**Issue by Farleight** [MN-Script-Team/DHS-MAXIS-Scripts#2825]
Request from Carlton worker to add a TIKL checkbox to CAF and Combined AR scripts for 2 year review cases, to remind workers to contact the client after 12 months. Additional functionality discussed to add TIKL wording to DAIL Scrubber for notice issuance, but that will be a separate issue once this one is cleared.

As is often the case, I can't guarantee a timeline on when I can work on this, so if someone else wants it, have at it. If it's still sitting out here when I get free time, I'll grab it.

**Comment by CDPotter** [comment]
What if instead of a TIKL checkbox we have the script determine this automatically? The CAF has an autofill from REVW (if recert is chosen) So it's already going to the panel. We could grab the next ER date for SNAP and if it is over 12 months away then we could assume it's for 2 years make the script TIKL.

Thoughts?

**Comment by Farleight** [comment]
It would have to be tied to the program so it wouldn't TIKL if they renewed something else in the off year, but yeah, that sounds better. Less clutter on the window and more accurate.

**Comment by CDPotter** [comment]
Great! Since this ramp-up was my idea I think I'll take this one.

**Comment by CDPotter** [comment]
Ok looking for a bit of feedback on verbiage!

For MAXIS footer month 02/17:

![image](https://cloud.githubusercontent.com/assets/7841989/21855977/df596d18-d7e5-11e6-97a6-bb54b6a8bcf4.png)


TIKL TEXT: If SNAP is open review to see if 12 month contact letter is needed. Send letter if it is needed.

**Comment by Farleight** [comment]
The MsgBox is fine. I'd add a comma after "If Snap is open," on the TIKL... and then that leads to the next question. If we open the issue to run the DAIL-scrubber and auto-send the notice from that TIKL, then we must as well mention the Dail Scrubber in the TIKL itself so people know that's an option.

**Comment by Farleight** [comment]
might as well... not must as well. (Although I won't lie; I'm going to start using "must as well.")

**Comment by CDPotter** [comment]
I don't see why we couldn't do that as well now that the TIKL will be standardized.

**Comment by Farleight** [comment]
So, something like this?

TIKL TEXT: If SNAP is open, review to see if 12 month contact letter is needed. DAIL Scrubber will send letter if used on this TIKL. All Your Base Are Belong To Us.

**Comment by CDPotter** [comment]
This is live in MASTER now, could I get some testing @MN-Script-Team/maxis-scriptwriters ?

**Comment by IlseFerris** [comment]
Confirmed, working in Master. There's a spelling error though on the message box
Clicking, not Cicking. I would also put a comma after CASE NOTE in that sentence.

**Comment by C-Love** [comment]
Separate thought - what about any TIKL with DAIL scrubber support gets this kind of handling. Like at the end we say 'THIS TIKL IS A PART OF THE DAIL SCRUBBER COLLECTIVE.' Or something much more acceptable in the world of a financial worker.

**Comment by Farleight** [comment]
Like a D.S. al Coda, except D.S. means Dail Scrubber. (Don't analyze that too much if you want it to make sense)

**Comment by CDPotter** [comment]
@C-Love seems like a good new issue!
