### ISSUE TITLE
Enhancement Request - Add functionality to update GRH PIC with Paystub Recv'd 

### ISSUE THREAD

**Issue by RoberT-1000** [MN-Script-Team/DHS-MAXIS-Scripts#2826]
I can take this. The idea is that the functionality that updates the SNAP PIC could be copied and pasted to update the GRH PIC.

**Comment by CDPotter** [comment]
@MN-Script-Team/maxis-scriptwriters This is in MASTER could I get confirmation that it is working?

**Comment by IlseFerris** [comment]
Confirmed, working in master
