### ISSUE TITLE
CSES scrubber enhancement: pending case handling & info

### ISSUE THREAD

**Issue by IlseFerris** [MN-Script-Team/DHS-MAXIS-Scripts#2830]
Cases that are pending MFIP will rec this error message: "script errar at Line 1 Column 1: Type mismatch Budg_Jobs" when processing CSES Dails. 

Enhancement will add message box instructing the worker to process this manually. 
@C-Love will take this as she is working on a couple other issues with CSES. 
Thanks @C-Love!

**Comment by CDPotter** [comment]
@MN-Script-Team/maxis-scriptwriters Here's hoping there's still some CSES messages to test this on!
