### ISSUE TITLE
NAV - REPT/ACTV and REPT/ACTV - bottom

### ISSUE THREAD

**Issue by kaleykobber** [MN-Script-Team/DHS-MAXIS-Scripts#2838]
These two NAV scripts no longer give the option to enter the worker number (last 3 digits) upon selecting. They navigate to the listing for the user signed into MAXIS. In master, it asks for the last 3 digits, but not in release (it was like this in release previously). Was it removed?

**Comment by CDPotter** [comment]
Check your global variable settings, there are two variables regarding this feature:

1: all_users_select_a_worker: if this is TRUE then everyone in the agency can enter the worker number for NAV scripts. 

2: users_using_select_a_user: this is an array that contains computer log in names (windows log ins) of people who can enter worker numbers into NAV scripts. You can also view this list by running utilities -> info script

**Comment by kaleykobber** [comment]
Ah - got it. We have different global variables for master and release. For master we have "ALL" and for release we have "USERS_USING_SELECT_A_USER = ARRAY()

**Comment by kaleykobber** [comment]
We would need to establish a list of users in this case?

**Comment by CDPotter** [comment]
If you wanted to limit it to certain release branch users yes, if you want everyone to be able to use it just change it to all for the release version of global variables.

**Comment by kaleykobber** [comment]
Gotcha. Thank you!

**Comment by CDPotter** [comment]
No problem! If there are any issues let me know. I'm gonna close the issue.
