### ISSUE TITLE
NEW scripts: SNAP WCOMS: Death, state duplicate assistance, returned mail

### ISSUE THREAD

**Issue by CDPotter** [MN-Script-Team/DHS-MAXIS-Scripts#2845]
Gonna knock out some problem SNAP wcoms quick before my end here. 

Death: see TE02.05.19 – “This SNAP case has been closed because the only eligible unit member has died.”

Duplicate assistance: You received SNAP benefits from the state of: (list the State that the client received SNAP benefits from) during the month of (Month & Year that SNAP benefits in the other were issued).  You cannot receive SNAP benefits from two states at the same time. **(for this one I want to incorporate it into current version as an option)**

Returned Mail:  “Your mail has been returned to our agency.  On (insert date) you were sent a Request for you to Contact this agency because of this returned mail.  You did not contact this agency by (insert the 10 date deadline) so your SNAP case has been closed.”

**Comment by CDPotter** [comment]
Attention all MFIP peeps: Does the duplicate assistance verbiage for for MFIP as well?

**Comment by CDPotter** [comment]
There are now live in Master. Could people test them in training region? @MN-Script-Team/maxis-scriptwriters 
(all in SNAP sub menu)
notices - client death WCOM
notices - duplicate assistance wcom
notices - returned mail wcom

**Comment by IlseFerris** [comment]
Tested on cases that did not have notices waiting. Out of state dup assistance worked correctly in this case, and said there was no notice. WCOM death and returned mail did not catch that there were not pending notices and gave a confirmation that the script worked at the end. 

I will approve results, and test on cases with notices pending next.

**Comment by IlseFerris** [comment]
All new WCOM's are working. 
The duplicate assistance wcom doesn't have a space between the footer month/year, and the next sentence (or a period). Other than that, looked good.

**Comment by CDPotter** [comment]
Ah, seems I left behind the MFIP variable from the code I poached from duplicate assistance. I committed directly to them, could you give em one more go?

**Comment by IlseFerris** [comment]
Duplicate assistance is looking good now.
