### ISSUE TITLE
ABAWD FIATer: new script

### ISSUE THREAD

**Issue by IlseFerris** [MN-Script-Team/DHS-MAXIS-Scripts#2848]
This is the second part of the issue brought up in #2690. 

With the banked months fiater retired, a script is needed to FIAT eligibility, deductions and income into the SNAP budget for cases that are eligible for ABAWD months, but eligibility results are not being created due to having banked months or second set month in the ABAWD tracking record. 

Per POLI TEMP: TE.02.06.02: 
> 
> ABAWDs who have used the initial 3 months of eligibility should again be eligible for the initial 3 month period of ABAWD eligibility after the 36 month period has ended, regardless of whether or not they used the 2nd 3-month period of ABAWD eligibility, see 0011.24 (Able-Bodied Adults Without Dependents).  
> 
> Currently, MAXIS fails the ABAWD Person test if the ABAWD status field on WREG is coded with a 10-ABAWD Counted Month and there are more than 3 months with X, M, Y, or N entered on the ABAWD tracking record. This does not follow SNAP policy.                                         
>                                                                       
> Workaround:  FIAT the ABAWD Person test for the household member that MAXIS incorrectly failed.                           

So this uses a lot of what was input into the ABAWD banked months fiater, but will have some special handling for the WREG panel. 

Assign to me.

**Comment by CDPotter** [comment]
@MN-Script-Team/maxis-scriptwriters this is live in MASTER could I get some confirmation it is working from a few sources?

**Comment by courtrightd** [comment]
Multiple users report successful use already in St. Louis.

**Comment by CDPotter** [comment]
Since this is a new script can I get one more county to confirm this is working as intended? @MN-Script-Team/maxis-scriptwriters

**Comment by IlseFerris** [comment]
Just tested, working beautifully in Master
