### ISSUE TITLE
NOTE - DENIED PROGRAMS -- procedural question about EGA-only applications

### ISSUE THREAD

**Issue by RobertFewins-Kalb** [MN-Script-Team/DHS-MAXIS-Scripts#285]
We have a concern about how the DENIED PROGRAMS case note should deal with EGA-only applications. Currently, the case note writes that the case becomes new intake 30 days after the date of initial application BUT the concern arose from a case that was denied during the intake as the client was over 200% FPG. We didn't see anything in the Combined Manual that says the case shouldn't have been a new intake the next day -- and I do know that for clients that are serial EGA applicants, a procedure exists wherein the new application is held for 30 days (for instance, if the client is ineligible because s/he has received EGA within the past 12 months and is not eligible to receive EGA at application) to prevent the client from applying immediately after being denied. Additionally, when this was discussed with my supervisor, we didn't find any guidance on reinstating a denied EGA applciation.

Like I said, there isn't a great deal in the Combined Manual about dealing with EGA, we're throwing this out the GitHub as a way of generating discussion on EGA processing procedure. Personally, I'm OK with changing the logic to something like ...

IF emer_check = 1 AND (snap_check = 0 AND cash_check = 0 AND hc_check = 0) AND (open_progs = "" OR open_progs = "none") THEN intake_date = dateadd("D", date, 1)

...and also removing the line:
IF emer_check = 1 THEN CALL write_editbox_in_case_note("Last emer REIN date", emer_last_REIN_date, 6)

I'm also going to post this to the Facebook group...

Thoughts?

**Comment by theVKC** [comment]
As an idea, it makes sense. I think that the logical choice (considering EGA is largely county-driven with lots of conflicting policies) would be something in the installer which sets a global (county-wide) variable. I'm a bit concerned about adding these right now (as we're currently going live with Operation Frink) but will definitely be keen on changes in the coming months...

**Comment by theVKC** [comment]
@RobertFewins-Kalb, any movement on this idea? Want I should close it?

**Comment by RobertFewins-Kalb** [comment]
Shut it down.

**Comment by theVKC** [comment]
Donezo.
