### ISSUE TITLE
FSET sanction enhancement: leave sanction number and reason in 'resolved sanction' option

### ISSUE THREAD

**Issue by IlseFerris** [MN-Script-Team/DHS-MAXIS-Scripts#2851]
Hennepin County SNAP FSET sanction worker requested: when the 'resolved sanction' option is selected the number of sanctions field and reason for sanction filled should not be blanked out. This provides workers information about the current sanction, and is informational for the next potential sanction. 

Assign to me.

**Comment by IlseFerris** [comment]
FYI: The notice is not effected when these fields are entered, only if the sanction begin date is entered.

**Comment by CDPotter** [comment]
This is live in Master could we get some testing @MN-Script-Team/maxis-scriptwriters ?

**Comment by IlseFerris** [comment]
Confirmed, working in master
