### ISSUE TITLE
We need to overhaul how income is case noted

### ISSUE THREAD

**Issue by theVKC** [MN-Script-Team/DHS-MAXIS-Scripts#288]
Basically, right now it case notes a single amount, without respect to the program selected. It targets SNAP first, followed by cash, then HC. I think it's time we split the amounts. So, the new code would look something like this:

```
If program = SNAP then <code to go get PIC income>
If program = MFIP then <code to go get retro/pro income>
If program = HC and footer_month = current then <code to get pro income>
If program = HC and footer_month = +1 then <code to get HC popup>
```

Then the case note would read something like: _“works at McDonalds, $100/wk budgeted for SNAP, $150/wk budgeted for MFIP and HC”._

I'm hoping to do this, but I'm putting it out here as a "help wanted" in case anyone else wants to hit it. It's a complicated one, but will be very well received by lots of folks.

**Comment by RobertFewins-Kalb** [comment]
I'll take a crack at this one

**Comment by theVKC** [comment]
Should we team up on it Wednesday? Perhaps I work all day from Anoka Wednesday and we knock this one out, as well as the BUSI updates?


Caution: This e-mail and attached documents, if any, may contain information that is protected by state or federal law. E-mail containing private or protected information should not be sent over a public (nonsecure) Internet unless it is encrypted pursuant to DHS standards. This e-mail should be forwarded only on a strictly need-to-know basis. If you are not the intended recipient, please: (1) notify the sender immediately, (2) do not forward the message, (3) do not print the message and (4) erase the message from your system.

**Comment by RobertFewins-Kalb** [comment]
I prefer that idea although I'm going to start poking at our copy of the functions file and run some obsolete scripts through it

**Comment by theVKC** [comment]
Can you book us a space all day for Wednesday then? And, do you need me to talk to anyone about getting you and @CDPotter off of appointments? Or are you good?

I have a DHS laptop, but if we need another one I can bring my county laptop as well.


Caution: This e-mail and attached documents, if any, may contain information that is protected by state or federal law. E-mail containing private or protected information should not be sent over a public (nonsecure) Internet unless it is encrypted pursuant to DHS standards. This e-mail should be forwarded only on a strictly need-to-know basis. If you are not the intended recipient, please: (1) notify the sender immediately, (2) do not forward the message, (3) do not print the message and (4) erase the message from your system.

**Comment by RobertFewins-Kalb** [comment]
What time are you thinking? Both of the computer labs appear to be open

**Comment by theVKC** [comment]
All day? This is a pretty heavy update. If we end early, we end early.


Caution: This e-mail and attached documents, if any, may contain information that is protected by state or federal law. E-mail containing private or protected information should not be sent over a public (nonsecure) Internet unless it is encrypted pursuant to DHS standards. This e-mail should be forwarded only on a strictly need-to-know basis. If you are not the intended recipient, please: (1) notify the sender immediately, (2) do not forward the message, (3) do not print the message and (4) erase the message from your system.

**Comment by CDPotter** [comment]
We shouldn’t be on any rotations for Wednesday and can just schedule ourselves in a meeting.

**Comment by theVKC** [comment]
@CDPotter, @RobertFewins-Kalb, and I will be handling this issue on Wednesday.

**Comment by theVKC** [comment]
Resolved with commits yesterday both here and on FuncLib. Closing issue. Nice work @RobertFewins-Kalb and @CDPotter!
