### ISSUE TITLE
New ACTION script: FIAT GA-RCA into SNAP budget

### ISSUE THREAD

**Issue by IlseFerris** [MN-Script-Team/DHS-MAXIS-Scripts#2883]
ACTION script that will determine which cash program is open, and fiat each months cash grant into each month's SNAP budget through current month plus one. 

I will take this. I have a local copy that is being used. Also instructions are ready.

**Comment by C-Love** [comment]
Will be added to the collaborative branch and then tagged for post freeze.

**Comment by IlseFerris** [comment]
https://github.com/MN-Script-Team/DHS-MAXIS-Scripts/tree/scriptwriter_collaborative/actions
Added to collaborative branch :)

**Comment by C-Love** [comment]
To be handled once conversion is over.
