### ISSUE TITLE
DAIL scrubber & Approved Programs

### ISSUE THREAD

**Issue by kaleykobber** [MN-Script-Team/DHS-MAXIS-Scripts#2887]
Adding functionality to process the TIKL messages generated from the Approved Programs script. The scrubber would look into the case, make updates (WREG) and case note.

**Comment by C-Love** [comment]
This is in regards to Banked Months - the TIKLs set for ever subsequent month to update the counter on WREG in each month.

This is basically a new DAIL Scrubber script request

**Comment by C-Love** [comment]
To be handled once conversion is over.
