### ISSUE TITLE
Bulk List for School panels

### ISSUE THREAD

**Issue by KLeflay** [MN-Script-Team/DHS-MAXIS-Scripts#2888]
Hi, 
Can we request a bulk script list to review all cases with students that may be causing errors?  
We would like to target 17 year olds or older and have the following screens on Excel spreadsheet:
Memb, Memi, Schl, Stin, Stec, Wreg
Thanks!! Kay Leflay, Scott County

**Comment by C-Love** [comment]
Create a new issue in the python repo once conversion has happened

**Comment by C-Love** [comment]
To be handled once conversion is over.
