### ISSUE TITLE
February 2015 Policy Changes -  30 Day Reinstatement

### ISSUE THREAD

**Issue by ramonalisa1** [MN-Script-Team/DHS-MAXIS-Scripts#290]
Effective February 1, 2015, a 30-day reinstatement period will be allowed.  If a cae closed due to not completing the recertification process, the case may be reinstated if recertification requirements are met within 30 days of the termination of benefits.  Benefit are retroative for the full month benefit.

I am sure a IB will be coming out soon.  This may affect the way some of our case noting scripts for case closures are worded

**Comment by theVKC** [comment]
What program does this refer to?

**Comment by ramonalisa1** [comment]
14 Legislative Session (See Bulletin 14-69-05).  It is to provide unity among GA, MSA, GRH, DWP and MFIP.  So basically the cash programs.

**Comment by theVKC** [comment]
Thank you (that's what I thought). I'm thinking closed programs for sure needs some touch-up work. Any takers?

**Comment by RobertFewins-Kalb** [comment]
This has been completed. Please close.
