### ISSUE TITLE
Enhancement to NOTES - Approved Programs for XFS cases

### ISSUE THREAD

**Issue by kaleykobber** [MN-Script-Team/DHS-MAXIS-Scripts#2904]
The Approved Programs script case notes grant information for the approval month + 1. When expedited food support is approved for one month only (postponed verifications are required in order for second month to be issued), the script adds grant information for the second month even though it was not included in the approval package. If this isn't recognized by the worker and corrected in the case note, the case note appears misleading.

It would be great if the script could be enhanced so that it can identify the non-included month of an expedited food support approval package.

**Comment by C-Love** [comment]
This should be considered when addressing issue #3012 (merging Approved/Denied/Closed programs scripts).
