### ISSUE TITLE
Scripts can no longer edit SPEC/WCOM notices

### ISSUE THREAD

**Issue by courtrightd** [MN-Script-Team/DHS-MAXIS-Scripts#2906]
Due to MAXIS update, an extra screen appears when editing notices, handling will need to be added to scripts to bypass the select recipient screen.  
The following scripts are likely effected and no longer functioning:

MA Inmate Application WCOM
MA-EPD No Initial Premium Paid
Method B WCOM
ABAWD with child in HH WCOM
Banked Month WCOMS
Client Death WCOM
Duplicate Assistance WCOM
Postponed WREG verif.
Returned Mail WCOM
Denied Programs (checkbox to add requested verifs to WCOM)

**Comment by courtrightd** [comment]
I am developing a fix for this right now, will create a pull in the event someone becomes available to approve it.

**Comment by theVKC** [comment]
I've received permission: here we go. @courtrightd is on it and I'll pull it in.

We'll need testers. @RoberT-1000? @IlseFerris? @C-Love? @MelissaFox-Stearns? @StormageddonDLOA? @Farleight?

**Comment by C-Love** [comment]
I can test!

**Comment by RoyStearns** [comment]
I am working phones so I cant do any writing, but I should be able to do some testing - so long as it is not a full moon :)

**Comment by courtrightd** [comment]
So I have updated all scripts, pull request in, whenever @theVKC decides we can merge.   I have only tested them on 1 scenario each, so further testing would be great.

**Comment by theVKC** [comment]
Pulled in with #2907. Ready for testing. Can I get testers for this? @C-Love, @IlseFerris, @RoyStearns?

**Comment by IlseFerris** [comment]
Tested Banked months WCOM. This is working. I'll test a few more.

**Comment by IlseFerris** [comment]
I've tested all of these scripts. They are working. 
ABAWD with child in HH WCOM
Banked Month WCOMS
Client Death WCOM
Duplicate Assistance WCOM
Postponed WREG verif.
Returned Mail WCOM

I have meetings all morning. Can someone test the rest?
MA Inmate Application WCOM
MA-EPD No Initial Premium Paid
Method B WCOM
Denied Programs (checkbox to add requested verifs to WCOM)

**Comment by courtrightd** [comment]
Denied Programs is working.

**Comment by courtrightd** [comment]
Method B WCOM, MA Inmate Application WCOM, and MA-EPD No Initial Premium Paid have all been tested and confirmed working here.

**Comment by theVKC** [comment]
Good deal. Due to the nature of this issue, I will be pulling this in to release right now. Nice work @courtrightd! Thanks for testing, all! #GoTeamGo
