### ISSUE TITLE
Case Note Templates - Include in Script Instructions

### ISSUE THREAD

**Issue by kaleykobber** [MN-Script-Team/DHS-MAXIS-Scripts#2909]
Our users have asked for information regarding case note templates used in scripts. This would be mainly for new workers or for use when scripts are down. Current script instructions do include screenshots, but not necessarily of case notes and usually not the entire case note.

Since case note language is written into the script code - is there a way to find and display that code - in a format that makes sense, that is updated in real-time as the script is updated in release, so that users can access it? (A way to view the output for scripts that case note?)

(This might be similar to PRISM issue #745 @theVKC ??)

**Comment by theVKC** [comment]
I am, in fact, working on this in PRISM https://github.com/MN-Script-Team/DHS-MAXIS-Scripts/pull/745. I expect to have a working prototype today. I'll tag it here when it's ready.

**Comment by C-Love** [comment]
With Python this will be potentially much easier and we can look at possible doc string solutions. We should keep this in mind that users want to be able to see what the output case note looks like from a script run.

**Comment by C-Love** [comment]
docstrings will do this thing
