### ISSUE TITLE
New script: BULK - PROFESSIONAL NEED STATEMENT

### ISSUE THREAD

**Issue by IlseFerris** [MN-Script-Team/DHS-MAXIS-Scripts#2914]
For each x number identified by the user in the user input dialog, the script will determine if the case is active on GRH. If so, it will add it to the Excel list. The script will determine which facility to gather the information for. The script does so by searching for FACI panels with open ended discharge dates. If there is not a case with an open ended discharge date, the information will be blank in the spreadsheet. This can help identify cases that are open on GRH, but not open in a FACI. 

If the case has an open-ended facility date, then the script will:
	1. Document the worker number
	2. Document the case number
	3. Read and document the Facility name
	4. Read and document the Facility type
	5. Read and document the GRH plan required code
	6. Read and document the plan verified code
	7. Read and document the Cty appd placement code
	8. Read and document the Approval cty code
	9. Read and document the GRH DOC amt
	10. Read and document the GRH rate
	11. Read and document the GRH plan dates from DISA

**Comment by C-Love** [comment]
Will be added to the collaborative branch and then tagged for post freeze.

**Comment by IlseFerris** [comment]
https://github.com/MN-Script-Team/DHS-MAXIS-Scripts/tree/scriptwriter_collaborative/bulk

**Comment by C-Love** [comment]
To be handled once conversion is over.
