### ISSUE TITLE
NOTES enhancement: Add 'Navigate to MMIS' buttons on several scripts

### ISSUE THREAD

**Issue by IlseFerris** [MN-Script-Team/DHS-MAXIS-Scripts#2922]
Common area of error is not checking/updating MMIS when processing HC cases. NOTES scripts that would benefit from this navigation functionality are: 

- Mnsure retro HC applcation
- HC Renewal
- HCAPP
- HRF
- LEP - EMA
- LTC - Intake approval
- LTC - MA approval
- LTC - renewal

**Comment by C-Love** [comment]
This might be a part of Hydra

**Comment by C-Love** [comment]
This will be a part of Hydra and all the wonderful nav things that will happen.
