### ISSUE TITLE
NOTES - APPROVED PROGRAMS enhancement for MA-EPD participants

### ISSUE THREAD

**Issue by IlseFerris** [MN-Script-Team/DHS-MAXIS-Scripts#2927]
In association with issue #2926, enhancement requested to the NOTES - APPROVED PROGRAMS script for MA-EPD applicants. At approval of MA-EPD case, several steps need to be taken/completed.

Proposed solution:

- Add information to the APPROVED PROGRAMS script which includes the following fields:
- Was initial premium Paid? Y or N
- Were MAXIS MA/DP results approved?
- Was MA/DP SPAN opened in MMIS? 
- Was MADE Premium Useform Filled out and sent to DHS via SIR? (Add link to the new MADE Premium Useform in SIR)
- Was case assessed for County Based Medicare Reimbursement? (Under 200% FPG found under BSUM Budget) - Possibly functionality to check for this.
- If under 200% has case been submitted for cost-effective health insurance reimbursement?

**Comment by Farleight** [comment]
If you use functionality to check for the reimbursement, we may need an answer on one question we've sent to DHS (which they have not been quick to respond to). Primarily, is the 200% calculated based on the FIAT'd EPD average or based on actual monthly income?

We've got one case here where averaging the income out actually pushed the person above the 200%, when in reality they're only over it for one month out of a 6-month span. General Cost-effective rules would make one think they'd still be elig based on actual income, and that is indeed how Ebud seemed to calculate it, but it started a large argument here and DHS has yet to weigh in.

**Comment by C-Love** [comment]
This should be considered when addressing issue #3012 (merging Approved/Denied/Closed programs scripts).
