### ISSUE TITLE
Bug: WCOM function in MFIP sanction/DWP disq. not adding worker comment

### ISSUE THREAD

**Issue by IlseFerris** [MN-Script-Team/DHS-MAXIS-Scripts#2929]
This is in association issue #2906. This one was missed when scripts were identified as needing the update. 
Since this is critical, is there a way to get this pulled in @theVKC?

**Comment by courtrightd** [comment]
Oops!  Forgot about these.  That means we can add NOTES - MFIP to SNAP transition to this issue as well.

**Comment by C-Love** [comment]
We think they changed back this WCOM change they made... this may no longer even be an issue,

@MN-Script-Team/maxis-scriptwriters - can anyone else confirm?

**Comment by C-Love** [comment]
Confirmed this is no longer an issue. Closing
