### ISSUE TITLE
BULK - MA-EPD Cases Pulled to EXCEL

### ISSUE THREAD

**Issue by ramonalisa1** [MN-Script-Team/DHS-MAXIS-Scripts#293]
I work with Medicare Part B premium reimbursements for our County and it would be nice to be able to find out which cases are MA-EPD.  Should be fairly simple script to write.  I can give it a try.

**Comment by theVKC** [comment]
You got it!

**Comment by ramonalisa1** [comment]
Well, didn't get to far.  I am trying to write this one completly from scratch instead of stealing.  So I put this into the script:

'LOADING ROUTINE FUNCTIONS
url = "https://raw.githubusercontent.com/MN-Script-Team/BZS-FuncLib/master/Master Functions Library.vbs"
Set req = CreateObject("Msxm12.XMLHttp.6.0")
req.open "GET", url, False
req.send
If req.Status = 200 Then
	Set fso = CreateObject("Scripting.FileSystemObject")
	Execute req.responseText
End if

I am getting the following error:

'ActiveXcomponent can't create object: 'Mxsm12.XML.Http.6.0"

Help?

**Comment by theVKC** [comment]
Capitalize “MASTER FUNCTIONS LIBRARY.vbs”, just like that. We changed it a couple of weeks ago to standardize the caps across all scripts.


Caution: This e-mail and attached documents, if any, may contain information that is protected by state or federal law. E-mail containing private or protected information should not be sent over a public (nonsecure) Internet unless it is encrypted pursuant to DHS standards. This e-mail should be forwarded only on a strictly need-to-know basis. If you are not the intended recipient, please: (1) notify the sender immediately, (2) do not forward the message, (3) do not print the message and (4) erase the message from your system.

**Comment by RobertFewins-Kalb** [comment]
@ramonalisa1  -- are we done with this issue?

**Comment by theVKC** [comment]
I am closing this issue for now due to lack of activity, but it can be reopened if/when a scriptwriter wants to take it on.
