### ISSUE TITLE
Enhancement Idea for all PHONE NUMBER Edit Boxes

### ISSUE THREAD

**Issue by C-Love** [MN-Script-Team/DHS-MAXIS-Scripts#2930]
I had a thought. What if we updated the edit boxes in which workers enter phone numbers to be a combo list box - (whatever it's called) - the one that has preselected dropdowns BUT can also be typed in! This way we can auto fill with ALL of the phone numbers that are listed in MAXIS and still allow workers to put in a different number  if appropriate. This also makes sure the worker is actually looking at the phone number instead of just relying on what the script filled in. 

What does everyone think?

**Comment by IlseFerris** [comment]
Oh I love that!

**Comment by C-Love** [comment]
I have started working on this in python with the panel classes. This should be addressed when converting.

**Comment by C-Love** [comment]
This will be a part of panel classes. Closing
