### ISSUE TITLE
Enhancement- CSES scrubber text is being cut off

### ISSUE THREAD

**Issue by MiKaylaH22** [MN-Script-Team/DHS-MAXIS-Scripts#2932]
User reported that text is being cut off, when we have a chance to enhance this script it woudl be great to include this. 

![image](https://cloud.githubusercontent.com/assets/17990650/26266410/c8ff91b2-3caa-11e7-98e4-b2fca4dad6cb.png)

**Comment by C-Love** [comment]
Closing - this will resolve naturally when dialogs have grids
