### ISSUE TITLE
New script: BULK - MFIP SANCTION

### ISSUE THREAD

**Issue by IlseFerris** [MN-Script-Team/DHS-MAXIS-Scripts#2936]
We've developed a new BULK script to assist our MFIP sanction experts. Participant info is pulled from REPT/MFCM, and includes the following information: 

Worker number
Case number
Client name
Member number
Vendor reason code
ABPS: support coop code
Attended financial orientation indicator
Financial orientation date
EMPS sanction reason 
EMPS sanction begin date
EMPS sanction end date
Last 2 month of TIME panel coding
60 month extension reason 
Total TANF months
Total # of sanctions
Sanction %
Last 6 months of SANC coding 
Date closed 7th sanction
Date closed post 7th sanction 

This is ready, and being used at Hennepin County. Will add to project once freeze is lifted. Will send code to any county in the meantime who would like to run it locally.

**Comment by GayS** [comment]
hi @IlseFerris , we would love to get the code for this!  Please send it to me.   Greatly appreciate it!
Gay

**Comment by C-Love** [comment]
Will be added to the collaborative branch. Then can be tagged for post freeze.

**Comment by IlseFerris** [comment]
https://github.com/MN-Script-Team/DHS-MAXIS-Scripts/tree/scriptwriter_collaborative/bulk

**Comment by C-Love** [comment]
To be handled once conversion is over.
