### ISSUE TITLE
DAIL - CSES processing: should be able to tell if only one month is represented on the PIC

### ISSUE THREAD

**Issue by theVKC** [MN-Script-Team/DHS-MAXIS-Scripts#294]
Right now, if there's just the one month on the PIC (let's say the person is paid multiple times per month for the same ABPS, and the panel shows just one month worth instead of a 3 month average), it thinks it's out of range. It'd be nice if it _at least_ stopped and told you, or better yet, calculated the range based on that data. Sound reasonable?

I'll take this one since I'm working on moving it off of Excel anyway.

**Comment by theVKC** [comment]
Hey @courtrightd!

Would you be interested in building a new CSES DAIL Scrubber? I got about 1/3 of the way done and DHS keeps happening. There's lots of opportunity for improvement and also glory. The project name was "Project Brooklyn". I don't remember why I named it that, I think I was lazy.

**Comment by courtrightd** [comment]
I think you tagged me on this before and I ignored it.  ☺  Actually I would love to take this on, though I can’t make any timeline promises I will try to get it done soonish.  I’m only in it for the glory.

**Comment by IlseFerris** [comment]
I had a Hennepin county worker ask if we could have the DAIL scrubber deleted CS DAIL messages if the case is HC only.  I said that this is likely to not be kosher, but wanted to at least pose the question again.  Thanks!!

**Comment by theVKC** [comment]
Reassigned to @MelissaFox-Stearns! Good luck!

**Comment by theVKC** [comment]
@RobertFewins-Kalb: any ETA on when you could get time to work on this? If not, I might ask for you to pull request your work into a side-branch and I might take it over (in the interest of issue reduction). This month is a better month to do it for me than December or February.

**Comment by RobertFewins-Kalb** [comment]
I won't be able to dedicate time to this any time soon. I was hoping to knock it out before the end of the previous calendar year but it did not happen. I can submit a pull request with what I have -- although it's still a bit of a discordant mess -- and let you run with it from there.

**Comment by theVKC** [comment]
I'd appreciate that. I'll create a DAIL-CSES-WORK branch and I'll ask you to pull it there, and not master.

**Comment by theVKC** [comment]
If you can pull it here, I'd be thankful. https://github.com/MN-Script-Team/DHS-MAXIS-Scripts/tree/CSES-WORK
