### ISSUE TITLE
New Script - Action "Claim Referral Tracking" script

### ISSUE THREAD

**Issue by MiKaylaH22** [MN-Script-Team/DHS-MAXIS-Scripts#2941]
![image](https://user-images.githubusercontent.com/17990650/27647834-2f36c0de-5bf2-11e7-8ed0-863da575b0a3.png)

Financial worker receives information indicating there may be a potential claim on a federal SNAP or MFIP (cash or food) case. 
This functionality will be added to the following scripts: (but are not limited to) an “OVERPAYMENT POSSIBLE” DAIL message,  NEW HIRE message and/or verification "DOCS RCVD" as mentioned in issue #2933.
This is ready, and being used at Hennepin County. Will add to project once freeze is lifted. Will send code to any county in the meantime who would like to run it locally.

**Comment by GayS** [comment]
@MiKaylaH22 please send me the script so that we may run it locally.  

 gay.sikkink@co.stearns.mn.us
Thanks!
Gay

**Comment by C-Love** [comment]
Will be added to collaborative branch then tagged for post freeze.

**Comment by IlseFerris** [comment]
https://github.com/MN-Script-Team/DHS-MAXIS-Scripts/tree/scriptwriter_collaborative/actions
Added to collaborative branch :)

**Comment by C-Love** [comment]
To be handled once conversion is over.
