### ISSUE TITLE
New script: LTCP (long term care partnership) NOTES script needed

### ISSUE THREAD

**Issue by IlseFerris** [MN-Script-Team/DHS-MAXIS-Scripts#2947]
DHS has specific case notes for required action/information. LTCP is an area that scripts are necessary. See screen shots below for options needed for this NOTES script. 

LTC Partnership (LTCP) Information Request Template
![image](https://user-images.githubusercontent.com/10836829/27806473-62aceb7a-6000-11e7-9e79-dae10936e8c0.png)
LTCP HealthQuest Submission Template
![image](https://user-images.githubusercontent.com/10836829/27806443-3ff74d50-6000-11e7-904e-d07d15fa08af.png)
LTCP Protected Assets – Request Information Not Returned
![image](https://user-images.githubusercontent.com/10836829/27806537-b44bc406-6000-11e7-871f-60618c74c536.png)

LTCP Protected Assets – HealthQuest Response
![image](https://user-images.githubusercontent.com/10836829/27806456-4498b33a-6000-11e7-91d4-4ac788d0e6dd.png)
LTCP Protected Assets – Assets Protected
![image](https://user-images.githubusercontent.com/10836829/27806467-559a5e68-6000-11e7-9d88-5f340e9bc9cf.png)

**Comment by C-Love** [comment]
New scripts to be made. These should be created as issues in the new python repo when ready.

**Comment by C-Love** [comment]
To be handled once conversion is over.
