### ISSUE TITLE
Bug on ACTIONS - Paystubs Received

### ISSUE THREAD

**Issue by kaleykobber** [MN-Script-Team/DHS-MAXIS-Scripts#2956]
The script gives an error message if the user enters a pay date using the current date. The script is identifying the current date as a future date and requires the user to correct the date entered: "You cannot enter a paydate in the future. Please remove and try again." We often have clients coming into the lobby with a paystub they have received that day, so would need capability to enter a current date.

**Comment by IlseFerris** [comment]
We've also had a worker report this issue, and would like to see this functionality enhanced.

**Comment by RoberT-1000** [comment]
Sorry...not sure why I programmed it that way. I just had someone ask me about this too. This should just be greater-than instead of greater-than-or-equal-to...

![image](https://user-images.githubusercontent.com/22157633/29230163-59517814-7ea7-11e7-9b19-a17bbc2a3ca6.png)
