### ISSUE TITLE
Onesource

### ISSUE THREAD

**Issue by SarahSmythe** [MN-Script-Team/DHS-MAXIS-Scripts#2957]
Hello, 
The link to onesource has stopped working in our scripts. Is there an update that can be done?

**Comment by IlseFerris** [comment]
See #2682, you may need to update your power pad

**Comment by Farleight** [comment]
Does that mean yours works? Because mine doesn't, and to my knowledge, it is up to date... ish. I'm not even sure where those links are stored to check it though. It's trying to go to hcopub right now.

**Comment by Farleight** [comment]
Oh, there it is!

**Comment by SarahSmythe** [comment]
I can try that, I was pretty sure we updated more recently than #2682 and it only just stopped working the last month or so.  Farleight were you able to get yours to start working again?

**Comment by Farleight** [comment]
I actually have not tried yet. My earlier exclamation was simply regarding finding the area where the link was kept. That said, I tried the link directly from that source and IT worked, so I have to assume that an updated power-pad would do the same. I want to spend a little more quality time with my current power pad though before I unceremoniously boot it out.

**Comment by lisaholker** [comment]
This link is still not working, still trying to go to this address: http://hcopub.dhs.state.mn.us/onesourcestd/ 
Can someone way smarter than me update this? :)
Thanks!!

**Comment by Farleight** [comment]
Has anyone followed up with you on this yet, Lisa? Arguably the best way to update this is to update to the latest DHS approved PowerPad... you could also edit the current version you have locally, but I would advise against that. 

The Common Links, where the OneSource button is kept, to my knowledge is not really an updatable Script. It's just a button on the PowerPad with a direct link to the website. Ergo, it cannot be updated through the same methods as other scripts.

Anyone else can chime in if I'm way off base there. I was not involved in any of that design.

**Comment by C-Love** [comment]
You are correct @Farleight . This is not a script, just an action assigned to a button on the power pad. 

I do have an idea to make this a script, in which it would open the website AND input the username and password. Since everyone uses the same information, it *should* be pretty simple. I haven't looked into the site yet to see how difficult it would be. We have some local scripts that work with inputting information into websites locally.

**Comment by C-Love** [comment]
Closing this issue as the power pad has been updated. With the conversion, many of these housekeeping items will be evaluated.
