### ISSUE TITLE
New Script - BULK Good Cause List

### ISSUE THREAD

**Issue by courtrightd** [MN-Script-Team/DHS-MAXIS-Scripts#2963]
This is a new script that pulls a list of cases into excel with good cause for management by the county good cause committee.  The script selects cases that are open / pending on HC, Cash or CCAP that have an ABPS panel with good cause Granted or Pending.  The excel file includes program status, good cause status, case review date and GC review date.
This is built and in use in Saint Louis County, I am happy to share the code with any interested counties.

**Comment by GayS** [comment]
Hi David @courtrightd , please share with me at gay.sikkink@co.stearns.mn.us

Thank you!
Gay

**Comment by IlseFerris** [comment]
Please send to Hennepin as well. 
Thank you!

**Comment by courtrightd** [comment]
@IlseFerris and anyone else, I have placed the code here:
https://github.com/courtrightd/Custom-Scripts/blob/master/BULK%20-%20Good%20Cause%20List.vbs

**Comment by C-Love** [comment]
To be handled once conversion is over.
