### ISSUE TITLE
New script: ABAWD exemption

### ISSUE THREAD

**Issue by IlseFerris** [MN-Script-Team/DHS-MAXIS-Scripts#2965]
A new script is being created to support documenting ABAWD exemption reasons in associated with  bulletin 17-01-01. (incapacitated/child under 6).

Link to Bulletin: http://www.dhs.state.mn.us/main/idcplg?IdcService=GET_FILE&RevisionSelectionMethod=LatestReleased&Rendition=Primary&allowInterrupt=1&noSaveAs=1&dDocName=dhs-295612

This is in development at Hennepin County. Will add to project once freeze is lifted. Will send code to any county in the meantime who would like to run it locally.

**Comment by GayS** [comment]
Hi @IlseFerris we are interested in your code for this ABAWD exemption. I'm not seeing it in the scriptwriter collaborative branch can you send it to me please? (or point me to the location)
Thanks!
Gay

**Comment by C-Love** [comment]
@IlseFerris - maybe we could add this to the collaborative branch so it is available for conversion. Then we can work on it Post Freeze.

**Comment by IlseFerris** [comment]
https://github.com/MN-Script-Team/DHS-MAXIS-Scripts/tree/scriptwriter_collaborative/actions
Added to collaborative branch :)

**Comment by C-Love** [comment]
To be handled once conversion is over.
