### ISSUE TITLE
New script: UTILITIES - ABAWD COUNTED MONTHS

### ISSUE THREAD

**Issue by IlseFerris** [MN-Script-Team/DHS-MAXIS-Scripts#2980]
New script that will display all the markings on the ABAWD tracking record, and display all the issuances for programs that can affect the ABAWD status for the same period in an Excel worksheet for a single member. 

Pulling into the collaborative branch. If anyone wants instructions, I can send those out to you.

**Comment by C-Love** [comment]
I saw this thing in action and it is incredible. Thank you @IlseFerris

**Comment by theVKC** [comment]
OK MAXIS folks: thinking we should make a project board to track collaborative-scripts-that-haven't-been-approved-by-DHS. We can track these scripts there and make your issue list smaller and more efficient.

We have this in PRISM, and I'm imagining you could simply replace "complete" with "ready for DHS to evaluate", then close issues when the script is ready in the collaborative branch.

(See https://github.com/MN-Script-Team/DHS-PRISM-Scripts/projects/3 for our version of this)

**Comment by C-Love** [comment]
I vote yes to project board. Is this something we are able to manage ourselves? Or is this something you will need to move issues through the project on your super admin power side.

**Comment by IlseFerris** [comment]
I also vote yes. What's our next steps?

**Comment by theVKC** [comment]
I believe you all can edit it. I'll set one up and send you both a link to test.

**Comment by C-Love** [comment]
This is done and working. The code is on the collaborative branch. It is then available for any of us to work on when converting. 

However, if anyone @MN-Script-Team/maxis-scriptwriters wants it available, say something and we can get it pulled in.

**Comment by IlseFerris** [comment]
https://github.com/MN-Script-Team/DHS-MAXIS-Scripts/tree/scriptwriter_collaborative/utilities

This one is awesome. If you're working with ABAWD's this is the script to use :)

**Comment by C-Love** [comment]
To be handled once conversion is over.
