### ISSUE TITLE
Question: Note-ltc-cola-summary

### ISSUE THREAD

**Issue by ValAnderson** [MN-Script-Team/DHS-MAXIS-Scripts#2990]
Question from Anoka Management, are there changes that need to be made to the LTC Cola Notes script?  Is this on somebody's radar or is this something we can handle here?

**Comment by IlseFerris** [comment]
Hi Val! Did you see issue #2934?

**Comment by ValAnderson** [comment]
No, I didn’t see that one. I’m new to this so bear with me. I’m wondering if there are any budgeting items that need to be updated in that script. I don’t remember what that script entails.

**Comment by IlseFerris** [comment]
No worries :)
I haven't heard of any budgeting issues. Anyone else @MN-Script-Team/dhs-scriptwriters?

**Comment by IlseFerris** [comment]
@ValAnderson did you have any other information/issues reported? Otherwise we'll close it next Tuesday.

**Comment by ValAnderson** [comment]
Nope, go ahead and close it.

**Comment by C-Love** [comment]
handled on #2934
