### ISSUE TITLE
New HIRE DAILs and Scrubber

### ISSUE THREAD

**Issue by rmatychuk** [MN-Script-Team/DHS-MAXIS-Scripts#2991]
Please someone fix the new HIRE DAILs as they don't work with the scrubber. It takes so much longer to do HIREs with no scrubber.
Thanks!

**Comment by ValAnderson** [comment]
Report from user that the Income Type and Verification are missing when using the DAIL Scrubber for New Hire messages.

**Comment by IlseFerris** [comment]
It appears the verification codes columns have changed on the JOBS panel. From 6 to 5. I'll create another issue, and start mapping out which scripts are affected.

**Comment by C-Love** [comment]
There are 2 issues with New Hire
1. NDNH New hires have different order of information on DAIL - this is being handled under issue #2966 
2. JOBS Panel had a move some time ago and code needs updating - this is being handled under issue #2999
