### ISSUE TITLE
BUG: ACTIONS - PAYSTUBS RECEIVED

### ISSUE THREAD

**Issue by IlseFerris** [MN-Script-Team/DHS-MAXIS-Scripts#2992]
Code was added to support the change in coordinates effective 10/2016. Those changes supported MAXIS footer year of 2016 and 2017, but now are not supporting 2018. 

Users are getting stat errors, and incorrectly updated JOBS panels due to the script attempting to write the JOBS_verif_code at the incorrect coordinate. 

![image](https://user-images.githubusercontent.com/10836829/33740062-ed52f5be-db64-11e7-907e-6ccc2813fe4f.png)

Conditional code needs to be removed, and coordinates for JOBS-verif_code should be 6, 34.

**Comment by C-Love** [comment]
This is indicated in issue #2999 and has been resolved with pull #3000
