### ISSUE TITLE
Critical Bug - Appointment Letter (and others) cannot open SPEC/MEMO

### ISSUE THREAD

**Issue by courtrightd** [MN-Script-Team/DHS-MAXIS-Scripts#2995]
The coordinates for selecting memo recipients have moved from column 10 to column 12.  Script appears to function and enters a case note, but does not actually send a memo.

**Comment by C-Love** [comment]
Do you know when this changed?

**Comment by courtrightd** [comment]
I have confirmed that the script functioned yesterday, so it must have been installed overnight.

**Comment by C-Love** [comment]
I took a quick look and these are the scripts I found that are impacted.

ACTIONS - Transfer Case

BULK - Case Transfer
BULK - MEMO from List
BULK - REVS Scrubber

DAIL - Send NOMI

NOTES - Closed Programs
NOTES - Interview No Show
NOTES - MFIP to SNAP Transition

NOTICES - 12 Month Contact
NOTICES - Appointment Letter
NOTICES - Eligibility Notifier
NOTICES - GRH Overpayment
NOTICES - LTC Asset Transfer
NOTICES - Method B WCOM
NOTICES - MFIP Orientation
NOTICES - MNSure Memo
NOTICES - NOMI
NOTICES - Overdue Baby

Someone want to double check to make sure I didn't miss something. (Also maybe this should be a function. - start_a_blank_memo because the code should be the same here for all of these and there is SWKR and AREP handling. )

**Comment by Farleight** [comment]
I agree with the function idea. This seems to come up too often with Memo.

**Comment by C-Love** [comment]
I will make an issue in FuncLib

**Comment by C-Love** [comment]
It already is an issue (379) - not sure I can tag it across repos.

**Comment by IlseFerris** [comment]
I agree as well. Makes sense for a function. 
What a mess! I am also looking at the scripts to see if there's any other ones that we're missing.

**Comment by C-Love** [comment]
Should we just make the function and submit that first and then fix each of the scripts with the function? Or should we spot fix these first?

**Comment by IlseFerris** [comment]
If we can update the function and the scripts, that would be ideal.

**Comment by IlseFerris** [comment]
DAIL - FMED DEDUCTION is also not working.

**Comment by C-Love** [comment]
I've created the function and submitted a pull request to the FuncLib - it is going to be reviewed in a hour or so. I will start adding it to the scripts and creating commits for a pull request for the individual script files.

**Comment by C-Love** [comment]
- [ ] ACTIONS - Transfer Case
- [ ] BULK - Case Transfer
- [ ] BULK - MEMO from List
- [ ] BULK - REVS Scrubber
- [ ] DAIL - Send NOMI
- [ ] DAIL - FMED Deduction
- [ ] NOTES - Closed Programs
- [ ] NOTES - Interview No Show
- [ ] NOTES - MFIP to SNAP Transition
- [ ] NOTICES - 12 Month Contact
- [ ] NOTICES - Appointment Letter
- [ ] NOTICES - Eligibility Notifier
- [ ] NOTICES - GRH Overpayment
- [ ] NOTICES - LTC Asset Transfer
- [ ] NOTICES - Method B WCOM
- [ ] NOTICES - MFIP Orientation
- [ ] NOTICES - MNSure Memo
- [ ] NOTICES - NOMI
- [ ] NOTICES - Overdue Baby

**Comment by C-Love** [comment]
I am plugging away at these. I will check them off before I start working so anyone else can grab one or two if they want. I am committing to the MEMO_bug branch and just adding the start_a_ne_spec_memo function in place of all the stuffs. 

I will work on this first thing Tuesday.

**Comment by IlseFerris** [comment]
UTILITIES - COPY CASE NOTE ELSEWHERE also has MEMO option

**Comment by courtrightd** [comment]
I'm knocking out some of these today as well, I'll check them off and commit to the branch just as C-Love is.

**Comment by C-Love** [comment]
Has anyone looked at the WCOM functionality? It appears that maybe it changed BUT the change just removes the option for choosing other recipients that had been added a few months ago. Either way WCOM updates appear to be working - can anyone else confirm this?

**Comment by IlseFerris** [comment]
Confirmed, WCOM's are still working. 
It seems like the WCOM coding that was added 6 months ago has been reversed. Really strange.

**Comment by courtrightd** [comment]
I think mine are actually in the correct place now.

**Comment by theVKC** [comment]
Pulled in, had to adjust Changelog placement on yours, @courtrightd... it always goes at the top and not the bottom. :)

Please test each script and confirm they're working!!! :)

**Comment by C-Love** [comment]
I have tested all scripts except REVS Scrubber as it will not send MEMOs until the 16th of the month.

**Comment by theVKC** [comment]
Can I get any other testers? @IlseFerris?

**Comment by IlseFerris** [comment]
Spot tested about 1/2 of these. Looking good on this end.

**Comment by C-Love** [comment]
I have testers other than myself that have run all except REVS scrubber and the DAILs successfully. 

Anyone else have some testing data so we can confirm this and wrap it?

**Comment by theVKC** [comment]
Perhaps @courtrightd or @Farleight have a bit of info? I think we can slide on REVS and DAILs because they are harder to test for, but I'd like at least one other agency to have tried the rest of them, especially since I don't have the MAXIS access to run a complete test myself... :/

**Comment by IlseFerris** [comment]
DAIL scripts tested. Both DAIL - Send NOMI and DAIL -FMED deduction working as expected.

**Comment by Farleight** [comment]
I haven't had time to test a whole lot, but I can confirm that the fix is working for Bulk-Memo

**Comment by theVKC** [comment]
OK, I'm making a call: we'll pull it in. It's on me if something major breaks.

**Comment by C-Love** [comment]
This has been pulled in to Release and is now done.
