### ISSUE TITLE
Notices - Appointment Letter & Notices - NOMI not working

### ISSUE THREAD

**Issue by ramonalisa1** [MN-Script-Team/DHS-MAXIS-Scripts#2998]
I see you may be working on this issue, but just wanted to let you know that in Wabasha County the Appointment Letter & NOMI scripts are still not working.  The Script acts like it works, but when we go back and review, no appointment letter or NOMI is created.

**Comment by C-Love** [comment]
When did you last experience this problem? We were working on this issue but have resolved it for our users earlier today.

**Comment by ramonalisa1** [comment]
One worker reported it this afternoon, but I just did another test on a case and it appears to have been fixed.  Not sure what she did, but it works now.  ☺

[cid:image003.jpg@01D3857A.C2B12550]
Lisa M.
Financial Assistance Supervisor

P
Please consider the environment before printing this email.

CAUTION:  This e-mail and attached documents, if any, may contain information that is protected by state or federal law.  E-Mail containing private or protected information should not be sent over a public (non-secure) Internet unless it is encrypted pursuant to DHS standards.  This e-mail should be forwarded only on a strictly need-to-know basis. If you are not the intended recipient, please:  (1) notify the sender immediately; (2) do not forward the message; (3) do not print this message; and (4) erase the message from your system.

USDA is an equal opportunity provider and employer.

**Comment by C-Love** [comment]
This issue was reported and will be handled in Issue #2995
