### ISSUE TITLE
SCRIPT ERROR

### ISSUE THREAD

**Issue by rmatychuk** [MN-Script-Team/DHS-MAXIS-Scripts#3004]
All of Scott County has lost the script power pad and is getting this error:
![script error](https://user-images.githubusercontent.com/34277173/35222992-ca741de8-ff77-11e7-93fe-724ccbb987d1.png)

**Comment by Farleight** [comment]
Your script files are probably not saved on the C Drive. It seems to me that your BlueZone settings reset to the default. Check your Script Proprerties (on the menu bar). At the bottom of the box that pops up, there should be a Script Directory: showing a file path. Make sure that path is set to wherever your county stores Scripts. This is different for every county, so I cannot give you an exact path.

Then from the menu bar again, select View Properties, click on the Power Pads tab, and make sure the Power Pads Directory is set to the same path. If you have the correct path, you should see the DHS Supported Pad in either the Active or Available Pads box on the page. Make sure you add it to Active if it is not already there.

If that is not the problem and you already knew all this stuff, ignore me and wait for other advice from someone who knows what they're talking about. :-)

**Comment by rmatychuk** [comment]
Hi,
My script files are in the C drive. I went to the Power Pads Directory and changed it to match the same path as you have said, but it did not offer any Available Power Pads.
Is there anything else you suggest?
We are all struggling here with no scripts.

**Comment by C-Love** [comment]
This has happened in the past when connection to the network drive is lost. Most counties have their script redirect files and global variables on a network drive so that the same scripts are accessed by all users. Since all users have reset to the bluezone default - my guess is that somehow the connection was lost. 

Have you checked your drives to be sure all of the ones you typically have are still available?

**Comment by theVKC** [comment]
Closing this issue, as it is not related to the script project itself, but is rather an issue of IT at a local level having moved files around.
