### ISSUE TITLE
DAIL Scrubber income type and verif

### ISSUE THREAD

**Issue by ValAnderson** [MN-Script-Team/DHS-MAXIS-Scripts#3008]
End user reports that the DAIL Scrubber is not entering the type of income and N for verification for new hire messages.

**Comment by theVKC** [comment]
Anyone else seen this? @C-Love?

**Comment by C-Love** [comment]
I am pretty sure this is an issue with the error previously reported with the JOBS panel.
I can look closer - but I believe this is resolved in pull request #3000

**Comment by C-Love** [comment]
Yes, this is the same issue as #2999
