### ISSUE TITLE
New script: Eligibility Summary 

### ISSUE THREAD

**Issue by IlseFerris** [MN-Script-Team/DHS-MAXIS-Scripts#3012]
Wouldn't it be nice if instead of having to run NOTES - APPROVED PROGRAMS, DENIED PROGRAMS and CLOSED PROGRAMS (sometimes back-to-back), we had an eligibility summary script. 

Hennepin County proposes that these scripts should be all-in-one. Options to include in this script would be to case note changes that result in new eligibility determinations, added WCOM options and improved eligibility information handling. (See issue #2953). 

Thoughts? Additions?

Associated issues #2927, #2601, #2904, #2953. We are closing these issues as they will be built into the new script (in PY of course).

**Comment by C-Love** [comment]
Include functionality to address if approval was made with or without unverified shelter expenses and future action required for that approval. Discussed in issue #2911

**Comment by C-Love** [comment]
This will be handled with conversion
