### ISSUE TITLE
Bulk - Pull Data to Excel EOMC Issue

### ISSUE THREAD

**Issue by Farleight** [MN-Script-Team/DHS-MAXIS-Scripts#304]
The Excel equations for the percentage autoclosing calculations in the EOMC section of this script seem to include an unnecessary -1, causing the program to count the Header fields when it should not, rendering the calculation inaccurate. Seems like a fairly simple fix for someone who knows what they're doing (i.e., not me)

Example equation: =(COUNTIFS(D:D, "*FS*",E:E, "<>" & "") - 1)/(COUNTA(E:E) - 1)
should be: =(COUNTIFS(D:D, "*FS*",E:E, "<>" & "") )/(COUNTA(E:E) - 1)

Not sure if this was intentional for reasons above my computation abilites, but it makes the math errant.

**Comment by theVKC** [comment]
I will look into this, I had some changes I was going to make. I seem to remember the `-1` was set up to remove the header, but let me dig in a bit next week. Thanks for the report!

**Comment by Farleight** [comment]
From what I can surmise, I'd say the second -1(denominator) was set up to remove the header, since that portion is just looking for any entry and would otherwise count it. The first -1 (numerator) is looking for the specific language of "FS" or whatever the program may be, so the header is not counted by default, and adding the -1 only serves to nullify the -1 in the denominator. On the other hand, I may be way off base. But you'll sort it out! Thanks!
