### ISSUE TITLE
NOTES - APPROVED PROGS not case noting MFIP cash correctly

### ISSUE THREAD

**Issue by courtrightd** [MN-Script-Team/DHS-MAXIS-Scripts#308]
The script is truncating or incorrectly converting the cash portion of MFIP when pulling the amounts for you.  I.E. $250 cash gets case noted as $25.00.

**Comment by theVKC** [comment]
@RobertFewins-Kalb? Did you happen to address this in your current Pull Request?


Caution: This e-mail and attached documents, if any, may contain information that is protected by state or federal law. E-mail containing private or protected information should not be sent over a public (nonsecure) Internet unless it is encrypted pursuant to DHS standards. This e-mail should be forwarded only on a strictly need-to-know basis. If you are not the intended recipient, please: (1) notify the sender immediately, (2) do not forward the message, (3) do not print the message and (4) erase the message from your system.

**Comment by RobertFewins-Kalb** [comment]
I did indeed!

**Comment by courtrightd** [comment]
I thought that was the case –  I meant to cancel my issue, not close it.  Oops.
