### ISSUE TITLE
Need instructions for a few Anoka scripts

### ISSUE THREAD

**Issue by theVKC** [MN-Script-Team/DHS-MAXIS-Scripts#316]
I'm looking at you, @CDPotter and @RobertFewins-Kalb. :)

Here's what I think I need based on my initial scanning:

* ACTIONS - Copy panels to Word
* ACTIONS - Transfer case
* ACTIONS - Update worker signature
* BULK - Case note from Excel list
* DAIL - BNDX scrubber
* NAV - REPT search
* NOTES - Approved programs
* NOTES - LTC - COLA Summary 2015 (although technically I think I built that one way back in 2012).

If you can write up instructions and provide some screenshots (just the JPGs, don't embed them in the email or document), I can get them added to the script wiki. If you want to try your hand at editing script wiki yourself, go ahead.

Assigning this to Robert right now, because I know Charles is out on Tuesdays. :P

**Comment by CDPotter** [comment]
Can do, we have a lot of screenshots/instructions in our one note. Some need some more details though. We can take a crack at it!

**Comment by theVKC** [comment]
Just thought of this: need instructions for your new eDRS script too! @cdpotter, want to email me a blip for the wiki?

**Comment by theVKC** [comment]
We should also add the new Overpayment script to the list. :)

**Comment by CDPotter** [comment]
They are all updated on the Wiki. If someone could take a look at them and let me know if there's any broken links that would be great. 

https://www.dhssir.cty.dhs.state.mn.us/MAXIS/blzn/scriptwiki/Wiki%20Pages/Copy%20panels%20to%20Word.aspx

https://www.dhssir.cty.dhs.state.mn.us/MAXIS/blzn/scriptwiki/Wiki%20Pages/PA%20verif%20request.aspx

https://www.dhssir.cty.dhs.state.mn.us/MAXIS/blzn/scriptwiki/Wiki%20Pages/Update%20worker%20signature.aspx

https://www.dhssir.cty.dhs.state.mn.us/MAXIS/blzn/scriptwiki/Wiki%20Pages/CASE-NOTE%20from%20Excel%20list.aspx

https://www.dhssir.cty.dhs.state.mn.us/MAXIS/blzn/scriptwiki/Wiki%20Pages/REPT%20search.aspx

https://www.dhssir.cty.dhs.state.mn.us/MAXIS/blzn/scriptwiki/Wiki%20Pages/LTC%20-%20COLA%20summary%202015.aspx

https://www.dhssir.cty.dhs.state.mn.us/MAXIS/blzn/scriptwiki/Wiki%20Pages/Overpayment.aspx

https://www.dhssir.cty.dhs.state.mn.us/MAXIS/blzn/scriptwiki/Wiki%20Pages/Approved%20programs.aspx

**Comment by theVKC** [comment]
No broken links! Looks really good, @CDPotter!! Woohoo!
