### ISSUE TITLE
Need instructions for a few Wabasha scripts

### ISSUE THREAD

**Issue by theVKC** [MN-Script-Team/DHS-MAXIS-Scripts#317]
Basically, I need instructions provided for any scripts you've sent me. I'm guessing you came out with something when you emailed staff about your scripts. I just need a copy of it, along with screenshots if you can provide them. :)

Here's what I think I need:

* BULK - REPT PND1 list
* BULK - SWKR list generator
* NOTES - GRH - HRF

If you can write up instructions and provide some screenshots (just the JPGs, don't embed them in the email or document), I can get them added to the script wiki. If you want to try your hand at editing script wiki yourself, let me know and I'll grant you temporary "Wiki editor" access.

Let me know if this is do-able! Hoping to get it done this week.

**Comment by ramonalisa1** [comment]
I will try to do what I can this week, but husband just had surgery on his shoulder today so will be between work and the office as a caregiver.  If I can't get to it this week, could next week work?

**Comment by theVKC** [comment]
Of course! Whenever you can send it to me, let me know. There'll be a "coming soon" page until it's done. :) :)

**Comment by ramonalisa1** [comment]
Here is my first stab at writing the Wiki for the BULK- REPT PND1 script.  I was so disappointed in myself.  I tried to go to the Wiki page in SIR and write a new one.  I copied and pasted this into a new page, but I can’t get the .jpeg images to come over ,and I can’t see an import function for Wiki pages.  So, it is attached.  If you need me to change something, let me know.  Two more instructions coming!!

Lisa M.
Financial Assistance Supervisor

P
Please consider the environment before printing this email.

CAUTION:  This e-mail and attached documents, if any, may contain information that is protected by state or federal law.  E-Mail containing private or protected information should not be sent over a public (non-secure) Internet unless it is encrypted pursuant to DHS standards.  This e-mail should be forwarded only on a strictly need-to-know basis. If you are not the intended recipient, please:  (1) notify the sender immediately; (2) do not forward the message; (3) do not print this message; and (4) erase the message from your system.

Wabasha County and the USDA are equal opportunity providers and employers.
