### ISSUE TITLE
Need instructions for a few SLC scripts

### ISSUE THREAD

**Issue by theVKC** [MN-Script-Team/DHS-MAXIS-Scripts#318]
Basically, I need instructions provided for any scripts you've sent me. I'm guessing you came out with something when you emailed staff about your scripts. I just need a copy of it, along with screenshots if you can provide them. Assigning to @courtrightd since you did most of the Githubbing on these scripts. :)

Here's what I think I need:

* ACTIONS - PA verif request
* MEMOS - MFIP orientation
* And, the "AGENCY CUSTOMIZED" script which @lpshanley invented.

If you can write up instructions and provide some screenshots (just the JPGs, don't embed them in the email or document), I can get them added to the script wiki. If you want to try your hand at editing script wiki yourself, let me know and I'll grant you temporary "Wiki editor" access.

Let me know if this is do-able! Hoping to get it done this week.

**Comment by courtrightd** [comment]
I will get the PA verif and MFIP orientation done by Thursday, the other one I will leave to my esteemed colleague.

**Comment by lpshanley** [comment]
I'll try to get the write up for mine done soon!
