### ISSUE TITLE
Casenote scripts not utilizing page 4 of casenote.

### ISSUE THREAD

**Issue by tdahl21** [MN-Script-Team/DHS-MAXIS-Scripts#320]
We’ve been having some problems with scripts not using page 4 of a case-note.  In one instance, a worker was using the asset assessment script and it stopped case-noting after the 3rd page.  In another case, the worker was using a CAF script and the script stopped writing on the 3rd page of the casenote and then created a second casenote to finish.  Thanks, guys!

**Comment by RobertFewins-Kalb** [comment]
I'll take a look

**Comment by RobertFewins-Kalb** [comment]
I think I found the problem in the Functions Library, but it is excessively difficult to be sure. I think there's duplicate logic that causes the script to generate a 2nd case note when a line ends on row 17. I have removed the duplicate logic and initial testing looks good, but I'm not 100% certain.

**Comment by theVKC** [comment]
@RobertFewins-Kalb, when you get in tomorrow, can you update me on how this has gone in Anoka? I received a bug report or two on this today, and I'd love to get it pushed out statewide. Thanks!

**Comment by RobertFewins-Kalb** [comment]
We haven't received any complaints. But Theresa was out and we don't know any other workers that write novels for case notes :)

**Comment by theVKC** [comment]
OK, I'll merge your pull request and remove the Anoka specific logic. Go team!

**Comment by RobertFewins-Kalb** [comment]
![image](https://cloud.githubusercontent.com/assets/7842016/5760301/331aa15e-9c99-11e4-92eb-d7cf86a44c30.png)

**Comment by theVKC** [comment]
Fixed in funclib. Reverted Anoka-specific menu changes for testing. Closing issue. Woohoo!
