### ISSUE TITLE
STAT/AREP navigation script error message (January release)

### ISSUE THREAD

**Issue by ALJ10** [MN-Script-Team/DHS-MAXIS-Scripts#337]
Since installing the new version earlier this month I've been getting the following message while attempting to navigate to STAT/AREP: 
Script Playback Error
Unable to open script file
F:\CommServ\Files\Shared\Scripts\Scripts\Script Files\REDIRECT - NAV - STAT-AREP.vbs

I did a search on github to see if it was previously reported, but did not see anything. Anyone else having this issue?

**Comment by CDPotter** [comment]
Hm looks like the file didn't download during the install. It is missing from our Q drive as well. 

You could download a copy and throw it in the directory where scripts are stored in your agency if there is a demand for the script.

**Comment by theVKC** [comment]
Shoot. I believe I've fixed this now. A text file containing a list of file redirects never got updated. My bad. Go ahead and run the installer again, and it should work.
