### ISSUE TITLE
Idea: can you create a dynamic list of buttons with an array?

### ISSUE THREAD

**Issue by theVKC** [MN-Script-Team/DHS-MAXIS-Scripts#355]
I'm wondering if a dialog can use a for...next to build a variable amount of buttons. This could be used for the agency custom script, among many other uses. Something like if buttonpressed = array(3) then do something.

**Comment by lpshanley** [comment]
Yes and No. My agency custom script already uses this. Would you like me to pull the raw code out so it can be added elsewhere?

**Comment by lpshanley** [comment]
Add this to me ill do it!
