### ISSUE TITLE
Mnsure memo only reading first line of WCOM

### ISSUE THREAD

**Issue by CDPotter** [MN-Script-Team/DHS-MAXIS-Scripts#360]
Had a worker report an issue with the WCOM side of the Mnsure memo. She had a waiting WCOM but it was on 10, 13 line rather than 7, 13. Robert and I have build a WCOM finder/generator for the large variety of memos and WCOMS that need to go out with MA (Though some may be a bit out of date with the constantly fluctuating rules.) So we could either try to incorporate our code to have the current Mnsure memo search for the waiting WCOM or we could try to bring our WCOM/MEMO script to the state. Thoughts?

**Comment by theVKC** [comment]
I like your "large variety" option, but could we flatten it to integrate into the MEMOS main menu? If the MEMOS main menu can simply be expanded to include your scripts, that might simplify the administration (vs a menu calling a menu). I'm not sure how you constructed it though, so I'd be eager to learn more...

**Comment by CDPotter** [comment]
Robert will be throwing it up on his Github along with the Section 8 bulk memo-er.

**Comment by theVKC** [comment]
Closing for lack of interest.
