### ISSUE TITLE
Transfer case: can't transfer cases to counties 20 or 81

### ISSUE THREAD

**Issue by theVKC** [MN-Script-Team/DHS-MAXIS-Scripts#361]
Basically, they merged into county 74 (I believe). We should modify the script to not allow these two counties. There's now an inhibiting error on XFER, apparently.

**Comment by RobertFewins-Kalb** [comment]
I'm on this...I'll try to resolve what issues I can from home but doing 2 jobs at once has me running in circles while I'm in Anoka...

**Comment by theVKC** [comment]
Been there, my friend. Good luck!

**Comment by RobertFewins-Kalb** [comment]
This has been resolved.
