### ISSUE TITLE
Find a way to block the "@" symbol in case noting functions

### ISSUE THREAD

**Issue by theVKC** [MN-Script-Team/DHS-MAXIS-Scripts#363]
It isn't really a bug, as people shouldn't do it. But people think it's a bug, so let's brainstorm.

**Comment by lpshanley** [comment]
What do you mean by block the @ symbol? Is it causing errors or do people just not like it?

-Luke
“Valar dohaeris”
#DecimateTheErrorRate

**Comment by theVKC** [comment]
The @ along with certain characters triggers an EMSendKey keystroke event. Apparently “@gmail.com” destroys case notes.


Caution: This e-mail and attached documents, if any, may contain information that is protected by state or federal law. E-mail containing private or protected information should not be sent over a public (nonsecure) Internet unless it is encrypted pursuant to DHS standards. This e-mail should be forwarded only on a strictly need-to-know basis. If you are not the intended recipient, please: (1) notify the sender immediately, (2) do not forward the message, (3) do not print the message and (4) erase the message from your system.

**Comment by lpshanley** [comment]
Prior to sending it to the console save it as a string and use replace to the @ symbol with chr(64). This should solve the problem.

-Luke
“Valar dohaeris”
#DecimateTheErrorRate

**Comment by theVKC** [comment]
That’s what I was thinking. I just need someone to do it. :)


Caution: This e-mail and attached documents, if any, may contain information that is protected by state or federal law. E-mail containing private or protected information should not be sent over a public (nonsecure) Internet unless it is encrypted pursuant to DHS standards. This e-mail should be forwarded only on a strictly need-to-know basis. If you are not the intended recipient, please: (1) notify the sender immediately, (2) do not forward the message, (3) do not print the message and (4) erase the message from your system.

**Comment by lpshanley** [comment]
It doesn’t actually allow it... ill look at it over lunch

-Luke
“Valar dohaeris”
#DecimateTheErrorRate

**Comment by theVKC** [comment]
Awesome. Let me know how it turns out! I'd accept replacing the @ symbol with the word "at" if needed.

**Comment by lpshanley** [comment]
I’ll write a function to clean the strings so we can use it over and over... any other chars we need to clean?


-Luke
“Valar dohaeris”
#DecimateTheErrorRate

**Comment by theVKC** [comment]
That’s all I can think of for now.


Caution: This e-mail and attached documents, if any, may contain information that is protected by state or federal law. E-mail containing private or protected information should not be sent over a public (nonsecure) Internet unless it is encrypted pursuant to DHS standards. This e-mail should be forwarded only on a strictly need-to-know basis. If you are not the intended recipient, please: (1) notify the sender immediately, (2) do not forward the message, (3) do not print the message and (4) erase the message from your system.

**Comment by lpshanley** [comment]
If I can I will make it into an array so it will be super easy to add to in the future. This way someone can just use

case_note_string = magic_escape_string(case_note_string)

EMSendKey(case_note_string)

☺ will that be ok?

-Luke
“Valar dohaeris”
#DecimateTheErrorRate

**Comment by theVKC** [comment]
Should work, although I want to incorporate this into the add_variables_to_case_note functions, so don’t make it too complex just yet. :P


Caution: This e-mail and attached documents, if any, may contain information that is protected by state or federal law. E-mail containing private or protected information should not be sent over a public (nonsecure) Internet unless it is encrypted pursuant to DHS standards. This e-mail should be forwarded only on a strictly need-to-know basis. If you are not the intended recipient, please: (1) notify the sender immediately, (2) do not forward the message, (3) do not print the message and (4) erase the message from your system.

**Comment by lpshanley** [comment]
[cid:image001.jpg@01D03AF0.917A0740]

-Luke
“Valar dohaeris”
#DecimateTheErrorRate

**Comment by lpshanley** [comment]
I have like 15 Case note scripts left to add this to then ill give it a push on over to you. ☺ should be done today

-Luke
“Valar dohaeris”
#DecimateTheErrorRate

**Comment by lpshanley** [comment]
Should be good to merge at this point. Let me know if you have any issues!

**Comment by lpshanley** [comment]
This is now its own commit by the by
