### ISSUE TITLE
Inac scrubber 4 mo reinstate

### ISSUE THREAD

**Issue by CDPotter** [MN-Script-Team/DHS-MAXIS-Scripts#364]
So with this new 4 month reinstate for MAGI clients our supervisors here have asked us to redo the inac scrubber to avoid these cases so they can sit in the worker's case load for the 4 month reinstate period. 

We wanted to know what other agencies are doing or if anyone else was looking at solutions for this.

**Comment by theVKC** [comment]
Most agencies that I know of wouldn’t be going that route. Feedback is good, and I’ll consider it, but this could get me a lot of flack. If we wanted to go that route, we should make it a global variable setting which defaults to False. Personally, I’m not a fan (that’s a LONG time to let something sit, and there’s no policy that I know of saying it has to stay with the “original worker of record”, that’s an Anoka convention).


Caution: This e-mail and attached documents, if any, may contain information that is protected by state or federal law. E-mail containing private or protected information should not be sent over a public (nonsecure) Internet unless it is encrypted pursuant to DHS standards. This e-mail should be forwarded only on a strictly need-to-know basis. If you are not the intended recipient, please: (1) notify the sender immediately, (2) do not forward the message, (3) do not print the message and (4) erase the message from your system.

**Comment by RobertFewins-Kalb** [comment]
Then here's a question to the group:

Is there a definitive way to check that a case closed for no or incomplete review rather than being closed in the middle of a renewal period? Should there ALWAYS be a T for HC status in STAT/REVW?

**Comment by theVKC** [comment]
@CDPotter, since you brought this one out in here... would you mind asking on the discussion forum (and I'll bump it via email to all counties). I think we should get some opinions on this one before I decide to incorporate it, or close the issue. Make sense?

**Comment by CDPotter** [comment]
Sorry for the delay this got buried in my email. I added a discussion to the SIR forum.

**Comment by CDPotter** [comment]
Alright since we got 0 replies on the discussion forum, and Robert and I have been patching our version every month because of new errors it might be best to just close this one.

**Comment by theVKC** [comment]
Reopening issue. In an effort to bring this to more counties (and reduce "non-supported" script use in counties), I think we should build this in.

* A new global variable for MAGI_cases_closed_four_month_TIKL_no_XFER, which is set to false (I'm open to other names)
* INAC scrubber gets the new logic on a "IF variable = "" or variable = false than...else..." concept (that way it defaults to the old way)
* Installer gets the new logic as a checkbox, which will update global variables

I suppose either @CDPotter or @RobertFewins-Kalb will want to do this one. :)

**Comment by theVKC** [comment]
(I'll do the installer updates after this is finished)

**Comment by CDPotter** [comment]
On it, been testing this morning!
