### ISSUE TITLE
DISA autofill: break down DISA status by program

### ISSUE THREAD

**Issue by theVKC** [MN-Script-Team/DHS-MAXIS-Scripts#365]
Right now it only does HC. I'm thinking a similar look to the recent income changes. Any takers?

**Comment by CDPotter** [comment]
I'll get started on this one.

**Comment by CDPotter** [comment]
So it looks like I already did this. pull request 70 on func lib.

https://github.com/MN-Script-Team/BZS-FuncLib/pull/70
