### ISSUE TITLE
Mileage Reimbursement enhancements

### ISSUE THREAD

**Issue by theVKC** [MN-Script-Team/DHS-MAXIS-Scripts#377]
I've heard a few requests for enhancement of this script, so here they go:

1. Lodging?
2. Meals?
3. Parking?

Anyone want to take this on? @ramonalisa1, I believe this started as your baby. :) No pressure if you don't have time, we can see if anyone else wants to tackle it...

**Comment by ramonalisa1** [comment]
Boy, my schedule is getting filled up fast.  Preparing for an FSME review.  Can anyone else take this on?

Lisa M.
Financial Assistance Supervisor

P
Please consider the environment before printing this email.

CAUTION:  This e-mail and attached documents, if any, may contain information that is protected by state or federal law.  E-Mail containing private or protected information should not be sent over a public (non-secure) Internet unless it is encrypted pursuant to DHS standards.  This e-mail should be forwarded only on a strictly need-to-know basis. If you are not the intended recipient, please:  (1) notify the sender immediately; (2) do not forward the message; (3) do not print this message; and (4) erase the message from your system.

USDA is an equal opportunity providers and employer.

**Comment by theVKC** [comment]
Closed for lack of interest.
