### ISSUE TITLE
Income case noting: HC should pull from the future month, or not pull at all

### ISSUE THREAD

**Issue by theVKC** [MN-Script-Team/DHS-MAXIS-Scripts#380]
It has the potential to be error prone, being done the way it is now. This would necessitate a change in the autofill functions. Anyone game? @CDPotter or @RobertFewins-Kalb, we were just working on this not too long ago...

**Comment by CDPotter** [comment]
I can take a crack at this one.

**Comment by theVKC** [comment]
Done. And thank you. It is appreciated.

**Comment by theVKC** [comment]
I'm imagining "if footer_month <> CM+1 then <don't do it>", but more correct than that.

**Comment by CDPotter** [comment]
This was fixed with pull #18 on Funclib. This can be closed.

**Comment by theVKC** [comment]
Good deal!
