### ISSUE TITLE
FMED is not pulling into autofill correctly

### ISSUE THREAD

**Issue by theVKC** [MN-Script-Team/DHS-MAXIS-Scripts#381]
If there's an end date, apparently it's not pulling in, even if the end date is in the future. Someone should take a look at this.

**Comment by RobertFewins-Kalb** [comment]
I can take this as well

**Comment by theVKC** [comment]
#RockStar

**Comment by theVKC** [comment]
@RobertFewins-Kalb, status update?

**Comment by RobertFewins-Kalb** [comment]
@theVKC ... not sure. I'll put it on my list.
