### ISSUE TITLE
LTC-Spousal Allocation FIATer script error/issue

### ISSUE THREAD

**Issue by jasont35** [MN-Script-Team/DHS-MAXIS-Scripts#386]
One of our long term care workers used this script and noticed an error on the ELIG screen. On STAT/UNEA for MEMB 02 - page 2 of 2 the worker has the income type of 17 - Other Retirement.
On the Spousal Allocation screen for MEMB 01 in ELIG/HC for the month of 01/15, the Gross Unearned Income came across as income type 17 - FC Child Requesting FS. This does not match STAT/UNEA's income type 17 - Other Retirement. The income type on the ELIG/HC budget screen should be 15 - Other Retirement. For some reason the income types on STAT/UNEA are different than the ones on ELIG/HC.

**Comment by theVKC** [comment]
Well @jasont35, do you feel up to doing it? I can help guide you through questions, if you're interested in doing it yourself!

**Comment by IlseFerris** [comment]
I can take a look at this if @jasont35 isn't able to.

**Comment by jasont35** [comment]
Go ahead and take this one @IlseFerris I am not able to at this time.

**Comment by IlseFerris** [comment]
Sounds good. VKC, I'm a go!

**Comment by theVKC** [comment]
It's yours @IlseFerris! Good luck!

**Comment by IlseFerris** [comment]
This has been fixed

**Comment by theVKC** [comment]
Thanks @IlseFerris! When abouts did you pull this?

**Comment by IlseFerris** [comment]
Looks like about 22 days ago.  I think we just didn't close this.  Oooh, you could add this change to the May release notes (woot woot!)
