### ISSUE TITLE
MA-EPD clients eligible for Medicare Part B Reimbursement

### ISSUE THREAD

**Issue by RobertFewins-Kalb** [MN-Script-Team/DHS-MAXIS-Scripts#389]
Recently @ramonalisa1 requested a modification to a report script that can identify all MA-EPD clients that are eligible for Medicare Part B premium reimbursement. It has occurred to me that mayhaps the state could also benefit from a script that Anoka County is currently using. It's a BULK script that checks for Medicare Part B premium reimbursement eligibility for MA-EPD clients. The script file can be found here: https://github.com/RobertFewins-Kalb/Anoka-Specific-Scripts/blob/master/BETA%20-%20BULK%20-%20MEDI%20CEI.vbs

Before running the script...
Make sure that you have MMIS running and not timed out and MAXIS running in Production Mode and not timed out.

Here's what it does...
The script requests the user to input the MAXIS case number, MA-EPD member number, and the Medicare Part B premium amount (once all case numbers are enterered, there is a button on the dialog that autofills "01" for all members and "104.90" for all Part B premiums) for up to 15 cases. The dialog also requests a user signature (if only there were a script that generates and autofills that business...) and a reimbursement month.
The script checks ELIG/HC on all cases to determine if the client is open on MA-EPD and has income at-or-under 200% FPG.
The script then jumps to MMIS. On RELG, it checks to see if the client is open on MA-EPD. On RBYB, it checks to see that the client is not open on the Buy-In. On MMSC, it checks to see that the client is not open on SSI and does not have an active MSA/GRH span.
The script then jumps back to MAXIS. For each case that is active on MA-EPD with income at-or-under 200% FPG, that is not active on the Buy-In, and that does not have an active SSI or MSA/GRH span, the script case notes that the client is being reimbursed their Medicare Part B premium for the reimbursement month. The script then generates a report in Microsoft Word and writes in each case that fails one of the checks above along with a reason and a location for the failed check. 

Results:
In Anoka County, we have 3 financial workers that manage all of the county's Part B reimbursements (something like 250 - 270 cases). They reported that manually checking all of those cases in all of those locations in MAXIS and MMIS. case noting the results, and cleaning up errors, took them anywhere between 8 and 12 hours each (3 workers, each checking 80-90 cases). They have been using this script for 2 months now and report that it now takes them 10-15 minutes each.

Time Savings: Massive
Win: Achieved

**Comment by ramonalisa1** [comment]
I agree!!  We found three cases we were missing when we ran this script.  Better for the clients and better for the workers.  A win-win.



[cid:image002.jpg@01D042DC.027A4430]

P
Please consider the environment before printing this email.

CAUTION:  This e-mail and attached documents, if any, may contain information that is protected by state or federal law.  E-Mail containing private or protected information should not be sent over a public (non-secure) Internet unless it is encrypted pursuant to DHS standards.  This e-mail should be forwarded only on a strictly need-to-know basis. If you are not the intended recipient, please:  (1) notify the sender immediately; (2) do not forward the message; (3) do not print this message; and (4) erase the message from your system.

Wabasha County and the USDA are Equal Opportunity Providers and Employers.

**Comment by theVKC** [comment]
This might be a good opportunity for incorporating my issue #390 in. Basically, if we could figure out how long it takes to do a single case, we can estimate the time savings very accurately. Let's turn your prospective "Time Savings: Massive" into a measurable "Time Savings: Massive"...

**Comment by theVKC** [comment]
Oh, do you want to take the next steps @RobertFewins-Kalb?

**Comment by RobertFewins-Kalb** [comment]
Next week, I will get time a health care worker doing this process manually to determine time savings.

**Comment by theVKC** [comment]
```
loop_count = 0
Do
  loop_count = loop_count + 1
  MsgBox "Woot"
Loop until loop_count = 2
```

**Comment by RobertFewins-Kalb** [comment]
Have I mentioned that the manual time of this process is 56.87 seconds/case?

**Comment by theVKC** [comment]
Can you pull request this one @RobertFewins-Kalb?

**Comment by RobertFewins-Kalb** [comment]
This is the one that case notes Medicare Part B CEI. Are you looking for that one as well?

The one we had talked about at the last hackathon was the one that checks your entire case load for clients that are MA-EPD and eligible for Part B reimbursement. 

I can pull request both, if'n you like.
