### ISSUE TITLE
GA/RCA Fiater onto SNAP budget

### ISSUE THREAD

**Issue by theVKC** [MN-Script-Team/DHS-MAXIS-Scripts#393]
I have this cross listed as ACTIONS and DAIL scrubber, as I don't know which one makes the most sense, as I've never worked this particular issue from the DAIL (but apparently, DAIL messages are made for it).

Basically, a simple script which will:

1. Look up the GA/RCA grant.
2. Navigate to SNAP budget.
3. FIAT that income in there.
4. Notify the worker that they should now review the results and approve as appropriate (the script should NOT approve for you).

Any takers? I have solicited a case number or two via email, just to see if those DAIL messages are made. I don't remember them from my time as a worker, but I could be way wrong. We'll see!

**Comment by theVKC** [comment]
TEMP cite: TE02.10.23 "GA Program".

**Comment by LaLarson** [comment]
This is needed for DWP as well! Pick me!

**Comment by theVKC** [comment]
Hey hey @LaLarson, I believe I saw that you were mostly done with this script. Have you finished it by chance?

**Comment by LaLarson** [comment]
I was close! I haven’t finished it though! I’ll try to get on that! ☺

Laura Larson
IMU – Family Unit

Goodhue County HHS
426 West Avenue
Red Wing, MN 55066

Phone: 651-385-3200
Fax Numbers:

  *   Child Support Fax: 651-267-4880
  *   Income Maintenance Fax: 651-267-4879
  *   Social Services Fax: 651-267-4877

Email: laura.larson@co.goodhue.mn.us<mailto:laura.larson@co.goodhue.mn.us>



HHS Temporary Relocation Update

Effective Tuesday, February 17, 2015 Goodhue County HHS staff & services from the Citizen’s Building, 426 West Avenue, Red Wing, MN 55066 will be relocated to the old St. Joseph School, 469 – 12th Street, Red Wing, MN 55066.

The following divisions will be relocated - Social Services, Income Maintenance, Child Support and IT / HHS Finance.
The Public Health Division will remain at the Government Center & Colvill School locations.

This is a temporary relocation until the Citizen’s Building renovations / addition have been completed.  There is no change to phone numbers, mailing address or emails. Thank you.

Map: From Citizen’s Building to St. Joseph School<http://mapq.st/1D30asB>


NOTICE: This e-mail and any files transmitted with it are intended only for the use and viewing of the individual or entity to which they are addressed. If you are not the intended recipient, please immediately notify the sender of the transmission error and then promptly delete this message from your computer system. Please be advised that e-mail correspondence to and from Goodhue County may be public data subject to the Minnesota Data Practices Act and may be disclosed to third parties.

**Comment by IlseFerris** [comment]
@LaLarson, me again.  What's the status of this one too?

**Comment by theVKC** [comment]
So, something funny happened with this one, @LaLarson... we discovered (I believe @CDPotter found it) a case in which the GA income was already present on the SNAP budget. It was a training case as I recall, but it has my attention, because maybe this script isn't necessary anymore.

So, here's what I want to do:

1. @CDPotter: can you tell me if you can confirm this is true? That the GA benefit is now carried over?
2. @LaLarson: can you tell me (either via GitHub or via email) how much work you've done on this one?

Assuming @LaLarson hasn't built much more for it and @CDPotter confirms SNAP automatically gets the GA amount now, I'll close the issue.

**Comment by CDPotter** [comment]
Strangely enough I can’t seem to get it to happen outside of Krabappel… even using the case in krabappel and manually doing it I can’t seem to get it to work. Maybe it’s just a weird krabappel thing with the year change (which is resolved now by clearing out the fiat field.)

**Comment by theVKC** [comment]
OK, we'll leave it up for now. Weird...

**Comment by theVKC** [comment]
Marking this as help wanted. If nobody wants it by hackathon Monday, I'll close it.

**Comment by C-Love** [comment]
I am still working on this but won't have it ready for March release - can we move it to April?

**Comment by theVKC** [comment]
I've moved this to @KateiMartini's plate, per her request at training this week. @KateiMartini: it's on the list for the April release, but we can easily put it out there for the May release if you don't think it'll be ready by April 15 for testing. Just let me know!

**Comment by RobertFewins-Kalb** [comment]
@KateiMartini, if you are interested, we have a GA fiater in Krabappel. Check out lines 2279-2482. Unless you already have it done, in which case, great success!

**Comment by theVKC** [comment]
@KateiMartini do you have any update on this issue?

We described this as being a sort-of "hot potato". Well, I'm willing to close the issue and mark it as a sleeper issue if you don't think you'll be able to prioritize it soon. Then, if anyone wants to pick it back up we can.

Thoughts?

**Comment by KateiMartini** [comment]
Yes, I think putting it as a sleeper issue for now would be fine.  I wish I had the time to work on it cause I think it would be great, but at this time I don't have the time for it.
