### ISSUE TITLE
BULK script to check all of the SNAP + GA/RCA cases to see if the income is in there

### ISSUE THREAD

**Issue by theVKC** [MN-Script-Team/DHS-MAXIS-Scripts#394]
This is a follow-on to #393. We should make a script that'll check the entire county caseload for this, and return cases that don't have it. #PaymentAccuracy

**Comment by ramonalisa1** [comment]
Love this one!



[cid:image002.jpg@01D0448C.BDB94410]

P
Please consider the environment before printing this email.

CAUTION:  This e-mail and attached documents, if any, may contain information that is protected by state or federal law.  E-Mail containing private or protected information should not be sent over a public (non-secure) Internet unless it is encrypted pursuant to DHS standards.  This e-mail should be forwarded only on a strictly need-to-know basis. If you are not the intended recipient, please:  (1) notify the sender immediately; (2) do not forward the message; (3) do not print this message; and (4) erase the message from your system.

Wabasha County and the USDA are Equal Opportunity Providers and Employers.

**Comment by theVKC** [comment]
@RobertFewins-Kalb is working this one.
