### ISSUE TITLE
Script Idea -- Unapproved Results Scrubber

### ISSUE THREAD

**Issue by RobertFewins-Kalb** [MN-Script-Team/DHS-MAXIS-Scripts#395]
The idea is a BULK script that runs on your DAIL, goes through all eligibility results, checks the current results against the previous. approved results (using multi-dimensional arrays, y'all) to determine if anything needs to be approved on the case OR if the results are no different from the previous version and can be deleted.

#Becausecomputers, the script should get functionality that allows it to check STAT/ADDR for address change.

**Comment by theVKC** [comment]
How would you propose to check for address change? Or perhaps you’d rather show me?


Caution: This e-mail and attached documents, if any, may contain information that is protected by state or federal law. E-mail containing private or protected information should not be sent over a public (nonsecure) Internet unless it is encrypted pursuant to DHS standards. This e-mail should be forwarded only on a strictly need-to-know basis. If you are not the intended recipient, please: (1) notify the sender immediately, (2) do not forward the message, (3) do not print the message and (4) erase the message from your system.

**Comment by RobertFewins-Kalb** [comment]
I'm still working the logic out but something that uses the ADDR change date on STAT/ADDR and then CASE/ADHI...
But for now, it's #BecauseComputers

**Comment by theVKC** [comment]
Closing due to lack of interest/time.
