### ISSUE TITLE
Returned mail with forwarding address script

### ISSUE THREAD

**Issue by theVKC** [MN-Script-Team/DHS-MAXIS-Scripts#397]
You know the drill. Updates panel, case notes, TIKLs for 10-day return of proofs. Here's some citations for policy courtesy of the original poster in SIR:

Cash & SNAP – TE02.08.012
Healthcare- couldn’t find anything real definitive, HCPM 13.05, 13.20 

Who wants to take it/be the hero?

**Comment by theVKC** [comment]
Thanks for taking it on, @mldietz! Let me know when you either have it mapped out, or even better, if you feel up to building any of it! I can answer any questions you may have while building it, if you choose to attempt it. I'm sure @RobertFewins-Kalb and @CDPotter would love to help too. :)

**Comment by theVKC** [comment]
Closed due to lack of interest, and unfortunately the scriptwriter assigned does not have a lot of time to go over it right now.

**Comment by RobertFewins-Kalb** [comment]
Just spoke with @mldietz and it looks like she has a good plan in place. We can keep the issue closed, but she is working on modifying the existing returned mail script to adjust the outcome. Details to come...
