### ISSUE TITLE
DFLN notes enhancement to CAF scripts

### ISSUE THREAD

**Issue by courtrightd** [MN-Script-Team/DHS-MAXIS-Scripts#398]
The idea is a new field on CAF / RECERT note scripts to pull info from STAT/DFLN.  This would serve as a reminder to look at DFLN status to the worker (and check to see if there is sanction needed, current release on file for testing if that is county policy, etc.)  We have been seeing a high number of errors at recert / change reported with SNAP DFLN sanctions not being carried to new results.

**Comment by theVKC** [comment]
Just thinking it through, and I don’t have BlueZone up at the moment… is this for cash only?


Caution: This e-mail and attached documents, if any, may contain information that is protected by state or federal law. E-mail containing private or protected information should not be sent over a public (nonsecure) Internet unless it is encrypted pursuant to DHS standards. This e-mail should be forwarded only on a strictly need-to-know basis. If you are not the intended recipient, please: (1) notify the sender immediately, (2) do not forward the message, (3) do not print the message and (4) erase the message from your system.

**Comment by courtrightd** [comment]
No the issues we are seeing are with SNAP, but I can't come up with a good solution for SNAP drug felon sanctions since they are done in FIAT and maxis doesn't seem to pull anything for them.  My thought is a DFLN notes field that would populate with a conviction date off the DFLN panel and the worker could add any notes pertaining to all programs.  Other ideas would certainly be welcome.

**Comment by Farleight** [comment]
One could theoretorically create a script that pulls into Excel or even mass TIKLs for this. It could search for review dates and be run monthly for a bank or a full county. It wouldn't be perfect, as transferred cases could still escape the watchful eyes, and the added reminder on a Notes script could certainly help alleviate that. I don't know how many people (here) actually do their notes with scripts though, so it'd be good to have a second route for this if possible. This is not an official request, but a "thought" on this related thread. Feel free to attack its merit.

**Comment by theVKC** [comment]
Jeeze, I'm disappointed in myself for not realizing this was for SNAP. That panel is new to me and as a worker I didn't have to use it. @courtrightD, do you want to take it on?

**Comment by courtrightd** [comment]
Go ahead assign this to me, I'll take it on when I can.

**Comment by theVKC** [comment]
Done!

**Comment by theVKC** [comment]
Closing for lack of interest from scriptwriters. Will re-evaluate if requested from counties.
