### ISSUE TITLE
Asset Assessment Note Script

### ISSUE THREAD

**Issue by tdahl21** [MN-Script-Team/DHS-MAXIS-Scripts#401]
Hey All,

There seems to be an issue with the second page of the Marital Asset portion of the asset assessment script.  A coworker ran into an issue where the second page of the marital asset portion was not being written into the person note nor the Maxis casenote.   Thank you for checking into it!

**Comment by theVKC** [comment]
Hmmm. I don't know of any issues with it. Of course, we have a case note function issue right now, which is being tested with Anoka and Goodhue (other beta counties should get the fix in the next day or two).

Any chance I can ask you to ask your coworker to try it again, and if it happens again, email me a case number to look at? I can dig into it and see what we can uncover, possibly tomorrow.

**Comment by tdahl21** [comment]
Hey Veronica,

I'll send you the case # through SIR.

**Comment by IlseFerris** [comment]
I'm pretty sure that the AA case note does not copy more than one page.  I can take this one

**Comment by IlseFerris** [comment]
I can work on this tomorrow if that works for you

**Comment by theVKC** [comment]
Sounds great! :)
