### ISSUE TITLE
Burial Asset Script Bug 

### ISSUE THREAD

**Issue by tdahl21** [MN-Script-Team/DHS-MAXIS-Scripts#408]
Hey All,

We are running into an issue where the burial asset script will overwrite just the first page of the casenote.   The script will fill the first page, then rewrite over the top.  Then, it will start F8'ing for new pages.  So, we are only ending up with pages 2,3, and 4 in the casenote.

**Comment by theVKC** [comment]
This is already a known bug.


Caution: This e-mail and attached documents, if any, may contain information that is protected by state or federal law. E-mail containing private or protected information should not be sent over a public (nonsecure) Internet unless it is encrypted pursuant to DHS standards. This e-mail should be forwarded only on a strictly need-to-know basis. If you are not the intended recipient, please: (1) notify the sender immediately, (2) do not forward the message, (3) do not print the message and (4) erase the message from your system.
