### ISSUE TITLE
BULK script to pull raw DAILS into Excel for measuring DAIL status

### ISSUE THREAD

**Issue by theVKC** [MN-Script-Team/DHS-MAXIS-Scripts#422]
I should have thought of this. Submitted by X155569. Who wants it?

**Comment by RobertFewins-Kalb** [comment]
I can knock this out.

**Comment by RobertFewins-Kalb** [comment]
The script is about 95% finished. I just have a question about the format of the Excel file...

 The Excel spreadsheet is formatted thusly:
Column 1 has the case numbers.
Column 2 has the applicant name.
Column 3 has the DAIL type (PEPR, INFO, FS, HC, MSA, TIKL, etc).
Column 4 has the DAIL date (MM YY, or MM/DD/YY in the case of TIKLs).
Column 5 has the DAIL message.

The script only dumps information in excel_row for columns 1 and 2 when the script encounters a MAXIS case. The script dumps information into excel_row for columns 3, 4, and 5 with every DAIL.

**Comment by theVKC** [comment]
I think the case numbers and names should be in each message. It allows better sorting.

**Comment by RobertFewins-Kalb** [comment]
Will do

**Comment by theVKC** [comment]
So @RobertFewins-Kalb, you said this was done "somewhere", no? Can you pull request it?

**Comment by RobertFewins-Kalb** [comment]
I will test this and pull request. I haven't touched it for 56 days.
