### ISSUE TITLE
Need instructions for MFIP orientation MEMO script

### ISSUE THREAD

**Issue by theVKC** [MN-Script-Team/DHS-MAXIS-Scripts#429]
I believe @courtrightd built this one. Do you feel up to making these? Perhaps you did and I forgot to add to the Wiki? Or, does anyone else feel up to doing it?

**Comment by courtrightd** [comment]
That was my fault – I think I did PA verif and forgot this one.  I’ll knock it out ASAP.

**Comment by theVKC** [comment]
Nice work!
