### ISSUE TITLE
Add Guardianship Fees to Bulk Pull to Excel

### ISSUE THREAD

**Issue by ramonalisa1** [MN-Script-Team/DHS-MAXIS-Scripts#432]
I would like to modify the pull to Excel to include an Excel report for guardianship fees.  We have one for PDED Rep Payee so it should be  simple one.  Anyone working on this?

**Comment by theVKC** [comment]
Not that I know of. You want to go for it?


Caution: This e-mail and attached documents, if any, may contain information that is protected by state or federal law. E-mail containing private or protected information should not be sent over a public (nonsecure) Internet unless it is encrypted pursuant to DHS standards. This e-mail should be forwarded only on a strictly need-to-know basis. If you are not the intended recipient, please: (1) notify the sender immediately, (2) do not forward the message, (3) do not print the message and (4) erase the message from your system.

**Comment by ramonalisa1** [comment]
I will give it a try!

Lisa M.
Financial Assistance Supervisor

P
Please consider the environment before printing this email.

CAUTION:  This e-mail and attached documents, if any, may contain information that is protected by state or federal law.  E-Mail containing private or protected information should not be sent over a public (non-secure) Internet unless it is encrypted pursuant to DHS standards.  This e-mail should be forwarded only on a strictly need-to-know basis. If you are not the intended recipient, please:  (1) notify the sender immediately; (2) do not forward the message; (3) do not print this message; and (4) erase the message from your system.

USDA is an equal opportunity providers and employer.

**Comment by theVKC** [comment]
@CDPotter, @RobertFewins-Kalb, @ramonalisa1, @RoyStearns, @farleight, any inkling about if this is done, or if it can be done? I know @ramonalisa1 hasn't had a lot of time for scripts recently...

**Comment by CDPotter** [comment]
So this is across the BULk - REPT ACTV list through REVW list? I should be able to get that squared away today if nothing comes up.

**Comment by theVKC** [comment]
I believe the latter is to what we are referring. Do you think that's do-able?

**Comment by CDPotter** [comment]
That should be pretty doable. I'm finishing up some work for a report here at Anoka and I should be able to look at it this afternoon or Wednesday.

**Comment by RobertFewins-Kalb** [comment]
@CDPotter  I am working on a PDED script that will include this information

**Comment by CDPotter** [comment]
Ah well fantastic, take it away Mr Solo!

**Comment by theVKC** [comment]
Reassigned to @RobertFewins-Kalb. Status update would be welcome. :P

**Comment by RobertFewins-Kalb** [comment]
BULK - PDED includes this information.

**Comment by RobertFewins-Kalb** [comment]
Correction, BULK - PDED LIST GEN reports the following information...

![image](https://cloud.githubusercontent.com/assets/7842016/9851908/0fe5ff76-5ac1-11e5-8194-c55b47db9244.png)

**Comment by RobertFewins-Kalb** [comment]
If something's worth doing, it's worth over-doing :)

**Comment by RobertFewins-Kalb** [comment]
We can close this issue. The script is live.

**Comment by theVKC** [comment]
Thanks for catching it!
