### ISSUE TITLE
Agency Custom Button

### ISSUE THREAD

**Issue by ramonalisa1** [MN-Script-Team/DHS-MAXIS-Scripts#433]
Just an FYI. I needed to run the Med B report so ran the script through the MAXIS menu instead of the Power Pad Button.  Worked fine.  When I tried to use the button, got the error.  May help resolve the issue.

**Comment by theVKC** [comment]
Today, just now? We resolved that issue by regressing. Does your script not contain the new Master Functions Library block?


Caution: This e-mail and attached documents, if any, may contain information that is protected by state or federal law. E-mail containing private or protected information should not be sent over a public (nonsecure) Internet unless it is encrypted pursuant to DHS standards. This e-mail should be forwarded only on a strictly need-to-know basis. If you are not the intended recipient, please: (1) notify the sender immediately, (2) do not forward the message, (3) do not print the message and (4) erase the message from your system.

**Comment by ramonalisa1** [comment]
Oh wait.  I could have been using the saved one I had gotten from Anoka.  Sorry about that.

Lisa M.
Financial Assistance Supervisor

P
Please consider the environment before printing this email.

CAUTION:  This e-mail and attached documents, if any, may contain information that is protected by state or federal law.  E-Mail containing private or protected information should not be sent over a public (non-secure) Internet unless it is encrypted pursuant to DHS standards.  This e-mail should be forwarded only on a strictly need-to-know basis. If you are not the intended recipient, please:  (1) notify the sender immediately; (2) do not forward the message; (3) do not print this message; and (4) erase the message from your system.

USDA is an equal opportunity providers and employer.
