### ISSUE TITLE
Enhancement Request -- Updating NOTES - COMBINED AR

### ISSUE THREAD

**Issue by RobertFewins-Kalb** [MN-Script-Team/DHS-MAXIS-Scripts#434]
A request has been made to include the following fields to the Combined AR case noter...
(1) Include a field to case note Interview Date
(2) Include a field to case note SHEL/HEST information

**Comment by theVKC** [comment]
Do you want this one?

**Comment by RobertFewins-Kalb** [comment]
yes

**Comment by RobertFewins-Kalb** [comment]
This issue can be closed.
