### ISSUE TITLE
REVW/MONT closures: cash date may be wrong, re-evaluate

### ISSUE THREAD

**Issue by theVKC** [MN-Script-Team/DHS-MAXIS-Scripts#436]

**Comment by theVKC** [comment]
Someone sent me a bulletin citation #14-69-05, IV - Program Uniformity Section B., 30-day reinstatements.

Anyone feel up to taking this?

**Comment by RobertFewins-Kalb** [comment]
I'll take a looky-loo.

**Comment by theVKC** [comment]
As I said elsewhere: killing. it. Assigned.

**Comment by RobertFewins-Kalb** [comment]
The policy appears to give a reinstatement period to GA, MSA, MFIP, DWP, and GRH, but not to RCA.

**Comment by RobertFewins-Kalb** [comment]
Question...
Policy allows for a 30-day reinstatement period. How literal is that 30-day period? Combined Manual gives a 30-day period as well for SNAP (From CM009.06.03, "If the unit takes the required action within 30 days after the end of the certification period, reopen the case and PRORATE benefits from the date the unit took the required action.", Source: http://www.dhs.state.mn.us/main/idcplg?IdcService=GET_DYNAMIC_CONVERSION&RevisionSelectionMethod=LatestReleased&dDocName=cm_00090603#).

Is the 1 calendar month a convention or is it actual policy? (I don't mean to stir up a hornet's nest, but...)

**Comment by ramonalisa1** [comment]
Here is a PI I found.  Hope this helps..
Completed

Submitted By:

Nedra Van Dam from Rice County
Phone: 507-332-6203 - Fax: 507-332-6247

Answered By:

Lea Glad

Approver:

Becky Payzant

Rush:

No

Attachment Sent:

No

Attachment Received:

--

Late?:

No

Extra Time Email Sent?:

Yes, on 1/29/2015 at 2:56 PM

Program Name:

MFIP

Manual Reference:

09.06

Question:

We have questions on the 30-day reinstatement process for MFIP. It indicates all recertification requirements need to be met prior to the end of the specific recertification month.
What do we do with mailed in CAF's received in the final days of the recertification month when the clients have not either had their interviews or turned in their verifications?
We're assuming that they would not have "completed all recertification requirements" and that they would remain closed. Do we code them as an "I" if they come in? Does the original closing notice stand? What would we do with a CAF that was received in office 2/27 (due for 2/1) and agency could not reach client for a interview?

Tentative Answer:

thank you







Answer



Final Answer:

Do not reinstate the cash program as soon as the CAF is received. By returning the CAF the unit has not yet completed the recertification requirements. To complete the recertification process the unit must also provide all necessary verification requested prior to the end of the recertification month. Also, for the MFIP program, an interview must be held prior to the end of the recertification month.

REINstate the cash program only when the unit has completed ALL recertification requirements before the end of the recertification month.

If the unit returns the CAF but does not complete the other recertification requirement(s) before the end of the recertification month, do not issue an additional closing notice. The original closing notice issued to the unit for not completing the yearly recertification process remains in effect.

If the unit provides a CAF during the recertification month but does not complete the requirements by the end of the 30 day reinstatement period, pend the CAF as a new application and allow the unit 30 days to complete the application process. Using your example, the unit did not complete all recertification requirements the end of February; therefore, process the 2/27 CAF as a new application and prorate benefits from 2/27, the date of application.




Lisa M.
Financial Assistance Supervisor

P
Please consider the environment before printing this email.

CAUTION:  This e-mail and attached documents, if any, may contain information that is protected by state or federal law.  E-Mail containing private or protected information should not be sent over a public (non-secure) Internet unless it is encrypted pursuant to DHS standards.  This e-mail should be forwarded only on a strictly need-to-know basis. If you are not the intended recipient, please:  (1) notify the sender immediately; (2) do not forward the message; (3) do not print this message; and (4) erase the message from your system.

USDA is an equal opportunity providers and employer.

**Comment by theVKC** [comment]
Resolved with #454, among others. :)
