### ISSUE TITLE
Checkbox for sending verif requests to AREP

### ISSUE THREAD

**Issue by CDPotter** [MN-Script-Team/DHS-MAXIS-Scripts#445]
So I had a suggestion and wanted to get some feedback on it. Someone brought up that we should likely be case noting when we send verification requests to AREPs as well as clients. In my short brainstorming I thought of two solutions

1. Add a new checkbox for "Mailed verif request form to AREP"
2. Change verbiage for already existing verif request form boxes to be something like "Send verification request form to client and (if applicable AREP).

Personally I lean towards the first because it it a chance to remind workers they need to send a AREP forms if they've requested it. However it will add more checkboxes to scripts and possibly be considered to clutter things up/get ignored.  

Thoughts?

**Comment by theVKC** [comment]
Personally, I like option 1 just fine. An explicit checkbox will do a far better job of reminding (and documenting) this issue than a passive message. But that’s just my opinion…


Caution: This e-mail and attached documents, if any, may contain information that is protected by state or federal law. E-mail containing private or protected information should not be sent over a public (nonsecure) Internet unless it is encrypted pursuant to DHS standards. This e-mail should be forwarded only on a strictly need-to-know basis. If you are not the intended recipient, please: (1) notify the sender immediately, (2) do not forward the message, (3) do not print the message and (4) erase the message from your system.

**Comment by theVKC** [comment]
Do you want to do this, @CDPotter? It wouldn't be controversial at all from my end. If you do, let me know and I'll assign you.

**Comment by CDPotter** [comment]
Sure! I'll take a crack at it.

**Comment by theVKC** [comment]
Good luck!

**Comment by IlseFerris** [comment]
I think that's a great idea!  Espeically for workers that primarily communicate with the AREP's instead of the clients (your LTC/Wavier/GRH folks in particular).

**Comment by CDPotter** [comment]
So it's been a bit crazy here so this may be delayed a bit but I wanted to make sure we hit every script that may need this added check box. Currently Megan and I came up with CAF, CAR, client contact, CSR, Emergency,  GRH HRF, HCAPP, HC Renewal,  HRF, LTC 1503, LTC Renewal, Verifs requested.

Can anyone think of any others we might have missed?

**Comment by CDPotter** [comment]
Also, Veronica,  since this would be editing a lot of scripts would you like it submitted in separate pulls for each script of one big branch with check boxes for all.
