### ISSUE TITLE
Can we use a HC ER for a CSR?

### ISSUE THREAD

**Issue by RobertFewins-Kalb** [MN-Script-Team/DHS-MAXIS-Scripts#452]
There has been concern in Anoka County that we cannot use a HC ER for a CSR (ex. a client is open on SNAP and MA and turns in their HC ER but fail to turn in their CSR for SNAP). What is the current policy? This matters because we may or may not need to remove the checkbox in the HC Renewal case note script that the ER was used for a CSR.

--Glossing over the fact that the SNAP and HC renewal dates should have been aligned--

**Comment by theVKC** [comment]
I have a policy inquiry in to get this resolved. ETA is the end of the week.

**Comment by theVKC** [comment]
Well that took a while. But... decision is that we should remove the checkbox at least temporarily. @RobertFewins-Kalb, care to do the honors? We should replace the checkbox with text explaining that it can't be done.

**Comment by theVKC** [comment]
PQ reference for the script should read "Per PQ 15338, a HC ER cannot be used as a SNAP CSR."

**Comment by theVKC** [comment]
I'm taking this one. Too big of a deal not to do.
