### ISSUE TITLE
Burial Asset Casenote Issue

### ISSUE THREAD

**Issue by tdahl21** [MN-Script-Team/DHS-MAXIS-Scripts#455]
Hey Everyone,

A co-worker ran into an issue where she was running the burial asset casenote to note the breakdown of goods for a specific insurance funded burial agreement.  She left everything blank, except for what she checked off on screen 3 of the dialog box, the different components of the agreement and their costs and whether or not it was excluded.  It ended up casenoting the total of the asset being $0.00 and signing the note.  A dialog box did not pop up asking for any required information.  Thank you for looking into it!

Tim

**Comment by theVKC** [comment]
This is kind of hard to diagnose from the description. Is the case note still in MAXIS? If so, @tdahl21, can you email me the case number, and I'll check it out tonight (I have a site visit planned for central MN, so it'll be some time before I get to it).

**Comment by IlseFerris** [comment]
Tim, this sounds similar to the issue you're having today (am I correct?).  I ran this several times, with several different variable, and was successful every time.  You're right in that if you do not fill in the HH member, you should get a message box with an error.  Might be a dumb question, but are you using an old power pad?

**Comment by IlseFerris** [comment]
Boom, issue resolved.  OK to close Notorious VKC!

**Comment by tdahl21** [comment]
Thanks peeps!  You're too good!
