### ISSUE TITLE
HCAPP script: add option to HCAPP status dropdown for "denied"

### ISSUE THREAD

**Issue by theVKC** [MN-Script-Team/DHS-MAXIS-Scripts#461]
From Olmsted County... it really does make sense if you think about it. Any takers?

**Comment by devonne01** [comment]
Kelly and I will work on this issue right now.

**Comment by devonne01** [comment]
Kelly and I will try and take this one.

**Comment by devonne01** [comment]
Devonne will take this one

**Comment by theVKC** [comment]
Thanks @devonne01!
