### ISSUE TITLE
Transfer Penalty Case Note Template

### ISSUE THREAD

**Issue by RobertFewins-Kalb** [MN-Script-Team/DHS-MAXIS-Scripts#462]
We have received a request from an Anoka LTC Worker to build a Transfer Penalty case note template.

All of the information can be found here...
http://www.dhs.state.mn.us/main/idcplg?IdcService=GET_FILE&RevisionSelectionMethod=LatestReleased&Rendition=Primary&allowInterrupt=1&noSaveAs=1&dDocName=dhs16_150210

**Comment by RobertFewins-Kalb** [comment]
Shout out to @IlseFerris @RoyStearns , yo.

**Comment by theVKC** [comment]
Any takers?

**Comment by theVKC** [comment]
@IlseFerris has our back on this one.

**Comment by theVKC** [comment]
I believe #500 brought @IlseFerris's work into the fold. Closing issue! Woot woot!
