### ISSUE TITLE
NOTES - GRH HRF: Add Obligation Amount to case note

### ISSUE THREAD

**Issue by theVKC** [MN-Script-Team/DHS-MAXIS-Scripts#465]
Came from X143626. Any takers?

**Comment by CDPotter** [comment]
I could probably do that. I'm not super familiar with GRH but is it just a edit box for Obligation amount? Should I be pulling that from somewhere or just letting people fill it in themselves?

**Comment by theVKC** [comment]
I’m betting @ramonalisa1 or @IlseFerris may be able to shed some light on that. :)


Caution: This e-mail and attached documents, if any, may contain information that is protected by state or federal law. E-mail containing private or protected information should not be sent over a public (nonsecure) Internet unless it is encrypted pursuant to DHS standards. This e-mail should be forwarded only on a strictly need-to-know basis. If you are not the intended recipient, please: (1) notify the sender immediately, (2) do not forward the message, (3) do not print the message and (4) erase the message from your system.

**Comment by asunderman** [comment]
Can it be pulled from the GRH elig after approval?

**Comment by ramonalisa1** [comment]
If you go to ELIG/GRH on the GRSM panel, the Client Obligation is at 18, 032.  If you could do this, that would be great!  You can view case 100630 if you need an example.

Lisa M.
Financial Assistance Supervisor

P
Please consider the environment before printing this email.

CAUTION:  This e-mail and attached documents, if any, may contain information that is protected by state or federal law.  E-Mail containing private or protected information should not be sent over a public (non-secure) Internet unless it is encrypted pursuant to DHS standards.  This e-mail should be forwarded only on a strictly need-to-know basis. If you are not the intended recipient, please:  (1) notify the sender immediately; (2) do not forward the message; (3) do not print this message; and (4) erase the message from your system.

USDA is an equal opportunity providers and employer.

**Comment by CDPotter** [comment]
Fantastic! Thanks you!

**Comment by theVKC** [comment]
@ramonalisa1, I deleted your comment because it contained a case number. I need to be extra sensitive about case data in GitHub. Even though it was just the case number info, I still needed to remove it.

**Comment by theVKC** [comment]
@CDPotter, I just merged this via #467.
