### ISSUE TITLE
CAF enhancement: ID/USC field

### ISSUE THREAD

**Issue by IlseFerris** [MN-Script-Team/DHS-MAXIS-Scripts#466]
QI team from Hennepin Co. is requsting that this field "ID/USC verified?  What is on file to verify? " be added to CAF script.  Check box for ID/USC verified, script would autofill the verif on file if verif is anything besides OT.  If OT, worker must manually enter what was used to verify.  
Purpose would be to document ID veriification for SNAP reviews/audits.
It's my understanding that the CAF is/almost at capacity.  Any thoughts?

**Comment by theVKC** [comment]
The state's recommendation remains that a separate case note for CIT/ID info be added, and there's already a script for that. At this time, amending the CAF script for such a request would be too progammatically cumbersome to be undertaken.
