### ISSUE TITLE
New Script - PDED

### ISSUE THREAD

**Issue by LaLarson** [MN-Script-Team/DHS-MAXIS-Scripts#471]
Wondering if there is a way to modify an existing BULK script so that it will create a list of all cases that have a PDED panel from the work around last year?
 
We were thinking it could work similar to one of the existing list generator scripts.

**Comment by lpshanley** [comment]
What screen/Source are you going to gather the case numbers to search through?

-Lucas
“Valar dohaeris”
#DecimateTheErrorRate

**Comment by LaLarson** [comment]
I’m super new to all this stuff, so I’m sorry if I sound really dumb/unsure… But I’m thinking, probably, REPT/ACTV???

Laura Larson
IMU – Family Unit

Goodhue County HHS
426 West Avenue
Red Wing, MN 55066

Phone: 651-385-3200
Fax Numbers:

  *   Child Support Fax: 651-267-4880
  *   Income Maintenance Fax: 651-267-4879
  *   Social Services Fax: 651-267-4877

Email: laura.larson@co.goodhue.mn.us<mailto:laura.larson@co.goodhue.mn.us>



HHS Temporary Relocation Update

Effective Tuesday, February 17, 2015 Goodhue County HHS staff & services from the Citizen’s Building, 426 West Avenue, Red Wing, MN 55066 will be relocated to the old St. Joseph School, 469 – 12th Street, Red Wing, MN 55066.

The following divisions will be relocated - Social Services, Income Maintenance, Child Support and IT / HHS Finance.
The Public Health Division will remain at the Government Center & Colvill School locations.

This is a temporary relocation until the Citizen’s Building renovations / addition have been completed.  There is no change to phone numbers, mailing address or emails. Thank you.

Map: From Citizen’s Building to St. Joseph School<http://mapq.st/1D30asB>


NOTICE: This e-mail and any files transmitted with it are intended only for the use and viewing of the individual or entity to which they are addressed. If you are not the intended recipient, please immediately notify the sender of the transmission error and then promptly delete this message from your computer system. Please be advised that e-mail correspondence to and from Goodhue County may be public data subject to the Minnesota Data Practices Act and may be disclosed to third parties.

**Comment by CDPotter** [comment]
No need to apologize! We could modify current scripts that use rept/actv however that would miss any cases that had the PDED fix that are now currently inactive. Of course we could also modify it to search CLS or wherever closed scripts are held (though sifting through that data will take a LONG time per run.)

What are you looking to do with the data if you don't mind me asking?

**Comment by LaLarson** [comment]
We would go into the cases identified as having a PDED panel, (for most of them) remove all of the PDED panels, and approve correct HC budgets.

I think it wouldn’t be a huge deal if it didn’t look at the closed cases? Those people, for the most part, are reapplying via MNSure? Also, we could just make it a point to run it periodically to check for new ones that somehow became active again?

Laura Larson
IMU – Family Unit

Goodhue County HHS
426 West Avenue
Red Wing, MN 55066

Phone: 651-385-3200
Fax Numbers:

  *   Child Support Fax: 651-267-4880
  *   Income Maintenance Fax: 651-267-4879
  *   Social Services Fax: 651-267-4877

Email: laura.larson@co.goodhue.mn.us<mailto:laura.larson@co.goodhue.mn.us>



HHS Temporary Relocation Update

Effective Tuesday, February 17, 2015 Goodhue County HHS staff & services from the Citizen’s Building, 426 West Avenue, Red Wing, MN 55066 will be relocated to the old St. Joseph School, 469 – 12th Street, Red Wing, MN 55066.

The following divisions will be relocated - Social Services, Income Maintenance, Child Support and IT / HHS Finance.
The Public Health Division will remain at the Government Center & Colvill School locations.

This is a temporary relocation until the Citizen’s Building renovations / addition have been completed.  There is no change to phone numbers, mailing address or emails. Thank you.

Map: From Citizen’s Building to St. Joseph School<http://mapq.st/1D30asB>


NOTICE: This e-mail and any files transmitted with it are intended only for the use and viewing of the individual or entity to which they are addressed. If you are not the intended recipient, please immediately notify the sender of the transmission error and then promptly delete this message from your computer system. Please be advised that e-mail correspondence to and from Goodhue County may be public data subject to the Minnesota Data Practices Act and may be disclosed to third parties.

**Comment by CDPotter** [comment]
Makes sense to me! We could totally alter the rept/actv bulk script we have (we do it all the time here at Anoka) to create a spreadsheet with active PDED panels. 

Would you want it to gather any and all pded panel active cases or only the ones with other earned/unearned income portions completed?

**Comment by LaLarson** [comment]
Saweeeet!!!

I really think either way would be fine… But I lean towards the first thought? Just all of them? I’m pretty sure that pretty much all of the PDED panels should get cleaned up (removed).

Laura Larson
IMU – Family Unit

Goodhue County HHS
426 West Avenue
Red Wing, MN 55066

Phone: 651-385-3200
Fax Numbers:

  *   Child Support Fax: 651-267-4880
  *   Income Maintenance Fax: 651-267-4879
  *   Social Services Fax: 651-267-4877

Email: laura.larson@co.goodhue.mn.us<mailto:laura.larson@co.goodhue.mn.us>



HHS Temporary Relocation Update

Effective Tuesday, February 17, 2015 Goodhue County HHS staff & services from the Citizen’s Building, 426 West Avenue, Red Wing, MN 55066 will be relocated to the old St. Joseph School, 469 – 12th Street, Red Wing, MN 55066.

The following divisions will be relocated - Social Services, Income Maintenance, Child Support and IT / HHS Finance.
The Public Health Division will remain at the Government Center & Colvill School locations.

This is a temporary relocation until the Citizen’s Building renovations / addition have been completed.  There is no change to phone numbers, mailing address or emails. Thank you.

Map: From Citizen’s Building to St. Joseph School<http://mapq.st/1D30asB>


NOTICE: This e-mail and any files transmitted with it are intended only for the use and viewing of the individual or entity to which they are addressed. If you are not the intended recipient, please immediately notify the sender of the transmission error and then promptly delete this message from your computer system. Please be advised that e-mail correspondence to and from Goodhue County may be public data subject to the Minnesota Data Practices Act and may be disclosed to third parties.

**Comment by RobertFewins-Kalb** [comment]
This report generator already has two options to pull information from PDED (https://raw.githubusercontent.com/RobertFewins-Kalb/Anoka-Specific-Scripts/master/BULK%20-%20Pull%20Cases%20into%20Excel.vbs). It would be a simple modification to just have it check for a PDED panel instead of the information on the PDED panel.

**Comment by LaLarson** [comment]
I just tried it… So cool!!!

I’m thinking we would either need it to pull cases w/ PDED panels in general, or the ones that have “Other Unearned income Deduction” and/or  “Other Earned Income Deduction” entered on them. Whatever is easiest?

Also… Is there a way to get it to run on the bank caseload (a caseload other than my own/the person running it)??

Laura Larson
IMU – Family Unit

Goodhue County HHS
426 West Avenue
Red Wing, MN 55066

**Comment by RobertFewins-Kalb** [comment]
You know what...that script has a section of code that checks for certain Anoka users. The point of the user validation was to give supervisors, program coordinators, and script developers access to more reports than the rest of the floor. It's also a way of preventing an FAS running a report on anyone else's caseload.

Two options: (1) Modify the variable "user_id_for_validation" to make it relevant to Goodhue County, (2) remove the conditional logic around user_id_for_validation (lines 319 through 336) and make the script run Dialog "pull_cases_into_excel_dialog".

Oops.

**Comment by LaLarson** [comment]
I’m really really sorry… I just read that last part about ten times, and I feel like I’m so close to understanding what those two options are, but not close enough to actually discuss them. Any chance you could dumb those down a little? (Probably a really sad request… I know.) Or maybe just elaborate a little more on what the two options would actually do, and what would be easiest?

Thank you so much for your time in discussing this with me! ☺

Laura Larson
IMU – Family Unit

Goodhue County HHS
426 West Avenue
Red Wing, MN 55066

**Comment by RobertFewins-Kalb** [comment]
No problem! Here's a quick breakdown of the user_id_for_validation logic...

The short version of what that variable is is the user's network log-in ID. So what we have set up in the script is an access block for most workers. We have allowed select supervisors, program coordinators, and script developers to run all of the available reports AND to allow them to run the reports on users other than themselves.

Lines 319 through 336 creates the value for user_ID_for_validation and then determines if the user ID is one of the select users. Those users are "VKCARY", "RAKALB", "CDPOTTER", "MLDIETZ", "PHBROCKM" etc. If the script detects one of those users, it calls the dialog "pull_cases_into_excel_dialog" which has more reports available and gives the user the option to run the report on a select x number or the entire agency.

Option 1 (modifying user_id_for_validation for Goodhue users) would require you to change the user_id_for_validation from Anoka users to Goodhue users. If you keep that logic without modifying it, you will only have access to "gen_worker_dialog" which has limited functionality.

Option 2 (commenting-out lines 320-330 and lines 333-336) would allow you to run the script as a developer as it would give you access to the script's full functionality.

For your current uses, I would recommend going with option 2. If you are not going to go live to the floor with this script, there's no reason to modify the logic for Goodhue County. It would be a good exercise for you to better understand the user_id_for_validation logic as this is not the only script that has it and it would allow you to customize county-specific scripts for the future, but for current testing, I would recommend commenting-out lines 320-330 and 333-336 which would give the script no option but the call "pull_cases_into_excel_dialog".

**Comment by lpshanley** [comment]
The ONLY dumb questions are the ones that go unasked ☺.

Rob will need to correct me if in incorrect here but:


(1)   Modify the variable "user_id_for_validation" to make it relevant to Goodhue County
-Essentially this variable in the script is to check if the user running the script is a user that is “Authorized” to be running the script. You could replace all the users in the variable with users at your agency that would need access to be running this script. This way any users in the list can run it.


(2)    remove the conditional logic around user_id_for_validation (lines 319 through 336) and make the script run Dialog "pull_cases_into_excel_dialog".

-Essentially this would allow any users to run the script. Removing the conditional logic would remove the condition (ex. If USER_RUNNING_SCRIPT is in LIST_OF_USERS_AUTHORIZED_TO_RUN_SCRIPT then run script, if not, don’t run script). Removing that would essentially make the script just run when a user invokes (selects it to run) the script.

Does this make sense? Again Rob will need to correct me if I’m mistaken but this should point you in the right direction. If you would like help actually reading the script to find out what to change let us know and we can give you a hand ☺

-Lucas
“Valar dohaeris”
#DecimateTheErrorRate

**Comment by RobertFewins-Kalb** [comment]
There is no need for correction. That is all 100% accurate.

**Comment by theVKC** [comment]
You folks are amazing. All of you. 

@RobertFewins-Kalb, I think this should be an official script... We can add an array for supervisor_script_users to GlobVar or FuncLib and make it happen... Care to take it?

**Comment by RobertFewins-Kalb** [comment]
This sounds juicy. Absolutely!

**Comment by theVKC** [comment]
@RobertFewins-Kalb, did you do this????

**Comment by theVKC** [comment]
Resolved with #1050. Go @RobertFewins-Kalb!
