### ISSUE TITLE
NOTE - Documents Received

### ISSUE THREAD

**Issue by GayS** [MN-Script-Team/DHS-MAXIS-Scripts#472]
the documents received script isn’t putting in title.  For example:

This is how it is currently creating case note:

Docs rec'd: 
hra award letter             
* Document datestamp: 02/27/15      
* Notes: slight increase in subsidy 
* Actions 

This is how it should be creating case note (I believe):

Docs rec'd: hra award letter             
* Document datestamp: 02/27/15      
* Notes: slight increase in subsidy 
* Actions

**Comment by theVKC** [comment]
We actually fixed this already, and it'll be released after hackathon tomorrow. :)

**Comment by GayS** [comment]
Great – thanks; I didn’t see it on the list. ☺
