### ISSUE TITLE
Proposed modification to ACTIONS - PAYSTUBS RECEIVED

### ISSUE THREAD

**Issue by RobertFewins-Kalb** [MN-Script-Team/DHS-MAXIS-Scripts#496]
I have received a request for a modification to ACTIONS – PAYSTUBS RECEIVED. First, I will run through the issue, and then I will present a possible solution.

A worker admitted his mistake, saying that he entered the wrong household member on the opening dialog. However, he also said he then wasted a good amount of time entering pay stub information into the second dialog only to run into the problem that the household member he selected had just 1 job, so the script did not give him the MsgBox to determine which JOBS panel to update. The end result was that the script update pay information for the wrong household member and the worker had to clean up the error and redo his work.

I am, admittedly, more amenable to a script modification because he started by admitting his mistake. I’m not saying I require that level of humility, but I am appreciative he said he knew he had erred and had brought up the enhancement request as a way of preventing other workers from duplicating his error. It should be noted that this worker is one of our Beta users. He is very thorough and is very vocal and thorough about possible bugs. @CDPotter , I think you know who I’m talking about.

This enhancement request got me thinking about the structure of the script and possible ways it could be amended to reduce the chance of a worker error. As I said, this is a user error coming from someone that I consider one of our better workers.

What I have in mind as a modification is a DO LOOP around DIALOG paystubs_received_case_number_dialog. After the worker enters information into the case number dialog (the dialog that also accepts the household member), the script would go to JOBS for that household member and create a the MsgBoxes to prompt the worker to select the job to be updated. Here, if the household member selected has no JOBS panel, we can still stop the script and instruct the worker to update MAXIS with a JOBS panel and then re-run the script to update pay information, or we can bring the script back to the dialog to give the worker a chance to change the household member.

Alternatively, if the household member has JOBS panel(s), the script would then present MsgBoxes for each JOBS panel that person has, and if the script gets through all the JOBS without one being selected, a MsgBox would inform the worker they have said “no” to all possible jobs for that household member and that they either need to enter a different household member or stop the script and create a new JOBS panel. From there, the worker could cancel the script to create the new JOBS panel or go back to the first dialog to correct the error. (I’m thinking MsgBox “You have determined that none of the JOBS for this household member are correct. Press OK to return to the previous screen and select a different household member or press Cancel to stop the script.”, vbOKCancel.)

@theVKC , this could be a chance to test your idea of changing the tab order for whatever field is invalid. The script could dynamically change the tab order to make the household member editbox first in the tab order and the case number editbox second. It wouldn’t change the location of the editboxes, obviously, but it would run on the assumption that the worker has the correct case number but incorrect household member.

A benefit to the workers of this restructure is that the second dialog (paystubs_received_dialog) can be very time intensive. If the worker has a complicated pay situation or is writing a good deal of information in “Explanation,” it would be good that this time is not wasted and a simple error is mitigated early to protect time savings.

**Comment by theVKC** [comment]
Why am I thinking it does exactly this? It asks which job is which and you have to say "yes, this is the job" if there are multiple jobs?

**Comment by RobertFewins-Kalb** [comment]
The idea would be that it asks BEFORE the financial workers spends the time filling in the second dialog.

**Comment by RobertFewins-Kalb** [comment]
I'm going to close this. I have a restructured PAYSTUBS RECEIVED on my compador 64. This issue is going to be resolved with a pull request.
