### ISSUE TITLE
Merge client contact with call center version

### ISSUE THREAD

**Issue by theVKC** [MN-Script-Team/DHS-MAXIS-Scripts#497]
Perhaps as simple as "are you part of a call center?" and it starts the more focused dialog... In any case, it'd be better to have just one version to support! Any takers?

**Comment by GayS** [comment]
I can give this a try -

**Comment by GayS** [comment]
I have this mostly completed.

**Comment by theVKC** [comment]
Go Gay!

**Comment by GayS** [comment]
I just submitted a pull request for this one!!
