### ISSUE TITLE
"Documents received" button merge?

### ISSUE THREAD

**Issue by theVKC** [MN-Script-Team/DHS-MAXIS-Scripts#498]
We need to pick a "project name" for this, and then set up a meeting to figure out what we want to do about the inevitable "______ document received" glut with new scriptwriters contributing info about specific docs (info that counties and DHS both want to case note). Basically, I don't want to create too many buttons.

My considerations off the top of my head:

* Do we spin off "verifs received" documents into a separate category?
* Just a new Power Pad button/main menu script? Or a new NOTES script type which attempts to consolidate the many scripts into one?
* If we consolidate, how do we do it? Logic?
* Do we enter the many documents into one case note? Or several?

@RobertFewins-Kalb and @IlseFerris, I've spoken with both of you about this today. Figured I'd tag you in case you're interested in continuing the convo via GitHub.

**Comment by IlseFerris** [comment]
Consolidating would most likely be the best way to save what I will call “button fatigue”.  Too many buttons could make less time savings if they are having to spend more time searching for them.  Plus the options within the buttons IE:  either of the ‘NOTES’ buttons , are getting heavy with options.

It’s a great problem to have with so many new scripts, but I am anticipating workers less enthusiastic about more buttons.

What I’m thinking is that the case number is entered, and the choice of document is then presented through drop down.  Once the worker chooses an option, the script would then load up for them.  “Other” documents that we don’t have a specific script can just use the current “documents rec’d” script.  V, you and I went over that a bit yesterday, and after thinking about it, I think it’s the way to go.

Have a great weekend everyone!

**Comment by CDPotter** [comment]
@RobertFewins-Kalb and I had a similar set up for this with our HC WCOM menu. You would click the WCOM button then check the type of WCOM you wanted and the specific WCOM script would load after that. Of course we have had issues with our ability to chainload scripts after moving to github so it would possibly all have to be part of one script or it's own button.

**Comment by theVKC** [comment]
This needs to get done today for the release. We've hit that point: too many buttons, the notes script menus are no longer viable to update.
