### ISSUE TITLE
CRF case-note Script Bug - No outcome

### ISSUE THREAD

**Issue by tdahl21** [MN-Script-Team/DHS-MAXIS-Scripts#504]
Hey Everyone,

We tried to run the new CRF script, but we are running into an error that says that the script does not have an outcome.

**Comment by RobertFewins-Kalb** [comment]
There appears to be an issue with how the script is handling case_number

**Comment by theVKC** [comment]
On it.

**Comment by theVKC** [comment]
I believe this should be resolved with Pull Request #507.
