### ISSUE TITLE
LTC/GRH list gen - cutting off last few names on the list

### ISSUE THREAD

**Issue by theVKC** [MN-Script-Team/DHS-MAXIS-Scripts#515]
That's the rumor. I have specific worker numbers. @IlseFerris has offered to take this on.

**Comment by IlseFerris** [comment]
I can work on this tomorrow if that works for you

**Comment by theVKC** [comment]
Again, sounds great! :)

**Comment by theVKC** [comment]
@RobertFewins-Kalb actually found a fix for this and is pulling it.
