### ISSUE TITLE
REIN/REAPP for CASH/SNAP

### ISSUE THREAD

**Issue by RobertFewins-Kalb** [MN-Script-Team/DHS-MAXIS-Scripts#517]
I recently put something on the SIR DIscussion board regarding automating a TIKL for incomplete CASH/SNAP reinstates. Figured I would put it on here too. The basic idea is automating a TIKL if the following conditions are met:

(1) CAF_type = "Recertification"
(2) DatePart("M", CAF_datestamp) = recert_month (may need to define recert_month)
(3) CAF_status <> "Approved"
(4) CASH_check = checked OR SNAP_check = checked

**Comment by theVKC** [comment]
Is this a new script? Enhancement? Huh?

**Comment by RobertFewins-Kalb** [comment]
Enhancement request. sorry...

Sent from my iPhone

On Mar 26, 2015, at 2:31 PM, Veronica Kahl Cary <notifications@github.com<mailto:notifications@github.com>> wrote:


Is this a new script? Enhancement? Huh?

-
Reply to this email directly or view it on GitHub<https://github.com/MN-Script-Team/DHS-MAXIS-Scripts/issues/517#issuecomment-86683971>.



Click here<https://www.mailcontrol.com/sr/60D3Kw+PEgzGX2PQPOmvUkaRNh6DuTIi6oBAIcunvN+X3gAQKX15UXHWyUefa3KGnEhnStyL1WLNfN+NdwfdFw==> to report this email as spam.


NOTICE: Unless restricted by law, email correspondence to and from Anoka County government offices may be public data subject to the Minnesota Data Practices Act and/or may be disclosed to third parties.

**Comment by theVKC** [comment]
Can you explain this idea in plain language for me to share with folks at DHS?

**Comment by RobertFewins-Kalb** [comment]
Yes...

When a client submits a CAF for late CASH recertification (as in, in the recertification month) and fails to complete the recertification, the CAF needs to be treated as a new application. Logic can be added to the CAF script (the worker does not have the option of turning it off) to TIKL to the first of the next month (so a CAF received April 9 for a 04/15 recertification and the client fails to complete the recertification by 04/30/2015 the script will automatically TIKL to 05/01/2015) with verbiage such as "IF the client has not completed the CASH/SNAP reinstatement, APPL the CAF for "CAF_datestamp" and TIKL to (30 days from CAF_datestamp) to take appropriate action.

The following conditions have to be met for the script to TIKL...
*  CAF_type = "Recertification"
*  DatePart("M", CAF_datestamp) = benefit_month
*  CAF_status <> "Approved"
*  CASH_check = checked OR SNAP_check = checked (maybe not necessary since HC not on CAF recert anymore)

**Comment by RobertFewins-Kalb** [comment]
This has been resolved. Closing.
