### ISSUE TITLE
Krabappel BUSI panel

### ISSUE THREAD

**Issue by CDPotter** [MN-Script-Team/DHS-MAXIS-Scripts#518]
While working on the month +1 issue we remembered BUSI got an overhaul this spring. This will need to be tackled in regards to Krabappel.

**Comment by theVKC** [comment]
Do you have this one?

**Comment by RobertFewins-Kalb** [comment]
We are the Intercontinental Tag Team Champions!!

**Comment by RobertFewins-Kalb** [comment]
Which is to say, "yes."

**Comment by RobertFewins-Kalb** [comment]
#Donezo

**Comment by theVKC** [comment]
So are you going to pull request all this wonderful stuff in? Because it's in a project folder you aren't exactly bound by code freeze...

**Comment by RobertFewins-Kalb** [comment]
Pulled. I don't deserve all the commit info on this one. @CDPotter and I tag-teamed this.

**Comment by RobertFewins-Kalb** [comment]
We just timed Krabappel creating and approving FS and HC on one Pressley case...

1 BUSI (updated for 03/15 and 04/15)
1 CASH
1 COEX (updated for 03/15 and 04/15)
1 DCEX (updated for 03/15 and 04/15) 
1 HEST
2 JOBS (updated for 03/15 and 04/15)
2 PARE
1 SHEL
2 UNEA (updated for 03/15 and 04/15)
1 WKEX (updated for 03/15 and 04/15)
(and obviously, TYPE, PROG, REVW, ADDR, 3 MEMB, 3 MEMI, 3 WREG, 1 EATS, 1 HCRE)

Total run time: 1:15.58
*Note: about 25 seconds of that was waiting for the case to come out of background.
