### ISSUE TITLE
ABAWD script

### ISSUE THREAD

**Issue by IlseFerris** [MN-Script-Team/DHS-MAXIS-Scripts#523]
So Henn Co. QI team is interested in an ABAWD script that can detail information about the ABAWD's including the follow up (EX: “Orientation scheduled for _(month)____- 2015 and exemption sheet given/mailed to client”)
Thoughts?

**Comment by courtrightd** [comment]
I have a SNAP orientation letter script that sends the WF1 referral and case notes, (soon to be released), perhaps adding a checkbox for exemption sheet given / mailed to client would work.  However if there is info that needs to be noted without sending a referral it wouldn’t make sense to do it this way.

**Comment by theVKC** [comment]
We could have the one script call the other where appropriate, right? Use the `CALL run_from_GitHub(url)` function, and make it easy for all of us? :)


Caution: This e-mail and attached documents, if any, may contain information that is protected by state or federal law. E-mail containing private or protected information should not be sent over a public (nonsecure) Internet unless it is encrypted pursuant to DHS standards. This e-mail should be forwarded only on a strictly need-to-know basis. If you are not the intended recipient, please: (1) notify the sender immediately, (2) do not forward the message, (3) do not print the message and (4) erase the message from your system.

**Comment by IlseFerris** [comment]
I would love to do both!  David, are you going to April's hackathon/going to be around the Hennepin County area anytime soon?

**Comment by courtrightd** [comment]
Staffing shortages and other issues are keeping me stuck in Duluth for the time being, but I can easily add stuff to the SNAP orientation script if you let me know what you are thinking.

**Comment by IlseFerris** [comment]
Sounds like a plan!  I'd love to be able to roll this out for 05/01/15

**Comment by theVKC** [comment]
Woohoo! @IlseFerris, could you tell @courtrightd what you think might make sense to add to his script in the way of a checkbox?
