### ISSUE TITLE
NOTE - Emergency

### ISSUE THREAD

**Issue by GayS** [MN-Script-Team/DHS-MAXIS-Scripts#524]
The script notes "Prospective" income that is pulled from the JOBS panel.   

Issue: client had three pay stubs entered for one month in JOBS and the case note script entered the total for the month vs. prospective income which case noted the client as over the 200% FPG.

Question:  should the "Prospective" income be pulled from teh FS PROSP INC screen instead?

**Comment by theVKC** [comment]
It is. Both areas are technically “prospective income”. MAXIS refers to it as “prospective income” in both places. If there is information on the PIC and the prospective income side of the panel, it pulls both per the request of our cash and SNAP folks.


Caution: This e-mail and attached documents, if any, may contain information that is protected by state or federal law. E-mail containing private or protected information should not be sent over a public (nonsecure) Internet unless it is encrypted pursuant to DHS standards. This e-mail should be forwarded only on a strictly need-to-know basis. If you are not the intended recipient, please: (1) notify the sender immediately, (2) do not forward the message, (3) do not print the message and (4) erase the message from your system.

**Comment by GayS** [comment]
Thanks for the clarification.
