### ISSUE TITLE
Need instructions for a few scripts

### ISSUE THREAD

**Issue by theVKC** [MN-Script-Team/DHS-MAXIS-Scripts#527]
No biggie, just need some instructions thrown up on the Wiki. I'll tag the folks who I believe worked on these scripts, correct me if I'm wrong (edited to show what's complete after the original post):

* MEMOS - Overdue Baby - @LaLarson - COMPLETE
* NOTES - Baby Born - @LaLarson - COMPLETE
* NOTES - Drug Felon - @devonne01 
* NOTES - DWP budget - @LaLarson - COMPLETE
* NOTES - MFIP sanction/DWP disqualification - @GayS - COMPLETE
* NOTES - MNSure Docs Req'd - I know this was an Anoka script, but I don't remember who built it. Perhaps @CDPotter or @RobertFewins-Kalb could shed some light? Did I do it way back when?

Anyway, if you're on this list, please write up some instructions and add them to the Wiki. If you have questions, email me. Thank you folks!

**Comment by theVKC** [comment]
I should have mentioned, please try and use the format that's already on the Wiki. Again, email me if you have questions! :)

**Comment by theVKC** [comment]
@GayS, I forgot one of yours. I've added it to the list.

**Comment by theVKC** [comment]
OK. I've just added the links to the MEMOS and NOTES sections of the Wiki. All you folks have to do is click the link, fill out your info, and send it in to me. Easy as pie.

**Comment by LaLarson** [comment]
Okay… I think I did it.

Laura Larson
IMU – Family Unit

Goodhue County HHS
426 West Avenue
Red Wing, MN 55066

Phone: 651-385-3200
Fax Numbers:

  *   Child Support Fax: 651-267-4880
  *   Income Maintenance Fax: 651-267-4879
  *   Social Services Fax: 651-267-4877

Email: laura.larson@co.goodhue.mn.us<mailto:laura.larson@co.goodhue.mn.us>



HHS Temporary Relocation Update

Effective Tuesday, February 17, 2015 Goodhue County HHS staff & services from the Citizen’s Building, 426 West Avenue, Red Wing, MN 55066 will be relocated to the old St. Joseph School, 469 – 12th Street, Red Wing, MN 55066.

The following divisions will be relocated - Social Services, Income Maintenance, Child Support and IT / HHS Finance.
The Public Health Division will remain at the Government Center & Colvill School locations.

This is a temporary relocation until the Citizen’s Building renovations / addition have been completed.  There is no change to phone numbers, mailing address or emails. Thank you.

Map: From Citizen’s Building to St. Joseph School<http://mapq.st/1D30asB>


NOTICE: This e-mail and any files transmitted with it are intended only for the use and viewing of the individual or entity to which they are addressed. If you are not the intended recipient, please immediately notify the sender of the transmission error and then promptly delete this message from your computer system. Please be advised that e-mail correspondence to and from Goodhue County may be public data subject to the Minnesota Data Practices Act and may be disclosed to third parties.

**Comment by GayS** [comment]
hmmm - I'm not seeing the NOTE - MFIP Sanctions/DWP Disqualification listed in WiKi.  I do  have a description ready.

**Comment by CDPotter** [comment]
If it's a brand new script you will have to add a page for it on the note wiki page. If you edit the menu page you can copy the formatting for the other links to make a new page. Let me know if you have any troubles with it and I can take a look/make instructions for it.

**Comment by GayS** [comment]
Thanks - I think I have added the note name & a description to the wiki page.  ??

**Comment by CDPotter** [comment]
I don't see it but I also don't have editing access so maybe it still need to be approved. @theVKC are you able to see the new NOTE - MFIP link on the notes scripts page?

**Comment by theVKC** [comment]
You did well, @GayS and @CDPotter. I am currently taking stock of all of the changes you all submitted and will update the initial issue with what I know. :)

**Comment by theVKC** [comment]
OK, looks like we still need NOTES - Drug felon (@devonne01) and NOTES - MNsure - Documents req'd. I really don't remember who built that one, but I know it was done at Anoka. If @CDPotter and @RobertFewins-Kalb call "not it", I'll take care of it myself. :)

**Comment by CDPotter** [comment]
Sorry it's been a really crazy week for me personally and I haven't had any time to take a crack at it. I should think by the end of the week I should be able to get it done.

**Comment by theVKC** [comment]
No worries @CDPotter, in fact, if you didn't write the script don't worry about it (unless you really want to). I just don't remember who wrote the dang thing!

**Comment by devonne01** [comment]
I’m sorry I was busy I will try and get to the drug felon in the next little bit..

**Comment by theVKC** [comment]
Thanks @devonne01! No rush, just happy to have it done! Let me know if you have any questions! :)

**Comment by CDPotter** [comment]
Got it added!
