### ISSUE TITLE
Training case creator

### ISSUE THREAD

**Issue by theVKC** [MN-Script-Team/DHS-MAXIS-Scripts#53]
Task list:

- [x] Add most panels to script
- [x] Add BILS to script
- [x] Add COEX to script
- [x] Add DFLN to script
- [x] Add WKEX to script
- [x] Add FMED to script
- [x] Add data validation features to spreadsheet
- [x] Approves HC
- [x] Approves cash
- [x] Allows birthdates other than 1/1
- [x] Shift DOA to a CM/01/CY type of approach
- [x] Merge custom functions into main library
- [x] Test Krabappel
- [x] Update Krabappel for time savings (Also part of #1626) - @CDPotter 
- [x] Krabappel needs a brand new FuncLib block - @IlseFerris 
- [x] Provide at least 8 SNAP scenarios - @CDPotter / @RobertFewins-Kalb
- [x] Provide at least 3 MFIP scenarios - @IlseFerris 
- [x] Provide at least 1 GA scenario - @CDPotter / @RobertFewins-Kalb
- [x] Provide at least 3 MAGI HC scenarios  - @CDPotter / @RobertFewins-Kalb / @IlseFerris / @C-Love 
- [x] Provide at least 3 non-MAGI HC scenarios - @IlseFerris / @C-Love 
- [x] Move Krabappel to the Utilities folder (rename as UTILITIES - TRAINING CASE CREATOR.vbs)
- [x] Move Krabappel spreadsheet to the primary folder (rename as SETTINGS - TRAINING CASE SCENARIOS.xlsx)
- [x] Add Krabappel to the Utilities main menu
- [x] Add any needed Global Variables for Krabappel to the GlobVar file
- [x] Update spreadsheet for some date-related bugs - @CDPotter 
- [x] Upload updated spreadsheet - @theVKC
- [x] Add selector for the Excel file - @theVKC
- [x] Update contributor list at the top of the script to reflect any new contributors to either the script or the scenarios - @theVKC
- [x] Fetch upstream on Utilities menu (we've added some buttons) - @theVKC
- [x] Test Krabappel in new location - @theVKC

(By switching to the checklist, we can remove issues #1625 and #1688 from the issue list)

**Comment by IlseFerris** [comment]
MFIP to DWP transition.  @courtrightd were you working on this?

**Comment by courtrightd** [comment]
I believe I pulled it into the current version of Krabbpel a week or so ago, should be working.

**Comment by IlseFerris** [comment]
Awesomeness, thanks David!

**Comment by theVKC** [comment]
Removed assignee, this is being tested by many at this point.

**Comment by theVKC** [comment]
Replaced many issues with functions...

Can I get an update on official scenarios? 2-3 from Stearns, Ramsey, Hennepin, Anoka, and St. Louis ought to do it. Should we set up a call to discuss how to proceed there?

* @IlseFerris 
* @courtrightd 
* @RobertFewins-Kalb 
* @CDPotter 
* @C-Love 
* @MelissaFox-Stearns 
* @GayS 
* @StormageddonDLOA 

Yay for being so close to finished!!!

**Comment by GayS** [comment]
My vote is for a conference call. :)

**Comment by CDPotter** [comment]
Where does the current version live again?

**Comment by IlseFerris** [comment]
I can do a conference call. I wasn't working on any official scenarios, but I could reach out to our training unit if we want some from Hennepin.

**Comment by GayS** [comment]
We reached out to our trainers for scenarios at Stearns - not sure when we will get them (1-2 weeks?)

**Comment by courtrightd** [comment]
I believe we have scenarios in SLC, but they were set up for a different version of Krabappel and I will need to reconfigure the spreadsheets and test.  Sometime in the next couple weeks is possible.

**Comment by theVKC** [comment]
I'm comfortable waiting for the official scenarios. Do we think we should release the script as-is for now, sans scenarios? Any thoughts?

**Comment by RobertFewins-Kalb** [comment]
Don't release. I'm testing our scenarios and I found an error. I'm going to fix and submit.

**Comment by Y-Lor-Y** [comment]
Casey might have more info on this than I, but last I heard…our training unit is creating a listing of scenarios for this.

Yang T. Lor | FCM Resource Trainer
Financial Assistance Services |  Ramsey County CHS
160 Kellogg Boulevard East, Saint Paul, MN  55101
P: 651-266-3621  |  Fax: 651-266-3705
E: yang.tou.lor@co.ramsey.mn.us
Schedule: M to Th, 7:45 AM to 6:00 PM
www.ramseycounty.us<http://www.ramseycounty.us>

The information included in this email message, including any attachments, is intended only for the person or organization to which it is addressed.  This email message may contain information that is privileged or confidential.  If you receive this email message and are not the intended recipient or responsible for delivering the message to the intended recipient, you may not use, disseminate, distribute, or copy the information included in this email and any attachments.  If you received this email by mistake, please reply by email and destroy all copies of this message and any attachments.  Thank you

**Comment by RobertFewins-Kalb** [comment]
@CDPotter is going to test the scenarios we have put together and check for bugs. He is also going to submit a pull request for the bug we found.

**Comment by theVKC** [comment]
Thanks @RobertFewins-Kalb and @CDPotter!

**Comment by CDPotter** [comment]
The fruits of today's testing have been added, more to come!

**Comment by CDPotter** [comment]
Ok! We have resolved all of our training case and the issues that have popped up while doing so. 

(save for rewriting code to adjust for HCRE's removal,)

Types of cases we have:
2 only Fam SNAP
2 GA/adult SNAP
1 adult SNAP
1 MFIP only
1 fam HC/SNAP

**Comment by theVKC** [comment]
Woot! Sounds wonderful!

**Comment by theVKC** [comment]
So, non-Anoka counties: could you review the new Excel file's scenarios? If these work for your counties, that's fine and we'll take them. If anyone wants to add more, we can do that.

**Comment by CDPotter** [comment]
There's only one example(not quite sure how it got in there...) in the excel file I uploaded. (currently) I can upload a new version with all of the ones we vetted?

**Comment by theVKC** [comment]
Yeah, I think so. Let's just put it out there to see what people think.

**Comment by CDPotter** [comment]
Ok they have been pulled in.

**Comment by theVKC** [comment]
Thanks @CDPotter! I'd love it if non-me people could evaluate them! :)

**Comment by CDPotter** [comment]
One thing for others to note, Copy and pasting scenarios from one excel file to another causes them to lose their validation. So we may just have to keep manually adding onto this file if we add more examples.

**Comment by theVKC** [comment]
What do we think of targeting this release for v2016.02? @IlseFerris @courtrightd @CDPotter @C-Love @RobertFewins-Kalb @GayS do any of you have any objections with me adding it to the planned February release?

**Comment by C-Love** [comment]
I have 6 Ramsey scenarios from our training unit. I will get them krabappleized and tested. I have a feeling there will be some overlap. Our training unit does not train any cash so our scenarios are SNAP/HC only

And I think Feb release is a good plan.

**Comment by theVKC** [comment]
"Krabappelized" = word of the century

**Comment by C-Love** [comment]
YIKES! I am getting an error when trying to create a case with HC. The 'write_panel_to_MAXIS_HCRE' function has either the wrong number of arguments or invalid property assignment. I have tried this on the Beasly scenario as well as my own. (Line 581). @RobertFewins-Kalb @CDPotter @theVKC   Sorry I don't have more detail, I have to run to a meeting and am not very familiar with that function. I think you mentioned something regarding HCRE was changed recently.

**Comment by theVKC** [comment]
@CDPotter: any ideas on Casey's issue?

**Comment by RobertFewins-Kalb** [comment]
Something is amiss. I thought we removed that function call in the script. It should just be transmitting through HCRE.

**Comment by theVKC** [comment]
I don't think I touched it. Hmmmmm.

**Comment by RobertFewins-Kalb** [comment]
OK...so I looked over our pull request. I think we replaced the wrong function. I'm going to test locally to verify.

**Comment by CDPotter** [comment]
Swapped the clauses back in #1766 Checked it on BURNS(HC) and BEASLY(SNAP) and it worked.

**Comment by C-Love** [comment]
I made the changes you just sent in @CDPotter  and that fixes the HCRE issue. Yay! 

However now there is some issue with writing to the JOBS and UNEA panel - everything is all cattywampus, the PIC doesn't open. Codes are being put in the wrong places.

**Comment by CDPotter** [comment]
What scenarios?

**Comment by C-Love** [comment]
I tried it on one of mine and then I tried it on Beasley

**Comment by CDPotter** [comment]
Hmm.. I'm not sure what is happening there. I just made 4 beasleys and it seemed to be working fine on our end.

**Comment by C-Love** [comment]
I figured some things out. First my Git Hub did not correctly load the new spreadsheet - so that causes some problems -eek - so I manually pulled the new one off and that fixed the JOBS and UNEA. 

I am running in to 2 more problems that you might have some insight on

For UNEA, starting in 01/16  the script stops because the COLA line is slightly insistent. I could not find another scenario with a UNEA to see if that was my fault BUT it was only happening in Jan for a scenario CM-4. I added a 'transmit' after line 1821 and that solved it, so appears some weird MAXIS hiccup.

The other has to do with HC FIAT for MAGI cases - the Burns scenario works but my scenario gets caught up and won't go into edit/fiat. Then MAXIS makes clients inelig for MNSURE. I'm sure I need to fix something, maybe you have some insight.

**Comment by CDPotter** [comment]
The COLA thing makes sense and should probably be pulled in. 

We did hit the BURNS FIAT issue (it happened when I looked away for a moment) where the script got hung up mid FIAT. Not sure why it happened and then we ran it again on 3 BURNS cases (at one time) and it worked fine for all of them so we weren't able to repeat it.

**Comment by C-Love** [comment]
I ran mine with 3 cases at once and it worked! Fun times in MAXIS training region. 

This script is amazing and gets more so every time I run it.

**Comment by IlseFerris** [comment]
Excellent! I was given some case scenarios from our Onboarding team, so I'll be able to get those submitted in the next day or two.

**Comment by C-Love** [comment]
I just ran in to a problem with IMIG. The function for writing to the IMIG panel has a different number of arguments in the script vs FuncLib. I tried just commenting out the extra arguments in the script but then I ran into a problem with 'Actual Date' on IMIG - it defaulted to the current date - which is not allowed when working on a panel in a past month.

**Comment by theVKC** [comment]
Hmmm. Think you can fix it @C-Love?

**Comment by C-Love** [comment]
I think I have an idea of what it needs. I will take a look today.

**Comment by theVKC** [comment]
FYI all: I'm targeting this for the March release. I will be formally closing the Krabappel milestone today.

**Comment by CDPotter** [comment]
Ok regarding adding timesavings to this one (finally have time to sink my teeth into this) We want to:

A: count the time for each panel (should I make a new manualtime for each panel?)
B: count time appling/approving

This will be done partly in funclib(for each write_panel function) and the script right?

Since I was out for the timesavings rebuild it looks like the script end procedure writes one number for STATS_manualtime so I'm not entirely sure how we could be specific for each panel written (such as CASH takes much less than ACCT). 

I suppose each function could add onto STATS_manualtime then add that to the STATS_manualtime(would that need to get added to be pulled through each function?) then multiply by how many cases get created?

**Comment by theVKC** [comment]
FYI all: if everything goes right I will be pushing this out. Tonight. Eeek.

**Comment by CDPotter** [comment]
Noticing a problem with Bdays, Any non-Anoka ones have had the dates converted by excel from 01/12 to Jan-12.

**Comment by theVKC** [comment]
Can we add that to the validation?

**Comment by CDPotter** [comment]
Possibly? Can you restrict something to MM/DD format? I know you can do date but that would include YYYY and the script isn't set to handle that.

**Comment by theVKC** [comment]
Maybe. Maybe the format for the cell can just be customized?

**Comment by CDPotter** [comment]
Looks like I can make a custom one. I'll update the file on github. @IlseFerris I'll update the file you're working off of as well and email it back to you. @theVKC can I email the file to you to upload to github?

**Comment by theVKC** [comment]
Sure thing.

**Comment by IlseFerris** [comment]
@CD you're amazing!
