### ISSUE TITLE
Fix Krabappel Date issues

### ISSUE THREAD

**Issue by courtrightd** [MN-Script-Team/DHS-MAXIS-Scripts#533]
I think write_panel_to_maxis_DISA has an issue with using create_maxis_friendly_date, since DISA uses 4 digit years.

**Comment by theVKC** [comment]
Who wants it?

**Comment by RobertFewins-Kalb** [comment]
On the topic...

One thing we need to do is insert an:
IF date_variable <> "" THEN CALL create_MAXIS_friendly_date(date_variable)

Otherwise, the function is dumping "12 30 99" in the date field.

**Comment by theVKC** [comment]
Are you volunteering, @RobertFewins-Kalb? :)

**Comment by RobertFewins-Kalb** [comment]
And I feel bad b/c I thought that I fixed that in my pull request. I know I was thinking about it. I can take it.

**Comment by theVKC** [comment]
Done. Good luck!

**Comment by RobertFewins-Kalb** [comment]
Rad. I will actually go through the Krabappel FuncLib, while I'm on it, and add the IF date_variable <> "" to make sure we aren't creating 12/30/99 all up in this.

**Comment by courtrightd** [comment]
Good thinking, I forgot that problem was occurring on DISA as well.

**Comment by RobertFewins-Kalb** [comment]
FACI is going to need 4-digit years as well. Tell y'all what. This let's rename this issue "Make sure Krabappel is writing dates correctly."

**Comment by theVKC** [comment]
#LetsWriteANewFunction called create_MAXIS_friendly_date_with_YYYY

**Comment by IlseFerris** [comment]
Yes please! I can't speak for anyone else, but I need this.
IF len(baseline_date) < 6 THEN MsgBox "You must enter a date in format MM/DD/YYYY"
	LOOP until len(baseline_date) >= 6
This code appears in much of my work.

**Comment by theVKC** [comment]
I can do that, folks. I'm currently updating FuncLib with all kinds of new fun.

**Comment by RobertFewins-Kalb** [comment]
#FutureProofing ... why not mod "create_MAXIS_friendly_date()" and have the function determine whether the year needs 2 or 4 digits?

**Comment by RobertFewins-Kalb** [comment]
The thought being that maxis screens can change, it reduces the potential for script writer error, and I'm going to be 30 in 5 weeks and age and memory are negatively correlated :)

**Comment by theVKC** [comment]
Because that requires going through over 130 scripts to update the references. :p

Separate functions might be easier for our end users, in my opinion. Besides, I just pushed it. [smirks]

**Comment by RobertFewins-Kalb** [comment]
Well...smirk, indeed!

**Comment by RobertFewins-Kalb** [comment]
OK...I have updated the date field filling on DISA and then added IF date_variable <> "" THEN ... for non-mandatory fields on the following panels...
* ABPS
* ACCT
* DISA
* DSTT
* EMMA
* IMIG
* RBIC
* STWK

committing and pulling...

**Comment by theVKC** [comment]
@RobertFewins-Kalb, was this done? Why is this open?

**Comment by RobertFewins-Kalb** [comment]
It is done. RE: Why it is open -- I have no idea. Shut it down.
