### ISSUE TITLE
SNAP E&T letter enhancements

### ISSUE THREAD

**Issue by IlseFerris** [MN-Script-Team/DHS-MAXIS-Scripts#536]
Have script make the WF1M referral and have check box for exemption sheet given/mailed to client.  I can work on this.  Hennepin wants to roll this out for May 1.

**Comment by IlseFerris** [comment]
Yeah, I'm going to rethink a couple things here. @theVKC we'll talk next week

**Comment by theVKC** [comment]
"rethink a couple things"... @IlseFerris, want me to close the issue?

**Comment by IlseFerris** [comment]
Yes, I think we can.  We should be A-OK POLI-wise with the SPEC/LETR.

**Comment by IlseFerris** [comment]
David @courtrightd was this running OK for you when you tested it?  I cannot test it without Dialog ID errors.

**Comment by courtrightd** [comment]
It was running fine, I’ll test it again and see if I can find what’s up.

**Comment by IlseFerris** [comment]
Awesome, thank you!  Let me know either way if you could.

**Comment by courtrightd** [comment]
Should be resolved with most recent pull.  Apparently the dialog name can’t have an &?
