### ISSUE TITLE
LTC 1503 script enhancements/fix

### ISSUE THREAD

**Issue by IlseFerris** [MN-Script-Team/DHS-MAXIS-Scripts#541]
x102631 reports that 'needs asset assessment' button does not case note.  I can update that.  
Additionally thinking that check boxes for forms needed/sent (IE: 3531, certain pops, etc) could be helpful.  I can take this one.

**Comment by theVKC** [comment]
Good luck!

**Comment by IlseFerris** [comment]
Thanks, I'm on it!

**Comment by IlseFerris** [comment]
this one can be closed too, we're on a roll!
