### ISSUE TITLE
Enhancement Request for Bulk REPT Script - ACTV

### ISSUE THREAD

**Issue by suzchik19** [MN-Script-Team/DHS-MAXIS-Scripts#543]
Hello,
Please add the following to the REPT/ACTV script. These features were all present on the Dakota County REPT/ACTV script, let me know if you need a copy. 
1. Add child care status column
2. Provide a total of the Programs per case, as follows:
Total MAXIS Cases = 87
Active cash cases = 65
Pending cash cases = 2
Active FS cases = 38
Pending FS cases = 0
Active CC cases = 22
Pending CC cases = 1
Suspended CC cases = 2
Active HC = 49
Pending HC = 0
Pending EA = 1
3. Add a summary tab that totals cases per worker and by program to help with caseload redistribution.
Thanks,
Susie

**Comment by theVKC** [comment]
Can you email me a copy to my state email?

**Comment by suzchik19** [comment]
Yep! I will have to get it from IT, and I’ll send it. ☺

Thanks,
Susie

**Comment by theVKC** [comment]
If email is difficult, it isn't hard to come down there from the state. I can bring a jump drive. :)

**Comment by suzchik19** [comment]
I think I sent a text file? Otherwise - come visit any time!

**Comment by theVKC** [comment]
I got it, but I'd still love to come visit. Just say when! :) :)

**Comment by theVKC** [comment]
@suzchik19, I'm closing this issue for the moment due to lack of time on my part. If Dakota would like to train a scriptwriter to take a look, we may be offering training soon and I'd be happy to help arrange that.

**Comment by suzchik19** [comment]
Thanks for the update.
