### ISSUE TITLE
Approved progs: for SNAP cases, grab change reporter status for case note, and note it

### ISSUE THREAD

**Issue by theVKC** [MN-Script-Team/DHS-MAXIS-Scripts#544]
Easy win. Who wants it?

**Comment by CDPotter** [comment]
I can knock this one out too

**Comment by CDPotter** [comment]
I think I've got it working, took a bit of scripting gymnastics because of how we built the original arrays.

Just to be clear we want to grab the reporting status section from the FSSM screen?  

for example I've got it writing "* SNAP for 04/15: $109.00 NON-HRF"

**Comment by theVKC** [comment]
Looks good. I'd add the word "reporter" onto that.

**Comment by theVKC** [comment]
Resolved a bit ago. Thanks @CDPotter!
