### ISSUE TITLE
Bug- Case note dialog does not change footer month forward

### ISSUE THREAD

**Issue by RoyStearns** [MN-Script-Team/DHS-MAXIS-Scripts#561]
These are the scripts that I know of that do this (there may be others)- CAF, CSR, HC renewal, HCAPP.
If you are trying to use the Case/NOTE scripts above and are in the footer month of 5 and change it to 4 from inside the script
![capture footer](https://cloud.githubusercontent.com/assets/10159949/7123493/05971d72-e1e8-11e4-80c4-396b305bfe99.PNG)
- the script will f3 out and start reading Maxis stats for the case note in the footer month of 4. However if you happen to start the script in the footer month of 4 and want to change it to 5 from inside the script- it will still pull all of the info for the case note from the footer month of 4, not changing to 5.
This has caused confusion as to where the script is getting the info from and also causing incorrect case notes if not caught.

**Comment by theVKC** [comment]
Hmmm. The logic for footer month entry is ancient. As in it was a very early development in my scriptwriter career at Anoka. Do you have ideas for fixing it, @RoyStearns?

**Comment by theVKC** [comment]
I'm going to try and pound this out before vacation this month!

**Comment by theVKC** [comment]
@IlseFerris just built a new function for this stuff. Perhaps after it's been tested we can evaluate again. Maybe in a couple of weeks we can close this issue.

**Comment by theVKC** [comment]
@IlseFerris/@RoyStearns, do either of you know if the new function resolved this?
