### ISSUE TITLE
BNDX Scrubber

### ISSUE THREAD

**Issue by RobertFewins-Kalb** [MN-Script-Team/DHS-MAXIS-Scripts#562]
Enhancement Request: Clean-up the logic of the BNDX Scrubber so it isn't a gigantic mess. Seriously, @RobertFewins-Kalb , what were you thinking?

Use arrays to compare multiple RSDI claims instead of that messing smushing.

**Comment by RobertFewins-Kalb** [comment]
I'm on it, @RobertFewins-Kalb . Please do not be so condescending.

**Comment by theVKC** [comment]
Settle down you two.

**Comment by RobertFewins-Kalb** [comment]
Resolved with Pull Request #580
