### ISSUE TITLE
Krabappel: Doe scenario generating random FACI panel?

### ISSUE THREAD

**Issue by theVKC** [MN-Script-Team/DHS-MAXIS-Scripts#563]
I don't know if someone can explain this one to me or not, but I'm adding it. @RobertFewins-Kalb or @CDPotter, I know you recently added some functionality... Care to look at it?

**Comment by RobertFewins-Kalb** [comment]
We wouldn't be able to recreate it. We have added panels that read before the script gets to FACI (DFLN and BILS, for example).

**Comment by RobertFewins-Kalb** [comment]
Basically, the work @CDPotter and I have completed render Doe, Inelig, Kia, Swiss, and Lab obsolete. The Presley template needs to be expanded for other scenarios because it is the most complete.

**Comment by theVKC** [comment]
We need to make sure those scenarios work, as I have internal folks planning to use them. Can you fix the scenario to work with them? Also, why would FACI be part of this at all? I'm confused. It never used to go to FACI...

**Comment by RobertFewins-Kalb** [comment]
Will do. In the meantime, can you accept the pull request 559? That has all the updates @CDPotter  and I have been working on.

As for the problems with FACI, I have no idea. I can only guess that the Excel row that the script starts reading FACI from is, on the Doe scenario, populated with some information that is associated with a different panel. So maybe the row that the script starts reading FACI from is actually populated with information for something like EATS...just a thought...

**Comment by RobertFewins-Kalb** [comment]
OK. SO. The script thinks FACI starts at row 287. On the Doe scenario, line 287 is "Child 1 Relationship Code" for PARE and there is information in that row. That's why it's creating a FACI panel.

**Comment by RobertFewins-Kalb** [comment]
Further OKs... I have updated Doe, and created a new case, and XFER'd to PWVKC45 (see case 219800). I will work on updating the remaining cases -- as in, getting the template pulled to Kia, Swiss, Lab, and Cash.

**Comment by RobertFewins-Kalb** [comment]
This has been resolved.
