### ISSUE TITLE
NOTES - CAF: add "Senior SNAP App (5223-F)" to the list of CAF types dropdown

### ISSUE THREAD

**Issue by IlseFerris** [MN-Script-Team/DHS-MAXIS-Scripts#564]
Jennifer Beek at X142573 has requested on SIR: Could someone create a script to case/note for 5223F?

I can take this one

**Comment by theVKC** [comment]
It's yours. Good luck!

**Comment by IlseFerris** [comment]
Do you think we should just add this as a drop down option much like the addendum?

**Comment by CDPotter** [comment]
I think that would make sense. I'm not super familiar with the seniors app but it probably requires that the same info be case noted.

**Comment by theVKC** [comment]
So, should we modify the title and tags for this issue to reflect that it's now an option on the CAF?

**Comment by IlseFerris** [comment]
Yep
