### ISSUE TITLE
Documentation: create "style guide" for best practices in dialogs

### ISSUE THREAD

**Issue by theVKC** [MN-Script-Team/DHS-MAXIS-Scripts#565]
I think this is a long time coming. Some of us do it one way, some another. I want everyone doing it the same way. :)

Anyone interested in assembling this?

**Comment by IlseFerris** [comment]
I can take a crack at it

**Comment by theVKC** [comment]
Good luck Ilse!!

**Comment by theVKC** [comment]
As requested while we sit next to each other: can you add "create comments in the CASE NOTE section to break down case noting dialog info by dialog, as you had in 5181?"

**Comment by theVKC** [comment]
Hey @CDPotter, are you interested in building this statewide documentation?

**Comment by CDPotter** [comment]
I could give it a go this week. What medium would you like me to use? Powerpoint, script wiki, word?

**Comment by theVKC** [comment]
I like Word myself.

**Comment by theVKC** [comment]
And thank you!

**Comment by theVKC** [comment]
Resolved, and added to SIR. Good job, @CDPotter!
