### ISSUE TITLE
Documentation: functions library breakdown

### ISSUE THREAD

**Issue by theVKC** [MN-Script-Team/DHS-MAXIS-Scripts#566]
The always amazing @IlseFerris has begun creating a document explaining every single function in FuncLib. I'm putting this issue in for tracking purposes.

@IlseFerris, shall we upload this to SIR so we both can work on it?

**Comment by IlseFerris** [comment]
Custom functions and VBscript commands quicklist now on SIR.  The rest of the documentation to follow.
