### ISSUE TITLE
Create an Excel file with client names and addresses

### ISSUE THREAD

**Issue by TMBohm** [MN-Script-Team/DHS-MAXIS-Scripts#567]
It would be nice to be able to run a script that would pull the names and addresses from the Rept/ACTV list and put into an Excel file.

**Comment by theVKC** [comment]
Hey @RobertFewins-Kalb and @CDPotter... am I right in thinking you built something like this after I left Anoka?

**Comment by RobertFewins-Kalb** [comment]
We built something similar. We were asked to build something to identify cases for the Lexington Office based on the zip code. This would be a really easy build.

**Comment by TMBohm** [comment]
Thanks.  What is the next step to get this script built?  Of course, it’s something we would like ASAP.  ☺



Treva Bohm
Eligibility Worker
218.470.8452

**Comment by RobertFewins-Kalb** [comment]
How comfortable are you building the script yourself? We have a solid foundation in Anoka (thanks @theVKC ) that we like to modify for quick reports. I can send you the link if you feel capable of building.

**Comment by TMBohm** [comment]
Not comfortable at all.  I went to training several months ago and haven’t been able to continue working on anything.  Also, that was my first dive into any type of programming/script writing other than writing simple macro in Work and WP a few years ago.

On the other hand, if you want to send me the link, I wouldn’t mind taking a look at it to see if some of the training comes back to me.  There’s another person here that went to training  with me, so we could look at it together.  We really want to stay connected to the script writing, but we haven’t had the time.  We were in the middle of going paperless at the time of training so that was the priority.

Treva Bohm
Eligibility Worker
218.470.8452

**Comment by RobertFewins-Kalb** [comment]
Here's the link...

https://raw.githubusercontent.com/RobertFewins-Kalb/Anoka-Specific-Scripts/master/BULK%20-%20Pull%20Cases%20into%20Excel.vbs

**Comment by TMBohm** [comment]
Thanks!

Treva Bohm
Eligibility Worker
218.470.8452

**Comment by TMBohm** [comment]
Thanks, Robert

I’m including Linda on this email as she also attended the Script Writing training in Polk County.

We’ve looked at the script you sent and see that it does a lot more than what we had in mind.  However, it’s possible we would want to use more of the script in the future.    I see you have a list of people allowed to use the script. Would it be possible to get added to the list to see if it’s something we want to use it, as is?

Thanks

Treva Bohm
Eligibility Worker
218.470.8452

**Comment by RobertFewins-Kalb** [comment]
Feel free to take that script and run with it. We have that set up for Anoka County users. You can remove those people if you like or just add specific Polk County users to the list. Run wild with it.

**Comment by TMBohm** [comment]
Thanks, Robert.

Treva Bohm
Eligibility Worker
218.470.8452

**Comment by theVKC** [comment]
So, @CDPotter has volunteered to build this script! Go Charles!
