### ISSUE TITLE
Paystubs Received: should yell at you if you have a future pay date

### ISSUE THREAD

**Issue by theVKC** [MN-Script-Team/DHS-MAXIS-Scripts#572]
Let's just toss this one on the pile for me to look at.

**Comment by RobertFewins-Kalb** [comment]
Ooo...I didn't do that yet. I will at it to the script. Shouldn't be an issue.

**Comment by RobertFewins-Kalb** [comment]
I'm close to submitting a pull request for ACTIONS - PAYSTUBS RECEIVED.
