### ISSUE TITLE
KRABAPPEL -- DWP to MFIP

### ISSUE THREAD

**Issue by RobertFewins-Kalb** [MN-Script-Team/DHS-MAXIS-Scripts#573]
Do we need to worry about a scenario in which DWP transitions to MFIP during the automated approval?

**Comment by courtrightd** [comment]
I can’t see that being a need, but who knows.  Are you talking DWP 1st month of package, MFIP second month?  I think being able to approve either one should be sufficient, changing the scenario between footer months seems like a lot of new functionality.

**Comment by RobertFewins-Kalb** [comment]
We were thinking about what happens if you APPL a case 5 months in the past, it generates DWP, and after 4 DWP months, the client is switched to MFIP. But @CDPotter  and I have never handled family case programs so we're not sure if it's going to be an issue.

**Comment by RobertFewins-Kalb** [comment]
Also, @CDPotter  and I put in a bunch of time this week wrapping up Krabappel. We have GA and MSA working. I am finishing up GA with SNAP this morning. 

There are only four panels to test: EMPS, IMIG, RBIC, and SPON.

Data validation is almost done.

**Comment by courtrightd** [comment]
EMPS is tested and working here, aside from it can’t be coded with child under 1 exemption, as the popup window needs to be manually entered with months for the exemption, and that has not been coded.   I will try the 5 months past DWP scenario before I pull request a couple of slight tweaks to the approval for family cash.

**Comment by RobertFewins-Kalb** [comment]
RAD!! I will erase EMPS from our window!

**Comment by theVKC** [comment]
"popup window needs to be manually  coded with months for exception"... can we not work logic into this based on application date?

**Comment by courtrightd** [comment]
Yes – I’m working on wrapping my head around the logic, it just won’t be quick and easy.

**Comment by theVKC** [comment]
Say @courtrightd, do we have any news on this? Just curious for an update.

**Comment by courtrightd** [comment]
Umm, no news is bad news, I’ll try and look at it tomorrow on my scripting day.
