### ISSUE TITLE
Check to see if "new_page_check" is being used by any scripts

### ISSUE THREAD

**Issue by theVKC** [MN-Script-Team/DHS-MAXIS-Scripts#576]
If it is, we should replace it with better functionality. That looks really old. Really, really, really old.

**Comment by RobertFewins-Kalb** [comment]
NOTES - BURIAL ASSET

**Comment by IlseFerris** [comment]
@CDPotter are you willing to take this one since you're working on the Burial assets scripts?  It's in the Burial assets script 52 times now.

**Comment by CDPotter** [comment]
Well the changes I did today already got accepted but I can add this to my to-do list.

**Comment by CDPotter** [comment]
What are we replacing new_page_check with?

**Comment by CDPotter** [comment]
Ah I think I found it, case_note_page_four and new_page_check have been incorporated into the write_variable/write_bullet_and_variable functions?

**Comment by CDPotter** [comment]
So I wanna get input from others. 

I noticed the write_three_columns_in_case_note function doesn't account for page 4. Should I try to update that function as well? Otherwise I can just leave the case_note_page_four bit in since it's an internal function exclusive to this script.

**Comment by theVKC** [comment]
Closing this issue because any remaining issues with burial assets should have their own issue numbers by now.
