### ISSUE TITLE
CAF addendum

### ISSUE THREAD

**Issue by IlseFerris** [MN-Script-Team/DHS-MAXIS-Scripts#577]
With all this talk about possible CAF script upating, how about a CAF addendum option.  Or just a new script all together?

**Comment by theVKC** [comment]
This is a duplicate of #89... if you want it, comment on that particular issue, @IlseFerris! :8ball:

**Comment by IlseFerris** [comment]
Well then, that will teach me to search before posting.  I'm totally failing at Mondays today.
