### ISSUE TITLE
Revw/mont closure issue

### ISSUE THREAD

**Issue by CDPotter** [MN-Script-Team/DHS-MAXIS-Scripts#597]
it looks like the portion of code that determines if the worker number entered is the same as the active user doesn't Ucase the worker number entered by the worker. As such workers with letters as their worker numbers have been missing their 1st page if they have multiple pages. Shout out to @mldietz for catching this one. I'll be submitting a fix shortly.

**Comment by theVKC** [comment]
#598 resolved this. Thanks @CDPotter!
