### ISSUE TITLE
Method B budget breakdown on SPEC/WCOM

### ISSUE THREAD

**Issue by IlseFerris** [MN-Script-Team/DHS-MAXIS-Scripts#599]
I know back in the day (Anoka circa 2014) we talked about this idea at one point.  Basically would breakdown the deductions and difference between the spenddown amount and the recipient amount.  Didn't see this issue out there, so thought I'd throw it out there.

**Comment by theVKC** [comment]
Reassigned to @CJOHNS356 as he is at our hackathon and willing to take this on. Thanks Chris!

**Comment by IlseFerris** [comment]
Suggested verbiage:

Although your spenddown is $xxx, your recipient (or the amount that you are responsible to pay each month) is $xxx.
This was determined using the following calculation:
Income: $xxx - MA income standard $xxx = $xxx spenddown
$xxx spenddown - $xxx variable one, - $xxx variable two, - $xxx variable three, - $xxx variable four = $xxx recipient amount.
*                                                        
You will also be responsible to room and board costs of  
$891 per month.                                          
Please contact me with any questions. Thank you.         

-Not all cases will be responsible for room and board, so that should be a choice in the script.

**Comment by theVKC** [comment]
@CJOHNS356, any chance we can get an update on where this might be at?

**Comment by theVKC** [comment]
(somehow writing that comment unassigned Chris, not sure how)

**Comment by CJOHNS356** [comment]
This is what I have so far

I need to add the room and part and figure out format currency

Christopher Johnson
Family Support and Assistance
Eligibilty Specialist
Olmsted County Family Support and Assistance
Phone: (507) 328-6311
Fax: (507) 328-7956

NOTICE: This e-mail communication is for the sole use of the intended recipients and may contain unclassified confidential information. Any unauthorized disclosure, copying or dissemination of this communication is prohibited. If you are not the intended recipient, please notify the sender by e-mail and delete all copies received. Thank you.
P Go Green!  Please do not print this e-mail unless it is completely necessary.

**Comment by theVKC** [comment]
@CJOHNS356, you are responding to a GitHub thread (so attachments don't work), and you typically can't send a script file (in any case). I just wanted to know where you were at with it. No rush, but I'd love to have this when you're done! If you need any help, let me know. :)

**Comment by theVKC** [comment]
@CJOHNS356: any chance you've wrapped this one up? We'd love to have it, considering COLA is on us again. :)

**Comment by CJOHNS356** [comment]
Sorry I don’t

I am having are hard time keeping up with my current work load I expect to have time to work on this but not until after the 1st of the year.

I have most of it done, I can email what I have if you like

Christopher Johnson
Family Support and Assistance
Eligibilty Specialist
Olmsted County Family Support and Assistance
Phone: (507) 328-6311
Fax: (507) 328-7956

NOTICE: This e-mail communication is for the sole use of the intended recipients and may contain unclassified confidential information. Any unauthorized disclosure, copying or dissemination of this communication is prohibited. If you are not the intended recipient, please notify the sender by e-mail and delete all copies received. Thank you.
P Go Green!  Please do not print this e-mail unless it is completely necessary.

**Comment by theVKC** [comment]
I think @IlseFerris might be interested in taking this on. But, I'd much rather have you pull request it in than email it. It should only take a few minutes, and a pull request would ensure you receive credit for your work (it also gets you on the formal email list for scriptwriters).

@IlseFerris: I'm thinking we create a branch, @CJOHNS356 pull requests to that branch (it would be copying your code and pasting it into GitHub), and @IlseFerris wraps it up.

**Comment by IlseFerris** [comment]
Sounds like a plan to me!

**Comment by CJOHNS356** [comment]
I did up load the script to GitHub I don’t know if I did it right please let me know

Thanks

Christopher Johnson
Family Support and Assistance
Eligibilty Specialist
Olmsted County Family Support and Assistance
Phone: (507) 328-6311
Fax: (507) 328-7956

NOTICE: This e-mail communication is for the sole use of the intended recipients and may contain unclassified confidential information. Any unauthorized disclosure, copying or dissemination of this communication is prohibited. If you are not the intended recipient, please notify the sender by e-mail and delete all copies received. Thank you.
P Go Green!  Please do not print this e-mail unless it is completely necessary.

**Comment by IlseFerris** [comment]
https://github.com/IlseFerris/DHS-MAXIS-Scripts/blob/Method-B/Script%20Files/MEMOS/MEMOS%20-%20METHOD%20B%20WCOM.vbs

**Comment by IlseFerris** [comment]
@CJOHNS356 I made a new branch for your file. Can you click on the link above, put the file into edit mode and copy and paste your code into the file? Then you'll be able to get the credit, and I'll be able to work on it.

**Comment by CJOHNS356** [comment]
Done

**Comment by IlseFerris** [comment]
@CJOHNS356 did you copy and paste your code into the link I sent? I don't see it

**Comment by CJOHNS356** [comment]
I tried it again hopefully I did it right this time

Christopher Johnson
Family Support and Assistance
Eligibilty Specialist
Olmsted County Family Support and Assistance
Phone: (507) 328-6311
Fax: (507) 328-7956

NOTICE: This e-mail communication is for the sole use of the intended recipients and may contain unclassified confidential information. Any unauthorized disclosure, copying or dissemination of this communication is prohibited. If you are not the intended recipient, please notify the sender by e-mail and delete all copies received. Thank you.
P Go Green!  Please do not print this e-mail unless it is completely necessary.

**Comment by theVKC** [comment]
@IlseFerris: can I assign this to you?

**Comment by IlseFerris** [comment]
Yes please do

**Comment by IlseFerris** [comment]
It worked, thank you Chris!
