### ISSUE TITLE
Closed Prog: enhancement to specify monthly/six monthy vs annual

### ISSUE THREAD

**Issue by ALJ10** [MN-Script-Team/DHS-MAXIS-Scripts#604]
Here is an enhancement request rec'd via a supervisor:

I am wondering what your thoughts are on an enhancement request to the Closed Progs Script that would separate out the following:

Current Box: Case is at renewal (monthly, six-month, annual. Client gets entire next month after closure for REIN)

Requested Enhancement: 

One box: Case is at renewal (monthly, six-month) Client gets entire next month after closure for REIN. ~Casenote then states only CSR not CSR/CAF

Second box: Case is at renewal (annual) Client gets entire next month after closure for REIN. ~Casenote then states only CAF. 

The reason for this request is we are seeing that when the current box is checked the case note states the client can turn in the CAF/CSR for the six month renewal. The problem with that is if support gives them the CAF they then need an interview, and it creates more work and holds things up for the client. When they could just turn in the CSR for the six month without an interview. 

***I see closed issue #123 is similar to this, but it didn't specifically mention being able to clearly specify if renewal is monthly/six month or annual. So we thought we'd submit a new request to see what other Git Hub user thoughts are.

**Comment by Farleight** [comment]
As someone who has no Script-writing experience, I only come on here to comment on policy which is ever-changing, so ignore me if I'm wrong here... but can't the CAF be used as a CSR without an interview? I've heard many other people say the interview is required too, but according to the random PQ I wrote down, from 2012, it doesn't seem to be. (PQ 11874)  I like random PQs... they let me get away with things.

**Comment by theVKC** [comment]
I believe we just did something like this. @CDPotter, can you jump in on this convo?

**Comment by CDPotter** [comment]
I believe @Farleight is right about not needing to do an interview if you get a CAF for a 6 mo renewal.

I'd worry about adding more check boxes to the closed progs script as there are many who are unsure what check box causes what to populate in the case note.

**Comment by theVKC** [comment]
Agreed on the more checkboxes concern. And I can also confirm that a CAF is acceptable in place of a CSR for a six-month renewal. We may not like it, but we have to take it.


Caution: This e-mail and attached documents, if any, may contain information that is protected by state or federal law. E-mail containing private or protected information should not be sent over a public (nonsecure) Internet unless it is encrypted pursuant to DHS standards. This e-mail should be forwarded only on a strictly need-to-know basis. If you are not the intended recipient, please: (1) notify the sender immediately, (2) do not forward the message, (3) do not print the message and (4) erase the message from your system.

**Comment by theVKC** [comment]
Closing due to lack of interest.
