### ISSUE TITLE
APPL case note template which contains option to send info to database

### ISSUE THREAD

**Issue by theVKC** [MN-Script-Team/DHS-MAXIS-Scripts#608]
Following various county meetings I've attended, I feel this would be helpful: a script which case notes that an APPL was done, and who was assigned the case. That part is pretty boring, but the cool part will be the option to send this info to an Access database. I'm betting counties would love a database of all of the APPLs, the date APPL'd, the time, the program applied for, the case number, and the worker assigned. Just a little.

Also, I'm on this.

**Comment by courtrightd** [comment]
It would be a nice future enhancement to add expedited tracking to this database, that is written to by the expedited screening tool.

**Comment by theVKC** [comment]
@C-Love has volunteered to take this one on. Booyah!

**Comment by theVKC** [comment]
This script went live a while ago.
