### ISSUE TITLE
2nd MAXIS check on CAF

### ISSUE THREAD

**Issue by CDPotter** [MN-Script-Team/DHS-MAXIS-Scripts#611]
I had a worker report and issue where she wrote a long detailed CAF note and after clicking ok on the dialog she had been passworded out and lost all her work. I've submitted a fix for this using the new check_for_maxis function with a FALSE variable allowing for looping to preserve the worker's note. (It has been tested)

**Comment by theVKC** [comment]
Resolved with #610.
