### ISSUE TITLE
Dialog documentation for creating dynamic dialogs

### ISSUE THREAD

**Issue by theVKC** [MN-Script-Team/DHS-MAXIS-Scripts#632]
Training, documentation, whatevs. @RobertFewins-Kalb volunteered. Boo-yah.

**Comment by theVKC** [comment]
@RobertFewins-Kalb, I believe you finished this. Can you confirm? My SIR access is weird today.

**Comment by theVKC** [comment]
@RobertFewins-Kalb, status?

**Comment by RobertFewins-Kalb** [comment]
No update. Not done. <frowny face>

**Comment by RobertFewins-Kalb** [comment]
frowny face

**Comment by theVKC** [comment]
@RobertFewins-Kalb any word on this?

**Comment by RobertFewins-Kalb** [comment]
Zero progress

**Comment by theVKC** [comment]
I think we're going to need this before we start Project Gorbachev. Perhaps you and I can work on it together sometime?

**Comment by theVKC** [comment]
@RobertFewins-Kalb sent what he has to me, and I'm reassigning it to myself to complete.

**Comment by theVKC** [comment]
This is not a script. It's documentation. I wrote it down on my to-do list, so I'm closing it here.
