### ISSUE TITLE
BULK - REVW/MONT closures can't handle PRIV cases in banks

### ISSUE THREAD

**Issue by courtrightd** [MN-Script-Team/DHS-MAXIS-Scripts#646]
When the script is run on a case bank, it errors out and stops when it hits a priv case that the worker doesn't have access to.  Major problem when it is case number 156 of 640. I'm thinking add logic to read screen on each case for the PRIV error message, if yes then dump case number to a file and skip to the next one.

**Comment by theVKC** [comment]
You want it?

**Comment by courtrightd** [comment]
I knew that was coming, so sure, I’ll take it.

**Comment by theVKC** [comment]
Oops re: closure

**Comment by theVKC** [comment]
I forgot that this hasn't been imported. Closed too soon.
