### ISSUE TITLE
approved programs update for MFIP housing grant and child support disregard

### ISSUE THREAD

**Issue by IlseFerris** [MN-Script-Team/DHS-MAXIS-Scripts#653]

**Comment by IlseFerris** [comment]
I've got this

**Comment by theVKC** [comment]
Tagged this as policy because the process is specifically indicated by DHS.

**Comment by courtrightd** [comment]
Not sure if you are aware, but currently when autofilling MFIP approvals, the script is case noting the housing grant in both the MFIP- food line and the housing grant line.

**Comment by theVKC** [comment]
@IlseFerris is out for the week. Is it not supposed to be? This was her script and I had little to do with it.

**Comment by theVKC** [comment]
So @RobertFewins-Kalb fixed the housing grant issue, I believe. Can we confirm that this is resolved? Is it doing anything new with the Child Support Disregard?

**Comment by theVKC** [comment]
@RobertFewins-Kalb bump. Was this resolved in your latest pull request?

**Comment by theVKC** [comment]
So I'm thrown off because I'm thinking about two different scripts. @RobertFewins-Kalb, did you fix this one yet?

**Comment by RobertFewins-Kalb** [comment]
The approved programs issue has not been resolved -- there needs to be a DateDiff comparison like we did for our BUSI custom function mod

**Comment by theVKC** [comment]
We need this ASAP. Do you have time @RobertFewins-Kalb?

**Comment by RobertFewins-Kalb** [comment]
On it

**Comment by IlseFerris** [comment]
Whoops, sorry about that.  @RobertFewins-Kalb if you need help let me know (although you are much more skilled than I).  Most likely working tomorrow in addtion to today.  # vacationisover

**Comment by RobertFewins-Kalb** [comment]
No worries. I'm just going to borrow something we did for BUSI. Because the MFIP ELIG screens for 06/15 and 07/15, there needs to be a If DateDiff("D", benefit_month, date) > 0 THEN ...

**Comment by IlseFerris** [comment]
Perfect!  Thanks for cleaning up my mess :?

**Comment by RobertFewins-Kalb** [comment]
#CollaborationForLife

**Comment by RobertFewins-Kalb** [comment]
Resolved with Pull Request #672

**Comment by IlseFerris** [comment]
Seriously looks awesome!

**Comment by RobertFewins-Kalb** [comment]
#RFKComeBack

**Comment by RobertFewins-Kalb** [comment]
#100thCommit

**Comment by theVKC** [comment]
Closing because OMG. Thank you @RobertFewins-Kalb. Isn't this fun?

**Comment by RobertFewins-Kalb** [comment]
Fucking kill me

**Comment by IlseFerris** [comment]
I'll second that!
