### ISSUE TITLE
MFIP/DWP FIATer for child support disregard

### ISSUE THREAD

**Issue by IlseFerris** [MN-Script-Team/DHS-MAXIS-Scripts#655]
@theVKC  and @CDPotter 

approved programs update done (workers should be using the FIATer and the approved programs together just as an FYI)

**Comment by theVKC** [comment]
So, we need a lead on this. @CDPotter, are you in? @IlseFerris is out this week.

**Comment by CDPotter** [comment]
I could give it a shot, we need to case note any MFIP grants and that child support was FIAT'ed? Also is there any way to get the Bluth cases from Ilse so I have an MFIP training case to work with?

**Comment by theVKC** [comment]
Well @IlseFerris took care of Approved Progs, we just need the MFIP/DWP FIATer built and committed. I believe this is what you two were working on at Hackathon Thursday, right? It's FIAT and note as I recall, but I wasn't involved with that script.

**Comment by CDPotter** [comment]
Ah ok, title threw me for a loop. Yeah we had hit a bit of a stall with it trying to figure out the best way to use the 3d array to find the specific person and deduct the correct amount. Depending on case work this week I'll try to take a crack at it.

**Comment by CDPotter** [comment]
So we ran into an issue with DWP.

The instructions suggest that you FIAT for each child rec'ing CS. However the only way to determine which member you're editing is to convert their name into a 15 character string with a possible ", " thus a 13-15 character last name makes it so you can't find any HH members, and a 12 character last name will only leave the first letter of the first name(making it difficult for HHs with matching first initials)

Our questions we'd like to pose to DWP people is does it really matter where we put in the disregard? Couldn't we just calculate what the correct disregard is based on the children receiving child support and fiat it into one person's unearned income field? Would the results not be the same?

**Comment by courtrightd** [comment]
Although it may achieve the same results, it may not generate a correct notice or be technically correct.   Could you do something with assigning a number to the household members based on their place in the household member list / array, then transmit that many times on the unearned income popup?

**Comment by theVKC** [comment]
@CourtrightD, I had the same thought.


Caution: This e-mail and attached documents, if any, may contain information that is protected by state or federal law. E-mail containing private or protected information should not be sent over a public (nonsecure) Internet unless it is encrypted pursuant to DHS standards. This e-mail should be forwarded only on a strictly need-to-know basis. If you are not the intended recipient, please: (1) notify the sender immediately, (2) do not forward the message, (3) do not print the message and (4) erase the message from your system.

**Comment by theVKC** [comment]
Not to put pressure on you, but we're going to need this in the next couple of days. If you aren't available to take it, I'd like to consider reassigning it. There's a lot of pressure to get this one done!


Caution: This e-mail and attached documents, if any, may contain information that is protected by state or federal law. E-mail containing private or protected information should not be sent over a public (nonsecure) Internet unless it is encrypted pursuant to DHS standards. This e-mail should be forwarded only on a strictly need-to-know basis. If you are not the intended recipient, please: (1) notify the sender immediately, (2) do not forward the message, (3) do not print the message and (4) erase the message from your system.

**Comment by CDPotter** [comment]
Well Robert and I were going to take a swing at it this afternoon case load allowing and I'm off on Tuesdays. We'll see what the two of us can cook up this afternoon then post it?
