### ISSUE TITLE
EOMC enhancement or variation ~ Compare initial EOMC data to actual closed cases on or after 1st of the month

### ISSUE THREAD

**Issue by ALJ10** [MN-Script-Team/DHS-MAXIS-Scripts#657]
We use the EOMC script for our HC and cash auto-close cases to help prevent the cases tied to a SWKR from closing. We want to be able to run a report  on or after the first of the month to determine what cases of those above mentioned, if any, actually closed. I know there is INAC, but that doesn't verify program(s). Copy of our latest EOMC spreadsheet was emailed to Veronica via SIR mail, per her suggestion.

**Comment by theVKC** [comment]
I'm on this one. This ties into another idea I had so this is nice. Hoping to pound it out after this week sometime, and then I'll try to make sure @ALJ10 and Crow Wing gets their hands on it to test. :)

**Comment by theVKC** [comment]
So... this obviously didn't get done, @ALJ10. We have a couple of different options:

1. Either you, or another scriptwriter, tries to take it on.
2. We close the issue.

My vote is for 1. If you'd like scriptwriter refresher training, I might be able to try and set that up. Or, we can mark it as help wanted and hope another scriptwriter takes it.

**Comment by ALJ10** [comment]
If it can be reassigned to see if a scriptwriter can work their magic on it, that would be great. If it doesn’t pan out,  that’s ok. I appreciate you keeping it on the To Do list this long and for checking on this.

I wish I could get into the scriptwriting mode. But as you know very well since you are in the same boat, there’s too many other projects that I’ve been put in charge of. I just can’t seem to dedicate any time to scriptwriting. I’m CWC’s DHS security liaison; am in charge of requesting/setting up access and orientation for new staff; and am also the system admin/first point of support for our EDMS system. At some point I would be willing to step into the scriptwriting role. I just don’t know when that will be.

Thanks again!

Amanda Jensen
Technology Coordinator/Onbase OCSA_OCWA Certified
Crow Wing County Community Services
P.O. Box 686, 204 Laurel Street
Brainerd, MN 56401
Office:  (218) 824-1235
Fax:     (218) 824-1141
www.crowwing.us<http://www.crowwing.us/>
[http://mn-crowwingcounty.civicplus.com/DocumentCenter/View/5692]
Our Vision: Being Minnesota’s favorite place.
Our Mission: Serve well. Deliver value. Drive results.
Our Values: Be responsible. Treat people right. Build a better future.

Let me know how I am doing. Take a moment to fill out this survey by "Clicking Here".<https://www.surveymonkey.com/r/CommunityServiceLeadership>

**Comment by theVKC** [comment]
Sounds good. I'm going to keep this as help wanted for a week, and we'll see if there're any takers. After that, I'll close it.

**Comment by courtrightd** [comment]
I would be willing to take this on - did either of you have a plan as to how to go about saving the data for comparison or the mechanics of the script?  My thought is to add a checkbox that saves the initial spreadsheet in the scripts directory, then a new script that lets a worker choose which spreadsheet to check after 1st of month and then looks up the  data from the sheet case by case.

**Comment by theVKC** [comment]
That's what I had in mind.

**Comment by courtrightd** [comment]
I need some help on this.  I'm working on a dialog to choose the Excel file to look at after the 1st of the month. I was trying to create an FSO to look at the contents of a folder, pull all .xlsx files into array, and populate them into a dropdown using the convert_array_to_droplist function.  It works great everywhere except the obvious place for this folder; "my documents".  Windows prevents the script (permission denied error) from collecting all the filenames in My Documents (but not other folders).  I would like users to keep their own files on a local machine, as putting them in the default scripts directory would quickly get messy.  Suggestions of where to instruct users to save files?  Or does anyone have a browse file dialog that runs under BZSH?  Or???

**Comment by theVKC** [comment]
I believe there is a reserved keyword for My Documents, as modern Windows lets you map it to several locations. I don't recall how @RobertFewins-Kalb did it for the worker signature script, but perhaps he can shed some light?

**Comment by courtrightd** [comment]
So, I think I have a solution - it works fine in subfolders, so either there is some corrupted file in my My Documents folder, or I can just place the files in their own subfolder.

**Comment by courtrightd** [comment]
Before you ask @theVKC , I have been working on this, and will get it wrapped up once boardwalk is finished.

**Comment by theVKC** [comment]
Thank you!

**Comment by theVKC** [comment]
Hey @courtrightd! Any update on this one?

**Comment by courtrightd** [comment]
Uggh.  Sometimes I think I looked at something 2 days ago, and in reality it was 2 months.  I have it mostly done, so I better finish it rather than have you close it.  Won’t make February release though.

**Comment by theVKC** [comment]
Sounds good. Just keep me posted.

**Comment by theVKC** [comment]
I'm tagging this for the March release. If that doesn't end up working, let me know. :)

**Comment by courtrightd** [comment]
This is finally working.  Does it belong in BULK or UTILITIES?

**Comment by theVKC** [comment]
I'd call it BULK like a list. FYI, we'll be rebuilding the BULK MAIN MENU to utilize my new automatic-dialog-generation functionality from NOTES. You may want to wait on uploading it until after hackathon when we've worked this stuff out.

**Comment by courtrightd** [comment]
I will do that.
