### ISSUE TITLE
Add to DAIL scrubber: update last grade completed

### ISSUE THREAD

**Issue by theVKC** [MN-Script-Team/DHS-MAXIS-Scripts#658]
So, the way I see it, it should probably send something to the client, right? Or perhaps if it's not needed it should delete the message? Could this be bulked (meaning it sends a MEMO to all clients affected)? Thoughts gang? My family experience is lacking so I'm going to tag a few folks on this:

@courtrightd 
@LaLarson 
@ramonalisa1

**Comment by LaLarson** [comment]
Sheila and I were just discussing this, and we think that maybe the most helpful thing it could do is just identify if they potentially graduated from high school, and then tell the worker to be sure and assess the case for changes in ABAWD, MFIP/DWP eligibility, and counting of income. For all the other grades it can probably just delete them, or case note and delete them. :)

**Comment by courtrightd** [comment]
Our MFIP team concurs, a case note to update the info at recert and delete the dail, and the potential grad check sounds about right.

**Comment by theVKC** [comment]
Sounds great! Anyone want to take a crack at it? Perhaps at hackathon in Rochester this month?

**Comment by theVKC** [comment]
@courtrightd, are you interested in doing this one at all?

**Comment by courtrightd** [comment]
Sure, I’ll take it.

**Comment by theVKC** [comment]
@courtrightd, bump. Is this coming along at all?

**Comment by courtrightd** [comment]
Haven’t started it.  Per the discussion it isn’t going to do anything other than case note the dail, as there is a different PEPR for MEMB Turned 18 check grad date or something like that.  If someone else wants it they can have it.

**Comment by theVKC** [comment]
Removing issue, there is no time at present to develop this.
