### ISSUE TITLE
ACTIONS - CS DISREGARD FIAT: needs comments in code. Lots of them.

### ISSUE THREAD

**Issue by theVKC** [MN-Script-Team/DHS-MAXIS-Scripts#664]
There's a serious lack of comments in this code. So serious that I wouldn't be releasing it if not for the urgency of this new process.

I believe this was built by:

* @IlseFerris 
* @CDPotter 
* @GayS 
* @RobertFewins-Kalb 

One of you should comment this thoroughly. Who wants it?

**Comment by RobertFewins-Kalb** [comment]
I can do that tonight and build the instructions tomorrow.

We omitted the documentation onaccounta the time frame.

**Comment by theVKC** [comment]
@CDPotter already called the instructions. But the comments are very helpful.


Caution: This e-mail and attached documents, if any, may contain information that is protected by state or federal law. E-mail containing private or protected information should not be sent over a public (nonsecure) Internet unless it is encrypted pursuant to DHS standards. This e-mail should be forwarded only on a strictly need-to-know basis. If you are not the intended recipient, please: (1) notify the sender immediately, (2) do not forward the message, (3) do not print the message and (4) erase the message from your system.

**Comment by RobertFewins-Kalb** [comment]
Deal.
