### ISSUE TITLE
MEMOS - Appointment letter: should have logic for the county addresses independent of GlobVar

### ISSUE THREAD

**Issue by theVKC** [MN-Script-Team/DHS-MAXIS-Scripts#666]
I think that makes a lot more sense with scriptwriters working in counties that aren't Anoka. I'd like them to be able to simply enter their county and voila. Address logic.

Plus, it's far less error prone for our end users, many of whom struggle with the installer.

On it. Already asked counties to start sending me their stuff.

**Comment by RobertFewins-Kalb** [comment]
THE ISSUE OF THE BEAST

**Comment by theVKC** [comment]
WHY DID I HAVE TO ALREADY NAME A PROJECT CERBERUS?????



Operation Hades?


Caution: This e-mail and attached documents, if any, may contain information that is protected by state or federal law. E-mail containing private or protected information should not be sent over a public (nonsecure) Internet unless it is encrypted pursuant to DHS standards. This e-mail should be forwarded only on a strictly need-to-know basis. If you are not the intended recipient, please: (1) notify the sender immediately, (2) do not forward the message, (3) do not print the message and (4) erase the message from your system.

**Comment by Farleight** [comment]
Operation Robby Benson.

**Comment by theVKC** [comment]
The dude who played the Beast in Beauty and the Beast? Who auditioned for Luke Skywalker? No, I didn’t just look him up on Wikipedia.


Caution: This e-mail and attached documents, if any, may contain information that is protected by state or federal law. E-mail containing private or protected information should not be sent over a public (nonsecure) Internet unless it is encrypted pursuant to DHS standards. This e-mail should be forwarded only on a strictly need-to-know basis. If you are not the intended recipient, please: (1) notify the sender immediately, (2) do not forward the message, (3) do not print the message and (4) erase the message from your system.

**Comment by Farleight** [comment]
Ha. That's the one... I didn't know he auditioned for Skywalker though.
