### ISSUE TITLE
Approved Programs -- Need date check for case noting MFIP housing grant

### ISSUE THREAD

**Issue by RobertFewins-Kalb** [MN-Script-Team/DHS-MAXIS-Scripts#668]
IF a worker runs the Approved Programs script in a month PRIOR to 07/15 the script is still case noting that there is a housing grant...when there isn't one. I can take a crack at fixing it.

**Comment by theVKC** [comment]
Did you fix this in most recent pull req?

**Comment by RobertFewins-Kalb** [comment]
I did not. I just noticed it now

**Comment by theVKC** [comment]
Resolved by #672.
