### ISSUE TITLE
NOTES - Approved programs: need to comment out the WCOM check for CS disregard

### ISSUE THREAD

**Issue by theVKC** [MN-Script-Team/DHS-MAXIS-Scripts#673]
@IlseFerris, can you do this? Maybe you're already on it. I know you built this and it needs to be done ASAP. What a day.

**Comment by RobertFewins-Kalb** [comment]
I can do it from the version that I am pull requesting

**Comment by RobertFewins-Kalb** [comment]
Done. Anybody want to get a beer...like right now?

**Comment by IlseFerris** [comment]
Thank you!  I'm in meetings all day.  # inameetingnow

**Comment by IlseFerris** [comment]
OMG I wish!

**Comment by theVKC** [comment]
@RobertFewins-Kalb, already updated? I don't see it.

**Comment by theVKC** [comment]
Found it.
