### ISSUE TITLE
SNAP sanction script request

### ISSUE THREAD

**Issue by IlseFerris** [MN-Script-Team/DHS-MAXIS-Scripts#675]
Hennepin county SNAP mentors are requesting a sanction script.  Here's the verbiage that they use now.
***ABAWD Sanction -  Ist/2nd 3rdOccurence***                                         
Memb __ has not cooperated with E & T Services.  Client is ineligible for     
SNAP for one month or until date of compliance, whichever is longer.         
WREG updated.                                                                 
SNAP closed eff __/__.                                                        
Name/Region     

Any thoughts?  link to CM 
http://www.dhs.state.mn.us/main/idcplg?IdcService=GET_DYNAMIC_CONVERSION&RevisionSelectionMethod=LatestReleased&dDocName=cm_00283006

**Comment by theVKC** [comment]
Hey @ruthmaloney, any thoughts on this?

**Comment by theVKC** [comment]
Also @IlseFerris, are you thinking a NOTE or ACTION script? And also also, do you want to do this one, or have it marked as "help wanted"?

**Comment by ruthmaloney** [comment]
Can you add in a spot for the date? Not sure if it would be better to have the date the client was found to be in sanction or the date the worker received the notice from E&T provider. Counties that are behind in processing tend to give extra months of benefits without looking at overpayments when they do this.

**Comment by IlseFerris** [comment]
We could add any number of things to the script.  Does DHS have a template that is avaialble for workers, or that they would like workers to use? @ruthmaloney, I'd love to work with you on this one!

**Comment by ruthmaloney** [comment]
I'm not aware of any template available. That would be nice though.

Is this script strictly for ABAWDS? Not sure if it matters or not...

It would be nice to have a couple of things added:
- Is the sanctioned member the PWE?
- Date the agency received the sanction notice from E&T provider
- A way to choose if it's the first, second, or third (+) sanction, along with the correct corresponding sanction time requirements
- The manual reference. CM 0028.30.06.

**Comment by IlseFerris** [comment]
@ruthmaloney Are there any more sanction reasons for SNAP besides the following:
Failed to attend SNAP overview
Failed to accept suitable employment w/o good cause
Voluntarily quit suitable employment w/o good cause
Voluntarily reduced work hours w/o good cause

**Comment by ruthmaloney** [comment]
Here’s what the CM says:
The following provisions apply to non-PA mandatory SNAP E&T participants who fail to participate, cooperate, accept employment, voluntarily quit suitable employment, or voluntarily reduce work hours while participating in SNAP E&T. When a mandatory participant fails, without good cause, to comply with SNAP E&T requirements, determine if you must sanction only the client or the entire unit.

Can you change the “Failed to attend SNAP overview” to “Failed to comply with SNAP E&T requirements”?

Ruth Maloney

**Comment by IlseFerris** [comment]
I changed the wording to “Failed to comply with SNAP E&T requirements” in the droplist.  Ruth, I have a version almost ready to test if you want to see it.  And yes, @theVKC assign it to me if it hasn't been assigned already
