### ISSUE TITLE
LTC intake approval script issue with 'application date'

### ISSUE THREAD

**Issue by IlseFerris** [MN-Script-Team/DHS-MAXIS-Scripts#684]
Looks like the edit box is not descriptive enough.  Needs to refer users to update the baseline date instead of the application date.  Also has some updating to do.

Oh, and I got this.

**Comment by theVKC** [comment]
Good luck @IlseFerris!

**Comment by theVKC** [comment]
Marking as critical because there was some functional problems with it...
