### ISSUE TITLE
Bug HC renewal

### ISSUE THREAD

**Issue by CDPotter** [MN-Script-Team/DHS-MAXIS-Scripts#685]
If you hit cancel on the HC renewal script it doesn't actually cancel. It re-reads all the panels and opened the dialog again.

**Comment by theVKC** [comment]
Is it using my cancel_confirmation function?


Caution: This e-mail and attached documents, if any, may contain information that is protected by state or federal law. E-mail containing private or protected information should not be sent over a public (nonsecure) Internet unless it is encrypted pursuant to DHS standards. This e-mail should be forwarded only on a strictly need-to-know basis. If you are not the intended recipient, please: (1) notify the sender immediately, (2) do not forward the message, (3) do not print the message and (4) erase the message from your system.

**Comment by CDPotter** [comment]
It looks like it is commented out.

**Comment by theVKC** [comment]
Wonder how that happened?

**Comment by theVKC** [comment]
Resolved with #686.
