### ISSUE TITLE
EXP SNAP defaults to 0 if dialog fields left blank

### ISSUE THREAD

**Issue by IlseFerris** [MN-Script-Team/DHS-MAXIS-Scripts#692]
Do you think we should update the script to make a worker enter 0 if there is no $0 income/$0 assets/$0 shelter costs? I was thinking that maybe this would be less error prone.  Thoughts?  Also I would be willing to update this.

**Comment by theVKC** [comment]
This was by design, actually, suggested by some state folks a while ago. What might be helpful would be text that explains that blanks will be considered zeros.

**Comment by theVKC** [comment]
@IlseFerris, would you be interested in updating the dialog to explain that blank will equal zero? We can't really change it, because that's how we wanted it a while ago (and I think it might be best to "lean toward expedited" to avoid incorrectly saying something _isn't_ expedited).

**Comment by IlseFerris** [comment]
You know it!  Also I updated the instructions on this one already https://www.dhssir.cty.dhs.state.mn.us/MAXIS/blzn/scriptwiki/Wiki%20Pages/Expedited%20screening.aspx

**Comment by theVKC** [comment]
#woot!

**Comment by IlseFerris** [comment]
this one can be closed (yay!)
