### ISSUE TITLE
appeal case note template

### ISSUE THREAD

**Issue by IlseFerris** [MN-Script-Team/DHS-MAXIS-Scripts#694]
> > APPEAL SUMMARY COMPLETED and taken to Appeals Office. <<
> > Date appeal request rec'd: **/**/**.  
> > Effective date of action being appealed: __/**/__.  
> > Action clt is appealing:  
> > Benefits continuing at pre-appeal level (Y/N):             

requested by Hennepin County.  Any feedback on this?

**Comment by theVKC** [comment]
Love it. Do you want this one? Might be good to get some feedback from some folks who do appeals. A few of our Anoka friends do that, and I'm sure folks in other counties know folks too...

**Comment by IlseFerris** [comment]
Of course I'll take it!  And yes, I was thinking that same thing

**Comment by CDPotter** [comment]
Per PCs here at Anoka they like it but maybe have a drop down box so people can select between taken to, faxed, mailed? We here at Anoka fax in our docs.

**Comment by theVKC** [comment]
I like that idea, myself.

**Comment by IlseFerris** [comment]
I like that too. @ruthmaloney anything you'd like to see on an appeal case note template?

**Comment by ruthmaloney** [comment]
To add what program/s they are appealing.

**Comment by theVKC** [comment]
@IlseFerris doesn't have loads of time for this at the moment. Any takers?

**Comment by theVKC** [comment]
Removed due to lack of interest.

**Comment by ALJ10** [comment]
A financial worker (and supervisor) are expressing interest in this same appeal script. So we are wondering if it could be opened up again to see if there could be further discussions/interest in creating it. Worker had a few suggestions to expand the script a bit: add a box to be able to cite manual references and policies that were used in the decision that is being appealed. Also, the first line could be listed as “APPEAL SUMMARY COMPLETED and sent to the Appeals Office”. Please let me know if this will be opened up for further discussions. Thank you!

**Comment by CDPotter** [comment]
Glad to re-open it. Any takers/interest in seeing this?

**Comment by IlseFerris** [comment]
@senhorc was working on an appeals case note. This can be assigned to him for the November release.

**Comment by CDPotter** [comment]
@senhorc Suggestions to consider when building this:

A financial worker (and a supervisor) are wondering if there could be discussions in the possibility of having a script for when an appeal hearing is scheduled. Worker thought it could include the date of the appeal hearing, if it's via phone or in person, the time, the docket number, the Judge’s name, the appeals phone number, and a notes box to add any other info that might be needed. Please let me know if there's interest in having discussions on this idea. Thank you!

A financial worker (and a supervisor) are wondering if there could be discussions in the possibility of having an Appeal Decision script. Worker thought it could include if the judge upheld or overturned the county's decision and actions needed/taken on the case. Please let me know if there's interest in having discussions on this idea. Thank you!

**Comment by CDPotter** [comment]
Let's pre-enhance this one to include the dynamic dialog calling(declaring the dialog just before calling it and naming them all "dialog") since it's using 5 dialogs on it's own in it's pre-release form.

**Comment by CDPotter** [comment]
@MN-Script-Team/maxis-scriptwriters this is out in Master now, Could I get a few agencies confirming it's working and testing each path on it?

**Comment by IlseFerris** [comment]
Confirmed, working in the master branch

**Comment by C-Love** [comment]
Appears to be working in master

**Comment by CDPotter** [comment]
In RELEASE note, there are instructions on SIR. Thanks!
