### ISSUE TITLE
MFIP sanction bug fix

### ISSUE THREAD

**Issue by IlseFerris** [MN-Script-Team/DHS-MAXIS-Scripts#700]
script_end_procedure needed to be updated.

hey look, it's updated!

**Comment by theVKC** [comment]
Resolved with #699.

**Comment by CDPotter** [comment]
@IlseFerris Was this the bug that causes a "no outcome in the script" message?

**Comment by IlseFerris** [comment]
I believe so.  I was looking for the exact Msgbox message.  I'll post it when I find it.

**Comment by CDPotter** [comment]
Ok, I just wanted to check since someone asked on SIR and it looks like it was fixed in MASTER/BETA but hasn't been released to RELEASE yet. I just wanted to make sure I let them know the correct info.
