### ISSUE TITLE
Interest gauging: BULK BGTX-er

### ISSUE THREAD

**Issue by CDPotter** [MN-Script-Team/DHS-MAXIS-Scripts#701]
Hello all, one of our GRH workers asked me for a fairly simple script last week. Something that allows her to run a bulk batch of cases(given to her by a GRH facility) through background. Would anyone be interested in this script? Basically works like returned mail but STAT BGTX's a bunch of cases entered into the dialog.

**Comment by CDPotter** [comment]
For clarification the reason being she gets a long GRH post pay list for a specific facility and the cases with no income no assets really only need to be sent through background before review and possibly approval.

**Comment by IlseFerris** [comment]
Does she get this as an Excel document?

**Comment by CDPotter** [comment]
Yes but it also contains people who may need a bit of work before BGTXing.

**Comment by CDPotter** [comment]
Gonna close due to lack of interest for the time being.
