### ISSUE TITLE
CAF Script/func file DCEX read

### ISSUE THREAD

**Issue by CDPotter** [MN-Script-Team/DHS-MAXIS-Scripts#705]
Currently the autofill editbox for DCEX only looks at the first panel. This would mean that any case with multiple DCEX panels have not been getting the 2nd (or more) panels case noted when using this function. I can update the logic in the functions file.

**Comment by theVKC** [comment]
Can you move this issue over to the FuncLib repo, if you haven't already? Thanks @CDPotter!
