### ISSUE TITLE
REVS scrubber needs comments, people

### ISSUE THREAD

**Issue by theVKC** [MN-Script-Team/DHS-MAXIS-Scripts#712]
I'm looking at @RobertFewins-Kalb, @CDPotter, and maybe @courtrightd for help here.

**Comment by CDPotter** [comment]
I can work on commenting this evening.

**Comment by RobertFewins-Kalb** [comment]
I can continue this today

**Comment by RobertFewins-Kalb** [comment]
Also, a Comment: I think the structure needs revision. When I tested this for @mldietz  for 08/15, I noticed that there are holes in the calendar. Let me esplain...

Currently, the REVS Scrubber...
(1) grabs all cases with FS = "N" in REPT/REVS for CM + 02 and dumps those cases in Excel. 
(2) Then the REVS Scrubber creates appointment times/dates for those cases.
(3) Then the REVS Scrubber goes in to STAT/REVW for each case, and removes the cases from the list that are CSR (leaving the SNAP ER remaining).
(4) Then the REVS Scrubber creates MEMOs, CASE NOTEs, TIKLs and (optional) Outlook Appointments.

My proposal is this...
(1) The REVS Scrubber goes into REPT/REVS for CM + 02 and grabs all cases coded FS = "N", dumping those cases into Excel.
(2) Then the REVS Scrubber goes into STAT/REVW for those cases, eliminating the ones coded CSR (vs. ER).
(3) Then the REVS Scrubber creates appointment times for the cases that are left.
(4) Then the REVS Scrubber creates MEMOs, CASE NOTEs, TIKLs, and (optional) Outlook Appointments.

Creating appointment times and dates AFTER eliminating all the CSRs would keep the appointment schedule more concise. Thoughts?

**Comment by IlseFerris** [comment]
Yikes, great catch Robert!  I agree, it should take out the non-recert cases prior to scheduling, otherwise we are not providing the service that the REVS scrubber is supposed to provide.

**Comment by RobertFewins-Kalb** [comment]
I'm working on the mod while I add documentation.

**Comment by RobertFewins-Kalb** [comment]
Actually...there's not much documentation that needs to be added. @CDPotter  did a great job yesterday

**Comment by theVKC** [comment]
Please create a new issue for the above discussion.
