### ISSUE TITLE
Mic drop: enable developer mode with Konami Code

### ISSUE THREAD

**Issue by theVKC** [MN-Script-Team/DHS-MAXIS-Scripts#713]
"Developer mode" will allow you to enter an array of case numbers manually for testing purposes, bypassing the logic to actually check REVS. Did either @CDPotter or @RobertFewins-Kalb do similar functionality already?

**Comment by CDPotter** [comment]
We did not add any developer mode to it. We've just been manually editing the code that does things.

**Comment by theVKC** [comment]
Added: https://github.com/theVKC/VKC-Script-Changes/commit/3ecc29c10aecb0fd51bcdf38cf905a8a46086360
