### ISSUE TITLE
DAIL scrubber- New hire Last 4 SSN request verified

### ISSUE THREAD

**Issue by RoyStearns** [MN-Script-Team/DHS-MAXIS-Scripts#715]
We had issues come up where we get a new hire for a person but since the SSN gets cleared in case notes we have no way of knowing if the match was actually for that person or if it was an SSN typo. 
I see in the script that it is matching the SSN but the worker does not know that without being able to read "script". 
Supervisor asked me to request that the last 4 be added back into case notes. 
I am assuming that the SSN gets cleared due to FTI?
If we cannot have the last 4 of SSN in case notes- can there be a note to say the SSN was matched? Or should we be instructing the workers to just trust it?

**Comment by theVKC** [comment]
Instruct the workers to trust it. You can’t address it in case notes. FTI.

**Comment by lpshanley** [comment]
Could a message box be added at the end that would simply show the SSN that was used so the worker can compare it? This would make it show the worker the SSN and it would leave the SSN in the case note as is. Could be a win-win ☺

-Lucas
“Valar dohaeris”
#DecimateTheErrorRate
P Please consider the environment before printing this email. P

**Comment by theVKC** [comment]
This area is a very sensitive subject with data security. When it comes to that, we're better off steering clear of the controversy. Especially right now, for reasons I shouldn't share at the moment.
