### ISSUE TITLE
Reconsider the structure of the REVS Scrubber

### ISSUE THREAD

**Issue by RobertFewins-Kalb** [MN-Script-Team/DHS-MAXIS-Scripts#716]
I think the structure needs revision. When I tested this for @mldietz for 08/15, I noticed that there are holes in the calendar. Let me esplain...

Currently, the REVS Scrubber...
(1) grabs all cases with FS = "N" in REPT/REVS for CM + 02 and dumps those cases in Excel. 
(2) Then the REVS Scrubber creates appointment times/dates for those cases.
(3) Then the REVS Scrubber goes in to STAT/REVW for each case, and removes the cases from the list that are CSR (leaving the SNAP ER remaining).
(4) Then the REVS Scrubber creates MEMOs, CASE NOTEs, TIKLs and (optional) Outlook Appointments.

My proposal is this...
(1) The REVS Scrubber goes into REPT/REVS for CM + 02 and grabs all cases coded FS = "N", dumping those cases into Excel.
(2) Then the REVS Scrubber goes into STAT/REVW for those cases, eliminating the ones coded CSR (vs. ER).
(3) Then the REVS Scrubber creates appointment times for the cases that are left.
(4) Then the REVS Scrubber creates MEMOs, CASE NOTEs, TIKLs, and (optional) Outlook Appointments.

Creating appointment times and dates AFTER eliminating all the CSRs would keep the appointment schedule more concise. Thoughts?

**Comment by theVKC** [comment]
Agreed! I presume you're on it, @RobertFewins-Kalb?

**Comment by RobertFewins-Kalb** [comment]
I'm going to close this issue. We have already done that.
