### ISSUE TITLE
BOLO agreeing to SSA information (BNDX scrubber)

### ISSUE THREAD

**Issue by CDPotter** [MN-Script-Team/DHS-MAXIS-Scripts#717]
(Be on the look out)

So this morning we had an issue with the scrubber where a worker hadn't renewed their INFC access. We resolved it by having her renew it but we didn't think to grab a screenshot until we finished troubleshooting.

 If anyone has a screenshot for what the screen looks like we would love to incorporate some safe guards into the bndx scrubber.

**Comment by theVKC** [comment]
I'm going to see if I can get access to this screen in a lab environment when I get back from vacation.

**Comment by CDPotter** [comment]
One has been found at Anoka. We will work on a fix in July after freeze.

**Comment by theVKC** [comment]
Great!

**Comment by theVKC** [comment]
I suppose this also affects SVES/QURY?

**Comment by CDPotter** [comment]
It most definitely would. We had a PC here find the screen and got a shot and coordinates so it's just a matter of programming it now.
