### ISSUE TITLE
Critical bug - LTC Intake approval error on case noting

### ISSUE THREAD

**Issue by courtrightd** [MN-Script-Team/DHS-MAXIS-Scripts#719]
Script is getting a wrong number of arguments error on writing the case note, I've got the fix, will pull.

**Comment by RobertFewins-Kalb** [comment]
i already submitted a pull request for this

Sent from my iPhone

On Jun 17, 2015, at 9:05 AM, David Courtright <notifications@github.com<mailto:notifications@github.com>> wrote:


Script is getting a wrong number of arguments error on writing the case note, I've got the fix, will pull.

-
Reply to this email directly or view it on GitHub<https://github.com/MN-Script-Team/DHS-MAXIS-Scripts/issues/719>.



Click here<https://www.mailcontrol.com/sr/C!mVzcR4pB7GX2PQPOmvUkyXKmclf+CP7lLrygCVXDv4oiTuzHEtNz4T73rUrgwUTvmUjtxxLKQeRLY+cWrx9g==> to report this email as spam.


NOTICE: Unless restricted by law, email correspondence to and from Anoka County government offices may be public data subject to the Minnesota Data Practices Act and/or may be disclosed to third parties.

**Comment by courtrightd** [comment]
Oops - trying to work fast between intakes, I didn't check for an issue.  Please close this, I'll cancel my pull.

**Comment by RobertFewins-Kalb** [comment]
Sorry, I didn't create an issue. I was emailed directly

**Comment by theVKC** [comment]
Opening this issue to reflect @RobertFewins-Kalb closed it.
