### ISSUE TITLE
Critical: Bulk cola scrubber GRH issue

### ISSUE THREAD

**Issue by CDPotter** [MN-Script-Team/DHS-MAXIS-Scripts#722]
So apparently the GRH autoapproved message is INFO type and not COLA. @RoyStearns  or @RobertFewins-Kalb  Would either of you be able to look at it and account for this change since you're both more familiar with the code? (I know Robert is out today). I can email a image of the message or there are some examples in x102524

**Comment by CDPotter** [comment]
Also it seems to be reading the COLA message for the wrong case. This script is very much down.

**Comment by CDPotter** [comment]
Also MSA autoapproved is also a INFO message.

**Comment by IlseFerris** [comment]
Thanks Charles.  I will let users here know.

**Comment by IlseFerris** [comment]
Does anyone have this?  I'd say this is critical

**Comment by CDPotter** [comment]
I'm trying to work through it but it's not going smoothly or quickly.

**Comment by IlseFerris** [comment]
Thanks Charles.  You are my current hero ;D

**Comment by CDPotter** [comment]
Update: I have submitted fixes for these and they will be reviewed tomorrow. Please inform workers to not use them for the time being.

**Comment by theVKC** [comment]
@CDPotter, any update on pull requesting this to BETA and RELEASE? If I don't hear from you soon, I'll just plan on shutting it down.

**Comment by CDPotter** [comment]
I've tried to fork BETA and make the changes but I keep getting unable to merge automatically. I could have sworn I submitted another RELEASE one. I've deleted my current forks for BETA and RELEASE and am planning to submit pulls shortly.
