### ISSUE TITLE
Critical COLA 2015 summary still using 01/15

### ISSUE THREAD

**Issue by CDPotter** [MN-Script-Team/DHS-MAXIS-Scripts#723]
LTC COLA 2015 is still pulling from 01/15. @IlseFerris Should it be changed to grab from 07/15 now?

**Comment by CDPotter** [comment]
Update: I have submitted fixes for these and they will be reviewed tomorrow. Please inform workers to not use them for the time being.

**Comment by theVKC** [comment]
This has now been approved and integrated into BETA and RELEASE as well as master. Thank you @CDPotter! Feel free to close branches created to solve this issue.
