### ISSUE TITLE
PA verifs requested enhancement

### ISSUE THREAD

**Issue by IlseFerris** [MN-Script-Team/DHS-MAXIS-Scripts#733]
PA Verif Requested.  The request I get in these cases is for a date range.  Most clts need to verify a year’s worth of benefits.  It would be great if you could modify this so that we could capture the clt’s benefits for a range, rather than just one month.
Submitted by Hennepin County

**Comment by theVKC** [comment]
Any thoughts? I believe @courtrightd built this one.

**Comment by courtrightd** [comment]
I’m sure it can be done, likely just rework the code that provides the last 3 months INQX to provide the last 12 and add a checkbox.  I don’t know when I will get to working on it though.

**Comment by courtrightd** [comment]
Update - I had to look into some other minor errors in this script, so I added this functionality.  It now has an editbox to enter the number of months you want from MONY/INQX added to the word doc.  Does that sound like a workable solution?
