### ISSUE TITLE
SPEC/WCOM for used ABAWD months

### ISSUE THREAD

**Issue by IlseFerris** [MN-Script-Team/DHS-MAXIS-Scripts#735]
Great idea from Kyle A (formerly of Anoka Co, currently of Hennepin Co., that's right)
Workers send a abawd letter to clients that state about using their months:  This is an example.
This what I add to the SPEC/WCOM if client has used their ABAWD months and comes in to apply with an exemption:

Jimmy Walker has used their 3 entitled months of SNAP 
benefits as an Able Bodied Adult Without Dependents.  
Verification of Medical Opinion Form has been postponed.  
You must turn in verification of Medical Opinion Form by 
3/12/2015 to continue to be eligible for SNAP benefits.  If 
you do not turn in the required verifications, your case will 
close on 3/31/2015.

**Comment by theVKC** [comment]
I like the idea, but I'd like to hear thoughts from @ruthmaloney about it if you don't mind. Ruth, why am I thinking there's a suggested template out there for this?

**Comment by ruthmaloney** [comment]
TE 02.05.70.01 has a worker comment for postponed verifications: 
(Name) has used their 3 entitled months of SNAP benefits as an Able Bodied Adult Without Dependents. Verification of (specify verification/s needed) has been postponed. You must turn in verification of (specify verification/s needed) by (verification due date) to continue to be eligible for SNAP benefits. If you do not turn in the required verifications, your case will close on (enter date of closure).

There's more information in that POLI TEMP as well.

**Comment by CDPotter** [comment]
I think I resolved this one with the #1206 script. (based on #1180 issue) The script provides the template found in poli/temp and allows the worker to enter the needed verification(s) (it will calc the dates based on the app date) and add it in a WCOM.

**Comment by theVKC** [comment]
@IlseFerris, based on @CDPotter's comments, are you thinking we can close this?

**Comment by IlseFerris** [comment]
@CDPotter resolved it. Shut it down...woo hoo!
