### ISSUE TITLE
Enhancement request: CSR Script - exempt renewals

### ISSUE THREAD

**Issue by tdahl21** [MN-Script-Team/DHS-MAXIS-Scripts#737]
Instead of having a note just indicating the case is exempt, could we have it still develop a full casenote?

**Comment by theVKC** [comment]
You know, there's already an issue out there around this topic (#73). However, yours references a specific alternative request. Any thoughts from the group on this? I'll leave this up for a bit to get feedback, but then whatever we decide will be tacked onto the previous issue and this will close.

**Comment by theVKC** [comment]
Closing due to lack of interest. Can pursue if this is desired from a scriptwriter or policy person.
