### ISSUE TITLE
Enhancement Request: Bulk: REVW/MONT closures - Ability to skip privileged cases.

### ISSUE THREAD

**Issue by tdahl21** [MN-Script-Team/DHS-MAXIS-Scripts#738]
We try and remember to run the REVW/MONT closures script when people are gone, etc.  Sometimes we run into cases that are privileged, which causes the script to stop where it was and not continue on to other cases that need to be noted.  Is it possible to have the script skip the case it finds to be privileged  and continue on?

**Comment by courtrightd** [comment]
I added this fix to REVW/MONT, it should be in the next release.
