### ISSUE TITLE
SNAP quality review case note---Call for input

### ISSUE THREAD

**Issue by IlseFerris** [MN-Script-Team/DHS-MAXIS-Scripts#746]
Hennepin County is going to start using this.  Just want to get everyone's input about it to see if this could be used at other agencies.

A basic case note template for SNAP reviewers to use that will case note whether a SNAP quality review was correct or incorrect, and if correct, will also note the issuance amount.
What the script will do for you:
1. If in ‘STAT’ or ‘CASE’, the case number will auto-populate.
2. If a field is not complete, the user will get a pop up informing them what is missing.
3. If incorrect, you will NOT need to complete the grant amount. If correct, and the user leaves the ‘grant amount’ field blank, a pop up instructing them to complete this field will appear.
4. If the ‘incomplete’ and ‘complete’ options are selected, a pop up instructing the worker to select an option will be created.
5. A specified case note will be created: one for complete and approved, and one for an error exists.

**Comment by theVKC** [comment]
Any ideas, @ruthmaloney? So far, I have none from the SNAP side.

**Comment by ruthmaloney** [comment]
It would be good to add the month and/or action reviewed along with the approval version number. Will the reviewer be entering a description of the error found or just that a review was done on the case?
