### ISSUE TITLE
Report Active- last review completed-- idea

### ISSUE THREAD

**Issue by RoyStearns** [MN-Script-Team/DHS-MAXIS-Scripts#747]
Idea for a new script to find cases that have not had a review lately completed in Maxis.  I am just talking about HC only cases but this may apply to other cases also- not sure.

Background info- We have found a number of cases where the case has not had a revw in the last 12 months or longer (the one on my desk right now applied 6/3/13 and has never had a revw). I believe this to be an issue because of ACA but cannot prove that. F11 replies have not been helpful. 

Idea- I was thinking of a script that would look at all rept/actv cases to see when the last review was completed and or just looking to see if the case is coded as a revw for CM+1 and if there actually is a N out there for it (it would have to be run monthly this way since rept/review has been coded as a review is needed but maxis has not been populating the N in and triggering a review). It could build an Excel report of all the cases with discrepancies, old reviews.

I think this could be very useful in finding the rogue cases that Maxis seems to be dropping but also could be used for all cases where there is no tracking in Maxis- such as Breast/Cervical cases, Adoption Assistance, TYMA. If you are paperless and happen to delete a revw reminder these cases may stay open for years beyond when they should have.

I had started looking at doing this myself previously but I am not able to devote any time to it right now and was asked to pass this along to the group. 

Any thoughts?

**Comment by theVKC** [comment]
Only thing I worry about with something like this is that Data Warehouse queries would be much easier and less resource intensive. Do you have anyone in Stearns who can just ask the Data Warehouse? I believe you can request a query using SIR (could be wrong).

**Comment by theVKC** [comment]
Closing because this is better suited for a data warehouse query.
