### ISSUE TITLE
GRH Overpayment Memo

### ISSUE THREAD

**Issue by CDPotter** [MN-Script-Team/DHS-MAXIS-Scripts#748]
Few questions on this one.

1. Could we have the reason for overpayment put into the spec memo?
2. In one instance the script seems to dump the FACI_name partially into the blank line near the end of the spec memo.
3. There is code to write into MEMO in the case note section that needs to be swapped (likely causing issue above).

**Comment by IlseFerris** [comment]
I could update that.  Consider it assigned!
