### ISSUE TITLE
Dail Scrubber - New Hire change footer month enhancement

### ISSUE THREAD

**Issue by courtrightd** [MN-Script-Team/DHS-MAXIS-Scripts#749]
Modify the script to build the new JOBS panel in the footer month of the job start date, as currently they are going back and adding this manually for MFIP cases.  Also add checkbox for MFIP cases that would note closed for next month, rather than TIKL 10 days out.  (MFIP doesn't require 10 days for verif before sending closure notice.)  If there are no objections, I can work on this.

**Comment by theVKC** [comment]
How sure are we that this is policy? I can ask my MFIP contact, but I was under the impression that this depends on when the new job started, but was not typical (could be wrong).

**Comment by theVKC** [comment]
@courtrightd, did you work on this?

**Comment by courtrightd** [comment]
No, I guess I was waiting for policy clarification?  You can close it for now since we don't know if it is legit.
