### ISSUE TITLE
ERROR: LTC Intake Approval script ~ Wrong # arguments or invalid property assignment

### ISSUE THREAD

**Issue by ALJ10** [MN-Script-Team/DHS-MAXIS-Scripts#751]
Rec'd this report from a LTC worker:
We are getting this error when we use LTC Intake Approval script
“ Script Error at Line 1, Column 1:
Wrong number of arguments or invalid property assignment:
‘write_variable_in_CASE_NOTE’

**Comment by IlseFerris** [comment]
Good morning, do you know if your worker ran the script more than once, and got this error multiple times? It looks like a fix went out of this about 9 days ago.

**Comment by ALJ10** [comment]
I just verified with the worker that she did try it multiple times and rec’d the error each time. She also mentioned one of the other LTC workers rec’d the same error last week, but they thought maybe it was how the worker was using the script. So they didn’t report it to me.

Let me know if you need further details.

Thank you!

**Comment by CDPotter** [comment]
It isn't updated in release yet.

**Comment by IlseFerris** [comment]
Thanks for the update @CDPotter!

**Comment by theVKC** [comment]
@CDPotter, was this your pull request from just now? I pulled it in, but you pulled into BETA. Can you also pull to master and RELEASE please?

**Comment by CDPotter** [comment]
Yes. This can be closed now.
