### ISSUE TITLE
Check your notice warning (enhancement)

### ISSUE THREAD

**Issue by CDPotter** [MN-Script-Team/DHS-MAXIS-Scripts#753]
Had a suggestion from a supervisor that maybe we could consider adding a reminder at the end of the CAF that would tell people to check their notices make sure they read correctly, and add WCOM if needed. 

My gut says to do it on Approved/denied/closed progs, if we were to add anything. I wanted to pitch it to the crowd and see what other people thought.

**Comment by courtrightd** [comment]
I agree with Approved/denied/closed as the route with this if one is going to add it somewhere.

**Comment by theVKC** [comment]
Agreed. Frankly, if we are to put ANYTHING into the CAF script, I think it should be a warning to use approved/denied/closed programs after running the CAF. #UseTheRightToolForTheJob

**Comment by CDPotter** [comment]
So we're thinking add a reminder message box at the end of the CAF to tell people to use Approve/Closed/Denied progs as necessary, and a message box at the end of those scripts reminding people to check their notices read correctly?

**Comment by theVKC** [comment]
I concur.

**Comment by IlseFerris** [comment]
Agreed.  You got this!

**Comment by theVKC** [comment]
Do you want this, @CDPotter?

**Comment by CDPotter** [comment]
Can do.
