### ISSUE TITLE
Denied progs ehancement - add worker comments to notice

### ISSUE THREAD

**Issue by courtrightd** [MN-Script-Team/DHS-MAXIS-Scripts#754]
The thought here is to add a check box that would modify the notice when denying for verifications.  Basically have it edit the notice with something like "The following verifications were not provided:" and then it lists the contents of the "verifs needed" editbox.

**Comment by theVKC** [comment]
I love it. Do you want it?

**Comment by courtrightd** [comment]
Yes, I will take it for sure.  Is there any official input on what the wording should be for the comments?

**Comment by courtrightd** [comment]
This is working, wondering if there is any input on functionality before I pull request it in 
If the worker checks the appropriate box, it goes to SPEC/WCOM and looks for any waiting cash/snap notices in each month from application month to CM+1.  If it finds a waiting notice for SNAP / CASH with the word "proofs" on it, it adds worker comment saying "The following verifications were not provided: (lists the contents of the verifs needed editbox here)"  
If it fails to find any such notices, gives a msgbox warning the worker to check their denial reasons.
@theVKC (or anyone else) Am I missing any functionality here?  Should it be worded differently?
