### ISSUE TITLE
Work reg matrix

### ISSUE THREAD

**Issue by IlseFerris** [MN-Script-Team/DHS-MAXIS-Scripts#758]
Here's the thought...

1.	 The script will read the HH members information (name, age, member number)
2.	Compares the ‘eating group(s)’ from the EATS panel
3.	Creates a dialog for the worker with all household members listed and ‘suggested household members’ (which will be identified by a check in the HH member’s checkbox) that appear to need a WREG panel. The worker will still be able to choose which HH member to have a WREG panel or not.
4.	The worker will have drop down options to reflect the coding on the WREG panel
5.	The script will provide logic that will ensure that the WREG & ABAWD codes are compatible, and will inform the worker if they are not.
6.	The error rate will drop :)

**Comment by theVKC** [comment]
Like the mic at the end of that idea. It's yours.

**Comment by theVKC** [comment]
Closing because this is sort-of duplicated from the ABAWD checker from @CDPotter and @RobertFewins-Kalb. Can re-evaluate if we decide to add actions (like updating WREG).
