### ISSUE TITLE
DHS-5181

### ISSUE THREAD

**Issue by theVKC** [MN-Script-Team/DHS-MAXIS-Scripts#76]
We would like to be able to fill out Maxis Stat panels and case note 5181 information.

The requester sent me a sample, and I've begun working on it. Hoping for release in time for the beta testing this month.

**Comment by theVKC** [comment]
My very talented Hennepin counterpart @IlseFerris has volunteered to take this on (pending supervisor approval). Woot woot!

**Comment by IlseFerris** [comment]
I got the a-ok from Ann to work on this whenever we get around to it ☺

**Comment by theVKC** [comment]
What what? :) 

I may have started a dialog for this. I'll see if I can send you what I have.

**Comment by IlseFerris** [comment]
Awesome!

Say, are you working at Anoka on Friday?  I have the 2 Lectora training workbooks with me.  They were in my training materials, and I forgot to grab them out and leave them at Anoka.  I was hoping you could take them with you on Thursday.  Ehhh?

Also remember how we get to work together a bunch starting Thursday?!  I’m super excited!

**Comment by IlseFerris** [comment]
Can I get the dialog you started on this one?  It doesn't need to be today.  Thanks!

**Comment by theVKC** [comment]
@IlseFerris committed this earlier, and I tweaked the logic for the dialog. Go team!
