### ISSUE TITLE
Transfer case script (within county

### ISSUE THREAD

**Issue by CDPotter** [MN-Script-Team/DHS-MAXIS-Scripts#763]
Had a few comments to add an EMER type to the program selection and generalize the units to transfer from just Adult and Family as that distinction is pretty localized to Anoka. Will be working on this one.

**Comment by theVKC** [comment]
Can you expand on "generalize the units"? I'm just a bit confused about what that means.

**Comment by CDPotter** [comment]
Right now it only says Adult and Family as options to transfer the case to. Since other agencies may have different units or locations they want to transfer cases to adding a combo box will allow them to pick from Adult, family, grh, cash, LTC, or enter whatever unit title they want. It'll allow more flexibility for structure changes in the future if needed.

**Comment by theVKC** [comment]
I see. That sounds much better!

**Comment by theVKC** [comment]
Resolved by #767.
