### ISSUE TITLE
All scripts: need to update FuncLib block again...

### ISSUE THREAD

**Issue by theVKC** [MN-Script-Team/DHS-MAXIS-Scripts#769]
so this is minor, but affects EVERYTHING.

This part of the FuncLib block...
`IF default_directory = "C:\DHS-MAXIS-Scripts\Script Files\" THEN`

...should look like this...
`IF default_directory = "C:\DHS-MAXIS-Scripts\Script Files\" OR default_directory = "" THEN`

...because that way, if you are a scriptwriter, it will use the master branch. Scriptwriters tend not to have a default_directory variable while they're working.

I'm deciding to add this to Doubtfire, because it will affect everything. @IlseFerris, do you still want Doubtfire? If not, I'm going to need to take it and get this done reasonably soon...

**Comment by IlseFerris** [comment]
I should be able to work on Doubtfire a bit tomorrow, and next week.  I still got this!

**Comment by theVKC** [comment]
Resolved by #1003.
