### ISSUE TITLE
Sponsor Income UI FIAT

### ISSUE THREAD

**Issue by theVKC** [MN-Script-Team/DHS-MAXIS-Scripts#77]
For the purpose of MA when sponsor have provided income to be deemed to Sponsored LPR'S and need to be fiated as unearned income for sponsored LPR'S when applicable. 

If a worker create a spreadsheet like the one attached, the income in the column Total income to be deemed could be fiated into unearned income for applicable sponsored LPR'S. 
as stated in the HC FIAT workaround list 0712.doc

**Comment by theVKC** [comment]
Closed due to lack of interest.

**Comment by RobertFewins-Kalb** [comment]
#radioshack
