### ISSUE TITLE
MFIP transitioning to SNAP case note

### ISSUE THREAD

**Issue by IlseFerris** [MN-Script-Team/DHS-MAXIS-Scripts#773]
Hennepin county family worker suggested this. Is this an area that is error prone/used enough to warrant this?  Thanks team!

**Comment by courtrightd** [comment]
The reply I got from MFIP folks is this:
Currently, when I do this I use a Closed Program case note and a Approved Program Case Note, which works fine. Having one case note that says both things might be convenient, but I don’t think it would improve performance. It IS a very error prone area, but not in a way that I think can be fixed w a case note script. ((Basically people do it too often, when we do not have everything called for by policy)).

So maybe it would be helpful if you had mandatory fields to note that all requirements were met, but that would of course be taking place after the approval.

**Comment by IlseFerris** [comment]
Good deal.  Do you want this one?

**Comment by courtrightd** [comment]
I can take it, but it would be quite a while before I can work on it, I have other people making decisions on my priorities now.

**Comment by IlseFerris** [comment]
Gross!  Well let's keep it out there, and maybe someone can take this one for the team.  If not, maybe we can tackle it together at a later date, SNAP E & T leter style.

**Comment by courtrightd** [comment]
This is coming along nicely, but I would like it to add language to the notice.  Per DHS 4412, "include comment on notice that household only needs to contact the agency to decline FS benefits"  I assume this would go on the SNAP approval notice and not the MFIP closure?  Any official wording to be used?
@theVKC  @ruthmaloney

**Comment by ruthmaloney** [comment]
I understand it to be that the comment goes on the SNAP eligibility notice and wording could be as simple as “If you would like to decline food benefits, please contact our office.”

Ruth Maloney

**Comment by theVKC** [comment]
@courtrightd can I bump this? How we doin'?

**Comment by courtrightd** [comment]
This is really close to done, I’ve just been slammed with my normal job duties.  Coming very soon.

**Comment by theVKC** [comment]
@courtrightd is amazing. Thank you!
