### ISSUE TITLE
PA verif request being built wrong? 

### ISSUE THREAD

**Issue by CDPotter** [MN-Script-Team/DHS-MAXIS-Scripts#779]
From SIR discussion board:

"We've found that script is pulling over the housing allowance $110 into the Food Portion of verification form and the SNAP portion into the Cash area. Perhaps with the new housing grant identified as grant amount - it is pulling the 1st identified items from MAXIS. Creates incorrect PA Verification amounts"

I'm not too familiar with MFIP but does anyone with MFIP cases mind taking a look at this?

**Comment by courtrightd** [comment]
I’ll take it, it’s my script and I probably should have noticed it when I was making other fixes to it recently.

**Comment by CDPotter** [comment]
Thanks David! I'll let them know on SIR.

**Comment by courtrightd** [comment]
I just pull requested the fix into master, @theVKC how do you want this handled for beta / release, as I built onto the previous enhanced version that is currently in Beta?

**Comment by theVKC** [comment]
Well, release was yesterday, so anything that was in BETA last week is already released, so... yay!

I have it in master now. If you feel this bug warrants immediate attention, create a separate pull request into release. The BETA branch will be updated tomorrow once I get an update to NOTES - MAIN MENU from @RobertFewins-Kalb.

**Comment by courtrightd** [comment]
I’ll create a pull into release this morning when I get a chance, pardon my lack of brain function.

**Comment by courtrightd** [comment]
This has been resolved and can be closed.
