### ISSUE TITLE
RETRO HC FIATer

### ISSUE THREAD

**Issue by theVKC** [MN-Script-Team/DHS-MAXIS-Scripts#78]
@lpshanley, I know you were working on it, and I know that Hennepin has been playing with it. Is SLC using it already? Any known issues? Think we could release to the beta counties for more testing?

**Comment by lpshanley** [comment]
@courtrightd Any word on the testing? This should be ready for launch I haven't heard anything back on this yet... I can only fix it if i know its broken!!

**Comment by RobertFewins-Kalb** [comment]
Going through for the sake of house cleaning. What is the status of this script?

**Comment by courtrightd** [comment]
I don’t see myself working on it anytime soon, I barely touch HC cases anymore and don’t trust myself to judge its accuracy / usability.  There is a mostly done old version here if someone else wanted to take it on, or just close it for now and we can throw up a new issue if we revisit it in the future.

**Comment by theVKC** [comment]
Closing for now. We can reopen it if needed.
