### ISSUE TITLE
LTC burial asset script

### ISSUE THREAD

**Issue by CDPotter** [MN-Script-Team/DHS-MAXIS-Scripts#792]
Had a worker here at Anoka suggest that we add some check and balance system to prevent people from accidentally not leaving the burial agreement type as NONE when they don't notice that it is a field. Worker had completed everything except that box and lost a lot of data because he missed the box. 

Thoughts?

**Comment by IlseFerris** [comment]
Thanks Charles!  Do you want to clean up some of the old functions too while you're in there.  Cancel_confirmation is one that stands out from the get go.

**Comment by CDPotter** [comment]
Sure I can close my current pull and fix some of them.
