### ISSUE TITLE
CRITICAL BUG for NOTES - SNAP CASE REVIEW

### ISSUE THREAD

**Issue by IlseFerris** [MN-Script-Team/DHS-MAXIS-Scripts#804]
CRITICAL BUG FIX #803 (pull request)

"call" was missing from check_for_MAXIS function.  Fixed and tested.

**Comment by theVKC** [comment]
Fixed on master and release. I created a second pull request for the release branch. Not fixing on beta, because it's on master and I'm going to do a beta push tonight (didn't do it yesterday as I was anticipating possible changes thanks to our other scriptwriters who couldn't attend hackathon).
