### ISSUE TITLE
MTAF Case Note Script

### ISSUE THREAD

**Issue by theVKC** [MN-Script-Team/DHS-MAXIS-Scripts#81]
A family cash worker asked if there was a possibilty of getting a script for case noting when they receive a MTAF (MN Transition Application Form). 
*Note- I have no idea about this because I personally don't work with DWP* 

---

I asked the requester, who suggested this:

Date MTAF recd: 
First month of MFIP/WB: 
Household Composition: 
Earned Income: 
Unearned Income: 
Referral to Employment services date: 
Signature:

**Comment by RobertFewins-Kalb** [comment]
What is the status of this script idea? In the interest of cleaning up our mess, I would say that we can close this unless we hear from the script writer in question.

Alternatively, how urgent is this? It sounds like a basic C/N template that would only require utilizing existing custom functions.

**Comment by theVKC** [comment]
I get asked for this on a weekly basis. I think someone should take it.

**Comment by IlseFerris** [comment]
I've got this

**Comment by theVKC** [comment]
@LaLarson and @IlseFerris are tag-teaming this.

**Comment by IlseFerris** [comment]
@LaLarson can you commit what she has so that you get credit for you work.  I should be able to take over this at some point.
