### ISSUE TITLE
Update FAQ on SIR:  workers do not need to update power pads at script release

### ISSUE THREAD

**Issue by IlseFerris** [MN-Script-Team/DHS-MAXIS-Scripts#831]
It's a common misconception that workers need to update their power pad whenever new scripts are added or an enhancement is made.  Could this be added to the FAQ's on SIR when the SIR issues get resolved?  Thanks @theVKC!

**Comment by theVKC** [comment]
I'm closing this because it isn't a SCRIPTS issue, per se, but a SIR issue (and is on my SIR to-do list already, but superseded by other issues).

**Comment by IlseFerris** [comment]
Works for me, as long I don't have to remember it any more.

**Comment by theVKC** [comment]
:)


Caution: This e-mail and attached documents, if any, may contain information that is protected by state or federal law. E-mail containing private or protected information should not be sent over a public (nonsecure) Internet unless it is encrypted pursuant to DHS standards. This e-mail should be forwarded only on a strictly need-to-know basis. If you are not the intended recipient, please: (1) notify the sender immediately, (2) do not forward the message, (3) do not print the message and (4) erase the message from your system.
