### ISSUE TITLE
MFIP sanction/DWP disqualification enhancement

### ISSUE THREAD

**Issue by IlseFerris** [MN-Script-Team/DHS-MAXIS-Scripts#832]
1. Hennepin worker has requested a field for the ES worker name and contact info.  

2. Another worker has requested that the type of sanction be added into header.

Thoughts from family workers? @LaLarson @courtrightd @lpshanley

**Comment by IlseFerris** [comment]
@courtrightd thanks for offering to take this one!

**Comment by theVKC** [comment]
@IlseFerris, is this no longer a call for input? If @courtrightd is doing it, I'd like to update the header and add tags.

**Comment by IlseFerris** [comment]
Updated the header

**Comment by theVKC** [comment]
Are you working this one, @IlseFerris? Or are you, @courtrightd?

**Comment by IlseFerris** [comment]
@courtrightd has got our back on this one.  For some reason when I posted this issue (and a few others), it duplicated the issue.  David agreed to take it on the duplicate issue I closed.  Although good time to say thanks again David!

**Comment by IlseFerris** [comment]
Whoops, almost closed that one too.  Calm down Ferris!

**Comment by theVKC** [comment]
@courtrightd, any word on this one?

**Comment by courtrightd** [comment]
Will be coming soon (next week?) This is in a group of family cash scripts that I am currently polishing / testing to utilize the new database function.
