### ISSUE TITLE
MFIP sanction/DWP disqualification enhancement--call for input

### ISSUE THREAD

**Issue by IlseFerris** [MN-Script-Team/DHS-MAXIS-Scripts#833]
1. Hennepin worker has requested a field for the ES worker name and contact info.  

2. Another worker has requested that the type of sanction be added into header.

Thoughts from family workers? @LaLarson @courtrightd @lpshanley

**Comment by courtrightd** [comment]
Both of these make sense and are easy enough.  This can be assigned to me if wanted, as I will be updating this script eventually anyway.
