### ISSUE TITLE
TPQY to case note RSDI/SSI info & redacting IRS data

### ISSUE THREAD

**Issue by IlseFerris** [MN-Script-Team/DHS-MAXIS-Scripts#844]
Looking through old instructions I found that a version was in the works at some point.  Have we abandoned this enhancement?

“TPQY RESPONSE RECEIVED FROM SSA” 
This navigates to INFC/SVES/TPQY when a TPQY response has been received. It doesn’t take any further action at this time, it simply navigates you to the TPQY response. 

Note: in the past this script also case noted the information from the TPQY, but this functionality was removed recently due to IRS data handling guidelines. A version will be created at some point that redacts the required sections.

**Comment by theVKC** [comment]
This was actually nixed by policy folks a bit ago, @IlseFerris... we should probably just update the reference to remove this text entirely...

**Comment by IlseFerris** [comment]
Sounds like a plan to me.  Also love the "wontfix" label.  I haven't noticed it until now.
