### ISSUE TITLE
PAYSTUBS RECEIVED not quite working

### ISSUE THREAD

**Issue by courtrightd** [MN-Script-Team/DHS-MAXIS-Scripts#845]
It hangs up after updating the retro side of the panel and seems to get stuck in a loop, no error message.  I saved the new version locally and it works perfectly when run directly or through "Agency Custom."  
This may be specific to Saint Louis County, but I haven't modified the actions redirect, so not sure where issue would come from.

**Comment by IlseFerris** [comment]
I tested it too, same issue updating the retro side

**Comment by RobertFewins-Kalb** [comment]
Ugh! I did not have these problems in testing. 

Can somebody email me the case number that was being used when this was discovered?

robert.kalb@co.anoka.mn.us

**Comment by RobertFewins-Kalb** [comment]
Looking into it

**Comment by RobertFewins-Kalb** [comment]
I are confused. When I copy the script and run it locally, it works just fine. When I run the script through GitHub, the script seems to be hung up on EMWriteScreen 'ing on the retro side.

**Comment by theVKC** [comment]
So, I reverted the beta version to match release, meaning it no longer contains these changes. Now, only the master version has the issue.

@RobertFewins-Kalb was working on this, and I'm hoping to take a crack at it later today.

**Comment by IlseFerris** [comment]
2 issues were reported on SIR yesterday.  @RobertFewins-Kalb, what's the status?

**Comment by RobertFewins-Kalb** [comment]
The error still does not make sense. I will copy the script to run it from my personal repo to test.

**Comment by RobertFewins-Kalb** [comment]
Fixed
