### ISSUE TITLE
WCOM for duplicate assistance notice text

### ISSUE THREAD

**Issue by theVKC** [MN-Script-Team/DHS-MAXIS-Scripts#85]
MAXIS does not generate correct notice text in some instances involving duplicate assistance. The idea has been floated to create a script to do this. We're doing more research on the WCOM specifics now, and will create a new script when this info comes in.

Any takers?

**Comment by CDPotter** [comment]
Any news on the verbiage for this?

**Comment by theVKC** [comment]
Not as far as I can see. Would you like to be "the taker" and I can ask about it?

**Comment by CDPotter** [comment]
Can do, we've built a few WCOM scripts here so we can use them as a base. A bit more background info into the when would this be used (I'm assuming it is for closures when we learn someone is receiving duplicate assistance?) and some verbiage would be fantastic!

**Comment by theVKC** [comment]
Assigned to @CDPotter. :)
