### ISSUE TITLE
CSR Note script dialog box fields not showing unless you tab through them or hover over them with your mouse.

### ISSUE THREAD

**Issue by Jmallen9** [MN-Script-Team/DHS-MAXIS-Scripts#860]

**Comment by theVKC** [comment]
Hi! I'm guessing you are using the beta scripts? I am not sure which county you're with (you look like you're new here, so welcome and thank you!)

We just installed some new functionality to the notes button that could be causing this. @RobertFewins-Kalb, any ideas? Or maybe @IlseFerris, did you say you added a second dialog to it? Perhaps we've hit the six dialog limit for the CSR script? We may need to temporarily fix this by removing less necessary panels, or if @RobertFewins-Kalb is so inclined he can adapt his function-based-dynamic-dialog-creation skillz to this.

**Comment by RobertFewins-Kalb** [comment]
I'll take this

**Comment by RobertFewins-Kalb** [comment]
@Jmallen9 , could you provide more details -- case number, screenshots? NOTES - CSR only includes 2 dialogs and the NOTES MAIN MENU only builds 1...

I did find an issue with the new NOTES MAIN MENU (creating issue and submitting pull request)

**Comment by IlseFerris** [comment]
Sorry, this wasn't me this time.  I haven't been near the CSR lately.  Good on you, @RobertFewins-Kalb, get that bug!  (Can you tell I made really strong coffee this morning?)

**Comment by Jmallen9** [comment]
Attached is a screenshot of what we are seeing when using the CSR script.  The screenshot is taken of the CSR dialog box.

This is happening for all cases when accessing this Script.   Let me  know if you need any more details.

Jeremy Allen
Interim Financial Assistance Supervisor
Minnesota Prairie County Alliance
22 6 ST EAST,DEPT 401
Mantorville, MN 55955
Phone: 507-923-2937
Fax: 507-635-6186

The content of this email (including any attachments) is strictly confidential. If you are not,
or believe you may not be, the intended recipient, please advise the sender immediately by
return email, delete this email and destroy any copies

**Comment by RobertFewins-Kalb** [comment]
Sorry, I am not seeing a screen shot. You can email me directly...sometimes the forum is difficult.

robert.kalb@co.anoka.mn.us

**Comment by theVKC** [comment]
Removed critical tag. I sent a followup email with different ideas. Because the script still appears to be functioning, I think I added "critical" too quickly.

**Comment by theVKC** [comment]
Also, removing help wanted tag for now, as I'm waiting on an email from @Jmallen9 before deciding next steps.

**Comment by theVKC** [comment]
This is resolved by #1002's fix.
