### ISSUE TITLE
CRITICAL BUG---BULK ADDR script

### ISSUE THREAD

**Issue by IlseFerris** [MN-Script-Team/DHS-MAXIS-Scripts#862]
issue reported on SIR...
I was trying to use the BULK SCRIPT: ADDR, the instruction is to enter the X1 number of the case load, I entered my number X177201, it bring a blank spreadsheet with Titles of
Worker Number- case Number- applicant name- Address Line 1- Address Line 2 - City- State- Zip Code, but there is no information of my caseload, and the BlueZone Script Host: MSgBox show sucess!!.
Could you please let me know if there is any problem with the script?
 
Here's what looks like could use some work:
1.  Logic to have a worker number or entire agency run
2. X # being entered may be the wrong variable

**Comment by IlseFerris** [comment]
Also I'm working on this

**Comment by theVKC** [comment]
Resolved by #863.
