### ISSUE TITLE
Enhancement to NOTES - Good Cause Claimed

### ISSUE THREAD

**Issue by GayS** [MN-Script-Team/DHS-MAXIS-Scripts#866]
I am working on adding the panel updates that are needed.

**Comment by theVKC** [comment]
Can you sum up what updates you made?

**Comment by theVKC** [comment]
*or are making

**Comment by GayS** [comment]
I will work on adding in the STAT ABPS updates so that the script is more than "just a" case note. :)

**Comment by theVKC** [comment]
@GayS, can you give me an update on this one?

**Comment by GayS** [comment]
Hi – this is still on my “to do” list.

**Comment by theVKC** [comment]
@GayS, I know you have soooooo much time, but wondering if I can get an update?

**Comment by GayS** [comment]
If you want to close this you can.  The script works as a case note, we want to take it to the next level but it isn’t a priority at the moment. ☺

**Comment by theVKC** [comment]
Will close for now. We can reopen it at any time.

**Comment by GayS** [comment]
Thanks!
