### ISSUE TITLE
BULK - MA-EPD/MEDI list errors in navigating to MMIS.

### ISSUE THREAD

**Issue by theVKC** [MN-Script-Team/DHS-MAXIS-Scripts#868]
navigating to MMIS... error prone because it's looking for C402, et. al, and not using the better EMSearch functionality that I believe I put into FuncLib some time ago. @RobertFewins-Kalb, can you look into this for me? If you can't find my functionality in FuncLib or possibly in my "MAXIS to MMIS" script, try looking for RECIPIENT FILE APPLICATION and using that as your function.

**Comment by RobertFewins-Kalb** [comment]
I think I just need to update the logic in the custom function to navigate to MMIS...

Instead of writing C302 or C402, it should be writing ("C3" & worker_county_code) or ("C4"  & worker_county_code) but I'm not entirely sure how to test before pulling a change...

**Comment by Y-Lor-Y** [comment]
If you can give me access to the script, I can test it for you.  I have MA-EPD cases that I can run this through to see if it's functioning.

**Comment by RobertFewins-Kalb** [comment]
I'll submit a fix today. The script is in GitHub, in with the BULK scripts...

**Comment by Y-Lor-Y** [comment]
Ah, found it.  I was looking for BULK - MA-EPD, but it's under BULK - FINDING MA-EPD.

**Comment by RobertFewins-Kalb** [comment]
As it happens, there's an issue with the MAXIS to MMIS and MMIS to MAXIS navigation functions...

I'm thinking about having the script just run in one window. Thoughts...?

**Comment by Y-Lor-Y** [comment]
I'm fine with that.  I'm not sure about other counties, but here at RC, worker has about 2 screens, so depending on the worker preferences, they may have it on the other screen/session from their production Maxis screen.  If we're to do that, maybe a text message informing them to open it on the same window/session would be good, too?  What you think?

**Comment by RobertFewins-Kalb** [comment]
I think I have found the solution. Methinks the script was trying to navigate back to MAXIS too quickly. I think an EMWaitReady has fixed the problem. Testing the solution.

**Comment by Y-Lor-Y** [comment]
Let me know if you need me to run it after you've made the changes.

**Comment by RobertFewins-Kalb** [comment]
You will need to run this as you normally would, first executing the text in your global variables file, then executing the FuncLib, then executing the script (because of the variable "worker_county_code")...

https://raw.githubusercontent.com/RobertFewins-Kalb/DHS-MAXIS-Scripts/patch-28/Script%20Files/BULK/BULK%20-%20FIND%20MAEPD%20MEDI%20CEI.vbs

**Comment by RobertFewins-Kalb** [comment]
Fix submitted #979

**Comment by Y-Lor-Y** [comment]
My understanding is, at the end result I'm suppose to end up with a list of clients & cases that are eligible for reimbursement status.  The script itself ran fine, but I have no list.  It kept deleting the listing as it goes through them after it went from MMIS back to MAXIS, and as MAXIS runs each cases from the spreadsheet, it deleted/removed the case/client. I did not see it jotting down the reimbursement amount, too.  Maybe I'm not doing something right?

**Comment by RobertFewins-Kalb** [comment]
You don't have any clients on MA-EPD eligible for Medicare Part B reimbursement...

**Comment by RobertFewins-Kalb** [comment]
It's supposed to be deleting records that are not relevant.

**Comment by Y-Lor-Y** [comment]
Thanks for the clarification on function.
