### ISSUE TITLE
update verifs requested script to call_for_MAXIS(False)

### ISSUE THREAD

**Issue by IlseFerris** [MN-Script-Team/DHS-MAXIS-Scripts#883]
Currently set to true.  Maybe this should also be a larger project to replace this in other scripts, or just to simply update the function, and then update the scripts.  Thoughts @theVKC ?

**Comment by theVKC** [comment]
Well, I like the idea in some scripts, but in others I want it set to True because I want it to cancel out. A good example of this is navigation, or other scripts before the user has entered info. You can feel free to update it now if you so desire, though. :)
