### ISSUE TITLE
PND2 report not adding correctly...?

### ISSUE THREAD

**Issue by RobertFewins-Kalb** [MN-Script-Team/DHS-MAXIS-Scripts#884]
An Anoka supervisor sent this screen shot asking why the BULK PND2 list gen script is not adding case counts... I can investigate...

![image](https://cloud.githubusercontent.com/assets/7842016/8832904/3c2c38a4-3071-11e5-8675-a6d38be42537.png)

**Comment by IlseFerris** [comment]
I also got this from a Hennepin County supervisor:
The PND2 Bulk report is missing the totals of the cases over the 30/45 days, Colum “K” this is super helpful.  How do I get that back?

**Comment by theVKC** [comment]
@RobertFewins-Kalb, good luck with your investigation.

**Comment by TRISOR** [comment]
The is_not_blank_excel_string is not being correctly evaluated and put in the formula on the Excel spreadsheet.  For example, on SNAP the formula is =COUNTIFS(E:E, ">30",F:F, ).  There is nothing after the 2nd criteria which is column F:F)

**Comment by TRISOR** [comment]
I couldn't find where the "is_not_blank_excel_string" is defined but I think it should be replaced with ""<>"" or "<>".  I can't test to know which would work.  because the formula should be  =COUNTIFS(E:E, ">30",F:F,"<>" ).

**Comment by RobertFewins-Kalb** [comment]
Found it! Thank you, @TRISOR !!
