### ISSUE TITLE
Addendum Script

### ISSUE THREAD

**Issue by theVKC** [MN-Script-Team/DHS-MAXIS-Scripts#89]
A script to case note when you get an Addendum. Like when a new born is added to the case or father of children move into HH, just for a couple examples. 
The script could include a lot of the same things that the new CAF script has, as the addendum basically asked the same thing as the CAF, but just about the person being added.

**Comment by theVKC** [comment]
@IlseFerris, this is the original issue for the one you just referenced. Do you want it?

**Comment by IlseFerris** [comment]
I could do that.  Thanks as always @theVKC

**Comment by theVKC** [comment]
Assigned to @RobertFewins-Kalb because he's going to be working on another CAF addition. Go Robert! :)

**Comment by theVKC** [comment]
Also, @RobertFewins-Kalb: this is now just a drop-down addition in the first dialog which alters the header to say "CAF addendum received" instead of whatever it currently says.
