### ISSUE TITLE
1503 overwriting current FACI

### ISSUE THREAD

**Issue by IlseFerris** [MN-Script-Team/DHS-MAXIS-Scripts#895]
I'm on this

**Comment by theVKC** [comment]
@IlseFerris, did you test this issue? I'm a bit unclear of exactly what instances the problem is occurring. Any insight?

**Comment by IlseFerris** [comment]
Yes, I tested it, and it should be working. From what was reported, script was writing over the current FACI panel.  I updated the logic to not overwrite the current FACI panel, and also added logic in case there are already 5 FACI panels.  It msgbox's the worker instructing them to delete the appropriate FACI panel, and stops the script.

**Comment by theVKC** [comment]
Good deal. :)
