### ISSUE TITLE
Denied programs

### ISSUE THREAD

**Issue by CDPotter** [MN-Script-Team/DHS-MAXIS-Scripts#899]
A worker reported and I was able to replicate an error at 1, 1 for wrong number of arguments in "write_bullet_and_variable_in_case_note" it seems like it has something to do with the write_editbox_in_case_note redirect in funclib. Has anyone been working on this recently?

**Comment by CDPotter** [comment]
@IlseFerris I know you were working on Doubtfire but have you done anything with Denied programs that's been tested but not submitted?

**Comment by RobertFewins-Kalb** [comment]
It's right here...

![image](https://cloud.githubusercontent.com/assets/7842016/8876482/a377037a-31e5-11e5-91e0-9b459be511f8.png)

**Comment by courtrightd** [comment]
I just pulled in an update to denied progs, and I replaced all the write_editbox_in_case_notes while I was in there, but it is just in MASTER at this point.

**Comment by CDPotter** [comment]
@courtrightd I did see that, are you able to run it fine without errors? Both @mldietz and I have been unable to. If it's only on master branch that's good since it won't be widespread.

**Comment by courtrightd** [comment]
I must have just missed it when testing, I’ll fix those two lines quick and submit a pull

**Comment by IlseFerris** [comment]
Nothing has been pulled yet from Operation Doubtfire.  Legit question though.

**Comment by theVKC** [comment]
Resolved with #900.
