### ISSUE TITLE
Bug-HH comp change

### ISSUE THREAD

**Issue by RoyStearns** [MN-Script-Team/DHS-MAXIS-Scripts#904]
When using the Household comp change script- you have to manually enter the case number and worker signature, then after you have entered all your info and press OK- it will take you back to self, put in CASE and NOTE but for some reason blanks out the case number and does not go into case notes.

**Comment by theVKC** [comment]
Have you looked at the `case_number` variable? Is it called `case_number` or maybe `MAXIS_case_number`?

**Comment by CDPotter** [comment]
I'll look into it.
