### ISSUE TITLE
Enhancement - Fraud Info

### ISSUE THREAD

**Issue by RoyStearns** [MN-Script-Team/DHS-MAXIS-Scripts#905]
Had a request to make some changes to Fraud script. They asked for 2 things
1) Add "TBD" to the Overpayment line where YES and NO currently are. Sometimes they case note the fraud findings but have yet to determine an OP.
2) Move the "Findings" spot to the bottom of the case note. They copy/paste in lengthy fraud findings and since the script text box does not support "carriage returns" they are unable to paste the notes in and have it follow the provided format.

**Comment by theVKC** [comment]
Well... the script does actually support carriage returns when entered with a semicolon. Perhaps a note explaining that would help?

In any case, any interest in doing this one @RoyStearns?

**Comment by CDPotter** [comment]
I will take this. To sum up we want an combo box on the overpayment line so people can add what they need, and then something to inform people how to format carriage returns on a editbox?

**Comment by theVKC** [comment]
Agreed. And thank you!

**Comment by RoyStearns** [comment]
Thanks Charles. With our current workload I never seem to have time to get out here unless I am passing along a suggestion. :(

I think the reason that they were asking about moving the "findings" to the bottom is they will get a fraud finding emailed to them that is 3 pages long and it does not copy/paste in well and to get it to show up they would have to semicolon each line (which they are not going to do for 3 pages worth of notes). That way if it is at the bottom they can paste it in after the script has run.

If it is not possible it will have to do the way it is. I know we need to make it work for the most amount of people and somethings are just not possible.
