### ISSUE TITLE
LTC asset assessment note

### ISSUE THREAD

**Issue by CDPotter** [MN-Script-Team/DHS-MAXIS-Scripts#908]
Had a report of an error with this script. Seemed pretty minor. Worker had a section of his case note print like this(assets have been generalized):

        Assets Total:     22,575.01                  
*  Asset Description    Value     Owner  Cnt/Exc  Ver
* --------------------  --------- -----  -------  ---
* BANK CHECK   _____0.01   1       C      Y 
* HOUSE  _13200.00   1       E      Y 
*CAR  __9375.00   1       E      Y 
* BANK CHECK   _____0.01   1       C      Y 
* HOUSE  _13200.00   1       E      Y 
* CAR __9375.00   1       E      Y 
* BANK CHECK   _____0.01   1       C      Y 
* HOUSE  _13200.00   1       E      Y 
* CAR __9375.00   1       E      Y 
* BANK CHECK   _____0.01   1       C      Y 
* HOUSE  _13200.00   1       E      Y

When it should have just done:

*  Asset Description    Value     Owner  Cnt/Exc  Ver
* --------------------  --------- -----  -------  ---
* BANK CHECK   6230  _____0.01   1       C      Y 
* HOUSE  _13200.00   1       E      Y 
* CAR  __9375.00   1       E      Y

He just deleted the duplicated ones but I was unable to try to re-create the issue. I just wanted to throw it up here in case anyone else sees anything like this.

**Comment by theVKC** [comment]
I believe @IlseFerris made some changes to this recently. She may have some insights. Is it happening on every case, or just occasionally?

**Comment by CDPotter** [comment]
Just the once so far that's why it seems low priority to me.

**Comment by ALJ10** [comment]
I rec'd notice from a financial worker that this script is doing that every time she uses the Asset Assessment script. Thought I'd mention that in case it is still on someone's "to do" list.  I will just have the worker remove the duplicate assets as an interim solution. Thank you!

**Comment by theVKC** [comment]
@IlseFerris is on this one. Thank you!

**Comment by theVKC** [comment]
#707 contains this basic concept and more. I'm closing this issue as duplicate per @IlseFerris.
