### ISSUE TITLE
ACTIONS - Paystubs Received: Allow worker to enter more than 5 pay stubs

### ISSUE THREAD

**Issue by theVKC** [MN-Script-Team/DHS-MAXIS-Scripts#91]
Could this script be updated to allow the worker to enter more than 5 paystubs?  (Ex: you can enter up to 10 pay stubs on the PIC if you shift+PF7/8.) 
This would be really helpful if you have people that are paid weekly and/or have widely varying income.

Originally suggested by X164414

**Comment by RobertFewins-Kalb** [comment]
So I think the script is done and ready for testing. There is a problem with using more than 5 pay dates when you go enter the pay dates into the retrospective side of JOBS. I think a message box should pop up informing the worker they will need to clean up the case. 

If you go to case 212915 (training region), the retrospective side for MEMB 01's job with Mom's Friendly Robot Factory is missing the 06/29/15 pay date. The MsgBox should inform the worker they will need to consolidate pay dates to make it all fit in the JOBS panel.
