### ISSUE TITLE
MFIP sanction cured: needs rename

### ISSUE THREAD

**Issue by theVKC** [MN-Script-Team/DHS-MAXIS-Scripts#911]
@khiestand: when you pulled this, you didn't include "NOTES - " at the beginning of the file name. My bad: I should have caught that. Can you rename the file for me (I want you to get the credit for the new script, if I rename it, it'll look like I wrote it)?

**Comment by khiestand** [comment]
So you want me to re-pull it in right with the updated name?

**Comment by khiestand** [comment]
@theVKC I don't have the script saved locally, it is only on GitHub or on the training PC in Stearns Co.  I thought I did have the "NOTES -" on there when I look at my pull request?

**Comment by theVKC** [comment]
Doesn't look like it. All you have to do is navigate to the file in GitHub (https://github.com/MN-Script-Team/DHS-MAXIS-Scripts/blob/master/Script%20Files/NOTES/MFIP%20SANCTION%20CURED.vbs), click the pencil icon, change the name in the name field, and submit a pull request at the bottom. That should do the trick.

**Comment by theVKC** [comment]
Resolved by #916. Thanks @khiestand! #rockstar
