### ISSUE TITLE
NOTE - Pregnancy Reported

### ISSUE THREAD

**Issue by khiestand** [MN-Script-Team/DHS-MAXIS-Scripts#912]
Hi,

I have written a new script this morning called "Pregnancy Reported."  This script will case note the following details:
HH Member Pregnant, Due Date, Conception Date, How the Pregnancy was reported, other comments/notes, Program/s pregnancy reported for, if MMIS was updated, and if verification request for cash was sent. 
The script will also update the stat/preg panel for the member that is pregnant.

Please assign this issue to me, thanks!

**Comment by theVKC** [comment]
Say, I haven't wrapped the BETA release yet! If you want this included, can you pull it in? Or will you need a bit more time? Either way, way to go @khiestand! :)

**Comment by khiestand** [comment]
@theVKC I am working on it with Robert, have a couple of things to clean up on it.  When would you need it by?

**Comment by RobertFewins-Kalb** [comment]
If you intend to have it ready today, please let me know so I can update the NOTES main menu

**Comment by khiestand** [comment]
@RobertFewins-Kalb @theVKC 
I think I have done all that I can do on it.  Might need more experienced scriptwriters to take a peek just to be sure.  If either of you think you will have time today, then great, if not, I can definitely go on the next release.  Thoughts?

**Comment by RobertFewins-Kalb** [comment]
email me

I will update the main menu
