### ISSUE TITLE
LTC transfer penalty bug

### ISSUE THREAD

**Issue by IlseFerris** [MN-Script-Team/DHS-MAXIS-Scripts#917]
Because I was a noobs....
The cancel button doesn't actually cancel anything.  Sooo, I'm updating that, and adding some other stuff too.
This was reported on SIR.

**Comment by theVKC** [comment]
When do you think it'll be finished, @IlseFerris?

**Comment by IlseFerris** [comment]
I have one more thing to do.  I should have it out by tonight.

**Comment by IlseFerris** [comment]
resolved with #922 pull request
