### ISSUE TITLE
Notes main menu

### ISSUE THREAD

**Issue by CDPotter** [MN-Script-Team/DHS-MAXIS-Scripts#921]
Notes main menu buttons do not work. After opening the notes main menu I cannot navigate between letter sections nor can I open scripts that are already displayed on #-C

**Comment by RobertFewins-Kalb** [comment]
There's currently no NOTES - MAIN MENU in the BETA branch

**Comment by theVKC** [comment]
It is coming

**Comment by theVKC** [comment]
Resolved when I pulled changes to BETA. I believe (at least I hope) this was only affecting scriptwriters, and only for a few minutes.
