### ISSUE TITLE
Critical bug LTC renewal 

### ISSUE THREAD

**Issue by CDPotter** [MN-Script-Team/DHS-MAXIS-Scripts#927]
worker_sig variable is still in do/loop rather than newly change worker_signature

**Comment by IlseFerris** [comment]
Pretty sure that was me, sorry gang!

**Comment by theVKC** [comment]
@IlseFerris, hold the phone... can you confirm this is happening in release as well? If so, @CDPotter, can you pull this fix into release? I'll pull it into beta right now after I pull the other bug fixes.

**Comment by CDPotter** [comment]
Release still has worker_sig so it isn't an issue yet.

**Comment by theVKC** [comment]
Bingo.
