### ISSUE TITLE
Bug LTC MA Approval

### ISSUE THREAD

**Issue by CDPotter** [MN-Script-Team/DHS-MAXIS-Scripts#929]
From a worker here at Anoka:

I’ve also seen that the “LTC-MA approval” script is having issues as well.  After completing the case note I only get the following lines:

                **Approved EX-S for 07/15, $0 SISEW waiver obl**                             
* Income: $583.00                                                            
* Deductions: Maintenance needs allowance ($988.00). Health insurance premium
                                             ($63.30).                                                      

It doesn’t case note the rest of the case note and this box below pops up:

"Script error at line 1, col 1: Type Mismatch: 'write_variable_in_case_note'"

Also, it doesn’t take us to the correct footer month but I know that was an issue for a lot of other scripts a while back too.

**Comment by theVKC** [comment]
Nice fix, @CDPotter!
