### ISSUE TITLE
Paystubs received - not updating PIC 

### ISSUE THREAD

**Issue by courtrightd** [MN-Script-Team/DHS-MAXIS-Scripts#931]
Appears it is updating the date of calculation but not entering the paystub info in the PIC.

**Comment by RobertFewins-Kalb** [comment]
I wonder if there's an issue with writing the PIC info using a function?

**Comment by RobertFewins-Kalb** [comment]
It works just fine when I run it independent of GitHub. We were having a similar problem with the dynamic dialog building. I want to try replacing the call for PIC_paystubs_info_adder(pay_date, gross_amt, hours) with the 11 lines of code.

**Comment by theVKC** [comment]
@RobertFewins-Kalb, will you have time to do this today? Otherwise, I need to pull the plug on your update again...

**Comment by RobertFewins-Kalb** [comment]
I'm working on it.

**Comment by theVKC** [comment]
Alternatively: want to add your function to FuncLib?

**Comment by RobertFewins-Kalb** [comment]
There's no reason. It's 10 lines of code that is called once. The function made more sense before the multi-dimensional array when it was called 5 times.

**Comment by theVKC** [comment]
Gotcha. Proceed boldly and with stealth.

**Comment by RobertFewins-Kalb** [comment]
:)

**Comment by RobertFewins-Kalb** [comment]
I have it set up to run through my personal repo. Run locally? Nope. Simulating the GitHub experience in a controlled environment.

**Comment by RobertFewins-Kalb** [comment]
pull requests #935 and #936
