### ISSUE TITLE
Bills updater bug

### ISSUE THREAD

**Issue by CDPotter** [MN-Script-Team/DHS-MAXIS-Scripts#948]
We had a worker using the bills updater and reported to us that a few times she used it recently and has gotten a message box error stating "Enter a valid command or pf key". It looks like recently a function got added to the script. Robert and I are thinking that this function might not work the best. It calls for a variable named reference which isn't getting used in the script therefore would be entering a blank in the ref number field. Robert said he took it out of use in krabapple because each panel acts so differently in terms of being created if non-existent. It might be wise to regress this one pre-function.

**Comment by RobertFewins-Kalb** [comment]
I took the function out of Krabappel whenever I could. It doesn't work well. Here's an example of the error message box...

![image](https://cloud.githubusercontent.com/assets/7842016/9008296/d7e1f6e6-375e-11e5-8fee-597404c376c1.png)

**Comment by RobertFewins-Kalb** [comment]
My recommendation is that we strike create_panel_if_nonexistent from the record. I apologize for merging it from Krabappel.

**Comment by RobertFewins-Kalb** [comment]
Example of the problem...

![image](https://cloud.githubusercontent.com/assets/7842016/9008474/3ce57ab2-3760-11e5-8476-537442fe6755.png)

**Comment by IlseFerris** [comment]
I can take this, I should be free this afternoon to work on it.

**Comment by theVKC** [comment]
@IlseFerris, I believe you chose to add this function to BILS buddy...

**Comment by IlseFerris** [comment]
Did you not see my response 7 seconds before your comment?  Sheesh....
LOL!

**Comment by theVKC** [comment]
Look at us GitHub-ing at the same time. :)

**Comment by RobertFewins-Kalb** [comment]
Kids, you need to stop fighting or I will stop this car!

**Comment by IlseFerris** [comment]
GitHub as a verb...I can get behind that!  GitHub also should be like a social media site so I can like comments.  @RobertFewins-Kalb and @theVKC, consider you comments 'liked' by me.  

Back to business...should we update this function then?

**Comment by RobertFewins-Kalb** [comment]
@IlseFerris  don't you mean, The Github?

**Comment by IlseFerris** [comment]
LIKE!!!!

**Comment by CDPotter** [comment]
We think the easiest thing would be to remove it from this script and maybe scour others for it? It would be a big huge if/else mess to try to program for basically each panel.

**Comment by theVKC** [comment]
My vote: remove it from existence.

**Comment by RobertFewins-Kalb** [comment]
I second that

**Comment by IlseFerris** [comment]
I have added it to my list of functions to remove.  Thanks all!
