### ISSUE TITLE
Expedited screening enhancement

### ISSUE THREAD

**Issue by CDPotter** [MN-Script-Team/DHS-MAXIS-Scripts#953]
It was suggested that maybe instead of failing if the worker runs the script on an out of county case(since you can't case note) or invalid case number that the expedited results appear in a message box sort of like a calculator. 

The new start_a_blank_case_note function will infinitely loop is someone is unable to edit a case. 

Thoughts?

**Comment by theVKC** [comment]
If you want to make the change(s), be my guest. :)
