### ISSUE TITLE
New function idea:  change numeric date into text date for letters

### ISSUE THREAD

**Issue by GayS** [MN-Script-Team/DHS-MAXIS-Scripts#954]
idea for letters to clients - create function that will convert numeric date to text date.  ie:  7/30/15 would read "July 30, 2015", or 7/15 = "July 2015"

**Comment by RobertFewins-Kalb** [comment]
If you use MonthName(x) where "x" is a number from 1 through 12

Sent from my iPhone

On Jul 31, 2015, at 3:39 PM, Gay Sikkink <notifications@github.com<mailto:notifications@github.com>> wrote:


idea for letters to clients - create function that will convert numeric date to text date. ie: 7/30/15 would read "July 30, 2015", or 7/15 = "July 2015"

-
Reply to this email directly or view it on GitHub<https://github.com/MN-Script-Team/DHS-MAXIS-Scripts/issues/954>.



Click here<https://www.mailcontrol.com/sr/AvMHZU981+zGX2PQPOmvUlHUcPnZ!qyDO6cNkQP9caJKqHbSxMay6UHbxAGR!FmmGe43BsKT9nKZtQUzGWYsdQ==> to report this email as spam.


NOTICE: Unless restricted by law, email correspondence to and from Anoka County government offices may be public data subject to the Minnesota Data Practices Act and/or may be disclosed to third parties.

**Comment by GayS** [comment]
great - this can be closed out then.  - thanks
