### ISSUE TITLE
SNAP CASE REVIEW enhancement

### ISSUE THREAD

**Issue by IlseFerris** [MN-Script-Team/DHS-MAXIS-Scripts#955]
asked to add MFIP information such as;

MFIP case review complete & app'd for 08/15 of $804 MFIP grant
MFIP Cash - $108, MFIP Food - $596, Housing Grant - $110              
MFIP case has been reviewed, and the budget and issuance is correct.

**Comment by ruthmaloney** [comment]
I like it!

Ruth Maloney

**Comment by IlseFerris** [comment]
I'll take this one @theVKC
