### ISSUE TITLE
BULK case transfer in MAXIS

### ISSUE THREAD

**Issue by IlseFerris** [MN-Script-Team/DHS-MAXIS-Scripts#956]
I was approached by a Hennepin County supervisor requesting a BULK case transfer script that can do the following:
1.  Allow the user to select certain criteria within the cases (post 60 month MFIP cases, immigration codes, sanction cases, etc)
2. Allow the user to select one or multiple users to transfer the cases to, and vice versa. 
3. Create an Excel report of the cases transferred.

**Comment by RobertFewins-Kalb** [comment]
Oo oo oo gimme gimme gimme!

Sent from my iPhone

On Jul 31, 2015, at 4:20 PM, Ilse Ferris <notifications@github.com<mailto:notifications@github.com>> wrote:


I was approached by a Hennepin County supervisor requesting a BULK case transfer script that can do the following:
1. Allow the user to select certain criteria within the cases (post 60 month MFIP cases, immigration codes, sanction cases, etc)
2. Allow the user to select one or multiple users to transfer the cases to, and vice versa.
3. Create an Excel report of the cases transferred.

-
Reply to this email directly or view it on GitHub<https://github.com/MN-Script-Team/DHS-MAXIS-Scripts/issues/956>.



Click here<https://www.mailcontrol.com/sr/4o1r4Ry2cDPGX2PQPOmvUhBG2SIKse0TpKhdI6NSUEsNse070lPCMCwgp0J8xEXOGe43BsKT9nJue2rhFpgg0Q==> to report this email as spam.


NOTICE: Unless restricted by law, email correspondence to and from Anoka County government offices may be public data subject to the Minnesota Data Practices Act and/or may be disclosed to third parties.

**Comment by RobertFewins-Kalb** [comment]
Or... Monday Hackathon...?

**Comment by ruthmaloney** [comment]
Wish I would have had this when I was a supervisor. LOVE the idea!

Ruth Maloney

**Comment by theVKC** [comment]
Actually, this ties in to a thing I wanted to do in FuncLib. @RobertFewins-Kalb, would you mind if I took this one? If you already started I can let it slide.

**Comment by RobertFewins-Kalb** [comment]
Take away. I haven't started this.

**Comment by theVKC** [comment]
OK, I've removed this from my to-do, on advice of others, based on my upcoming schedule. Second chance at taking it! Could be a big one! @RobertFewins-Kalb? You had it before.

**Comment by theVKC** [comment]
If @RobertFewins-Kalb doesn't want it, I think anyone from the @MN-Script-Team/5k-club could do it.

**Comment by theVKC** [comment]
OK, I tagged this a week ago, and nobody has taken it. As such, I'm closing the issue due to lack of interest.

**Comment by C-Love** [comment]
@theVKC - I will take this. I will be able to get the dedicated time for it. Yay!!!

**Comment by theVKC** [comment]
Go @C-Love!
