### ISSUE TITLE
'informed client of recert period' checkbox added to CAF

### ISSUE THREAD

**Issue by IlseFerris** [MN-Script-Team/DHS-MAXIS-Scripts#957]

**Comment by devonne01** [comment]
Do you just want a check box added to the CAF that says that? If so, I can probably tackle that one. If it's more detailed let me know.. LOL

**Comment by IlseFerris** [comment]
That's the gist of it.

**Comment by IlseFerris** [comment]
Thanks @devonne01!

**Comment by devonne01** [comment]
Ok, I think I can handle that. ☺ Let’s hope anyways.

**Comment by theVKC** [comment]
You got it, @devonne01! I believe the last dialog has room to grow. If you run into problems in Dialog Editor, let me know!

**Comment by theVKC** [comment]
@devonne01, any update on this?

**Comment by devonne01** [comment]
HI Veronica

I was out yesterday with a horrible MIGRAINE. I have been attempting to work on it inbetween things I haven’t done it for a couple weeks and was hoping to work on it at the hackathon that was cancelled. When I first started working on it I was having issues with the dialogue editor and even had Kelly come in here and sit with me to see if there was something wrong I was doing but we couldn’t figure it out. I will try and work on it before next hackathon on the 28th that we will be attending ☺

**Comment by devonne01** [comment]
Hi.. I am trying to work on this script and I am getting a dialog editor box still. Not sure what I'm doing wrong?

**Comment by RobertFewins-Kalb** [comment]
Count the number of objects in the dialog. You may have hit 64. If you do, the dialog editor stops working.
