### ISSUE TITLE
MEMOS - Appointment letter: recertification wording

### ISSUE THREAD

**Issue by theVKC** [MN-Script-Team/DHS-MAXIS-Scripts#96]
Originally submitted by X121450:

If the appointment is in the office, they don’t need to send their forms in before the appointment. 
The memo says “Remember to send in your forms before the interview” regardless if you select phone or in office. 

Also for recertifications it should say "If we do not hear from you by 10/31/2014 your case will close" rather than the current wording which says we will deny your application. 

---

This wording should be evaluated by policy folks, but I'm adding to the issue list anyway for tracking purposes.

**Comment by theVKC** [comment]
Hey @ruthmaloney! This issue was brought up. Do you think it would be problematic if we said "If we do not hear from you before _____ _your case will close_" (instead of _we will deny your application_ as it currently says in SPEC/MEMO). This seems logical.

The other part ("remember to send in your forms before the interview" seems prescribed by POLI/TEMP (the NOMI section) if I'm not mistaken. If I am mistaken, please let me know (and thank you)! :)

**Comment by ruthmaloney** [comment]
Are you rewording the new app NOMI or the Recert NOMI?

Recerts should say "your case will auto-close". 

New apps should say "we will deny your application", because they don't have an open case, so shouldn't say your case will close.

**Comment by CDPotter** [comment]
@ruthmaloney this would be for editing the initial appointment letter that is sent to a client for both new app and recert.

**Comment by ruthmaloney** [comment]
Can it be different depending whether the worker selects new app or recert? I hate to say this, but if it has to be the same, I think someone from policy should probably look at it because there is so much scrutiny over our notices right now.

**Comment by theVKC** [comment]
This is the appointment letter, not the NOMI. The NOMI is system generated for non-recerts, and a SPEC/MEMO for recerts, but again this is the appointment letter.

I say we go with "your case will auto-close" for recert appointment letters and the existing "we will deny your application" for new apps. Thoughts?

**Comment by ruthmaloney** [comment]
Agreed

Ruth Maloney

**Comment by theVKC** [comment]
I'll take care of this one myself. @IlseFerris, care to update the language of the SPEC/MEMO for REVS scrubber to say "your case will auto-close" instead of "we will deny your application"?

**Comment by theVKC** [comment]
Nevermind, @IlseFerris, I've got this one for REVS scrubber.
