### ISSUE TITLE
LTC-Spousal Allocation FIATer script Issue

### ISSUE THREAD

**Issue by jasont35** [MN-Script-Team/DHS-MAXIS-Scripts#960]
Some of the Income Types on STAT/UNEA don't match the Income Types in ELIG/HC in the Spousal Allocation Gross Unearned Income section. 

Example: If STAT/UNEA has Income Type 17 Other Retirement and the spousal allocation FIATer script is ran the ELIG/HC Spousal Allocationn Gross Unearned Income section Income Type 17 is not Other Retirement, it is FC child Requesting FS.

**Comment by IlseFerris** [comment]
Thanks for reporting this.  I have started mapping this out a bit, and will take the issue. @theVKC, go ahead and assign this to me.

**Comment by theVKC** [comment]
You got it.
