### ISSUE TITLE
MNSure memo enhancement

### ISSUE THREAD

**Issue by RoyStearns** [MN-Script-Team/DHS-MAXIS-Scripts#961]
![img1](https://cloud.githubusercontent.com/assets/10159949/9066226/f0a57f5a-3a9b-11e5-9d22-c49410798888.png)
When doing a memo for Maxis to apply in Mnsure the script is only looking at the top location for a waiting memo (07, 071). So in this case if you are in any footer month other than 9/1/15 it will fail and say that there is no waiting wcom because the location 07, 071 is populated w PRINTED instead of WAITING as new notices always go to the bottom. Not sure if we want the script to navigate out to to CM+1 or to look at more locations than 07, 071??

**Comment by theVKC** [comment]
Why am I thinking @CDPotter did something on this?

**Comment by CDPotter** [comment]
I did indeed build a WCOM-er for MAGI renewal notices/case notes then @RobertFewins-Kalb and I beefed it up to become a WCOM-er menu for other HC scenarios searching for the correct waiting note. We can submit it for testing/review if you'd like?

**Comment by theVKC** [comment]
Two things:

1. If your script you built isn't live statewide, we should go to there and get it live. :)
2. This is an enhancement to a much earlier script which predates your work, I believe. Care to enhance this script to include your great work?

**Comment by CDPotter** [comment]
1. Ok I will submit a folder with our current builds in there. We are a little unsure about what is still valid wording and what isn't.

2. Well the way out WCOM script works is you enter a case number, approval month, and worker signature. Then it asks what type of WCOM do you want to print. It then brings up HH memb dialog and you can select if you need the WCOM on  multiple people's notices. Then it adds the WCOM and case notes. It might make more sense to pull the Mnsure referral into the menu system?

**Comment by CDPotter** [comment]
Ok while looking through our WCOM menu I found that many of the scripts were outdated and related to the MAGI income policies of last fall. As such there is really only one script we'd like to salvage and bring statewide and thats the MA-EPD no initial premium paid wcomer. According to POLI/TEMP TE 04/02 page 7 there is specific verbiage that goes into denying someone for no initial premium page. This script enters that verbiage.

**Comment by theVKC** [comment]
@CDPotter, can you create a new issue around your WCOM script before you resubmit it?
