### ISSUE TITLE
FSET sanction MEMO for closed SNAP cases

### ISSUE THREAD

**Issue by IlseFerris** [MN-Script-Team/DHS-MAXIS-Scripts#962]
Hennepin County worker requested "Is there a way to develop a script that would send a sanction notice for cases where the client failed to attend orientation but the case has since closed?
in this instance we need to impose the sanction if the client reapplies, say they failed to attend during the time the case was open."

@ruthmaloney can you shed some light on this request?  Is this kosher?

**Comment by theVKC** [comment]
Can I bump this a bit? @IlseFerris, @ruthmaloney?

**Comment by theVKC** [comment]
Per @IlseFerris , shutting it down.
