### ISSUE TITLE
NEW SCRIPT IDEA >>> BULK script for identifying panel update date on key panels

### ISSUE THREAD

**Issue by RobertFewins-Kalb** [MN-Script-Team/DHS-MAXIS-Scripts#975]
New script idea emerged today -- a BULK script that allows the user to select specific caseloads, identify specific panels to check, and a time period criteria to check.

The time period criteria would be something like...
* Identify panels that have been updated within the past 30 days.
* Identify panels that have been updated within the past 6 months (180 days).
* Identify panels that are active but have not been updated in 12 months or more (365 days).
* Identify panels that are active but have not been updated in 24 months or more (730 days).

The available panels would be those focused on income, expenses and deductions.

This script would not be designed to be a tool for financial workers, but instead a supervisory or review tool.

**Comment by RobertFewins-Kalb** [comment]
What luck! @CDPotter  and I have begun work on just such a script!!

**Comment by IlseFerris** [comment]
Your timing is impeccable then :)

**Comment by Farleight** [comment]
Done right, that actually could be a tool for workers to help verify mass changes went through properly (since, ya' know... they usually don't)... just sayin'.

**Comment by theVKC** [comment]
I assigned @CDPotter. If it's a joint effort, please try and cross-pull from a central branch, so as to assign credit to both of you. It may not be important to you, but it is to me and my superiors. :)
