### ISSUE TITLE
POLI/TEMP NAV bug

### ISSUE THREAD

**Issue by IlseFerris** [MN-Script-Team/DHS-MAXIS-Scripts#981]
If you select "INDEX OF TOPICS", script navigates you to POIL/TEMP - INDEX
If you select "TABLE OF CONTENTS", script navigates you to POLI/TEMP - INDEX

**Comment by theVKC** [comment]
Do you want it?

**Comment by IlseFerris** [comment]
I can take it, unless one of the newer scriptwriters wants to take a crack at it.

**Comment by Y-Lor-Y** [comment]
I've updated the script with drop list rather than radio.  I've tested it and it works to navigate to TEMP/INDEX and TEMP/TABLE.
