### ISSUE TITLE
Incarceration Notes Script

### ISSUE THREAD

**Issue by khiestand** [MN-Script-Team/DHS-MAXIS-Scripts#987]
I have an incarceration case noting script that I am working on.  Can you assign this issue to me?  Thanks!  Hoping to pull it in this week sometime.  Will case note details of incarceration and update STAT/FACI if necessary.

**Comment by theVKC** [comment]
Love it! Woot!

**Comment by theVKC** [comment]
@khiestand, can you update me on this?

**Comment by khiestand** [comment]
@theVKC, working on this this afternoon!

**Comment by khiestand** [comment]
This is complete, will be pull requesting to GitHub on 9/30/15.
