### ISSUE TITLE
FuncLib enchancement for autofilling SWRK panel

### ISSUE THREAD

**Issue by IlseFerris** [MN-Script-Team/DHS-MAXIS-Scripts#994]
call autofill_editbox_from_MAXIS(HH_member_array, "SWKR", SWKR) does not exist.  Would be nice if it did.

**Comment by theVKC** [comment]
Do you want to build this? Also, wrong repo. Can you re-enter in BZS-FuncLib?

**Comment by IlseFerris** [comment]
Yep and yep
