### ISSUE TITLE
New script - NOTES - ES REFERRAL

### ISSUE THREAD

**Issue by courtrightd** [MN-Script-Team/DHS-MAXIS-Scripts#997]
A case note template for use when referring someone to employment services. Includes fancy database - populated dropdowns for counties using the ES Database.  Currently in the project TPS REPORTS folder, I need to update for non-database counties and then move to main folder.

**Comment by theVKC** [comment]
"non-database counties" :( 

#IWishWeCouldGiveEveryoneTheTools

I presume you're taking this one. :)

**Comment by theVKC** [comment]
@courtrightd can I get an update?

**Comment by IlseFerris** [comment]
@courtrightd do you make an ES referral upon approval?  If so, could we add this to the approved programs scripts?

**Comment by courtrightd** [comment]
Almost ready to rock, in the same bunch that should be out next week.

**Comment by courtrightd** [comment]
ES referral is on approval with MFIP, but must be done before approval with DWP, so it makes sense to be standalone.

**Comment by theVKC** [comment]
@courtrightd, can I bump this topic? How you doin'?

**Comment by courtrightd** [comment]
Same response as the last – I’m working on it.   I’ll try to get a script day this week.
